nextcloud/spreed

- composer.json
- tests/php/Service/ProxyCacheMessageServiceTest.php
- tests/php/Signaling/ListenerTest.php
- tests/php/phpunit.xml
- vendor-bin/csfixer/composer.json
- vendor-bin/mozart/composer.json
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
> deps(CI): Update to PHPUnit10

- psalm.xml
- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/bootstrap/SharingContext.php
- vendor-bin/psalm/composer.json
> chore(CI): Update Behat and PHPUnit10 in integration tests

- lib/AppInfo/Application.php
- lib/Federation/Proxy/TalkV1/Listener/ResourceTypeRegisterListener.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/ocm.feature
- tests/integration/features/federation/poll.feature
- tests/integration/features/federation/reminder.feature
> feat(federation): Register the OCM resource

- src/store/conversationsStore.js
- src/views/WelcomeView.vue
* Allows to handle `/apps/spreed?callUser=...` without page reloading, for example, for:
- Links in the chat, like with links to a conversation
- Contacts menu on Talk Desktop (not in the Web, requires ` feat/in-app-talk-links-support` branch for desktop build)
> feat: handle callUser links in Talk without page reload

- src/components/TopBar/TopBarMenu.vue
* Fix #12044 
* Regression from #8209
> fix(TopBarMenu): register File icon

- lib/Model/ProxyCacheMessage.php
- lib/ResponseDefinitions.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
This makes it a lot easier to handle messages in clients because local and remote messages use the same base type with the same properties.
> refactor(OpenAPI): Use proper type inheritance for chat messages

- package-lock.json
- package.json
* Changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.11.2
* Fix #12009
-- | --
Screenshot before | ![image](https://github.com/nextcloud/spreed/assets/93392545/73a1fadf-c548-436a-b562-f65e95c43867)
> chore(deps): bump nextcloud/vue from 8.11.1 to 8.11.2

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Fix #12046
https://github.com/nextcloud/spreed/assets/84044328/5b827f80-6c2f-487a-a869-9addd002603a
> fix(MessagesButtonsBar): exclude click on emoji picker from outside click event listener

- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
* Fix #11402
https://github.com/nextcloud/spreed/assets/84044328/fb078ead-6de7-440a-8804-7f32573c7a7c
> feat(MessageBody): apply checkbox interactivity

- CHANGELOG.md
- feat(chat): Allow todo lists to be interactive [#12065](https://github.com/nextcloud/spreed/issues/12065)
- feat(devicechecker): Save all previously picked devices instead of the last one [#12067](https://github.com/nextcloud/spreed/issues/12067)
- feat(OCM): Register TalkV1 as OCM resource [#12045](https://github.com/nextcloud/spreed/issues/12045)
- feat(dashboard): Implement Dashboard Widget APIv2 [#12035](https://github.com/nextcloud/spreed/issues/12035)
- fix(chat): Mentions in todo lists are not rendered [#12009](https://github.com/nextcloud/spreed/issues/12009)
- fix(one2one): Allow the desktop client to handle one-to-one links without a reload [#12047](https://github.com/nextcloud/spreed/issues/12047)
- fix(attachments): Ensure …
> chore(release): Add changelog for 19.0.0-rc.3

- .github/workflows/appstore-build-publish.yml
Ref https://github.com/nextcloud-releases/spreed/actions/runs/8653875091/job/23729990728#step:20:1335
> This version of Nextcloud requires at least PHP 8.1<br/>You are currently running 8.0.30. Please update your PHP version.
As there is no latest-29 package, master is cloned, but that is no longer compatible with 8.0, so hard coding the version to 8.1 for now.
We can revert this once the 29 final is in place.
> chore(release): Fix build action while there is no latest-29 package

- README.md
- appinfo/info.xml
* 💬 **Chat** Nextcloud Talk comes with a simple text chat, allowing you to share or upload files from your Nextcloud Files app or local device and mention other participants.
* 👥 **Private, group, public and password protected calls!** Invite someone, a whole group or send a public link to invite to a call.
* 🌐 **Federated chats** Chat with other Nextcloud users on their servers
* 💻 **Screen sharing!** Share your screen with the participants of your call.
* 🚀 **Integration with other Nextcloud apps** like Files, Calendar, User status, Dashboard, Flow, Maps, Smart picker, Contacts, Deck, and many more.
* 🌉 **Sync with other chat solutions** With [Matterbridge](https://github.com/42wim/matterbridge/) being integrated in Talk, you can easily sync a lot of other chat solutions to Nextcloud …
> fix(docs): Sync and update feature list in info.xml and readme

- CHANGELOG.md
- fix(conversation): Fix error when adding participants while creating a conversation [#12057](https://github.com/nextcloud/spreed/issues/12057)
- fix(conversation): Fix missing icon in conversation settings for file conversations [#12051](https://github.com/nextcloud/spreed/issues/12051)
- fix(conversation): Fix error when adding participants while creating a conversation [#12059](https://github.com/nextcloud/spreed/issues/12059)
- fix(conversation): Fix missing icon in conversation settings for file conversations [#12052](https://github.com/nextcloud/spreed/issues/12052)
> chore(release): Add changelog for 17.1.8 and 18.0.7

- lib/Notification/Notifier.php
* Ref https://github.com/nextcloud/server/pull/44770
- Less logs
```json
{"message":"OCA\\Talk\\Notification\\Notifier::prepare() threw \\InvalidArgumentException which is deprecated. Throw \\OCP\\Notification\\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \\InvalidArgumentException yourself."}
```
> fix(notifications): Update the notification handling

- lib/Chat/Parser/SystemMessage.php
> fix(chat): Rename circles to teams in system messages

- css/icons.css
* Fix regression from #11811
* For BG color specifity was increased, so it follows:
* server/component styles (0.2.0);
* light theme in-Talk styles (0.3.0);
* dark theme in-Talk styles (0.4.1);
* system dark theme in-Talk styles (0.3.0 `@media`);
* Increase size for mention bubble (see screenshots)
-- | --
Before | After
-- | --
> style: update CSS specificity for fallback mention icons

- src/components/NewMessage/NewMessage.vue
* Fix #12008
* Same appearance as for filters in LeftSidebar
* Less text changes, to describe only ENABLED behavior
-- | --
> fix(NewMessage): make silent chat button appearance more obvious

- lib/Service/BreakoutRoomService.php
- lib/Signaling/Listener.php
- We had sorting in place already, but for some reason only on start breakout rooms, not on stop....
> fix(tests): Make tests more reliable on PostgreSQL by also sorting on stop

- src/services/__tests__/mediaDevicePreferences.spec.js
- src/services/mediaDevicePreferences.ts
- src/utils/webrtc/MediaDevicesManager.js
* Closes #12064
* rewrite media preferences functions
- fix registering only last device when populate with several
- fix selecting last available device in list when join (instead of last used | first available)
- drop 'promote' option as unused (we register promoted device in another place)
- keep default devices in preferences list
- remove fallback id logic
- move console.log from function for testing purposes
> fix(media): rewrite media preferences functions

- src/components/ConversationSettings/LobbySettings.vue
- src/components/LobbyScreen.vue
- src/utils/__tests__/formattedTime.spec.js
- src/utils/formattedTime.ts
* Fix #12027
very soon | soon | not in 24 hours |
-- | -- | -- |
Lobby screen:
> enh(LobbySettings): add timezone and relative time

- CHANGELOG.md
- fix(calls): Correctly pick the device when showing the device picker after a page reload [#12124](https://github.com/nextcloud/spreed/issues/12124)
- fix(conversations): Correctly update conversations when the read marker changes via another device or window [#9590](https://github.com/nextcloud/spreed/issues/9590)
- fix(chat): Make "silent send" state more obvious for follow up messages [#12118](https://github.com/nextcloud/spreed/issues/12118)
- fix(dashboard): Correctly handle 1-1 conversations with unread system messages [#12073](https://github.com/nextcloud/spreed/issues/12073)
> chore(release): Add changelog for 19.0.0-rc.4

- src/mainPublicShareSidebar.js
* Fix #12132
Vue was not tracking the object changes in computed ( though in prop, it was changed), which means it's not reactive.
> fix(PublicShareSidebar): fix prop reactivity

- src/components/NewMessage/NewMessageAttachments.vue
* Fix: icon is not shown for some attachments 
* Fix: https://github.com/nextcloud/talk-desktop/issues/63
* See: https://github.com/nextcloud/server/blob/a86c1131d7092b4abb1abac8a55f2e71f7a2bbaa/apps/files/lib/ResponseDefinitions.php#L42-L52
-- | --
> fix(chat): show iconSvgInline in attachments

- src/components/MessagesList/MessagesList.vue
* Fix regression from #11702
* It turns out, that `'226' < '55'` is true
-- | --
> fix(MessagesList): make sure to compare numeric values

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesList.spec.js
- in #12021 type of server response was changed to strings, forgot to cover with tests
- `Element.scrollTo` is not implemented in JSDOM, need to mock it to avoid errors in Jest
> test: fix tests, cleanup jest output

- src/utils/webrtc/MediaDevicesManager.js
Follow up to https://github.com/nextcloud/spreed/pull/12108
@DorraJaouad After being working on this for quite some time I saw that [you fixed it](https://github.com/nextcloud/spreed/pull/12146) several hours ago already :cry:
Nevertheless, I took the freedom to push my version anyway as it also handles a special behaviour of Chromium*, and it is a pure fix rather than including an enhancement (showing the devices section when no preferences are set yet). While I think it that is a nice feature I would prefer to see the issue fixed first to then focus on the improvements :-) (specially given that the RC is so close).
*Actually it is in the spec, it is just that Firefox does not implement it yet, but [I forgot about it](https://github.com/nextcloud/spreed/commit/ec7fa54fafb326c111ce7a8c61a6 …
> fix(media): Fix initial selection of devices

- src/components/MediaSettings/MediaSettings.vue
- src/utils/webrtc/MediaDevicesManager.js
- It shows Devices section when no preferences are set yet
- It fixes the issue when there is no prefs yet, no device is selected.
---
> fix(media): improve the default selection before preferences

- CHANGELOG.md
- fix(lobby): Show the timezone and relative time when enabling the lobby [#12135](https://github.com/nextcloud/spreed/issues/12135)
- fix(shareIntegration): Fix handle to close and open the right sidebar on publish share links [#12134](https://github.com/nextcloud/spreed/issues/12134)
- fix(chat): Fix collapsing grouped system message [#12139](https://github.com/nextcloud/spreed/issues/12139)
- fix(attachments): Fix missing icons when creating a file in a chat [#12138](https://github.com/nextcloud/spreed/issues/12138)
- fix(media): Fix initial selection of devices [#12152](https://github.com/nextcloud/spreed/pull/12152) [#12146](https://github.com/nextcloud/spreed/pull/12146)
> chore(release): Add changelog for 19.0.0-rc.5

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
Checkboxes should be disabled in other user messages for one to one conversation.
> fix(MessageBody): restrict checkbox editing in one-to-one conversation

- lib/Dashboard/TalkWidget.php
- lib/Manager.php
- lib/Room.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
> fix(dashboard): Dashboard does not show mentions from federated conversations

- lib/Activity/Listener.php
- lib/Activity/Provider/Base.php
- lib/Activity/Provider/Call.php
- lib/Activity/Provider/Invitation.php
- tests/php/Activity/Provider/BaseTest.php
- tests/php/Activity/Provider/InvitationTest.php
* Ref https://github.com/nextcloud/server/pull/44886
> fix(techdebt): Update exception handling in activity app

- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
* Pass actorId and actorType to MessageBody as props (not attrs)
* Allows to correctly check for message ownership
> fix(MessageBody): pass actorId and actorType as props to the component

- src/components/NewMessage/NewMessage.vue
* Fix #12061
* after typing and hitting enter, debounces update of store (200 ms), might still be in the queue, we need to clear it from there
🏚️ Before
[Screencast from 22.04.2024 09:15:08.webm](https://github.com/nextcloud/spreed/assets/93392545/7c4584cf-324b-4c7e-8ccc-cee2723494c4)
🏡 After
[Screencast from 22.04.2024 09:18:29.webm](https://github.com/nextcloud/spreed/assets/93392545/e775c587-c840-4461-94dc-de04eb6665bf)
> fix(NewMessage): clear debounce queue when posting a message

- src/store/messagesStore.js
* Ref #11994
* Not sure if that fixes this issue, but should fix another:
```js
const messageIds = Object.keys(state.messages[token])
// Array<string>
...
const messagesToRemove = messageIds.sort().reverse().slice(199)
// Sort strings by characters, so '100' < '99'
...
if (state.firstKnown[token] && messagesToRemove.includes(state.firstKnown[token]))
// state.firstKnown[token] is number, so Array<string>.includes(number) is always false
```
Because of that, firstKnown is not updated after list, and after opening the chat again, user couldn't load old messages
> fix(messagesStore): compare message ids as numeric values

- CHANGELOG.md
- fix(chat): restrict checkbox editing in one-to-one conversations [#12160](https://github.com/nextcloud/spreed/pull/12160) [#12176](https://github.com/nextcloud/spreed/pull/12176)
- fix(chat): Fix clearing the input field after file upload [#12061](https://github.com/nextcloud/spreed/issues/12061)
- fix(chat): Fix setting known chat messages borders after leaving the conversation [#12183](https://github.com/nextcloud/spreed/pull/12183)
- fix(dashboard): Dashboard does not show mentions from federated conversations [#12163](https://github.com/nextcloud/spreed/pull/12163)
> chore(release): Add changelog for 19.0.0-rc.6

- vendor-bin/csfixer/composer.json
- vendor-bin/csfixer/composer.lock
See https://github.com/symfony/symfony/pull/54691 for more details
> fix(CI): Fix local cs:check by nailing symfony/finder to 5.4.x

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/participantsStore.js
* follow-up to #11934
Conversation switching before
https://github.com/nextcloud/spreed/assets/84044328/480f1393-a9ad-4912-8fde-f2e5248ef616
Conversation switching after
https://github.com/nextcloud/spreed/assets/84044328/34e1e285-68e1-456e-a919-6e8ded5537ef
> Follow-up: chat scrolling refactoring

- src/components/TopBar/TopBarMediaControls.vue
* Fix #12155 
-- | --
Vue warn from vue-lib | Clean console
> fix(a11y): provide aria-labels for screenshare buttons in every state

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
- src/stores/breakoutRooms.ts
* Fix #11921
* sort rooms in getter by id (order of creation, so 1 -> 2 -> 3) _hard to reproduce_
* use server-provided room names where possible _ParticipantsEditor_
* ease template in Vue SFC files 
* add some ?. conditions to avoid TypeErrors _Vue devtools_
* fix styles to avoid double scrollbar in dialogs _screenshot_
* don't mount NcDialog for deletion if not called explicitly _console_
TODO:
-- | --
> fix(breakout-rooms): enforce rooms order, minor fixes

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
We use last read message to scroll to when opening conversation. When it is collapsed, there is nothing to scroll to and the conversation remains shown at the top. 
* Scroll to its nearest visible parent div
* Adjust the other safeguards
-- | --
> fix(MessagesList): handle special case in scrolling

- src/components/NewMessage/NewMessage.vue
* Follow-up to #11451 
`Ctrl + Arrow` is commonly used way to navigate (move cursor) through documents, text fields or inputs: https://www.w3schools.com/tags/ref_keyboardshortcuts.asp
`Ctrl + Up` should move cursor to the beginning of the text line (if we have one), now it starts last message editing
* Now combination works only with empty input
* event.preventDefault() added to set cursor to the end of edited text
🏡 After - Navigation with  `Ctrl + Arrow`
[Screencast from 02.05.2024 12:55:44.webm](https://github.com/nextcloud/spreed/assets/93392545/60feda68-8f50-4ee9-b8a8-8c4e7691f498)
> fix(editing): restore default behaviour of keyboard hotkeys `Ctrl+Up`

- src/components/LeftSidebar/LeftSidebar.vue
* On scroll with debounce delay we add a 1px border
* It visually moves all the list after the scroll is finished or during the scroll
* When scroll position is 1px - it results in an infinite glitch
-- | --
> fix(LeftSidebar): small glitch on sidebar scroll

- lib/Service/RoomFormatter.php
- src/App.vue
- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
- src/components/LeftSidebar/ConversationsList/ConversationsSearchListVirtual.vue
- src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/composables/useConversationInfo.js
- tests/integration/features/conversation-2/find-listed.feature
> feat(OpenConversationsList): expose description

- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
* Fix regression from #11592
* Messages that are no longer persisted in the store, should be cleared from rendered list
Tested cases:
// group is older than any known newGroup
`[1][2,3],[4,5]` => `[6]` (6 - clear history) - remove all old groups
// at least one message from group is no longer in the store
`[1][2,3],[temp-4]` => `[1][2,3],[4]` - replace temporary message
`[1][2,3],[4],[5,6]` => `[1][2,3],[4]` (4 - message expiration, all messages after 4 were removed)
`[1][2,3],[4,5]` => `[1][2,3],[6]` (mocked case, whole group was removed)
`[1][2,3],[4,5]` => `[1][2,3],[4],[6]` (mocked case, non-first message was removed)
`[1][2,3],[4,5]` => `[1][2,3],[5],[6]` (mocked case, first message was removed)
-- | --
> fix(MessagesList): clean up expired, removed messages from the chat

- src/components/ConversationSettings/LobbySettings.vue
It seems that placeholders in [translation](https://github.com/nextcloud-libraries/nextcloud-l10n/blob/main/lib/translation.ts#L70) are not converted to strings, at least to minimize [unhandled cases](https://github.com/nextcloud-libraries/nextcloud-l10n/blob/e0b16b54fc946273e31e99e0b16d5e85b4ff9560/lib/translation.ts#L88)  :')  
-- | --
> fix(LobbySettings): convert to string before passing it to translation

- src/components/NewMessage/NewMessageUploadEditor.vue
* Fix https://github.com/nextcloud/talk-desktop/issues/651
* Regression of https://github.com/nextcloud/spreed/pull/10730 for old servers:
* When captions aren't supported submit button should be focus as it was before adding captions
* Otherwise it is focused on "Close" button and `Enter` results in dismissing sending files
* Removed optional chaining `?.` to not miss error here
* Note, `getContainerId` did not returned actual promise from `nextTick`. It word because of `await` just as `await Promise.resolve()` but it is not guaranteed
-- | --
> fix(chat): focus submit on upload attachments without caption

- package-lock.json
- package.json
* Fix #…
* Changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.11.3
> chore(deps): Bump @nextcloud/vue from 8.11.2 to 8.11.3

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Required https://github.com/nextcloud-libraries/nextcloud-vue/pull/5553
* Reduce dependencies list (bundle size if different versions) by reusing available function from `nextcloud/vue` library
* Supports skin tone
-- | --
> fix: replace emoji-mart-vue-fast lib usage with nextcloud/vue function

- appinfo/routes.php
- appinfo/routes/routesBanController.php
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/BanController.php
- lib/Controller/RoomController.php
- lib/ResponseDefinitions.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/php/CapabilitiesTest.php
> ⛔ feat(ban): Contract for banning attendees and IP/ranges

- lib/Dashboard/TalkWidget.php
- tests/integration/features/integration/dashboard.feature
> fix(dashboard): Fix dashboard when the last message of a chat expired

- src/components/LeftSidebar/LeftSidebar.vue
* Fix: there is always `New personal note` button even on `stable27` without this feature
-- | --
> fix: check for `note-to-self` capability on frontend

- lib/Notification/Listener.php
- lib/Notification/Notifier.php
Reducing the roundtrips in the notification providers by only parsing each language once
Previous PRs:
- https://github.com/nextcloud/spreed/pull/11208
- https://github.com/nextcloud/spreed/pull/12031
> fix(notifications): Preparse call notifications for improved performance

- src/components/ConversationSettings/LinkShareSettings.vue
- src/store/conversationsStore.js
* keep error handling in the store only
* disable option in dialog window
-- | --
> fix(settings): don't allow guests when breakout rooms are set

- .eslintrc.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Ref #12346
* Force lint CI to fail on incorrect import order
> chore(lint): use strict checks on import/order rule

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
> fix: hide Translate option for files without caption

- src/collections.js
- src/deck.js
- src/maps.js
- src/search.js
- src/utils/requestRoomSelection.js
* 4 plugins have almost copy/past implementation of room selection
* Simplifies Vue 3 migration
* 👀 Review by commit with hide whitespaces
> refactor(plugins): add reusable requestRoomSelection util to run room selector

- src/utils/requestRoomSelection.js
* Regression: https://github.com/nextcloud/spreed/pull/12356
* Fix: Actually do what util's documentation says and plugins expect
* Doesn't seem to really break anything, but annoying error in the console
-- | --
> fix(plugins): return null when room is not selected in plugin instead of throwing an exception

- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageAudioRecorder.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/TopBar/ReactionMenu.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
* Ref #9448
* Unify usage of tooltips across the app
* Remove the global registration of tooltip added in MatterbridgeSettings
* Remove outdated / no longer used imports
> fix(directive): unify tooltip registration

- lib/Controller/CallController.php
- lib/Service/ParticipantService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/callapi/notifications.feature
- tests/php/Service/ParticipantServiceTest.php
* Fix #11282 
- Throws a new error if target is on DND
> fix: throw error when target has DND on

- src/components/NewConversationDialog/NewConversationSetupPage.vue
* Ref #12366
* To test - create a new conversation with description and passport via dialog window
> fix(vue3): use value from v-model (instead of event.target.value)

- src/FilesSidebarCallViewApp.vue
- src/FilesSidebarTabApp.vue
- src/views/FilesSidebarCallView.js
* Ref: https://github.com/nextcloud/spreed/issues/12366
* [Async components now require defineAsyncComponent method to be created](https://v3-migration.vuejs.org/breaking-changes/async-components.html)
* [$children instance property](https://v3-migration.vuejs.org/breaking-changes/children.html)
* Note: sidebar is still half broken but can be fixed separately on `main`. This PR only fixes breaking changes.
* Styles has been lost
* Reactivity is lost
-- | --
> chore(vue3): migrate async component registration and remove $children

- src/components/UIShared/TransitionWrapper.vue
> fix(vue3): keep wrapper in transition group for styles

- src/components/TopBar/CallButton.vue
For https://github.com/nextcloud/spreed/issues/10358
| Before | After |
|---|---|
| ![image](https://github.com/nextcloud/spreed/assets/42591237/81a63177-68c0-4b2d-88d1-40ea071c239f) | ![image](https://github.com/nextcloud/spreed/assets/42591237/f60bd8ca-7092-4432-ab9e-69e6c8b2a05a) |
<details>
<summary>For my own testing</summary>
```
docker run -it --rm ^
--name nextcloud-easy-test1 ^
-p 8443:443 ^
-e TALK_BRANCH=enh/noid/shrink-button ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
ghcr.io/szaimen/nextcloud-easy-test:latest
```
</details>
> feat(mobile): use button without text if on mobile

- lib/ResponseDefinitions.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
Psalm probably didn't catch the missing field because the logic for setting it is too complicated and it can't figure out what is happening.
https://github.com/nextcloud/spreed/blob/704a0727ddc1c798a1f2ba8120cb17316a9995c6/lib/Controller/ChatController.php#L680-L694
> fix(OpenAPI): Add missing reactionsSelf to ChatMessage

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(polls): Remove actor info from system message [#12343](https://github.com/nextcloud/spreed/pull/12343)
- fix(recording): Stop broken recording backend [#12402](https://github.com/nextcloud/spreed/pull/12402)
- fix(polls): Remove actor info from system message [#12342](https://github.com/nextcloud/spreed/pull/12342)
- fix(recording): Stop broken recording backend [#12401](https://github.com/nextcloud/spreed/pull/12401)
> Release 18.0.8

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(polls): Remove actor info from system message [#12342](https://github.com/nextcloud/spreed/pull/12342)
- fix(recording): Stop broken recording backend [#12401](https://github.com/nextcloud/spreed/pull/12401)
> Release 17.1.9

- src/components/CallView/shared/VideoBottomBar.vue
- src/components/CallView/shared/VideoVue.vue
- src/components/ChatView.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
> Fix(vue3): remove unecessary keys for v-if 

- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/store/conversationsStore.js
* Fix #12206 
* Only `createConversation` is mandatory to be completed first, rest request are secondary and could be done in parallel
* As owner of conversation definitely has all needed permissions and access to the conversation, we can fetch participants list (with statuses, permissions, e.t.c) much earlier
* we don't need to wait to join conversation
* we're the only one in the conversation yet, so don't need to debounce request (up to 3-15 sec)
Testing the time (with local server) from **submitting the form** with following:
- Description
- Avatar
- Password
- Listable
- 5 participants
to the time **participants are fetched** 
-- | --
> fix(NewConversationDialog): speed up conversation creation flow

- src/components/LeftSidebar/ConversationsList/Conversation.vue
* Ref #12329 
* Partial backport of https://github.com/nextcloud/spreed/commit/dc0edf87fb0ca70ae47c8d1eb08913d012b39b9a
* Already tested and works on `stable29` and `main`
* Do not render a component, if wasn't called -> optimize performance a bit
No visual changes, jsut less errors in the console
> [stable28] fix(Conversation): do not render NcDialog if was not called explicitly

- src/utils/browserCheck.js
- src/utils/media/pipeline/MediaDevicesSource.js
* Perform browser checks via single utils module
* Tested with Chrome and Firefox
> chore(browserCheck): unify ua-parser usage through the utils

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/composables/__tests__/useMessageInfo.spec.js
* Related to #12380 and to avoid passing class as a prop in vue 3 
Tested with Vue3:
> fix(MessageButtonsBar): pass props only

- src/components/LeftSidebar/InvitationHandler.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/stores/__tests__/federation.spec.js
- src/stores/federation.ts
* Follow-up #11944
* Use header `x-nextcloud-talk-federation-invites` to update counter within 30-sec interval
* Also update manually while accpeting/dismissing
* Rely on that number to show 'Pending invites' button
* Fetch pending invites from server on-demand (if number mismatches)
Loading | Placeholder
-- | --
> fix(federation): use a value from response header to count invites

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/composables/useViewer.js
- pass permissions to Viewer as a string instead of Bitmask
- add visual indicator of loading
-- | --
> fix(viewer): fix creation of file from template

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/composables/useViewer.js
* Follow-up to #12467
* Follow more strict logic when mapping an object for Viewer:
* fileData from Files API goes as-is, only permissions converted;
* fileData from Talk API converted completely to match expected value;
> fix(useViewer): initially define which type will be used to map objects

- src/components/MediaSettings/MediaSettings.vue
- src/components/SettingsDialog/MediaDevicesPreview.vue
- src/composables/useDevices.js
- src/services/__tests__/mediaDevicePreferences.spec.js
- src/services/mediaDevicePreferences.ts
- src/utils/webrtc/MediaDevicesManager.js
* Fix #12185
* Fix #12120
-- | --
> fix(MediaSettings): sync preferences with devices direct selection

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* fetching old messages (starting from "conversation_created") happens then param is missing - request is `api/v1/chat/{token}?setReadMarker=0&lookIntoFuture=1&limit=100&includeLastKnown=0&markNotificationsAsRead=0` instead of `api/v1/chat/{token}?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId={id}&limit=100&includeLastKnown=0&markNotificationsAsRead=0`
Component methods were using the actual token.
- If catch a moment during a conversation switch (while request for messageContext is pending), context for conv1 will be cancelled, but lookForNewMessages for conv2 will be triggered (before preconditions for conv1), resulting not known and missing lastKnownMessageId parameter. 
- With explicitly passing a token through a methods, we ensure it won't leak while switch
-  If request was …
> [stable29] fix(MessagesList): keep token consistent during async methods

- tests/integration/features/sharing-2/get.feature
* Close #12504
* Adjusting test expectations after server changes (loading incoming and outgoing shares now) https://github.com/nextcloud/server/pull/45698
> fix(tests): Adjust expected share type attributes after server change

- src/utils/webrtc/CallParticipantsAudioPlayer.js
- src/utils/webrtc/CallParticipantsAudioPlayer.spec.js
- src/utils/webrtc/index.js
- src/utils/webrtc/models/CallParticipantModel.js
Fixes #12455
[Safari does not allow autoplaying on audio elements in inactive tabs](https://bugs.webkit.org/show_bug.cgi?id=262952), so if the user switched to another tab during a call the participants that join while the tab is inactive will not be heard until the user switches back to the Talk tab. To work around that now an audio element is created when the local participant joins the call and then the audio of all participants is mixed and played on that audio element.
This is applied only to Safari (although maybe it should be applied to any webkit browser? :thinking:); other browsers still play the audio in independent audio elements, just like before (although now they are all managed by a single object, rather than each `CallParticipantModel` managing audio elements specific to a …
> Fix audio in inactive tab in Safari

- CHANGELOG.md
Commited with [skip-ci] to save some CI time on this busy day.
- fix(call): Fix audio issue in Safari when a user unmutes after a longer time while the tab is inactive [#12511](https://github.com/nextcloud/spreed/pull/12511)
- fix(bots): Fix bots with self-signed certificates [#12471](https://github.com/nextcloud/spreed/pull/12471)
- fix(chat): Improve scrolling behaviour when reopening a conversation [#12199](https://github.com/nextcloud/spreed/pull/12199)
- fix(chat): Better handling of captioned messages in federated conversations [#12375](https://github.com/nextcloud/spreed/pull/12375)
- fix(attachments): Fix creating new files from templates [#12488](https://github.com/nextcloud/spreed/pull/12488)
- fix(call): Directly sync the preferences with the device selection …
> chore(release): Changelog for 19.0.2

- .github/workflows/integration-mysql.yml
- .github/workflows/integration-oci.yml
- .github/workflows/integration-pgsql.yml
- .github/workflows/integration-sqlite.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/conversation-2/files.feature
- tests/integration/run.sh
> test(teams): Add a test to check if "Shared with team" allows chatting

- src/assets/variables.scss
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageTypingIndicator.vue
> fix(NewMessage): typing indicator alignment for wide screens

- package-lock.json
> chore: audit JS dependencies

- src/utils/webrtc/CallParticipantsAudioPlayer.js
Follow up to #12497 (see https://github.com/nextcloud/spreed/pull/12497#pullrequestreview-2115081704)
It seems that Safari loops the audio buffer (or something like that) when disconnecting an audio node from a destination node being played, so if a remote participant mutes while speaking Safari plays weird noises. To work around that now the source of the output media element is set again whenever a node is disconnected to force creating a new audio renderer.
Kudos to @SystemKeeper for finding [this nugget](https://bugs.webkit.org/show_bug.cgi?id=198545#c16) in Safari bug tracker and thus avoiding a more complex work around :-)
**Reviewers:** please check the scenarios below without this pull request to ensure that the problem can be reproduced. Specially please check scenario 2, as the …
> fix: Fix broken audio in Safari after disconnecting node

- CHANGELOG.md
- fix(chat): visual alignment of typing indicator for wide screens [#12521](https://github.com/nextcloud/spreed/pull/12521)
- fix(call): remove sound interference in Safari after audio disconnecting [#12534](https://github.com/nextcloud/spreed/pull/12534)
> chore(release): Changelog for 19.0.3

- src/components/NewConversationDialog/NewConversationDialog.vue
* Fix regression from #12431 
* we should push a result `function()`, not a `function` itself 
| 🏡 After |
| -- |
> fix: pass returned promise instead of function

- src/components/MessagesList/MessagesList.vue
* Fix regression from #12492
* first argument (token) was added to the method
-- | --
> fix: pass both arguments to the method

- src/stores/__tests__/federation.spec.js
- src/stores/federation.ts
Ref #12340: we should remove update the object records count after updating themselves.
> fix(federation): update counter after invites store update

- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
* Pre-requisite to #12434
-- | --
No | ![image](https://github.com/nextcloud/spreed/assets/93392545/e7f1f642-5155-42d5-9126-680eea99ef55)
No | ![image](https://github.com/nextcloud/spreed/assets/93392545/558d842b-b662-45f0-94a9-8ac0b288ccd1)
No | ![image](https://github.com/nextcloud/spreed/assets/93392545/4984b127-b8d8-4309-8e10-fbf5fc0581dd)
> feat(conversation): add confirmation dialog when removing participant

- lib/Command/Stun/Add.php
- lib/Command/Turn/Add.php
- tests/php/Command/Stun/AddTest.php
- tests/php/Command/Turn/AddTest.php
> fix: duplicate stun and turn servers cannot be added

- src/components/TopBar/CallTime.vue
It makes sense if attendees who joined after 1h and 10 sec to not see the hint.
> fix(CallTime): stop showing hint for participants who joined after 1 hour. 

- .github/contributing.md
- docs/TURN.md
Added correct links to documentation in spreed\docs\TURN.md
Minor changes to documentation and correct links added to spreed\.github\contributing.md
* Fix #11489
> fix: Broken links in documentation

- src/App.vue
- src/__mocks__/router.js
- src/components/ConversationSettings/BanSettings/BanSettings.vue
- src/components/ConversationSettings/BanSettings/BannedItem.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/router/router.js
- src/services/banService.ts
- src/store/participantsStore.js
- src/types/index.ts
- src/views/ForbiddenView.vue
* Ref #12293
* Provide a minimal frontend to test feature
> [!TIP]
> To test handling a page navigation:
> - create user with id `banned`
> - create conversation with name `ban user`
> - try to join as user
Ban | -
-- | --
List | -
Page | -
> feat(ban): add endpoints for ban handling

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
The button was displayed, even when the user had no permissions to send a message to the chat.
> fix(MessageButtonsBar): Hide reply button if participant has no chat permission

- package-lock.json
- package.json
* bump `nexcloud/capabilities` from v1.1.0 to v1.2.0
* this cleans up extraneous prod.dependencies from the lib (`babel`, `jest`, e.t.c)
* fix `nexcloud/vue` to v8.11.3 (exact)
* this prevents an accidental library bump by dependabot
* audit the rest dependencies
> [stable29] chore(deps): bump and fix nexcloud dependencies

- src/components/RightSidebar/RightSidebar.vue
0. Open Nextcloud Talk on `/apps/spreed`
1. Open a chat with one tab, for example, one-to-one with only **Shared Media** tab
2. Switch to a conversation with only one another tab, for example, Federation chat with only **Participants** tab
3. See no tab
Follow-up: add note to docs in `nextcloud-vue`.
`NcAppSidebar` registers tabs when they are created or destroyed.
But in this case, with Vue optimizing rendering, no tab has been destroyed or created. Instead, the only tab has been reused: it has received new content and `id` changed from `shared-media` to `participants`.
Supporting tab's `id` change in `NcAppSidebar` is not really possible and risky.
A solution - identify `NcAppSidebarTab`s with `key`, so Vue knows that `shared-items` and `participants` or other tabs are actually …
> fix(sidebar): tab is not shown after switching a conversation

- src/components/RightSidebar/RightSidebar.vue
- src/store/sidebarStore.js
- src/store/sidebarStore.spec.js
* Remove some outdated code
* Add 'Participants' tab for 1-1 calls
-- | --
> fix(RightSidebar): refactor, add 'Participants' to 1-1 calls

- src/components/MediaSettings/MediaSettings.vue
* Fix #12545
* I didn't like the idea of a long-text hint obstructing the video, so decided to try a toggle button:
* title and aria-labels define the way video will be displayed for a user
* users can check by himself, how others actually see them.
-- | --
> feat(MediaSettings): add option to mirror video preview

- .github/workflows/appstore-build-publish.yml
- .github/workflows/integration-mysql.yml
- .github/workflows/integration-oci.yml
- .github/workflows/integration-pgsql.yml
- .github/workflows/integration-sqlite.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/occ-command-documentation.yml
- .github/workflows/openapi.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp.yml
Update `setup-php` action to latest 2.31.0 which added a fallback mirror in case launchpad is down: https://github.com/shivammathur/setup-php/releases/tag/2.31.0
> chore(CI): Update setup-php to 2.31.0

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Backport of https://github.com/nextcloud/spreed/pull/12598
- fix(bots): Fix bots with self-signed certificates [#12470](https://github.com/nextcloud/spreed/pull/12470)
- fix(attachments): Fix creating new files from templates [#12487](https://github.com/nextcloud/spreed/pull/12487)
- fix(shareIntegration): Fix handle to close and open the right sidebar on publish share links [#12494](https://github.com/nextcloud/spreed/pull/12494)
- fix(bots): Show error messages during bots setup [#12573](https://github.com/nextcloud/spreed/pull/12573)
- fix(chat): Adjust toast message on message deletion [#12588](https://github.com/nextcloud/spreed/pull/12588)
- fix(bots): Fix bots with self-signed certificates [#12469](https://github.com/nextcloud/spreed/pull/12469)
- fix(shareIntegration): Fix handle …
> chore(release): v18.0.9

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Backport of  https://github.com/nextcloud/spreed/pull/12598
- fix(bots): Fix bots with self-signed certificates [#12469](https://github.com/nextcloud/spreed/pull/12469)
- fix(shareIntegration): Fix handle to close and open the right sidebar on publish share links [#12495](https://github.com/nextcloud/spreed/pull/12495)
> chore(release): v17.1.10

- CHANGELOG.md
- feat(call): Add option to mirror video preview [#12593](https://github.com/nextcloud/spreed/pull/12593)
- feat(call): Add 'Participants' tab to 1-1 calls [#12594](https://github.com/nextcloud/spreed/pull/12594)
- fix(federation): Update federation invites counter [#12544](https://github.com/nextcloud/spreed/pull/12544)
- fix(chat): Hide reply button for participants without chat permissions [#12577](https://github.com/nextcloud/spreed/pull/12577)
- fix(bots): Show error messages during bots setup  [#12572](https://github.com/nextcloud/spreed/pull/12572)
- fix(sidebar): Restore missing tab after switching a conversation [#12587](https://github.com/nextcloud/spreed/pull/12587)
- fix(chat): Adjust toast message on message deletion  [#12589](https://github.com/nextcloud/spreed/pull/12589)
- …
> chore(release): Changelog for 17.1.10 | 18.0.9 | 19.0.4

- package-lock.json
- package.json
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
* Fix: https://github.com/nextcloud/spreed/issues/11454
* Bump `@nextcloud/vue` from 8.11.3 to 8.13.0
* Using new `open` state of `NcAppSidebar` with built-in toggle button
* Adjusted animations
-- | --
> fix(sidebar): use open state to remove always working focus trap on mobile

- docs/bots.md
- docs/events.md
- lib/AppInfo/Application.php
- lib/Command/Bot/Remove.php
- lib/Command/Bot/Setup.php
- lib/Controller/BotController.php
- lib/Events/BotDisabledEvent.php
- lib/Events/BotEnabledEvent.php
- lib/Listener/BotListener.php
- lib/Service/BotService.php
* Fix #11461 
* The PR introduces BotEnabledEvent and BotDisabledEvent.
* These events are dispatched when a bot is enabled or disabled through controller or occ. 
* And sends an asynchronous request to the bot server when these events occur.
This allows the bot server to be notified when a bot is enabled or disabled, enabling it to take appropriate action.
https://github.com/nextcloud/spreed/assets/88997516/2b555435-3eea-4e95-aefd-f6d159222c9c
> feat(bots): Add events for enabling and disabling bots

- src/components/RightSidebar/RightSidebar.vue
* https://github.com/nextcloud/spreed/pull/12387
> refactor(sidebar): stop relying on internal classes and rename class

- lib/Share/RoomShareProvider.php
Forward-ported https://github.com/nextcloud/server/pull/24103
> Only check path for being accessible when the storage is a object home

- src/components/NewMessage/NewMessageAbsenceInfo.vue
- Part of https://github.com/nextcloud/server/issues/40398
-- | --
> feat: show out of office replacement

- src/components/CallView/Grid/Grid.vue
- src/store/participantsStore.js
* Fix #11393
1. user is screensharing
2. user is speaking
3. user has speaking rights and video with video ON
4. user has speaking rights and video with video OFF
5. user with no permissions
There is no differentiation between guests, users and moderators (hopefully in v2 😇)
> [!TIP]
> For testing with a few tiles, make this condition always falsy
> and I suggest to review changes all at once and not by commit, it's messy..
```js
// if model is already in the first page, do nothing
if (false && this.orderedVideos.slice(0, this.slots).find(video => video.attributes.peerId === model.attributes.peerId)) {
return
}
```
-- | --
> [!CAUTION]
> This section for the side effects that I need to handle
> feat(CallView): introduce dynamic order

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* Update deleted messages in LefSidebar
* Drop last edit information for deleted messages (edited before)
* Simplify soft group update in MessagesList
* keep simple conditions: 1 `group no longer exists`, 2 `group did not exist before`, 3 `group is different from previous version`
* re-sort conditions for groups identical comparison (to make early return on less complex operations)
> [!TIP]
> Case 1: delete message
> Before | After
> -- | -- 
> not updated in LefrtSidebar | updated at the same time
> [!TIP]
> Case 2: delete edited message
> Before | After
> -- | -- 
> ![image](https://github.com/nextcloud/spreed/assets/93392545/b22dd290-dbe7-463b-a9e5-f517e2b4bc9d) | ![image](https://github.com/nextcloud/spreed/assets/93392545/fde97617-27d3-4e9a-96e0-cab8cea6d1aa)
> [!TIP]
> Case 3: drop …
> fix(chat): promptly update messages list in sidebar, store and chat

- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/participantsStore.js
Fix #12548
- pass `options: { all }` to leader tab, when force refresh;
- do not fetch anything on secondary tabs, pass message to force refresh via broadcast channel;
- do not fetch anything on leaving conversation;
- broadcast federation invites count to secondary tabs;
🏡 After
[Screencast from 21.06.2024 15:58:27.webm](https://github.com/nextcloud/spreed/assets/93392545/95a7d3e8-26d8-406f-9bce-5b7244f2ab9f)
> fix(conversation): adjust broadcasted data between tabs

- package-lock.json
- package.json
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
* Ref https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.14.0
* Drop `nextcloud-vue-collections` in favor of migrated component
Ton on visual changes with interactive elements sizes and border radiuses
> chore(deps): bump nextcloud/vue from 8.13.0 to 8.14.0

- src/components/Quote.vue
* Fix faulty dialog trigger when navigating to quoted message in the same chat
*  Replace `<a>` with `<RouterLink>`
🏚️ Before 
[Screencast from 08.07.2024 17:06:36.webm](https://github.com/nextcloud/spreed/assets/93392545/ba95b2bf-f535-4f17-8c18-4571ecb78992)
🏡 After
[Screencast from 08.07.2024 17:03:48.webm](https://github.com/nextcloud/spreed/assets/93392545/7a111dc0-8de7-46b6-9e85-585d2cacebc6)
> fix(chat): wrap Quote in RouterLink to handle in-app navigation

- src/components/MessagesList/MessagesList.vue
* Fix #12453
sticky date value was stored from the previous conversation and applied to the current conversation. 
-- | --
> fix(MessagesList): show date separator when div is not scrollable

- appinfo/info.xml
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Migration/Version19000Date20240709183937.php
- tests/php/Federation/FederationTest.php
Since [Nextcloud 29.0.4 ICloudID::getRemote() contains the protocol](https://github.com/nextcloud/server/pull/46133). Therefore we can no longer find the federation invites by the server URL, as the protocol was missing in the database.
To be more aligned with the future expectation of the handling, the protocol is added and now always expected.
* Fix #12654 
- Can not be covered by integration tests as they use http and therefore always have the protocol anyway.
> fix(federation): Fix federation with Nextcloud 29.0.4 or later

- src/components/MessagesList/MessagesList.vue
* Fix #12595
See screencast in original issue.
> fix(MessageList): Workaround rendering issue on safari when unread marker is removed

- appinfo/info.xml
- appinfo/routes/routesBanController.php
- lib/Controller/BanController.php
- lib/Migration/Version20000Date20240621150333.php
- lib/Model/Ban.php
- lib/Model/BanMapper.php
- lib/Service/BanService.php
- openapi-full.json
- openapi.json
- src/services/banService.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/ban.feature
* Fix #12292 
1. Check the contract for needed fields
2. Get inspired from `Version18000Date20230808120823` how to define the `oc_talk_bans` table, columns and indixes
> feat: Added database migration for banning users

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/main.js
- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/mainRecording.js
* Drop dependency lib `vue-observe-visibility`, as it's using the same browser API
* `vue-virtual-scroller` still has it in deps, but different version anyway
No changes
> fix(directive): replace v-observe-visibility with vIntersectionObserver

- lib/TInitialState.php
- src/components/CallView/CallView.vue
- src/components/SettingsDialog/SettingsDialog.vue
* Follow-up to #10464 
* Ref https://github.com/nextcloud/server/pull/45395
* Keep checkbox and translation for the reference, add link to server theming settings
> [!TIP]
> To discard state, use `occ user:setting <user_id> theming force_enable_blur_filter ''`
-- | --
---
> fix(settings): drop local setting for background blur filter, use provided by server

- lib/Dashboard/TalkWidget.php
- Regression from #10250 
🏚️ Before | ☀️ Light theme | 🌑 Dark Theme
--|--|--
> fix(dashboard): Fix missing dashboard icon

- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/store/messagesStore.js
* Fix #12454
* Reserve space for time element for all processed messages:
* file uploads
* edited messages
* new messages
* Show spinner for:
* file uploads
* edited messages
-- | --
> fix(chat): show spinner for temporary / edited messages

- lib/Chat/Parser/SystemMessage.php
- tests/php/Chat/Parser/SystemMessageTest.php
As we don't care which node we get for rendering the message
As suggested by icewind
> [stable29] perf(sharing): Use getFirstNodeById() which is more performant

- CHANGELOG.md
- fix(federation): Correctly handle federation with Nextcloud Server 29.0.4 or later [#12663](https://github.com/nextcloud/spreed/pull/12663)
- fix(chat): Fix scrolling to a quoted message in the desktop client [#12653](https://github.com/nextcloud/spreed/pull/12653)
- fix(conversations): Improve sharing data between different tabs [#12637](https://github.com/nextcloud/spreed/pull/12637)
- fix(chat): Improve update of messages list in the sidebar and the chat [#12636](https://github.com/nextcloud/spreed/pull/12636)
- fix(chat): Show loading spinner when submitting an edited message [#12674](https://github.com/nextcloud/spreed/pull/12674)
- fix(chat): Workaround rendering issue in Safari when unread marker is removed [#12669](https://github.com/nextcloud/spreed/pull/12669)
- fix(chat): Fix …
> chore(release): Changelog for 18.0.10 and 19.0.5

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(sharing): Fix share detection within object stores [#12628](https://github.com/nextcloud/spreed/pull/12628)
> Release 18.0.10

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(federation): Correctly handle federation with Nextcloud Server 29.0.4 or later [#12663](https://github.com/nextcloud/spreed/pull/12663)
- fix(chat): Fix scrolling to a quoted message in the desktop client [#12653](https://github.com/nextcloud/spreed/pull/12653)
- fix(conversations): Improve sharing data between different tabs [#12637](https://github.com/nextcloud/spreed/pull/12637)
- fix(chat): Improve update of messages list in the sidebar and the chat [#12636](https://github.com/nextcloud/spreed/pull/12636)
- fix(chat): Show loading spinner when submitting an edited message [#12674](https://github.com/nextcloud/spreed/pull/12674)
- fix(chat): Workaround rendering issue in Safari when unread marker is removed [#12669](https://github.com/nextcloud/spreed/pull/12669)
- fix(chat): Fix …
> Release 19.0.5

- src/store/messagesStore.js
- src/store/messagesStore.spec.js
Fix lost replies
- a fix from e815ef2dd0cd37e8fde5a3f8cff652dc1277970b works for plain values, but we don't propagate nested parents to parents
- see backend reference:
https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Controller/ChatController.php#L551-L552
-- | --
> fix(chat): keep message parents in the store after update

- lib/Service/BanService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/ban.feature
> fix: Moderators no longer able to ban themselves or other moderators

- lib/Controller/BanController.php
- lib/Model/Ban.php
- lib/Service/BanService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/conversation-1/ban.feature
- Allow empty internal note (its marked optional)
- Use existing room object (save a query)
- Skip moderator check when not needed
- Allow banning former and future users
> fix(ban): Limit query for participants when they actually can be a moderator

- CHANGELOG.md
- fix(federation): Fix missing notifications in https-federated conversations (Nextcloud Server 29.0.4 or later - Part 3) [#12724](https://github.com/nextcloud/spreed/pull/12724)
- fix(chat): Fix chat not loading new messages anymore in new conversation when switching quickly after writing a message [#12721](https://github.com/nextcloud/spreed/pull/12721)
- fix(chat): Fix missing parent message when a chained child message gets edited or deleted [#12719](https://github.com/nextcloud/spreed/pull/12719)
> chore(release): Add changelog for 19.0.7

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(federation): Fix missing notifications in https-federated conversations (Nextcloud Server 29.0.4 or later - Part 3) [#12724](https://github.com/nextcloud/spreed/pull/12724)
- fix(chat): Fix chat not loading new messages anymore in new conversation when switching quickly after writing a message [#12721](https://github.com/nextcloud/spreed/pull/12721)
- fix(chat): Fix missing parent message when a chained child message gets edited or deleted [#12719](https://github.com/nextcloud/spreed/pull/12719)
> Release 19.0.7

- src/components/ConversationSettings/BanSettings/BannedItem.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/store/participantsStore.js
- src/views/ForbiddenView.vue
- Fix #12690
- Ref #12735
- Ref #12293
- Adjust text in 403 view
- Sanitize internal note
- Use banned and moderator display names
- Don't remove user if ban failed
- replace TextField with TextArea for internal note, handle max length exceed
- handle loading state for NcDialog
- allow to set permissions and ban federated users
🏡 After
> fix(bans): minor corrections

- lib/Service/SessionService.php
- tests/php/Service/SessionServiceTest.php
> fix: Fix generating session id again if duplicated

- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesList.vue
* Fix #10627 
During testing, this fix seems smooth when joining, during scrolling and on message link (yet, needs some conditions for this case). 
Before
https://github.com/nextcloud/spreed/assets/84044328/b79aae8a-cce2-4881-8941-2b8d48bc9796
After
https://github.com/nextcloud/spreed/assets/84044328/974a84ec-e357-4ecf-a637-758800ffb2a8
> fix: chat jumping when reference widgets are rendered

- lib/Share/RoomShareProvider.php
* Fix 
```
Using where() on non-empty WHERE part, please verify it is intentional to not call andWhere() or orWhere() instead. Otherwise consider creating a new query builder object or call resetQueryPart('where') first.
```
> fix(sharing): Don't repopulate query builder object

- src/components/Quote.vue
* Fix https://github.com/nextcloud/spreed/issues/12757
* Regression from f513569945d88eee3bdaa8d743165b1038a99279
* simplify styles from 2020 👴🏽 
-- | --
> fix(Quote): simplify styles for ellipsized text

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
* Settings button is a nix of global legacy server styles and `@nextcloud/vue`
* It's style is a bit different from other buttons
* It has double outline on focus
* Options 1: `secondary` - same as other similar apps - Mail, Calendar
* Options 2: `tertiary` - close to previous design
* Also, added a top padding
🏚️ Before | 🏡 After (secondary) | 🏡 After (tertiary)
-- | -- | --
> fix(LeftSidebar): get rid of server styles for settings button

- appinfo/info.xml
- lib/Migration/Version10000Date20201015134000.php
- lib/Migration/Version18000Date20230504205823.php
- lib/Migration/Version20000Date20240717180417.php
> fix: Removed redundant database indices

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
- tests/integration/features/federation/invite.feature
- tests/integration/features/federation/poll.feature
- tests/integration/features/federation/reminder.feature
The remote room identifier happened to work in the tests just because it matched the room name, and [unmapped tokens are automatically mapped to their room name in `assertRooms()`](https://github.com/nextcloud/spreed/blob/da33a4436cf423472008b85445d282ee559f56f4/tests/integration/features/bootstrap/FeatureContext.php#L423-L425).
> Fix mapping of token to identifier for federated rooms

- package-lock.json
- package.json
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
- src/components/NewMessage/NewMessage.vue
* Fix some topic from daily design review
* Tested with `nextcloud-vue@main`, so need to release for some upstream changes 
-- | --
> style: design adjustments for Nc30

- tests/integration/features/bootstrap/CommandLineTrait.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/federation/chat.feature
- tests/integration/features/federation/poll.feature
- tests/integration/run.sh
Split from https://github.com/nextcloud/spreed/pull/12604 for easier reviewing and to be able to backport it if needed to ease future backports of integration tests that could depend on these changes.
The real federated server uses the same code as the main server but a different configuration and data directory. For simplicity, the configuration directory is expected to be inside the data directory of the main server, specifically in `tests-talk-real-federated-server/config`.
If the federated server was not installed in the expected directory before the tests are run a basic installation using SQLite will be
performed, using `tests-talk-real-federated-server/data` as its data directory.
- Install the federated server in CI when using a database other than SQLite? Or just leave the main …
> Add real federated server for integration tests

- lib/Chat/SystemMessage/Listener.php
- Create a group room
- Add a federated user and accept the invitation
- Change the group room to a public room
No errors
Errors appear in both the logs of the host server and the federated server
> fix: Do not try to post messages when federated room visibility changes

- lib/AppInfo/Application.php
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
- tests/integration/features/federation/lobby.feature
Should this be backported to _stable29_? I guess that mobile clients will properly show the lobby if the proxy conversation has the parameter set, but I have not tested it.
- Create a conversation
- Add a federated user
- In a private window, log in as the federated user
- Accept the invitation
- In the original window, enable lobby
- In the private window, open the conversation
The lobby is shown
The conversation never ends to load
> Propagate lobby state to federated servers

- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/TurnServer.vue
* A part of: https://github.com/nextcloud/spreed/issues/12800
-- | --
. | ![image](https://github.com/user-attachments/assets/8e21a49a-ebf2-4e57-8498-637c5872beec)
. | ![image](https://github.com/user-attachments/assets/40a7e5d4-da07-4a7c-9d8e-d71692489e11)
. | ![image](https://github.com/user-attachments/assets/26b5f021-7a85-47d9-ba3b-b653253d6322)
- Completely disable is not possible with `type="password"`, forced by web-browsers
> fix(AdminSettings): hide secrets in password fields

- src/components/AdminSettings/HostedSignalingServer.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
* Fixes https://github.com/nextcloud/spreed/issues/10486
Same as we currently do for the SIP configuration: https://github.com/nextcloud/spreed/blob/main/src/components/AdminSettings/SIPBridge.vue.
* Add emitter to promprtly update all sections (see screencast)
Changes are best reviewed as https://github.com/nextcloud/spreed/pull/12771/files?diff=unified&w=1
-- | --
[Screencast from 22.07.2024 20:44:11.webm](https://github.com/user-attachments/assets/99d619f6-793d-4582-b2bd-0dbe28008a9f)
> fix(AdminSettings): Require HPB for recording server configuration

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Banning users and guests [#12291](https://github.com/nextcloud/spreed/issues/12291)
- Allow to prevent "@ all" mentions for non-moderators [#9074](https://github.com/nextcloud/spreed/issues/9074)
- Add button to show smart picker [#12250](https://github.com/nextcloud/spreed/issues/12250)
- Dispatch events when enabling or disabling bots [#12551](https://github.com/nextcloud/spreed/pull/12551)
- Preview: Federated calls [#11232](https://github.com/nextcloud/spreed/issues/11232)
- Requires Nextcloud 30
- External signaling requires [federation support](https://github.com/strukturag/nextcloud-spreed-signaling/pull/776)
- API performance improvements
- Dynamic order of tiles in a call [#11393](https://github.com/nextcloud/spreed/issues/11393)
- Automatically lower raised hand when …
> Release 20.0.0-beta.1

- src/PublicShareSidebarTrigger.vue
* Fix #12132
* I'm surprised it works with MDI icons
-- | --
-- | --
> fix(public share): make trigger button color contrast to background

- src/components/MediaSettings/MediaSettings.vue
* Minor UI changes:
* Remove Picture-In-Picture
* It must be exactly `disablePictureInPicture`, it cannot be `disable-picture-in-picture`
* Use base * 2 padding for the toggle button
* Inline with other paddings on the modal
-- | --
> fix(MediaSettings): remove PiP and increase mirror toggle margin

- src/components/AdminSettings/RecordingServer.vue
- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/TurnServer.vue
* A part of: https://github.com/nextcloud/spreed/issues/12800
-- | --
- Recording server - delete
- Signaling server - delete
- STUN server - delete (+ add a missing gap here)
- TURN server - delete + test. 
- Don't switch to "testing" (loading) state if testing is not happening
- Disable the testing button when testing is not possible
Before | After
---|---
> fix(AdminSettings): server buttons visual interactivity

- src/components/Quote.vue
* Follow up to #12651
* button is wrapped in `<a>` link, so bubbling click event doesn't get captured by router-link, and causes watning dialog to be shown (my humble assumption)
-- | --
> fix(Quote): prevent button click event from propagation

- css/talk-admin-settings.css
- lib/Settings/Admin/AdminSettings.php
- templates/settings/admin-settings.php
* Likely from legacy, during admin settings loading, half of the settings are half-loaded
* On slow connection it feels weird because the settings are unusable
* On fast connection it looks like a layout shift glitch
Replaced with a placeholder
-- | --
> fix(AdminSettings): remove PHP template

- package-lock.json
- package.json
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MediaSettings/MediaDevicesSelector.vue
- src/components/MediaSettings/MediaDevicesSpeakerTest.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/constants.js
> fix(design): adjustments for Nextcloud 30 - v3

- tests/integration/features/bootstrap/FeatureContext.php
* To avoid bugs like https://github.com/nextcloud/circles/pull/1650 ruining our tests
> fix(tests): Limit notification testing to `app='spreed'`

- lib/ResponseDefinitions.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
* Add two fields in Room schema:
```php
* @psalm-type TalkRoom = array{
*     remoteServer?: string,
*     remoteToken?: string,
}
```
> fix(openapi): add remote* fields to Room definition

- lib/AppInfo/Application.php
- lib/Controller/CallController.php
- lib/Events/ActiveSinceModifiedEvent.php
- lib/Notification/Listener.php
- lib/Notification/Notifier.php
- lib/Service/RoomService.php
- tests/integration/features/federation/call.feature
> feat(calls): Add notifications for federated calls

- css/talk-admin-settings.css
- src/components/NewMessage/NewMessage.vue
* Fixup to  https://github.com/nextcloud/server/pull/46876
-- | --
> style: adjust line-height usage after change from px value to unitless

- css/publicshareauth.css
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/ConversationIcon.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBar.vue
* Fix broken styles
* apply `box-sizing: border-box`
* adjust spacings
* fix colors and text appearance
-- | --
Auth | --
> fix(PublicShareAuthSidebar): fix and refactor styles for video verification sidebar

- src/views/FilesSidebarChatView.vue
* Follow-up to #12853
* Same changes as in PublicShareSidebar. but for registered users via Files app
See original PR
> fix(FilesSidebarChaView): hide duplicated CallButton, when in call

- lib/Controller/SignalingController.php
- lib/ResponseDefinitions.php
- lib/Signaling/BackendNotifier.php
- openapi-full.json
- openapi.json
- src/components/CallView/shared/VideoVue.vue
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/webrtc.js
- tests/integration/features/callapi/update-call-flags.feature
- tests/integration/features/conversation-4/promotion-demotion.feature
Follow up to #12668
Although the `userId` property in the `participants->update` signaling message, which is used by clients to know the participants in a call, [was set to the cloud ID for federated participants](https://github.com/nextcloud/spreed/pull/12668/commits/f91bdfa38ae5922fac15bd64353715bceac8d08a#diff-7ed631e9f04a0445d27e26f716dee988bd363d56cbfa4453ed74bd3605433f9aR433-R434) this was not enough to identify a federated user, as it was not possible to know for sure the actor type only based on the user ID (as [a local user could have a user ID that resembled a cloud ID](https://github.com/nextcloud/spreed/pull/12668#discussion_r1690234134), so looking for _@ remote_ would not be reliable).
Due to that now the `participants->update` signaling messages explicitly provide the …
> Fix avatars in federated calls

- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/ChatView.vue
- src/components/RightSidebar/RightSidebar.vue
- src/views/FilesSidebarChatView.vue
- src/views/MainView.vue
* Separated from #12823 (unrelated mostly)
* `isSidebar` isn't used in this PR, but I'd keep it for future ones (if we ever need to distinct)
> fix(ChatView): mark when used in sidebar, simplify templates

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(calls): Add notifications for federated calls [#12845](https://github.com/nextcloud/spreed/issues/12845) [#12856](https://github.com/nextcloud/spreed/issues/12856) [#12874](https://github.com/nextcloud/spreed/issues/12874)
- fix(calls): Fix broken avatar of remote users in calls [#12863](https://github.com/nextcloud/spreed/issues/12863)
- fix(videoverification): Fix design [#12853](https://github.com/nextcloud/spreed/issues/12853)
- fix(chat): Prevent leave call dialog when canceling quoting [#12824](https://github.com/nextcloud/spreed/issues/12824)
- fix(UI): More design adjustments for nextcloud/vue changes [#12810](https://github.com/nextcloud/spreed/issues/12810)
> Release 20.0.0 beta.2

- src/components/TopBar/CallButton.vue
- src/services/CapabilitiesManager.ts
- src/stores/talkHash.js
* Fix #12864
* Not sure if we should allow chat with dirty hash (as we did before), but feels like we need to
Moved toast to the top to see call button on th screenshot
> fix(federation): disable call buton if talk proxy hash is dirty

- src/components/ConversationSettings/ConversationSettingsDialog.vue
> fix(ConversationSettings): hide ban section in note to self

- lib/Service/RoomService.php
- tests/integration/features/chat-1/message-expiration.feature
> fix: Cannot set message expiration in former 1:1 rooms

- src/assets/variables.scss
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageTypingIndicator.vue
* Ref #12800
🏚️ Before | 🏡 After |
-- | -- |
> [!TIP]
> For visual diff use https://www.diffchecker.com/image-compare/
> fix(MessageList): rewrite CSS layout of chat

- src/components/MessagesList/MessagesList.vue
* Based onto #12823
* Align spinner for loading messages with user avatars
* position absolute to not affect scrolling (extra 40px)
* reduce upper padding which was added to compensate spinner before
-- | --
Wide chat | Call sidebar
> fix(MessagesList): position loading spinner to not affect scrolling

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
* Based on top of  #12823 
* make reactions wrapper a part of message grid, so it is aware of available width (date deducted)
* rewrite styles to default 'small' NcButton
* add thumbnails to reserve space for appearing icons (to avoid chat jumping)
🏚️ Before | 🏡 After |
-- | -- |
> fix(Reactions): integrate reactions into grid CSS layout

- package-lock.json
- package.json
[Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.16.0)
> chore(deps): bump nextcloud/vue lib from 8.15.1 to 8.16.0

- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
* Ref #12800 
* Requires https://github.com/nextcloud-libraries/nextcloud-vue/pull/5870
-- | --
> fix(Participant): migrate to NcListItem

- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
* Fix `[Vue warn]: Error in beforeDestroy hook: "TypeError: this.notifyUnreadMessages is not a function"`
* Leftover from moving it from `TopBar` to `RightSidebar`
* Also discard the notification on conversation switch
> fix(RightSidebar): discard unread messages toast on conversation change

- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/UIShared/ContactSelectionBubble.vue
> fix(ContactSelectionBubble): migrate to NcChip and script setup

- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/constants.js
> Fix conversations layout

- src/components/CallView/CallView.vue
- src/components/TopBar/TopBar.vue
- With the default `line-height` one-line is 1.5 height of font
- In a limited spaces and with different font sizes, it looks a bit not aligned for me
- The gap between lines is higher than between line and bottom border
- Small text may look too small
- Using `normal` (about 1.2) line height ensures that the text is not cut off but also has no extra height even with normal font-size
-- | --
> fix(TopBar): align lines

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Disallow setting message expiration in former one-to-one conversations
[#12882](https://github.com/nextcloud/spreed/issues/12882)
- Show avatar thumbnail for former one-to-one conversations
[#12886](https://github.com/nextcloud/spreed/issues/12886)
- Hide Ban section in "Note to self" conversation settings
[#12889](https://github.com/nextcloud/spreed/pull/12889)
- Disallow banned user to be added to the conversation
[#12793](https://github.com/nextcloud/spreed/issues/12793)
- Disable call button in a federated chat when its settings was changed
[#12864](https://github.com/nextcloud/spreed/issues/12864)
- More UI changes according to design review
[#12800](https://github.com/nextcloud/spreed/issues/12800)
> release: v20.0.0-beta.3

- src/components/UIShared/LoadingPlaceholder.vue
* Fix https://github.com/nextcloud/spreed/issues/12848
-- | --
(slight change in chat placeholder (only in avatar).
> fix(participants): adjust placeholder

- src/components/LeftSidebar/ConversationsList/Conversation.vue
* Fix https://github.com/nextcloud/spreed/issues/12781
-- | --
> fix(Conversation): adjust design of icons

- src/components/TopBar/CallButton.vue
* Fix https://github.com/nextcloud/spreed/issues/12862
* End call icon is the same as the Webcam toggle button
-- | --
> fix(CallButton): replace video icon with phone

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/UIShared/SearchBox.vue
* Issue: if filter is on, you click on search box (without typing), and then click on a conversation, the latter won't be clicked.
-- | --
> fix(LeftSidebar): Fix conversation click when filter and search are on

- lib/Controller/BanController.php
- lib/Service/BanService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/ban.feature
- API level check of https://github.com/nextcloud/spreed/pull/12889
> fix(ban): Don't allow banning in one-to-one conversations and fix banning IP ranges

- lib/Controller/BotController.php
- tests/integration/features/chat-1/bots.feature
> fix: Cannot enable bots in former 1:1 rooms

- lib/Service/BanService.php
- tests/integration/features/conversation-1/ban.feature
> fix: When banning a user they are also removed from the room

- lib/Service/BanService.php
> chore: Removed ban checks for federated users

- tests/integration/features/federation/call.feature
> feat: Added tests for recording consent of federated conversations

- lib/ResponseDefinitions.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
For rooms with message expiry the parent message might no longer be available and thus has a different shape:
https://github.com/nextcloud/spreed/blob/4a27dd5a4ded4b3052326ba3e66b8c226040f87c/lib/Controller/ChatController.php#L581-L584
> fix(OpenAPI): Fix expired parent messages

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/UIShared/SearchBox.vue
* Fix https://github.com/nextcloud/spreed/issues/12912
-- | --
> fix: make more obvious that you can add Federated Cloud ID accounts

- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Service/ParticipantService.php
- tests/integration/features/federation/invite.feature
- tests/php/Federation/FederationTest.php
- CloudID only works with https://github.com/nextcloud/server/pull/47195
- Display name works already
> fix(federation): Fix invited cloudID and save the responded displayname

- package-lock.json
- package.json
* Bumps libraries (nextcloud/auth, axios)
> chore(deps): bump nextcloud/auth library from 2.3.0 to 2.4.0

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/GuestWelcomeWindow.vue
- src/components/PermissionsEditor/PermissionsEditor.vue
- src/components/PollViewer/PollViewer.vue
* Follow-up to #12918
* Not a complete work
* For complex cases: add `labelId`
> fix: provide accessible heading for components

- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
* Fix #12955
Alice is a federated user
🏚️ After | 🏡 Before
-- | --
> fix(Participant): hide ban option for federated users

- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/ReactionToaster.vue
- src/components/CallView/shared/Screen.vue
- src/components/CallView/shared/VideoVue.vue
CallParticipantModels provide the [signaling session ID](https://github.com/nextcloud/spreed/blob/32ba79dec837d3c2f33015ccb2522bc4b4534b46/src/utils/webrtc/models/CallParticipantModel.js#L30) and the [Nextcloud session ID](https://github.com/nextcloud/spreed/blob/32ba79dec837d3c2f33015ccb2522bc4b4534b46/src/utils/webrtc/models/CallParticipantModel.js#L31). When the internal signaling server is used both IDs are the same, but not with the external signaling server. The session ID in the [participant](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L959) and [peer](https://github.com/nextcloud/spreed/blob/2a38a527d24b26a1c6bbcfc7a752061d54ab7276/lib/Controller/CallController.php#L100) data provided by the Nextcloud server …
> Fix using signaling session ID instead of Nextcloud session ID

- src/components/TopBar/TopBar.vue
- src/services/conversationsService.js
- src/stores/chatExtras.js
* Fix https://github.com/nextcloud/calendar/issues/5909
* Requires https://github.com/nextcloud/server/pull/45435
-- | --
> feat(TopBar): add next meeting date

- docs/call.md
- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Federation/Proxy/TalkV1/Controller/CallController.php
- src/components/CallView/shared/VideoVue.vue
- tests/integration/features/federation/call.feature
- tests/integration/features/federation/join-leave.feature
Fixes #12936
Additionally:
- it updates the ping of federated users when they join the host room for consistency with the behaviour for the rest of the participants (which is unrelated to https://github.com/nextcloud/spreed/issues/12917; there the problem is that the ping is not updated in the federated server) and because it is needed for the integration tests that depend on the ping and do not have a real external signaling server (in a real environment the external signaling server updated the ping of federated users in the host server)
- it takes into account federated users when getting the actor id from the call peers in the WebUI, which is used to set the correct avatar and background (in case the actor id was not provided by signaling messages, which it should be).
- Note that it …
> Get call peers by federated users

- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/ConversationSettings/BanSettings/BanSettings.vue
- src/components/LeftSidebar/InvitationHandler.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue
- src/components/NewMessage/NewMessagePollEditor.vue
* Follow-up to #12918
* Not a complete work
* For easy cases: migrate from NcModal to NcDialog
-- | --
> fix: migrate NcModal to NcDialog

- .github/workflows/integration-mariadb.yml
- .github/workflows/integration-mysql.yml
- .github/workflows/integration-oci.yml
- .github/workflows/integration-pgsql.yml
- .github/workflows/integration-sqlite.yml
- .github/workflows/occ-command-documentation.yml
- composer.json
- composer.lock
> chore(CI): Adjust testing matrix for Nextcloud 30 on stable30

- src/__mocks__/capabilities.ts
- src/components/LeftSidebar/InvitationHandler.vue
- src/services/CapabilitiesManager.ts
- src/services/__tests__/CapabilitiesManager.spec.js
* Fix duplicated requests and reloads, if different federated rooms belong to the same remote server
Added some logs for visibility:
- for clean storage or new server - works as before, asking to reload the page
- for next, if server matches - update token map, cache new token for future
- in Network - no new requests for 'capabilities'
[Screencast from 31.07.2024 13:50:16.webm](https://github.com/user-attachments/assets/17f8c52c-e07f-433b-a30f-91dc1d6fd5a1)
> fix(capabilities): store remote capabilities based on remoteServer

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/services/CapabilitiesManager.ts
* Follow-up to #12861
* switch from loadState to getTalkConfig for checking federation (Desktop relies on capabilities rather that initial state)
* clean up remnant configurations (unknown / old tokens, local tokens)
-- | --
> fix(capabilities): minor adjustments for federation

- src/components/AvatarWrapper/AvatarWrapper.spec.js
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/InvitationHandler.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
- src/components/TopBar/TopBar.vue
- src/components/UIShared/LoadingPlaceholder.vue
- src/constants.js
* Part of design changes to Nc30
* User status is reduced in `@nextcloud/vue@master` https://github.com/nextcloud-libraries/nextcloud-vue/pull/5959
-- | --
> fix(avatar): decrease avatar size from 44px to 36px

- src/components/AvatarWrapper/AvatarWrapper.vue
`'loading'` class is "reserved" class that has attached spinner.
-- | --
> fix: remove extra spinner

- src/components/RightSidebar/Participants/ParticipantsTab.vue
> fix: warning from `false` SearchBox's aria-describedby value

- CHANGELOG.md
- Show upcoming event information (up to 1 month) in conversation top bar [#12984](https://github.com/nextcloud/spreed/issues/12984)
- Show user status messages of other local users in a federated conversation [#12982](https://github.com/nextcloud/spreed/issues/12982)
- Don't trigger notifications for system messages in federated conversations [#12985](https://github.com/nextcloud/spreed/issues/12985)
- Add a quick option to log-in when visiting a public conversation as a guest [#12988](https://github.com/nextcloud/spreed/issues/12988)
- Save displayname immediately when inviting a federated account [#12954](https://github.com/nextcloud/spreed/issues/12954)
- Show error messages when uploading a file failed [#12919](https://github.com/nextcloud/spreed/issues/12919)
- Add a hint how to add …
> chore(release): Changelog for 20.0.0-rc.1

- CHANGELOG.md
- Show upcoming event information (up to 1 month) in conversation top bar [#12984](https://github.com/nextcloud/spreed/issues/12984)
- Show user status messages of other local users in a federated conversation [#12982](https://github.com/nextcloud/spreed/issues/12982)
- Don't trigger notifications for system messages in federated conversations [#12985](https://github.com/nextcloud/spreed/issues/12985)
- Add a quick option to log-in when visiting a public conversation as a guest [#12988](https://github.com/nextcloud/spreed/issues/12988)
- Save displayname immediately when inviting a federated account [#12954](https://github.com/nextcloud/spreed/issues/12954)
- Show error messages when uploading a file failed [#12919](https://github.com/nextcloud/spreed/issues/12919)
- Add a hint how to add …
> Release 20.0.0 rc.1

- lib/Chat/Changelog/Manager.php
- Moderators can now ban accounts and guests to prevent them from rejoining a conversation
- Upcoming calls from linked calendar events and out-of-office replacements are shown now in conversations
- *Preview:* Calls can now be done in a federated way with other Talk servers (requires the High-performance backend)
> feat: Add "New in Talk 20" messages

- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/InvitationHandler.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
- src/components/TopBar/TopBar.vue
- src/components/UIShared/LoadingPlaceholder.vue
- src/constants.js
> fix(avatar): increase avatar size to 40px

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/components/RightSidebar/SharedItems/SharedItemsBrowser.vue
- src/components/RoomSelector.spec.js
- src/components/RoomSelector.vue
- src/components/SelectPhoneNumber.vue
> fix(a11y): migrate NcModal to NcDialog p2

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix previews in shared items tab
-- | --
> style(FilePreview): adjust row layout design

- src/components/ConversationSettings/ConversationSettingsDialog.vue
… and former 1-1 conversations
* Fix #12884
🏚️ Former 1-1 | 🏡 1-1 | 🏘️ Group
-- | -- | --
> fix(ConversationSettingsDialog): hide unused settings sections in 1-1

- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
* Fix appearance of component
* visual - should look like NcListItem
* a11y - should be an input with type: checkbox
-- | --
> fix(SelectableParticipant): restyle component

- tests/integration/run.sh
> Enable debug mode in helper script for integration tests

- src/PublicShareAuthSidebar.vue
- src/components/CallView/Grid/Grid.vue
- src/components/SetGuestUsername.vue
- src/stores/__tests__/guestName.spec.js
- src/stores/guestName.js
* Fix #12751
* There is no migration step in the lib, so guests might need to enter nick again
> fix(guest): migrate localStorage nick to nextcloud/auth implementation

- lib/Chat/Parser/SystemMessage.php
- lib/ResponseDefinitions.php
- lib/Share/Helper/FilesMetadataCache.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/php/Chat/Parser/SystemMessageTest.php
> feat: Added blurhash to image metadata

- lib/Config.php
Fixed `isFederatedEnabledForUser`, which was returning true when the intersection of `allowedGroups` and `userGroups` was empty. Now it correctly returns true when the intersection is not empty.
> fix: correct userGroups intersection check for federation access

- src/components/RightSidebar/RightSidebar.vue
* In Lobby sidebar is not available (intentionally, I guess?) but there still was the toggle button
-- | --
> fix(RightSidebar): hide sidebar button in lobby

- package-lock.json
- package.json
* Changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.17.0
-- | --
> chore(deps): bump nextcloud/vue from 8.16.0 to 8.17.0

- lib/Model/AttendeeMapper.php
- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-5/set-permissions.feature
Even if [call permissions will be removed in Talk 21](https://github.com/nextcloud/spreed/issues/13012) right now they are available through the API, so they should to be fixed. Moreover, technically adding and removing permissions [could be done too with room permissions](https://github.com/nextcloud/spreed/blob/main/lib/Service/RoomService.php#L177-L202), even if right now [the API only allows that with call permissions](https://github.com/nextcloud/spreed/blob/c8b9e8d785a9ff04037a91257ef981266eca05c2/lib/Controller/RoomController.php#L2175) (which on the other hand could be a hint to also remove adding/removing permissions and just allow setting them).
For the details please refer to the integration tests and the description in each individual commit.
> Fix adding and removing permissions

- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/ChatController.php
- tests/integration/features/chat-1/note-to-self.feature
> feat: NoteToSelf messages are editable forever

- src/components/AdminSettings/RecordingServers.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/RecordingConsentSettings.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/TopBar/CallButton.vue
- src/constants.js
> fix(recording): distinguish global consent and room-level consent in constants

- package-lock.json
- package.json
- src/App.vue
- src/PublicShareAuthRequestPasswordButton.vue
- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/NewMessage/NewMessage.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
- src/main.js
- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/mainRecording.js
* drop `vue-shortkey` library
* use useHotKey composable (from vue-lib):
> [!IMPORTANT]
> * Ctrl+F doesn't work neither on main branch nor here
* replace shortcuts directive:
* toggle audio / video / raised hand
* toggle fullscreen
* focus shorcuts
* drop `@keydown` listener from NcButton (it's same as click)
No visual or UX changes
> chore(deps): replace vue-shortkey with vueuse directive

- src/__mocks__/capabilities.ts
- src/composables/__tests__/useMessageInfo.spec.js
- src/composables/useMessageInfo.js
> feat(NoteToSelf): allow to edit old messages on frontend

- src/utils/signaling.js
* Fix https://github.com/nextcloud/talk-desktop/issues/760
Tested with Talk 19 on Talk Desktop (20 frontend)
-- | --
> fix(signaling): check only required features on Frontend

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoVue.vue
* Reduce spinner size to 1/2 of avatar
-- | --
> fix(avatar): decrease size of loading spinner

- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
- src/components/ConversationSettings/ConversationPermissionsSettings.vue
- src/components/ConversationSettings/DangerZone.vue
- src/components/ConversationSettings/LobbySettings.vue
- src/components/ConversationSettings/LockingSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/NewMessage/NewMessage.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/RightSidebar.vue
* Follow-up with some vue-lib changes adjustments
* Fix #12921
-- | --
> fix(NcListItem): force three-dot-menu (+ minor follow-ups)

- docs/events.md
- lib/AppInfo/Application.php
- lib/Controller/RoomController.php
- lib/Events/ARoomModifiedEvent.php
- lib/Events/ARoomSyncedEvent.php
- lib/Events/BeforeRoomSyncedEvent.php
- lib/Events/RoomSyncedEvent.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/Proxy/TalkV1/Controller/RoomController.php
- lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
- lib/Recording/Listener.php
- lib/Service/RoomService.php
- lib/Signaling/Listener.php
- openapi-federation.json
- openapi-full.json
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- tests/php/Service/RoomServiceTest.php
- tests/php/Signaling/ListenerTest.php
* Fix #13045
* Fix #13060
* Ref #12953 (fixes room permissions, but individual participant permissions still need manual syncing like attempted in #12979 )
- Track a "property-version" so that recipients know if the just now received data is newer or older https://github.com/nextcloud/spreed/issues/13079
- Always send the full room object when the room was modified, so the sync can heal other properties as well https://github.com/nextcloud/spreed/issues/13079
> fix(federation): Sync room properties on join

- CHANGELOG.md
- Allow editing "Note to self" messages forever [#13083](https://github.com/nextcloud/spreed/issues/13083) [#13089](https://github.com/nextcloud/spreed/issues/13089)
- Add blurhash to files so "previews" can be shown while loading [#13058](https://github.com/nextcloud/spreed/issues/13058) [#13075](https://github.com/nextcloud/spreed/issues/13075)
- fix(federation): Fix propagating permissions, recording consent, permissions and more
- Don't break when joining an open conversation [#13090](https://github.com/nextcloud/spreed/issues/13090)
- Fix signaling server check for Desktop Client so that Nextcloud 29 does not need the newest version [#13094](https://github.com/nextcloud/spreed/issues/13094)
- fix(settings): Hide unused settings in (former) one-to-one …
> chore(release): Add changelog for 18.0.11, 19.0.8 and 20.0.0-rc.3

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(settings): hide secrets in password fields [#12843](https://github.com/nextcloud/spreed/issues/12843)
- fix(conversation): Fix adding and removing permissions [#13080](https://github.com/nextcloud/spreed/issues/13080)
- fix(session): Fix generating session id again if duplicated [#12744](https://github.com/nextcloud/spreed/issues/12744)
> Release 18.0.11 

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(settings): hide secrets in password fields [#12842](https://github.com/nextcloud/spreed/issues/12842)
- fix(conversation): Fix adding and removing permissions [#13081](https://github.com/nextcloud/spreed/issues/13081)
- fix(session): Fix generating session id again if duplicated [#12745](https://github.com/nextcloud/spreed/issues/12745)
- fix(sidebar): hide sidebar button in lobby [#13070](https://github.com/nextcloud/spreed/issues/13070)
- fix(call): prevent navigating away when clicking on a quote while being in a call [#12841](https://github.com/nextcloud/spreed/issues/12841)
- fix(federation): fix system message when removed user has same userId as the moderator [#13054](https://github.com/nextcloud/spreed/issues/13054)
- fix(federation): correctly …
> Release 19.0.8

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Allow editing "Note to self" messages forever [#13083](https://github.com/nextcloud/spreed/issues/13083) [#13089](https://github.com/nextcloud/spreed/issues/13089)
- Add blurhash to files so "previews" can be shown while loading [#13058](https://github.com/nextcloud/spreed/issues/13058) [#13075](https://github.com/nextcloud/spreed/issues/13075)
- fix(federation): Fix propagating permissions, recording consent, permissions and more
- Don't break when joining an open conversation [#13090](https://github.com/nextcloud/spreed/issues/13090)
- Fix signaling server check for Desktop Client so that Nextcloud 29 does not need the newest version [#13094](https://github.com/nextcloud/spreed/issues/13094)
- fix(settings): Hide unused settings in (former) one-to-one …
> Release 20.0.0 rc.3

- src/components/TopBar/TopBar.vue
> fix(TopBar): show "now" instead of start time when it is in the past

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- Minor UX changes to FilePreview
- fix container size to single source (prevents jumping to 0 and back when image is loaded)
- use NcLoadingIcon
- don't load virtual image in mounted hook
- add fade transition from blurhash/loader to image
🏚️ Before
https://github.com/user-attachments/assets/b07a6464-2810-4892-9440-d9249b9ea946
🏡 After
https://github.com/user-attachments/assets/92102d54-0e13-47a9-8ff4-dd29214386e8
> fix(FilePreview): set fixed size to image container

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
* Fix: instead of `"A, B, C, and 1 other participant"`, it is now `"A, B, C, and D"` , +1 `"A, B, C, and 2 other participants"` ....
-- | --
> fix(Reactions): show all names if they are at most 4 reactions

- lib/Controller/RoomController.php
- lib/Service/SessionService.php
- tests/php/Service/SessionServiceTest.php
> fix(federation): Expire sessions of federated users

- src/App.vue
- src/services/federationService.ts
- src/stores/__tests__/federation.spec.js
- src/stores/federation.ts
- src/types/index.ts
* Fix #13146
* Works now after reload / accept from notification
* If already in the store - early return, so doesn't affect performance
> fix(federation): ensure federation invites appear in store

- lib/Chat/Parser/SystemMessage.php
- tests/integration/features/federation/chat.feature
- tests/php/Chat/Parser/SystemMessageTest.php
> fix(federation): Correctly handle decline in system messages

- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/components/TopBar/TasksCounter.vue
- src/components/TopBar/TopBar.vue
- src/stores/chatExtras.js
* Fix #13034
| Nothing done | Partially completed | 🏡 Completed
-- | -- | --
> feat(NoteToSelf): add tasks counter

- lib/Config.php
> fix(appconfig): Ensure configs are within ranges

- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/TopBar/TopBarMediaControls.vue
* Fix false positively active buttons
* audio/video buttons could opened MediaSettings before, but if you're not allowed to stream audio/video - nothing to change?
🏚️ Before (cursor: pointer) | 🏡 After (cursor: default)
-- | --
> fix(TopBar): disable buttons if user has no media permissions

- lib/Command/Room/TRoomCommand.php
- lib/Controller/RoomController.php
- lib/Exceptions/RoomProperty/DefaultPermissionsException.php
- lib/Exceptions/RoomProperty/LobbyException.php
- lib/Exceptions/RoomProperty/NameException.php
- lib/Exceptions/RoomProperty/RecordingConsentException.php
- lib/Exceptions/RoomProperty/SipConfigurationException.php
- lib/Service/RoomService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- Preparation for easier execution of #13163 
- Best reviewed commit-by-commit
> fix(api): Properly typed room-property updates - Part 1

- src/components/CallView/CallView.vue
* Shadows are used only for elements on top of other elements, like menus/autocomplete
-- | --
> fix(CallView): remove shadow of avatars

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix regression from #13109
-- | --
> fix(FilePreview): use original size for uploaded image files

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix regression from #13147 
* max-height: 100% takes the height of parent, which is .image-container, which is not limited
* images larger than 384px shown at full-size (especiall if photos app is disabled)
-- | --
> fix(FilePreview): limit preview size to 384px at upload

- tests/integration/run-docker.sh
When using a different image to run tests, the working directory might not always be `/`. Therefore adjust the commands we use to use an absolute path.
> fix(tests): Always use absolute path in run-docker.sh

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoVue.vue
* Fix screenshot mode a bit
-- | --
Remote screen | ![image](https://github.com/user-attachments/assets/24959d51-ff5d-462f-9a89-9aef88d96329)
> fix: use provide/inject to pass values of devMode to CallView children

- src/components/NewMessage/NewMessageAttachments.vue
- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/store/fileUploadStore.js
* Fix duplicating of templates
-- | --
> fix(fileUpload): don't duplicate file templates in store

- src/components/CallView/shared/EmptyCallView.vue
- src/store/participantsStore.js
- src/utils/signaling.js
* Fix part of #13160
-- | --
| Before | ![Screenshot 2024-08-30 112219](https://github.com/user-attachments/assets/c1e67539-8e01-44ae-9dd4-289ce416e117) |
> fix: refactor connection failed description

- CHANGELOG.md
- Add a task counter for to-do lists in "Note to self" messages [#13034](https://github.com/nextcloud/spreed/issues/13034)
- Fix accepting federation invites from notification [#13146](https://github.com/nextcloud/spreed/issues/13146)
- Show error when joining a call failed [#13077](https://github.com/nextcloud/spreed/issues/13077)
- Handle OS theme change without page reload [#10774](https://github.com/nextcloud/spreed/issues/10774)
- Various design fixes
> chore(release): Add changelog for 20.0.0-rc.4

- lib/Controller/TempAvatarController.php
- lib/Service/AvatarService.php
- tests/psalm-baseline.xml
> fix: use \OCP\Image instead of \OC_Image

- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
[ISSUE 1]: chats are not fetched when there are a few messages visible
**Conditions:**
- Open a conversation
- First 50 messages have a few messages visible (e.g: 5)
- These messages fit viewport and thus div is not scrollable
**Result:**
User cannot fetch older messages as this is triggered by scrolling only
**Fix:**
Introduced wheel event, that watches over mouse/touchpad scrolling and trigger scrolling process for non-scrollable messages list. 
[ISSUE 2]: scroll to bottom button keeps showing at the bottom
Fix: set `scrolledToBottom` marker by calculation and not by forced value at some cases.
-- | --
> fix(MessagesList): Fix chat fit in one screen not fetching

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/components/RightSidebar/Participants/Participant.vue
* LeftSidebar: get rid of forced scrollbars
* NewMessageUploadEditor: adjust design, add hover effect
-- | --
Screenshot before | ![image](https://github.com/user-attachments/assets/124ca40f-dcef-4e24-8f8c-71950b7128f5)
Signed-off-by: Antreesy <antreesy.web@gmail.com>
> fix: minor UX enhancements

- src/components/ChatView.vue
* Fix https://github.com/nextcloud/spreed/issues/13238
-- | --
> fix(chat): add title to "Scroll to bottom" button

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/constants.js
- src/store/fileUploadStore.js
* Fix #12866
Before | 🏡 After
-- | --
> fix(upload): show blob previews for .webp image uploads

- lib/Notification/Notifier.php
Found using https://github.com/nextcloud/server/pull/47662.
I temporarily pointed OCP to my local lib/public so psalm started finding the issues. In the future once the PR is merged it will be enforced by default.
> fix(Notification): Fix rich object parameters with non-string values

- lib/Chat/Parser/SystemMessage.php
Deleting message as user1 from federated server shows user1 from host server as actor
> fix(federation): matching current user is actor in delete message

- docs/bots.md
> docs: Fix copy-paste-error on Join/Leave docs for Bot messages

- lib/Config.php
- lib/Controller/SignalingController.php
- tests/php/ConfigTest.php
- tests/php/Controller/SignalingControllerTest.php
- tests/php/Listener/RestrictStartingCallsTest.php
- tests/php/Recording/BackendNotifierTest.php
* we knew the difference already
* Saves a query for federated users
> fix(signaling): Avoid conflict potential of user and federated user

- lib/Command/Room/TRoomCommand.php
- lib/Controller/RoomController.php
- lib/Exceptions/RoomProperty/AvatarException.php
- lib/Exceptions/RoomProperty/BreakoutRoomModeException.php
- lib/Exceptions/RoomProperty/BreakoutRoomStatusException.php
- lib/Exceptions/RoomProperty/CallRecordingException.php
- lib/Exceptions/RoomProperty/DescriptionException.php
- lib/Exceptions/RoomProperty/ListableException.php
- lib/Exceptions/RoomProperty/MentionPermissionsException.php
- lib/Exceptions/RoomProperty/MessageExpirationException.php
- lib/Exceptions/RoomProperty/PasswordException.php
- lib/Exceptions/RoomProperty/ReadOnlyException.php
- lib/Exceptions/RoomProperty/TypeException.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Service/BreakoutRoomService.php
- lib/Service/RoomService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/conversation-1/breakout-rooms.feature
- Preparation for easier execution of #13163 
- Best reviewed commit-by-commit
- Part 2 of #13167
> fix(api): Properly typed room-property updates - Part 2

- lib/AppInfo/Application.php
- lib/SetupCheck/BackgroundBlurLoading.php
- lib/SetupCheck/FederationLockCache.php
- lib/SetupCheck/RecommendCache.php
- lib/SetupCheck/RecordingBackend.php
- lib/SetupCheck/SIPConfiguration.php
- psalm.xml
- tests/psalm-baseline.xml
- tests/stubs/oc_memcache.php
- tests/stubs/oca_settings_setupchecks_checkserverresponsetrait.php
> fix(setupchecks): Add setup checks for current checks

- package-lock.json
- package.json
- src/components/SettingsDialog/SettingsDialog.vue
- src/main.js
- src/services/SettingsAPI.ts
- src/services/__tests__/SettingsAPI.spec.js
* Primary for: https://github.com/nextcloud/talk-desktop/issues/27
* Talk Desktop demo PR: https://github.com/nextcloud/talk-desktop/pull/792
Adds new public API to register custom settings sections for Talk app using Web Components.
```ts
type TalkSettingsSection = {
/**
* Section internal ID
*/
id: string
/**
* Section visible name
*/
name: string
/**
* WebComponent's (custom element's) tag name to render as the section content
*/
element: string
}
window.OCA.Talk.Settings = {
/**
* Open settings dialog
*/
open()
/**
* Register a custom settings section
* @param section - Settings section
*/
registerSection(section: TalkSettingsSection)
/**
* Unregister a custom settings section
* @param id - Section ID
*/
unregisterSection(id: string)
}
```
> feat(desktop): add OCA.Talk.Settings API to customize and manage settings

- src/services/SettingsAPI.ts
- src/services/__tests__/SettingsAPI.spec.js
Changes nothing in how it works.
Gets rid of the annoying Vue 2 warning about `reactive(array)` behavior on Vue 2 vs Vue 3 in `watch` (which we even don't use).
> chore(SettingsAPI): replace reactive with ref to remove Vue 2 warn

- src/components/TopBar/CallButton.vue
- src/store/callViewStore.js
- src/store/messagesStore.js
* Fix #8148
* DIsable CallButton for `10` seconds, when `call_ended_everyone` system message is received
* Longer time picked for longer disconnection period
| 🏡 After
| --
| <img width="149" alt="image" src="https://github.com/user-attachments/assets/72cb137f-d437-43dc-b865-f038fb5565c1">
> fix(call): temporary disable a call button if ended by moderator

- src/components/ConversationSettings/ConversationAvatarEditor.vue
> fix(avatar): don't use 'user/avatar' endpoint for generating a temp avatar

- CHANGELOG.md
- fix(federation): Fix federation invites accepting from the notification [#13153](https://github.com/nextcloud/spreed/issues/13153)
- fix(chat): Fix "You deleted the message" when performed by federated user with same ID [#13250](https://github.com/nextcloud/spreed/issues/13250)
- fix(files): Keep order of attachments when sharing multiple [#13099](https://github.com/nextcloud/spreed/issues/13099)
- fix(avatar): Don't overwrite user avatar when selecting a square for a conversation [#13277](https://github.com/nextcloud/spreed/issues/13277)
> chore(release): Add changelog for 19.0.9 and 20.0.0-rc.5

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(federation): Fix federation invites accepting from the notification [#13153](https://github.com/nextcloud/spreed/issues/13153)
- fix(chat): Fix "You deleted the message" when performed by federated user with same ID [#13250](https://github.com/nextcloud/spreed/issues/13250)
- fix(files): Keep order of attachments when sharing multiple [#13099](https://github.com/nextcloud/spreed/issues/13099)
- fix(avatar): Don't overwrite user avatar when selecting a square for a conversation [#13277](https://github.com/nextcloud/spreed/issues/13277)
> Release 19.0.9

- src/components/Quote.vue
Backport of #12718 (reduced modifications)
> fix(Quote): add remote server and edited hints in quoted messages

- package-lock.json
- package.json
* Fix checkbox/radio/switch disabled colors
* Audit some dependencies
> chore(deps): bump nextcloud/vue lib from 8.17.1 to 8.18.0

- CHANGELOG.md
- Federated calls
- Add a task counter for to-do lists in "Note to self" messages
- Allow editing "Note to self" messages forever
- Show blurhash while loading attachments
- Show upcoming event information in conversation
- Banning users and guests
- Allow to prevent `@all` mentions for non-moderators
- Add button to show smart picker
- Dispatch events when enabling or disabling bots
- Show user status messages of other local users in a federated conversation
- Requires Nextcloud 30
- High-performance backend with `federation` support is required (Version 2.0.0 or later)
- API performance improvements
- Dynamic order of tiles in a call to prioritize participants with audio or video
- Automatically lower raised hand when participant speaks
- Show confirmation dialog when removing a …
> chore(release): Add changelog for 20.0.0

- src/__mocks__/capabilities.ts
- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/ConversationIcon.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/TopBar/TopBar.vue
- src/composables/useSortParticipants.js
- src/services/CapabilitiesManager.ts
- src/services/avatarService.ts
- src/services/banService.ts
- src/services/botsService.ts
- src/services/breakoutRoomsService.ts
- src/services/federationService.ts
- src/services/messagesService.ts
- src/services/reactionsService.ts
- src/stores/bots.ts
- src/stores/breakoutRooms.ts
- src/stores/federation.ts
- src/types/index.ts
- src/utils/getItemTypeFromMessage.ts
- src/utils/textParse.ts
- src/utils/userStatus.js
- src/utils/userStatus.ts
* Prerequisite to #12850
* Allow to use util with search results
> fix(userStatus): migrate util to Typescript

- src/App.vue
- src/components/MessagesList/MessagesList.vue
- src/components/TopBar/CallTime.vue
- src/composables/useActiveSession.js
- src/composables/useGetParticipants.js
- src/composables/useWindowVisibility.ts
- src/store/windowVisibilityStore.js
* Move a value handling from the store
> fix: move page visibility check to composable

- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsList.vue
- src/components/RightSidebar/Participants/ParticipantsSearchResults.vue
* Ref #12800
* Extract `searched` behaviour` from `<Participant />` component into a new one
* Migrate component to NcListItem (template) and TS (script)
* Rewrite color scheme for the component
-- | --
> feat(ParticipantSelectable): add component for participant search results and bulk selection

- README.md
- docs/developer-setup.md
- docs/index.md
Add a step by step guide for a development setup for talk, including HPB and recording server.
> feat(devsetup): Add step by step guide for a development setup

- src/components/MediaSettings/VideoBackgroundEditor.vue
> fix(VideoBackgroundEditor): change the container of file picker

- src/store/participantsStore.js
* Fix #13334 
* Frontend wasn't aligned with backend, that `ban` also removes a user
No unexpected behavior
> fix(ban): do not try to remove a banned user (handled by backend)

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/Recording.vue
- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/composables/useDocumentFullscreen.ts
- src/composables/useViewer.js
- src/main.js
- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/mainRecording.js
- src/store/uiModeStore.js
* Fix broken toast messages, removes need for reparenting Viewer, e.t.c
* Instead of requesting a fullscreen for App, do it for the document.body (hide header and resize content to make it look the same)
-- | --
> fix: request fullscreen for the whole page

- lib/Command/Developer/UpdateDocs.php
- lib/Signaling/Responses/DialOut.php
- lib/Signaling/Responses/DialOutError.php
- lib/Signaling/Responses/Response.php
- tests/php/bootstrap.php
- vendor-bin/csfixer/composer.json
- vendor-bin/csfixer/composer.lock
> feat(codingstandard): Update coding-standard to 1.3.1

- src/components/TopBar/TopBar.vue
> fix(TopBar): migrate to NcPopover

- src/components/CallView/Grid/Grid.vue
* Allows to change pages in call grid with a mouse wheel scrolling
⚠️ Second commited is not to be backported!
> feat(call): list participants grid/stripe with a mouse wheel

- lib/Chat/Changelog/Listener.php
- lib/Chat/Changelog/Manager.php
* Related
There was a simple race condition previously with 2 requests R1 and R2:
- R1: handle()
- R1: userHasNewChangelog() compares X0 with count()
- R2: handle()
- R2: userHasNewChangelog() compares X0 with count()
- R1: updateChangelog()
- R1: getChangelogForUser() reads X0
- R1: setUserValue() sets X1 with precondition X0
- R2: updateChangelog()
- R2: getChangelogForUser() reads X1 :boom: 
- R2: setUserValue() sets X1 with precondition X1
> fix(changelog): Don't check the user changelog twice

- lib/Chat/ChatManager.php
* Fix #13286 
Before
Just as with the screencast below, the difference is that the unread message doesn't disappear even after refreshing the page.
After
https://github.com/user-attachments/assets/390a6902-f6d7-4aa7-990c-bdab5d7e0995
---
> fix(chatManager): Expire unread cache on message delete

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix #13199 
**Note:**  In Whatsapp (whose example is given in the issue), the voice messages auto-play only when they are grouped together. Therefore I tried to replicate that only. If there's a message between two voice messages, it will not be auto-played.
That being said, its very easy to change this behaviour. We just need to remove this `since` check over [here](https://github.com/nextcloud/spreed/pull/13360/files#diff-8a7e5104736c054cb13539ee9b0721cbb5ad4bfa747633f51e9794f08d6a1ce6R94).
Before 
https://github.com/user-attachments/assets/5b899ae6-1e0e-4563-9097-e3282b8a0c28
After
https://github.com/user-attachments/assets/968525ea-9758-4b0f-bb63-a9b447c4557e
> feat(audioPlayer): Auto play voice messages which are grouped together

- src/components/ConversationSettings/ConversationAvatarEditor.vue
* 'settings' translations are not loaded in 'spreed' page
-- | --
> Fix some translation calls

- lib/Federation/BackendNotifier.php
- lib/Federation/FederationManager.php
- tests/php/Federation/FederationTest.php
1. Invite User2 from Remote2
2. Simulate a disconnect, by either:
a. Disable Remote2 and then delete User2 on Remote1
b. or directly remote User2 from attendees table on Remote1
3. Re-invite User2 from Remote2 to the same room
> fix(federation): Recover broken invites

- src/assets/variables.scss
* Decrease max width of text message to 750px (50em)
* Most resources recommended from 60 to 80 characters per line, example: https://baymard.com/blog/line-length-readability
* I managed now to fit 113 characters with normal font (91 with dyslexic font)
-- | --
75ch (article) | ![image](https://github.com/user-attachments/assets/f40115eb-ed0f-49a8-92f1-65284ec3eb15)
35em (article) | ![image](https://github.com/user-attachments/assets/1da84005-13a5-46f1-a4b8-2a8bd5774533)
600px (stable29) | ![image](https://github.com/user-attachments/assets/98038ae8-c420-4785-a1b5-6b3ae2197b7e)
⚠️ 50em (this PR) | ![image](https://github.com/user-attachments/assets/1a928aa0-c6a5-451d-9cdd-f46b73118ebb)
⚠️ 50em (this PR) | ![image](https://github.com/user-attachments/assets/508c1b4e-eef8 …
> style: decrease chat messages 'reading width'

- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
* by setting a new value to modelProxy, instead of updating native input
* Fix regression from #12850
> fix(SelectableParticipant): fix keydown.enter event 

- src/components/RightSidebar/Participants/Participant.vue
* Ref #13390
* Stick NcActions to dedicated Participant in virtual list
* Virtual list reuses same components
* In theory, it shoouldn't be possible anymore to promote/delete random participant because of the wrong action
-- | --
> fix(Participant): re-render component in VirtualScroller

- src/components/MessagesList/MessagesList.vue
* Fix: when keeping the conversation open overnight, relative dates do not get updated. 
-- | --
messages list showing two "today", one of them is supposed to be "yesterday" | only one correct "today"
> fix(MessagesList): update date separator overnight

- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/NewMessage/NewMessageAudioRecorder.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/ReactionMenu.vue
- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
- src/components/UIShared/EditableTextField.vue
* Fix leftovers from v-tooltip usage
-- | --
> fix: replace v-tooltip with native title

- src/components/CallView/CallView.vue
- PresenterOverlay broke `v-else-if` chain in previous place
- also add distinct keys to prevent rendering issues
-- | --
> fix: do not show two promoted videos

- lib/Controller/SignalingController.php
- tests/php/Controller/SignalingControllerTest.php
> fix: Check media direction in internal signaling messages

- src/components/NewMessage/NewMessagePollEditor.vue
- src/stores/__tests__/polls.spec.js
- src/stores/polls.ts
> fix: store form data as a single object

- CHANGELOG.md
- feat(call): Add wave and fire call reactions [#13349](https://github.com/nextcloud/spreed/issues/13349)
- fix(chat): Reduce read-width of chat again [#13421](https://github.com/nextcloud/spreed/issues/13421)
- fix(signaling): Deprecate using multiple High-performance backends and the fake-clustering mode [#13420](https://github.com/nextcloud/spreed/issues/13420)
- fix(chat): Fix missing push notifications for chat messages [#13331](https://github.com/nextcloud/spreed/issues/13331)
- fix(chat): Correctly update "Today"-date separator when the day changes [#13434](https://github.com/nextcloud/spreed/issues/13434)
- fix(call): Correctly ignore media offers from users without permissions when internal signaling is used …
> chore(release): Add changelog for 18.0.12, 19.0.10 and 20.0.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(call): Add wave and fire call reactions [#13349](https://github.com/nextcloud/spreed/issues/13349)
- fix(chat): Reduce read-width of chat again [#13421](https://github.com/nextcloud/spreed/issues/13421)
- fix(signaling): Deprecate using multiple High-performance backends and the fake-clustering mode [#13420](https://github.com/nextcloud/spreed/issues/13420)
- fix(chat): Fix missing push notifications for chat messages [#13331](https://github.com/nextcloud/spreed/issues/13331)
- fix(chat): Correctly update "Today"-date separator when the day changes [#13434](https://github.com/nextcloud/spreed/issues/13434)
- fix(call): Correctly ignore media offers from users without permissions when internal signaling is used …
> Release 20.0.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(performance): Fade out local blur-filter option for Nextcloud wide setting [#13100](https://github.com/nextcloud/spreed/issues/13100)
- fix(avatar): Fix missing translations [#13410](https://github.com/nextcloud/spreed/issues/13410)
- fix(chat): Expire message cache when deleting the last message [#13392](https://github.com/nextcloud/spreed/issues/13392)
- fix(call): Correctly ignore media offers from users without permissions when internal signaling is used [#13494](https://github.com/nextcloud/spreed/issues/13494)
- fix(call): Fix missing call sounds in Safari when tab is moved to the background [#13352](https://github.com/nextcloud/spreed/issues/13352)
> Release 19.0.10

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(avatar): Fix missing translations [#13411](https://github.com/nextcloud/spreed/issues/13411)
- fix(chat): Expire message cache when deleting the last message [#13391](https://github.com/nextcloud/spreed/issues/13391)
- fix(call): Correctly ignore media offers from users without permissions when internal signaling is used [#13493](https://github.com/nextcloud/spreed/issues/13493)
- fix(call): Fix missing call sounds in Safari when tab is moved to the background [#13351](https://github.com/nextcloud/spreed/issues/13351)
- fix(avatar): Don't overwrite user avatar when selecting a square for a conversation [#13287](https://github.com/nextcloud/spreed/issues/13287)
> Release 18.0.12

- package-lock.json
- package.json
> chore: bump @nextcloud/webpack-vue-config from 6.1.1 to 6.2.0

- src/__mocks__/capabilities.ts
- src/constants.js
- src/services/pollService.ts
- src/stores/__tests__/polls.spec.js
- src/stores/polls.ts
- src/types/index.ts
* Follow-up to #13506
* Only logic, frontend elements will come separately
> feat: align polls state management with API

- appinfo/routes/routesCallController.php
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/CallController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/public.feature
> feat(calls): Allow moderators to download a call participants list

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix FilePreview appearance
* Mimetypes from server are here: https://github.com/nextcloud/viewer/blob/41f169bbef37ce5e9c52ca9c3b632f9cb69bae99/src/models/videos.js
-- | --
> fix: respect mimetype aliases for file previews

- docs/developer-setup.md
Add option to enable federation via occ to our developer setup docs as well.
> fix(docs): Add federation occ to developer setup docs

- lib/Controller/CallController.php
- src/components/TopBar/TopBarMenu.vue
* Ref #13453 
During call | Output
-- | --
> feat(calls): Allow moderators to download a call participants list - frontend

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/PollViewer/PollDraftHandler.vue
- src/components/PollViewer/PollViewer.vue
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
- src/stores/polls.ts
* Follow-up to #13516
Creation | Open poll
-- | -- 
Closed poll | Shared Items
Filled, from Poll Editor | Empty, from Shared items
Opened from DraftHandler ('Back' arrow) | -
> feat: draft polls management 📊

- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
- disable smooth scroll to bottom
- update previous scroll position in scroll event (not after it's finished)
- store direction while scrolling
- ensure debounceHandleScroll is fired before endScroll
* Fix #13237
-- | --
> fix(chat): disable smooth scroll to bottom

- lib/Activity/Provider/Base.php
- lib/Activity/Provider/Invitation.php
- tests/php/Activity/Provider/InvitationTest.php
> fix(activity): Fix parameter type of call activity

- src/components/CallView/CallView.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/utils/__tests__/satisfyVersion.spec.js
- src/utils/satisfyVersion.ts
* Ref #12633
- partially reverts ed39a6bef13f7c1312459ebc610ba669d26501e0
- returns compatibility for Talk Desktop with versions below 29.0.4
-- | --
> fix: handle background blur in Talk if server doesn't support it

- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/PollViewer/PollViewer.vue
- src/utils/fileDownload.ts
- src/utils/validatePollForm.ts
> feat(polls): Import/Export pre-filled poll form to JSON 📊

- tests/integration/run.sh
> ci: Always reset the skeleton directory

- src/components/MessagesList/MessagesList.vue
* Follow-up to #12205 
* if chat is mounted, but hidden (in sidebar), offsetParent is also null
-- | --
> fix: check for false positive hidden parent when scroll

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageAudioRecorder.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
* Fix broken video preview, when user uploads
* Use local files for voice messages, when user uploads
* Fix store usage, when no preview is needed
⚠️ Technically, fallbackLocalUrl is not needed for upload rather than images, but if preview is available and server doesn't return it, client should fall back to mime icon anyway, so no need to duplicate it
-- | --
Voice messages | --
Video previews | --
> fix: localURL previews

- src/App.vue
- src/components/TopBar/TopBar.vue
* Removes gap left to conversation icon
* Removes gap under message input
-- | --
> fix: appearance of public conversation for guests

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoBottomBar.spec.js
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/TopBar/TopBarMenu.vue
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/stores/__tests__/callView.spec.js
- src/stores/callView.js
* Fix broken public share sidebar 
* init => import Vuex => import Pinia => import Vuex - breaking loop that should be avoided (until everything is migrated)
⚠️ server master branch (31) has now different behaviour for public shares, so testable only on stable30 (see backport)
-- | --
Errors in console | Working as expected
> fix: pass token to callView store via actions

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/utils/davUtils.ts
* Fix: https://github.com/nextcloud/talk-desktop/issues/824
> feat(chat): add download link to attachments

- src/components/NewMessage/NewMessageAttachments.vue
Just check the commit. The instance's name is useless. Elsewhere, in that kind of context, "... from Files" is used instead.
Test from reviewers are welcome.
* Fix #…
-- | --
---
> Share from Files wording fix (better consistency)

- src/components/TopBar/TopBarMenu.vue
> fix(TopBarMenu): check capabilities for downloading participants in call

- tests/integration/features/sharing-1/create.feature
- Ref https://github.com/nextcloud/server/pull/48381
Fixes https://github.com/nextcloud/spreed/actions/runs/11511042812/job/32043844236#step:13:3316
> fix(sharing): Align expected sharing behaviour after server change

- composer.lock
- lib/Model/Attachment.php
- lib/Model/Attendee.php
- lib/Model/Ban.php
- lib/Model/BotConversation.php
- lib/Model/BotServer.php
- lib/Model/Consent.php
- lib/Model/Invitation.php
- lib/Model/Poll.php
- lib/Model/ProxyCacheMessage.php
- lib/Model/Reminder.php
- lib/Model/RetryNotification.php
- lib/Model/Session.php
- lib/Model/Vote.php
> [main] Update nextcloud/ocp dependency

- src/components/PollViewer/PollViewer.vue
- src/utils/__tests__/calculateVotePercentage.spec.js
- src/utils/calculateVotePercentage.ts
* Fix #11867 
* Ref https://en.wikipedia.org/wiki/Quota_method
* Rounds up total to 100% for most cases. Keeps it lower if there is no possibility to add up to equally high values
-- | --
> fix: use method of largest remainder to count poll votes

- src/components/AvatarWrapper/AvatarWrapper.spec.js
- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/constants.js
- src/services/participantsService.js
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
> fix: e-mail guests - frontend 📧 (part 1)

- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
* Fix regression from #13518
-- | --
> fix: hide 'Browse drafts' button in Note to self and 1-1 rooms

- src/App.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/MediaSettings/MediaSettings.vue
- src/views/MainView.vue
* Ref #13485
* There's not much to be done on frontend side, applied it the same way we're using for `#direct-call`
> feat: show conversation settings, if URL hash is specified

- package-lock.json
- package.json
* Rate-limit image previews in FilePicker
🏡 After
> chore(deps): bump @nextcloud/dialogs library from 6.0.0 to 6.0.1

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/services/CapabilitiesManager.ts
- src/services/__tests__/coreService.spec.js
- src/services/conversationsService.js
- src/services/coreService.ts
* Fix #4937
* As for now participants added after conversation is created and token is known, that works the same way as adding participant from the right sidebar
* ~~If at least one participant is e-mail, create a public conversation instead of rewriting it later on backend~~
* Also extract API call for 'core/autocomplete/get' to not mix with conversation services
-- | --
> feat: invite email guests when creating a conversation

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Fix hover effect when image is not loaded yet
-- | --
> style: move a hover effect to image container

- src/App.vue
- src/composables/useDocumentTitle.ts
- src/views/SessionConflictView.vue
* Refactor document.title setting
* extract logic from App.vue component
* minimize computations, when not needed
* set and remove asterisk only when needed
* rely on Vue Router to get correct title parts
Better to check commits separately
* Duplicate session should be now correctly set on specified route
TODO:
> fix: move useDocumentTitle logic to composable

- src/components/RightSidebar/Participants/ParticipantsTab.vue
* Blocks non-moderators to send query requests from ParticipantsTab
> fix: non-moderators should not query participants from server

- css/icons.css
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- Ref #13606
- do not show as mail in mentions
- show correct color in popover
-- | --
> style: fix e-mail guests icons

- CHANGELOG.md
- fix(attachments): Fix a performance issue when opening the file picker in Talk [#13698](https://github.com/nextcloud/spreed/issues/13698)
- fix(meetings): Fix layout for guests on public conversations [#13552](https://github.com/nextcloud/spreed/issues/13552)
- fix(chat): Fix layout for guests on public conversations [#13620](https://github.com/nextcloud/spreed/issues/13620)
- fix(UI): Improve handling of sidebar on mobile view [#12693](https://github.com/nextcloud/spreed/issues/12693)
- fix(calls): Fix background blur performance if Server was not upgraded [#13603](https://github.com/nextcloud/spreed/issues/13603)
- fix(chat): Fix layout for guests on …
> chore(release): Add changelog for 18.0.13, 19.0.11 and 20.0.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(chat): Fix layout for guests on public conversations [#13620](https://github.com/nextcloud/spreed/issues/13620)
- fix(UI): Improve handling of sidebar on mobile view [#12693](https://github.com/nextcloud/spreed/issues/12693)
> chore(release): Bump version to 18.0.13

- src/PublicShareSidebar.vue
- src/components/CallView/CallFailedDialog.vue
- src/components/CallView/shared/EmptyCallView.vue
- src/components/TopBar/CallButton.vue
- src/services/callsService.js
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/utils/signaling.js
- src/utils/webrtc/index.js
- src/views/FilesSidebarChatView.vue
- src/views/MainView.vue
* Part of #13160
Before
https://github.com/user-attachments/assets/85d9db4c-d9fc-4ad1-bb9c-5c4ddf458121
After
https://github.com/user-attachments/assets/e108bb3f-2321-481f-a6d9-4d14a8e34bf9
> fix(Call): introduce intermediary phase before joining call

- src/composables/useIsInCall.js
* Fix creating a separate composable instance for each component it uses
-- | --
> fix: make useIsInCall a shared composable

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesList.vue
* Fix regression from #12550 
* listeners weren't removed from unmounted components
* Follow-up to 7bc38ae53f0fbf306de5e784413f5fa906185e7d
*  Toggle CSS class with native method rather than emitting event, which should be listened to all mounted components
> fix: reduce amount of EventBus listeners on messages

- css/publicshare.css
* remove empty space reserved for re-parented footer in public share
* Fixed differently in `main` branch
-- | --
> [stable30] style: fix public share layout

- src/components/AvatarWrapper/AvatarWrapper.spec.js
- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/CallView/shared/VideoVue.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/PollViewer/PollVotersDetails.vue
- src/components/Quote.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/composables/__tests__/useMessageInfo.spec.js
- src/composables/useMessageInfo.js
- src/utils/getDisplayName.ts
> fix: faulty avatars for guests and deleted users

- package-lock.json
- package.json
- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/NewConversationDialog/NewConversationSetupPage.vue
* Bumps vue-library [Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.19.0...v8.20.0)
> chore(deps): bump @nextcloud/vue lib from 8.19.0 to 8.20.0

- src/__mocks__/capabilities.ts
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/DangerZone.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/utils/conversation.js
* Set frontend code for unexisting (yet) capability
* Mock is kept so test won't fail
> fix: hide archive-conversations feature from 20.1.0rc1

- src/App.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/services/EventBus.ts
- src/services/__tests__/EventBus.spec.js
* Fix stray once event listeners, if they were never called
- test with joining call:
Before | After
-- | --
> fix: overwrite EventBus.off method to clear once events

- CHANGELOG.md
- feat(polls): Allow to draft, export and import polls [#13439](https://github.com/nextcloud/spreed/issues/13439)
- feat(voice-messages): Auto play voice messages which are grouped together [#13199](https://github.com/nextcloud/spreed/issues/13199)
- feat(calls): Allow moderators to download a call participants list [#13453](https://github.com/nextcloud/spreed/issues/13453)
- feat(calls): Allow to enforce a maximum call length [#13445](https://github.com/nextcloud/spreed/issues/13445)
- feat(chat): Add option to directly download attachments [Desktop #824](https://github.com/nextcloud/talk-desktop/issues/824)
- feat(calls): Add an option to always disable devices by default [#13446](https://github.com/nextcloud/spreed/issues/13446)
- feat(email-guests): Identify and recognize guests …
> chore(release): Add changelog for 20.1.0-rc.1

- src/composables/useChatMentions.ts
- src/composables/useDocumentTitle.ts
* Fix #13799 / regression from #13672
* don't show asterisk if lastMessageMap has 0 (federated conversation do not have last message id, so 0 will be stored in the map)
* Fix regression from #13778
* autocomplete federated users mentions with mentionId (for federated users mentionId contains prefix, which should be passed)
-- | --
> fix: minor regression fixes

- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Controller/ChatController.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/composables/useChatMentions.ts
- src/constants.js
- src/utils/textParse.ts
* Ref #13606
* fix e-mail guests mention parsing in chat messages (for both sides)
* fix e-mail guests parsing in NewMessage input (requires https://github.com/nextcloud-libraries/nextcloud-vue/pull/6233)
-- | --
---
> fix: e-mail guests parsing in chat messages

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/NewMessage/NewMessage.vue
* Fix #12008
-- | --
|![image](https://github.com/user-attachments/assets/0d643df2-f3b1-4897-af02-c498fc5a4c45)| ![image](https://github.com/user-attachments/assets/a31e3c13-f245-449e-923d-e66b4639a54c)|
> fix: improve silent message visibility 

- lib/Controller/ChatController.php
> fix(chat): Fix summarizing chats if there are blocks with only invisible messages

- lib/Service/RecordingService.php
- tests/php/Service/RecordingServiceTest.php
> fix(call): Add warning to AI summary and transcript

- docs/user-requirements.md
The minimum supported Android version for Nextcloud Talk app is Android 8.
> Update Minimum Android Version for Nextcloud Talk

- package-lock.json
- package.json
* Bump nextcloud vue library: [changelog](https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.21.0)
> chore(deps): bump @nextcloud/vue lib from 8.20.0 to 8.21.0

- src/components/TopBar/CallTime.vue
* Fix: https://github.com/nextcloud/spreed/issues/13427
Used a Arial for better visibility
-- | --
> fix(call): prevent call time jumping

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageAbsenceInfo.vue
- src/components/NewMessage/NewMessageChatSummary.vue
- src/constants.js
- src/services/coreService.ts
- src/services/messagesService.ts
- src/stores/chatExtras.js
- src/types/index.ts
* Ref #13430
* refactor unread marker styles
-- | --
> feat: add 'Generate summary' integration: frontend ✨

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Fix #13176
* No-whitespaces diff: https://github.com/nextcloud/spreed/pull/13862/files?w=1
-- | --
no | ![image](https://github.com/user-attachments/assets/3c3d3694-2aa5-475a-8f90-09cc8ba72131)
> fix: introduce submenu logic in Conversation component

- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- remove breakoutRooms logic from reused SendMessageDialog
> fix: delegate message posting from NewMessage to parent components

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/composables/useChatMentions.ts
Fix regressions from:
---
* https://github.com/nextcloud/spreed/pull/13778
* Shared composable is not called, if one instance of component already mounted.
* To test:
* open chat 1 with userList1 and '@' mention someone to get list of mentions
* start a call, end a call
* switch to chat 2 with userList2 and '@' mention someone 
* suggestions should be requested for chat 2, not chat 1
---
* https://github.com/nextcloud/spreed/pull/13862
* Conversation components should not keep internal value for notification level, but get it from store
* To test:
* open chat 1 and conversation settings
* set notification level settings to 'Off' and 'Off'
* open three-dot menu for same conversation -> Notifications
* settings should be 'Off' and 'Off', not what was at the mounting moment
---
* …
> fix: minor regressions

- appinfo/routes/routesRoomController.php
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/RoomController.php
- lib/Exceptions/GuestImportException.php
- lib/GuestManager.php
- lib/Service/ParticipantService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> feat(invitations): Allow importing CSV email lists

- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
- src/store/conversationsStore.js
* Fix #13651 
- Added `@valid`, `@invalid` handlers to ensure password meets policy requirements
- Moved success and error handling to store
https://github.com/user-attachments/assets/1ed6fe01-6bc3-441e-8bca-76fda648d27d
> fix: handle password policy validation

- src/components/CallView/CallView.vue
- src/components/MediaSettings/MediaSettings.vue
🏚️ Before 
If you have default device state to be off and you toggle either audio or video on before joining the call, your changes won't be considered
🏡 After
If you have default device state to be off and you toggle either audio or video on before joining the call, your changes will be considered
> fix: respect user changes of devices state when toggling it

- CHANGELOG.md
- feat(conversations): Add direct option to change notification settings to the conversation list again [#13870](https://github.com/nextcloud/spreed/issues/13870)
- feat(meetings): Allow importing email lists as attendees [#13882](https://github.com/nextcloud/spreed/issues/13882)
- fix(conversation): Fix password validation when setting a password [#13890](https://github.com/nextcloud/spreed/issues/13890)
- fix(calls): Don't disable microphone and camera when it was enabled in the device check [#13893](https://github.com/nextcloud/spreed/issues/13893)
- fix(chat): Hide "Generate summary" in federated conversations for now [#13881](https://github.com/nextcloud/spreed/issues/13881)
- fix(chat): Fix mention suggestions referring to participants of …
> chore(release): Add changelog for 20.1.0-rc.3

- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Exceptions/GuestImportException.php
- lib/GuestManager.php
- openapi-full.json
- openapi.json
- src/__mocks__/capabilities.ts
- src/components/ConversationSettings/LobbySettings.vue
- src/components/ImportEmailsDialog.vue
- src/components/RightSidebar/LobbyStatus.vue
- src/services/participantsService.js
- src/types/index.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/php/GuestManagerTest.php
- tests/php/data/import-valid-email-and-name.csv
- tests/php/data/import-valid-email-and-name.csv.license
- tests/php/data/import-valid-filter-duplicates-by-email.csv
- tests/php/data/import-valid-filter-duplicates-by-email.csv.license
- tests/php/data/import-valid-only-email.csv
- tests/php/data/import-valid-only-email.csv.license
* Ref #13451
* On top of API #13871
🏡 After | 🏡 After
-- | --
> feat(invitations): Import e-mail participants from CSV 🗒️ 

- lib/ResponseDefinitions.php
- lib/Service/RoomFormatter.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
- src/components/LeftSidebar/LeftSidebar.spec.js
- src/composables/useConversationInfo.js
- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- src/utils/getMessageIcon.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-3/lobby.feature
* Last step after #13837 before #13792
> fix(openapi): Remove lastMessage from TalkRoom object when empty

- CHANGELOG.md
- Introducing the Nextcloud Talk desktop client for Windows, macOS and Linux [Download](https://nextcloud.com/talk-desktop-install)
- feat(calls): Summarize call recordings automatically with AI when installed [#13429](https://github.com/nextcloud/spreed/issues/13429)
- feat(chat): Allow to summarize the chat history when there are many unread messages [#13430](https://github.com/nextcloud/spreed/issues/13430)
- feat(calls): Allow moderators to download a call participants list [#13453](https://github.com/nextcloud/spreed/issues/13453)
- feat(meetings): Allow importing email lists as attendees [#13882](https://github.com/nextcloud/spreed/issues/13882)
- feat(email-guests): Identify and recognize guests invited via email address [#6098](https://github.com/nextcloud/spreed/issues/6098)
- …
> chore(release): Add changelog for 20.1.0

- src/components/NewMessage/NewMessageAbsenceInfo.vue
> fix: out of office caption

- src/components/NewMessage/NewMessageAbsenceInfo.vue
- src/services/coreService.ts
- src/services/participantsService.js
- src/stores/__tests__/chatExtras.spec.js
- src/stores/chatExtras.js
- src/types/index.ts
* Show absence period (start and end date)
* Similar to https://github.com/nextcloud/talk-ios/pull/1899
* also add typings for out-of-office response
* Ref: https://github.com/nextcloud/documentation/pull/12406
Eng locale | Other locale
-- | --
> feat(ooo): Add start and end dates to out-of-office view

- lib/Service/ParticipantService.php
- tests/integration/features/chat-1/delete.feature
- Add users to a chat
- Purge history
- As user from step 1 try to load the chat
> fix(chat): Fix infinite loading spinner when someone cleared the history

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> chore(release): Bump version to 20.1.0

- src/components/ConversationSettings/Matterbridge/matterbridgeTypes.ts
> fix(Matterbridge): add a hint about Discord Channel ID usage

- lib/Controller/RoomController.php
- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/RecordingServers.vue
> fix: add admin setting for AI generated call recording summary

- lib/Notification/Notifier.php
> fix(summary): Don't add share button to failed summary notification

- appinfo/routes/routesCallController.php
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/CallNotificationController.php
- lib/Service/ParticipantService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/notifications.feature
- tests/integration/features/federation/call.feature
Just as I was about to send this PR, I remembered that we built https://github.com/nextcloud/notifications/blob/master/openapi.json#L742-L748
That should be sufficient here as well.
> feat(call): Direct endpoint to check if call notification should be dismissed

- src/components/SettingsDialog/SettingsDialog.vue
* Fix https://github.com/nextcloud/talk-desktop/issues/957
> fix(SettingsDialog): check capability for start without media

- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
- src/services/CapabilitiesManager.ts
- src/services/conversationsService.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/types/index.ts
- src/utils/generatePassword.ts
* Fix #13450
🏚️ Force password is disabled | 🏡 Force password enabled
-- | --
. | ![password-after2](https://github.com/user-attachments/assets/6b19a5bd-dee6-4443-acf1-e379d7d89b7f)
Public conversations without password | ![image](https://github.com/user-attachments/assets/00d67132-7032-4df2-8a0d-0bca1af2aede)
Password is missing (should not happen) | ![image](https://github.com/user-attachments/assets/df842b8d-a82f-4d53-ab92-a10087da9b61)
> Feat: add option to force password in public conversations

- appinfo/info.xml
- lib/Migration/FixLastReadMessageZero.php
**Repair step doc block**
- In previous versions of Talk, the value 0 was used to mark a chat as
completely unread. This meant that the next time a client/browser loaded the
chat it would start all from the beginning. However, there were various
issues over the time that made the frontend getting `null` or `undefined`
into the wrong place and then accidentally loading 8 years of chat from the
beginning. So it was agreed that the frontend manually blocks loading with
last-read-message=0 and the special cases use -2 for this situation.
> fix(chat): Add a repair-step to handle the last-read-message=0 case

- lib/Federation/CloudFederationProviderTalk.php
- lib/Model/AttendeeMapper.php
- lib/Model/InvitationMapper.php
- tests/integration/features/federation/invite.feature
- tests/psalm-baseline.xml
* Ref https://github.com/nextcloud/server/pull/49646
> fix(federation) Implement signing of federation requests in Talk

- lib/Controller/SignalingController.php
Currently guests with a display name are not cleaned up, to keep their name for chat messages and other activity.
1. Set up HPB
2. Create a conversation with public access
3. Join as a guest and set a name
4. Write a message
5. Reload the page
6. Check if the message from 4 still has the display name
x | Firefox | Chrome
---|---|---
Before | :white_check_mark: | :x:
After | :white_check_mark: |:white_check_mark: 
The main difference is that Firefox seems to keep the session and is still recognized as the previous guest, chrome creates a new attendees entry on each reload
- As this is the reaction to a request from the HPB no suitable test can be written.
> fix(guests): Don't force remove guests but leave it to the "purge logic"

- src/store/conversationsStore.js
* Backport of hardening from #13915 
* Throw error -> no response with empty token -> no BFP triggered
-- | --
> [stable30] fix(store): throw error from room creation to handle in component

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
> fix: remove "formatted" from copy message button

- lib/AppInfo/Application.php
- Moving Talk before Files (`0`)
- Have to move Dashboard (`-1`) ever further down, as there is currently no gap: https://github.com/nextcloud/server/pull/49915
> fix(navigation): Improve sort order of navigation entry

- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/utils/webrtc/SpeakingWhileMutedWarner.js
* Fix regression from #9336 
* Functionality was unclear, as passed via `this` and therefore it wasn't easy to track changes when moved to a new component
🏡 After
> fix(SpeakingWhileMutedWarner): show toast message 

- CHANGELOG.md
- perf(calls): Add endpoint for clients to specifically check if a call notification is still current [#13950](https://github.com/nextcloud/spreed/issues/13950)
- fix(chat): Add start and end of out-of-office to the note card in one-to-one conversations [#13926](https://github.com/nextcloud/spreed/issues/13926)
- fix(chat): Fix chats for offline participants when the chat history was reset [#13965](https://github.com/nextcloud/spreed/issues/13965)
- fix(calls): Remove "Share to chat" button from failure notifications of recording summaries [#13941](https://github.com/nextcloud/spreed/issues/13941)
- fix(calls): Hide option to start without enabled media when it can not be stored on the server …
> chore(release): Add changelog for 20.1.1

- appinfo/routes/routesBotController.php
- appinfo/routes/routesRecordingController.php
- lib/Model/BotServer.php
- lib/ResponseDefinitions.php
- openapi-full.json
- src/types/openapi/openapi-full.ts
- vendor-bin/openapi-extractor/composer.lock
> chore(deps): Update openapi-extractor to v1.3.0

- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/ConversationSettings/LobbySettings.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/NewMessage/NewMessage.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/UIShared/EditableTextField.vue
> fix: migrate Nc* components to v-model usage

- src/components/NewMessage/NewMessage.vue
* Follow-up to library bump (8.22)
* border-radius is set to upstream component (8px);
* max-height is set to upstream component (5.5 * 34px ~ 180px);
* padding is set with CSS variables;
-- | --
> fix(NewMessage): prevent placeholder content overflow

- docs/internal-signaling.md
- lib/SetupCheck/Configuration.php
- lib/SetupCheck/HighPerformanceBackend.php
- lib/SetupCheck/RecordingBackend.php
- lib/SetupCheck/SIPConfiguration.php
- lib/TInitialState.php
- src/components/AdminSettings/Federation.vue
- src/components/AdminSettings/HostedSignalingServer.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
- src/views/AdminSettings.vue
* Fix part 2 of #14018 
-- | --
**Beginning of the page**<br>
> Warn the admin when no High-performance backend is set up

- tests/integration/run.sh
```
System config value overwrite.cli.url set to string http://localhost:8080/
Resetting custom skeletondirectory so that tests pass
./run.sh: Zeile 120: config:system:delete: Befehl nicht gefunden
System config value overwrite.cli.url set to string http://localhost:8280/
```
And following that any integration test that checks files is failing.
- Follow up to the restructuring of https://github.com/nextcloud/spreed/pull/13967
> test: Fix local integration tests with custom skeleton directory

- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/SipSettings.vue
- src/types/index.ts
- src/utils/signaling.js
* Fix #13904
* Should be no visual changes
> fix(SIP): get dial-in info from signaling settings

- package-lock.json
- package.json
- src/components/CalendarEventsDialog.vue
- src/components/TopBar/TopBar.vue
- src/services/CalDavClient.ts
- src/stores/groupware.ts
- src/types/index.ts
- src/types/vendor/@nextcloud/cdav-library.d.ts
* Ref #6292
Light | Dark
-- | --
Trigger | Form
-- | --
> feat(meetings): Preview upcoming events

- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/RightSidebar/InternalSignalingHint.vue
- src/components/RightSidebar/RightSidebar.vue
- src/utils/signaling.js
- src/views/FilesSidebarChatView.vue
* Ref #14018
* Show warning during the call in group / public conversations, when only internal signaling is available
-- | --
Talk app | <img width="404" alt="image" src="https://github.com/user-attachments/assets/41cc9706-e873-4214-a83c-1c62ac06579f" />
Files app and sidebars | <img width="398" alt="image" src="https://github.com/user-attachments/assets/035327c8-7480-4784-8efc-90845a1c5cd2" />
> fix(signaling): add UI warning in call with 2+ participants

- lib/Controller/RoomController.php
- lib/Service/ParticipantService.php
- tests/integration/features/conversation-4/promotion-demotion.feature
- Join as a second user
- With the first user try to promote the second one
> fix(moderator): Allow promoting self-joined participants to moderators

- docs/participant.md
* Follow-up to https://github.com/nextcloud/spreed/pull/14079 to have it correctly documented on the legacy docs.
> fix(docs): Add self-joined user to bad request response

- src/components/RightSidebar/InternalSignalingHint.vue
> fix(hpb): Add a small heading to the call note

- lib/Federation/CloudFederationProviderTalk.php
* we can not test this as tests are done with `http://` which always has the protocol
* But this prevented Nimisha from joining our federation room:
- c.nc.c log: `Failed to send notification for share from https://s….nextcloud.com/, received status code 400`
- s.nc.c log: `entry  does not contains @`
> fix(federation): Fix compatibility with Nextcloud 30 when using https

- src/store/messagesStore.js
* Fix hanging interface when call with a lot of participants ended for everyone
* Client wait for signaling update (`usersInCallChanged`) to leave by itself
* Additionaly, system message in chat is a good equivalent of the fact call has ended
How to test: 
1) apply patch to imitate delay in receiving a signal
```diff
diff --git a/src/utils/webrtc/webrtc.js b/src/utils/webrtc/webrtc.js
--- a/src/utils/webrtc/webrtc.js	(revision c4a63ff18ae6aa83acb0f54e14c7d91832fabee5)
+++ b/src/utils/webrtc/webrtc.js	(date 1733849256161)
@@ -473,10 +473,12 @@
&& localUserInCall) {
console.info('Force leaving the call for current participant')
+		setTimeout(() => {
store.dispatch('leaveCall', {
token: store.getters.getToken(),
participantIdentifier: store.getters.getParticipantIdentifier(),
})
+		}, 3000) …
```
> fix: leave call from system message 'call_ended_everyone'

- src/utils/signaling.js
> fix: Remove unused function

- src/components/AdminSettings/SignalingServers.vue
- src/components/ConversationSettings/LobbySettings.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/store/participantsStore.js
* Fix 'email' writing (as in other translated strings)
> fix(i18n): replace 'e-mail' to 'email' in strings

- src/__mocks__/capabilities.ts
- src/components/CalendarEventsDialog.vue
- src/components/TopBar/TopBar.vue
- src/services/groupwareService.ts
- src/stores/groupware.ts
- src/types/index.ts
* Follow-up to #14008 
* API  #14073
> 📆 feat(meetings): Allow moderators to schedule a meeting

- lib/Controller/RoomController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> feat(meeting): Allow to give a list of attendee ids to invite 

- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/CalendarEventsDialog.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/services/groupwareService.ts
> feat(calendar): allow to select meeting attendees

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/constants.js
* Fix #11697
REMARK: avatar size was explicitly chosen 20px to match the appearance of settings LS, but we can make it EXTRA_SMALL (22px)
- Call and Favorite icons are 15px
- Status icon is reduced to 11px
Normal | Compact
--|--
> feat(conversations):  compact view

- src/components/CallView/shared/PresenterOverlay.vue
- src/components/CallView/shared/Screen.vue
* Fix overlay positioning
* Should not exceed `video__promoted` borders
* Should be initially positioned absolute
-- | --
> fix(PresenterOverlay): limit overlay to video_promoted wrapper borders

- src/components/AdminSettings/SignalingServer.vue
- src/utils/SignalingStandaloneTest.js
Allows to test websocket connection with HPB in Admin settings (before users will face it in Talk interface): client attempts to establish new websocket, then:
- clean close on success
- throw error if any
Small screen | Wide screen
-- | --
> fix(AdminSettings): test Websocket connection

- src/components/PollViewer/PollDraftHandler.vue
- src/init.js
- src/services/EventBus.ts
- src/utils/signaling.js
> fix(types): add typings for EventBus

- src/components/TopBar/TopBarMediaControls.vue
* Ref #14019
🏚️ Before | 🏡 After - focus is still in chat
Reproducable with static screenshare
> fix(popover): do not steal focus with connection warning

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/constants.js
* Follow-up to https://github.com/nextcloud/spreed/pull/14099
-- | --
> feat(compact): follow-up

- CHANGELOG.md
- Clarify the usage of the High-performance backend and warn when it's not configured [#14065](https://github.com/nextcloud/spreed/issues/14065)
- fix(moderation): Allow promoting self-joined users [#14082](https://github.com/nextcloud/spreed/issues/14082)
- fix(firstrun): Create default conversations when loading the dashboard [#14089](https://github.com/nextcloud/spreed/issues/14089)
- fix(archive): Don't add asterix to title for unread messages in archived conversations [#14102](https://github.com/nextcloud/spreed/issues/14102)
- fix(calls): Retain names of guests when they disconnect from the High-performance backend [#13983](https://github.com/nextcloud/spreed/issues/13983)
- fix(search): Add …
> chore(release): Changelog for 18.0.14, 19.0.12 and 20.1.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(calls): Retain names of guests when they disconnect from the High-performance backend [#13982](https://github.com/nextcloud/spreed/issues/13982)
- fix(search): Add pagination support to the conversation search in unified search [#14032](https://github.com/nextcloud/spreed/issues/14032)
- fix(setupcheck): Check server times of Webserver nodes and High-performance backend to be in sync [#14014](https://github.com/nextcloud/spreed/issues/14014)
- fix(moderation): Allow promoting self-joined users [#14080](https://github.com/nextcloud/spreed/issues/14080)
> Release 18.0.14

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(calls): Retain names of guests when they disconnect from the High-performance backend [#13983](https://github.com/nextcloud/spreed/issues/13983)
- fix(search): Add pagination support to the conversation search in unified search [#14033](https://github.com/nextcloud/spreed/issues/14033)
- fix(setupcheck): Check server times of Webserver nodes and High-performance backend to be in sync [#14015](https://github.com/nextcloud/spreed/issues/14015)
- fix(moderation): Allow promoting self-joined users [#14081](https://github.com/nextcloud/spreed/issues/14081)
- fix(calls): Fix "Talk while muted" toast [#14026](https://github.com/nextcloud/spreed/issues/14026)
- fix(firstrun): Create default conversations when loading the dashboard …
> Release 19.0.12

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Clarify the usage of the High-performance backend and warn when it's not configured [#14065](https://github.com/nextcloud/spreed/issues/14065)
- fix(moderation): Allow promoting self-joined users [#14082](https://github.com/nextcloud/spreed/issues/14082)
- fix(firstrun): Create default conversations when loading the dashboard [#14089](https://github.com/nextcloud/spreed/issues/14089)
- fix(archive): Don't add asterix to title for unread messages in archived conversations [#14102](https://github.com/nextcloud/spreed/issues/14102)
> Release 20.1.2

- lib/Federation/CloudFederationProviderTalk.php
Invitations are always stored with the protocol,
so when checking for invitations we use the original remoteServerUrl
which contains the protocol in http and https cases
> fix(federation): Fix protocol handling of invitations

- src/components/CalendarEventsDialog.vue
- src/components/UIShared/ContactSelectionBubble.vue
* Follow-up to #14097
-- | --
loader | ![image](https://github.com/user-attachments/assets/72a11b28-3717-45bc-ae52-dd20c39128ed)
> fix(meeting): adjust styles and wording

- lib/SetupCheck/HighPerformanceBackend.php
> fix(setupcheck): Downgrade setup check when warning opt-out is used

- src/components/ConversationSettings/BasicInfo.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
- src/constants.js
> fix: add max description length as a capability

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(search): Add message search to the right sidebar [#14125](https://github.com/nextcloud/spreed/issues/14125)
- feat(conversations): Add sample conversation mechanism [#14124](https://github.com/nextcloud/spreed/issues/14124)
- feat(calls): Add end-to-end encryption for calls with the High-performance backend [#14005](https://github.com/nextcloud/spreed/issues/14005)
- fix(federation): Fix federation from Nextcloud 30 to 31 with https [#14141](https://github.com/nextcloud/spreed/issues/14141)
- fix(conversations): Make compact list more compact and avatar bigger [#14118](https://github.com/nextcloud/spreed/issues/14118)
- fix(signaling): Test actual websocket connection in admin settings …
> chore(release): Prepare 21.0.0-beta.2

- package-lock.json
- package.json
- src/components/CallView/shared/Screen.vue
- src/components/SettingsDialog/SettingsDialog.vue
* Fix #12187
* On top of #14044
* chore(deps): install panzoom library v9.4.3
- library is 6kB, so nothing painful
* feat(Screen): allow to zoom and pan screenshare content
- zoom up to 8 times (only zoom-in)
- keep in bounds (to not move it away from view)
- only in Speaker view
https://github.com/user-attachments/assets/2a662c43-aed1-429d-a33b-9e5972df7daf
>  feat(Screen): allow to zoom and pan screenshare content

- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/sharing-1/create.feature
This field was changed so often in the server,
that we simply don't care any more. We want to test Talk, not normal user shares.
- https://github.com/nextcloud/server/pull/49898
- https://github.com/nextcloud/server/pull/48381
- https://github.com/nextcloud/spreed/pull/13632
* Make tests green again
> fix(tests): Remove unstable sharing field from tests

- css/icons.css
- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/CallButton.vue
> fix: inverse left arrow icons when it is RTL

- .github/workflows/integration-federation.yml
- .github/workflows/integration-mariadb.yml
- .github/workflows/integration-mysql.yml
- .github/workflows/integration-oci.yml
- .github/workflows/integration-pgsql.yml
- .github/workflows/integration-sqlite.yml
- docs/events.md
- docs/occ.md
- lib/Command/Bot/Install.php
- lib/Controller/BotController.php
- lib/Events/BotInvokeEvent.php
- lib/Model/Bot.php
- lib/Service/BotService.php
- tests/integration/features/chat-2/bots.feature
- tests/integration/run.sh
- tests/integration/talk_webhook_demo/appinfo/info.xml
- tests/integration/talk_webhook_demo/appinfo/routes.php
- tests/integration/talk_webhook_demo/lib/Controller/BotController.php
- tests/integration/talk_webhook_demo/lib/Migration/InstallBot.php
- tests/integration/talk_webhook_demo/lib/Migration/UninstallBot.php
- tests/integration/talk_webhook_demo/lib/Migration/Version1000Date20230719061613.php
- tests/integration/talk_webhook_demo/lib/Model/Bot.php
- tests/integration/talk_webhook_demo/lib/Model/LogEntry.php
- tests/integration/talk_webhook_demo/lib/Model/LogEntryMapper.php
- tests/integration/talk_webhook_demo/lib/Service/BotService.php
- tests/integration/talk_webhook_demo/lib/Service/SummaryService.php
- Sample bot https://github.com/nextcloud/command_bot
- Redoing the call_summary_bot in https://github.com/nextcloud/call_summary_bot/pull/110
> feat(bots): Event based bots

- src/components/AdminSettings/GeneralSettings.vue
- src/components/AdminSettings/HostedSignalingServer.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SIPBridge.vue
- src/components/AdminSettings/SignalingServers.vue
- src/env.d.ts
- src/services/EventBus.ts
- src/types/index.ts
- src/views/AdminSettings.vue
> fix(AdminSettings): move signaling state to the root

- docs/index.md
- docs/quick-install.md
- lib/Settings/Admin/AdminSettings.php
- lib/SetupCheck/HighPerformanceBackend.php
- lib/SetupCheck/RecordingBackend.php
- lib/SetupCheck/SIPConfiguration.php
- mkdocs.yml
- src/components/AdminSettings/SignalingServers.vue
- src/types/index.ts
- src/views/AdminSettings.vue
- tests/php/Settings/Admin/AdminSettingsTest.php
> docs: Add quick install

- src/components/MessagesList/MessagesList.vue
* Fix using of `from.params.token`
* 'params' is always an object including 'token'
* rest places are fine
* should only affect cases like 'open another conversation on another message_id', so not critical
> fix(MessagesList): adjust route params check

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
* Fix sudden appearing of archived conversations when searchbox is focused
* Focus should only disable filtering, but 'archived' is not a filter category, therefore should be hidden unless searched by name or in specific view
* Focus trap is always triggered when toggle navigation
* 'Archived conversation' does nothing when search, so should be hidden
* Focus search input on opening SearchMessagesTab
🏚️ Before (Note to self 📥)   | 🏡 After
-- | --
> fix: focus issue and minor enhancements

- appinfo/routes/routesPollController.php
- docs/capabilities.md
- docs/poll.md
- lib/Capabilities.php
- lib/Controller/PollController.php
- lib/Exceptions/PollPropertyException.php
- lib/Federation/Proxy/TalkV1/Controller/PollController.php
- lib/Model/Poll.php
- lib/Model/PollMapper.php
- lib/Service/PollService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-3/poll.feature
> feat(polls): allow editing of draft polls

- src/components/CallView/CallFailedDialog.vue
- src/components/TopBar/CallButton.vue
- src/composables/useHashCheck.js
- src/services/CapabilitiesManager.ts
- src/store/participantsStore.js
- src/stores/talkHash.js
- src/utils/signaling.js
- src/utils/talkDesktopUtils.ts
* On Talk Desktop it shouldn't say, "Reload the page". Instead, it must be "Restart the app".
* Module name might not be the best, but rushing before the string freeze to have the strings. Module/structure can be refactored afterwards.
> fix(desktop): change "reload page" messages to "restart app"

- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/CalendarEventsDialog.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
* Regresion from #14097
* Fix search in participants list for user with no moderator permissions
* `invitedActorId` is not provided to them
> fix: do not fail to filter if invitedActorId is not provided

- .github/workflows/integration-mariadb.yml
- .github/workflows/integration-mysql.yml
- .github/workflows/integration-oci.yml
- .github/workflows/integration-pgsql.yml
- .github/workflows/integration-sqlite.yml
- composer.lock
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-1/bots.feature
- tests/integration/run.sh
- tests/integration/talk_webhook_demo/appinfo/info.xml
- tests/integration/talk_webhook_demo/appinfo/routes.php
- tests/integration/talk_webhook_demo/lib/Controller/BotController.php
- tests/integration/talk_webhook_demo/lib/Migration/InstallBot.php
- tests/integration/talk_webhook_demo/lib/Migration/UninstallBot.php
- tests/integration/talk_webhook_demo/lib/Migration/Version1000Date20230719061613.php
- tests/integration/talk_webhook_demo/lib/Model/Bot.php
- tests/integration/talk_webhook_demo/lib/Model/LogEntry.php
- tests/integration/talk_webhook_demo/lib/Model/LogEntryMapper.php
- tests/integration/talk_webhook_demo/lib/Service/BotService.php
- tests/integration/talk_webhook_demo/lib/Service/SummaryService.php
> [stable29] Update nextcloud/ocp dependency

- lib/Service/RoomService.php
> fix: allow to create public room without password if password_policy enabled

- src/components/LeftSidebar/LeftSidebar.vue
> fix(LeftSidebar): remove outdated style

- lib/Command/Bot/Install.php
- lib/Events/BotInstallEvent.php
- lib/Listener/BotListener.php
- lib/Model/Bot.php
- lib/Service/BotService.php
* Noticed on prod when reinstalling call_summary_bot
> fix(bots): Fix default and restrict features of app bots when install with event

- package-lock.json
- package.json
- stylelint.config.js
* Add `csstools/use-logical`
Note: no auto-fix was performed. Some non-logical properties must be checked, for example, when they redefine external styles.
> chore(stylelint): add `csstools/use-logical`

- src/components/CalendarEventsDialog.vue
* Fix insertBefore method:
* Each inner dialog is replaced with comments in DOM, if v-if=false
* Now they're under a single template
To test:
- Open calendarevents dialog, then close
- Switch to conversation, with no moderator permissions (e.g. Changelog)
-- | --
> fix(CalendarEventsDialog): keep components in one node

- src/components/ChatView.vue
> fix(ChatView): center dragover on MessagesList only

- src/components/ImportEmailsDialog.vue
> fix(i18n): align 'importListDescription' format and example in string

- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/utils/webrtc/SpeakingWhileMutedWarner.js
> fix(SpeakingWhileMutedWarner): show warning in the popup

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/store/conversationsStore.spec.js
- src/store/messagesStore.spec.js
- src/store/participantsStore.spec.js
- src/utils/__tests__/formattedTime.spec.js
- src/utils/__tests__/prepareTemporaryMessage.spec.js
* Fix `Error: Uncaught [TypeError: Date.now is not a function]` (I hope 🤞🏽)
> fix(test): replace jest.spyOn with jest.useFakeTimers

- src/utils/webrtc/analyzers/AverageStatValue.js
- src/utils/webrtc/analyzers/AverageStatValue.spec.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.spec.js
Fixes (non-UI part of) #14019
There are some known false positives that cause the connection warning to be shown when the connection is fine:
- Stat timestamp may not be updated when the stats stall: sometimes the same number of packets is reported two times in a row. The code currently keeps the quality calculation on hold if the same number of packets is reported twice in a row until a third value is received, and then updates the quality based on that third value. In the past it was observed that when the stats stalled the timestamps were updated. However, it seems that it can also happen that the timestamp is also repeated, which messes with the calculations and causes the connection to be reported as very bad even if the same number of packets is reported twice in a row (which was …
> Fix (known) false positives in connection warning

- css/icons.css
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/composables/useChatMentions.ts
- src/constants.ts
- src/utils/textParse.ts
* Ref #12036 
* Relevant, but not required: #14204
* To test: uncomment `$mention['type'] === 'team' ||` and `&& !str_starts_with($search, 'team/')` in UserMention.php
-- | --
> fix(team): support team mentions on frontend

- CHANGELOG.md
- feat(chat): Support mentioning teams [#14259](https://github.com/nextcloud/spreed/issues/14259) [#14260](https://github.com/nextcloud/spreed/issues/14260)
- fix(UI): Fix multiple right-to-left issues [#14235](https://github.com/nextcloud/spreed/issues/14235) [#14256](https://github.com/nextcloud/spreed/issues/14256)
- fix(meetings): Allow creating conversations when password policy app is enabled [#14227](https://github.com/nextcloud/spreed/issues/14227)
- fix(calls): Fix multiple false-positives when showing the connection warning [#14252](https://github.com/nextcloud/spreed/issues/14252)
- fix(bots): Fix installing PHP event bots via an event [#14231](https://github.com/nextcloud/spreed/issues/14231)
> chore(release): Changelog 21.0.0-rc.2

- src/components/ChatView.vue
> fix(ChatView): adjust dragover position

- src/components/CallView/shared/VideoVue.spec.js
- src/components/MessagesList/MessagesList.vue
- src/test-setup.js
Fix breaking the list scrolling when input height changes from:
- multiline message
- reply to
- typing indicator
- e.t.c.
🏚️ Before
https://github.com/user-attachments/assets/d567b660-f7bf-46d7-92eb-2c6216cdb8c0
🏡 After
https://github.com/user-attachments/assets/21236d4a-8e80-4d6d-8d68-8f0ca1ee600a
> fix(MessagesList): keep chat at the bottom when list height is changing

- src/components/GuestWelcomeWindow.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/SetGuestUsername.vue
- Loading should be with ellipsis
- 'Log in': action, 'Login': noun
> fix(i18n): minor string fixes

- src/components/CallView/shared/Screen.vue
* Fix #14243
* 👀 Zoom factor is 4, which is the middle between min/max boundaries
* 🧪 First double-click zooms in to 4x scale, second (or first one, if you already scaled) - resets to default
https://github.com/user-attachments/assets/e15f32c3-5b11-463a-be28-f7a2be8252d2
> fix(Screen): change double-click behaviour for screenshare panzoom

- lib/Controller/SignalingController.php
- tests/php/Controller/SignalingControllerTest.php
This pull request addresses the review comments from https://github.com/nextcloud/spreed/pull/8020 (the original branch could not be pushed to, so I had to create a new branch).
[As explained in the review](https://github.com/nextcloud/spreed/pull/8020#discussion_r984577745) I have adjusted the signaling settings returned by the server so the STUN and TURN servers do not contain empty or invalid `urls`. With that change it is no longer needed to guard setting `iceServers` in the frontend, so I reverted those changes. I have squashed everything into the first commit, slightly adjusted its message to reflect the changes done to the code and pushed the branch again after rebasing. @pboguslawski I hope that is fine :-)
Now `stunservers` and `turnservers` will be an empty array if the URL is …
> Empty iceServers.urls handling fix (reloaded)

- lib/Dashboard/TalkWidget.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/archive.feature
- tests/integration/features/integration/dashboard.feature
> fix(dashboard): Hide archived conversations from dashboard unless mentioned

- .github/workflows/psalm.yml
- composer.json
- lib/Controller/RecordingController.php
- lib/Controller/SignalingController.php
- psalm.xml
- tests/psalm-baseline.xml
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
> ci: Update psalm to v6

- src/components/NewMessage/NewMessageAbsenceInfo.vue
> fix(absence): Don't break when you are the absence or it's recursion

- lib/Events/BotInvokeEvent.php
- lib/Service/ActivityPubHelper.php
- lib/Service/BotService.php
- tests/psalm-baseline.xml
* Fix #14285 
Allows bots to do things like:
Person using the bot | Original author being assisted
---|---
> feat(bots): Let bots know the parent message when it was a reply

- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Federation/Proxy/TalkV1/UserConverter.php
- tests/integration/features/callapi/notifications.feature
- tests/integration/features/chat-1/delete.feature
- tests/integration/features/chat-1/edit-message.feature
- tests/integration/features/chat-1/file-share.feature
- tests/integration/features/chat-1/note-to-self.feature
- tests/integration/features/chat-3/poll.feature
- tests/integration/features/chat-3/reaction.feature
- tests/integration/features/chat-4/rich-messages.feature
- tests/integration/features/chat-4/rich-object-share.feature
- tests/integration/features/chat-4/unread-messages.feature
- tests/integration/features/command/user-remove.feature
- tests/integration/features/conversation-1/avatar.feature
- tests/integration/features/federation/chat.feature
- tests/integration/features/federation/invite.feature
- tests/integration/features/federation/poll.feature
- tests/integration/features/sharing-1/delete.feature
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Chat/Parser/UserMentionTest.php
> feat(chat): Add the mention id to parameters for easier editing

- CHANGELOG.md
- feat(bots): Let bots know when a message was a reply [#14310](https://github.com/nextcloud/spreed/issues/14310)
- fix(calls): Adjust double-click behaviour when zooming screenshares [#14284](https://github.com/nextcloud/spreed/issues/14284)
- fix(chat): Fix double scroll bar [#14265](https://github.com/nextcloud/spreed/issues/14265)
- fix(chat): Keep chat position at the bottom when the chat list height expends [#14268](https://github.com/nextcloud/spreed/issues/14268)
- fix(chat): Fix missing "Copy code" in some cases [#14308](https://github.com/nextcloud/spreed/issues/14308)
- fix(archive): Hide archived conversations from dashboard unless mentioned [#14299](https://github.com/nextcloud/spreed/issues/14299)
- fix(chat): Add mention-id to …
> chore(release): Add changelog 21.0.0-rc.3

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(bots): Let bots know when a message was a reply [#14310](https://github.com/nextcloud/spreed/issues/14310)
- fix(calls): Adjust double-click behaviour when zooming screenshares [#14284](https://github.com/nextcloud/spreed/issues/14284)
- fix(chat): Fix double scroll bar [#14265](https://github.com/nextcloud/spreed/issues/14265)
- fix(chat): Keep chat position at the bottom when the chat list height expends [#14268](https://github.com/nextcloud/spreed/issues/14268)
- fix(chat): Fix missing "Copy code" in some cases [#14308](https://github.com/nextcloud/spreed/issues/14308)
- fix(archive): Hide archived conversations from dashboard unless mentioned [#14299](https://github.com/nextcloud/spreed/issues/14299)
- fix(chat): Add mention-id to …
> Release 21.0.0 rc.3

- src/App.vue
- src/components/CallView/shared/PresenterOverlay.vue
- src/components/MessagesList/MessagesList.vue
* Fix regression after RTL changes
* `isRTL is a function, so direct check without calling returns `true`
* Dropped some resize listeners, as they are not used, or duplicating ResizeObserver functionality
-- | --
> fix(PresenterOverlay): fix RTL check

- src/components/ConversationIcon.vue
* Fix #13324
* See icon in TopBar for better reference
* Also add failed state and fallback in case avatar wasn't loaded
-- | --
Failed state | --
> fix(ConversationIcon): get rid of grey hairline, provide a fallback icon

- docs/bots.md
- docs/constants.md
- docs/occ.md
- lib/Command/Bot/Install.php
- lib/Command/Bot/State.php
- lib/Events/BotInvokeEvent.php
> docs(bots): Update documentation for bots

- lib/Collaboration/Collaborators/Listener.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/add-participant.feature
> fix(teams): Filter out already added teams from invite suggestions

- lib/Controller/ChatController.php
- src/composables/useMessageInfo.js
- src/constants.ts
> fix(chat): Allow to edit messages of bots in one-to-one conversations

- lib/AppInfo/Application.php
- lib/Listener/CircleEditedListener.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-5/team-participants.feature
- tests/psalm-baseline.xml
* Add a team to a conversation
* Rename the team
* Check name in chat where it was added or mentioned :checkered_flag: 
* Check name in participant list, before :boom: after :checkered_flag:
> fix(teams): Track team name updates

- src/composables/useMessageInfo.js
- Regression from #14344 
Noticed on the backport to 29 that I forgot the "IN one-to-one" part.
> fix(chat): Correctly limit editing to bots IN 1-1

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
* Partial backport of #12767 
* Includes 8e5a9d1, 073a9b0, cb3a7fa
-- | --
> [stable29] style: make type icon in LeftSidebar blend with background

- src/components/CallView/shared/PresenterOverlay.vue
* Fix placing presenter video out of visible bounds while screensharing
* Parent size is recalculated after mounting, which results in smaller parentHeight than actual -> moveVertically pushes it behind the CallView
🏚️ Before 
https://github.com/user-attachments/assets/4af0ca81-f779-424e-8d06-2aaf7cfa16df
🏡 After
https://github.com/user-attachments/assets/d1e54469-94d5-4f63-8a89-1db9800c59eb
> fix(PresenterOverlay): do not move component to negative values

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(bots): Allow users to edit messages of bots in one-to-one conversations [#14360](https://github.com/nextcloud/spreed/issues/14360)
- fix(calls): Address some false positives when showing the connection warning [#14250](https://github.com/nextcloud/spreed/issues/14250)
- fix(conversation): Don't suggest teams that are already added to the conversation [#14347](https://github.com/nextcloud/spreed/issues/14347)
> Release 19.0.13

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(bots): Allow users to edit messages of bots in one-to-one conversations [#14352](https://github.com/nextcloud/spreed/issues/14352)
- fix(calls): Address some false positives when showing the connection warning [#14251](https://github.com/nextcloud/spreed/issues/14251)
- fix(dashboard): Hide archived conversations from dashboard unless mentioned [#14298](https://github.com/nextcloud/spreed/issues/14298)
- fix(conversation): Don't suggest teams that are already added to the conversation [#14348](https://github.com/nextcloud/spreed/issues/14348)
- fix(chat): Fix missing "Copy code" button when syntax is used [#14309](https://github.com/nextcloud/spreed/issues/14309)
> Release 20.1.4

- src/services/CalDavClient.ts
* Fix https://github.com/nextcloud/talk-desktop/issues/1031
> fix(CalDavClient): handle XHR errors internally on Desktop client

- CHANGELOG.md
- feat(bots): Allow bots to get invoked for reactions [#14336](https://github.com/nextcloud/spreed/issues/14336)
- fix(bots): Allow users to edit messages of bots in one-to-one conversations [#14353](https://github.com/nextcloud/spreed/issues/14353)
- fix(conversation): Correctly update team names after being edited [#14358](https://github.com/nextcloud/spreed/issues/14358)
- fix(conversation): Don't suggest teams that are already added to the conversation [#14349](https://github.com/nextcloud/spreed/issues/14349)
- fix(meetings): Fix calendar integration for Desktop client [#14379](https://github.com/nextcloud/spreed/issues/14379)
- fix(calls): Fix issues with presenter overlay [#14330](https://github.com/nextcloud/spreed/issues/14330) …
> chore(release): Add changelog for 21.0.0-rc.4

- src/components/NewMessage/NewMessage.vue
- src/utils/selectionRange.ts
* Fix https://github.com/nextcloud/spreed/issues/4265
Preserve new message input's selection (caret position) on blur and restore on focus.
Currently only useful for emoji picker, but can be useful in other inserts.
Using preserved selection, emoji picker inserts the selected emoji in the correct position.
**Additional change:** after the emoji picker close, the focus returns to the field.
Works:
- In the end
- In the middle
- With replace
- Having new lines and mentions (without adding `<br>`)
- Opening the picker by mouse, by SHIFT+Tab + Enter
- Closing the picker by ESC, by click outside, by click on the trigger
> fix(chat): preserve selection (caret) on new message input

- package-lock.json
- package.json
* bump nextcloud/vue from 8.22.0 to 8.23.1
-- | --
Screenshot before | ![image](https://github.com/user-attachments/assets/2a23d020-34a2-4394-99b6-7feb2b0267a6)
a | ![image](https://github.com/user-attachments/assets/ae6e4a4b-7b75-4832-8151-2b171bc20cc5)
> chore(deps): bump nextcloud/vue from 8.22.0 to 8.23.1

- src/components/TopBar/CallButton.vue
- src/services/CapabilitiesManager.ts
- src/services/__tests__/CapabilitiesManager.spec.js
- src/stores/__tests__/federation.spec.js
- src/stores/federation.ts
- src/stores/talkHash.js
- src/test-setup.js
* Ref #14201
* Ref #12885
* make a deep comparison of old and new remote capabilities (omitting local ones), to see if there are actual changes that might require a reload of page or rejoining
* move toast message handling to the store, reset on leaving conversation and on following checks (next join)
* when accepting an invitation from federated server, immediately fetch remote capabilities for it, so we know them  before joining. 
-- | --
Toast message | Less of it
> fix(capabilities): make a deep comparison

- src/components/AdminSettings/TurnServer.vue
- src/components/CalendarEventsDialog.vue
- src/components/ConversationSettings/LobbySettings.vue
- src/components/LobbyScreen.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessageAbsenceInfo.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/store/participantsStore.js
- src/utils/__tests__/formattedTime.spec.js
- src/utils/formattedTime.ts
- src/utils/signaling.js
- Ref #14434
- Replace some of `@nextcloud/moment` functionality:
- formatter `moment().unix()` replaced with `convertToUnix()` util
- same done for all `timestamp / 1000`
- constructor `moment.unix(arg)` returns the same result as `moment(arg * 1000)`
No visual change
> fix: replace moment.unix()

- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.spec.js
Follow up to #14095
The stats were supposed to be distributed once they had changed, but in practice they were always distributed, as the packet count is absolute rather than relative. Nevertheless, if the packet count did not change distributing them would have no effect. The problem could appear in the (rare) case of the timestamps not being updated three times in a row, as the distribution algorithm failed if the final timestamp was the same as the initial timestamp (causing `NaN` to be set for the packets and packets lost).
Due to all that now the staged stats are always distributed before being commited (which is still done when the stats stalled for two seconds), although the distribution exits early if the timestamps did not change.
> Fix distributing staged stats when not updated three times in a row

- CHANGELOG.md
- fix(chat): Mark mentions of teams you are a part of primary [#14455](https://github.com/nextcloud/spreed/issues/14455)
- fix(federation): Fix "remote server was updated" shown too frequently [#14389](https://github.com/nextcloud/spreed/issues/14389)
> chore(release): Add changelog for 21.0.0-rc.5

- src/stores/__tests__/chatExtras.spec.js
- src/types/index.ts
- src/utils/__tests__/textParse.spec.js
- src/utils/textParse.ts
> fix(textParse): use mention id to parse message parameters

- src/components/CalendarEventsDialog.vue
- src/components/ConversationSettings/LobbySettings.vue
- src/components/LobbyScreen.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/composables/useMessageInfo.js
- src/utils/formattedTime.ts
* Ref #14434 
* Now only `moment.format()` is left for human-readable string to be replaced
> fix: replace moment objects comparison

- src/FilesSidebarTabApp.vue
- src/components/MessagesList/MessagesList.vue
- src/constants.ts
- src/services/__tests__/messagesService.spec.js
- src/services/messagesService.ts
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
- Non-breaking pre-requisite to #10084
- I'm giving up and will implement it by parts 👀 
- rename `getNewMessages` and `lookForNewMessages` to `pollNewMessages` (to avoid confusion - get*Messages should not poll)
- drop `lookForNewMessages` component method as redundant
- `_isBeingDestroyed`, `_isDestroyed` are internal Vue flags, different in Vue3, and not needed here
- refactor `fetchMessages` to support both direction of `lookIntoFuture` (to make fetching the chunk of **new** messages possible)
- refactor tests
> fix(MessagesList): rename method to pollNewMessages

- lib/Chat/Parser/SystemMessage.php
- tests/integration/features/command/user-remove.feature
- tests/integration/features/command/user-transfer-ownership.feature
* Fix #14056 
* Further simplification can be considered when the behaviour of 1-1 calls is (ever) changed to end the call if one person hangs up, or declines.
-- | --
> fix(call): Simplify wording for one-to-one calls

- lib/Controller/RoomController.php
- lib/Federation/Proxy/TalkV1/ProxyRequest.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
* Fix https://github.com/nextcloud/spreed/issues/12803
> feat(conversation): add federated typing indicator

- src/components/LeftSidebar/LeftSidebar.vue
* Fix expanding the searchbar and covering focus buttons on any focus (any sidebar open)
* Now it's expanded only when there's an actual search query
* searchResultsConversationList is used only when `isSearching` is true, so there's no need for a focus check
-- | --
> fix(LeftSidebar): do not expand empty search bar when focused

- docs/sample-conversations.md
- docs/samples/en/lets-get-started.md
- lib/Service/SampleConversationsService.php
- tests/integration/features/bootstrap/FeatureContext.php
> [l10n]: Change apostrophe

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* Follow-up to #14266
* Keeps node reference for ResizeObserver after switching conversations
* Ensure non-scrollable chat doesn't have 'scroll to bottom' button
* Fix #14392 🚧
* `setChatScrolledToBottom(false)` should be only set on scroll up (if we're scrolling down. it should be already set)
🏡 After
https://github.com/user-attachments/assets/0cdcac86-e967-43e4-a894-94f5b5861c86
> fix(MessagesList): fix resizeObserver and scrolledToBottom state update

- lib/Service/RoomFormatter.php
- tests/integration/features/conversation-3/lobby.feature
* Ref #14368 
* When moderator disables lobby, user receive updated common room properties via HPB signaling message. If lobbyState changes to 0, that unlocks chat messaging. But user-level parameters, like `lastReadMessage === 0`, and some other are not updated, thus blocking getting the message context
> fix(LeftSidebar): fetch room if user was in the lobby

- src/App.vue
* A good addition before #14406
> feat(App): add escape shortcut to go to root

- .github/workflows/update-nextcloud-openapi.yml
* Action was using server as repo: https://github.com/nextcloud/spreed/actions/runs/13612031198/job/38050450540
```sh
/usr/bin/git config --local --get remote.origin.url
https://github.com/nextcloud/server
```
Maybe this time it'll work 🤞🏽
> fix(update/openapi): make PR from spreed Git repo

- lib/Chat/ChatManager.php
- lib/Chat/CommentsManager.php
- lib/Search/MessageSearch.php
- tests/integration/features/chat-4/search.feature
* Fix #11281 
Before | After
---|---
> fix(search): Include captions in message search

- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
Required fixes to make parsing work with https://github.com/nextcloud/openapi-extractor/pull/214.
> fix(OpenAPI): Fix docs to be parsable with phpdoc-parser v2

- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
fix multiple issues with participants virual list
- detect self with immediate data (do not rely on sessionId, as its update could be delayed, and client does not know if you is you)
- rerender virtual list when switch conversations (Recycle scroller is keeping items in the poll and reuse them, which may differ and interfere with actual list of participants from another conv)
- reset initial state of component if reused (same as above - Removed user from the list may be replaced by any other user from poll (usually first in the list) with open dialog and possibility to remove self)
To reproduce:
1. Open conversation 1
2. Switch to conversation 2
3. Open a dialog for deleting participant from conv2
4. Click 'Back' in browser, to return to previous route
-> dialog should dissapear if …
> fix(Participant): unexpected change of participant to be removed and users can ban themself

- lib/Controller/RoomController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> fix(openapi): Fix deprecation syntax after openapi-extractor change

- openapi-full.json
- src/types/openapi/openapi-full.ts
- vendor-bin/openapi-extractor/composer.json
- vendor-bin/openapi-extractor/composer.lock
Fix https://github.com/nextcloud/openapi-extractor/issues/222
> chore(openapi): Update openapi-extractor to 1.5.1 to fix openapi-full.json

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix UX interactions with 'Generate chat summary" button
🏡 After
> fix(Message): show loading spinner when request chat summary

- src/__mocks__/capabilities.ts
- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/services/conversationsService.ts
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Follow up to #14579
* Prerequisite to #14399
Advanced creation reduces amount of server requests:
- Before: `1..5` requests for setup + `N` for participants
- After: `1` request only (+`1` if avatar is picture - not supported by API)
> fix: expose 'createConversation' method

- CHANGELOG.md
- fix(calls): Improve call related system messages in one-to-one conversations [#14495](https://github.com/nextcloud/spreed/issues/14495)
- fix(search): Include caption messages in search results [#14553](https://github.com/nextcloud/spreed/issues/14553)
- fix(chat): Show loading spinner when requesting AI chat summary [#14625](https://github.com/nextcloud/spreed/issues/14625)
- fix(chat): Correctly start loading the chat when the lobby is removed [#14517](https://github.com/nextcloud/spreed/issues/14517)
- fix(dashboard): Hide lobbied conversations from the dashboard [#14612](https://github.com/nextcloud/spreed/issues/14612)
- fix(federation): Fix broken participant avatar when federated instance is down …
> chore(release): Add changelog for 19.0.14, 20.1.5 and 21.0.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(search): Include caption messages in search results [#14551](https://github.com/nextcloud/spreed/issues/14551)
- fix(conversation): Stay in chat when removing a group or team the moderator is a member of [#14395](https://github.com/nextcloud/spreed/issues/14395)
- fix(dashboard): Hide lobbied conversations from the dashboard [#14610](https://github.com/nextcloud/spreed/issues/14610)
- fix(calls): Further improve false positives when showing the connection warning [#14448](https://github.com/nextcloud/spreed/issues/14448)
- fix(reminder): Log when generating a reminder failed [#14616](https://github.com/nextcloud/spreed/issues/14616)
> Release 19.0.14

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(calls): Improve call related system messages in one-to-one conversations [#14495](https://github.com/nextcloud/spreed/issues/14495)
- fix(search): Include caption messages in search results [#14553](https://github.com/nextcloud/spreed/issues/14553)
- fix(chat): Show loading spinner when requesting AI chat summary [#14625](https://github.com/nextcloud/spreed/issues/14625)
- fix(chat): Correctly start loading the chat when the lobby is removed [#14517](https://github.com/nextcloud/spreed/issues/14517)
- fix(dashboard): Hide lobbied conversations from the dashboard [#14612](https://github.com/nextcloud/spreed/issues/14612)
- fix(federation): Fix broken participant avatar when federated instance is down …
> Release 21.0.1

- src/App.vue
- src/components/Quote.vue
* Fix scrolling to another message in call, when navigating via quote or link
* Quote was hard-fixed, reverted now
> fix(call): do not show warning for the same conversation

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Listener/CalDavEventListener.php
- lib/Room.php
- lib/Service/RoomService.php
- psalm.xml
- tests/php/Listener/CalDavEventListenerTest.php
- tests/psalm-baseline.xml
- tests/stubs/oca_dav_caldav_timezoneservice.php
* Needs https://github.com/nextcloud/calendar/pull/6768
* Fix #14402
> feat(conversations): handle event conversation rooms

- src/App.vue
- src/components/UIShared/ConfirmDialog.vue
- src/store/participantsStore.js
* Fix deprecated syntax, replacing with custom component
* since Nc 30 `OC.dialogs.confirmDestructive` uses the same Dialog constructor
To test: modify store action with following:
```js
async joinConversation(context, { token }) {
const forceJoin = SessionStorage.getItem('joined_conversation') === token
if (!forceJoin) {
await context.dispatch('confirmForceJoinConversation', { token })
return
}
try {		
...
```
-- | --
oc-dialog-dim is deprecated, reloads after 3 seconds | works as expected
> fix: migrate from deprecated OC.dialogs.confirmDestructive

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/Grid/gridPlaceholders.ts
* replace `window.addEventListener('resize')` with `ResizeObserver`
* `$refs.grid` is rendered conditionally, so we might lose a reference to it once mounted
* 1 listener instead of 2, looks only for exact DOM element
* fix video cropping at the last row
* drop redundant method and store getter
* cleanup comments
* improve DX by exposing (in debug mode only):
* `OCA.Talk.gridDebugInformation`
* `OCA.Talk.gridDevModeEnable`
-- | --
> fix(Grid): fix cropped videos in the last row

- src/components/AdminSettings/GeneralSettings.vue
* Fix #14672 
* Same check as used in encryption module:
https://github.com/nextcloud/spreed/blob/938cc9854f8127386b088c1a727c02551d194fce/src/utils/e2ee/encryption.js#L66
> fix(AdminSettings): respect initial state of E2EE setting

- src/store/messagesStore.js
* Fix #14670
**Explanation:**
Own message can be added to polling response (1) before receiving the message creation response (2), the bot will thus react before (2) and another polling response will be received containing the bot reaction system message (3). 
The final order is: (1) -> (3) -> (2) 
We always update by the recent response, which is (2) in this case and it's outdated. 
**Workaround:**
As own message in polling is always up to date (e.g. contains reactions), we skip the update with (2) when (1) is already received.
🏚️ Before 
https://github.com/user-attachments/assets/6ba4ac9e-eb16-41d6-b37c-a94d3d1ae302 
🏡 After
https://github.com/user-attachments/assets/a287769d-f81f-4210-bf4b-f4d8898348a9
> fix(messages): fix missing instant reactions for own message

- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageAudioRecorder.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/UIShared/EditableTextField.vue
- src/main.js
- src/mainAdminSettings.js
- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/mainRecording.js
* Fix #12033
* Directive was only declared in MatterbridgeSettings.vue, which made it work in main app (without it nothing works 🙈)
* stable30+ are not affected, as we replaced tooltips with native titles or NcPopover
-- | --
Files sidebars (3/3) | --
Admin settings | --
> [stable29] fix: show tooltips in sidebar (from Vue directive)

- src/components/PollViewer/PollViewer.vue
* Fix un-showable intermediate results in open anonumous polls
-- | --
> fix(PollViewer): hide intermediate results from anonymous polls

- css/publicshare.css
> [stable30] style: drop redundant overrides for public shares

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
- src/components/UIShared/SearchBox.vue
- src/types/vendor/vue-virtual-scroller.d.ts
* Fix #14415
Rendering went from `n` items rendered out of `n` (100%) to 15-30 items out of `n` items. 
-- | --
> feat: reduce items rendering in left sidebar search results

- src/utils/signaling.js
After the signaling session was resumed the list of known participants was reset to the next received list of joined users, as it was expected that the `join` event included the full list of participants currently in the room. This was introduced when support for the external signaling server was added in Talk, and back then it may have worked as expected. However, in current signaling server versions when a `join` event is received after the session was resumed it only includes the participant that was just added, rather than the full list (like any other `join` event except the first one received after joining a room). Therefore all the previous participants in the room are seen as leaving the room, which would cause, for example, that they are removed from the call view. Due to that …
> fix: Do not reset previous users after a resume

- src/PublicShareSidebarTrigger.vue
- src/components/SetGuestUsername.vue
* Ref #12159 
* Fix #14694
-- | --
> [stable29] fix: public share style and guest actions fixes 

- lib/Controller/RoomController.php
- Requires: https://github.com/nextcloud/server/pull/51501
- Resolves: https://github.com/nextcloud/calendar/issues/6819
Event status should be set on new events, the organizer should also not be added as a participant.
> fix: do not add organizer as attendee and set status

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
- src/components/NewMessage/NewMessageAbsenceInfo.vue
- src/components/NewMessage/NewMessageChatSummary.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/UIShared/DialpadPanel.vue
* Fix: missing aria-labels for button components
* Actually fix: yellow warnings in console
> fix(a11y): provide missing aria-labels to buttons with no visible text

- lib/Federation/CloudFederationProviderTalk.php
In case the in_call update arrives before the actual active_since update, we fake the timestamp so we at least don't fail the request. When the active_since finally arrives we merge the results.
* Fix #14623
> fix(federation): Heal request order for slow federation connections

- lib/Controller/RoomController.php
- lib/Service/RoomFormatter.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
This is useful e.g. when only showing a compact list
> feat(conversations): Allow to not request the last message when getting rooms

- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Collaboration/Reference/TalkReferenceProvider.php
- lib/Controller/ChatController.php
- lib/Dashboard/TalkWidget.php
- lib/Events/MessageParseEvent.php
- lib/Notification/Notifier.php
- lib/Service/BotService.php
- lib/Service/RoomFormatter.php
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Controller/ChatControllerTest.php
In some cases we only use the "plain text" version of a chat message. We can render the conversation list subline without knowing the exact path and permissions of a file. All other information is still available on the cache entry. The path is only needed in some special cases when afterwards the viewer is proposed to the user.
- As user1 create a conversation with only yourself and upload test.txt
- As user2 create a conversation with user1 and upload test.txt
- As user2 go to your Files app and change the share permissions to view-only
- As user1 check the message parameters from the last message of the conversation and compare them with the message parameters from the chat request: path should be "test.txt instead of Talk/test.txt" and permissions are "27 instead of 1"
> fix(performance): Parse file shares inaccurately to prevent setupFS

- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Follow-up to #14772
https://github.com/user-attachments/assets/261dfd22-a199-4036-a909-6d492fa7d616
* Has no effect without backend, so should be safe for Desktop client?
* Shows a fallback for a moment when switching from 'compact-mode' - acceptable?
> feat(conversations): do not request last message when in compact mode

- src/utils/webrtc/webrtc.js
When the local participant is in the call and a signaling message does not list the participant as being in the call the call is left (as it is assumed that, for example, the participant was kicked out from the call by a moderator). During a forced reconnection the local participant was not marked as "not in the call" when the call was left, so in the time between sending the request to join the call again and receiving a signaling message confirming that the call was joined another signaling message that does not list the participant yet as in the call caused the UI to leave the call (for example, if another participant also joined).
Although the window for the issue is very narrow the chances increase when there are a lot of participants. Nevertheless, the steps below force the issue by …
> Fix leaving call if a signaling message is received while reconnecting

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(calls): Do not reset previous connected users after resuming in a call [#14735](https://github.com/nextcloud/spreed/issues/14735)
- fix(sidebar): Show tooltips when Talk is in the sidebar [#14697](https://github.com/nextcloud/spreed/issues/14697)
- fix(guests): Fix style and labels on public share page as a guest [#14720](https://github.com/nextcloud/spreed/issues/14720) [#14726](https://github.com/nextcloud/spreed/issues/14726)
- fix(calls): Skip password verification for guests that are reconnecting to the call [#14787](https://github.com/nextcloud/spreed/pull/14787)
- fix(calls): Fix leaving call if a signaling message is received while reconnecting [#14788](https://github.com/nextcloud/spreed/pull/14788)
> chore(release): Prepare 19.0.15

- lib/Manager.php
> fix(chat): Fix preloading the last chat message with the room query

- lib/Controller/RoomController.php
- lib/Listener/CalDavEventListener.php
- lib/Service/RoomService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/php/Listener/CalDavEventListenerTest.php
- tests/php/Service/RoomServiceTest.php
* Fix https://github.com/nextcloud/spreed/issues/14689
> feat(conversations): Follow up for event conversation handling

- lib/Controller/CallController.php
- lib/Service/ParticipantService.php
We called getTime() twice and if by chance the time bit flipped between the call for the attendee last_joined_call and the room last_activity, the chat would show a "Missed call" for the starter when they also finished the call.
> fix(chat): Fix end-of-call showing "missed call" sometimes in one-to-one

- CHANGELOG.md
- fix: Improve performance of conversation list [#14811](https://github.com/nextcloud/spreed/issues/14811) [#14779](https://github.com/nextcloud/spreed/issues/14779) [#14777](https://github.com/nextcloud/spreed/issues/14777) [#14775](https://github.com/nextcloud/spreed/issues/14775) [#14774](https://github.com/nextcloud/spreed/issues/14774) [#14831](https://github.com/nextcloud/spreed/issues/14831)
- fix: Improve performance when rendering system messages [#14817](https://github.com/nextcloud/spreed/issues/14817)
- fix: Improve performance when searching for conversations [#14734](https://github.com/nextcloud/spreed/issues/14734)
- fix(chat): Fix missing reactions on own messages while posting …
> chore(release): Changelog for 19.0.15, 20.1.6, 21.0.2

- src/App.vue
- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/ExtendOneToOneDialog.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/RightSidebar/Participants/ParticipantsSearchResults.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
- src/components/UIShared/ContactSelectionBubble.vue
- src/components/UIShared/SearchBox.vue
- src/constants.ts
- src/store/conversationsStore.js
- src/utils/getDisplayName.ts
* Fix #14399
* New util "getDisplayNamesList" to format display name lists with length constraints.
* Introduce the "extendOneToOneConversation" store action
* Show the "Participants" button in one-to-one
* Allow to search for user participant only in the one-to-one call
* Allow to lock pre-selected participant when creating a new group conversation
* New popover to extend one-to-one conversations in the TopBar.
From LeftSidebar (locking group/team)
From TopBar (in chat)
From RightSidebar (in call)
> feat: allow to create new conversation from one-to-one

- src/App.vue
* talk-desktop ref: https://github.com/nextcloud/talk-desktop/pull/1174
I had to introduce some changes to spreed that are described below to create a central unreadCountStore to have an even hook in talk-desktop to get updates of these unreadCounts and enable talk-desktop to set the correct badge count on the app icon.
A new Vuex store module that serves as the single source of truth for all unread counters:
```javascript
state: {
// Total counters
totalUnreadMessages: 0,
totalUnreadMentions: 0,
totalUnreadMentionDirect: 0,
// Per-conversation tracking
unreadMessagesMap: {},
unreadMentionsMap: {},
unreadMentionDirectMap: {},
}
```
- Enhanced `addConversation` mutation:
- Automatically updates unread counters when adding new conversations
- Handles initial state synchronization
- Improved …
> Introduce unreadCount store

- src/components/ChatView.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
- src/components/NewMessage/NewMessage.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/RoomSelector.vue
- src/components/TopBar/CallButton.vue
* Fix regression after adding federated calls support
29 (no support) | 30 (support calls)
-- | --
All:
> fix(federation): respect remote capabilities when show "Notify about calls"

- CHANGELOG.md
- fix(avatar): Fix regression from library requesting too many status updates [#14894](https://github.com/nextcloud/spreed/issues/14894)
- fix(chat): Improve regex of todo-list handling also uppercase X [#14904](https://github.com/nextcloud/spreed/issues/14904)
- fix(federation): Use correct capability to show call-notification setting in federated conversations [#14907](https://github.com/nextcloud/spreed/issues/14907)
> chore(release): Add changelog for 21.0.3

- src/components/CalendarEventsDialog.vue
- src/components/TopBar/TopBar.vue
- Ref: https://github.com/nextcloud/spreed/issues/14802
-- | --
> fix(CalendarEventsDialog): adjust UI based on conversation type

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/store/conversationsStore.js
* Fix regression from #14730
* In store:
* second participant was duplicated from event dialog -> removed
* In conversation:
* second participant of 1-1 was passed to vuex store with other newParticipants -> kept
* In call:
* only one new participant always passed -> add original
-- | --
a | <img width="236" alt="2025-04-24_14h47_09" src="https://github.com/user-attachments/assets/3ac9c234-2465-4894-8bca-f886c1f307b9" /><img width="272" alt="2025-04-24_14h47_22" src="https://github.com/user-attachments/assets/c4958a38-4f0d-428b-b82c-6833b0fe0282" />
> fix(conversations): do not add second participant to extended 1-1 twice

- src/components/CalendarEventsDialog.vue
- src/components/TopBar/TopBar.vue
* Fix #14964
* Follow-up to #14965
* Just created conversation with no messages has no second participants added, therefore should be faked
-- | --
> fix: show schedule meeting invite option for fresh 1-1 conversations

- CHANGELOG.md
- fix(schedule-meeting): Make sure the other user is in one-to-one when scheduling [#14973](https://github.com/nextcloud/spreed/issues/14973) [#14967](https://github.com/nextcloud/spreed/issues/14967)
- fix(schedule-meeting): Improve dialog when scheduling in one-to-one [#14923](https://github.com/nextcloud/spreed/issues/14923)
- fix(schedule-meeting): Hide schedule meeting from former one-to-one [#14923](https://github.com/nextcloud/spreed/issues/14923)
- fix(performance): Fix unnecessary user_status requests from avatar component [#14932](https://github.com/nextcloud/spreed/issues/14932)
> chore(release): Changelog for 21.0.4

- appinfo/routes/routesRoomController.php
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Notification/Notifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Service/PhoneService.php
- openapi-backend-sipbridge.json
- openapi-full.json
- src/components/TopBar/CallButton.vue
- src/constants.ts
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-full.ts
- tests/php/Controller/SignalingControllerTest.php
> feat(sip): Allow the sipbridge to create a conversation with a user for  a phone number

- src/utils/signaling.js
The whole error was logged, but by default its contents were not visible unless the object was expanded. Rather than explicitly printing the error code and message, which are always provided, the whole error is now stringified. This ensures that any detail will be also readable, as they would be provided as additional custom attributes.
Note that due to the length of the messages a similar result could be just get by logging the `data.error` object (instead of `data`) rather than stringifying it, but stringifying it ensures that it will be also readable when the logs are sent through WebDriver BiDi (that is, for the recording server).
- Create a conversation
- Open Talk administration settings and set a wrong secret for the signaling server
- Open Talk again
- Open the …
> fix: Print error code and message for unhandled signaling errors

- lib/BackgroundJob/ExpireObjectRooms.php
* Otherwise event conversations for events in 5 weeks will be deleted by the time the event happened :see_no_evil:
> fix(events): Don't apply retention before the event happened

- src/components/MediaSettings/MediaDevicesSelector.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/SettingsDialog/MediaDevicesPreview.vue
- src/composables/useDevices.js
- src/services/__tests__/mediaDevicePreferences.spec.js
- src/services/mediaDevicePreferences.ts
- src/stores/sounds.js
- src/test-setup.js
- src/utils/webrtc/CallParticipantsAudioPlayer.js
- src/utils/webrtc/MediaDevicesManager.js
- src/utils/webrtc/index.js
* Fix #7125
* Fix #14405
* Fix #14404
* Current POC: works when selecting device before start of the call
-- | --
> feat: add selector for Audio Output 🔈

- src/components/ConversationSettings/BasicInfo.vue
- src/components/UIShared/ConversationActionsShortcut.vue
* Fix regression from #14714
* Non-moderators can not unbind / delete conversations
-- | --
> fix: do not show event-room actions for non-moderators

- CHANGELOG.md
- 📅 Improve handling of event conversations: filtered until close to the meeting, default expiration, tracking of event name and description [#14401](https://github.com/nextcloud/spreed/issues/14401)
- 👥 Allow adding participants to one-to-one calls creating a new conversation [#14398](https://github.com/nextcloud/spreed/issues/14398)
- 📇 Enhance right sidebar in one-to-one conversations with information about the participant[#14411](https://github.com/nextcloud/spreed/issues/14411)
- 📲 Allow SIP direct dial-in to start a new conversation with an existing Nextcloud account [#14992](https://github.com/nextcloud/spreed/issues/14992)
- 🖌️ Allow to provide custom images for virtual backgrounds for branding or corporate appearance [#14987](https://github.com/nextcloud/spreed/issues/14987)
- 🔈 …
> chore(release): Changelog for 21.1.0-rc.1

- lib/Listener/CalDavEventListener.php
* Fix
- if the location property does not exist using getValue will error.
> fix: check if property exists before using getValue

- src/composables/useGetParticipants.js
* I was wrong in  #11064 =P
* Original solution was introduced in 29936c357a3953e995dea091a384e55dccb5785c
* Previous request still cancels the parallel one, but each debounce trigger pushed the request invocation.
* E.g. if there is a signaling message every 2 seconds (with update interval of 3 seconds), we will never request the list
* At the start of the large calls, that explains , if you're not in the call yet, why participants loading is taking long (but maybe that also spreads the server load from when everyone joins at the same time)
* After joining (or without a call), interval is 3 seconds, so it's harder to notice.
* New approach:
* Do not debounce requests by 3/15 seconds, but delay the first invocation by 3/15 seconds, and ignore consequent ones happening within that interval …
> fix: throttle participants request instead of debouncing

- src/components/ConversationIcon.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/RightSidebarContent.vue
- src/stores/sounds.js
- src/utils/conversation.ts
* fix: init audio objects before setting sinkId (Not the RightSidebar, but already pushed)
* before: join/leave sounds will be played on default system devices
* fix: update local time in RightSidebar with periodic interval
* before: time stuck once it's computed
* fix: extract icon fallback class to utils
* reuse function from ConversationIcon
* fix: better throttle wheel events from touchpad
* before: this can skip preview modes, as touchpad firing a ton of events
* Fix: #15072
* no avatar for deleted users, show conversation avatar instead
-- | --
> fix(RightSidebar): better error handling for user profile

- CHANGELOG.md
- 🍱 Add a Talk Dashboard [#15094](https://github.com/nextcloud/spreed/issues/15094)
- 📅 Allow creating instant meetings [#15073](https://github.com/nextcloud/spreed/issues/15073)
- 🤝 Show mutual events in the sidebar of one-to-one [#15097](https://github.com/nextcloud/spreed/issues/15097)
- 🙊 Add sensitive conversations which don't show a chat messages in sublines and notifications [#15098](https://github.com/nextcloud/spreed/issues/15098)
- Send call notification to newly added participants [#15090](https://github.com/nextcloud/spreed/issues/15090)
- Fix issues with calendar event integration [#15078](https://github.com/nextcloud/spreed/issues/15078) [#15080](https://github.com/nextcloud/spreed/issues/15080)
> chore(release): Changelog for 21.1.0-rc.2

- lib/Controller/ChatController.php
- tests/integration/features/chat-3/reminder.feature
- Mark a conversation as sensitive
- Create a reminder
- Check the dashboard
- Message should not be visible
> fix(upcoming-reminders): Respect sensitive conversation setting

- lib/Capabilities.php
- src/components/UIShared/ConversationActionsShortcut.vue
- tests/php/CapabilitiesTest.php
> fix(instant-meetings): Fix missing retention duration from instant meetings

- src/components/RightSidebar/RightSidebarContent.vue
- src/components/UIShared/LocalTime.vue
- src/composables/useCurrentTime.ts
* Ref #15096
* make time in Right SIdebar update every minute (align with system clock)
* introduce shared composable for Date() object
* introduce shared component for showing the date
It works
> fix(RightSidebar): make local time reactive

- package-lock.json
- package.json
* Fix NcIconSvgWrapper alignment
-- | --
> chore(deps): bump @nextcloud/vue from 8.26.0 to 8.26.1

- src/utils/webrtc/CallParticipantsAudioPlayer.js
* ~~Safari does not support AudioContext#setSinkId (required for call audio mixer)~~
* ~~UI was considering only Audio#setSinkId~~
* AudioContext destination was actually given to `<audio>` element, which we can modify
-- | --
Screenshot before | to be added
> fix: make audio output feature work in calls for Safari

- lib/Controller/BotController.php
Ref https://github.com/nextcloud/openapi-extractor/actions/runs/15105903623/job/42454551559?pr=242
> fix(openapi): Remove unused return documentation

- lib/Controller/SignalingController.php
- lib/ResponseDefinitions.php
- lib/Signaling/Manager.php
- openapi-administration.json
- openapi-backend-recording.json
- openapi-backend-signaling.json
- openapi-backend-sipbridge.json
- openapi-bots.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-administration.ts
- src/types/openapi/openapi-full.ts
BC-Fixable part from https://github.com/nextcloud/openapi-extractor/pull/244
> fix(openapi): Be more accurate for non-empty-lists

- tests/php/bootstrap.php
This uses the new tests/autoload.php from nextcloud/server instead of messing directly with OC private autoloader.
See https://github.com/nextcloud/server/pull/52951 and https://github.com/nextcloud/server/pull/52945 for context.
> chore(tests): Cleanup bootstrap.php to be forward-compatible

- src/components/UIShared/ConversationActionsShortcut.vue
* Fix redundant label shown to users non-moderators in rooms with 0 retention
-- | --
> fix(ConversationActionsShortcut): hide component if nothing to show

- src/__mocks__/capabilities.ts
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/services/conversationsService.ts
- src/store/conversationsStore.js
- src/types/index.ts
* Fix #14880 
* Icons and wording aligned with iOS pull request
-- | --
> feat: add UI for important/sensitive conversations

- src/components/LeftSidebar/LeftSidebar.vue
- src/test-setup.js
* Allows to capture issues at JS code before it got merged
* Components should be mounted in any test
* can be avoided by `console.#method = jest.fn()` in place where it's expected
-- | --
Green CI | Red CI
> test: make Jest fail on console.warn / console.error

- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/RightSidebarContent.vue
* Throttle wheel events to the last+100ms instead of last+300ms
* Allow wheel events to expand only  in the content area (where header//image is)
* Wheel events to shrink are intact (scroll in the chat/attendees list still work to hide it)
* Clicking on image:
* has correct cursor
* expand to full size or back to preview (only 2 options)
* Clicking on header:
* has correct cursor;
* has correct width animation;
* expand/shrink to preview size; or shrink to compact, if was in preview
🏚️ Before
https://github.com/user-attachments/assets/a813a7b0-1e7c-45dc-9aee-169bf4d9c033
🏡 After
https://github.com/user-attachments/assets/e70eecda-2b67-41d8-8204-66895dd2e68e
> fix(RightSidebar): adjust profile info expanding logic

- src/components/LobbyScreen.vue
> fix(lobby): Only show relative time for 24h

- src/composables/useGetParticipants.js
- src/constants.ts
- src/services/EventBus.ts
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/stores/__tests__/session.spec.js
- src/stores/session.ts
- src/types/index.ts
* Attempt to reduce the number of participants list updates
> [!IMPORTANT]
> 🍍Stores all sessions in Pinia store:
> - internal: by nextcloud sessionId
> - external: by signaling server sessionId
> If no attendee was mapped to the session, fetch participants and patch session later
>
> ♻️ Update participant object with data from signaling:
> - permissions
> - nextcloud sessionId
> - inCall
> - participantType
> - lastPing
> - displayName
> [!IMPORTANT]
> 🚧 Experimental feature: set config to enable:
> `occ config:app:set spreed experiments_users --value=1`
<details>
<summary> Examples of signaling messages inside: (was changed in Talk 20, have some new fields now) </summary>
```json
[
[
{
"userId": "alice",
"roomId": 7,
"lastPing": 1718882327,
"sessionId": …
```
> perf(participants): update participants session status from signaling

- CHANGELOG.md
- 📲 🙊 Add option to mark a conversation as sensitive or important [#15175](https://github.com/nextcloud/spreed/issues/15175)
- fix(chat): Fix missing push notifications for chat messages in important conversations [#15180](https://github.com/nextcloud/spreed/issues/15180)
- fix(dashboard): Make sure all events of the upcoming week are considered [#15177](https://github.com/nextcloud/spreed/issues/15177)
- fix(conversations): Make the "Local time" reactive in one-to-one conversations [#15130](https://github.com/nextcloud/spreed/issues/15130)
- fix(conversations): Only show events in one-to-one conversations when upcoming recurrences contain both participants [#15163](https://github.com/nextcloud/spreed/issues/15163)
- fix(conversations): Fix …
> chore(release): Add changelog for 20.1.7 and 21.1.0.rc3

- src/composables/useGetParticipants.js
- src/services/EventBus.ts
- src/utils/signaling.js
* On top of #12556
* ATM testing in real calls to gather data (how it affects amount of data fetched)
* long poll updates currently set to 60 seconds
* long poll updates are needed for user_status update (but if all participants have 1-1 with you, you would get the data every 30 seconds via other source)
* ~~room-list updates are disabled for the sake of experiment, so results would be slightly different if add/remove participants, or at webinars with guests~~ fake requests should replicate the old behaviour (how many would have been)
> [!IMPORTANT]
> 🚧 Experimental feature: set config to enable:
> `occ config:app:set spreed experiments_users --value=1`
<details>
<summary>First attempt</summary>
1. Small call (8 participants), some people are joining/leaving conversation, but not the call …
> perf(participants): reduce amount of participants list updates

- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/stores/__tests__/sharedItems.spec.js
- src/stores/sharedItems.js
-- | --
NOTE/ When to refresh for expiring messages?
> fix: reset shared items from a deleted message

- package-lock.json
- package.json
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/RightSidebar/RightSidebarContent.vue
* Bump `@nextcloud/vue` library to 8.27.0
* Drop overriden styles, replace with new features/bugfixes
-- | --
> chore(deps): bump @nextcloud/vue from 8.26.1 to 8.27.0

- lib/Service/RoomService.php
- src/components/ConversationSettings/LobbySettings.vue
- src/components/RightSidebar/LobbyStatus.vue
- src/store/conversationsStore.js
* Allow to enable lobby in 'Instant meeting' conversations
* Refactor frontend code to get rid of error handling duplication logic
no visual changes
---
> fix(meeting): allow to toggle lobby state for instant meetings

- lib/Controller/AEnvironmentAwareOCSController.php
- lib/Controller/AvatarController.php
- lib/Controller/BotController.php
- lib/Controller/CallController.php
- lib/Controller/ChatController.php
- lib/Controller/FederationController.php
- lib/Controller/PollController.php
- lib/Controller/ReactionController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Federation/Authenticator.php
- openapi-backend-sipbridge.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
* Ref https://github.com/nextcloud/openapi-extractor/pull/243
* Blocked by https://github.com/nextcloud/openapi-extractor/issues/248
* Should wait for https://github.com/nextcloud/openapi-extractor/issues/247
* Could prepare migration of headers to https://github.com/nextcloud/openapi-extractor/issues/246 before
> feat(request-headers): Document request headers

- composer.json
- openapi-backend-recording.json
- openapi-backend-signaling.json
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-recording.ts
- src/types/openapi/openapi-backend-signaling.ts
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- vendor-bin/openapi-extractor/composer.json
- vendor-bin/openapi-extractor/composer.lock
> ci(openapi): Bump nextcloud/openapi-extractor to 1.8

- lib/Service/ParticipantService.php
* Fix typo in `ParticipantService#getHighestPermissionAttendee()` to check for moderators correctly
* Add logging to highlight possible errors
> fix(ParticipantService): fix sending a federation invite from room with no owner

- appinfo/info.xml
- docs/occ.md
- lib/Command/Signaling/VerifyKeys.php
- lib/Config.php
- lib/SetupCheck/HighPerformanceBackend.php
* Fixes https://github.com/nextcloud/spreed/issues/14312
Error handling based on 
https://github.com/nextcloud/server/blob/a8f46af20f4fccac0257eba950e70d0da96c4a5a/lib/private/Authentication/Token/PublicKeyTokenProvider.php#L559-L565
> Verify signaling token keys

- src/components/SelectPhoneNumber.vue
- src/composables/useAsyncInit.ts
- src/composables/useLibphonenumber.ts
* Ref https://github.com/nextcloud/spreed/issues/9406
* `libphonenumber-js` is quite a large library
* 2 used functions alone: `121 kB` after tree-shaking [bundlejs](https://bundlejs.com/?q=libphonenumber-js%401.12.9&treeshake=%5B%7B+parsePhoneNumberFromString%2CvalidatePhoneNumberLength+%7D%5D)
* `120kb` is not a big deal for our large bundle, but:
* It is only used in a rare case - on a phone number search (not supported in many instances)
* Many small libraries make a larger part later
* Added `useAsyncInit` helper to be used in other similar cases
Entity | 🏚️ Before | 🏡 After
-- | -- | --
`/js` | `50_384 kb` | `49_900 kb` (🔻1%)
`talk-main.js` | `7_549_282 b` | `7_425_859 b` (🔻1.6%)
> perf(frontend): lazy load `libphonenumber-js`

- lib/Controller/PageController.php
- lib/Listener/CSPListener.php
- Fix encrypted calls in Talk integrations (Files Sidebar, Password Share request)
- this aligns CSP policy between controller and listner
- wasm allowed for encryption
- ConnectDomain('*') replaced with HPB, TURN, STUN servers
> fix: allow encrypted calls in Talk integrations

- src/App.vue
* Fullscreen layout due to mounting inside `#content` instead of replacing it
-- | --
> fix(vue3): fullscreen mode in Vue 3 container 

- src/App.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/services/EventBus.ts
- src/store/conversationsStore.js
* Separated from #15412 and reworked
* as initial route is '/', and guests are redirected to not-found, we should either wait for router to be ready, or do not use it
-- | --
> fix: adjust logic of 'conversation-received' event emitting

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
- src/test-setup.js
* Bump `@nextcloud/upload` to `v2.0.0-rc.0`
* Uncomment commended uploader usage
> fix(vue3): bring uploader back with @nextcloud/upload v2.0.0-rc.0

- lib/ResponseDefinitions.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
* Fixup to #15095
* Define field via openapi / TS
> fix(ResponseDefinitions): define 'hide-download' field to message parameters

- CHANGELOG.md
- fix(chat): Always render code blocks left-to-right [#15364](https://github.com/nextcloud/spreed/issues/15364)
- fix(call): Allow end-to-end encrypted calls in integrations like files and sharing [#15415](https://github.com/nextcloud/spreed/issues/15415)
- fix(sip): Add log message when direct dial-in had no match to help configuring phone numbers [#15358](https://github.com/nextcloud/spreed/issues/15358)
- fix(federation): Fix sending invites from conversations without an owner [#15354](https://github.com/nextcloud/spreed/issues/15354)
- fix(settings): Show errors when the websocket connection could not be opened [#15368](https://github.com/nextcloud/spreed/issues/15368)
- fix(settings): Validate that signaling private and public key match …
> chore(release): Add changelog for 20.1.8 and 21.1.1

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
> fix: Use outline icons in LeftSidebar

- appinfo/info.xml
- lib/Chat/ChatManager.php
- lib/Controller/ThreadController.php
- lib/Migration/Version22000Date20250710124258.php
- lib/Model/Thread.php
- lib/Model/ThreadAttendee.php
- lib/Model/ThreadMapper.php
- lib/ResponseDefinitions.php
- lib/Service/ThreadService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-4/threads.feature
> feat(threads): Recent threads, no more read marker and add conversation token

- src/components/AdminSettings/BotsSettings.vue
- src/components/AdminSettings/MatterbridgeIntegration.vue
- src/components/AdminSettings/RecordingServer.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/StunServers.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/TurnServers.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
> fix: migrate to outline icons in admin settings

- jest.config.js
- src/components/PermissionsEditor/PermissionsEditor.vue
- src/components/RightSidebar/Participants/ParticipantPermissionsEditor.spec.js
- `<PermissionsEditor>` had template refs and component properties with the same name, for example, `lobbyIgnore` was at the same time:
- a template ref, storing with a child component instance
- a boolean property of the component instance
- These template refs were only added for tests - removing
- Fixing tests:
- Submit the HTML form instead of clicking on the submit button
- Find checkboxes by label text instead of template refs
- Remove `wrapper.setData()` usage, it is a forbidden method for tests
-- | --
> fix(permissions): permissions editor ignores changes

- lib/Config.php
The `deriveSignalingTokenPublicKey` method checks for OpenSSL errors and throws in case there are any. When run as part of the setup checks, it's possible that there are OpenSSL errors in other parts of the checks, but we still throw in `deriveSignalingTokenPublicKey` and indicate that the HPB setup is not correct.
> fix(setupcheck): Clear OpenSSL errors before executing

- src/components/Quote.vue
- src/components/RightSidebar/Threads/ThreadItem.vue
* Fix #15512
* Give some space
* Add a shortcut button to thread view from a quote (if this message is already a thread)
⚠️ Screenshots are made against unreleased vue-library (messages do not have margin-bottom)
-- | --
> feat(Quote): add a shortcut to threaded view from replies

- src/components/ChatView.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesList.vue
- src/services/EventBus.ts
* Fix scrolling to focused items
* Imitate smooth scrolling with 'instant scroll to almost visible > smooth'
* That way rendered references will not interfer with container height and scroll position
* Drop hash from route/URL when scrolling to bottom (via button click)
https://github.com/user-attachments/assets/1fda29a3-87d1-4d0a-83fb-b8a9ec5b1fd2
> fix(chat): imitate smooth scrolling and drop hash when scroll to bottom

- src/App.vue
* Fix pressing Esc button loading dashboard / home page, when in public view
-- | --
> fix: disable Esc hotkey for guests

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
* Fix flickering, when mouse hover a one-line message (height 32px), it shows buttons menu (height 34px), total height is changed,  message is not hovered anymore, buttons menu is hidden - ... - repeat until tired
* Fix message height to be minimum of (24px+2*4px padding)
* Reduce buttons menu top inline to 4px (align top border with Quote)
* Add safe margin for minimum resulting difference (34px + 4px - 2 * 4px - 24px)
* Refactor template to not use function, and migrate to const object instead
* Previous fix doesn't work in Vue3 due to inheritAttrs: false. Initial problem was solved, so removing an option
Alternative: buttons should not exceed message height
-- | --
Flickering | Stable
> fix(chat): fix flickering MessagesList

- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Controller/ThreadController.php
- lib/Federation/Proxy/TalkV1/Controller/ThreadController.php
- lib/Model/ThreadAttendeeMapper.php
- lib/Service/ParticipantService.php
- lib/Service/ThreadService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-4/threads.feature
- tests/php/Chat/NotifierTest.php
* Ref #9679 
- Value is not used for notifications yet, will be a follow up
- Integration test will follow when that is implemented
> feat(threads): Allow to subscribe with a different notification level

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Fix: https://github.com/nextcloud/spreed/issues/15586
> fix(chat): close message action on "Download file" click

- src/components/MessagesList/MessagesList.vue
- src/composables/useDocumentTitle.ts
- src/composables/useGetMessages.ts
- src/store/messagesStore.js
- src/stores/__tests__/chat.spec.js
- src/stores/chat.ts
* Follow-up to #15566 
* Pre-requisite to #10084
> fix(chatStore): add search, cleanup, getFirst / getLast methods

- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Controller/ChatController.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-4/threads.feature
- Should allow clients to update the thread list from pulling the chat
- Title is a parameter
- Last activity the timestamp of the system message
- num replies 0
- last message null
- first message the parent
> fix(threads): Add the thread title to the system message

- src/components/TopBar/CallButton.vue
* Fix #10343 
* Will be merged with #15583
-- | --
Screenshot before | <img width="364" height="102" alt="image" src="https://github.com/user-attachments/assets/1e7ceb35-b65c-4036-9f4e-26446a68a4c1" />
a | <img width="253" height="143" alt="image" src="https://github.com/user-attachments/assets/5947df1b-9c30-45cf-9476-5184f6d287e6" />
> fix(CallButton): make leave call button a split button.

- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageAttachments.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/components/RightSidebar/Threads/ThreadItem.vue
- src/components/TopBar/TopBar.vue
- src/services/__tests__/messagesService.spec.js
- src/services/messagesService.ts
- src/store/fileUploadStore.js
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
- src/stores/chatExtras.ts
* Ref #9680
-- | --
action | <img width="241" height="102" alt="2025-07-29_11h49_17" src="https://github.com/user-attachments/assets/ab9e65cb-9165-4b9a-980b-eb5f81d47a35" /> <img width="281" height="129" alt="2025-07-29_11h49_51" src="https://github.com/user-attachments/assets/e9f41185-64d5-43ba-b24f-8685498d9a53" />
input | <img width="919" height="130" alt="image" src="https://github.com/user-attachments/assets/80844cca-aa6e-418f-b546-a50ba93def57" /> <img width="927" height="141" alt="image" src="https://github.com/user-attachments/assets/a8bfb343-6163-4e67-b8e1-a02babbe475d" />
file share | <img width="687" height="397" alt="image" src="https://github.com/user-attachments/assets/34df7162-03ee-464d-af5c-00991b7933ad" />
> feat(threads): Allow to set thread title (frontend)

- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/composables/useDocumentTitle.ts
- src/composables/useGetMessages.ts
- src/services/messagesService.ts
- src/store/messagesStore.js
- src/stores/__tests__/chat.spec.js
- src/stores/chat.ts
* Fix-up to: #15596
* Pre-requisite to: #10084 
-- | --
Before | ![2025-08-01_11h36_31](https://github.com/user-attachments/assets/f4141d54-b752-450b-b319-1cf53ba1c2d8)
> fix(chat): respect threadId in store requests

- lib/Chat/ChatManager.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Controller/ChatController.php
- lib/Controller/ThreadController.php
- lib/Federation/Proxy/TalkV1/Controller/ThreadController.php
- lib/Service/ThreadService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-4/threads.feature
- tests/php/Chat/SystemMessage/ListenerTest.php
- Ref #9679
- Allow to rename a thread
- Add "you" version of rename and create system message
> feat(threads): Allow to rename a thread

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/Participants/Participant.vue
* Fix #15609
LS | Participant
-- | --
> fix(icons): make phone dial out icon more relatable and adjust filter icon size

- lib/Controller/RoomController.php
- psalm.xml
- tests/psalm-baseline.xml
- tests/stubs/oc_authentication_token_provider.php
Fixes https://github.com/nextcloud/spreed/issues/14698
> [stable31] fix: invitation emails for talk

- lib/Activity/Listener.php
- lib/Chat/ChatManager.php
- lib/Chat/ReactionManager.php
- lib/Chat/SystemMessage/Listener.php
- lib/Controller/ChatController.php
- lib/Controller/PollController.php
- lib/Controller/ThreadController.php
- lib/MatterbridgeManager.php
- lib/Service/RecordingService.php
- tests/php/Chat/ChatManagerTest.php
- tests/php/Chat/SystemMessage/ListenerTest.php
- tests/php/Controller/ChatControllerTest.php
* Fix #15489 
This PR modifies the `addSystemMessage` method to optionally accept a `?Participant` argument. This allows us to determine if system messages should include the `METADATA_CAN_MENTION_ALL` based on either room settings or the participant's moderator permissions.
Also includes test updates to validate the new behavior.
> fix(message): support mention-all metadata in system messages

- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Chat/AutoComplete/Sorter.php
- lib/Controller/ChatController.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/mentions.feature
- tests/integration/features/federation/chat.feature
- tests/php/Chat/AutoComplete/SearchPluginTest.php
- Since bots, todo lists and other things became more popular it makes sense to add the self-user also as a mention suggestion
- Ignore guests from mention suggestions that disconnected
They will have a new session ID when reconnecting so the highlight
does not work anyway and participants are better of quoting them.
* Fix #15597 
* Fix #15366
> fix(chat): Suggest to mention self

- src/assets/variables.scss
- src/components/CallView/BottomBar.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/CallView/shared/PresenterOverlay.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBarMediaControls.vue
* Follow-up to #15583 
- add spacing between stripe and bottom bar
- Restore highlighted screen share button when screensharing
- Add shadow on own video when one-to-one
- Reduce gap in split button
-- | --
> fix(Grid): add spacing between stripe and bottom bar

- .github/pull_request_template.md
- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/main.js
- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/mainRecording.js
- src/router/router.ts
- src/views/FilesSidebarChatView.vue
* Fix #15573
* testing with Files Sidebar (from files, public, public auth)
* integration route is matching message actual URL
-- | --
🏡 After
https://github.com/user-attachments/assets/916600a3-339c-4935-9e42-07a4663cee7b
> fix: use memory router for Talk integration

- eslint.config.mjs
- package-lock.json
- package.json
- src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
- src/services/coreService.ts
- src/types/index.ts
- src/types/vendor/@nextcloud/cdav-library.d.ts
- src/types/vendor/vuex.d.ts
* bump eslint dependency
* audit the rest
* lint files and updat eslint config
> chore(deps): bump @nextcloud/eslint-config to v9.0.0-rc.4

- CHANGELOG.md
- Makefile
- appinfo/info.xml
- package-lock.json
- package.json
- Implement threads feature [#15313](https://github.com/nextcloud/spreed/issues/15313)
- Implement 'Busy' status in calls [#15465](https://github.com/nextcloud/spreed/issues/15465)
- Update call interface design [#15025](https://github.com/nextcloud/spreed/issues/15025)
- Improve chat history browsing performance [#6046](https://github.com/nextcloud/spreed/issues/6046)
- Migrate app to Vue3 [#9448](https://github.com/nextcloud/spreed/issues/9448)
- Require Nextcloud 32 / Hub 25 Autumn
> chore: release Talk v22.0.0-beta.1

- src/App.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/composables/useGetMessages.ts
* Follow-up to #15704
* Wait for router navigation to successfully complete before emitting an event seems more reasonable:
* `token` and `threadId` are updated globally according to route
* navigation can be no longer interrupted
* all current use cases are side-effects, which are safe to run after navigation:
* SearchMessageTab, ThreadsTab - change sidebar tab, safe to do after
* LeftSidebar - leave-join to signaling happens here, but safe to after
* useGetMessages - defining a context, the place where it's important to do after 🟢 
> fix(router): emit 'route-change' after navigation

- src/components/AdminSettings/BotsSettings.vue
- src/components/AdminSettings/RecordingServer.vue
- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/WebServerSetupChecks.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/PollViewer/PollViewer.vue
- src/components/RightSidebar/Participants/Participant.vue
- `--color-success-text` is the text color for `--color-success`
- `--color-text-success` is the text color for normal backgrounds
-- | --
> fix(ui): Fix state colors

- docs/quick-install.md
* Follow up to https://github.com/nextcloud/spreed/pull/15724
Noticed a few seconds after merge that we have 2 links :-(
> docs: Adjust second docs link for snap installation

- src/components/AdminSettings/RecordingServer.vue
- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/ConversationSettings/Matterbridge/BridgePart.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/UIShared/ConversationActionsShortcut.vue
* Ref #15473
-- | --
Screenshot before | <img width="226" height="46" alt="image" src="https://github.com/user-attachments/assets/89a07191-1c60-430f-8f54-fefaed91deda" />
> Use material symbol variant of delete icon

- CHANGELOG.md
- feat(sip): Allow to send the direct dial-in number of users on out-going calls [#15701](https://github.com/nextcloud/spreed/issues/15701)
- feat(settings): Add a config for the unread message threshold for the AI summary [#15734](https://github.com/nextcloud/spreed/issues/15734)
- fix(dashboard): Fix events without an end date [#15732](https://github.com/nextcloud/spreed/issues/15732)
- fix(chat): Suggest mentioning yourself, it's useful with bots and todos [#15656](https://github.com/nextcloud/spreed/issues/15656)
- fix(chat): Fix search interaction when scrolling away and clicking on a result again [#15706](https://github.com/nextcloud/spreed/issues/15706)
- fix(chat): Fix support for at-all in captions when sharing a file …
> chore(release): Changelog for 21.1.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(sip): Allow to send the direct dial-in number of users on out-going calls [#15701](https://github.com/nextcloud/spreed/issues/15701)
- feat(settings): Add a config for the unread message threshold for the AI summary [#15734](https://github.com/nextcloud/spreed/issues/15734)
- fix(dashboard): Fix events without an end date [#15732](https://github.com/nextcloud/spreed/issues/15732)
- fix(chat): Suggest mentioning yourself, it's useful with bots and todos [#15656](https://github.com/nextcloud/spreed/issues/15656)
- fix(chat): Fix search interaction when scrolling away and clicking on a result again [#15706](https://github.com/nextcloud/spreed/issues/15706)
- fix(chat): Fix support for at-all in captions when sharing a file …
> Release v21.1.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(calls): Implement live-transcriptions when the ExtApp is available [#15696](https://github.com/nextcloud/spreed/issues/15696)
- feat(dashboard): Improve empty content view of the dashboard sections [#15697](https://github.com/nextcloud/spreed/issues/15697)
- fix(UI): Further design adjustments to outlined icons
- fix(chat): Many improvements for threads [#15616](https://github.com/nextcloud/spreed/issues/15616) [#15703](https://github.com/nextcloud/spreed/issues/15703) [#15704](https://github.com/nextcloud/spreed/issues/15704) [#15722](https://github.com/nextcloud/spreed/issues/15722) [#15735](https://github.com/nextcloud/spreed/issues/15735)
> Release v22.0.0-beta.2

- src/components/MediaSettings/MediaSettings.vue
- src/components/TopBar/TopBarMediaControls.vue
* Adds a button to quickly open 'virtual backgrounds'
> fix(MediaSettings): fix modal width

- lib/BackgroundJob/CheckHostedSignalingServer.php
- src/components/AdminSettings/HostedSignalingServer.vue
- tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
With an upcoming release of the HPB service API, accounts will optionally include STUN-/TURN-server information for customers that don't want to host these themselves but get them through our offering.
This PR evaluates the additional fields and updates the Talk configuration accordingly.
Let me know if you don't already have access to the HPB service API documentation and want to set this up locally for testing.
> feat(hpb-service): Configure STUN/TURN servers if included in HPB account

- src/components/CalendarEventsDialog.vue
- src/components/ExtendOneToOneDialog.vue
-- | --
Before| Screenshot after
> fix(CalendarEventsDialog): don't let popovers overlap

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/RoomSelector.vue
- src/components/UIShared/StaticDateTime.vue
- src/utils/davUtils.ts
- src/utils/requestRoomSelection.js
* Found while fixing tests, extracted for separate review
-- | --
Nothing | <img width="289" height="55" alt="2025-09-01_10h37_34" src="https://github.com/user-attachments/assets/bd7f84f1-f6e8-4f78-8eae-3c9c9dbf1f2b" />
> fix(vue3): adjust to Vue 3, fix regressions

- src/components/CallView/BottomBar.vue
Similarly to the icon in the raise hand button, when the live transcription button is enabled now the normal icon is used instead of the outline one.
I am not sure if this is needed or not, but just in case :-) If it is not needed feel free to close ;-)
-- | --
> fix: Use normal subtitles icon instead of outline when enabled

- src/components/MessagesList/MessagesList.vue
* Fix chat at the top when remounting the chat component to a new place
> fix(MessagesList): scroll to bottom when joining the call

- lib/Controller/ChatController.php
Fix https://github.com/nextcloud/spreed/pull/15776#issuecomment-3246026047
> fix(thread): Fix thread info for the root message

- src/components/PollViewer/PollVotersDetails.vue
* Fix regression from overriden styles
* selector specificity is too low now, increasing according to upstream lib
-- | --
> fix(PollViewer): fix mispositioned icons

- src/components/NewMessage/NewMessage.vue
* Align with other clients on threads submitting
> fix(threads): prevent submitting a thread without a title

- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
* We no longer need those styles after https://github.com/nextcloud-libraries/nextcloud-vue/pull/6004
-- | --
> fix: fix skewed position of user status

- src/components/LeftSidebar/LeftSidebar.vue
- When clicking on thread item and you are not in the same conversation, LS suddenly jumps and shows conversations list with the new conversation joined
- When returning from threads navigation, it feels a bit lost on where you are as thread items don't show which conversation you are in. Best is to return the conversation you were joined in before navigation. 
-- | --
> fix: don't reset automatically threads list

- src/components/CallView/BottomBar.vue
* Fix UI appearance of call buttons
* Selector should always be specified higher, if its' overriding styles
-- | --
> style(BottomBar): increase selector specificity for tertiary buttons

- src/store/messagesStore.js
> fix(messagesStore): harden check for lastMessage

- src/init.js
* In order to avoid the accumulation of migrations and workarounds that are no longer necessary, I suggest if a deadline is set in its description (e.g: REMOVE: in stable33, REMOVE: in nextcloud-vue v8.30.0). TODO/FIXME keyword are very general to keep fast and easy cleanup batches.
> fix: remove old migrations

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
- src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
* Fix performance issue with virtual scroller rendering (hopefully)
* with key set on root (NcListItem), it causes re-rendering of the whole item component (app) -> leads to observer disonnecting and creating new one (lib) -> calls getBoundingClient rect (lib) -> recalculate styles
-- | --
> fix(RecycleScroller): reuse items for better performance

- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/MediaSettings/MediaSettings.vue
* Extracted from #15680
* Fix device state after closing 'Check devices' dialog:
* with input id change, device is muted and toggled outside of component
* instead of toggle methods in buttons, directly change state in the model after close
> fix(call): apply selected device state after closing dialog in call

- src/components/MessagesList/MessagesList.vue
- src/components/Quote.vue
- src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
- src/composables/useGetMessages.ts
- src/services/EventBus.ts
* Fix constant highlighting of message (due to using contextMessageId)
* Most noticeable on previously loaded chat
-- | --
> fix(chat): do not highlight messages, if they're not focused

- .github/contributing.md
Broken link. 
It's still possible to link to the resource directly like `https://app.transifex.com/nextcloud/nextcloud/spreed/`, however guest users are then redirected to a login page, and therefore I've opted for the project overview.
> chore: update transifex link

- lib/Chat/SystemMessage/Listener.php
- lib/Service/ThreadService.php
- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/chat-4/threads.feature
> fix(threads): Count shared files as thread replies and last message

- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Chat/SystemMessage/Listener.php
- lib/Notification/Notifier.php
- lib/Search/MessageSearch.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-4/threads.feature
> fix(threads): add threadId to objectId for notifications

- src/components/TopBar/CallTime.vue
- src/components/TopBar/TopBar.vue
* Fix 'components with digits' width for any font (should be reproducible with Inter)
-- | --
Should be worse | Should be better
> style(TopBar): set fixed width for digit characters

- src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
* Fix #15890
-- | --
Screenshot before | <img width="280" height="221" alt="image" src="https://github.com/user-attachments/assets/cb9d75be-6c6e-4c00-8c7a-c83f483c9b95" />
> fix(LeftSidebar): allow to search for strings with diacritics

- CHANGELOG.md
- fix(chat): Validate file name when creating from template instead of failing afterwards [#15919](https://github.com/nextcloud/spreed/issues/15919)
- fix(conversation): Fix spacing between items in conversation list when forwarding [#15812](https://github.com/nextcloud/spreed/issues/15812)
- fix(conversation): Fix joining and leaving conversations when errors occurred [#15797](https://github.com/nextcloud/spreed/issues/15797)
- fix(chat): Support at-all in captions [#15746](https://github.com/nextcloud/spreed/issues/15746)
- fix(chat): Fix loading a completely empty conversation as a guest [#15551](https://github.com/nextcloud/spreed/issues/15551)
- fix(conversation): Fix joining and leaving …
> chore(release): Add changelog for 20.1.10 and 21.1.5

- CHANGELOG.md
- fix(call): Correctly sync media devices with OS sound settings
[#15900](https://github.com/nextcloud/spreed/pull/15900)
[#15972](https://github.com/nextcloud/spreed/pull/15972)
- fix(chat): Validate file name when creating from template instead of failing afterwards
[#15920](https://github.com/nextcloud/spreed/issues/15920)
- fix(threads): Post shared files in the opened thread
[#15938](https://github.com/nextcloud/spreed/pull/15938)
- fix(threads): Count shared files as thread replies and last message
[#15946](https://github.com/nextcloud/spreed/pull/15946)
> chore: prepare changelog for v22.0.0-rc.3

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
* Ref https://github.com/nextcloud/talk-ios/issues/2188
* temporary message is created, when file is just uploaded/pasted/dropped on the chat, and not sent yet
* parent message might be dismissed by then (in the dialog)
* Should be checked when sending
* Fix appearance for temporary voice message
-- | --
> fix(chat): attach actual parent message to file uploads

- src/composables/useDevices.js
- src/stores/sounds.js
- Fix sound stop when joining call
- output is already set at the device checker, no need to set it again
- Might still sound abruptly, but it is not actually needed
- Proper A-B fix would be to separate useDevices
> fix(sounds): do not pause playing audio on speaker change

- src/composables/useGetMessages.ts
- src/stores/chat.ts
* Steps to reproduce:
* type message
* create a thread and type a message inside thread
* Reload on the thread view
* Type some messages in thread view
* Return to the main chat
-> You will see emtpy chat
-- | --
> fix(threads): show main chat after activity in a thread view on a fresh reload

- package-lock.json
- package.json
- src/components/CalendarEventsDialog.vue
- src/components/MediaSettings/MediaSettings.vue
* Bump library to stable
* Remove deprecated prop (NcPopover close-on-click-outside)
> chore(dependencies): bump @nextcloud/vue to stable v9.0.0

- CHANGELOG.md
- fix(threads): Support object shares, polls and file uploads
[#15990](https://github.com/nextcloud/spreed/pull/15990)
[#16001](https://github.com/nextcloud/spreed/pull/16001)
- fix(call): Release media devices and memory resources after the call end
[#15992](https://github.com/nextcloud/spreed/issues/15992)
- fix(call): Adjust call recording layout
[#16016](https://github.com/nextcloud/spreed/pull/16016)
> chore: prepare v22.0.0-rc.4 release

- src/utils/getMessageIcon.ts
* Indicate that a last message is in the thread
* Do not merge until #16009, needs a consistent response body for `lastMessage`
> fix(threads): show thread icon in LeftSidebar

- src/composables/useGetMessages.ts
- src/stores/chat.ts
* Fix regression from #16012 
* in main context, `threadId` is always 0, and `store.getters.message(token, messageId)?.threadId !== threadId` is always true
🏚️ Before 
https://github.com/user-attachments/assets/0de1759b-0a5d-4ae4-b163-785a9c8e6584
🏡 After
https://github.com/user-attachments/assets/7c043c9d-f512-4c3a-8b28-445b7ee0cd63
> fix(chat): improve check for last message context

- src/components/CalendarEventsDialog.vue
- src/components/RightSidebar/RightSidebarContent.vue
- src/components/UIShared/CalendarEventSmall.vue
- src/components/UIShared/StaticDateTime.vue
- src/composables/useConversationInfo.ts
- src/utils/formattedTime.ts
* Ref #14434
* Extracted from #14492
* Trade-offs:
* we're losing prefixes like 'Today `at` 3:00 PM'
* for 6+ days, we're using the same format as date separators (and not DD.MM.YYYY)
-- | --
6+ days | --
> fix: replace moment.calendar() with Intl formatters

- lib/AppInfo/Application.php
- lib/ConfigLexicon.php
- lib/Controller/PageController.php
- lib/Files/TemplateLoader.php
- lib/PublicShare/TemplateLoader.php
- lib/PublicShareAuth/TemplateLoader.php
- lib/TInitialState.php
Starting 1 config at a time, as not all are straight forward to add
> feat(config): Start config lexicon

- package-lock.json
- package.json
- src/components/AdminSettings/BotsSettings.vue
- src/components/AdminSettings/HostedSignalingServer.vue
- src/components/ConversationSettings/BanSettings/BannedItem.vue
- src/components/LobbyScreen.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/NewMessage/NewMessageAbsenceInfo.vue
- src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
- src/store/fileUploadStore.js
- src/utils/__tests__/formattedTime.spec.js
- src/utils/formattedTime.ts
* Fix #14434
-- | --
Banned user date | -
'lll', `Feb 15, 2025 8:30 PM` | 'dateTimeShort', `Feb 15, 2025, 8:30 PM`
Bot last error | -
'll LTS', `Feb 15, 2025 8:30:00 PM` | 'dateTimeShortWithSeconds', `Feb 15, 2025, 8:30:00 PM`
Hosted HPB expiration dates | -
'L', `02/15/2025` | 'dateNumeric', `02/15/2025`
Lobby start time | -
'LLL', `February 15, 2025 8:30 PM` | 'dateTimeLong', `February 15, 2025 at 8:30 PM`
Message time and date | -
'LT', `8:30 PM` | 'timeShort', `8:30 PM`
'LL', `February 15, 2025` | 'dateLong', `February 15, 2025`
'lll', `Feb 15, 2025 8:30 PM` | 'dateTimeShort', `Feb 15, 2025, 8:30 PM`
Message reminders | -
'LT', `8:30 PM` | 'timeShort', `8:30 PM`
'ddd LT', `Sat 8:30 PM` | 'weekdayTimeShort', `Sat 8:30 PM`
'LLL', `February 15, 2025 8:30 PM` | …
> fix: replace moment.js with Intl formatters
