nextcloud/spreed

src/utils/signaling.js

rm -rf jquery/

---

src/components/MessagesList/MessagesList.vue
src/services/messagesService.js
src/store/messagesStore.js
src/utils/signaling.js

[stable18] Improve chat loading

---

src/components/RightSidebar/RightSidebar.vue

Add missing IDs to sidebar tabs

---

src/utils/signaling.js

Fix joining a call with internal signaling

---

css/icons.scss
src/components/ConversationIcon.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

> ![Bildschirmfoto von 2020-02-07 15-42-37](https://user-images.githubusercontent.com/213943/74039748-accfbd00-49c2-11ea-92a1-540cd70056d6.png)

Add a red camera icon for conversations with an ongoing call

---

CHANGELOG.md

Add changelog for 8.0.2

---

src/components/ConversationIcon.vue

> ![290-65-max](https://user-images.githubusercontent.com/213943/74132276-85593a00-4be6-11ea-8266-dc032b6c62e5.png)
Follow up to #2905

Only show the call or the favorite icon

---

src/services/signalingService.js
src/utils/signaling.js

Fix signaling from move to axios

---

src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/ConversationsList/ConversationsList.vue
src/components/LeftSidebar/LeftSidebar.vue
src/store/conversationsStore.js

2. Add to favorites
3. Remove from favorites
4. Check console
No errors
> ![Bildschirmfoto von 2020-02-10 09-49-34](https://user-images.githubusercontent.com/213943/74134359-b76c9b00-4bea-11ea-9300-e1c116a26691.png)

Fix vuex store modification issue

---

CHANGELOG.md

Changelog for v8.0.3

---

CHANGELOG.md
src/FilesSidebarTabApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/mainFilesSidebar.js
src/mainFilesSidebarLoader.js
src/mainPublicShareAuthSidebar.js
src/mainPublicShareSidebar.js
src/views/FilesSidebarTab.vue

Fix sidebars integrations

---

css/icons.scss
src/components/TopBar/TopBar.vue

Bring back the fullscreen option

---

CHANGELOG.md

Update changelog for 8.0.4

---

lib/Notification/Listener.php

This prevents issues when sending takes long, e.g. with a lot of users

Send the notifications after joining the call

---

lib/Activity/Listener.php

Also end teh call state when a user leaves

---

css/icons.scss
src/components/RightSidebar/RightSidebar.vue

Add "Go to file" link to conversation info

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue

Focus the chat input in the sidebars

---

src/FilesSidebarTabApp.vue
src/mainFilesSidebarLoader.js
src/services/filesIntegrationServices.js

* Open the files app
* Open sidebar of a folder
* See signaling connection being opened :boom: 
* See leave room `<empty string>` + request :boom: 
* See leave room `null` + request :boom: 
* See "Error: "

Only leave and join real conversations

---

src/components/NewMessageForm/NewMessageForm.vue

Print sharing error on correct level

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue

Fix copy-pasting into chrome/chromium/safari

---

lib/Listener.php
lib/TalkSession.php

Fix leaving a call on logout

---

lib/Config.php
tests/php/ConfigTest.php

Don't provide a stun without internet connection

---

src/components/NewMessageForm/NewMessageForm.vue

Fix #2890 
Backport will conflict, but I guess we should nevertheless backport it

Remove upload button from read only conversations

---

lib/AppInfo/Application.php
lib/Collaboration/Collaborators/Listener.php

* Add a user to a conversation
* Search their name and check the response of the `ocs/v2.php/core/autocomplete/get` request

Filtering of participant suggestions

---

lib/Settings/Admin/StunServer.php
src/views/AdminSettings/StunServers.vue
tests/php/CapabilitiesTest.php
tests/php/Settings/Admin/StunServerTest.php

Don't add default stun in UI on removal

---

src/components/MessagesList/MessagesList.vue

For guests we also need to set the last known message id
after the first grab of the history, otherwise they start loading
the full history with getNewMessages() because last known message
is still 0. Since the requests for getNewMessages() are doine right
away, it will make constant requests until the full chat is loaded
Fix #3020 
1. Create a public conversation with some messages
2. As a guest open the chat with network tab open
3. See a request to get the history
4. See a second request getting new messages containing the "XYZ created the conversation" (indicator that the chat beginning is loaded instead of new messages)

Correctly get new messages for guests

---

lib/Room.php

Before all guests were updated to moderators in the database

Only update the named session if it is a guest

---

lib/Chat/Notifier.php

Mark quote-author as mentioned also when there was no mention at all

---

src/components/LeftSidebar/LeftSidebar.vue
src/components/LeftSidebar/SearchBox/SearchBox.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue

Adds a button that allows to end the search operation.
Fix #2551

Add ✕ button to end search

---

src/components/NewMessageForm/NewMessageForm.vue

[stable18] Remove upload button from read only conversations

---

lib/Settings/Admin/StunServer.php
src/views/AdminSettings/StunServers.vue
tests/php/Settings/Admin/StunServerTest.php

[stable18] Don't add default stun in UI on removal

---

src/components/NewMessageForm/NewMessageForm.vue
src/store/fileUploadStore.js
src/utils/fileUpload.js

Rename duplicate files when uploading

---

Makefile

Cleanup the exclude list

---

src/components/LeftSidebar/LeftSidebar.vue

fix: #3047 
I think this is the best solution for now.

Don't interrupt search operation when clicking on a conversation

---

src/components/RightSidebar/RightSidebar.vue

Don't interrupt the renaming process when conversations are refreshed

---

lib/Signaling/Listener.php
tests/php/Signaling/BackendNotifierTest.php

The external signaling server expects to receive a `participants` message from the backend notifier when the participants in a room change. This message is in turn sent as a [participants update signaling message to the clients](https://github.com/nextcloud/spreed/blob/f5683d1771ff9f079653eb31c217e0568f812ecd/src/utils/signaling.js#L928), and the WebUI [updates the list of participants](https://github.com/nextcloud/spreed/blob/08b492054469f43e5c9cdcc2880bba19be723306/src/components/RightSidebar/Participants/ParticipantsTab.vue#L242) whenever that message is received.
However, when the type of a participant changes the backend notifier sent an `update` message instead, which is in turn sent as a [room list update signaling message to the …

Fix participant type change with external signaling server

---

src/components/ChatView.vue
src/components/NewMessageForm/NewMessageForm.vue
src/store/conversationsStore.js
src/utils/fileUpload.js

Add ability to upload files by dropping them in the chat

---

appinfo/routes.php
lib/Controller/PageController.php

Allow page reload on /not-found page

---

src/utils/signaling.js

Change redirect in case an error happens when joining a call

---

src/utils/webrtc/webrtc.js

Fix typo in debug message

---

package.json
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
src/components/MessagesList/MessagesList.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue
src/store/index.js
src/store/newGroupConversationStore.js
src/views/MainView.vue

Display contact sources in new group conversation creation search

---

docs/TURN.md

Extend the documentation a bit for when HPB is needed

---

jest.config.js
package-lock.json
package.json
tests/unit/example.spec.js

Kickstart unit tests

---

Makefile
package.json
tests/unit/example.spec.js

Fix test commands

---

package-lock.json
package.json

Add cli services

---

src/services/conversationsService.js
src/services/filesSharingServices.js
src/services/mentionsService.js

Fix #3088 
See issue for steps

Passwords with hashtags are cut

---

.github/workflows/test.yml
jest.config.js
package.json
src/test-setup.js

Execute unit tests on github

---

templates/settings/admin/turn-server.php

Don't include sha1 anymore

---

src/App.vue
src/components/TopBar/TopBar.vue
src/store/windowVisibilityStore.js

Hide navigation on fullscreen

---

src/components/CallView/CallView.vue

Fix video position

---

.github/workflows/lint.yml
.github/workflows/test.yml

Update github workflows

---

src/services/conversationsService.js
src/services/mentionsService.js

[stable18] Passwords with hashtags are cut

---

src/utils/webrtc/webrtc.js
src/views/AdminSettings/Commands.vue
src/views/AdminSettings/TurnServers.vue

Fix #915
Fix https://github.com/nextcloud/spreed/issues/2243

Show a warning on connection failed when no TURN server is set up

---

src/utils/webrtc/webrtc.js

[stable18] Prepare for janus 0.7.3

---

Makefile

Ship map files by default

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Make system messages light again

---

webpack.common.js
webpack.dev.js
webpack.prod.js

fix code style config files

---

src/utils/signaling.js

With the internal signaling currently you get one additional signaling request when changing to a different conversation.

Don't restart signaling for an old conversation

---

src/components/RightSidebar/Participants/ParticipantsTab.vue

Otherwise it could be that loading participants never finishes
when your server is not too responsive, as people join and quit
or ping faster than your requests load, it will always cancel
the previous attempt and start a new one
```diff
diff --git a/lib/Controller/RoomController.php b/lib/Controller/RoomController.php
index 1ddfc5e4..ee5c3317 100644
--- a/lib/Controller/RoomController.php
+++ b/lib/Controller/RoomController.php
@@ -689,6 +689,7 @@ class RoomController extends AEnvironmentAwareController {
]);
}
+               sleep(5);
return new DataResponse($results);
}
diff --git a/lib/Controller/SignalingController.php b/lib/Controller/SignalingController.php
index eef6baec..a05bc95a 100644
--- a/lib/Controller/SignalingController.php
+++ b/lib/Controller/SignalingController.php
@@ …
```

Don't cancel an on going fetch of participants via signaling

---

src/App.vue

Fixes #3144 
Closes #3181 
@Dids-Himanshu If you want, we could quickly get your PR merged first then merge this?
Signed-off-by: Gary Kim <gary@garykim.dev>

Improve Leave Call modal

---

src/components/RightSidebar/Participants/ParticipantsTab.vue
src/services/participantsService.js

Backport of #2880 
Backport of #3165

[stable18] Don't cancel an on going fetch of participants via signaling

---

src/App.vue

Add trailing comma

---

lib/Controller/PageController.php
package-lock.json
package.json
src/utils/webrtc/simplewebrtc/peer.js

Previous attempts:
* #1284
* #1171
```
./occ config:app:set spreed prefer_h264 --value yes
```
You should see the following message as debug in your browsers console:
```
'Preferring hardward codec H.264 as per global configuration'
```
Fix #1223

Prefer H264 codec when it is available

---

appinfo/info.xml
docs/conversation.md
lib/Controller/CallController.php
lib/Controller/RoomController.php
lib/Migration/Version8000Date20200331144101.php

Reduce database load against participants table

---

docs/TURN.md

Reflect the NAT situation a bit better in the TURN docs

---

lib/Controller/PageController.php
package-lock.json
package.json
src/utils/webrtc/simplewebrtc/peer.js

[stable18] Allow to prefer H.264 when available via a config

---

appinfo/info.xml
docs/conversation.md
lib/Controller/CallController.php
lib/Controller/RoomController.php
lib/Migration/Version8000Date20200331144101.php

[stable18] Reduce database load against participants table

---

CHANGELOG.md

Add changelog for 8.0.6

---

Makefile

[stable18] Ship map files by default

---

lib/Controller/SignalingController.php

Fix link to docs

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

fix messages padding

---

appinfo/info.xml
lib/Migration/Version8000Date20200402124456.php

User index on participants

---

appinfo/info.xml
lib/Migration/Version8000Date20200402124456.php

[stable18] Add user index on participants table

---

babel.config.js
webpack.common.js

[stable18] Compile some more libs to make IE load

---

src/utils/webrtc/webrtc.js

This fixes a regression introduced in 6187b28ba111487

Fix "unknown message" log when receiving valid data channel messages

---

CHANGELOG.md

Add changelog for 8.0.7

---

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/views/RoomSelector.vue

Use the primary element color in case it primary color is too bright

---

webpack.common.js

Fix webpack config

---

sample-commands/wikipedia.php

```
Wikipedia search results for "force":
* Force -  - https://en.wikipedia.org/wiki/Force
* Forced disappearance -  - https://en.wikipedia.org/wiki/Forced_disappearance
* Force India -  - https://en.wikipedia.org/wiki/Force_India
* Forced displacement -  - https://en.wikipedia.org/wiki/Forced_displacement
* Forced conversion -  - https://en.wikipedia.org/wiki/Forced_conversion
* and 5 more articles found
```
```
Wikipedia search results for "force":
* Force - Any action that tends to maintain or alter the motion of an object - https://en.wikipedia.org/wiki/Force
* Forced displacement - Coerced movement of a person or persons away from their home or home region - https://en.wikipedia.org/wiki/Forced_displacement
* Forced disappearance - Unlawful secret disappearance - …
```

Fix the wikipedia example

---

docs/capabilities.md
lib/Capabilities.php
lib/Collaboration/Collaborators/Listener.php
lib/Config.php
lib/ContactsMenu/Providers/CallProvider.php
lib/Controller/PageController.php
lib/Controller/RoomController.php
lib/Listener.php
lib/Settings/Admin/AdminSettings.php
src/components/AdminSettings/AllowedGroups.vue
src/components/AdminSettings/GeneralSettings.vue
src/components/LeftSidebar/LeftSidebar.vue
src/services/conversationsService.js
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation/limit-creation.feature
tests/php/CapabilitiesTest.php
tests/php/Controller/RoomControllerTest.php

Limit creating public and group conversations to a group

---

lib/Signaling/BackendNotifier.php
src/utils/signaling.js

Should have solved the unknown issues people were having on our cloud yesterday

Show a warning and error on signaling issues

---

package-lock.json
package.json

Bump vue-richtext from 0.3.0 to 0.3.1

---

appinfo/info.xml
lib/Migration/Version8000Date20200407073807.php

This is called from time to time as well. Especially on big instances
having this proper indexed saves a lot of row scanning.

Add index on the session_id

---

lib/Controller/PageController.php

Follow up to #3095
Conflict due to changes in #3153

Fix invalid config attribute after merge

---

lib/Signaling/BackendNotifier.php
src/utils/signaling.js

[stable18] Show a warning and error on signaling issues 

---

src/utils/signaling.js

Also cancel the warning timeout on success or error

---

src/components/AdminSettings/TurnServer.vue

TURN server testing feedback

---

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue

Fix appcontentlistitem active color

---

css/icons.scss

Fix broken conversation icons and CSS

---

lib/Controller/SignalingController.php
lib/Room.php
tests/php/Controller/SignalingControllerTest.php

Ping all session ids with 1 query from the external signaling

---

Makefile

Remove more dev files from final package

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
src/components/Quote.vue

Show previews of files in quotes

---

lib/Controller/PageController.php

[stable18] Remove unused template parameters

---

tests/php/Controller/SignalingControllerTest.php

Fix constructor in SignalingController unit tests

---

sample-commands/hackernews.php
sample-commands/wikipedia.php

Fix command samples

---

src/components/TopBar/CallButton.vue

Make leave-call button red

---

lib/Room.php

Correctly specify the parameter type on the placeholder

---

css/icons.scss
img/promoted-view.svg

Add `promoted-view` icon

---

lib/Share/RoomShareProvider.php

Always use table prefix in queries

---

src/components/CallView/CallView.vue

Remove the filter on the videos to improve the performance a lot

---

docs/webinar.md

Otherwise it is unreadable, see:

New line for readthedocs

---

lib/Config.php
lib/TInitialState.php
src/App.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/services/callsService.js
src/services/participantsService.js
src/utils/webrtc/index.js

Add wrappers for signaling related functions

---

README.md

...just to make things even more clear.

Minor rewording of scalability section of README

---

lib/Config.php
lib/TInitialState.php
src/App.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/services/callsService.js
src/services/participantsService.js
src/utils/webrtc/index.js

[stable18] Add wrappers for signaling related functions

---

package-lock.json
package.json
src/services/conversationsService.js
src/utils/webrtc/webrtc.js

Ref https://github.com/nextcloud/nextcloud-dialogs/pull/112

Update dialogs to support no timeout

---

css/video.scss

[stable17] Remove the filter on the videos to improve the performance a lot

---

lib/Manager.php

cc @apircalabu want to review this?

Fix ambiguous id in query of getRoomForParticipant

---

src/components/LeftSidebar/ConversationsList/ConversationsList.vue
src/services/conversationsService.js

Correctly catch errors that happen when fetching conversations

---

src/components/LeftSidebar/ConversationsList/Conversation.vue
src/utils/signaling.js

Handle more invalid responses

---

src/components/CallView/CallView.vue

[stable18] Improve call view

---

css/icons.scss

Fix three dot color when in a call

---

docs/settings.md
mkdocs.yml

Add documentation for the settings api

---

src/services/conversationsService.js
src/services/participantsService.js

Move more calls to API v2

---

.gitignore
Makefile

Update the exclude lists

---

src/components/LeftSidebar/ConversationsList/ConversationsList.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue

2 steps towards #3377
For now this could however debounce forever, so I want to keep the 30 second polling around.
It should still help a lot with the current issues, as joining/leaving doesn't make:
1. Parallel requests
2. Is only done after 3sec debounce.

Debounce reloading the room list

---

package-lock.json
package.json
src/components/CallView/CallView.vue
src/components/CallView/GridView/GridView.vue
src/components/CallView/shared/Video.vue
src/components/CallView/shared/VideoBackground.vue
src/components/TopBar/CallButton.vue
src/components/TopBar/TopBar.vue
src/store/callViewStore.js
src/store/index.js
src/views/MainView.vue
webpack.common.js

Video selection

---

.github/workflows/lint.yml
composer.json

Ref https://github.com/nextcloud/server/pull/20952

Fix linter command

---

CHANGELOG.md

Add changelog for 8.0.9

---

.drone.yml

Fix stable19 testing target

---

appinfo/info.xml
package-lock.json
package.json
tests/integration/spreedcheats/appinfo/info.xml

Adjust version and requirement on master

---

lib/Controller/RoomController.php

Take config settings into account when promoting an update

---

src/components/AdminSettings/Commands.vue
src/components/AdminSettings/SignalingServers.vue
src/components/AdminSettings/TurnServers.vue

Use new initial state

---

appinfo/info.xml
lib/BackgroundJob/CheckReferenceIdColumn.php
lib/Capabilities.php
lib/Controller/RoomController.php
tests/php/CapabilitiesTest.php

Only add chat reference id capability when it exists

---

src/FilesSidebarCallViewApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/components/CallView/CallView.vue
src/components/CallView/GridView/GridView.vue
src/components/CallView/shared/EmptyCallView.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/Video.vue

Fix the callview in sidebars

---

docs/chat.md

Add docs for message.parent

---

lib/Controller/ChatController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/reply.feature

Correctly pick the parent if it is index 0 of the messages

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Don't auto join a new conversation when you are in a call

---

src/components/TopBar/CallButton.vue

Add a tooltip for the disabled "Start call" button

---

lib/Config.php
lib/Settings/Admin/AdminSettings.php
lib/TInitialState.php
src/components/AdminSettings/SignalingServers.vue
src/constants.js
tests/php/Settings/Admin/AdminSettingsTest.php

Don't allow multiple HPB without clustering and add a cache warning

---

src/mixins/browserCheck.js

Ref https://github.com/nextcloud/spreed/pull/3602#pullrequestreview-414081675

Fix browser version comparison with Chromium

---

lib/Share/RoomShareProvider.php

If available creatae a cacheentry

---

src/components/CallView/CallView.vue

Improve grid target aspect ratio

---

src/components/CallView/shared/Video.vue

Remove lock icon

---

src/components/CallView/Grid/Grid.vue

Show first joining participant in grid-view

---

src/components/CallView/Grid/Grid.vue

Fix grid view error when last participant leaves

---

src/utils/webrtc/index.js

The token passed to "startCall" was set when WebRTC was set up. However, WebRTC is set up only when the signaling server is changed. Therefore, when joining a call in a different conversation but in the same signaling server the token used was the one from the first conversation.

Fix joining a different call on the same signaling server

---

CHANGELOG.md

Move the changelog to 9.0.0 so it shows in the appstore

---

docs/call.md
docs/chat.md
docs/constants.md
docs/conversation.md
docs/integration.md
docs/internal-signaling.md
docs/participant.md
docs/settings.md
docs/webinar.md
mkdocs.yml

Add docs for the HPB conversation clustering

---

src/App.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/utils/signaling.js

Please see commit messages for details.

Do not fetch all conversations on some signaling events

---

src/components/TopBar/TopBar.vue

Close action menu after entering/leaving fullscreen

---

src/components/CallView/shared/VideoBackground.vue

1. Have a call with a guest
2. See a request for `https://localhost/index.php/avatar/null/300`

Don't request avatars for user null

---

package-lock.json
package.json
src/App.vue
src/components/RightSidebar/RightSidebar.vue
src/components/TopBar/TopBar.vue
src/services/BrowserStorage.js

Move sidebar state to browser storage package

---

src/components/TopBar/CallButton.vue

Add 4px space between icon and label of the call button

---

src/components/CallView/shared/Screen.vue
src/components/CallView/shared/Video.vue
src/components/CallView/shared/VideoBottomBar.vue

- create a call with at least 2 participants
- share the screen with one of them 
no name or unfollow button were displayed;
participant name and unfollow button are displayed

Add bottombar in screensharings

---

appinfo/info.xml
lib/Command/ActiveCalls.php

Exit code 0
Exit code 1
Fix #3671

Add a command to detect active calls

---

src/components/CallView/shared/VideoBottomBar.vue

Make the video button half opace as well

---

src/components/CallView/Grid/Grid.vue

Reduce console spam unless in dev mode

---

src/utils/signaling.js

Reduce console logging unless in debug

---

lib/Command/Room/Add.php
lib/Command/Room/Create.php
lib/Command/Room/Delete.php
lib/Command/Room/Demote.php
lib/Command/Room/Promote.php
lib/Command/Room/Remove.php
lib/Command/Room/TRoomCommand.php
lib/Command/Room/Update.php
lib/Manager.php
lib/Room.php
tests/php/Command/Room/AddTest.php
tests/php/Command/Room/CreateTest.php
tests/php/Command/Room/DeleteTest.php
tests/php/Command/Room/DemoteTest.php
tests/php/Command/Room/PromoteTest.php
tests/php/Command/Room/RemoveTest.php
tests/php/Command/Room/RoomMockContainer.php
tests/php/Command/Room/TRoomCommandTest.php
tests/php/Command/Room/UpdateTest.php

backport of #3505
I don't really understand why automatically backporting this to 19 failed... There were no conflicts :confused:

[stable19] Improve talk:room:* CLI commands

---

src/components/LeftSidebar/LeftSidebar.vue
src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue

Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

l10n: Fixed typo

---

src/components/NewMessageForm/NewMessageForm.vue
src/store/conversationsStore.js

Immediately move conversation up when sending a message

---

lib/Chat/Parser/SystemMessage.php
lib/Chat/SystemMessage/Listener.php

Special handling of CLI administrators in system messages

---

lib/Controller/RoomController.php

It was dropped wih Room v2 API after the participant list was dropped completly there (ref https://github.com/nextcloud/spreed/pull/3271 )

Bring back session expiration

---

lib/Controller/ChatController.php

Don't ping the session while waiting for chat messages

---

lib/Controller/RoomController.php

Fix user timeout with numeric ids

---

.github/ISSUE_TEMPLATE/bug_report.md

Add signaling server to issue template

---

package-lock.json
package.json

To profit from https://github.com/nextcloud/nextcloud-dialogs/commit/8b88d8fe2980e8c03d867362e9d9333b69b6f24b

Update @nextcloud/dialogs so toasts show for guests

---

src/components/AdminSettings/GeneralSettings.vue

Failure from #2858 yielding an error in the browser console.

Fix usage of uninitialized variable

---

src/components/AdminSettings/HostedSignalingServer.vue

Follow up to #3620
Fixes #3802

Fix typo in trial

---

.drone.yml
.github/workflows/lint.yml

Validate the info.xml file with a workflow

---

package-lock.json
package.json
src/components/CallView/shared/VideoBackground.vue

Use usernameToColor from @nextcloud/vue

---

package-lock.json
package.json

[stable19] Bump webrtc-adapter to 7.6.2

---

package-lock.json
package.json

[stable18] Bump webrtc-adapter to 7.6.2

---

.drone.yml
tests/php/Signaling/BackendNotifierTest.php

Aparently `POSTGRES_HOST_AUTH_METHOD: trust` was missing

Enable fixed postgres tests again

---

lib/Notification/Notifier.php
tests/php/Notification/NotifierTest.php

Circumvent long messages breaking the notification app by accident

---

src/utils/webrtc/VideoConstrainer.js

When video constraints are adjusted based on the quality applying the default constraints may fail, and a relaxed but roughly equivalent set of constraints has to be found to be applied instead.
Until now the check for the valid constraints was done every time the quality was changed. Now a cache is added to keep track of valid constraints for each quality to apply them directly.
**Reviewers:** for some reason I was not able to make my Firefox fail to set the default constraints :shrug: so I could only check that the default constraints were cached, but not the relaxed ones, which is in fact the reason to have this... If possible please verify that `Failed to set quality` is shown when changing to certain quality for the first time, but then it is no longer shown. Thanks!

Add cache for video constraints

---

lib/Command/ActiveCalls.php
lib/Command/Command/Add.php
lib/Command/Command/AddSamples.php
lib/Command/Command/Delete.php
lib/Command/Command/ListCommand.php
lib/Command/Command/Update.php
lib/Command/Room/Add.php
lib/Command/Room/Create.php
lib/Command/Room/Delete.php
lib/Command/Room/Demote.php
lib/Command/Room/Promote.php
lib/Command/Room/Remove.php
lib/Command/Room/Update.php
lib/Command/Signaling/Add.php
lib/Command/Signaling/Delete.php
lib/Command/Signaling/ListCommand.php
lib/Command/Stun/Add.php
lib/Command/Stun/Delete.php
lib/Command/Stun/ListCommand.php
lib/Command/Turn/Add.php
lib/Command/Turn/Delete.php
lib/Command/Turn/ListCommand.php

Add return types to commands

---

lib/Command/Room/Create.php
lib/Command/Room/TRoomCommand.php
lib/Controller/FilesIntegrationController.php
lib/Controller/PublicShareAuthController.php
lib/Controller/RoomController.php
lib/Manager.php
lib/Service/RoomService.php
tests/php/Command/Room/AddTest.php
tests/php/Command/Room/CreateTest.php
tests/php/Command/Room/DeleteTest.php
tests/php/Command/Room/DemoteTest.php
tests/php/Command/Room/PromoteTest.php
tests/php/Command/Room/RemoveTest.php
tests/php/Command/Room/UpdateTest.php
tests/php/Controller/RoomControllerTest.php
tests/php/Controller/SignalingControllerTest.php
tests/php/Service/RoomServiceTest.php
tests/php/Signaling/BackendNotifierTest.php

Currently only room creation is done, but I prefer small steps in the migration.
Integration tests should confirm that everything still works as intended

Services: Start room service

---

lib/Listener.php

Backport of #3863
I have not been able to reproduce the issue from _master_ in _stable19_; as soon as the user is removed her UI is updated to show that the conversation does not exist, so there is not enough time to logout. In _master_ it took much longer and it was easier to trigger the issue, I have not digged further to check why. I did not bother to force the code to wait longer to check the issue either, as catching the exceptions still sounds like a good idea.

[stable19] Fix logout failure if active session was removed from room

---

docs/system-requirements.md
mkdocs.yml

Document system requirements

---

docs/call-experience.md
mkdocs.yml

Add documentation about call experience

---

package-lock.json
package.json

Revert "Bump webpack-merge from 4.2.2 to 5.0.9"

---

package-lock.json
package.json
webpack.dev.js
webpack.prod.js

Revert "Revert "Bump webpack-merge from 4.2.2 to 5.0.9""

---

src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue

Don't trimm displayname in selection

---

package-lock.json
package.json

[stable18] Bump @juliushaertl/vue-richtext from 0.3.0 to 0.3.2

---

package-lock.json
package.json

Adds progress bar and emoji picker

bump @nextcloud/vue

---

src/store/fileUploadStore.js

Fix wrong argument in the upload store

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Fix spinner position

---

src/store/fileUploadStore.js
src/utils/fileUpload.js

- Displays temporary messages for each file immediately for bulk uploads
- Delays the deletion of temporary message

Display multiple simultaneous uploads

---

tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/SharingContext.php

* See https://drone.nextcloud.com/nextcloud/spreed/8031/20/4
* See https://drone.nextcloud.com/nextcloud/spreed/8031/22/4

Presort the mention suggestions to fix postgres integration tests

---

package-lock.json
package.json
webpack.common.js

Use `babel-loader-exclude-node-modules-except`

---

webpack.common.js

Make IE11 render the page again

---

lib/Controller/SignalingController.php
lib/Signaling/BackendNotifier.php

Always allow local HPBs

---

src/FilesSidebarCallViewApp.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthRequestPasswordButton.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue

Only show browser warning when interacting with talk

---

lib/Activity/Listener.php
lib/BackgroundJob/CheckHostedSignalingServer.php
lib/BackgroundJob/RemoveEmptyRooms.php
lib/Chat/Command/Executor.php
lib/Controller/HostedSignalingServerController.php
lib/Controller/PageController.php
lib/Controller/SettingsController.php
lib/Notification/Listener.php
lib/Service/HostedSignalingServerService.php
lib/Signaling/BackendNotifier.php
tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
tests/php/Chat/Command/ExecutorTest.php
tests/php/Signaling/BackendNotifierTest.php

Move to Psr\Log\LoggerInterface

---

package-lock.json
package.json

Downgrade CSS Loader to 3.6 for now to fix IE11

---

lib/Search/ConversationSearch.php

see https://github.com/nextcloud/server/pull/22120

Fix search order

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Show date on hover of time

---

src/views/Dashboard.vue

Remove duplicated slashes

---

src/views/RoomSelector.vue

- Conversations are not ordered as in the app navigation
- Conversation icons are not as "expected"
- Adjust selection style to current state of the art
- Better styling of the headline (and same wording as the file picker for projects)
Before | After
---|---
Fix #2314

Multiple fixes to the conversation selector for projects

---

src/components/TopBar/TopBar.vue

Fix translation

---

src/views/Dashboard.vue

Ref https://github.com/nextcloud/server/issues/22339

Better empty content on dashboard

---

src/components/Quote.vue

Fix semantic markup for replies

---

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

Add anchor ids to conversations

---

lib/Search/MessageSearch.php

Fix search anchor

---

lib/Search/CurrentMessageSearch.php
lib/Search/MessageSearch.php

Ref https://github.com/nextcloud/server/pull/22422

Fix pagination of message search

---

src/components/CallView/CallView.vue

Add abilitiy to select localvideo

---

css/At.scss
package-lock.json
package.json
src/components/AvatarWrapper/AvatarWrapper.vue
src/components/AvatarWrapper/AvatarWrapperSmall.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/Video.vue
src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/RightSidebar/RightSidebar.vue

Show the status on avatars

---

package-lock.json
package.json

Bump @nextcloud/vue-dashboard to 0.1.8

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

| Before  | After |
| ------------- | ------------- |
| ![Screenshot from 2020-08-27 11-02-03](https://user-images.githubusercontent.com/26852655/91420350-df54e080-e854-11ea-9d21-be1b606dee9e.png) | ![Screenshot from 2020-08-27 11-01-29](https://user-images.githubusercontent.com/26852655/91420365-e67bee80-e854-11ea-8790-1ab0cd462818.png) |

Do not show the status in the new group conversation flow

---

src/utils/webrtc/simplewebrtc/peer.js

Prevent infinite loop in datachannel open re-transmission

---

src/components/Caption.vue

Make sidebars' captions bold

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Use v-tooltip instead of popover for new group conversation's tooltip

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue

Fix focus state after pasting something into the chat input

---

src/components/TopBar/TopBar.vue

Improve promoted view wording

---

lib/Controller/ChatController.php
lib/Controller/RoomController.php

Ref https://github.com/nextcloud/nextcloud-vue/pull/1379
The status was still leaked on mention suggestions and in the participant list for guest moderators

No statuses for guests

---

package-lock.json
package.json

Bump @nextcloud/vue to 2.6.4

---

lib/Controller/MatterbridgeController.php
lib/MatterbridgeManager.php
src/components/RightSidebar/Matterbridge/BridgePart.vue
src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue

New stuff:
* Do not translate protocol/system names
* Fix IRC connection password in generated config for IRC
* Add NickServ-related fields for IRC
* New BridgePart field type: checkbox

Matterbridge adjustments

---

appinfo/info.xml
lib/BackgroundJob/CheckMatterbridges.php
lib/BackgroundJob/RemoveEmptyRooms.php
lib/BackgroundJob/ResetAssignedSignalingServer.php

refs #4097
Start the ones that should be running, kill the ones that are not related with a room in config.

Job to check Matterbridge processes

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue

Remove colon before style tag

---

docs/matterbridge.md
mkdocs.yml
src/components/AdminSettings/MatterbridgeIntegration.vue

Add link to doc explaining how to customize matterbridge binary path

---

lib/Chat/Parser/SystemMessage.php
lib/Controller/MatterbridgeController.php
lib/MatterbridgeManager.php
src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue

refs #4099 
I just had trouble including the bridged systems in the system messages. Hints are welcome :grin:.

Log matterbridge start/stop actions in related room

---

package-lock.json
package.json

* Fix status on different active/hover states
* Fix group avatar handling in user bubble

Bump @nextcloud/vue lib to 2.6.5

---

src/components/MessagesList/MessagesGroup/AuthorAvatar.vue

Avatar menu of chat in sidebar underflows video layout

---

src/components/MessagesList/MessagesList.vue

Fix scrolling of sidebar's chat

---

lib/Search/MessageSearch.php

Better title for search results in one-to-one conversations

---

Makefile

Don't update packages on npm-init or dev-setup

---

lib/MatterbridgeManager.php

Fix IRC nickserv credentials

---

lib/Controller/PageController.php
lib/Controller/RoomController.php

Fix #4186 
1. Create one to one conversation with a user
2. Open the avatar menu of that user any where
3. Click on "Talk with X"
4. Be greeten by 500

Also return the conversation data when the room exists already

---

lib/BackgroundJob/ResetAssignedSignalingServer.php

Ref https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/lib/public/BackgroundJob/Job.php#L55-L60

Fix missing parent constructor call

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/mixins/userStatus.js

As discussed being online is more important information than being a moderator.

Online > User type

---

lib/Migration/Version11000Date20200922161218.php

Fix update query

---

lib/Chat/Changelog/Manager.php

Add "New in Talk 10" section

---

CHANGELOG.md

Add changelog for 10.0.0-rc.2

---

docs/matterbridge.md

Just some small fixes and improvements for the Matterbridge documentation.

Small fixes for Matterbridge documentation

---

src/components/MessagesList/MessagesList.vue

Make the "Scroll to bottom" button non-primary

---

lib/Controller/ChatController.php
tests/php/Controller/ChatControllerTest.php

Set the user status when a mobile client polls for messages

---

src/components/SettingsDialog/SettingsDialog.vue

The string text will appear in Transifex.

l10n: Improving the string mark

---

package-lock.json
package.json

Bump @nextcloud/vue to 2.6.6 for the status avatar updates

---

package-lock.json
package.json
src/components/AvatarWrapper/AvatarWrapper.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/mixins/userStatus.js

Ref https://github.com/nextcloud/nextcloud-vue/pull/1422 and https://github.com/nextcloud/server/pull/23114

Show icon only with dnd status in the message

---

CHANGELOG.md

Combine the changelog for 10.0.0 in the appstore

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue

Don't load the user_status in big conversations

---

package-lock.json
package.json

Add style loader

---

lib/MatterbridgeManager.php
src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue

* Connection password field was used as channel password
* Channel password field was missing
refs #4283

Fix IRC bridge connection password and add channel password field

---

README.md

Update list of integrated apps and update some version examples

---

src/components/CallView/shared/LocalMediaControls.vue

How to test: start a call with an active mic and press spacebar.
fix #603 

Add push to talk and push to mute

---

tests/php/RoomTest.php

EventDispatcher uses PSR Logger now

---

src/components/CallView/shared/LocalMediaControls.vue
src/components/TopBar/TopBar.vue

Max width on call view tooltips

---

lib/Chat/SystemMessage/Listener.php
lib/Share/Listener.php

Fixes https://github.com/nextcloud/spreed/issues/4404
I could not test locally as the local version (even the composer one) does not even report those issues.
Let's see what CI says...

Skip psalm issues related to hook names

---

lib/Chat/CommentsManager.php

Update comments manager constructor

---

src/components/CallView/shared/LocalMediaControls.vue

Fix bug when being muted by a moderator while on push to talk

---

CHANGELOG.md

Add changelog for 10.0.1, 9.0.5 and 8.0.12

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

[stable18] Add changelog for 8.0.12 

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

[stable19] Add changelog for 9.0.5 and 8.0.12 

---

tests/integration/features/conversation/set-password.feature

Correctly leave the room not the call in integration tests

---

composer.json
composer.lock
tests/psalm-baseline.xml

1) Adjusted composer psalm commands
- Run with a single thread, otherwise it crashes on some environments like mine...
- Added composer command to clear psalm's caches.
- Added command to update the baseline automatically
2) Update and lock christophwurst/nextcloud to 70e36349cd
3) Update Psalm baseline for listener
Fixes https://github.com/nextcloud/spreed/issues/4512
4) Automatic cleanup Psalm baseline
Ran `composer run psalm:update-baseline`

Fix psalm issues plus extras

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Use standard size for new group conversation modal

---

src/components/SettingsDialog/SettingsDialog.vue

Add push to talk and push to mute instructions

---

package-lock.json
package.json

Changelog here https://github.com/nextcloud/nextcloud-vue/releases/tag/v2.9.0

Bump @nextcloud/vue to 2.9.0

---

package-lock.json
package.json

Changelog here: https://github.com/nextcloud/nextcloud-vue/releases/tag/v3.2.0
Fixes https://github.com/nextcloud/spreed/issues/4330

Bump @nextcloud/vue to 3.2.0

---

lib/Notification/Notifier.php

Fix https://github.com/nextcloud/spreed/issues/4354

Politer language for call notifications for private calls 

---

package.json

Fix build production

---

lib/Controller/RoomController.php

[stable18] Also delete the room if the last moderator leaves

---

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue

Sort call participants up

---

CHANGELOG.md

Add changelogs for 10.0.2, 9.0.6 and 8.0.13

---

lib/Participant.php
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/constants.js

Fixes warning about missing "callIcon" property.

[stable20] Add a phone icon for SIP phone users

---

appinfo/info.xml

After already 50+ PRs I guess it was time :-D

Add Vincent to authors

---

src/components/CallView/shared/EmptyCallView.vue

Resend of https://github.com/nextcloud/spreed/pull/4617
Fixes #4311

Fix "Copy link" button not clickable (resend)

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Best tested with https://github.com/nextcloud/spreed/pull/4620 :
I wasn't sure about the wording and didn't want to delay the above PR, so made this separate PR.
Let me know what you think.

Add tooltips to call icons in participant list

---

composer.json

Fix the psalm:update-baseline command

---

package-lock.json
package.json

- unblocks https://github.com/nextcloud/spreed/pull/4576 by fixing the app settings dialog

Bump @nextcloud/vue from 3.2.0 to 3.3.0

---

.github/no-response.yml

Add "No response" bot

---

src/assets/variables.scss

Seems both come from the same commit by @ma12-co :-)

Remove duplicate top bar height scss variable

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Center vertically the moderator and guest indicator in the participant
row.

Vertically align participant indicator

---

src/components/CallView/shared/LocalMediaControls.vue

Fixes https://github.com/nextcloud/spreed/issues/4616
See steps to reproduce here https://github.com/nextcloud/spreed/issues/4616#issuecomment-738134192
Instead of letting Vue take care of updating the height and also affecting all neighbors, set the height directly to the element when the value changes, detected by a watcher.
~~Bonus: added transition for the height for a smoother fade!~~
We might want to backport this.

Fix volume indicator performance

---

tests/integration/spreedcheats/appinfo/routes.php
tests/integration/spreedcheats/lib/AppInfo/Application.php
tests/integration/spreedcheats/lib/Controller/ApiController.php

Update Spreed Cheats for 21

---

lib/MatterbridgeManager.php

The bot user was never removed from rooms. It is now done when the bridge is disabled.

Remove bridge bot from room when bridge is disabled

---

lib/Chat/Changelog/Manager.php

Prevent issues with utf8mb4 chars on update

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 10.1.0-rc.1

---

docs/settings.md

Document read-status privacy setting

---

lib/MatterbridgeManager.php
src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue

As mentioned in #4719, `channel` is the key used for all services in `gateway` section.
MsTeams is now finally working.

Fix MsTeams and Steam Matterbridge config

---

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue

Display hint when no participant found in right sidebar

---

lib/MatterbridgeManager.php

This clarifies how we run commands and launch Matterbridge binary. It silences the processes. Output is now parsed with Php instead of using pipes, grep, awk and wc (which might all be missing on some systems).
refs  #4743

Use proc_open to run system commands in bridge manager

---

package-lock.json
package.json

Fixes avatar context menu click event by bumping nextcloud-vue to 3.3.2.
Retested, works.
Fixes https://github.com/nextcloud/spreed/issues/4718

Update nextcloud-vue to 3.3.2 and fix avatar menu

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Message status ux improvements

---

CHANGELOG.md
appinfo/info.xml

[stable18] Add changelog for 8.0.14

---

CHANGELOG.md
appinfo/info.xml

[stable19] Add changelog for 9.0.7

---

CHANGELOG.md
appinfo/info.xml

[stable20.1] Add changelog for 10.1.0

---

package-lock.json
package.json

Revert "Bump @babel/preset-env from 7.12.10 to 7.12.11"

---

lib/Service/HostedSignalingServerService.php

Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

Fixed grammar

---

src/components/CallView/shared/VideoBottomBar.vue

Lower names font sizes in calls

---

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

- Fix counter pushed to the right by long messages
- Fix smaller bubble on some counters

Fix counters

---

composer.json
composer.lock

Only allow dev quality for christophwurst/nextcloud

---

src/components/RightSidebar/Description/Description.vue

Fix description fade-out on dark mode

---

tests/integration/spreedcheats/lib/Controller/ApiController.php

This is a leftover from c0358096b3e5 (#4764).

Remove undefined variable from spreedcheats controller cleanup

---

docs/capabilities.md
docs/conversation.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add capability for room descriptions

---

lib/Controller/RoomController.php
tests/integration/features/conversation/remove-self.feature

Don't remove a chat when a self-joined user leaves

---

src/components/RightSidebar/Description/Description.vue

Fix always expandable descriptions

---

src/components/CallView/Grid/Grid.vue
src/store/callViewStore.js

Fix call view errors

---

lib/Controller/GuestController.php
lib/GuestManager.php
lib/Migration/Version10000Date20200819121721.php
lib/Migration/Version10000Date20201012144235.php
lib/Migration/Version10000Date20201015134000.php
lib/Migration/Version11000Date20200922161218.php
lib/Migration/Version11000Date20201011082810.php
lib/Migration/Version2000Date20170707093535.php
lib/Migration/Version2001Date20170707115443.php
lib/Migration/Version2001Date20170913104501.php
lib/Migration/Version2001Date20170921145301.php
lib/Migration/Version2001Date20171009132424.php
lib/Migration/Version2001Date20171026134605.php
lib/Migration/Version2001Date20171031102049.php
lib/Migration/Version2001Date20180103144447.php
lib/Migration/Version3003Date20180707222130.php
lib/Migration/Version3003Date20180718112436.php
lib/Migration/Version3003Date20180718133519.php
lib/Migration/Version3003Date20180720162342.php
lib/Migration/Version3003Date20180722152849.php
lib/Migration/Version3003Date20180730080327.php
lib/Migration/Version4099Date20181001123058.php
lib/Migration/Version5099Date20190121102337.php
lib/Migration/Version5099Date20190319134820.php
lib/Migration/Version6099Date20190627172429.php
lib/Migration/Version7000Date20190717141457.php
lib/Migration/Version7000Date20190724121136.php
lib/Migration/Version8000Date20200407115318.php
psalm.xml
tests/psalm-baseline.xml

Update code to work with doctrine/dbal 3.0

---

CHANGELOG.md
appinfo/info.xml

Changelog for 8.0.15

---

CHANGELOG.md
appinfo/info.xml

Changelog for 9.0.8

---

CHANGELOG.md
appinfo/info.xml

Changelog for 10.0.5

---

CHANGELOG.md
appinfo/info.xml

Changelog for 10.1.1

---

CHANGELOG.md
appinfo/info.xml

Changelog for 11.0.0-alpha.3

---

src/views/Dashboard.vue

Fixes https://github.com/nextcloud/spreed/issues/4466

Show unread 1-1 messages in dashboard widget

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue

Simple text link for now, with "Stack in Board" on hover
https://github.com/nextcloud/server/pull/25070

Add deck cards as dedicated simple rich object string parameters

---

package-lock.json
package.json

Ref https://github.com/nextcloud/nextcloud-vue/releases/tag/v3.4.0
Brings in link support in input field.

Bump @nextcloud/vue from 3.3.2 to 3.4.0

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/RightSidebar/SipSettings.vue
src/mixins/readableNumber.js

Details | Participant list
---|---
Fix #4947

Make the dial-in info better readable

---

lib/Collaboration/Resources/Listener.php

Regression from the participant rewrite in  #4324

Fix "Undefined index: userId"

---

src/components/CallView/shared/LocalVideo.vue

Fix local video positioning

---

package-lock.json
package.json

To fix Safari due to linkify-urls issue in https://github.com/nextcloud/spreed/issues/4995

Bump @nextcloud-vue from 3.5.2 to 3.5.3

---

css/icons.scss
src/assets/buttons.scss
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
src/components/MessagesList/MessagesList.vue
src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/RightSidebar/Description/Description.vue

Fix description icon sizes

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/store/fileUploadStore.js

Follow up to fix wording from https://github.com/nextcloud/spreed/pull/5031

Fix free space wording

---

lib/MatterbridgeManager.php

In any case, config file presence is checked when launching Matterbridge binary. It can be missing after a reboot for example.
refs #4776

Recreate matterbridge config file if missing when launching

---

src/assets/variables.scss
src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/EmptyCallView.vue

Make background black again

---

appinfo/routes.php
docs/participant.md
lib/Controller/RoomController.php
lib/GuestManager.php
lib/Service/ParticipantService.php
src/components/ConversationSettings/LinkShareSettings.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/constants.js
src/services/participantsService.js
src/store/participantsStore.js

Allow resending invitation emails

---

.drone.yml
.github/workflows/phpunit.yml

Update stable21 target versions

---

src/components/LeftSidebar/ConversationsList/Conversation.vue

Fix forced active action looks

---

.github/workflows/phpunit.yml
src/App.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/TopBar/TopBar.vue

Fix unwanted background changes in some buttons

---

.github/workflows/phpunit.yml

Had to do this on master as well in #5061

[stable21] Explcitly install gd and zip PHP extensions in CI

---

tests/drone-run-acceptance-tests.sh
tests/drone-run-integration-tests.sh
tests/drone-run-php-tests.sh

Run all tests on info.xml modifications

---

tests/integration/features/sharing/get.feature
tests/integration/features/sharing/hooks.feature
tests/integration/features/sharing/move.feature
tests/integration/features/sharing/restore.feature
tests/integration/features/sharing/update.feature

Fixes https://github.com/nextcloud/spreed/issues/5120
This adjusts the tests to accomodate for the fix from https://github.com/nextcloud/spreed/pull/5076

Fix sharing tests to work with attachment folders fix

---

lib/Chat/Notifier.php
lib/Command/Room/TRoomCommand.php
lib/Controller/RoomController.php
lib/Files/Listener.php
lib/Manager.php
lib/MatterbridgeManager.php
lib/Service/ParticipantService.php
lib/Service/RoomService.php
tests/php/Service/RoomServiceTest.php

Populate the display name when adding logged in users

---

.drone.yml
tests/drone-run-acceptance-tests.sh
tests/drone-run-integration-tests.sh
tests/drone-run-php-tests.sh

The guests app checkout was missing in some of the integration-conversation runs.
Signed-off-by: Vincent Petry <vincent@nextcloud.com>

Add guests app in CI runs that need it

---

appinfo/info.xml
lib/Migration/CacheUserDisplayNames.php

Add a repair step that updates the display name for existing users

---

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
src/components/LeftSidebar/ConversationsList/ConversationsList.vue
src/components/LeftSidebar/LeftSidebar.vue

WIP to update the left sidebar design a bit.

Update the left sidebar design

---

tests/drone-run-acceptance-tests.sh
tests/drone-run-integration-tests.sh
tests/drone-run-php-tests.sh

From https://github.com/nextcloud/spreed/pull/5145 and follow up of #5121

[stable20.1] Retrigger full CI when drone.yml was changed

---

src/components/NewMessageForm/NewMessageForm.vue
src/services/participantsService.js
src/store/messagesStore.js

Fix js error when posting as guest

---

css/icons.scss

Fix missing delete icon

---

src/components/AdminSettings/TurnServer.vue

Help translators

---

docs/capabilities.md
docs/constants.md
docs/conversation.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add docs and capability for callFlag of conversations

---

docs/call.md
docs/chat.md
docs/constants.md
docs/conversation.md
docs/internal-signaling.md
docs/participant.md
docs/settings.md
docs/webinar.md
lib/Controller/RoomController.php
mkdocs.yml

Fix API documentation

---

docs/conversation.md

Sort by isFavorite and lastActivity instead of lastPing

---

lib/Search/MessageSearch.php

Replace all message parameters and not only the last one

---

lib/Room.php

Drop guest moderators when changing a conversation to group conversation

---

lib/Migration/Version10000Date20201015134000.php

1. Install on stable20
2. Create a room and join it
3. In the oc_talk_participants table create a second entry without a session id (so use string `'0'`) for your user and that room
4. Checkout stable20.1 and try to update
💥  Unique constraint violation
🏁  Only one attendee is added and all is fine.

Try to catch the unique constraint violation on migrating the data

---

src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/ConversationSettings/DangerZone.vue
src/components/ConversationSettings/NotificationsSettings.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/LeftSidebar.vue
src/components/TopBar/TopBar.vue
src/store/conversationsStore.js

Copy actions in conversation menu into the new conversation settings dialog

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

Check viewer handlers before using them

---

package-lock.json
package.json

Should unblock a few things for @ma12-co

Bump @nextcloud/vue from 3.5.4 to 3.6.0

---

lib/Controller/ChatController.php
src/components/MessagesList/MessagesGroup/Message/Message.vue
tests/integration/features/chat/delete.feature

Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>
solves #5290
But unfortually it doesn't work. 
Who can help?

don't allow to delete other persons chats in 1-1 chats

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 10.1.3

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

Use MDI in video preview in a conversation

---

lib/Controller/RoomController.php

Fix copy paste error on parameter docs

---

package-lock.json
package.json

Fixes https://github.com/nextcloud/spreed/issues/5292
I've tested to confirm.
Thanks a lot to @ma12-co for fixing the issue in the lib!

Bump @nextcloud/vue from 3.7.0 to 3.7.1

---

composer.lock
lib/BackgroundJob/CheckReferenceIdColumn.php
psalm.xml

Fix the background job checking the schema

---

css/app.scss
css/merged.scss
src/components/CallView/shared/LocalMediaControls.vue

Use actions for screensharing menu

---

src/components/CallView/shared/LocalMediaControls.vue

Add "(r)" shortcut key for raise/lower hand to label

---

src/components/AdminSettings/SIPBridge.vue

Hide SIP settings without a HPB

---

.drone.yml
appinfo/routes.php
composer.json
composer.lock
lib/Capabilities.php
lib/Controller/TempAvatarController.php
tests/php/CapabilitiesTest.php
tests/psalm-baseline.xml

[stable21.1] Temporary OCS API for user avatar upload and delete 

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Fix constant usage

---

src/store/fileUploadStore.js

Only use local preview for some image types

---

lib/Migration/Version10000Date20201015134000.php

Fix migration checking for unique constraint violation

---

lib/Migration/Version10000Date20201015134000.php
lib/Migration/Version12000Date20210401124139.php

Ref https://github.com/nextcloud/server/pull/24055

Notnull Boolean fields break oracle

---

src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/ConversationSettings/DangerZone.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/services/conversationsService.js
src/services/filesSharingServices.js
src/services/participantsService.js
src/utils/signaling.js

Handle failed server responses more gracefully

---

src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/services/conversationsService.js
src/services/filesSharingServices.js
src/services/participantsService.js
src/utils/signaling.js

[stable21.1] Handle failed server responses more gracefully

---

src/components/AdminSettings/HostedSignalingServer.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue

Unify the spelling in applications.

l10n: Correct spelling

---

lib/Chat/Changelog/Manager.php
src/components/AdminSettings/TurnServers.vue
src/components/MessagesList/MessagesGroup/Message/Message.vue
templates/settings/admin-settings.php

Spelling unification in Nextcloud applications.

l10n: Unify spelling

---

CHANGELOG.md
appinfo/info.xml

[stable20] Changelog for 10.0.7

---

CHANGELOG.md
appinfo/info.xml

[stable20.1] Changelog for 10.1.4 and 10.0.7

---

CHANGELOG.md
appinfo/info.xml

[stable21] Changelog for 11.1.2, 10.1.4 and 10.0.7

---

composer.lock
lib/Manager.php
lib/Room.php
tests/php/RoomTest.php

Log conversation deletions in the audit.log

---

lib/AppInfo/Application.php
lib/Listener/GroupDeletedListener.php
lib/Settings/Admin/AdminSettings.php

Remove deleted groups from settings

---

src/App.vue

Ref https://github.com/nextcloud/spreed/pull/5315#issuecomment-805929174

Reset page title when not found

---

src/components/CallView/shared/LocalMediaControls.vue
src/components/TopBar/TopBar.vue

Keyboard shortcuts should be capital letters.

l10n: Change to capital letter

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

No actions on temporary messages

---

src/components/CallView/shared/LocalMediaControls.vue

Fix missing screenshare icon

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/store/fileUploadStore.js

Show an error when sharing fails

---

src/components/SettingsDialog/SettingsDialog.vue
src/store/fileUploadStore.js
src/store/soundsStore.js

1. As a user
2. Open the settings
3. Disable call sounds
4. Reload the page
5. Check settings again.

Fix loading the correct sound setting for users

---

lib/Collaboration/Collaborators/Listener.php
lib/Command/Room/TRoomCommand.php
lib/Controller/RoomController.php
lib/MatterbridgeManager.php
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/constants.js

Don't allow to manually interact with the bridge bot user

---

src/store/participantsStore.js

Not sure when this was introduced...

Fix "dipatch" typo

---

tests/integration/features/conversation-2/set-description.feature

Consequence from https://github.com/nextcloud/server/pull/26572

Make sure the user we are testing with exists

---

lib/Chat/ChatManager.php
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/store/conversationsStore.js

Only show public messages as last messages

---

src/store/conversationsStore.spec.js
src/store/talkHashStore.spec.js

Added fetchConversations tests.
Added maintenance mode and talk hash check in conversation tests.
Added talk hash store tests, also for maintenance mode check.

Added talk hash store and fetchConversations tests

---

README.md
appinfo/info.xml
src/components/CallView/CallView.vue
src/components/CallView/shared/LocalMediaControls.vue

Remove old firefox screenshare fallback and allow to see other screens

---

src/test-setup.js
src/views/RoomSelector.spec.js
src/views/RoomSelector.vue

Might not be the most important component to test but I wanted to practice writing Vue tests first

Added tests for RoomSelector

---

docs/chat.md
lib/Chat/Parser/SystemMessage.php

Fixing android atm, @Ivansss can you check iOS to show those as system messages properly?

Update list of system messages

---

docs/call.md
docs/chat.md
docs/conversation.md
docs/integration.md
docs/internal-signaling.md
docs/participant.md
docs/settings.md
docs/webinar.md
lib/Controller/RoomController.php

Add versions to API docs (sorry for cleaning up)

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add geo-location-sharing capability

---

src/components/MessagesList/MessagesList.spec.js
src/components/MessagesList/MessagesList.vue
src/constants.js
src/test-setup.js

~~See skipped tests as TODO list~~
I didn't cover the bits with the read marker and scroller gymnastics as they require a real viewport and I'm not sure if testing individual conditions here with a faked viewport make sense.
So let's move forward with what I have already here.

JS tests for MessagesList

---

jest.config.js
src/components/LeftSidebar/LeftSidebar.spec.js
src/components/LeftSidebar/LeftSidebar.vue

- ~~move service calls to the store~~ maybe another time...

JS tests for LeftSidebar

---

tests/integration/features/sharing/create.feature
tests/integration/features/sharing/update.feature

Ref https://github.com/nextcloud/server/pull/26679
Integration test are currently failing in master

Fix expected HTTP status code for OCS 403

---

lib/Controller/PageController.php
lib/TalkSession.php

Regenerate session id after entering password

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue

Credit where credit is due

---

src/components/ChatView.vue

Fix a regression introduced with #5596 

Fix chatview

---

docs/matterbridge.md

Spelling unification in Transifex.

l10n: Spelling unification

---

lib/Listener/GroupDeletedListener.php

2. Add a group to the conversation
3. Delete the group in the user management
The group is gone
The group is still listed as a participant

Remove groups as participants when deleted

---

.drone.yml

Migrates:
* Redis
* MySQL
* Postgres

Migrate more build images to GHCR

---

appinfo/info.xml

Update version to alpha 1

---

lib/Controller/RoomController.php
lib/Service/ParticipantService.php
psalm.xml

As I'm not sure we will finish #5670 in time, here is a quick fix to fix the "Undefined method `getType`" error on circle members as the circles app evolved and renamed the method.

Deduplicate and bug-fix circles integration

---

CHANGELOG.md
appinfo/info.xml

[stable20.1] Changelog for 10.1.5

---

CHANGELOG.md
appinfo/info.xml

[stable20] Changelog for 10.0.8

---

CHANGELOG.md
appinfo/info.xml

[stable19] Changelog for 9.0.10

---

src/assets/avatar.scss
src/assets/variables.scss
src/components/ConversationIcon.vue
src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue

FIx "Using / for division is deprecated"

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Before | After
---|---
Before | After
---|---

Inviting users appear offline

---

lib/MatterbridgeManager.php

Set permissions on Matterbridge config and log

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Don't show delete option for object shares

---

jest.config.js
package-lock.json
package.json
src/test-setup.js
webpack.common.js

Update nextcloud-vue to version 4.0.0

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add voice message capability

---

lib/Chat/SystemMessage/Listener.php

Only allow audio voice messages

---

src/services/conversationsService.js

copy-pasta regression from #5465

Listed conversation search doesn't work

---

src/components/Description/Description.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
src/views/NotFoundView.vue
src/views/SessionConflictView.vue
src/views/WelcomeView.vue

Fix coding style of translations

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

Display audio elements in the message list

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/UploadEditor.vue
src/services/filesSharingServices.js
src/store/fileUploadStore.js
src/store/messagesStore.js

Voice messages

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Add "Go to file" link

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Fix file link for guests

---

src/utils/webrtc/analyzers/AverageStatValue.spec.js

Note: the values were taken from the existing calculation, and I haven't verified whether the weighted average values are mathematically correct, but at first glance they looked fine.
@danxuliu would be good if you could review and tell me whether the chosen test values make sense for testing this

Add JS test for AverageStatValue

---

package-lock.json
package.json

Bump @nextcloud/vue to v4.0.1

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

Allow to open files with ctrl+click

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
src/components/NewMessageForm/NewMessageForm.vue

Fix newmessageform layout bug

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue

Fix advanced input border radius

---

docs/chat.md
lib/AppInfo/Application.php
lib/Chat/Parser/SystemMessage.php
lib/Chat/SystemMessage/Listener.php
lib/Events/AttendeesAddedEvent.php
lib/Events/AttendeesEvent.php
lib/Events/AttendeesRemovedEvent.php
lib/Service/ParticipantService.php
tests/integration/features/chat/reply.feature
tests/integration/features/chat/system-messages.feature
tests/php/Chat/Parser/SystemMessageTest.php

Add system messages for group attendees

---

docs/Talkbuchet.js

Initial Talkbuchet version

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue

fix audio player layout

---

lib/Controller/SignalingController.php
tests/php/Controller/SignalingControllerTest.php

Add debug logs to allow finding out what kind of requests are sent

---

src/components/RightSidebar/Participants/ParticipantsTab.vue

Only slow, not additional

---

src/views/Dashboard.vue

Stop polling rooms in the dashboard when the document is hidden

---

docs/TURN.md

@LukasReschke Could you check the three first commits through your security lense? Thanks!

Add TLS, setup details and Talk 12 changes to TURN server documentation

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Gets rid of the long list of messages in the console, one per chat
message...

Remove stray debug log in Message vue

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue

Correctly fallback in case of missing data

---

docs/conversation.md
docs/participant.md

currently it is in the `Removed` col

fix cell of publishingPermissions description

---

Makefile
appinfo/info.xml

Bump exclude list of packaing and bump version

---

src/components/CallView/shared/VideoBottomBar.vue

Fix disabling videos and selecting the screen of others

---

src/App.vue

Reverse of https://github.com/nextcloud/notifications/pull/1028
1. Reload page on talk and wait until it finished loading
2. Open a new tab so the page is in the background
3. Trigger a notification: `occ notification:generate`
4. Write a message in a channel where this user is a member of
`* * …`
`* …`

Fix asterix conflict with notifications

---

lib/Signaling/BackendNotifier.php

Also have sending requests marked as hpb

---

src/components/MessagesList/MessagesList.vue
src/components/NewMessageForm/NewMessageForm.vue

Also removed unused code about deletion after going through all calls of
"deleteMessage" to check for missed signature changes.
Fixes https://github.com/nextcloud/spreed/issues/5845

Fix removing temp message after retry

---

.drone.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml

Update stable22 target versions

---

src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/MessagesList/MessagesGroup/Message/Message.vue

Add icons for Mark as read and unread

---

src/components/LeftSidebar/LeftSidebar.spec.js
src/components/LeftSidebar/LeftSidebar.vue

Fix missing "Open conversations" caption

---

src/components/RightSidebar/Participants/ParticipantsTab.vue

Why does something like this not yield ESLint or fail the node build? -.-

Add missing import

---

lib/Controller/SignalingController.php
src/components/AdminSettings/Commands.vue
src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/AdminSettings/TurnServers.vue
src/utils/webrtc/webrtc.js

Fix https://github.com/nextcloud/spreed/issues/5935
Signed-off-by: szaimen <szaimen@e.mail.de>

fix links to documentation

---

lib/Chat/ChatManager.php
tests/php/Chat/ChatManagerTest.php

Use memcache to save the query for unread message count

---

src/components/AvatarWrapper/AvatarWrapper.spec.js
src/components/AvatarWrapper/AvatarWrapper.vue
src/components/AvatarWrapper/AvatarWrapperSmall.vue

Fix guest avatars

---

CHANGELOG.md

Fix changelog, version and date for 12.0.0

---

src/components/NewMessageForm/NewMessageForm.vue

Fix invisible emoji picker

---

appinfo/routes.php
docs/chat.md
lib/Chat/ChatManager.php
lib/Chat/Notifier.php
lib/Chat/Parser/SystemMessage.php
lib/Controller/ChatController.php
lib/Service/ParticipantService.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/delete.feature
tests/php/Chat/ChatManagerTest.php
tests/php/Chat/NotifierTest.php

🗑️ 💬 Clear chat history - Backend

---

css/app.scss

To make it appear on top of the settings modal.
Fixes https://github.com/nextcloud/spreed/issues/5980

Fix date picker z-index

---

lib/Room.php

Fix constant names

---

docs/chat.md
lib/Activity/Listener.php
lib/Chat/Parser/SystemMessage.php

Add "missed call" chat system message for one-to-one

---

lib/MatterbridgeManager.php
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue

Add skip TLS option for XMPP and Rocketchat

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

Fix displaying moderation options in one-to-ones

---

.github/workflows/phpunit.yml

[stable22.1] "Fix" CI with mariadb

---

.github/workflows/phpunit.yml

[stable21] "Fix" CI with mariadb

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 11.3.1, 10.1.6, 10.0.9

---

CHANGELOG.md

Fix version typo

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 10.1.6, 10.0.9

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 10.0.9

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add capability for clear history feature

---

lib/Controller/RoomController.php
lib/Service/ParticipantService.php
psalm.xml

Check circles membership when trying to add

---

lib/Chat/Changelog/Manager.php

Fixes https://github.com/nextcloud/spreed/issues/6043

Add "New in Talk" entries for version 12

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue
src/store/messagesStore.js
src/views/RoomSelector.vue

Fixes: #5287
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>

forward message

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue
src/store/messagesStore.js

Fix forwarding mentions

---

README.md

Revert "Fix TURN's url in README.md"

---

lib/Controller/SignalingController.php
src/components/AdminSettings/Commands.vue
src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/AdminSettings/TurnServers.vue
src/utils/webrtc/webrtc.js

Reverts nextcloud/spreed#5936
Let's hope they are not changing the links every week now :see_no_evil:

Revert "fix links to documentation"

---

src/components/NewMessageForm/NewMessageForm.vue

Remove div tags from safari messages

---

src/components/ConversationSettings/DangerZone.vue

Fixed typo.

---

CHANGELOG.md

Add changelog of 12.1.0

---

lib/Settings/Admin/AdminSettings.php
src/components/AdminSettings/HostedSignalingServer.vue

Rename language strings after string changes in https://github.com/nextcloud/server/pull/28423

Rename language strings to camelCase

---

src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue

Fix audio recordings in conversations with special chars and long names

---

lib/Chat/ChatManager.php

[stable22] Fix backport merge conflict

---

src/utils/signaling.js

Handle errors better

---

src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue

Add more buffer on file name length so "(1)" and other things work

---

src/components/LobbyScreen.vue

Fix #4921 
> ![Bildschirmfoto von 2021-08-27 14-45-24](https://user-images.githubusercontent.com/213943/131129378-bfbc1cfa-d0e6-4fcf-8ad8-9559b024e999.png)

Add description and relative lobby timer on lobby screen

---

src/components/CallView/shared/LocalMediaControls.vue

Fix video toggling on pasting

---

src/components/LeftSidebar/LeftSidebar.vue

| Before  | After  |
|---|---|
| <img width="354" alt="Screenshot 2021-09-02 at 13 25 51" src="https://user-images.githubusercontent.com/26852655/131836070-0c2bc3c8-4358-46f7-b526-896980bc2f27.png"> | <img width="364" alt="Screenshot 2021-09-02 at 13 25 24" src="https://user-images.githubusercontent.com/26852655/131836086-13ea4338-6f23-4662-a4b5-fbb81d8cc63f.png"> |

Fix navigation margins

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Fixes #5452
https://user-images.githubusercontent.com/26852655/131839574-ee90d2c9-a560-4462-81f6-924242ea4611.mov

Add create conversation button

---

lib/TalkSession.php

Fix renewing the session id after password use

---

CHANGELOG.md

[stable21] Add changelog for 10.0.10, 10.1.7 and 11.3.2

---

CHANGELOG.md

[stable20.1] Add changelog for 10.0.10 and 10.1.7

---

CHANGELOG.md

[stable20] Add changelog for 10.0.10

---

src/components/CallView/CallView.vue
src/components/TopBar/TopBar.vue

Make the topbar a topbar also in call view

---

package.json
src/components/LeftSidebar/ConversationsList/Conversation.spec.js
src/components/LeftSidebar/LeftSidebar.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
src/components/MessagesList/MessagesList.spec.js
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
src/services/conversationsService.spec.js
src/store/callViewStore.spec.js
src/store/messagesStore.spec.js
src/store/participantsStore.spec.js

Before:
```
npm run lint
> talk@13.0.0 lint
> eslint --ext .js,.vue src
/home/nickv/Nextcloud/23/server/appsbabies/spreed/src/components/LeftSidebar/ConversationsList/Conversation.spec.js
100:0  warning  Missing JSDoc @param "item" description                 jsdoc/require-param-description
100:0  warning  Missing JSDoc @param "item" type                        jsdoc/require-param-type
101:0  warning  Missing JSDoc @param "expectedText" description         jsdoc/require-param-description
101:0  warning  Missing JSDoc @param "expectedText" type                jsdoc/require-param-type
102:0  warning  Missing JSDoc @param "isSearchResult" description       jsdoc/require-param-description
102:0  warning  Missing JSDoc @param "isSearchResult" type              jsdoc/require-param-type
277:0 …
```

Fix remaining linting issues

---

src/components/CallView/shared/LocalMediaControls.vue

Fix leftover from switching "Hand" to "HandBackLeft"

---

src/components/CallView/CallView.vue

Fix missing background in callview placeholder

---

package.json

Bump nextcloud vue to v4.2.0

---

src/utils/webrtc/simplewebrtc/localmedia.js

[stable22.1] Fix null stream given to RTCPeerConnection.addTrack

---

src/utils/webrtc/simplewebrtc/localmedia.js

[stable22] Fix null stream given to RTCPeerConnection.addTrack

---

src/utils/webrtc/simplewebrtc/localmedia.js

[stable21] Fix null stream given to RTCPeerConnection.addTrack

---

src/utils/webrtc/simplewebrtc/localmedia.js

[stable20] Fix null stream given to RTCPeerConnection.addTrack

---

lib/Chat/Notifier.php
lib/Controller/CallController.php
lib/Controller/RoomController.php
lib/Model/Session.php
lib/Service/ParticipantService.php
tests/php/Chat/NotifierTest.php

[stable22.1]  Ignore sessions older than 30 seconds on notifications again

---

lib/BackgroundJob/RemoveEmptyRooms.php
tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
tests/psalm-baseline.xml

* Refactored the code to reduce the quantity of query's
* Fixed a bug when get `federationManager` property and property don't exists
The code do a lot of queries on database. Is good reduce the numbers of queries maintaining with a lower memory usage.

Implement remove file room of removed file

---

composer.json
composer.lock
psalm.xml
tests/psalm-baseline.xml

Signed-off-by: Vitor Mattos <vitor@php.rio>

Bump psalm version

---

lib/Listener/RestrictStartingCalls.php
tests/php/Listener/RestrictStartingCallsTest.php

Fix #6306 
Could add an integration test i guess

Always allow guests to start a call in video verification

---

lib/Controller/SignalingController.php
lib/Signaling/BackendNotifier.php
lib/Signaling/Manager.php
src/components/AdminSettings/SignalingServer.vue
src/utils/signaling.js

Show an error/warning when the HPB is incompatible

---

src/components/ConversationSettings/ConversationPermissionsSettings.vue
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/PermissionsEditor/PermissionsEditor.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js
src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
src/services/conversationsService.js
src/store/conversationsStore.js
src/store/conversationsStore.spec.js

Add ability to set default permissions for a conversation

---

docs/call-experience.md
docs/constants.md
src/components/CallView/shared/LocalMediaControls.vue
src/components/ConversationSettings/ConversationPermissionsSettings.vue

Change grammar of sentences

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Add ability to set default participant permissions

---

src/utils/media/pipeline/MediaDevicesSource.js

This fixes a regression introduced in #6321 (specifically, in b8fc1b28f32ac72cb8212b0a71e2c6a22403efcd)
Since MediaDevicesSource was introduced errors thrown when requesting the media streams were wrongly swallowed; those errors could be real errors, like the camera being used by another program, but they would happen too if both audio and video devices were explicitly disabled. As the errors were not propagated joining the call failed, because LocalMedia assumed that a stream was available but ended adding a null stream instead.
Note that this does not affect participants who have no permissions to publish, as a different code path is taken in that case.
Also note that this just restores the same behaviour used before the regression. The code to handle the errors and show the messages …

Fix joining call without media devices

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

* Have a user with default permissions
* Change to different permissions
Icon does not update away from "..."
Reloading shows the correct icon
Icon updates immediately
Reloading shows the correct icon

Always mount the slow so it is reactive to the state

---

css/icons.scss
src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalMediaControls.vue
src/components/CallView/shared/LocalVideo.vue
src/components/TopBar/CallButton.vue
src/components/TopBar/TopBar.vue

Call view improvements

---

src/components/TopBar/CallButton.vue

Only show "End meeting for all" when starting is restricted

---

.drone.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml

Update stable23 target versions

---

CHANGELOG.md

Add empty changelog for Talk 13 rc1

---

src/components/TopBar/CallButton.vue

Don't "End meeting" when onclick event is the all parameter :P

---

src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/Video.vue

Round videos

---

src/assets/variables.scss
src/components/CallView/shared/LocalMediaControls.vue
src/components/TopBar/TopBar.vue

fixes #6468 
https://user-images.githubusercontent.com/26852655/141328061-74ed4200-5c2b-4dff-ac99-f87be5e9e964.mov

Fix topbar buttons design and mobile layout

---

.github/workflows/phpunit.yml

Reduces CI time with dependabot JS updates

Only run unit tests when php is affected

---

src/components/DeviceChecker/DeviceChecker.vue

Makes content scrollable 
fixes #6388 
https://user-images.githubusercontent.com/26852655/141833061-72f90b9a-89f8-47cc-9153-872198b203b0.mov

Fix device checker on shorter screens

---

CHANGELOG.md
lib/Chat/Changelog/Manager.php

Add changelog for 13 and "What's new"

---

src/PublicShareAuthRequestPasswordButton.vue

Fix non-themed video-verification button

---

docs/system-requirements.md
src/components/AdminSettings/WebServerSetupChecks.vue
src/utils/media/pipeline/VirtualBackground.js
src/views/AdminSettings.vue

Fixes #6503 
**Reviewers:** this adds new strings! Also feel free to change them as needed, because I am not convinced by the texts I wrote :-P
Pending:

Add setup check for background blur

---

.github/workflows/phpunit.yml

[stable23] Only run unit tests when php is affected

---

lib/Activity/Setting.php

[stable22.1] Don't allow to get pushes for Talk activity

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

Use the same default for the device checker in the conversation settings

---

lib/Chat/ChatManager.php
src/services/messagesService.js
src/utils/temporaryMessage.js
tests/integration/features/chat/reference-id.feature

[stable21] accept SHA256 hash sums for reference id as documented

---

src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/Video.vue
src/components/CallView/shared/VideoBackground.vue

https://github.com/nextcloud/spreed/blob/0f69fef5c48e6d7f59af6f365aa17faa02e0c824/src/components/CallView/shared/VideoBackground.vue#L180

Add breathing room to stripe

---

src/utils/webrtc/VideoConstrainer.js

Mitigates #6527 (the real fix is in #6544)
`applyConstraints` is asynchronous, so calling it several times in a row tried to apply the constraints again while the constraints for the previous quality were still being applied. Due to this the constraints for the same quality could be applied several times. Now applying further constraints is deferred and collapsed in a single operation until the previous operation finished.
When several different qualities are deferred there is no need to apply the full sequence of deferred qualities; only the last quality is applied, as qualities do not depend on previous qualities and the last applied quality will always override any other quality previously applied.
Note that, in general, `applyConstraints(quality)` is not expected to be called again …

Do not apply constraints again until the previous operation finished

---

src/components/CallView/shared/LocalMediaControls.vue

Fix connection warning positioning

---

CHANGELOG.md

Add changelog for 13.0.0-rc.2

---

src/components/CallView/shared/LocalMediaControls.vue

Fix buttons in the topbar

---

lib/Activity/Listener.php

Regression from da20f4bbfeb369a823288a5af5dac3756f57ee6f

A missed call is only when there was only 1 user

---

src/components/CallView/CallView.vue
src/components/CallView/shared/Video.vue

https://user-images.githubusercontent.com/26852655/142632996-25a85d89-840e-4e4c-aaab-c18c0d495572.mov

Fix video container sizing (Again)

---

src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/TopBar/TopBar.vue
src/store/tokenStore.js

1. Create 2 conversations and add their name as description
2. While being in conversation A open the settings of conversation B via the actions menu in the conversation list
3. Settings of conversation A are opened and modified

Always open the conversation settings with the right data

---

src/utils/media/pipeline/TrackSourceMixin.js

This fixes a regression introduced in #6321
The parameter given to the `ended` event handler emitted by MediaStreamTracks is not the track itself, but an `Event` object. Due to this the handler parameter never matched with the known tracks, so ended tracks were not automatically removed.
The steps below use a PulseAudio virtual device with Firefox (Chromium does not seem to react to changes in PulseAudio modules, tracks are still marked as `live` and no `ended` event is emitted); in theory it can be tested too with real hardware devices that can be unplugged, but it depends on whether the browser properly emits `ended` events for the tracks in that case.
- Add a virtual device with PulseAudio (for example, with `pactl load-module module-echo-cancel`)
- Start a call with Firefox
- In the …

Fix automatic removal of streams when ended

---

lib/Command/Room/Create.php

Return room token

---

src/components/PermissionsEditor/PermissionsEditor.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js

Correctly populate the modal with default permissions

---

lib/Command/Room/Create.php
tests/integration/features/command/create.feature

* Increase test coverage on command `talk:room:create`.
* Remove unnecessary rows.

Implement tests on command create room

---

CHANGELOG.md

Changelog for 13.0.0

---

src/components/RightSidebar/Participants/ParticipantsTab.vue
src/store/participantsStore.js

Should stop the red wall of "Participant not found" we see on our instance at the moment.

Await adding the participant before updating the user status

---

lib/TInitialState.php

Reduce filecache hits for Talk/ folder creation

---

src/components/AdminSettings/WebServerSetupChecks.vue

l10n: Add dot to the end of the sentence

---

src/components/NewMessageForm/NewMessageForm.vue

fix #6642 
Kinda ugly I know but I didn't find another way to block the popover.

Disable emoji picker in locked conversations

---

appinfo/info.xml
lib/Command/User/Remove.php
lib/Listener/UserDeletedListener.php
lib/Manager.php
tests/integration/features/command/user-remove.feature
tests/psalm-baseline.xml

Add command to remove users from all rooms

---

composer.lock
lib/Activity/Listener.php
lib/AppInfo/Application.php
lib/Chat/Changelog/Listener.php
lib/Chat/Command/Listener.php
lib/Chat/Parser/Listener.php
lib/Chat/SystemMessage/Listener.php
lib/Collaboration/Resources/Listener.php
lib/Files/Listener.php
lib/Listener/RestrictStartingCalls.php
lib/Notification/Listener.php
lib/Share/Listener.php
lib/Share/RoomShareProvider.php
lib/Signaling/Listener.php
tests/php/Activity/SettingTest.php
tests/php/ConfigTest.php
tests/php/Controller/SignalingControllerTest.php
tests/php/Signaling/BackendNotifierTest.php
tests/psalm-baseline.xml

deprecated since 20.0.0 use \Psr\Container\ContainerInterface::get
https://github.com/nextcloud/server/blob/master/lib/public/IContainer.php#L76

Replace deprecated method

---

lib/BackgroundJob/RetryJob.php
lib/Chat/AutoComplete/Sorter.php
lib/Chat/Command/Executor.php
lib/Chat/Parser/UserMention.php
lib/Config.php
lib/Events/GetTurnServersEvent.php
lib/Federation/CloudFederationProviderTalk.php
lib/Migration/Version2001Date20170707115443.php
lib/Model/SessionMapper.php
lib/Settings/Admin/AdminSettings.php
tests/php/Federation/FederationTest.php

Before:
```
506 other issues found.
```
After:
```
488 other issues found.
```

Reduce psalm info

---

lib/Chat/ChatManager.php
lib/Chat/CommentsManager.php
lib/Chat/MessageParser.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/unread-messages.feature
tests/php/Chat/ChatManagerTest.php

Recognize voice messages, object and file shares as unread messages

---

tests/integration/composer.json
tests/integration/composer.lock

Changed:
https://github.com/Behat/Behat/pull/1372

Bump behat

---

CHANGELOG.md
appinfo/info.xml

Release 12.2.2

---

src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/SettingsDialog/SettingsDialog.vue

Make conversation settings scrollable

---

src/components/CallView/Grid/Grid.vue

- More opacity
- better positioning
- Shadow removed 
- Borders removed

Improve grid pagination buttons

---

webpack.js

Put back mapfiles. Seems like webpack updated and fixed the issue now

Restore default terser config and get mapfiles back

---

src/components/ConversationIcon.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue
src/components/TopBar/TopBar.vue
src/mixins/getParticipants.js

Show active in conversation status in one-on-one conversations

---

lib/Service/ParticipantService.php
tests/integration/features/conversation/join-listable.feature

See integration test for steps

Allow joining open conversations with passwords

---

lib/Room.php
lib/Signaling/Listener.php
src/utils/signaling.js
tests/php/Signaling/BackendNotifierTest.php

Fix signaling events roomlist

---

src/components/CallView/shared/LocalVideo.vue

l10n: Change to a capital letter

---

lib/Search/ConversationSearch.php
lib/Search/MessageSearch.php

Add attributes in search results

---

src/components/NewMessageForm/NewMessageForm.vue

4310: fixed emoticon displaying after selection

---

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue

6318: fixed mention complete with mouse clicking

---

src/components/ConversationSettings/DangerZone.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

5094: fixed special symbols for translation

---

src/components/ConversationIcon.vue
src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
stylelint.config.js

Fix some stylelint warnings

---

lib/Chat/CommentsManager.php

Remove temporary function after server merge

---

src/components/MessagesList/MessagesList.vue

#6607 
I think it is unused code.

6607: fixed scrolling issue to latest message

---

src/components/CallView/shared/EmptyCallView.vue

6154: fixed copy link issue for public call

---

package-lock.json
package.json
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/DeviceChecker/DeviceChecker.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
src/components/PermissionsEditor/PermissionsEditor.vue
src/components/UploadEditor.vue

Bump @nextcloud/vue to v5.0.0-beta.0

---

lib/BackgroundJob/CheckHostedSignalingServer.php
lib/Controller/HostedSignalingServerController.php
tests/php/BackgroundJob/CheckHostedSignalingServerTest.php

Don't force signaling mode when HPB trial is used

---

CHANGELOG.md
appinfo/info.xml

Backport of https://github.com/nextcloud/spreed/pull/6827

Changelog for 11.3.5

---

src/components/NewMessageForm/NewMessageForm.vue

Fix mentions inside brackets

---

lib/Events/EndCallForEveryoneEvent.php
lib/Service/ParticipantService.php
lib/Signaling/Listener.php

I thought this is already the case, but seems I only implemented the new event in the activity listener....

Only send 1 HPB request for the "end call for everyone" case

---

src/views/RoomSelector.vue

Fix eslint after #6763

---

.github/workflows/phpunit.yml

Change all phpunit versions and fix accidental revert

---

lib/Chat/CommentsManager.php

Remove custom method after server merge

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

5615: fixed message menu error in scrolling

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Add a capability for conversation permissions

---

lib/BackgroundJob/CheckHostedSignalingServer.php
lib/Manager.php
lib/Share/RoomShareProvider.php

Before:
```
500 other issues found.
```
After:
```
496 other issues found.
```

Reduce psalm issues

---

lib/Activity/Listener.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/system-messages.feature

Handle generate the end_call_for_all activity intentionally

---

lib/Chat/ChatManager.php
lib/Chat/Notifier.php
lib/Service/ParticipantService.php
tests/php/Chat/NotifierTest.php

Check type when verify if already notified

---

appinfo/routes/routesRoomController.php
appinfo/routes/routesSettingsController.php
appinfo/routes/routesSignalingController.php
appinfo/routes/routesTempAvatarController.php

Makes it a bit easier while debugging to jump from a known URL to the actual controller/code

Add see-links to route files

---

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue

Better participants sorting in sidebar tab

---

lib/Signaling/Messages.php

Use transactions for internal signaling

---

lib/Chat/ReactionManager.php
tests/integration/features/reaction/react.feature

Integration tests changed to cover this scenario

Return empty array when comment haven't reactions

---

src/components/TopBar/CallButton.vue

6927: updated button for call button

---

src/components/PermissionsEditor/PermissionsEditor.vue

6927: updated button for permissions editor

---

src/components/DeviceChecker/DeviceChecker.vue

6927: updated button for device checker

---

src/components/LeftSidebar/NewGroupConversation/Confirmation/Confirmation.vue

6927: updated button for confirmation

---

lib/AppInfo/Application.php
lib/Chat/ChatManager.php
lib/Chat/SystemMessage/Listener.php
lib/Events/AddParticipantsEvent.php
lib/Events/ChatEvent.php
lib/Room.php
lib/Service/ParticipantService.php
lib/Signaling/Listener.php

Combine multiple system messages updates

---

src/components/RightSidebar/LobbyStatus.vue

6927: updated button for lobby status

---

tests/integration/features/scaling/README.md
tests/integration/features/scaling/call.feature
tests/integration/features/scaling/chat.feature

Add an integration test for the scaling tests

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue

6927: updated button for forwarder

---

src/components/AdminSettings/AllowedGroups.vue

6927: updated button for allowed groups

---

src/FilesSidebarTabApp.vue

6927: updated button for files sidebar tab|

---

src/components/RightSidebar/RightSidebar.vue

6927: updated button for right sidebar

---

src/components/ConversationSettings/DangerZone.vue

6927: updated button for danger zone

---

CHANGELOG.md

Add changelog for 11.3.6, 12.2.4 and 13.0.4

---

tests/integration/features/bootstrap/FeatureContext.php

Goals: Reduce the quantity of endpoints and consequently the quantity of queries.
Before:
* GET to check if group exists. One problem: this method do a query to get all users of group (unnecessary).
* POST to create if not exists
After:
* POST to create group. If group already exists, the endpoint will return this on the status, getting the same result.
Reduces of queries on integration tests:

Reduce integration tests queries

---

CHANGELOG.md
appinfo/info.xml

- Fix several modals, dialogs and popovers in fullscreen mode [#6886](https://github.com/nextcloud/spreed/pull/6886)
- Fix mentions inside brackets [#6871](https://github.com/nextcloud/spreed/pull/6871)

Add changelog for 11.3.6

---

CHANGELOG.md
appinfo/info.xml

- Fix several modals, dialogs and popovers in fullscreen mode [#6884](https://github.com/nextcloud/spreed/pull/6884)
- Fix mentions inside brackets [#6870](https://github.com/nextcloud/spreed/pull/6870)
- Fix call flags update when track is disabled [#7015](https://github.com/nextcloud/spreed/pull/7015)

Add changelog for 11.3.6 and 12.2.4

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Fix position of primary action in action

---

src/components/Description/Description.vue

6927: updated button for description

---

.drone.jsonnet
.drone.yml

1. Download/install drone binary:
`curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx`
2. Adjust the matrix as wished
3. Run: `./drone  jsonnet --stream --format yml`
4. Commit the result
---
Ref https://docs.drone.io/pipeline/scripting/jsonnet/

Generate drone testing matrix from .drone.jsonnet file

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesList.vue
src/components/Quote.vue
src/services/messagesService.js
src/store/messagesStore.js
src/store/messagesStore.spec.js
src/store/reactionsStore.js
src/store/storeConfig.js

❤️ Message reactions front-end

---

src/components/UploadEditor.vue

6927: updated button for upload editor

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Fix broken avatars in conversation creation

---

appinfo/routes/routesChatController.php
docs/capabilities.md
docs/chat.md
lib/Capabilities.php
lib/Chat/ChatManager.php
lib/Controller/ChatController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/rich-object-share.feature
tests/php/CapabilitiesTest.php

Add an endpoint for a media tab

---

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue

Sort guests behind online logged in users

---

src/components/SetGuestUsername.vue

Upgrade buttons for setGuestUsername

---

src/components/TopBar/CallButton.vue

6995: updated button position in chat message

---

src/components/TopBar/CallButton.vue

7057: fixed success, error message style for call button

---

src/components/LeftSidebar/ConversationsList/Conversation.vue

Can not copy link of open conversation without joining

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.vue

Improve reaction summary: make yourself "You" and sort to the beginning

---

lib/Chat/ReactionManager.php
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/store/messagesStore.js

Allow to react to file and object shares

---

appinfo/info.xml
lib/Migration/Version14000Date20220328153054.php

Change display_name size

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

Fixes #7056 
https://user-images.githubusercontent.com/26852655/160154992-8122dadd-3008-4649-a5a5-ccc796bb5adb.mov

Keep reactions menu open

---

package-lock.json
package.json

Bump @nextcloud/vue to 5.3.0

---

src/components/MessagesList/MessagesList.vue

6927: updated button for message list

---

lib/Controller/ChatController.php
lib/Settings/Admin/AdminSettings.php
tests/php/Controller/SignalingControllerTest.php
tests/php/Federation/FederationTest.php

Necessary fixes to change the typing properties from annotations to real property typing.

fix property typing

---

src/components/MessagesList/MessagesList.vue
src/views/RoomSelector.spec.js
src/views/RoomSelector.vue

6927: updated button for room selector

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

* Remove reactions option
* Remove forward option

Fix message button bar for deleted messages

---

appinfo/info.xml

Bump version to 13.0.5

---

appinfo/info.xml

Bump version to 14.0.0-beta.1

---

lib/Chat/ChatManager.php
lib/Chat/Command/Executor.php
lib/Chat/MessageParser.php
lib/Chat/Parser/Listener.php
lib/Chat/Parser/ReactionParser.php
lib/Chat/Parser/SystemMessage.php
lib/Chat/ReactionManager.php
lib/Controller/ChatController.php
lib/Model/Message.php
lib/Notification/Notifier.php
tests/php/Chat/Parser/SystemMessageTest.php

Add constants for the verbs in the oc_comments table

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

7104: removing of heading auther name

---

lib/Share/RoomShareProvider.php
tests/integration/features/sharing-2/hooks.feature

Remove event to delete shares when user leave of room

---

src/services/conversationSharedItemsService.js
src/store/conversationSharedItemsStore.js

Fix store stuff

---

CHANGELOG.md

Changelog 24.0.0-rc.2

---

lib/Collaboration/Collaborators/Listener.php

Move collaboration listener annonymous function to static

---

lib/Chat/Changelog/Listener.php

Move changelog listener anonymous function to static

---

lib/Chat/Command/Listener.php

Move command listener anonymous function to static

---

src/components/Description/Description.vue

Fix https://github.com/nextcloud/spreed/pull/4546#discussion_r854066220

Fix CSS variable name

---

docs/conversation.md

Document that the lastMessage attribute is limited

---

appinfo/info.xml
lib/Migration/Version14000Date20220330141646.php
lib/Migration/Version14000Date20220330141647.php

Fix migration of attachment types for media

---

lib/Controller/ChatController.php

Only set header when the value changed and the status is not 304

---

src/components/RightSidebar/RightSidebar.vue

Open chat when in a call

---

lib/Status/Listener.php

Move status listeners anonymous functions to static

---

lib/Listener/RestrictStartingCalls.php
tests/php/Listener/RestrictStartingCallsTest.php

Move sharing listeners to static

---

lib/Signaling/Listener.php

Move signaling listeners anonymous functions to static

---

lib/Chat/SystemMessage/Listener.php
lib/Events/AlreadySharedEvent.php
lib/Share/RoomShareProvider.php
tests/psalm-baseline.xml

Move system message listeners to static methods

---

lib/Command/ActiveCalls.php

```sh
$ nc25 talk:active-calls --output json
{"calls":0,"participants":0}
$ nc25 talk:active-calls --output json_pretty
{
"calls": 1,
"participants": 1
}
$ nc25 talk:active-calls --output json
{"calls":1,"participants":1}
```

Add JSON option to active-calls command

---

lib/Controller/ChatController.php
lib/Controller/ReactionController.php

Allow to get Reactions summary and media tab in read-only rooms

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/ConversationSettings/Matterbridge/BridgePart.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue

Theming adjustments to latest master

---

src/components/SettingsDialog/SettingsDialog.vue

Use a normal link and open in new tab by default

---

tests/integration/features/reaction/react.feature

Adjust reactions order after server merge

---

lib/Chat/Changelog/Manager.php

Add changelog chat messages

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

Fix button bar position

---

src/components/CallView/shared/Video.spec.js
src/maps.js
src/utils/webrtc/RemoteVideoBlocker.spec.js

Fix eslint warnings

---

package-lock.json
package.json
src/components/RightSidebar/SharedItems/SharedItemsTab.vue

Update nextcloud-vue-collection to trigger less collection requests

---

src/views/RoomSelector.vue

Fix room selector

---

src/components/LeftSidebar/NewGroupConversation/PasswordProtect/PasswordProtect.vue

Set autocomplete="new-password" for conversation creation link password

---

src/views/RoomSelector.vue

Add border-box to fix the RoomSelector in maps and deck

---

src/components/ConversationSettings/SipSettings.vue

l10n: Fixed grammar

---

tests/integration/features/conversation/delete-user.feature
tests/integration/features/conversation/join-listable.feature

[stable21] Fix integration tests on stable21

---

lib/Controller/CallController.php
lib/Room.php
lib/Service/RoomService.php
tests/php/Service/RoomServiceTest.php

Move permissions logic to room service

---

src/components/ConversationSettings/SipSettings.vue

l10n: Change to uppercase

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

Prevent reactions for commands for now

---

lib/Controller/RoomController.php
lib/Room.php
lib/Service/RoomService.php

Move setSIPEnabled to room service

---

lib/Command/Room/TRoomCommand.php
lib/Controller/RoomController.php
lib/Manager.php
lib/Room.php
lib/Service/RoomService.php
tests/php/Signaling/BackendNotifierTest.php

Move setListable() to RoomService

---

lib/Controller/RoomController.php
lib/Room.php
lib/Service/RoomService.php
tests/php/Signaling/BackendNotifierTest.php

Move setLobby() to room service
