nextcloud/spreed

appinfo/database.xml
fixes https://github.com/nextcloud/spreed/issues/27
cc @juliushaertl
=> fix DB column types and widths

js/index.js, js/rooms.js
We shouldn't create rooms with an empty name. Also fixed an issue where a newly created room was not joined correctly.
cc @LukasReschke
=> Don't try to create rooms with an empty name.

appinfo/database.xml, appinfo/info.xml, js/rooms.js, lib/Controller/ApiController.php, templates/index.php
Having the same room name multiple times in the sidebar doesn't seem right, so each room can only be created once.
=> Prevent duplicate room names.

.drone.yml, .eslintignore, .eslintrc.yml, .stylelintrc, css/style.css, js/rooms.js, js/webrtc.js, js/xhrconnection.js, run-eslint.sh, run-stylelint.sh
Added some basic settings what should be checked and changed existing code to comply.
=> Check JavaScript / CSS files for errors/style using Drone CI (#42).

css/style.css, js/webrtc.js
@fancycode no need to change the default styles ;)
=> improve style of camera & microphone errors

js/app.js, js/models/room.js, js/rooms.js, js/views/roomlistview.js
Fixes https://github.com/nextcloud/spreed/issues/25
Note: due to our low contrast in the sidebar this is not really noticeable -> @jancborchardt fix it! 👷
=> visually show which room is selected/active

js/app.js, js/models/room.js, js/models/roomcollection.js, js/rooms.js, js/webrtc.js, templates/index.php
This fixes https://github.com/nextcloud/spreed/issues/62.
=> use fewer global vars and move init code to a central place

js/models/room.js, js/models/roomcollection.js
=> Sort rooms by last room usage.

appinfo/database.xml, appinfo/info.xml, lib/Controller/SignallingController.php
Postgres doesn't look the other way when you try to compare an int to a string and respectfully asks you to escape your identifiers.
Now I can finally have a call with myself
cc @LukasReschke
=> Make it work with postgresql

lib/Controller/ApiController.php
=> Fixed getPrivateChatRoomForUsers SQL query.

js/app.js, js/rooms.js, js/views/roomlistview.js
It implements what was proposed on #70 .
=> Adjusted more-actions menu and button to use guidelines.

appinfo/app.php
Should increase overall performance
=> Only load the routing when the navigation is displayed

js/app.js, js/rooms.js, js/webrtc.js, lib/Controller/ApiController.php
Set rooms active and join them when users select a name from the drop-down list.
If the room does not exists it will be created, set it as active and user will join that room.
If the room already exists it will be set as active and user will join that room.
=> Join rooms and set them active.

lib/Controller/ApiController.php, lib/Room.php
Start adding support for group calls.
=> Group calls

.eslintignore, .eslintrc.yml, js/app.js, js/rooms.js
/drone/src/github.com/nextcloud/spreed/js/rooms.js
* 19:6   error  'roomChannel' is defined but never used  no-unused-vars
/drone/src/github.com/nextcloud/spreed/js/app.js
* 36:8   error  'self' is defined but never used     no-unused-vars
* 62:9   error  Unnecessary semicolon                no-extra-semi
* 71:9   error  Unnecessary semicolon                no-extra-semi
* 98:29 error Expected '===' and instead saw '==' eqeqeq
@Ivansss
=> Fix JS linting errors

css/style.css, js/app.js, js/views/roomlistview.js, lib/Controller/ApiController.php
Add following actions to each room/group:
=> More actions

appinfo/app.php, appinfo/routes.php, js/app.js, js/rooms.js, js/views/roomlistview.js, lib/Controller/ApiController.php, lib/Manager.php, lib/Notification/Notifier.php, lib/Room.php, lib/Util.php, tests/php/Notification/NotifierTest.php
@LukasReschke 
Fix #4 
Fix #85
=> Room objects and a manager

js/webrtc.js
=> Reopen the signaling connection if closed

js/simplewebrtc.js
=> add more debug info

css/style.css
Please review @MorrisJobke @LukasReschke
=> hide app navigation on fullscreen as well

appinfo/info.xml
Requires https://github.com/nextcloud/server/pull/2139
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> Increase version to 11

js/simplewebrtc.js, js/webrtc.js, js/xhrconnection.js, lib/Controller/ApiController.php, lib/Controller/SignallingController.php
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> Make signalling great again

js/views/roomlistview.js, lib/Room.php
Implemented leave room action.
=> Add leave room functionality.

js/webrtc.js, js/xhrconnection.js
Event is not used so remove it to make eslint happy
=> Fix eslint

css/style.css, js/webrtc.js, templates/index.php
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> Move into same div

lib/Controller/ApiController.php
=> Publish the list of participants via the API

css/style.css, js/views/roomlistview.js, lib/Controller/ApiController.php
Add participants to a call functionality.
=> [WIP] Add person to a call

appinfo/routes.php, lib/Controller/ApiController.php, lib/Room.php
Fix #98 
@Ivansss returns `['type' => Room::GROUP_CALL]` when the type was changed
=> Stay in the same room and upgrade it instead

js/views/roomlistview.js, js/webrtc.js
cc @rullzer @nickvergessen @fancycode @LukasReschke 
I tested it and it still works.
=> Fix eslint errors

appinfo/info.xml
Fix #126 
@Ivansss @LukasReschke
=> Info.xml update

css/style.css, js/views/roomlistview.js
=> Fix unshare button on FF.

lib/Controller/ApiController.php, lib/Notification/Notifier.php
1. Create a one2one call with test1
2. Check that test1 has a notification ✅ 
3. Add user test2 to that call
4. Check that test2 has a notification ✅  
5. Create a group call
6. Check that all members of the group have a notification, except the user that started the room ✅  
Fix #128
=> Add notifications for all room additions

css/style.css, js/app.js, js/views/roomlistview.js, js/webrtc.js, templates/index.php
=> Add different messages on emptycontent depending on room type.

lib/Controller/SignallingController.php, lib/Util.php, tests/php/UtilTest.php
@MorrisJobke That fixes TURN for CoTurn.
cc @Ivansss
=> Fix turn server for coturn

COPYING, README.md
I think it is time for a proper README, I added some licensing stuff that contributors know that they should sign their commits and how to do it.
Feel free to add some nice screenshots and other stuff 😉
=> add a proper readme file and a license file

bower.json
=> Fix json syntax

css/style.css, js/views/roomlistview.js
Some details:
- make copy share link box work on mobile or narrow screens
- add min-width to own video in emptycontent or 1on1 call
- adjust opacity of unshare icon
- remove exclamation mark from emptycontent message
=> Design fixes

js/app.js, js/views/roomlistview.js
Clipboard button in room list items was not working correctly in some situations.
=> Fix clipboard in list items.

lib/Controller/ApiController.php, lib/Room.php
=> Sort rooms when joining or creating rooms.

appinfo/routes.php, js/rooms.js, lib/Controller/ApiController.php, lib/Manager.php
Leave room where a user or a guest is participating.
Fix #157
=> Leave endpoint

appinfo/app.php, lib/Room.php, lib/Util.php
Fix #169 
Also fixes:
* Rooms where the user was the only one where not deleted
* Public rooms where the user was the only local user where not deleted
cc @LukasReschke
=> Fix delete user listener

js/views/roomlistview.js
=> Change some room info texts

lib/Controller/ApiController.php, lib/Manager.php, lib/Room.php
Fix #106 
@schiessle @LukasReschke @Ivansss
=> Make sure that the session id is unique

js/app.js, js/simplewebrtc.js, js/webrtc.js
=> Remember audio and video settings

css/style.css, js/app.js, js/webrtc.js, templates/index-public.php
=> Public page improvements

js/app.js, js/views/roomlistview.js, templates/index-public.php
When you are waiting for the person who shared the call link to join, it would be nice to have a more personalized interface. 
I copied the snippet from the "files drop", but lack the knowledge to make the Javascript work...
Please help @MorrisJobke @Ivansss :)
=> personalize caller experience with avatar and name

Makefile
=> Make sure to only exclude the build/ in root

Makefile, appinfo/info.xml
@LukasReschke @ChristophWurst 
Follow up to #180
=> Update version fix script and upload 1.1.1

js/views/roomlistview.js
=> Fix HTML escaping issues

l10n/.tx/config
=> add transifex support

appinfo/app.php, js/app.js, js/views/roomlistview.js, js/webrtc.js, lib/Controller/PageController.php, templates/index.php, templates/settings-admin.php, templates/settings-personal.php
After doing the german translation, I found some mistakes.
cc @Ivansss @schiessle
=> Improve translations

templates/settings-admin.php, templates/settings-personal.php
I guess that is the correct capitalization, see https://github.com/nextcloud/spreed/pull/188/files#r92625064
Please review @nextcloud/spreed
=> capitalize UDP and TCP correctly

css/style.css, js/app.js, js/rooms.js, js/views/roomlistview.js, js/webrtc.js, templates/index-public.php, templates/index.php
=> Leave current room without reloading the page

js/webrtc.js
=> Show default non-user avatar for guests when disabling video

js/views/roomlistview.js
Sync rooms after adding a person to a room. The new participant is visible much faster.
=> Improve user experience when adding a person to a room

js/app.js, js/views/roomlistview.js
Fix #204 
@jancborchardt maybe you can also take a look at the other strings in `js/views/roomlistview.js` around the diff.
And maybe also with a german translation in mind.
=> Improve wording

tests/php/Notification/NotifierTest.php
=> Add group notification tests

lib/Controller/PageController.php
=> Remove unused dependencies

js/app.js
=> Open the "choose person" dropdown when user has no calls

js/app.js
=> Disable video when entering a call with more than 5 participants

.github/contributing.md, .github/issue_template.md, Makefile
=> Add github special files

appinfo/info.xml
=> Fix the app name in info.xml

appinfo/info.xml
=> Add resource links

css/style.css, templates/index-public.php
=> Fix broken header

appinfo/info.xml
=> Add info that HTTP/2.0 has known issues atm

css/style.css, js/views/roomlistview.js
=> Fix broken call menu

js/webrtc.js
Get correct video container after PR #233 changes.
=> Get correct video container after PR #233 changes

css/style.css
Fix other participants' avatar position when no camera.
=> Fix avatar container css

css/style.css, js/webrtc.js
Fix wrong positioned avatars name/audio indicators in calls.
The audio mute/unmute indicator is part of the videoContainer-dummy now.
=> Adjust avatars and name/audio indicators

js/views/roomlistview.js
=> Close rename input when popover is closed

css/style.css
=> Fix broken avatars in navigation bar

js/webrtc.js
This will make sessionId get updated in pullMessages() while loop.
https://github.com/nextcloud/spreed/blob/master/lib/Controller/SignallingController.php#L150
Before sessionId was not updated causing troubles to guests for joining rooms.
=> Restart event source when joining a room

templates/index-public.php
Now guests can also see the notifications.
=> Add notifications for guests

README.md, appinfo/info.xml
Signed-off-by: Marius Blüm <marius@lineone.io>
=> Adjust info.xml and README according to merging of screensharing

templates/index-public.php, templates/index.php
For https://github.com/nextcloud/server/pull/4013
=> Use own backbone.js

js/webrtc.js
=> Avoid printing raw error message in empty-content

appinfo/app.php, appinfo/info.xml
=> Register the navigation entry via info.xml

.eslintrc.yml, appinfo/database.xml, appinfo/info.xml, appinfo/routes.php, js/app.js, js/models/room.js, js/rooms.js, js/views/roomlistview.js, js/xhrconnection.js, lib/AppInfo/Application.php, lib/Controller/ApiController.php, lib/Controller/PageController.php, lib/Manager.php, lib/Migration/FillRoomTokens.php, lib/Notification/Notifier.php, lib/Room.php, templates/index-public.php, templates/index.php
=> Better room urls

js/app.js
=> Fix guest name initialization

lib/Controller/SignallingController.php
=> Stop the app framework from doing stuff

appinfo/info.xml
=> This branch only works with master

js/rooms.js
=> Update the URL when creating a room

css/style.css, js/app.js, js/webrtc.js, templates/index-public.php, templates/index.php
=> Select-Screensharing feature

js/app.js, js/simplewebrtc.js
=> Require Firefox version 52 or newer for sharing screen

js/webrtc.js
=> Promote back last speaker after screensharing is stopped

README.md
Please review @nextcloud/spreed
=> Add screensharing extension links to readme

templates/settings-admin.php
=> Clarify translation

js/app.js
=> Disable screensharing button while screensharing dialog is open.

lib/Controller/PageController.php
=> Use the new short url

lib/ContactsMenu/Providers/CallProvider.php
=> Change text capitalization

appinfo/info.xml
=> Change nc version dependency for stable 11 release

css/style.css, js/rooms.js, js/simplewebrtc.js, js/webrtc.js
=> Reconnection

js/app.js
=> Add better user feedback for screensharing support

CHANGELOG.md
=> Add changelog for 2.0.1

README.md
=> Update info about screensharing in README file.

appinfo/routes.php, js/app.js, js/models/roomcollection.js, js/rooms.js, js/views/roomlistview.js, js/xhrconnection.js, lib/Controller/ApiController.php
Required for the work on mobile clients
=> Move API to OCS

js/views/roomlistview.js
=> Use constants for room types.

js/app.js, js/calls.js, js/rooms.js, js/signaling.js, js/views/roomlistview.js, js/webrtc.js, templates/index-public.php, templates/index.php
This is a work in progress to get some early feedback. Will need more changes, especially with #349 and while testing and thinking about how the final API should look like.
The goal is to be able to replace the whole "what-rooms-exist", "who-is-which-room" and "who-is-in-a-call" functionality with a different implementation at some point.
=> Move room/call API to central location

js/signaling.js
=> Add only the users that need to be called by you to call description.

js/views/roomlistview.js
Looks like this was missed by #351.
=> Use updated API to leave the current call.

.drone.yml
=> Only check the syntax of the spreed app

js/app.js
=> Fix select2 selecting action.

js/views/roomlistview.js
=> Fix room renaming event

js/app.js, js/calls.js, templates/index.php
=> Fix select2 glitch

lib/Migration/FillRoomTokens.php, lib/Migration/Version2001002Date20170707115443.php, lib/Room.php
=> Fix app to work on oracle

lib/Manager.php, lib/Migration/FillRoomTokens.php
Moderators can remove users, but this will reduce the number of times they have to
=> Increase token calculation time

templates/settings-admin.php
=> Add translation and use fake-brand

css/style.css
=> Remove video filter from screensharing videos

js/webrtc.js
We need these events for [presentation resume support](https://github.com/nextcloud/spreed/pull/387/commits/19783330906ac4f6ea15ba651a16fe7369449a40#diff-f9a8399f04091748fa56c9d2b7ff747bR362)
=> Actually trigger users{Left,Joined} event

js/webrtc.js
=> Revert "Actually trigger users{Left,Joined} event"

lib/Migration/Version2000Date20170707093535.php, lib/Migration/Version2001Date20170707115443.php
=> Fix versioning of migrations

lib/Manager.php, lib/Room.php
=> Dispatch event when participant list changes

tests/integration/features/bootstrap/FeatureContext.php
As stated in [the documentation for `uasort`](http://php.net/manual/en/function.uasort.php), _if two members compare as equal, their relative order in the sorted array is undefined._ `uasort` is used in `RoomController` [to sort the participants of a room by their last ping](https://github.com/nextcloud/spreed/blob/8c1691cdc1f6573caf7241ca776e01777c7cbaf1/lib/Controller/RoomController.php#L144), so when two participants have the same last ping they could be returned in any order.
Although undefined, the order is probably consistent (so, whatever the order is, it is the same between different executions for the same data). When using PHP 7 the participants are sorted in the same order that currently appears in the integration test definitions. However, PHP 5.6 uses a different order, so …
=> Fix integration tests on PHP 5.6

docs/api-v1.md
=> Start writing docs for the mobile app devs

lib/Controller/RoomController.php, lib/Exceptions/ParticipantNotFoundException.php, lib/Room.php
Much cleaner than catching default exceptions...
=> Add a dedicated exception for participants

tests/integration/features/callapi/public.feature
Current master:
```
--- Fehlgeschlagene Szenarien:
/home/nickv/Nextcloud/13/server/appsbabies/spreed/tests/integration/features/callapi/public.feature:35
/home/nickv/Nextcloud/13/server/appsbabies/spreed/tests/integration/features/callapi/public.feature:58
75 Szenarien (73 bestanden, 2 fehlgeschlagen)
891 Schritte (859 bestanden, 2 fehlgeschlagen, 30 übersprungen)
```
Regression from #402
=> Fix integration tests

.drone.yml
=> No more CodeCov

lib/Controller/CallController.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Room.php
Taken from https://github.com/nextcloud/spreed/pull/366/commits/120edee4295616c059ede4ea18c084c1c594de7a and cleaned it up
=> Add events

js/signaling.js
=> Stop sending call description to simplewebrtc using internal signaling.

js/app.js
=> Only show the name hint once

lib/Controller/PageController.php
Neither template used this placeholder => unused => remove
=> Remove unused session id

lib/Migration/Version2001Date20170913104501.php, lib/Migration/Version2001Date20170929092606.php
=> Add license to migration files

docs/api-v1.md, lib/Room.php
=> Add events and docs for password change

appinfo/info.xml, lib/BackgroundJob/ExpireSignalingMessage.php, lib/Signaling/Messages.php
=> Expire signaling messages that are older than 5 minutes

lib/Room.php
=> Allow to remove the password

css/authenticate.css, js/authenticate.js, js/signaling.js, lib/Controller/CallController.php, lib/Controller/PageController.php, lib/Room.php, templates/authenticate.php
=> Don't use popup to ask for the password but the "blue screen"

js/webrtc.js
This fixes the sidebar overlapping the call and after call screen
=> Fix sidebar overlap in calls

lib/Controller/PageController.php
1. Open contacts menu
2. Click on talk icon
3. Wait until the browser finished loading 💀
=> Fix infinite redirect when following the link in a contacts menu

css/style.css, js/app.js, js/views/callinfoview.js, js/views/participantlistview.js, js/views/participantview.js, js/views/roomlistview.js, templates/index.php
=> Sidebar polishing

docs/api-v1.md
=> Add "Remove a guest" to the API docs

lib/Manager.php, lib/Room.php
=> Fix creating Participants

js/app.js
=> Fix app name in browser title

js/views/chatview.js
=> Submit chat messages with Enter and use Shift+Enter for new lines

js/app.js
Add some translation attributes to some strings.
=> Add translation attribute

lib/Activity/Hooks.php, lib/AppInfo/Application.php, lib/Controller/RoomController.php, lib/Notification/Hooks.php
Preparation for "Notifications on 'Join call'"
=> Activities and notifications via hooks

lib/AppInfo/Application.php, lib/Notification/Hooks.php, lib/Notification/Notifier.php, lib/Room.php, tests/php/Notification/NotifierTest.php
> ![bildschirmfoto von 2017-11-16 10-59-28](https://user-images.githubusercontent.com/213943/32885774-cbb9896a-cabe-11e7-994d-cea1dcde67fe.png)
=>  Create notifications for inactive users when a call happens 

js/calls.js, js/signaling.js
=> also leave the room when the user navigates away

css/comments.css
=> Force breaks on extremely long words in chat messages

js/views/roomlistview.js, js/webrtc.js
Add more t-attributes for the translation
=> Additional translation attributes

lib/Chat/Notifier.php, lib/Controller/PageController.php, lib/Notification/Hooks.php, lib/Notification/Notifier.php, tests/php/Chat/NotifierTest.php, tests/php/Notification/NotifierTest.php
=> Use a different object type for all the notifications

js/views/callinfoview.js
=> Do not fall back to the User list when there is no name

js/signaling.js
Otherwise your session times out while chatting and you can not
receive and post new messages after the 30 second timeout on your
session
Fix #495
=> Ping should work when you joined a room

lib/Manager.php
Applications can use the following (pseudo) code to override token generation:
```php
use OCA\Spreed\Manager;
use Symfony\Component\EventDispatcher\GenericEvent;
...
$dispatcher = $this->getContainer()->getServer()->getEventDispatcher();
$dispatcher->addListener(Manager::class . '::generateNewToken', function(GenericEvent $event) {
$token = 'my-random-token';  // <- this needs to be implemented
$event->setArgument('token', $token);
});
```
=> Allow other apps to override token generation.

appinfo/info.xml
=> Fix element order to match appstore expectations

css/comments.css
Based on nextcloud/server#7280
=> Fix working icon position when sending a chat message

js/signaling.js
A new 'pull messages' request was generated when changing to another room.
Now, it aborts the ongoing request (if there is any) before creating a new request.
=> Avoid multiple pull messages requests at the same time.

js/app.js, js/views/roomlistview.js, lib/Controller/RoomController.php
=> Adjust the room/call message while waiting for a call

lib/ContactsMenu/Providers/CallProvider.php
Update action from 'Video call' to 'Talk to {displayName}'
=> Update contacts menu call provider.

CHANGELOG.md, appinfo/info.xml
=> Update version and changelog for 2.9.0 beta release.

lib/ContactsMenu/Providers/CallProvider.php
=> First check the UID before using it

css/style.css, js/views/callinfoview.js
Proper padding, spacing and wording. This is ready to review to get it in fast, I am working on more enhancements.
Please review @nickvergessen @danxuliu @Ivansss
=> Design enhancements

js/views/callinfoview.js, js/views/editabletextlabel.js
=> Improve title for 1-to-1 calls.

css/comments.scss, css/style.scss, js/app.js, js/views/chatview.js
Before chat messages were shown from newest to oldest, with the new message input above the list of messages. Now they are shown from oldest to newest, with the new message input below the list of messages.
=> Reverse chat layout

css/comments.scss
Fixing first part of https://github.com/nextcloud/spreed/pull/558#issuecomment-356522526, please review @danxuliu
=> Reduce margin-bottom of comment input

js/app.js, js/views/sidebarview.js
=> Select chat tab when adding it to the sidebar

appinfo/info.xml
Signed-off-by: Marius Blüm <marius@lineone.io>
=> Fix markdown in info.xml

js/views/chatview.js
Fixes a stupid mistake introduced by some sleepy guy in #564 :-P
=> Fix variables already defined

lib/Capabilities.php, tests/php/CapabilitiesTest.php
=> Add capabilities

css/style.scss, js/app.js, js/views/participantlistview.js, js/views/tabview.js
=> Do not use relative paths to images on the server

docs/api-v1.md, js/app.js, js/calls.js, lib/Controller/RoomController.php, lib/Manager.php
=> Use search input as room name for "New public call"

css/style.scss
=> Fix screensharing position for guests.

.drone.yml, appinfo/info.xml, css/style.scss, docs/api-v1.md, js/app.js, js/calls.js, js/views/chatview.js, js/views/editabletextlabel.js, js/views/participantlistview.js, js/views/tabview.js, js/webrtc.js, lib/Controller/RoomController.php, lib/Manager.php, lib/Migration/Version2000Date20170707093535.php, lib/Migration/Version2000Date20171026140256.php, lib/Migration/Version2000Date20171026140257.php, lib/Migration/Version2001Date20170707115443.php, lib/Migration/Version2001Date20170913104501.php, lib/Migration/Version2001Date20170921145301.php, lib/Migration/Version2001Date20170929092606.php, lib/Migration/Version2001Date20171009132424.php, lib/Migration/Version2001Date20171026134605.php, lib/Migration/Version2001Date20171026141336.php, lib/Migration/Version2001Date20171031102049.php, lib/Migration/Version2001Date20180103144447.php, lib/Migration/Version2001Date20180103150836.php, tests/integration/spreedcheats/appinfo/info.xml
✅ Please review
❌ But do **NOT** merge
=> Make master work against Nextcloud 14

css/style.scss, js/webrtc.js
=> [stable13] Fix screensharing issues

js/signaling.js, js/webrtc.js, lib/AppInfo/Application.php, lib/Controller/SignalingController.php, lib/Signaling/BackendNotifier.php, tests/php/Controller/SignalingControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
Backport of #492 (I cherry-picked the commits from the other PR, please let me know if you are creating the backports differently).
=> [stable13] Split "room" from "call" when using the standalone signaling server.

docs/api-v1.md, lib/Capabilities.php, lib/Controller/RoomController.php, tests/php/CapabilitiesTest.php
Fix #628 
Should we add this into the UI too?
=> Allow to create group rooms without inviting anyone

js/app.js, js/calls.js
=> Add UI to create empty group rooms.

docs/api-v1.md, lib/Controller/ChatController.php
=> [stable13]  Add docs for chat and fix the links on github 

lib/Capabilities.php, lib/Controller/SignalingController.php, tests/php/CapabilitiesTest.php
=> [stable13] Allow to get signaling settings as guests

.tx/config, Makefile
See nextcloud/docker-ci#78 for details
Signed-off-by: Morris Jobke <hey@morrisjobke.de>
=>  Move transifex config for updated l10n script

docs/api-v1.md, js/app.js, js/calls.js, lib/Capabilities.php, lib/Controller/RoomController.php, tests/php/CapabilitiesTest.php
=> [stable13]  Allow to create group rooms without inviting anyone

js/app.js
=> Only return 20 suggestions, it's still more than enough

js/app.js
=> [stable13] Only return 20 suggestions, it's still more than enough

lib/AppInfo/Application.php, lib/Capabilities.php, tests/php/CapabilitiesTest.php
Failed hard there....
@Ivansss anything urgent we should backport? Because we should do a 3.0.2 with this fix soon...
=> Register capabilities and make them available for guests

lib/AppInfo/Application.php, lib/Capabilities.php, tests/php/CapabilitiesTest.php
=> [stable13] Register capabilities and make them available for guests

css/style.scss
=> [stable13] Set maximum video height when more than 2 people in call. 

lib/Controller/RoomController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/one-to-one.feature
=> Do not allow one2one calling yourself

.drone.yml, tests/integration/features/bootstrap/FeatureContext.php
=> [stable13] Run integration tests on MySQL and PostgreSQL too

lib/Migration/Version2001Date20171026134605.php
=> Fix update/install issue with old activity app

lib/Migration/Version2001Date20171026134605.php
=> [stable13] Fix update/install issue with old activity app

lib/ContactsMenu/Providers/CallProvider.php
=> [stable13] pass if no valid user object was returned

lib/Activity/Hooks.php
=> [stable 13] cast userids to string to avoid issues with  numerical IDs

js/admin/stun-server.js, js/admin/turn-server.js
=> [stable13] Strip protocol from stun and turn

appinfo/info.xml, lib/BackgroundJob/RemoveEmptyRooms.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Room.php
=> Also delete rooms when the leaving user is the only non-guest

appinfo/info.xml, lib/BackgroundJob/RemoveEmptyRooms.php, lib/BackgroundJob/ResetInCallFlags.php, lib/Manager.php
=> Reset in call flag when a user timed out

css/style.scss
=> Fix screensharing video position.

css/style.scss, js/app.js, js/connection.js, js/init.js, js/signaling.js, js/simplewebrtc.js, js/views/callinfoview.js, js/views/roomlistview.js, js/webrtc.js, templates/index-public.php, templates/index.php
This is a first step in that you can chat and join calls. The UI needs improvements though (e.g. own black video is shown). Also probably misses some cases where it still doesn't work correctly.
=> Support connecting without local media (#538).

js/views/chatview.js
1. No contacts menu for guests (can't use it anyway)
2. No contacts menu on guests (no data available)
3. Show "You" as author name above "new" box
4. Do not try to load avatars of guests (results in 404)
real guest names will follow in a separate PR
=>  Improve guest handling in comments

js/app.js
a - toggle audio on/off
v - toggle video on/off
p - switch to participants tab
c - switch to chat tab
Fix #308 
I guess we should add some info about this into the UI? @jancborchardt 
Mail app has this hidden in the settings dialog at the bottom of the sidebar. Not sure it's worth adding that?
=>  Add shortcuts for calling

js/app.js
=> Fix undefined this.connection when creating a room

css/style.scss, js/app.js, js/connection.js, js/init.js, js/signaling.js, js/simplewebrtc.js, js/views/callinfoview.js, js/views/roomlistview.js, js/webrtc.js, templates/index-public.php, templates/index.php
Backport of https://github.com/nextcloud/spreed/pull/619 & https://github.com/nextcloud/spreed/pull/709
=> [stable13]  Support connecting without local media & #709 (#538)

css/style.scss
=> [stable 13] Fix screensharing video position.

css/style.scss
=> [stable 13] Fix local video shadow.

lib/Signaling/BackendNotifier.php
Found while looking at the logs.
=> Provide the app to logger

lib/Controller/CallController.php
=> Remove unused dependency to logger

lib/Controller/PageController.php
=> Don't check for a password, when we didn't even find a room

js/connection.js, js/signaling.js, js/simplewebrtc.js, js/webrtc.js
Fix #708 
For me Firefox is "broken", sometimes the UI doesn't switch correctly from in call to not in call anymore, but this is also the case on master.
=> Disconnect media when leaving call

js/views/callinfoview.js
1. Join a room with Firefox
2. Join the call
3. Leave the call
loading for ever
all good
=> Fix join/leave with firefox aka. yay for autocomplete

js/app.js, js/views/chatview.js, js/views/tabview.js
=> Correctly focus editable content with firefox

appinfo/routes.php, docs/api-v1.md, js/app.js, lib/AppInfo/Application.php, lib/Controller/ChatController.php, lib/Controller/GuestController.php, lib/Controller/SignalingController.php, lib/GuestManager.php
=> Update participant list also when not in call

js/models/chatmessagecollection.js, js/models/participantcollection.js, js/models/roomcollection.js, js/views/chatview.js, js/views/sidebarview.js, js/views/tabview.js
=> Fix JS docs

appinfo/info.xml, lib/BackgroundJob/RemoveEmptyRooms.php, lib/BackgroundJob/ResetInCallFlags.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Room.php
=> [stable13] Also delete rooms when the leaving user is the only non-guest

lib/Signaling/BackendNotifier.php
=> [stable13] Provide the app to logger

lib/Controller/CallController.php
=> [stable13] Remove unused dependency to logger

js/models/chatmessagecollection.js, js/models/participantcollection.js, js/models/roomcollection.js, js/views/chatview.js, js/views/sidebarview.js, js/views/tabview.js
=> [stable13] Fix JS docs

js/views/callinfoview.js
=> [stable13] Fix join/leave with firefox aka. yay for autocomplete

lib/Controller/PageController.php
=> [stable13] Don't check for a password, when we didn't even find a room

js/connection.js, js/signaling.js, js/simplewebrtc.js, js/webrtc.js
=> [stable13] Disconnect media when leaving room

js/app.js, js/views/chatview.js, js/views/tabview.js
=> [stable13] Correctly focus editable content with firefox

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> [stable13] Spelling: by a user that has since been deleted

js/admin/stun-server.js
=> Add a notification when readding the default stun server

css/authenticate.css
=> Fixed authenticate script

css/style.scss
=> Do not cut popover on participant list

js/signaling.js, js/views/roomlistview.js
Fix #626 
The fixme from signaling.js should be done in a new PR
=> Remove chat when leaving active room

js/app.js, templates/index-public.php, templates/index.php
- (m)ute audio is now `m`
- (f)ullscreen added
- add shortcut hints into the ui strings
=> Change keyboard shortcuts

js/app.js, js/views/callinfoview.js, js/views/participantview.js, js/views/roomlistview.js, templates/index.php
=> Unify naming in the UI: rooms are conversations

js/models/roomcollection.js
Rooms were not correctly sorted after multi-session PR https://github.com/nextcloud/spreed/pull/748.
=> Sort correctly room collection.

js/app.js
=> Ignore shortcuts in chat

css/style.scss, js/app.js
Set dark style icon to screensharing button when local video is disabled.
=> Fix screensharing button style when no local video.

js/admin/stun-server.js
As per https://en.wikipedia.org/wiki/STUN
=> Spelling: stun server→ STUN server

tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/chat.feature
This looks so empty without anything written here... Yes, much better now :-)
=> Add acceptance tests for chat

css/style.scss, js/models/participant.js, js/views/participantlistview.js
> ![bildschirmfoto von 2018-04-17 10-51-16](https://user-images.githubusercontent.com/213943/38859096-8feb4ab8-422d-11e8-9a8e-c8feb0d8a508.png)
As discussed with ivan and frank
=> Add an icon for participants which are in the call

README.md, css/style.scss, js/app.js, js/simplewebrtc.js, js/webrtc.js
=> Allow to join without camera/mic

js/admin/stun-server.js
=> [stable13] Add a notification when readding the default stun server

css/authenticate.css
=> [stable13] Fixed authenticate script

css/style.scss
=> [stable13] Do not cut popover on participant list

js/signaling.js, js/views/roomlistview.js
=> [stable13] Remove chat when leaving active room

js/app.js, js/views/roomlistview.js, js/webrtc.js
=> [stable13] Streamline empty content message handling

css/style.scss, js/app.js, js/webrtc.js
=> [stable13] Allow screensharing even when alone

css/style.scss, js/app.js, js/connection.js, templates/index-public.php, templates/index.php
=> [stable13] Change keyboard shortcuts

css/style.scss
=> [stable13] Increase padding in chat view to leave enough space for side buttons.

appinfo/routes.php, js/signaling.js, lib/Manager.php
=> [stable13] Fix signaling endpoints

js/models/roomcollection.js
=> [stable13] Correct roomlist sorting

js/admin/stun-server.js, js/app.js, js/views/callinfoview.js, js/views/participantview.js, js/views/roomlistview.js, templates/index.php
=> [stable13] Unify naming in the UI: rooms are conversations 

css/style.scss, js/views/sidebarview.js
=> [stable13] Always show sidebar toggle

.drone.yml
I forgot this in #775 :facepalm:
=> Add acceptance tests for chat to Drone

css/patches.scss, css/style.scss, js/views/callinfoview.js, js/views/editabletextlabel.js
=> [stable13] Show password input field in a popover menu.

js/app.js, js/views/chatview.js
=> Remove useless logs

docs/api-v1.md, js/models/chatmessagecollection.js, lib/Chat/CommentsManager.php
=> Do not query the last comment info when there is none

lib/Controller/ChatController.php
=> Make sure the displayname is always a string

docs/api-v1.md, js/models/chatmessagecollection.js, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Controller/ChatController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/php/CapabilitiesTest.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
=> [stable13] Proper chat offset

css/comments.scss, css/style.scss, docs/api-v1.md, js/models/chatmessage.js, js/richobjectstringparser.js, js/views/chatview.js, lib/Chat/RichMessageHelper.php, lib/Controller/ChatController.php, templates/index-public.php, templates/index.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/group.feature, tests/integration/features/chat/one-to-one.feature, tests/integration/features/chat/password.feature, tests/integration/features/chat/public.feature, tests/integration/features/chat/rich-messages.feature, tests/php/Chat/RichMessageHelperTest.php, tests/php/Controller/ChatControllerTest.php
=> [stable13] Format mentions without avatars in the message list

css/comments.scss
=> [stable13] Make mentions more prominent

css/comments.scss, js/views/chatview.js
=> [stable13] Fix pointer cursor not shown on message authors

js/views/chatview.js
=> Only group up to 10 messages and only for up to 15 seconds

docs/api-v1.md, js/views/roomlistview.js, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
=> [stable13] Add unread message count to the room list

lib/Controller/ChatController.php
=> [stable13] Make sure the displayname is always a string

css/comments.scss
=> [stable13] Fix working icon position when sending a message

docs/api-v1.md, lib/Controller/RoomController.php
=> Return the room name on creation

css/style.scss, js/views/roomlistview.js
=> [stable13] Make the unread count more obvious

js/views/chatview.js
=> [stable13] Only group up to 10 messages and only for up to 15 seconds

css/comments.scss, js/views/chatview.js
=> [stable13] Fix pointer cursor shown for guests and in new message form

css/comments.scss, js/app.js, js/views/chatview.js
=> [stable13] Remove support for newest on top chat layout

docs/api-v1.md, lib/Controller/RoomController.php
=> [stable13] Return the room name on creation

css/comments.scss, js/views/chatview.js
=> [stable13] Disable contacts menu for mentions in the public view

js/views/chatview.js
=> Don't try to calculate the height of no comment

js/views/roomlistview.js
=> Do not show "remove from list" option for one2one conversations

js/app.js
Depending on timings it could happen that the guest name was set before the room token was known (resulting in `null` in the url) or before the user has joined the room (so setting the name got rejected).
=> Make sure user is in a room before the guest name is set.

js/app.js, js/signaling.js, lib/AppInfo/Application.php, lib/Signaling/BackendNotifier.php
=> [stable13] Various standalone signaling fixes.

js/webrtc.js
=> [stable13] Unpromote latest speaker if no users remain in call when removing video.

lib/AppInfo/Application.php, lib/Signaling/BackendNotifier.php
=> [stable13] Notify standalone signaling server about sessions to remove from room.

js/app.js
=> [stable13] Make sure user is in a room before the guest name is set.

js/views/chatview.js
=> [stable13] Fix check for guest's display name.

css/style.scss, js/views/roomlistview.js
=> [stable13] Limit unread message counter to "99+"

js/views/chatview.js
=> [stable13] Don't try to calculate the height of no comment

lib/Controller/SignalingController.php, lib/GuestManager.php
=> [stable13] Stop refreshing participant list when a guest is chatting

js/signaling.js
=> [stable13] Stop ping and signaling when the room was deleted

js/views/roomlistview.js
=> [stable13] Do not show "remove from list" option for one2one conversations

js/app.js, js/connection.js
=> [stable13] Fix UI when leaving current call

js/app.js, js/webrtc.js
=> Reset audio and video control panel.

js/connection.js, tests/acceptance/features/conversation.feature
=> Change deleted room message.

js/app.js, js/webrtc.js
=> [stable13] Reset audio and video control panel.

js/connection.js
=> [stable13] Make sure to always set the token on joining a room

CHANGELOG.md
=> Add changelog for 3.2.1

js/connection.js
=> [stable13] Change deleted room message.

css/style.scss
=> [stable13] Fix scrolling on participants list

appinfo/info.xml, lib/Settings/Personal.php, templates/settings/personal/clients.php
@nextcloud/talk 
cc @karlitschek
=> Add client links to personal settings

lib/Activity/Provider/Base.php, lib/Notification/Notifier.php, tests/php/Activity/Provider/BaseTest.php, tests/php/Notification/NotifierTest.php
=> [stable13] Calls are Conversations

lib/Chat/ChatManager.php
=> [stable13] Mark messages directly as read when waiting for new messages.

css/style.scss
=> [stable13] Fix tab header icons not shown

css/style.scss
=> [stable13] Fix appearance of participants menu button

lib/Notification/Hooks.php, lib/Room.php
=> [stable13] Send call notifications to every room participant that is not in the call

css/style.scss, js/webrtc.js
=> [stable13] Add toggle to show and hide video from other participants

js/views/participantview.js
=> [stable13] Fix add participant shown to normal participants

js/views/participantview.js
=> [stable13] Fix adding the same participant several times in a row

css/style.scss
=> [stable13] Fix menu position for rooms and participants

CHANGELOG.md
=> Add changelog for 3.2.2

CHANGELOG.md, appinfo/info.xml
=> [stable13] Add changelog for 3.2.2

README.md
Signed-off-by: Daniel Hansson <daniel@techandme.se>
Feeedback is welcome!
=> add info about install script

js/signaling.js, lib/AppInfo/Application.php, lib/Controller/SignalingController.php
Some more fixes found while testing.
=> More standalone signaling fixes

css/style.scss
- Use variables for borders
- Fix 'Add participant' input sticking to right side
Please review @nextcloud/talk
=> Fix input and grey tones

css/style.scss
Before:
After:
cc @nextcloud/talk
=> Adjust room name and edit flow layout

js/app.js
Quick wording change, check it out @nextcloud/talk
=> Name change is in Chat, not right sidebar

js/views/callinfoview.js
=> Remove dead code now that the guest name is no longer shown

lib/Controller/SignalingController.php
This is a follow-up to #910, thanks @nickvergessen for the suggestion!
=> Simplify check for "action" value in room request.

tests/acceptance/config/behat.yml
This pull request adjust the acceptance tests to the [changes in the server](https://github.com/nextcloud/server/pull/9967).
=> Set "wd_host" using the simulated "selenium.server" variable

js/views/callinfoview.js
Fix #976, please check @nickvergessen :)
=> Label button 'Start call' if none is in progress yet, fix #976

README.md
=> Add supported Browser list to README

js/models/participantcollection.js
=> Fix participants sorting

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> [stable13] Simplify notification wording

js/signaling.js, lib/AppInfo/Application.php, lib/Controller/SignalingController.php
=> [stable13] More standalone signaling fixes

css/style.scss
=> [stable13] Participants whitespace

js/views/callinfoview.js
=> [stable13] Remove guest name input from sidebar

css/style.scss
=> [stable13] Adjust room name and edit flow layout

js/webrtc.js
=> Name not shown for registered users without microphone nor camera

css/style.scss
=> [stable13] Fix position of local container children in older Firefox versions

css/style.scss, js/views/callinfoview.js
=> [stable13] Improve call controls layout to single row 

js/views/roomlistview.js
=> Remove participant tooltip from room list

lib/Room.php
=> Add the userId and user status to the disconnect evens

js/views/chatview.js
=> Allow single quote in date-separater for french translation

js/views/roomlistview.js
=> Refresh the room list when favoriting (similar to name and type changes)

lib/Activity/Hooks.php, lib/Activity/Provider/Base.php, lib/Activity/Provider/Call.php, lib/Activity/Provider/Invitation.php, lib/Activity/Setting.php
=> PHP7 for OCA\Spreed\Activity

.drone.yml, lib/Notification/Hooks.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php, tests/php/bootstrap.php
* Move to phpunit 6.5+ (same as server)
* Upgrade OCA\Spreed\Notifications to PHP7
=> PHP7 for OCA\Spreed\Notifications + PHPUnit 6.5

appinfo/routes.php, docs/api-v1.md, js/signaling.js, lib/Capabilities.php, lib/Controller/CallController.php, lib/Controller/ChatController.php, lib/Controller/SignalingController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/callapi/group.feature, tests/integration/features/callapi/one-to-one.feature, tests/integration/features/callapi/password.feature, tests/integration/features/callapi/public.feature, tests/integration/features/rename-room.feature, tests/php/CapabilitiesTest.php, tests/php/Controller/ChatControllerTest.php
=> Remove useless ping call and "ping" with the signaling fetch instead

appinfo/info.xml, docs/api-v1.md, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Migration/Version3003Date20180718133519.php, lib/Room.php, tests/php/Signaling/BackendNotifierTest.php
=> Add support for last message when fetching a room

css/style.scss, js/app.js, js/views/participantview.js
=> Move to public autocomplete endpoint

lib/Controller/PageController.php, lib/Notification/Hooks.php
My humble attempt at fixing the issue outlined in #1083.
Tested and works-for-me(tm).
Signed-off-by: Mario Danic <mario@lovelyhq.com>
=> Fixes #1083

lib/Controller/SignalingController.php
=> Make sure the list of signaling messages is a JSON array

css/settings-admin.scss, js/admin/signaling-server.js, js/admin/stun-server.js, js/admin/turn-server.js, templates/settings/admin/signaling-server.php
- Move shared secret description above the input field to avoid space between from https://github.com/nextcloud/server/issues/10094
- Increase add/delete button size and align them properly to the input fields
- Add aria-label values to the input fields
=> Settings UI enhancements

lib/Controller/ChatController.php, lib/Controller/RoomController.php
=> Fix the data type of the comment id

lib/Chat/CommentsManager.php
1. Start mentioning someone in a chat
2. See error in log file (if on debug/info)
=> Fix undefined index latest_comment

js/app.js
=> [stable13] Work around fetching participants before setting the room

lib/Chat/Notifier.php, lib/Notification/Notifier.php, tests/php/Chat/NotifierTest.php, tests/php/Notification/NotifierTest.php
=> Set the notification message to the full chat message with mentions

js/views/chatview.js
Increased seconds threshold to 30 for grouping messages.
=> Increase seconds threshold for grouping messages.

css/style.scss, js/views/roomlistview.js
Fix #1064 
@danxuliu can you add the star-icon to the conversation list? `{{#if isFavorite}}` can be used to identify such conversations.
=> Fixes for favorite conversations

lib/Chat/AutoComplete/Sorter.php, tests/php/Chat/AutoComplete/SorterTest.php
=> Fix "Object of class DateTime could not be converted to int"

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> Fix missing call-type in groups with no name

templates/settings/admin/signaling-server.php, templates/settings/admin/stun-server.php, templates/settings/admin/turn-server.php
**Before:**
**After:**
Signed-off-by: Marius Blüm <marius@lineone.io>
=> Change <h3> to <h2> in admin-settings

css/comments.scss
=> Make current-user mentions blue again

docs/api-v1.md, lib/Chat/SystemMessage/Listener.php, lib/Chat/SystemMessage/Parser.php
Add specific system message when a call is started.
Fix #1101
=> System message for call started

docs/api-v1.md
=> Update Signaling documentation.

lib/Chat/SystemMessage/Parser.php
=> Better system messages if you did something

lib/Share/RoomShareProvider.php
=> Fix "call to member function on null"

lib/Chat/SystemMessage/Parser.php
=> Shorten the system messages

appinfo/info.xml, css/style.scss, js/app.js, js/views/roomlistview.js
=> Use the search term as conversation name again

lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Chat/SystemMessage/Listener.php, lib/Chat/SystemMessage/Parser.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Notification/Notifier.php, tests/php/Chat/NotifierTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Notification/NotifierTest.php
=> Last message and notification for shares

lib/Activity/Hooks.php, lib/Manager.php, lib/Participant.php
Missed this on https://github.com/nextcloud/spreed/pull/1162
=> Fix the system message of call activities

.drone.yml
=> Test against stable14 for now

css/comments.scss, js/richobjectstringparser.js, js/views/chatview.js, tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/chat.feature
@danxuliu please have a look today or tomorrow, so we can get this in.
=> WIP: Show user avatar in mentions

css/comments.scss, js/richobjectstringparser.js, js/views/chatview.js, lib/Chat/SystemMessage/Parser.php
=> Show preview of shared files in system messages

js/views/chatview.js
As requested by @jancborchardt
=> Add tooltips to submit and share buttons

tests/integration/run-docker.sh
Now it is possible to use MySQL or PostgreSQL as the database when running the integration tests on Docker by calling _run-docker.sh_ with the `--database mysql` or `--database pgsql` option; if no database is specified SQLite is used by default (same as before).
The default MySQL database image is _mysql:5.7_, and the default PostgreSQL database image is _postgres:10_, [the same images currently used when running the tests on Drone](https://github.com/nextcloud/spreed/blob/d78027505249bfa983e9282536adfaa9aff729df/.drone.yml#L216-L233); a different one can be specified with the `--database-image IMAGE_NAME` option.
=> Make possible to run Docker integration tests on other databases

.drone.yml, appinfo/info.xml, tests/integration/spreedcheats/appinfo/info.xml
=> Update requirement to 15

.drone.yml, appinfo/info.xml, tests/integration/spreedcheats/appinfo/info.xml
=> Revert "Update requirement to 15"

lib/Controller/SignalingController.php
=> [stable13] Make sure the list of signaling messages is a JSON array

js/views/chatview.js
=> [stable13] Allow single quote in date-separater for french translation

lib/Config.php, tests/php/ConfigTest.php
=> [stable13] Fix TURN credential generation.

lib/Controller/ChatController.php
=> [stable13] Fix the data type of the comment id

lib/Chat/CommentsManager.php
=> [stable13] Fix undefined index latest_comment

tests/integration/run-docker.sh
=> [stable13] Make possible to run Docker integration tests on other databases

lib/Manager.php, lib/Participant.php
=> Make Participant class strict

lib/Manager.php
@fancycode you should have noticed this in #1226 ?
=> Correctly cast the in_call flag to integer

docs/api-v1.md, js/views/chatview.js, lib/Controller/ChatController.php, tests/php/Controller/ChatControllerTest.php
=> Handle exception on too long chat message gracefully

lib/Controller/PageController.php
=> Fix CSP also for guests

README.md
So people actually know how easy it is to set it up locally and contribute. :sun_with_face: 
Please review @nextcloud/talk :)
=> Add quick development setup introduction

lib/Notification/Notifier.php
=> Use short beautiful links for notifications

css/style.scss, js/views/participantlistview.js
=> [stable14] Fix interaction with participant menu

js/views/callinfoview.js
=> [stable14] Fix room name in CallInfoView for "share:password" rooms

css/comments.scss
=> [stable14] Fix vertical position of contacts menu on author row

js/richobjectstringparser.js, js/views/chatview.js
=> [stable14] Avatar on mentions from guests

js/views/chatview.js, lib/Chat/SystemMessage/Listener.php, lib/Share/RoomShareProvider.php
=> [stable14] Allow to reshare files again

lib/Controller/PublicShareAuthController.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> [stable14] Better notifications for password shares

lib/Activity/Hooks.php, lib/Chat/AutoComplete/SearchPlugin.php, lib/Controller/CallController.php, lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/HookListener.php, lib/PublicShareAuth/Listener.php, lib/Room.php, lib/Share/Helper/DeletedShareAPIController.php, lib/Share/Helper/ShareAPIController.php, lib/Share/RoomShareProvider.php, lib/Signaling/BackendNotifier.php, tests/php/Chat/AutoComplete/SearchPluginTest.php
It allows showing if user is online + what it's status is (inCall / audio / video) without needing two separate calls.
=> Add session & participantFlags to participant

css/comments.scss
=> Fix avatar position in mention box

.drone.yml, Makefile, check-handlebars-templates.sh, compile-handlebars-templates.sh, package.json
See nextcloud/server#11444
Now if the source templates were modified but their compiled versions were not updated the Drone job will fail.
=> Add Drone step to check Handlebars templates

js/app.js, js/views/chatview.js, js/views/sidebarview.js, js/views/tabview.js
=> [stable14] Fix the scroll position of the chat view in the sidebar

css/comments.scss
=> Fix avatar position in mention box.

.drone.yml
=> Test against 15 for now

js/app.js, js/simplewebrtc.js, templates/index-public.php, templates/index.php
For now uses the same icon for sharing screen and window, this should be changed.
Fix #671
=> Add support for sharing fullscreen on Firefox.

tests/acceptance/features/conversation.feature
Before: https://drone.nextcloud.com/nextcloud/spreed/1358/49
Regression from #1275
=> Fix acceptance tests regression from #1275

css/files.scss, js/filesplugin.js
=> Show "Chat" tab also when a file is not shared

js/filesplugin.js
Chromium seems to drop a stream when the element it is attached to is detached or reparented. The sidebar in the Files app is [open](https://github.com/nextcloud/server/blob/da0bdd1391d86046662e3e3cee046a48ffb58d22/core/js/apps.js#L31) and [closed](https://github.com/nextcloud/server/blob/da0bdd1391d86046662e3e3cee046a48ffb58d22/core/js/apps.js#L43) using a jQuery animation, which reparents the whole sidebar and then restores it at the end of the animation, so closing the sidebar breaks an ongoing call in Chromium. To prevent that, during a call the functions to open and close the sidebar are replaced with custom versions that do not use an animation.
At some point opening and closing the sidebar is likely to be fixed in server to be done using CSS transitions or something like that which …
=> Prevent breaking the call when the Files sidebar is closed in Chromium

tests/php/Chat/Parser/SystemMessageTest.php
=> Fix unit tests

js/simplewebrtc.js, js/views/mediacontrolsview.js
Changes to support screensharing in Chrome 71 and Iridium browser
=> Fix screensharing support in Chrome 71 and Iridium. 

lib/Chat/SystemMessage/Parser.php
Fixes extracted from #1168 
Fix #1349
=> [stable14] Errors with system messages

tests/integration/spreedcheats/appinfo/info.xml
=> Bump server version in the helper app for integration tests

css/style.scss
=> Fix favorite icon.

lib/Controller/SignalingController.php, tests/php/Controller/SignalingControllerTest.php
This could be used to return more information about a user to the signaling server which would not otherwise be able to retrieve it.
=> Add hook to allow returning additional data for clients joining a room.

.drone.yml
- php7.0 is no longer supported on master
- php7.3 is now supported on master
=> Update testing matrix

lib/Signaling/BackendNotifier.php
=> Make Signaling\BackendNotifier strict

CHANGELOG.md
=> Add changelog for 5.0.1

css/style.scss, js/app.js, js/views/participantview.js, js/views/roomlistview.js
> ![bildschirmfoto von 2019-01-23 13-47-19](https://user-images.githubusercontent.com/213943/51607872-3591cd00-1f16-11e9-8aa8-3cd47eeac33d.png)
> ![bildschirmfoto von 2019-01-23 13-49-31](https://user-images.githubusercontent.com/213943/51607873-3591cd00-1f16-11e9-8da4-f92d078746f4.png)
As per https://github.com/nextcloud/spreed/pull/1451#issuecomment-456552866
=> Always use white icons on the avatar-alike-placeholders

lib/Config.php
=> Make sure there is always a trailing slash

css/autocomplete.scss
> ![bildschirmfoto von 2019-01-24 21-06-23](https://user-images.githubusercontent.com/213943/51705457-f483e080-201b-11e9-83bb-5e1e6c81e6c2.png)
=> Fix autocomplete on darktheme

css/style.scss
Seperator of the options in the dropdown on a conversation of the conversation list is not visible anymore due to server css changes
=> Make the seperator visible

lib/Config.php
=> Also add default stun server on valid but empty value

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/bootstrap/FilesAppRoomSharingContext.php, tests/acceptance/features/bootstrap/ParticipantListContext.php, tests/acceptance/features/room-shares.feature
=> [stable14] Add acceptance tests for room shares 

lib/Activity/Hooks.php, lib/AppInfo/Application.php, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Chat/SystemMessage/Listener.php, lib/Controller/ChatController.php, lib/Manager.php, lib/Notification/Hooks.php, lib/Share/Helper/ShareAPIController.php, lib/Share/RoomShareProvider.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
=>  Use the datetime factory everywhere

lib/Controller/CallController.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/Manager.php, lib/Room.php, lib/Share/RoomShareProvider.php, lib/Signaling/Messages.php, tests/php/Controller/RoomControllerTest.php, tests/php/Controller/SignalingControllerTest.php, tests/php/PasswordVerificationTest.php
=> Use ITimeFactory instead of time()

js/merged-files.json, js/merged-guest.json, js/merged-share-auth.json, js/merged.json, js/views/templates.js, js/views/templates/videoview.handlebars, js/views/videoview.js, js/webrtc.js
Note that this pull request is a pure refactoring; there should be no behaviour changes (not even bug fixes).
=> Extract view for a participant in a call

css/video.scss
=> Own video is too big, setting it to 22%

js/merged-files.json, js/merged-guest.json, js/merged-share-auth.json, js/merged.json, js/views/screenview.js, js/views/templates.js, js/views/templates/screenview.handlebars, js/webrtc.js
Note that this pull request is a pure refactoring; there should be no behaviour changes (not even bug fixes).
=> Extract view for a shared screen

lib/Chat/MessageParser.php, lib/Chat/Parser/SystemMessage.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Notification/Notifier.php, tests/php/Chat/Parser/SystemMessageTest.php, tests/php/Chat/Parser/UserMentionTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Notification/NotifierTest.php
Currently unit tests on master are broken
=> Fix unit tests from #1453

lib/Chat/MessageParser.php
* As a guest set a name
* Post a message
* Expect that the message shows as "Your name"
Regression from #1453
=> Fix missing guest names in chat

js/app.js, js/embedded.js, js/filesplugin.js, js/merged-files.json, js/merged-guest.json, js/merged-share-auth.json, js/merged.json, js/publicshareauth.js, js/views/localvideoview.js, js/views/mediacontrolsview.js, js/views/templates.js, js/views/templates/localvideoview.handlebars, js/webrtc.js, templates/index-public.php, templates/index.php
Note that this pull request is a pure refactoring; there should be no behaviour changes (not even bug fixes).
=> Extract view for local participant

js/models/room.js
=> Fix ESlint on master

tests/integration/features/sharing/create.feature
Follow up to f3d46999f5ce28f1e77cba1bb069205ab1c186dd
=> Fix missing room names in integration tests

lib/Controller/ChatController.php
=> Remove '@ all' mention in one2one rooms.

js/simplewebrtc.js
=> Fix messages not sent due to datachannel not open.

js/simplewebrtc.js
=> Revert "Fix messages not sent due to datachannel not open."

.drone.yml
Faster and saves drone resources
=> Use DCO bot for signoff checks

tests/integration/features/chat/system-messages.feature, tests/integration/features/sharing/move.feature
=> Greeeeeeeeeeeeeen 💚

lib/Notification/Listener.php
=> Don't send a notification when inviting a user because he was mentioned

js/views/chatview.js
Post the message:
```
foo https://github.com/nextcloud/spreed
bar
```
=> Fix links before line breaks

css/style.scss, js/views/roomlistview.js
=> Add "copy link" option to the conversation list dropdown

css/style.scss
=> Add background color to unread messages counter.

.eslintignore, js/simplewebrtc/bundled.js, js/simplewebrtc/getscreenmedia.js, js/simplewebrtc/localmedia.js, js/simplewebrtc/peer.js, js/simplewebrtc/simplewebrtc.js, js/simplewebrtc/webrtc.js
=> Fix ESLint for custom SimpleWebRTC

.drone.yml
=> [stable15] Adjust drone config for stable15

appinfo/info.xml, lib/Command/Command/AddSamples.php, lib/Migration/RegisterSampleCommands.php, sample-commands/calc.sh, sample-commands/hackernews.php, sample-commands/wikipedia.php
> ![Bildschirmfoto von 2019-04-04 12-43-32](https://user-images.githubusercontent.com/213943/55550005-7a38a200-56d7-11e9-976c-9e3d17c6ef9a.png)
=> Add sample commands

css/publicshareauth.scss, js/views/templates.js, js/views/templates/chatview_add_comment.handlebars
=> [stable15] Fix misplaced chat view in public share auth page

appinfo/info.xml, tests/integration/spreedcheats/appinfo/info.xml
=> Update version on master

js/views/chatview.js
=> Dont focus chat on small screens

CHANGELOG.md
=> Fix changelog.md

lib/Controller/PageController.php
=> Correctly forward the password to the controller method

templates/authenticate.php
Follow up to #919 
How far back should this be backported? I leave up to you to call the backportbot ;-)
=> Rename "call" to "conversation" in authenticate page

.gitignore, package-lock.json
As stated in [NPM documentation](https://docs.npmjs.com/files/package-lock.json), the file is intended to be committed into source repositories; this ensures that everyone is using the same dependencies (as the semantic versioning of dependencies in _package.json_ does not).
=> Add "package-lock.json" to the versioned files

js/signaling.js
=> Also reload the conversation list every 30s with standalone signaling

CHANGELOG.md
=> Update changelog for 6.0.1

js/simplewebrtc/bundled.js, js/simplewebrtc/simplewebrtc.js, js/simplewebrtc/webrtc.js
We do not use the information of this message.
=> Do not send volume datachannel message.

package-lock.json, vue/package-lock.json
=> [stable16] Bump version also in "package-lock.json" files

CHANGELOG.md, appinfo/info.xml
=> Changelog 5.0.4

js/simplewebrtc/bundled.js
=> Bundle SimpleWebRTC with WebRTC adapter 7.2.4

lib/Config.php, tests/php/ConfigTest.php
=> Fix CSP with wss:// and ws:// signaling server

css/style.scss, js/views/roomlistview.js, js/views/templates.js, js/views/templates/roomlistview.handlebars
=> added a caption and improved the radio buttons descriptions

lib/Listener.php
=> Make the app compliant again

lib/Chat/AutoComplete/Sorter.php, lib/Controller/ChatController.php, tests/php/Chat/AutoComplete/SorterTest.php
Fix #1963 
1. Have a college "Daniel Mario" and "Mario Daniel"
2. Type `@dani` and then for `@mario`
=> Sort mentions with the searched start first

lib/Listener.php, lib/Manager.php, tests/integration/features/conversation/delete-user.feature
=> Retain one-to-one conversations when a user is deleted

docs/commands.md, docs/constants.md, lib/Command/Command/Add.php, lib/Command/Command/Update.php
=> More hints for absolute paths

.drone.yml, check-handlebars-templates.sh, check-simplewebrtc-bundle.sh, check-vuejs-builds.sh
=> Check if SimpleWebRTC and VueJS are build correctly

lib/Chat/Changelog/Manager.php
This PR will fix #1817. But I'm not sure what to do now to update the translation on transifex.
=> Use dashes as list bullets in changelog

lib/AppInfo/Application.php, lib/Listener/CSPListener.php
This makes sure we only set the CSP when it is actually needed
=> Use the CSP event

js/signaling.js
=> Don't retry signaling when the room was deleted or restricted

appinfo/info.xml, lib/Activity/Listener.php, lib/Manager.php, lib/Migration/Version7000Date20190717141457.php, lib/Participant.php, lib/Room.php
This makes sure users that only joined the chat are not listed in the call summary
Fix #1735
=> Add a new column to record who joined a call

lib/Notification/Notifier.php
... so we should just assum someone will be in the call soon.
Regression from #2003
=> Push notifications are rendered pre joining the call

lib/Controller/PageController.php, templates/authenticate.php, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/ConversationInfoContext.php, tests/acceptance/features/bootstrap/ConversationListContext.php, tests/acceptance/features/bootstrap/PublicConversationContext.php, tests/acceptance/features/conversation-public.feature
=> Show "Wrong password" info when the conversation password was wrong

check-vuejs-builds.sh
=> Check lock files for changes as well

js/views/chatview.js
=> Make links in brackets "(https://nextcloud.com/)" clickable

.drone.yml
I forgot to add this in #2018 :man_facepalming:
=> Add acceptance tests for public conversations to Drone

appinfo/info.xml, lib/Collaboration/Resources/ConversationProvider.php, lib/Migration/ClearResourceAccessCache.php, tests/php/Collaboration/Resources/ConversationProviderTest.php
=> Correctly check if a user has access to a conversation

lib/AppInfo/Application.php, lib/Listener/FeaturePolicyListener.php
For https://github.com/nextcloud/server/pull/16613
=> Allow mic+camera using feature policy

README.md
=> [stable16] Added a missing instruction to the development setup

js/app.js, js/views/callinfoview.js, js/views/chatview.js, js/views/roomlistview.js
See [the tooltip wrapper provided by server](https://github.com/nextcloud/server/blob/496a668bd4635802ee9759b1517a0a551a180218/core/src/Polyfill/tooltip.js#L27-L34).
=> Replace deprecated tooltip function calls with recommended functions

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> Use the guest name in notifications if it was provided

lib/Controller/ChatController.php
This falsly set the read marker on new messages although you
navigated away to a different chat already. So we removed this
and instead update the read marker before your next waiting.
So when you are still there, it will just have a wrong read
marker for the time until your next request starts, while it will
not update the value, when you actually left the chat already.
=> Set the automatic read marker before the waiting request, not afterwards

lib/Activity/Setting.php
=> Fix the activity description because there are no rooms

js/views/chatview.js
=> [stable16] Fix self avatar size for guests

.drone.yml
I forgot this in #1926 :man_facepalming:
=> Add acceptance tests for lobby to Drone

docs/TURN.md, mkdocs.yml
Based on the HowTo from Nextcloud forum: https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794
As of request: https://github.com/nextcloud/talk-android/pull/422#issuecomment-526711087
Signed-off-by: MichaIng <micha@dietpi.com>
=> Add coTURN setup documentation

docs/chat.md, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Controller/ChatController.php, tests/php/Chat/ChatManagerTest.php
=> Allow to include the last known message as well

docs/TURN.md
=> Remove DTLS sample

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> Use the new rich object type guest

lib/Chat/Command/Executor.php, lib/Chat/Command/ShellExecutor.php
=> Better command debugging

.drone.yml, package.json, vue/package.json
=> Update stable17 testing version

appinfo/info.xml, package.json, tests/integration/spreedcheats/appinfo/info.xml, vue/package.json
=> Update the master version and test app

package-lock.json, vue/package-lock.json
=> Update version in package-lock.json files

package-lock.json, vue/package-lock.json
=> Update stable17 version in package-lock.json files

css/style.scss
=> Prevent the chat from compressing too much on narrow screens

js/views/chatview.js
1. Create a user with only numbers as user id: `123456`
2. Add that user to a group room
3. Reload the chat and watch the console: ` TypeError: $element.data(...).substr is not a function` :boom: 
`substr` is undefined on integers and we assume all userIds are strings
=> Fix mentions with numeric users

js/views/chatview.js
Backport of #2161 
Patch is different because guest mention code is missing
=> [stable16] Fix mentions with numeric users

appinfo/routes.php, lib/Controller/FilesIntegrationController.php
=> Free FilesController

lib/Controller/ChatController.php
=> Allow to mention "all" by autocompleting the room name

lib/Chat/Changelog/Manager.php
=> Add changelog messages for Talk7

js/views/chatview.js, js/views/templates.js, js/views/templates/chatview_comment.handlebars, js/views/templates/richobjectstringparser_userlocal.handlebars, lib/Chat/Parser/SystemMessage.php, tests/php/Chat/Parser/SystemMessageTest.php
=> Unify the handling of the guest avatars

js/models/chatmessagecollection.js, js/signaling.js, js/views/chatview.js, js/views/virtuallist.js
=> [stable17] Load old chat messages on request

js/views/chatview.js, js/views/templates.js, js/views/templates/chatview_add_comment.handlebars
=> Fix check for guests on the comment field

css/video.scss
=> Show volume indicator in greyscale when speaking while muted

CHANGELOG.md
=> Final changelog for 7.0.0

lib/Controller/ChatController.php
1. Create a conversation "Private"
2. Invite user "Ivan"
3. Type `@iva`
* Ivan
* Private
* Private
* Ivan
=> Prepend the conversation mention only if it start with the match

.drone.yml, compile-handlebars-templates.sh
=> Use handlebar from node_modules

.drone.yml
=> Fix server branch used in public share acceptance tests in stable17

js/views/callinfoview.js
=> Add tooltip with start time format.

tests/drone-run-acceptance-tests.sh, tests/drone-run-integration-tests.sh, tests/drone-run-php-tests.sh
Found in https://drone.nextcloud.com/nextcloud/spreed/3550/9/4
=> Do not run tests when PHP files of other types of tests are modified

js/views/callinfoview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars
=> Add section title to share-link options.

js/views/callinfoview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars
=> [stable17] Add section title to share-link options.

css/publicshare.scss, css/style.scss, js/views/callinfoview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars, tests/acceptance/features/bootstrap/ConversationInfoContext.php, tests/acceptance/features/lobby.feature
=> Add lobby checkbox instead of radio buttons for enabling lobby.

css/publicshare.scss, css/style.scss, js/views/callinfoview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars, tests/acceptance/features/bootstrap/ConversationInfoContext.php, tests/acceptance/features/lobby.feature
=> [stable17] Add lobby checkbox instead of radio buttons for enabling lobby

src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue
Since this is the class which is only temporary here, I guess it needs to be changed in the vue-library as well?
=> Make app navigation dark-mode compatible

src/components/MessagesList/Message/Message.vue, src/components/MessagesList/MessageBody/MessageBody.vue, src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue, src/components/Navigation/Navigation.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/store/conversations.js, src/store/messages.js, src/views/ChatView.vue
=> Fix spaces and units

src/components/MessagesList/MessageBody/MessageBody.vue, src/components/Navigation/ConversationsList/ConversationsList.vue, src/components/Navigation/Navigation.vue
=> Fix navigation design issues.

src/components/ConversationIcon.vue, src/constants.js, src/services/conversationsService.js
=> Define all constants

src/components/ConversationIcon.vue, src/constants.js, src/services/conversationsService.js
=> Uppercase all constants

lib/AppInfo/Application.php, lib/Middleware/CanUseTalkMiddleware.php, lib/Middleware/InjectionMiddleware.php
=> Use DI for the middleware

appinfo/app.php
Follow up to https://github.com/nextcloud/server/pull/17509
=> Correctly setup the Application class

package-lock.json, package.json, src/components/Navigation/ConversationsList/Conversation.vue, src/components/Navigation/ConversationsList/ConversationsList.vue, src/components/Navigation/ConversationsList/ConversationsListItem.vue, src/main.js, src/services/conversationsService.js, src/store/conversations.js
=> Conversation list

src/views/AdminSettings/GeneralSettings.vue
=> Fix missing translation of the placeholder

lib/Controller/FilesIntegrationController.php, lib/Files/TemplateLoader.php, lib/PublicShare/TemplateLoader.php, lib/Settings/Admin/GeneralSettings.php, src/views/AdminSettings/GeneralSettings.vue
> ![Bildschirmfoto von 2019-10-08 11-49-00](https://user-images.githubusercontent.com/213943/66386020-caaff580-e9c1-11e9-9776-9c05907665ed.png)
Fix #2280
=> Allow to disable file rooms

src/components/Navigation/ConversationsList/ConversationsList.vue, src/store/conversations.js
=> Periodically refresh ConversationsList.

src/App.vue, src/components/Navigation/ConversationsList/ConversationsList.vue, src/services/EventBus.js
=> Add the conversation name to the page title

src/components/Navigation/ContactsList/ContactsList.vue
=> Use the display name for contacts

src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue
=> Fix searchbox style

src/components/Navigation/Caption/Caption.vue, src/components/Navigation/Navigation.vue
* now translated
* Adjusted design to https://github.com/nextcloud/spreed/issues/1010#issuecomment-527891578
> ![Bildschirmfoto von 2019-10-23 13-05-29](https://user-images.githubusercontent.com/213943/67386767-e1477680-f595-11e9-8736-618c8d62f6fc.png)
=> Fix captions in navigation

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/MessagesList/MessagesList.vue
* Do not group chat with system messages
* Do not show the author and avatar on system messages
=> Better system messages

src/App.vue
=> Do not fail hard when the conversation wasn't found (yet)

src/components/NewMessageForm/NewMessageForm.vue
=> Add missing default for systemMessage on new chat message

docs/conversation.md, lib/Controller/RoomController.php, src/components/Navigation/ContactsList/ContactsList.vue
=> Immediately add a new conversation to the list

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/Navigation/ConversationsList/ConversationsList.vue, src/components/Navigation/Navigation.vue
=> Filter the conversation list with the search term

css/icons.scss, src/components/ConversationIcon.vue, src/components/Navigation/ConversationsList/Conversation.vue
=> Add the favorite icon to the conversation list

src/components/Navigation/Navigation.vue
=> Remove dummy settings

src/components/Navigation/ConversationsList/Conversation.vue
=> Remove FIXME hack for favorites

package-lock.json, package.json, src/App.vue, src/components/ConversationIcon.vue, src/components/MessagesList/MessagesList.vue, src/components/Navigation/ConversationsList/Conversation.vue, src/services/conversationsService.js, src/services/messagesService.js, src/services/participantsService.js, src/views/AdminSettings/AllowedGroups.vue, src/views/RoomSelector.vue
=> Stop long polling requests when changing conversations.

src/components/Navigation/Navigation.vue
=> Remove unused class name and css rules

src/services/messagesService.js
=> Do not throw errors on 304s

src/components/Navigation/ContactsList/ContactsList.vue, src/components/Navigation/ConversationsList/Conversation.vue, src/components/Navigation/GroupsList/GroupsList.vue, src/components/Navigation/Navigation.vue, src/components/Navigation/NewConversation/NewPrivateConversation.vue, src/components/Navigation/NewConversation/NewPublicConversation.vue, src/services/conversationsService.js
=> Add the old-way to start an empty conversation

src/components/MessagesList/MessagesList.vue
=> End execution of 'getNewMessages' method if the api call is canceled

lib/Share/RoomShareProvider.php
=> Update share provider with the missing method

src/components/NewMessageForm/NewMessageForm.vue
=> Fix actorType for temporary message

src/components/MessagesList/MessagesGroup/Message/Message.vue
=> Simplify the parsing a bit

src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue
=> Add active state for conversations

src/components/MessagesList/MessagesGroup/Message/Message.vue
=> Fix messages increasing height when hovering them

src/App.vue, src/components/Sidebar/Sidebar.vue
=> Add the sidebar

src/components/Sidebar/Sidebar.vue
=> Make sidebar show and hide

src/assets/variables.scss
=> Increase message width

src/components/MessagesList/MessagesGroup/Message/Message.vue
=> Fix quoting with parsed messages

src/components/NewMessageForm/NewMessageForm.vue
=> Fix Input width and icons

src/assets/variables.scss, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue
=> Limit input height

src/assets/variables.scss, src/components/MessagesList/MessagesGroup/Message/Quote/Quote.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/Navigation/Navigation.vue, src/components/NewMessageForm/NewMessageForm.vue
=> Fix messages width

src/components/MessagesList/MessagesList.vue
=> Restart long polling on success

src/components/NewMessageForm/NewMessageForm.vue
=> Fix parsing of temporary message

src/assets/variables.scss, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue, src/components/Sidebar/Sidebar.vue, src/components/TopBar/TopBar.vue, src/store/sidebarStore.js, src/views/ChatView.vue
=> Create TopBar component

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
Currently the avatar has some issues in the bubble.
The issues are fixed in https://github.com/nextcloud/nextcloud-vue/pull/708 so will come automatically with `@nextcloud/vue:1.2.1`
=> Mention bubble for users

src/components/TopBar/TopBar.vue
=> Make topbar narrower and remove background

src/components/Sidebar/ParticipantsTab/Participant.vue
=> Fix participant's height

css/style.scss, src/components/ConversationIcon.vue, src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue, src/components/Navigation/ConversationsList/Conversation.vue
=> Fix AppContentListItem's layout

src/components/Sidebar/ParticipantsTab/Participant.vue
=> Fix actions position in the participants list

src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue, src/components/Sidebar/ParticipantsTab/Participant.vue
=> Fix margin on AppContentListItem

src/components/TopBar/TopBar.vue
=> Use right icon to toggle sidebar

src/components/Navigation/ConversationsList/Conversation.vue, src/components/Navigation/GroupsList/GroupsList.vue, src/components/Navigation/NewConversation/NewPrivateConversation.vue, src/components/Navigation/NewConversation/NewPublicConversation.vue
Ref https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md
=> Switch to new slot syntax

src/constants.js, src/services/conversationsService.js
=> Fix broken share types

src/components/Navigation/ConversationsList/Conversation.vue, src/components/Navigation/GroupsList/GroupsList.vue, src/components/Navigation/NewConversation/NewPrivateConversation.vue, src/components/Navigation/NewConversation/NewPublicConversation.vue
=> Fix broken conversation icons

src/components/Navigation/ConversationsList/ConversationsList.vue
=> Only hint the search when there where no results

src/components/Sidebar/ParticipantsList/Participant/Participant.vue
=> Dont error when participants are loaded faster then rooms

src/components/Navigation/ConversationsList/Conversation.vue
=> Fix slots of the AppNavigation

src/components/Navigation/ConversationsList/Conversation.vue
=> Only make the counter blue on mentions

css/icons.scss, src/components/Sidebar/Sidebar.vue, src/services/conversationsService.js, src/store/conversationsStore.js
* Toggle guests
* Toggle lobby
---
* Lobby timer with datetime picker
=> Conversation settings

src/App.vue
=> Add * to the header for unread messages

package-lock.json, package.json, src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/MessagesList/MessagesList.vue
> ![Bildschirmfoto von 2019-11-11 13-45-25](https://user-images.githubusercontent.com/213943/68588378-a4cab480-0489-11ea-9c40-3ed535690717.png)
=> Add a date separator between messages

tests/acceptance/features/app-files.feature
=> Fix old string in acceptance tests

src/components/NewMessageForm/NewMessageForm.vue
=> Remove unused buttons

src/components/MessagesList/MessagesList.vue
=> Fix the date-header of temporary messages

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesList.vue
=> Prevent lookForNewMessage call infinite loop

src/components/TopBar/CallButton.vue, src/components/TopBar/TopBar.vue
=> Add a CallButton with dummy methods

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/Quote.vue, src/store/messagesStore.js
=> Fix reply bugs

src/store/participantsStore.js
=> Don't throw false errors

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
=> Fix cursor behavior on AppContentListItem

package-lock.json, package.json
=> Update @nextcloud/vue to 1.2.2

src/components/LeftSidebar/NewConversation/SearchBox.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/main.js
=> Properly focus of input fields

.drone.yml, .github/workflows/lint.yml, .stylelintrc, package.json, run-stylelint.sh
=> Try linting via github actions

lib/Notification/Notifier.php
=> Fix language in notification

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
=> Remove moderator label in one-to-one conversations

css/icons.scss, src/App.vue, src/components/CallView/CallView.vue, src/components/CallView/MediaControls.vue, src/components/MessagesList/MessagesGroup/AuthorAvatar.vue, src/components/TopBar/TopBar.vue, src/router/router.js, src/views/ChatView.vue, src/views/MainView.vue
> ![Bildschirmfoto von 2019-12-06 16-20-34](https://user-images.githubusercontent.com/213943/70333826-81a2e300-1844-11ea-9023-a411f10d3f27.png)
=> Dummy call view

src/App.vue, src/FilesSidebarTabApp.vue, src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/components/RightSidebar/RightSidebar.vue, src/components/TopBar/CallButton.vue, src/store/index.js, src/store/tokenStore.js
=> Create token store

package-lock.json, package.json, src/App.vue
=> Prevent unload when in a call

.drone.yml, Makefile, check-simplewebrtc-bundle.sh
=> Remove code from bundling webrtc manually

css/icons.scss
=> Fix talk icons css

css/icons.scss
fixes a bug introduced in #2598
=> Fix sidebar icons color

src/utils/signaling.js
Fixes #2586 
Joining a room, if there is no connection yet to the external signaling server, is deferred until a connection is established. When that happens `joinRoom` is automatically called again by the signaling code.
However, the deferred `joinRoom` returned a Promise that was never resolved nor rejected. Due to this [the code originally calling `joinRoom`](https://github.com/nextcloud/spreed/blob/5368f4a98a95d3193c59a03513668cdcee7acbca/src/services/participantsService.js#L36-L38) can be left hanging indefinitely. This happened when joining the room as a guest, which caused the chat to never load.
Now the initial Promise is resolved when the deferred `joinRoom` is finally performed (unless `joinRoom` has been called again in the meantime with a different token, in which case it is …
=> Fix joining room before being connected to the external signaling server

src/assets/variables.scss, src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/Quote.vue
=> Align new message form input with messages

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
=> Fix participant actions position

docs/capabilities.md, docs/conversation.md, lib/Capabilities.php, lib/Controller/RoomController.php, src/components/LeftSidebar/CirclesList/CirclesList.vue, src/components/LeftSidebar/LeftSidebar.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/services/conversationsService.js, tests/php/CapabilitiesTest.php, tests/php/Controller/RoomControllerTest.php
1. Install circles: https://github.com/nextcloud/circles/pull/361
2. Create a circle
3. Try to create a conversation with a circle
4. Try to add a circle to an existing conversation
=> Add support for circles

src/components/LeftSidebar/GroupsList/GroupsList.vue
=> Remove unneeded debug

src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/utils/signaling.js
=> Update the participant list on signaling notification for a changed list

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
=> Fix guests (without a name) in the participant list

src/components/TopBar/CallButton.vue
=> Allow moderators to call while the lobby is active, not others

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Please review @ma12-co @nextcloud/designers-talk :) 
More helpful message, also pointing out the possibility of @-mention to people who don’t know about this.
=> Fix message placeholder, add @-mention hint

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
needs this to be merged and released: https://github.com/nextcloud/nextcloud-vue/pull/773 
| Before      | After |
| ----------- | ----------- |
| ![Screenshot_20191224_105832](https://user-images.githubusercontent.com/26852655/71407856-8802ce80-263c-11ea-938d-a6a0585ba5ea.png)  | ![Screenshot_20191224_105711](https://user-images.githubusercontent.com/26852655/71407875-93ee9080-263c-11ea-87ea-b49b668a92bc.png)|
=> Fix popover's position in participant component

src/components/RightSidebar/RightSidebar.vue
=> Remove favorite option for guests

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue
=> Prevent inherit attributes on messages v-bind

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
=> Translate placeholder for new messages

src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Make all text bold for unread conversations

src/components/ConversationIcon.vue, src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
=> Cleanup: fixes on the ConversationIcon design

src/components/Quote.vue
=> Fix missing "Guests" placeholder on quotes

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue
Ref https://github.com/nextcloud/spreed/pull/1018
=> Prevent empty messages and pasting HTML

package-lock.json, package.json, src/components/RightSidebar/RightSidebar.vue
Requires https://github.com/nextcloud/nextcloud-vue/pull/798
=> Correctly register the chat tab

css/icons.scss, package-lock.json, package.json, src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue, src/main.js, src/mainChatTab.js, src/mixins/vueAtReparenter.js, src/services/mentionsService.js
=> Add autocompletion for mentions

src/components/MessagesList/MessagesList.vue
=> Fix chat tab autoscroll to bottom

src/App.vue, src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/router/router.js, src/services/conversationsService.js, src/utils/signaling.js, src/views/NotFoundView.vue
=> Allow logged in users to join public conversations

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue, src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue, src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue, src/components/LeftSidebar/SearchBox/SearchBox.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
=> Spell checking

package-lock.json, package.json, src/components/MessagesList/MessagesList.vue, src/main.js, src/mainFilesSidebar.js
=> Remove vue-scroll library

src/components/MessagesList/MessagesList.vue, src/services/messagesService.js
=> Load older messages when scrolling to the top of the list

css/icons.scss, src/assets/variables.scss, src/components/ConversationsOptionsList.vue, src/components/LeftSidebar/LeftSidebar.vue, src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue, src/components/MessagesList/MessagesGroup/AuthorAvatar.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue
=> Participant list fixes

src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Show part of the name on the lest message

src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Fix primary bubble

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
=> Autofocus chat on reply

src/assets/avatar.scss, src/components/CallView/CallView.vue, src/components/CallView/LocalVideo.vue, src/components/CallView/Video.vue, src/components/MessagesList/MessagesGroup/AuthorAvatar.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
=> Don't override the avatar style to "fix" guests

css/icons.scss, css/merged-share-auth.scss, css/publicshareauth.scss, lib/PublicShareAuth/TemplateLoader.php, src/PublicShareAuthRequestPasswordButton.vue, src/PublicShareAuthSidebar.vue, src/mainPublicShareAuthSidebar.js, src/services/publicShareAuthService.js, webpack.common.js
Fix #2615
Requires nextcloud/server#18859
=> Video verification

src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Use defined ActionSeparator

src/assets/avatar.scss
=> Fix broken group option on conversation creation

src/FilesSidebarCallViewApp.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Fixes a regression introduced in 1bbc90d77b
[In Firefox accessing `cssRules` may throw a `SecurityError` if the style sheet was loaded from a different domain](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet#Notes). The style sheets loaded by Nextcloud all come from the same domain, but some Firefox extensions inject their own stylesheets from a different domain. Due to this, when the style sheet from the vue-at component was being looked for those style sheets from a different domain could be iterated over, which caused the exception to be thrown and stopped the load of Talk, which ended causing a blank page.
In a similar way this caused an exception to be thrown when starting a call in the Files app sidebar, which ended causing the call view to not be shown in the …
=> Fix "The operation is insecure" when accessing cssRules

src/components/MessagesList/MessagesGroup/Message/Message.vue
=> Move the author of the message above the quote box

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesList.vue, src/components/RightSidebar/RightSidebar.vue, src/services/participantsService.js, src/store/actorStore.js
=> Allow guests to set their user name

src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Primary unread counter in one-to-one conversation

src/components/LeftSidebar/ConversationsList/Conversation.vue, src/components/NewMessageForm/NewMessageForm.vue
=> Fix posted code to not be sent escaped

src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/LoadingHint.vue, src/services/conversationsService.js
* Don't clear the conversations list in case of an error
* Add dummy placeholders while loading
> ![Peek 2020-01-16 10-40](https://user-images.githubusercontent.com/213943/72513098-0245fd80-384d-11ea-9582-a38d5a488fa0.gif)
=> Improve loading of conversations

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue, src/components/LeftSidebar/ConversationsList/Conversation.vue
=> Fix counter layout bugs

src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue
=> Dummy placeholders for the participant list

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
=> Add hover/active/focus states to the appcontentlistitem component

src/components/MessagesList/LoadingMessage.vue, src/components/MessagesList/MessagesGroup/AuthorAvatar.vue, src/components/MessagesList/MessagesList.vue
> ![Bildschirmfoto von 2020-01-16 14-56-17](https://user-images.githubusercontent.com/213943/72530880-9bd2d680-3870-11ea-9643-a43b65327329.png)
=> Add placeholder dummy for messages

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
=> Fix appcontentlistitem hover active behavior

css/icons.scss, css/merged-public-share.scss, css/publicshare.scss, lib/PublicShare/TemplateLoader.php, src/PublicShareSidebar.vue, src/mainPublicShareSidebar.js, src/services/filesIntegrationServices.js, src/store/conversationsStore.js, webpack.common.js
Fixes #2616 
- Open the link to the share in a private window
The Talk sidebar should be shown in the public share page.
=> Add Talk sidebar to public share page

package-lock.json, package.json, src/components/RightSidebar/RightSidebar.vue, src/services/conversationsService.js
based on https://github.com/nextcloud/nextcloud-vue/pull/818
=> Add ability to rename conversations

src/components/RightSidebar/RightSidebar.vue
=> Hide password input when conversation is private

src/components/RightSidebar/RightSidebar.vue
=> Add copy link button

src/App.vue
=> Confirm leaving the call

src/components/CallView/CallView.vue, src/components/CallView/EmptyCallView.vue, src/components/LeftSidebar/ConversationsList/Conversation.vue, src/components/RightSidebar/RightSidebar.vue
Fixes #2650 
For now there are only messages about participants, no message about waiting for permissions or WebRTC not being supported.
=> Add content to empty call view

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/Quote.vue
=> Fix layout bugs

CHANGELOG.md, appinfo/info.xml
=> Update the changelog and the version

src/components/MessagesList/MessagesGroup/MessagesGroup.vue
Vertical alignment was a bit off
=> Fix avatar alignment in message list

lib/Chat/Changelog/Manager.php
=> Add most important features to changelog conversation

package-lock.json, package.json, src/components/CallView/LocalMediaControls.vue, src/main.js, src/mainFilesSidebar.js, src/mainPublicShareAuthSidebar.js, src/mainPublicShareSidebar.js
=> Add shortcuts for audio and video control again

src/components/MessagesList/MessagesList.vue
=> Increase tolerance for stickyness of the message list

src/components/NewMessageForm/NewMessageForm.vue
=> Remove the reply before waiting for the servers response

tests/php/Chat/Parser/SystemMessageTest.php
=> Fix systemmessage unit test

package-lock.json, package.json, src/components/CallView/LocalMediaControls.vue, src/main.js, src/mainFilesSidebar.js, src/mainPublicShareAuthSidebar.js, src/mainPublicShareSidebar.js
=> [stable18] Add shortcuts for audio and video control again

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
=> Allow selecting mention with the tab key

src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
Fix #2684
how to test: 
* navigate conversations with keyboard;
* open conversations in new tabs;
=> Wrap conversations in links

src/router/router.js
=> Set no rewrite for generateUrl, in case URL contains index.php despite configured rewrite

lib/Controller/PageController.php, lib/Controller/RoomController.php, src/components/LeftSidebar/LeftSidebar.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue
=> Check if circles is enabled

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
> Invalid prop: type check failed for prop "tabSelect". Expected Boolean, got String with value "true".
=> Fix type error

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
=> Add call indicator to participant list

css/icons.scss, src/components/LeftSidebar/ConversationsList/Conversation.vue
> ![Bildschirmfoto von 2020-01-24 10-16-45](https://user-images.githubusercontent.com/213943/73058517-1b296100-3e94-11ea-8560-7a2ec657c005.png)
Fix #2817
=> Require confirmation before deleting a conversation

docs/conversation.md
=> Fix typos in the docs

lib/GuestManager.php, src/components/CallView/LocalVideo.vue, src/components/CallView/Video.vue, src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/MessagesList/MessagesList.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/components/RightSidebar/RightSidebar.vue, src/services/messagesService.js, src/store/guestNameStore.js, src/store/index.js
=> Update guest names on chat messages and in the call

CHANGELOG.md
=> Add changelog for 8.0.1

lib/Controller/ChatController.php
Fix #2696 
Not sure why this was never done....
=> Mark own messages immediatelly read

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue
=> Pressing enter again re-sends last message

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
1. Create a conversation and invite a user
2. Start typing "@abcdefghi"
3. Check the number of requests to the mention endpoint (actually there are 2 per character you type)
With this PR sending the request is delayed by 400ms
=> Dont spam requests when typing a mention

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue, src/components/LeftSidebar/NewGroupConversation/PasswordProtect/PasswordProtect.vue, src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue, src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue, src/components/LeftSidebar/NewGroupConversation/SetConversationType/SetConversationType.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
=> Improve new group conversation feature
