css/style.css, js/webrtc.js
For now uses a custom message for HTTPS-required error in Chrome (#18) and
the "NotAllowedError" error if the used denied access to the devices. All
other errors show the message as reported by the browser.
=> Handle errors when accessing local media.

appinfo/info.xml, appinfo/routes.php, js/settings-admin.js, lib/Controller/AppSettingsController.php, lib/Controller/SignallingController.php, lib/Settings/Admin.php, lib/Util.php, templates/settings-admin.php
No longer hardcodes the STUN server to `stun.l.google.com:19302` (but still uses it by default if not changed).
Implements the `STUN` part of #2.
cc @LukasReschke
=> Make STUN server configurable through settings.

appinfo/database.xml, appinfo/info.xml, appinfo/routes.php, css/style.css, js/app.js, js/rooms.js, js/views/roomlistview.js, lib/Controller/ApiController.php, lib/Controller/PageController.php, lib/Exceptions/RoomNotFoundException.php, lib/Room.php, templates/index.php
This adds a person selector as well as avatars so that initiating a call will be more intuitive. This is WIP and doesn't already do everything.
The idea is basically that by default you just type a name and then once you have completed that join a channel for those two people. The other person will then get a notification (to be done later) and a screen will be shown to the current user indicating that you're waiting until the other user joins the channel.
To create a group chat the three dot menu is currently being implemented by @Ivansss on another branch.
Fixes https://github.com/nextcloud/spreed/issues/25
Fixes https://github.com/nextcloud/spreed/issues/11
cc @jancborchardt @ChristophWurst FYI
=> [WIP] Add person selector

.gitignore, appinfo/app.php, lib/Controller/ApiController.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php, tests/php/UtilTest.php
=> Notifications

js/webrtc.js
=> Lower quality to improve performance and lower cpu usage

lib/Util.php, tests/php/UtilTest.php
We should use our own server by default, not the external one from Google.
@Ivansss @nickvergessen
=> Change default STUN server (#86)

js/app.js
The webrtc lib already holds the video and audio state (of the local
video). We should make use of this to avoid getting out of sync for
whatever reason.
=> The webrtc library already keeps state lets use that

js/webrtc.js
What is the correct error handler? I suppose `on('WebrtcError'` is wrong ;)
Please help @fancycode @LukasReschke :)
=> show feedback when WebRTC is not supported by the browser

appinfo/app.php, appinfo/info.xml, appinfo/routes.php, js/settings-admin.js, js/settings-personal.js, lib/AppInfo/Application.php, lib/Controller/PersonalSettingsController.php, lib/Controller/SignallingController.php, lib/Util.php, personal.php, templates/settings-admin.php, templates/settings-personal.php, tests/php/PersonalSettingsControllerTest.php
This implements the second part of #2 to add TURN support. For now each user
has to have an account on the TURN server. Support for shared credentials will
be added in a separate PR.
@nickvergessen @LukasReschke
=> Add TURN server to personal settings.

css/settings-admin.css, js/settings-admin.js, lib/Controller/AppSettingsController.php, lib/Controller/SignallingController.php, lib/Settings/Admin.php, lib/Util.php, templates/settings-admin.php, tests/php/UtilTest.php
* then calculates the user credentials on the fly for 1 hour
* followup to #84 
cc @fancycode @LukasReschke
=> Add admin setting to specify a TURN server and a shared secret

lib/Room.php
This can return an empty result set in which case this spams the error log every second with a horrible amount of errors such as the following:
> Undefined index: num_participants at /media/psf/stable9/apps/spreed/lib/Room.php#195
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
cc @Ivansss @nickvergessen
=> Return 0 if element does not exists

css/style.css
One issue is that we have no app namespace on the body or HTML so we can not namespace the select2 styles, as the #select2-drop is in the body.
Will this mess with the other apps because CSS is loaded everywhere? If so, we need namespacing on the body. Like id="app-appname" as we currently do on `id="content"` with `class="app-appname"`.
cc @skjnldsv @nextcloud/javascript @nextcloud/designers
=> fix select2 styles for Spreed

js/app.js, js/views/roomlistview.js
We do not use the terms »Room« or »Public« anywhere. So »New shared call« is better than the long »Create a new public room«.
Please review @nextcloud/designers @LukasReschke @nickvergessen @MorrisJobke
=> fix wording to 'new shared call'

lib/Controller/ApiController.php, lib/Controller/PageController.php
1. As user1 invite user2 to a room
2. As user2 follow the link of the notification
3. The notification should be gone, but before this patch it was still visible until the next pull of the notifications after your first ping in the room.
This is now fixed.
@Ivansss the thing you found.
=> Kill notifications already when entering the room, not on first ping

css/style.css, templates/index-public.php
Displays the Nextcloud logo in a blue header bar when entering a public call page. When another caller joins, the bar goes from blue to transparent so more of the video area is visible.
=> show header on public shared room page

css/style.css
Before // After:
Note that before the controls were not centered below the avatar.
cc @nextcloud/designers
=> Fix alignment of call controls

js/webrtc.js
By now, it's only adding 'Guest' if 'nick' property of the peer is empty. 
Another option would be to create a random string/number and add it to guest when creating the peer.
https://github.com/nextcloud/spreed/blob/master/js/webrtc.js#L116
=> Add 'Guest' as name indicator for guests.

README.md, appinfo/info.xml
@Ivansss @jospoortvliet 
I just copied the stuff from the readme now for the app store description
=> Screensharing readme

css/style.css
Before & after:
Please review @nextcloud/designers
=> fix popover position

appinfo/info.xml
This breaks public calls as well as calls to users which are not in the group
Fix #201
=> Do not allow to restrict the app to a group

lib/Settings/Admin.php, tests/php/Settings/AdminTest.php
=> Add tests for Admin settings

.drone.yml, appinfo/database.xml, appinfo/info.xml, appinfo/routes.php, css/style.css, js/views/roomlistview.js, lib/Controller/ApiController.php, lib/Manager.php, lib/Migration/EmptyNameInsteadOfRandom.php, lib/Room.php, tests/php/Migration/EmptyNameInsteadOfRandomTest.php
I think our "Ivan Sein, Roel..." call name is pretty useless for everybody. Instead it would make sense, when it's called "Company Call".
This PR adds an endpoint which allows to set a name for calls. The participant list is still used, when there was no room name set manually.
@Ivansss can you help?
=> Allow to give calls a name

js/simplewebrtc.js
Fix #215 
@jancborchardt don't complain when the screensharing will not work in the future for you. This is because there is no Firefox version available and no-version does not match `version >= 33`.
=> Check whether this is firefox before trying to get the version

js/app.js, js/simplewebrtc.js, js/webrtc.js
=> Use app with no-camera devices

js/webrtc.js, js/xhrconnection.js
`simplewebrtc.js` is getting the type from the keys in https://github.com/nextcloud/spreed/blob/dc8d7ee32e001794150ae66fffa914a4682cf848/js/simplewebrtc.js#L14149 so the key should be `video`, not `type`.
@nickvergessen @LukasReschke
=> Fixed wrong peer type for regular (video) streams.

js/simplewebrtc.js
Update SimpleWebRTC to version 2.2.3 and apply our changes.
=> Update SimpleWebRTC to version 2.2.3

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
Doesn't work before 12.0 and where ever we backport the [definitions change](https://github.com/nextcloud/server/pull/3106).
So no need to rush it for 1.2
=> Add the call name to the notification when the call has a name

js/app.js, js/rooms.js, js/webrtc.js
Improve the feedback given to the user when Spreed app is launched.
Wait to microphone and camera permission before joining a room (it also shows a message to the user).
- Fix #214
=> Give user better feedback when launching Spreed

js/xhrconnection.js
Check against session ids to create roomDescription when joining a room.
Before guests were adding themselves in roomDescription.
=> Fix roomDescription for guests

css/style.css, js/app.js, js/simplewebrtc.js, js/webrtc.js, templates/index-public.php, templates/index.php
This PR adds support for screensharing (#31).
Currently more a tech demo :see_no_evil: various parts still need implementation:
cc @jancborchardt for ui, @nickvergessen @LukasReschke, @Ivansss for general review
=> [WIP] Add screensharing support.

js/app.js
Implements what discussed in https://github.com/nextcloud/spreed/pull/227#issuecomment-279396890 regarding notifications when no screensharing extension installed.
=> Add screensharing extension links to notifications

js/webrtc.js, lib/Controller/SignallingController.php
This fixes what wanted to be fixed in #255 
$sessionId = $this->session->get('spreed-session');
https://github.com/nextcloud/spreed/blob/master/lib/Controller/SignallingController.php#L150
sessionId is never updated because it is inside a while loop that never ends.
This makes guests sometimes never able to join a call (If they didn't get the spreed-session before EventSource was started). Now, if this happens, the EventSource will be restarted until it get the current spreed-session.
PR #255 has been reverted because it was causing loses of some signaling messages when the EventSource was restarted.
=> Restart EventSource if no spreed session

css/style.css
This fixes the background switch issue we encountered today in the company call. It should stay black the whole time but went to white above 10 participants:
Please review @nextcloud/spreed
=> fix background going white above 10 participants

js/simplewebrtc.js
Sometimes 'stunservers' event is received after 'turnservers' event.
This causes that only the STUN server is set as ICE servers (TURN servers are overwritten).
=> Fix ICE servers configuration

lib/Controller/ApiController.php, lib/Manager.php, lib/Room.php
=> Allow logged in users to join public rooms again

appinfo/info.xml, lib/ContactsMenu/Providers/CallProvider.php, lib/Controller/PageController.php
=> Add contacts menu integration

js/views/roomlistview.js
Before, room tooltip was not updated when the room had a room name set.
=> Update tooltip when room participants change

templates/settings-admin.php
Adding more hints to settings, ref https://github.com/nextcloud/server/pull/4478 https://github.com/nextcloud/server/pull/4540
Please review @karlitschek @nextcloud/spreed
=> Add hint to settings

js/simplewebrtc.js
=> Fix isVideoEnabled function

js/app.js, js/webrtc.js
=> Add avatars for guests

css/style.css
Guest name color in light color themings is black.
When the guest is in a call the top bar becomes transparent and the name is not visible anymore.
Now (in-call):
=> Fix guest name color in light color themings

templates/index-public.php
We just had this issue in a call ;) Please review @rullzer @juliushaertl
=> Open header link of public call page in new tab to not throw people out of call

js/app.js, js/simplewebrtc.js, js/webrtc.js
=> Fix datachannels

appinfo/info.xml, appinfo/routes.php, js/rooms.js, js/signaling.js, js/views/roomlistview.js, lib/ContactsMenu/Providers/CallProvider.php, lib/Controller/CallController.php, lib/Controller/PageController.php, lib/Controller/RoomController.php, lib/Notification/Notifier.php
`/api`
- `/{apiVersion}`
- `/call`
- `/{token}` - `GET` connected peers
- `/{token}` - `POST` to join a call
- `/{token}` - `PUT` your "I'm still here"
- `/{token}` - `DELETE` when you leave the app or close the browser
- `/room` - `POST` create a room
- `/room` - `GET` all rooms
- `/{token}` - `GET` room publicly
- `/{token}` - `DELETE` delete a room #353 
- `/{token}` - `PUT` rename a call
- `/public` - `POST` make a call public
- `/public` - `DELETE` make a call private
- `/moderators` - `POST` promote a participant to be a moderator #353 
- `/moderators` - `DELETE` demote a moderator #353 
- `/participants` - `POST` add a participant
- `/participants` - `DELETE` remove a participant #353 
- `/self` - `DELETE` remove yourself from a room
=> Split API controller and clarify method names

appinfo/info.xml, appinfo/routes.php, css/style.css, js/views/roomlistview.js, lib/Controller/RoomController.php, lib/Manager.php, lib/Migration/Version2001002Date20170707115443.php, lib/Participant.php, lib/Room.php
Fix #297 
@jancborchardt we need a UI to allow to promote users to moderators, demote them again and in the future also to remove users from a room. Do you have a good idea for a UI here? I think it would be nice if this was possible while being in a call, but it should also work when there is no call atm (to prepare it) and when the user is not part of the current call, which I think makes this a bit tricky. But maybe you have an idea?
When there is a call for participants I would suggest a dropdown on the name of the user, or a little triangle behind it.
@Ivansss what do you think, how should we set the owner on update for group rooms etc. I mean for 1on1 rooms we just set both as owners, when there is only one user in a room it's also easy. But what do we do with public/group rooms …
=> Participant types

lib/Room.php
Otherwise `getName` always returns the initial name.
=> Update "name" member on rename so "getName" returns updated name.

css/style.css
Otherwise it looks like this where the other person is overlapped by your own video:
So it’s now limited to 30% height.
=> Limit size of own video on mobile so other participant is still visible

.gitignore
This file is installed by npm as of version 5 when running
"npm install"
=> gitignore: Ignore 'package-lock.json'

.drone.yml
The _php7.1_ and _php7.1-integration_ tests seem to be running in Drone, but in fact they are not; although there are no errors, if you take a closer look to their output you can see that the tests themselves are not run either (see, for example, [_php7.1_ log for pull request 100](https://drone.nextcloud.com/nextcloud/spreed/100/29) and [_php7.1-integration_ log for pull request 100](https://drone.nextcloud.com/nextcloud/spreed/100/31).
As the _spreed_ repository only contains the app, in order to run the tests Drone downloads and executes https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh, which downloads the server and prepares the environment as needed, and then downloads and executes https://raw.githubusercontent.com/nextcloud/travis_ci/master/core_install. …
=> Use a newer version of the nextcloudci/php7.1 Docker image in Drone

js/app.js
This `avatar(null, 128)` no longer works because of this change https://github.com/nextcloud/server/commit/54c68519ce1cab9baaf86a29c7172811767d97c4
null is converted to string and then an avatar with an 'N' is generated.
Before:
Now:
=> Fix guest's avatar

appinfo/routes.php, js/views/participantview.js, lib/Controller/RoomController.php, lib/Room.php
=> Fix guest entries in sidebar

tests/integration/features/bootstrap/FeatureContext.php
Besides returning the last element, `end` also sets the internal pointer of the array to the last element, and for that it receives a reference to the array. Thus, `end(array_keys(...` can not be used, as it would
generate the Strict Standards error _Only variables should be passed by reference_, so the returned value from `array_keys` has to be stored in a variable.
=> Fix Strict Standards error in integration tests on PHP 7

tests/integration/features/add-participant.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/delete-room.feature, tests/integration/features/leave-room.feature, tests/integration/features/one-to-one.feature, tests/integration/features/promotion-demotion.feature, tests/integration/features/public-private.feature
This makes possible to ensure that the right value was returned by the server.
=> Use a different display name than the user ID in the integration tests

tests/integration/run-docker.sh
When running the integration tests through _run.sh_ the parent directory of the Spreed application must be the _apps_ directory of an installed Nextcloud server. Running the tests modifies the configuration and database of that server, and the tests could fail too if the state of its database conflicts with that expected by the tests.
The new _run-docker.sh_ is a wrapper around _run.sh_ that copies the code (but not the configuration or data) of the Nextcloud server and its applications to a Docker container, installs the Nextcloud server inside the container (with a SQLite database), and then executes the integration tests on the fresh server. This prevents the integration tests from messing with the original Nextcloud server, and also ensures that the integration tests will be run with …
=> Add helper script to run integration tests on a Docker container

appinfo/info.xml, appinfo/routes.php, css/style.css, docs/api-v1.md, js/signaling.js, js/views/roomlistview.js, lib/Controller/CallController.php, lib/Controller/RoomController.php, lib/Exceptions/InvalidPasswordException.php, lib/Manager.php, lib/Migration/Version2001003Date20170911145301.php, lib/Migration/Version2001Date20170921145301.php, lib/Room.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/callapi/password.feature, tests/integration/features/set-password.feature
=> Room passwords

appinfo/info.xml, lib/Activity/Hooks.php, lib/Activity/Provider/Base.php, lib/Activity/Provider/Call.php, lib/Activity/Provider/Invitation.php, lib/AppInfo/Application.php, lib/Manager.php, lib/Migration/Version2001Date20171009132424.php, lib/Room.php, tests/php/Activity/Provider/BaseTest.php, tests/php/Activity/Provider/InvitationTest.php
Fix #236  
> ![bildschirmfoto vom 2017-10-10 17-10-55](https://user-images.githubusercontent.com/213943/31394357-62b054e6-adde-11e7-9954-b520a0c8abf7.png)
Should add the room name to the activity so it's clickable.
But I just noticed this is also missing for invitations, so I will do it in a follow up PR.
=> Activities for calls

js/views/sidebarview.js, js/views/tabview.js
Fixes #446
When adding tabs to the right sidebar it is now possible to provide a `priority` property to set the order of the tab header relative to the other tab headers.
=> Add support for specifying tab order in the right sidebar

appinfo/routes.php, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/group.feature, tests/integration/features/chat/one-to-one.feature, tests/integration/features/chat/password.feature, tests/integration/features/chat/public.feature, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
This pull request adds a basic backend for the chat; the frontend will be added in later pull requests.
The backend provides two controller methods: `sendMessage` and `receiveMessages`. `receiveMessages` uses a long-polling approach: it returns immediately only if there are messages available; otherwise it keeps the HTTP connection open and waits for new messages, returning them as soon as they are available (in which case a new HTTP request must be done by the client). The HTTP connection is not kept open indefinitely, though; the default timeout is 30 seconds, and the maximum timeout that can be set is 60 seconds (I have used those values because they _felt_ right; they are not related to typical values for web server timeouts or anything like that).
Note that, at this time, chat …
=> Add basic backend for chat

js/views/callinfoview.js
When the `CallInfoView` is rendered the values set in the input fields but not saved yet are lost. Therefore, instead of directly rendering the view when the attributes of the model change it is first checked if an edition is being performed and, it is, then the view is rendered once the edition is finished.
`renderWhenInactive` assumes that the password is not being edited when the field has no value. However, when the user set a password the field was not automatically emptied, and thus the rendering was blocked (unless the user manually emptied the field). To prevent this, now, once the password is successfully set, the field is automatically emptied.
=> Fix call info not being rendered when a password is set

css/style.css
This will conflict with #456 (I will rebase as needed depending on which one gets merged first).
In normal mode (and a wide screen), when the sidebar is opened a `margin-right` is applied to the app content to make room for the sidebar. In fullscreen mode the element set as fullscreen is the app
content, but it seems that different browsers handle fullscreen elements with a margin in different ways: Firefox ignores the margin and uses the full width, while Chromium uses a strange mix which is neither the full width nor the full margin. Due to this, now the margin is removed in fullscreen mode to unify the appearance across browsers.
As there is no margin, the sidebar now visually seems to slide on the app content instead of _pushing_ it to the left (which is the same behaviour shown in …
=> Fix sidebar in fullscreen mode

css/style.css, js/app.js, js/models/localstoragemodel.js, js/models/room.js, js/signaling.js, js/views/callinfoview.js, js/views/editabletextlabel.js, templates/index-public.php, templates/index.php
This pull request adds the right sidebar also to the public page. Right now the right sidebar in the public page does not provide much value, but this is a preparatory step to later add a chat tab in the sidebar.
The guest name is now shown in the sidebar too instead of in the header as before. This made possible to move the _Enter/Exit fullscreen_ button to the top right corner (which in my opinion looks better), extend the sidebar to the top (as the header is hidden during calls in the public page), and reduce the UI elements shown during calls.
The room name and the guest name had a lot of similar code, so it was refactored into a new view, `EditableTextLabel`. An `EditableTextLabel` shows a single text attribute from a Backbone model and, optionally, also makes possible to edit it. As …
=> Add support for right sidebar in public page

appinfo/info.xml, appinfo/routes.php, css/settings-admin.scss, js/admin/signaling-server.js, js/calls.js, js/signaling.js, lib/AppInfo/Application.php, lib/BackendNotifier.php, lib/Config.php, lib/Controller/BackendController.php, lib/Controller/PageController.php, lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/Room.php, lib/Settings/Admin/SignalingServer.php, templates/index-public.php, templates/index.php, templates/settings/admin/signaling-server.php, tests/php/ConfigTest.php
This PR adds support for using a standalone signaling server.
See https://github.com/nextcloud/spreed/wiki/Spreed-Signaling-API for the documentation of message formats. In a follow-up PR, the same messages will be implemented for the PHP backend, so there is only one API that clients need to implement.
@nickvergessen @Ivansss
=> Standalone signaling support

css/comments.css, js/app.js, js/models/chatmessage.js, js/models/chatmessagecollection.js, js/views/chatview.js, templates/index-public.php, templates/index.php
This pull request adds a basic web frontend for the chat to the right sidebar. The UI is based on the Comments app, although without some of its more advanced features like mentions or autocompletion.
The CSS file is a direct copy of the CSS file from the Comments app; in the future it could be worth extracting the common parts between the Comments app and Nextcloud Talk, but for now... A copy is fine ;-)
The ChatView has some minor problems with the avatars of guest users; they should be addressed in a future pull request.
=> Add basic frontend for chat

appinfo/info.xml, appinfo/routes.php, docs/api-v1.md, js/app.js, js/calls.js, js/signaling.js, js/simplewebrtc.js, js/views/callinfoview.js, js/views/roomlistview.js, js/webrtc.js, lib/AppInfo/Application.php, lib/Controller/CallController.php, lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/Manager.php, lib/Migration/Version2001Date20171031102049.php, lib/Participant.php, lib/Room.php
=> Split "being in a room" from "calling"

js/signaling.js
This fixes a UI issue with the standalone signaling where the interface didn't switch back to the "Looking good" view when leaving a room.
=> Trigger "usersLeft" event for remaining users when leaving room.

lib/Controller/CallController.php, lib/Room.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/callapi/group.feature, tests/integration/features/callapi/one-to-one.feature, tests/integration/features/callapi/password.feature, tests/integration/features/callapi/public.feature, tests/integration/features/chat/password.feature, tests/integration/features/chat/public.feature, tests/integration/features/set-password.feature
This is a follow up for #459.
This pull request fixes the arguments passed to `Participant` constructor (which fixes joining a room as a guest from the UI) and the integration tests for setting a password and chatting, as they should join a room instead of a call since the changes introduced in the previous pull request.
The integration tests are not fully fixed yet, though. It seems that it is no longer possible to join a call without joining the room first, not even for the creator or someone who was invited to the room. The question is, should directly joining a call automatically make the participant to join the room too? Or should it be kept like now, in which the participant must join the room explicitly? @Ivansss @nickvergessen Please fix the code and/or the integration tests as …
=> Fix split "being in a room" from "calling"

css/style.css, templates/index-public.php
This will conflict with #455 (I will rebase as needed depending on which one gets merged first).
This pull request fixes the Nextcloud logo not being shown on the public page, aligns the header markup with the one used in user pages, and hides the header when in fullscreen mode on the public page.
=> Fixes for header on public page

js/views/callinfoview.js
When there is no password input field its value is undefined, so the rendering never finished when calling `renderWhenInactive` due to the strict equal comparison.
This is a prerequisite for, but does not fixes, the [slow update of the _Join/leave call_ button](https://github.com/nextcloud/spreed/issues/473) (that will come in a different pull request).
=> Fix call info rendering blocked for normal (not moderator) users

js/webrtc.js
Fixes #473
The button is updated when the model changes, but the model was not being synced when the user joined or left a call, so it only changed when it was synced for any other reason.
=> Fix slow update of "Join/leave call" button

css/comments.css, js/views/chatview.js
Now contiguous chat messages sent by the same user with a difference of less than 120 seconds between each message are grouped together; chat messages sent during the same day are _grouped_ by showing a header with the date.
Just for the record, the threshold of 120 seconds was chosen for no special reason; it simply felt like a reasonable value.
**Before grouping:**
**After grouping:**
=> Add grouping of messages in chat view

lib/Activity/Hooks.php, lib/AppInfo/Application.php, lib/Room.php
Only last commit is relevant, because it is:
Regression from #459 
Before joining a room would start the call and the call would only end when there is no one in the room and someone is removed from a room 💔
=> Fix call activity

lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Controller/ChatController.php, lib/Notification/Notifier.php, tests/php/Chat/ChatManagerTest.php, tests/php/Chat/NotifierTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Notification/NotifierTest.php
This pull request adds notifications for users mentioned in a chat; the notification links to the Talk room, and includes an ellipsized version of the original message centered around the mention (as the length of the notification message can be at most 64 bytes).
The rich subject of the notifications use `call` instead of `room` or `chat` due to `call` being already available in [lib/public/RichObjectStrings/Definitions.php](https://github.com/nextcloud/server/blob/a089e084116e88b3cad35b2f3a294445d78d8a3d/lib/public/RichObjectStrings/Definitions.php#L155) (in Nextcloud server). Unlike with the current code for invitation notifications, no checks are made on whether `call` is available or not, as the chat will be available only from Nextcloud 13 and onwards (I think so :-P ).
A mentioned …
=> Notify users mentioned in chat messages

templates/index-public.php, templates/index.php
Fixes regression https://github.com/nextcloud/server/issues/7243
audio-white and audio-off-white should be visible in Talk app when video is disabled (thanks to shadow).
This introduces new class `.icon-shadow` that can be use on any icon. Other icons that (still) have SVG shadow filters will be migrated to this solution in a subsequent PR, because only this one is critical.
To be reviewed and merged with https://github.com/nextcloud/server/pull/7247
=> Give audio-white and audio-off-white shadow via CSS

lib/Manager.php
The problem is, that SQLite does the LIMIT before the LEFT JOIN.
This means it would always take the latest room and then try to
match your session against it. However, we wanted to first match
the LEFT JOIN and then limit the result set to 1 row.
By changing the FROM to the participant table, we will always match
the correct participant (if there is one) and then left join the
room just like we intended to.
=> Fix SQLite random issues where you can only connect to the newest room

appinfo/routes.php, lib/Config.php, lib/Controller/PageController.php, lib/Controller/SignalingController.php
"Regression" from 6ee066ab0825517fb992cf9377e7b0fc46005827
call `GET ocs/v2.php/apps/spreed/api/v1/signaling/settings` to get the stun, turn and other required config
=> Allow apps to get the signaling information

js/views/sidebarview.js, js/views/tabview.js
Now it is possible to remove a tab from the sidebar; the content view of removed tabs is not destroyed, which makes possible to add it again in a new tab if needed.
This will be used to move the chat view between the main view and the sidebar depending on whether the participant is in a call or not.
=> Make possible to remove tabs from the right sidebar

js/views/chatview.js
Based on nextcloud/server#7266
=> Fix input field not disabled while a chat message is being sent

js/models/chatmessagecollection.js
The timestamp is in seconds, so when sent extremely fast two or more messages can have the same timestamp. As a stable sorting algorithm is used and the messages were sorted only by timestamp, when two or more messages had the same timestamp the relative order between them was the same as the one returned by the server. Due to this those messages were sorted from newest to oldest between them, while the rest were sorted from oldest to newest. The solution is to sort the models by their reversed position in the set returned by the server.
=> Fix sorting of chat messages with same timestamp

js/app.js
Fixes #461
The sidebar has a width of 27% of the window width and a minimum width of 300px. Therefore, when the window is 1111px wide or narrower the sidebar will always be 300px wide, and when that happens it will overlap with the content area (the narrower the window the larger the overlap); this will be more evident once the chat view is shown as the main view. Due to this the sidebar is opened automatically only if it will not overlap with the content area.
With this change if the window is wide enough the sidebar will always be opened when joining a room. Should we try to be more _clever_ about that (and take into account that _soon_ the main view will show not only video, but also a chat when not in a call)? For example, if the user joins a room and closes the sidebar without …
=> Open sidebar automatically when joining a room

templates/index-public.php, templates/index.php
To be reviewed alongside PR: https://github.com/nextcloud/server/pull/7319
Basically moves the toggle icon to core iconset and migrates to CSS-generated icon shadows, deprecating SVG-shaded versions.
Finishes work started in #501 
@nextcloud/designers
=> Remove svg shadows

js/models/room.js
`name` is the name of the room that can be editable and it's saved in the db.
When getting the rooms we set a list of participants in `displayName`
In the left side bar, when the room has no name, we use `displayName`.
=> Fix room rename.

js/admin/turn-server.js
Fixes #531
The TURN server values are now (tried to be) saved when the protocols are changed, like it is done when the server URL or the secret are changed.
Note that, just like with the server URL or the secret, all the required fields must be filled for the saving to succeed. Otherwise no value will be saved.
=> Fix protocols for TURN server not saved

appinfo/info.xml, lib/Manager.php, lib/Migration/Version2000Date20171026140256.php, lib/Migration/Version2000Date20171026140257.php, lib/Migration/Version2001Date20170707115443.php, lib/Migration/Version2001Date20171026141336.php, lib/Migration/Version2001Date20171031102049.php, lib/Migration/Version2001Date20180103144447.php, lib/Migration/Version2001Date20180103150836.php, lib/Room.php
=> Simplify the owner update queries when the instance has no one2one rooms

css/style.css, js/app.js, js/webrtc.js
If theres no cam available, this fix will toggle the video icon into the disabled mode. This is solved by query the hardware from navigator.getUserMedia API. 
This Fix is based on:
Disable 'Enable video' button if no camera is connected [#441](https://github.com/nextcloud/spreed/issues/441)
=> Disable 'Enable video' button if no camera is connected

js/views/chatview.js
Some browsers (like Firefox) automatically return the focus to the new message input after sending a message, while others (like Chromium) do not. Now the focus is explicitly given back to the new message input to make more comfortable to keep writing new messages.
=> Focus again on new message input after sending a message

css/style.css, js/app.js, js/views/chatview.js, templates/index-public.php
No changes were made to the layout of the chat view in this layout. Therefore, the messages are shown from newest to oldest and the new message input is shown at the top, even when shown as the main view, which is an uncommon layout. A follow up pull request will reverse the layout of the chat view to use a more common one.
In the same way, the local video is now hidden behind the chat view. When the chat view is shown as the main view the local video should appear in a sidebar tab; this will be done in another pull request too.
=> Show chat view as main view when in a room but not in a call

css/style.scss, js/app.js, js/views/sidebarview.js, js/views/tabview.js
Except when almost empty, the message list of the chat view is taller than its available vertical space in the sidebar. Due to this a scroll bar was shown for the whole sidebar, and everything was moved when
scrolling to see overflown messages.
That is a valid approach when messages are shown from newest to oldest and the new message input is above the list of messages, as in that case the call details and the tab headers are near the new message input and the newest messages.
However, once the layout of the chat view is reversed and the messages are shown from oldest to newest with the new message input below the list of messages having to scroll back and forth to see the call details/tab headers or the new message input/newest messages would be a pain.
Therefore now the scroll bar is …
=> Limit scroll bar in sidebar to chat view

js/views/editabletextlabel.js
The value of the input was not properly updated when the model attribute changed.
For example:
- Moderators A and B join a room
- Moderator A changes the name of the room
- The room name label is updated in the browser of moderator B. However, if moderator B tries to change the name of the room the old name is shown in the input.
Instead of updating the value of the input when the name of the room changes now it is always updated before the input element is shown.
=> Fix the update of the EditableTextLabel input

css/style.scss, js/views/chatview.js
When a new message arrives the list of messages is automatically scrolled to show the new message,
except if the list was not at the bottom in which case no scrolling is made and the current visible messages are kept at the same place. Basically this auto scrolls, except if the user is checking older messages.
There are still some details that should be improved regarding scrolling:
- When the chat is moved between the main view and the sidebar the scroll position is not kept. Same when expanding and restoring the list of messages using #558 
-  If the last message is partially visible sometimes (when the message is grouped) the list is not scrolled to the new message; it seems that calling `position()` on a comment returns where it should be instead of where it is due to a negative …
=> Improve automatic scrolling behaviour when new messages arrive

css/style.scss
Before / after:
More breathing space, 50% default width for the tabs, proper underline for inactive tab.
Please review @nextcloud/talk
=> Improve tab header styles, center headings, flexbox

js/views/chatview.js
=> make links in chat clickable

appinfo/info.xml, lib/Migration/Version2000Date20171026140256.php, lib/Migration/Version2000Date20171026140257.php, lib/Migration/Version2001Date20170707115443.php, lib/Migration/Version2001Date20171026134605.php, lib/Migration/Version2001Date20180103144447.php
~~Postgres could not be used in 12. It installed the tables with wrong names
so we need to ignore it on the update steps. The wrong tables will be
dropped and new tables will be created with further migrations.
But we shouldn't try to migrate data from the old and broken layout.~~
Fix #578 
Fix #543
=> Fix postgres issue when updating

js/app.js, js/views/editabletextlabel.js, js/webrtc.js
Now, the guest name is sent every time the connection is established.
Also guest names are stored by every participant in a (session -> guest name) table.
So screenshare's name indicator can be updated properly.
Fix #552
=> Remember guest names

js/views/chatview.js
@jancborchardt it's not exactly the steps you mentioned, but instead its automatically done by momentjs.
I think it's good enough, but since "a month ago" is repeating with each day in the past, I'd also be fine with only showing relative until it's no longer displayed as "days ago".
No one needs relative dates for "7 months ago".
> ![ug-test_-_gesprach_-_nextcloud_-_2018-01-15_16 10 07](https://user-images.githubusercontent.com/213943/34949010-182e20e2-fa0f-11e7-99e9-ac48f43fd1e7.png)
Fix #559
=> Add a relative prefix to the date divider in the chat

lib/Migration/Version2000Date20170707093535.php, lib/Migration/Version2000Date20171026140256.php, lib/Migration/Version2000Date20171026140257.php, lib/Migration/Version2001Date20170707115443.php, lib/Migration/Version2001Date20170913104501.php, lib/Migration/Version2001Date20170921145301.php, lib/Migration/Version2001Date20170929092606.php, lib/Migration/Version2001Date20171009132424.php, lib/Migration/Version2001Date20171026134605.php, lib/Migration/Version2001Date20171026141336.php, lib/Migration/Version2001Date20171031102049.php, lib/Migration/Version2001Date20180103144447.php, lib/Migration/Version2001Date20180103150836.php
Ref https://github.com/nextcloud/server/pull/7909
=> Fix migration type hints

lib/Migration/Version2000Date20171026140257.php
Appearantly some rooms had null as a token in the past
Don't know why this should occur, because the table had default value empty string since ever, but this should fix the problem of @tobiasKaminsky
=> Also set a token when it is null

css/style.scss
=> Keep light style icons when screensharing is active.

css/style.scss, js/webrtc.js
=> Fix screensharing issues

js/signaling.js, js/webrtc.js, lib/AppInfo/Application.php, lib/Controller/SignalingController.php, lib/Signaling/BackendNotifier.php, tests/php/Controller/SignalingControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
=>  Split "room" from "call" when using the standalone signaling server.

css/style.scss
Sometimes, when there are more than 2 people in a call, remote peers videos covered the promoted video.
This problem was more evident when one of the videos at the bottom was sent by a phone in portrait orientation.
This PR set a maximum height of 200px to all videos at the bottom of the screen when there are more than 2 participants in the call.
Important: Rounded corners and shadows had to be removed 😞 
@jancborchardt maybe you come up with a better idea but that's the best one I found.
Before:
Now:
Fix #629
=> Set maximum video height when more than 2 people in call.

lib/Capabilities.php, lib/Controller/SignalingController.php, tests/php/CapabilitiesTest.php
Fix #634 
@fancycode this is required, so the mobile apps work for guests.
I couldn't find a reason in the path why it should be disallowed for guests,
as there is special handling on generating the ticket for guests:
https://github.com/nextcloud/spreed/blob/5670fcb9ad2136062ef2aa7f3f51d8cc3a1de3d0/lib/Config.php#L180-L184
=> Allow to get signaling settings as guests

css/style.scss, img/no-password.svg, js/views/callinfoview.js
Password input caught to much attention in the right side bar.
It will be hidden by default and a password button will replace it.
@jancborchardt It would be nice to have an **'opened lock' icon** so we can show it when the room has no password set.
Also, we could have a new combined icon (public + password) for the left side bar, so a user could see directly which public calls are password protected without being in that room.
Something like this:
=> Improve password protection UX and UI.

css/style.scss, img/no-password.svg, js/views/callinfoview.js
=> [stable 13] Improve password protection UX and UI

CHANGELOG.md, appinfo/info.xml
- Finish support for go-based external signaling backend
[#492](https://github.com/nextcloud/spreed/pull/492)
- Make capabilities and signaling settings available for guests
[#644](https://github.com/nextcloud/spreed/pull/644), [#654](https://github.com/nextcloud/spreed/pull/654)
- Use the search name as room name when creating a new room
[#592](https://github.com/nextcloud/spreed/pull/592)
- Make links in chat clickable
[#579](https://github.com/nextcloud/spreed/pull/579)
- Fix screensharing layout for guests
[#611](https://github.com/nextcloud/spreed/pull/611)
- Correctly remember guest names when a guest is rejoining an existing call
[#593](https://github.com/nextcloud/spreed/pull/593)
- Better date time divider in chat view
[#591](https://github.com/nextcloud/spreed/pull/591)
---
❓ …
=> Prep release of 3.1.0

.drone.yml, tests/integration/features/bootstrap/FeatureContext.php
Fixes #443
Requires nextcloud/travis_ci#5
The _before_install.sh_ script uses the `$DATABASEHOST` environment variable to either create the database or wait for it to be up, and also to set the database host during the installation. Drone services are located by other Drone containers by their name, so the `$DATABASEHOST` must be set to the name of the database service; in the case of SQLite `$DATABASEHOST` is ignored, so there is no need to set it.
~~By the way, it seems that there is a bug with the order of received chat messages in PostgreSQL :-O I will try to take a look.~~ @nickvergessen addressed that in the last commit.
=> Run integration tests on MySQL and PostgreSQL too

lib/Controller/RoomController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/one-to-one.feature
=> [stable13]  Do not allow one2one calling yourself

lib/ContactsMenu/Providers/CallProvider.php
Fixes:
when an invalid user was posted to the provider.
Can happen if an LDAP user is unavailable for whatever reason.
=> pass if no valid user object was returned

lib/Activity/Hooks.php
Related to https://github.com/nextcloud/server/pull/8355 
This would blow up further in line 109, because `setAffectedUser()` only accepts strings. 
I could not test this on my dev setup unfortunately.
=> cast userids to string to avoid issues with  numerical IDs

js/admin/stun-server.js, js/admin/turn-server.js
Closes #600
The `https://` protocol is not used (to my knowledge) in TURN connections, rather it is the turn protocol. So, this placeholder should not include HTTPS prefix, as it may mislead end users.
=> Remove https:// prefix from TURN URL placeholder

css/style.scss
=> Fix local video shadow

js/app.js
a - toggle audio on/off
v - toggle video on/off
p - switch to participants tab
c - switch to chat tab
Backport #705
=> [stable13] Add shortcuts for calling

css/style.scss, js/app.js, js/webrtc.js
Also fixes "Stop screensharing" which is broken since the webrtc overhaul
Fix #688
=> Allow screensharing even when alone

css/style.scss, js/connection.js, templates/index.php
That seems to be ignored. Can you help @skjnldsv 
Fix #527
=> Improve fullscreen handling

css/style.scss
Bring back #573 implemented by @schiessle 
Until the header discussed in #573 is not implemented, chat view looks much better with this padding.
=> Increase padding in chat view to leave enough space for side buttons.

appinfo/routes.php, js/signaling.js, lib/Manager.php
Follows #748 
getSettings endpoint could not be used because `signaling/settings` was wrongly treated as `signaling/{token}` (pullingMessages).
=> Fix new multi-session signaling endpoints.

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/ChatAncestorSetter.php, tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/bootstrap/ConversationInfoContext.php, tests/acceptance/features/bootstrap/ConversationListContext.php, tests/acceptance/features/bootstrap/ParticipantListContext.php, tests/acceptance/features/bootstrap/TalkAppContext.php, tests/acceptance/features/conversation.feature, tests/acceptance/installAndConfigureServer.sh, tests/acceptance/run.sh
Requires nextcloud/server#9114 and nextcloud/server#9127
This pull request adds support for acceptance tests to Nextcloud Talk and provides a basic set of tests for conversations (creating conversations, changing and removing them); more tests will be added in following pull requests.
=> Add acceptance tests

css/style.scss, js/models/participant.js, js/views/participantlistview.js
=> [stable13] Add an icon for participants which are in the call

css/style.scss, js/views/sidebarview.js
This makes the interface more predictable and doesn’t leave the fullscreen toggle hanging in mid-air in some settings.
@Ivansss @danxuliu we only need to add the handler to make the sidebar-trigger close the sidebar again. I guess it’s in sidebarview.js but don’t know fully how, can you help me here? :)
=> Always show sidebar toggle, also when sidebar is open

js/views/callinfoview.js
Before:
Now:
As an icon is required in popover menu (as discussed in https://github.com/nextcloud/spreed/pull/647#issuecomment-376143749), I think a lock icon makes more sense than a triangle.
It looks like something could be disclosed with the triangle.
=> Add lock icon to password popover.

docs/api-v1.md, js/models/chatmessagecollection.js, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Controller/ChatController.php, tests/integration/features/bootstrap/FeatureContext.php, tests/php/CapabilitiesTest.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
The offset now is based on the last known chat message instead of limit-offset,
so new messages don't mess up requests to get the history of a room
Todo:
=> Add proper chat message offset support

docs/api-v1.md, js/views/roomlistview.js, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
Part 1 of https://github.com/nextcloud/spreed/issues/798
=> Add unread message count to the room list

css/comments.scss, css/style.scss, docs/api-v1.md, js/models/chatmessage.js, js/richobjectstringparser.js, js/views/chatview.js, lib/Chat/RichMessageHelper.php, lib/Controller/ChatController.php, templates/index-public.php, templates/index.php, tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/chat.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/group.feature, tests/integration/features/chat/one-to-one.feature, tests/integration/features/chat/password.feature, tests/integration/features/chat/public.feature, tests/integration/features/chat/rich-messages.feature, tests/php/Chat/RichMessageHelperTest.php, tests/php/Controller/ChatControllerTest.php
This pull request adds formatted mentions to the message list (but not formatted mentions nor auto-completion in messages being composed); it is based on #517, although in this case avatars are no longer included in the mention ([as decided in #517](https://github.com/nextcloud/spreed/pull/517#issuecomment-357277790)).
It is based on both the mentions shown in the Comments app and the rich formatting of notifications. The backend uses the Comments API to store the messages, so when `receiveMessages` is called the Comments API is used to extract the mentions from the plain text message originally sent. However, unlike the Comments app, the mentions are not returned to the client in its own attribute, but in a generic way using a rich object string. Thanks to this approach it should be …
=> Format mentions (without avatars) in the message list

css/comments.scss
=> Make mentions more prominent

css/comments.scss
This pull request fixes a regression introduced in b458794e6a6430fda9c835ef84ed29c163d45019
The submit icon is hidden when the working icon is shown; in the screenshots below both are shown at the same time for clarity.
Before:
After:
=> Fix working icon position when sending a message

css/comments.scss
When a message shows the date separator its author row is explicitly shown. This is needed to ensure that the author row will always be shown in that case, even if the message is a grouped message. In normal messages (those that are not grouped and do not show the date separator) [now the author row is shown using "display: inline-flex"](https://github.com/nextcloud/spreed/pull/812/commits/85cd8181e5c5c0a58f89d67a492b97b10631fdc2#diff-e2a9b39888965cc9ac080ee77638d6d3R155), so the same value should be used too for messages that show the date separator.
Before (issue is in first message; second message is a non-grouped message, shown for reference):
After (the difference is subtle, but it is there :-P ):
=> Fix appearance of author row when showing the date

css/comments.scss, js/views/chatview.js
Follow-up to #814.
Now the default cursor is shown instead of the pointer cursor on guest users, on any user in the public view, and on the user shown in the new message form, as in those cases the contacts menu does not appear when clicking on the users.
=> Fix pointer cursor shown for guests and in new message form

css/comments.scss, js/app.js, js/views/chatview.js
When [the oldest on top layout was added](https://github.com/nextcloud/spreed/pull/561) it was enabled by default, although the original newest on top layout was also kept as an option. However, the newest on top layout has not been used since then, and it is not expected to be used ever again. To make the chat view more maintainable and ease adding new features this pull request removes the original newest on top chat layout.
This pull request also removes the unused CSS rules for `.oldestOnTopLayout` elements (yes, oldest on top, not the layout that is being removed but the layout that is being kept); due to a stupid mistake the CSS class was never added, so the CSS rules were not used :facepalm:
=> Remove support for newest on top chat layout

js/app.js, js/views/chatview.js
Follow-up to #564.
This pull request fixes the chat view not scrolling to the new message if the last message was grouped and partially visible. More important, it also fixes the scroll position not being kept when the chat view is switched between the main view and the sidebar.
**How to test (chat view not scrolling to new message):**
- Open a conversation and write enough messages to show the scroll bar.
- Write two messages quickly, so the second one is grouped with the previous one.
- Scroll so the last message (the grouped one) is slightly visible.
- Write another message.
Expected result:
- The chat view automatically scrolls to the new message.
Actual result:
- The chat view does not scroll.
**How to test (scroll position kept when switching the chat view):**
- Open a conversation …
=> Fix scrolling in chat view

css/comments.scss, js/views/chatview.js
The contacts menu can be shown only in user sessions; in the public view it just fails and shows an error message instead of any useful option, so now it is disabled for mentions in the public view.
Accordingly, now the cursor is a pointer on mentions only if the contacts menu can be shown for that mention.
=> Disable contacts menu for mentions in the public view

js/app.js, js/views/chatview.js
=> [stable13] Fix scrolling in chat view

css/style.scss, js/views/roomlistview.js
CSS is a copy of the server version now
Top is new (84445 is now 99+)
Bottom is old (number is cut off)
> ![bildschirmfoto von 2018-05-03 11-18-59](https://user-images.githubusercontent.com/213943/39568876-ea3de7c6-4ec3-11e8-9c36-d424202b61e7.png)
As per documentation https://docs.nextcloud.com/server/13/developer_manual/design/navigation.html#counter the counter should be limited to 3 digits, but I think for chat messages it does not matter anymore when it's over 100, so we display 99+ when it's more then 99
@Ivansss @mario we limit the number in the UI not the api, so maybe you can limit it too to 99+
=> Limit unread message counter to "99+"

js/views/chatview.js
Fix #817 
After this change https://github.com/nextcloud/spreed/pull/807 we should not check any more for null values.
=> Fix empty guest display name

js/app.js, js/connection.js, js/webrtc.js
When we delayed the media access, we were all fast with testing.
Before this patch, when there was already at least one user in the
call and you took longer to accept the media request than webrtc
took to init everything, you would always send a black video signal
and no sound, because the data was not there, when connections were
established with the other users. Now we first request the media and
send the join call to the server afterwards.
Fix #850
=> Join the call only aftrer media access was done

js/app.js, js/signaling.js, lib/AppInfo/Application.php, lib/Signaling/BackendNotifier.php
This PR fixes a couple of issues when using the standalone signaling server.
Should be backported to the current stable after landing.
=> Various standalone signaling fixes.

js/webrtc.js
If the same user joins the call again, the video would otherwise not be promoted automatically because the id is still stored in `latestSpeakerId`.
=> Unpromote latest speaker if no users remain in call when removing video.

js/app.js, js/connection.js, js/views/roomlistview.js, tests/acceptance/features/bootstrap/ConversationListContext.php, tests/acceptance/features/bootstrap/TalkAppContext.php, tests/acceptance/features/conversation.feature
=> Fix chat view when leaving current room

lib/AppInfo/Application.php, lib/Signaling/BackendNotifier.php
Btw, that is the expected behaviour when a user is removed? For now I can simply reconnect and will be in the room again.
=> Notify standalone signaling server about sessions to remove from room.

js/app.js, js/connection.js, js/views/roomlistview.js, tests/acceptance/features/bootstrap/ConversationListContext.php, tests/acceptance/features/bootstrap/TalkAppContext.php, tests/acceptance/features/conversation.feature
Requires #871 
This pull request fixes the call UI being shown after leaving the current call.
Note that the fix just shows and hides the HTML elements when needed; a proper fix would require to introduce view objects for the call UI and things like that, but for the time being this is good enough ;-)
Unfortunately acceptance tests could not be provided; as far as I know it is not possible to grant media permissions from WebDriver (although there are some tricks to grant them beforehand when using Mozilla Firefox, but they are cumbersome to apply with Behat/Mink :-( ).
- Create a conversation with another user
- Join the call with both users
- Delete the conversation
**Expected result:**
The empty content message is shown.
**Actual result:**
The local video container and …
=> Fix UI when leaving current call

lib/Controller/SignalingController.php, lib/GuestManager.php
=> Stop refreshing participant list when a guest is chatting

js/app.js, js/connection.js, js/views/roomlistview.js
Backport of #871
When testing note that without the backport of #861 it will fail when creating another conversation after deleting the previous one.
=> [stable13] Fix chat view when leaving current room

js/app.js, js/connection.js, js/webrtc.js
When we delayed the media access, we were all fast with testing.
Before this patch, when there was already at least one user in the
call and you took longer to accept the media request than webrtc
took to init everything, you would always send a black video signal
and no sound, because the data was not there, when connections were
established with the other users. Now we first request the media and
send the join call to the server afterwards.
Backport #854
=> [stable13] Join the call only aftrer media access was done

tests/acceptance/features/chat.feature
The chat between two users was tested by a sequence of one user sending a message and immediately after that the other user sending another message. Most of the time the messages were processed in the server in the order in which they were sent, but sometimes it could happen that a previous message took longer than usual to get to the server and then the next message from the other user was processed before it; in those cases the test failed due to the messages not matching the expected order. Now each user waits for the last message of the other user to be received before sending the next message.
=> Make acceptance test for two users chatting more robust

css/style.scss
Fixes #851, which is a regression introduced in #745.
When using Firefox, the participants tab view requires its overflow to be hidden to limit its size to the size of its parents. Otherwise, the participants tab view grows to fit its children; if that happens then no scroll bar is shown for the participants list, as the participants list is tall enough to fit all its items (even if they are not visible because they are in the overflow area). In Chromium, on the other hand, the participants tab view size is always limited by its parents, no matter if the overflow is hidden or not.
In a similar way, once the overflow is hidden the bottom padding added to the participants list has to be added to its last item instead. Firefox only takes into account the bottom padding in the participants …
=> Fix scrolling on participants list

lib/Activity/Provider/Base.php, lib/Notification/Notifier.php, tests/php/Activity/Provider/BaseTest.php, tests/php/Notification/NotifierTest.php
Follow up #751 
**Activities:**
{User} invited you to a call (before)
{User} invited you to a conversation (now)
**Notifications:**
{User} invited you to a group call (before)
{User} invited you to a group conversation (now)
{User} mentioned you in a group chat (before)
{User} mentioned you in a group conversation (now)
=> Calls are Conversations

css/style.scss
=> Fix appearance of participants menu button

lib/Chat/ChatManager.php
**Before:**
Messages already read by the user were marked as 'read' after new messages were sent by the server.
When there were no new messages, this could take 30 seconds (timeout) until the server replied.
If the request was canceled by the user during this time, read messages were not marked as read.
**Now:**
Read messages are directly marked as 'read' when the user request new messages.
=> Mark messages directly as read when waiting for new messages.

css/style.scss, js/webrtc.js
Before a user could disable her own video, but she had no way to disable the videos from other participants. This could be needed, for example, to alleviate the load on low-end systems, as in that case playing the video from remote participants could be too much for the system. Now a toggle is provided to manually show or hide the video of each remote participant if needed.
The toggle is shown only when the remote participant is sending video; if the remote participant has disabled her own video (or does not have a camera) the toggle is hidden.
Note that the toggle just shows or hides the HTML video element; it does not notify the remote participant to mute her video or to fully stop sending it. It is purely a local change that does not affect the remote clients. In the future this could …
=> Add toggle to show and hide video from other participants

css/style.scss
=> Fix menu position for rooms and participants

js/views/participantview.js
**How to test (a):**
- Create a group room
- Add a user to the room
- Create another group room
- Add the same user to the new room
**How to test (b):**
- Create a group room
- Add a user to the room
- Remove the user from the room
- Add the user again to the room
**Expected result:**
The user is added.
**Actual result:**
The user is not added.
=> Fix adding the same participant several times in a row

js/webrtc.js
=> [stable13] Fix local audio and video not disabled when not available

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
[As suggested by @jancborchardt](https://github.com/nextcloud/spreed/pull/500#issuecomment-356440981); although the meaning is not exactly the same (personally I would add back the _now_) the new wording is simpler and thus easier to understand.
=> Simplify notification wording

js/models/chatmessagecollection.js, js/signaling.js
No functional changes yet, but this will allow later to use the standalone signaling backend to notify clients about new chat messages without having to poll (see #624).
=> Move loading of chat messages to signaling class.

js/signaling.js, lib/AppInfo/Application.php, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, lib/Signaling/BackendNotifier.php, tests/php/Controller/ChatControllerTest.php
Implements #624. Based on #887 which should be merged first.
=> Support standalone signaling server for chat

js/views/roomlistview.js, tests/acceptance/features/bootstrap/ConversationListContext.php, tests/acceptance/features/conversation.feature
I had the same confusion as @diplodata in https://github.com/nextcloud/spreed/issues/849 where I wasn’t sure what the difference was between "Remove conversation from list" and "Delete conversation".
So now "Remove conversation from list" is "Leave conversation". :)
=> Fix wording for 'Leave conversation'

css/style.scss
- Reduce whitespace between participant list and "Add" input because they belong closer together
- Make it so that the participant list scrolls below the input field and there’s no white "block"
- Fix the participant list scrollbar not being on the very right
Before:
After:
=> Participant list whitespace

js/views/callinfoview.js
No need to duplicate that, especially as there it just flies around in the middle of other controls.
Not needed since we already have it in the chat input, where it’s much more relevant.
=> Remove guest name input from sidebar as it already is in chat

css/style.scss
=> Fix position of local container children in older Firefox versions

css/style.scss, js/views/callinfoview.js
First step of doing https://github.com/nextcloud/spreed/pull/562 _again_
- Controls in one row
- No height jumping
- Proper order and hierarchy of controls
- Primary action button has proper clickable size
Please review @nextcloud/talk 
Before:
After:
=> Improve call controls layout to single row

js/app.js, js/signaling.js, js/simplewebrtc.js, js/webrtc.js, lib/Signaling/BackendNotifier.php, tests/php/Signaling/BackendNotifierTest.php
This PR is work-in-progress to support using an MCU.
With an MCU, each client publishes only once (to the MCU) and viewers subscribe the streams from the MCU. This means that for subscribing, the MCU always has to send the "Offer" message which requires some changes in the workflow.
=> MCU integration

js/views/chatview.js
When some marked-up content is in the clipboard, it will be formatted as HTML on paste into  the chat input field. The patch fixes it, according to how it is done in [file comments](https://github.com/nextcloud/server/blob/master/apps/comments/js/commentstabview.js#L757-L761). Since we accept plain text only as comment/chat data, it should be inserted as plain text directly.
Before:
After:
Actually, it also affects what is exactly provided as chat message: 
(above before the patch, below after)
=> paste only plaintext into the chat input field

css/style.scss
Before:
After:
Please review @nextcloud/talk @nextcloud/designers @MariusBluem
=> Remove additional non-guideline padding in navigation entries

js/app.js, js/models/chatmessagecollection.js, js/signaling.js, js/simplewebrtc.js, js/views/roomlistview.js, js/webrtc.js, lib/AppInfo/Application.php, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, lib/Signaling/BackendNotifier.php, tests/php/Controller/ChatControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
Backport #887
Backport #398
Backport #890 
Backport #990
Backport #977
=> Backport all the things

lib/AppInfo/Application.php, lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Notification/Hooks.php, lib/Notification/Notifier.php, tests/php/Chat/ChatManagerTest.php, tests/php/Chat/NotifierTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Notification/NotifierTest.php
Changes the object id from room id to the token, so you can query the room to get the full information for it
Fix #1001
=> Use the token instead of the id to identify the room objects

appinfo/info.xml, lib/AppInfo/Application.php
As requested in #1043, this will make sure we only show the client links if the firstrunwizard app is enabled.
Fix #1043
=> Only show client links when the firstrunwizard is enabled

appinfo/info.xml, lib/Controller/PageController.php, lib/Room.php, tests/php/PasswordVerificationTest.php
I have added a hook to allow overriding the password check in order to provide a different password evaluation.  I am using this so that each user can have a different password.
=> Added hook to verify password to allow custom password check

css/style.scss, js/app.js, lib/Controller/PageController.php, templates/index-public.php, templates/index.php, tests/acceptance/features/bootstrap/ConversationInfoContext.php
This pull request fixes the several issues in the UI of Talk caused by the layout changes in the server (nextcloud/server#9982 and follow ups).
Note that this takes into account the changes in the server only up to Nextcloud 14 Beta 1; other layout changes were introduced after Beta 1, but those will be tackled in other pull requests.
Other known issues that will be fixed in other pull requests:
- Colour of fullscreen and sidebar trigger icons (the issue was not caused by the layout changes, but by a different server change)
- Header no longer hidden during calls in public page
- In fullscreen mode the sidebar now "pushes" the content to the left instead of sliding over it; while this is great in large screens it is problematic in narrow screens, and in those screens the old behaviour of …
=> Adjust UI to layout changes in server

css/style.scss, js/app.js
This pull request fixes a regression introduced in 8b247e25e1b5
Before:
After:
=> Fix "Participants" text not shown in tab header

css/style.scss, js/app.js
This pull request fixes the colour and the opacity of the icons shown on the content (the app navigation toggle, the sidebar trigger, the fullscreen button and the media buttons).
@nextcloud/designers Note that each group of icons uses its own opacity: the app navigation toggle (which comes from the server) uses 0.6, the sidebar trigger and the fullscreen button use 0.5, and the media buttons use 0.7. I have respected the opacity that was being used for them because I was not sure if those different values were on purpose due to their different function, or it is just something that should be fixed (but, if that is the case, it can wait to a different pull request ;-) ).
Before, no call:
After, no call:
Before, call:
After, call:
=> Fix colour and opacity of icons shown over main content

css/style.scss, templates/index-public.php
This pull request is a follow up to #1085 that adjust the UI again to the layout changes introduced in the server after Beta 1.
Basically it fixes the scrolling of the main view and removes a duplicated element (because it is now provided by the server).
Will this be the last pull request with fixes due to changes of the layout in the server before NC 14? He, who knows... :-P
=> Adjust UI to further layout changes in server

css/style.scss
Fixes #904
Note that the screenshots below were taken on top of #1091, so when testing this branch you will not see some of the icons (anyway, I have used different pull requests for them because they are independent issues).
Before:
After:
Note that the size of the media icons was not reduced; in my opinion it does not look good (in fact I would have increased the size of the app navigation toggle instead of reducing the others, but that is a different matter ;-) ):
=> Fix size of sidebar trigger and fullscreen icons

lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
Notification is only send, when you don't have an active session for the room.
Or should we still do this, so you beep-boop when you have the tab open somewhere in the background? @mario @jancborchardt 
Fix #875
=> Always notify in one2one rooms

js/app.js
Fixes #1113 
The room data currently comes from both the signaling and queries to the server, and each one of those sources have its own set of events. Due to this, when entering a room the list of participants can sometimes be tried to be fetched before the room was set for the list of participants.
This commit works around that problem by fetching the participant list only when a URL was set; the real fix (proper synchronization between the events from both sources) would require a much deeper overhaul of the architecture.
In order to test this and consistently cause `participantListChanged` to be triggered before the room is set [`this.setRoom(model)`](https://github.com/nextcloud/spreed/blob/85d3514991aadd4b31d8f5f306c337c3784215e8/js/app.js#L362) can be wrapped with a timeout, like …
=> Work around fetching participants before setting the room

appinfo/routes.php, css/publicshareauth.scss, js/app.js, js/connection.js, js/publicshareauth.js, js/webrtc.js, lib/Controller/PageController.php, lib/Room.php
Follow up for #1049 (without its last commit).
This pull request starts a call as soon as the password is requested; the video and the shared screen are shown in the sidebar, above the chat view.
The video could be shown in a larger area between the password form and the chat view; however it was added above the chat view to keep the concept of a sidebar, and because in most cases the person that needs to clearly see the other participant is the sharer, and not the requester.
In any case there would be no problem in changing the layout to the one mentioned above, or adding a fullscreen button to the sidebar to show the video as large as possible in case the requester needs it.
Unfortunately there is an issue with the notifications; [starting a call removes all the previous notifications …
=> Add support for video calls when requesting the password for a share

js/webrtc.js
During screensharing the `participants-X` and `incall` CSS classes were not updated, which could led to inconsistencies in the UI (for example, if another participant joined or left the call during screensharing).
How to test:
- Start call with user A
- Join call with user B
- Share screen with user A
- Leave call with user B
- Stop screen sharing with user A
Expected result:
The screen turns white again and the message _Waiting for user B to join the call …_ is shown.
Actual result:
The screen stays black. Note that, eventually, the proper UI will be restored due to the signaling, but it is not immediate as it should be.
=> Fix update of CSS classes during screensharing

js/richobjectstringparser.js, lib/AppInfo/Application.php, lib/Chat/SystemMessage/Listener.php, lib/Chat/SystemMessage/Parser.php, lib/Share/Helper/DeletedShareAPIController.php, lib/Share/Helper/ShareAPIController.php, lib/Share/RoomShareProvider.php, tests/integration/config/behat.yml, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/bootstrap/SharingContext.php, tests/integration/features/sharing/create.feature, tests/integration/features/sharing/delete.feature, tests/integration/features/sharing/get.feature, tests/integration/features/sharing/hooks.feature, tests/integration/features/sharing/move.feature, tests/integration/features/sharing/restore.feature, tests/integration/features/sharing/transfer-ownership.feature, tests/integration/features/sharing/update.feature, tests/integration/spreedcheats/lib/Controller/ApiController.php
Talk part of nextcloud/server#10255
First of all sorry for the massive size of this pull request. If it is any comfort to you it is basically a big specification of integration tests with some code in between :-P
This pull request, with its server counterpart, makes possible to share a file or folder into a Talk room. The integration test will need to be launched again once the server part is merged.
Room shares are heavily based on (read, copy-pasted from :-P ) group shares, although with some differences. In the same way that a user must be a participant of a room to send a message to it a user must be a participant of a room to share a file with it (in the case of group shares enforcing that is enabled in the settings). Similarly, when a user leaves a room she has no longer access to …
=> Add support for room shares

css/comments.scss, js/views/chatview.js
The button, which is shown next to the area to write new messages, shows a file picker and then shares the chosen file with the room.
Note that currently new files can not be uploaded through the file picker; only those already in the Nextcloud account of the user can be chosen.
Also, currently only registered users can share files with a room, so the button is hidden for guests.
=> Add button to share files from Talk UI

README.md
> ... but the guys from [Nextcloud VM](https://github.com/nextcloud/vm) *has* developed a script ...
->
> ... but the guys from [Nextcloud VM](https://github.com/nextcloud/vm) *have* developed a script ...
=> Correction of grammar issue

js/views/chatview.js
Requires nextcloud/server#10936 (so if it is not merged in the server this pull request breaks the file picker)
=> Make possible to pick both folders and files

lib/Config.php, tests/php/ConfigTest.php
The temporary username must consist of the timestamp and a random username, see https://github.com/coturn/coturn/wiki/turnserver#turn-rest-api (and https://tools.ietf.org/html/draft-uberti-behave-turn-rest-00#section-2.2) for details on the format.
=> Fix TURN credential generation.

docs/standalone-signaling-api-v1.md
Was previously located at https://github.com/nextcloud/spreed/wiki/Signaling-API, better to keep that in the repository similar to the other API documentation.
cc @mario @Ivansss
=> Add and update API for standalone signaling server from wiki.

css/comments.scss
See nextcloud/server#11258
**Before:**
**After:**
=> Fix position of contacts menu shown on mentions

lib/Manager.php
[As `object_type` and `object_id` are nullable](https://github.com/nextcloud/spreed/blob/29a72c3ededd44ffb44d5bcb02763aabd1f041ea/lib/Migration/Version3003Date20180720162342.php#L41-L50) the row returned by the database can contain a null value in those fields. However, those fields are nullable only due to some Oracle limitations; conceptually they should be empty strings, so an explicit cast to string is now used when creating the room object.
An example of those fields being returned as null could be seen in rooms created in Talk 3.x and then updated to Talk 4.x (although rooms created in Talk 4.x should be fine, as [by default an empty string is stored in the database when the room is created](https://github.com/nextcloud/spreed/blob/1edb5226bb103ba8143a5a5a0cda00f49ccc5d56/lib/Manager …
=> Ensure that "object_type" and "object_id" are strings

js/signaling.js
This can be used by third-party apps to get notified about what happens in a meeting. Also they can use the `BackendNotifier::sendRoomMessage` API to send custom messages to all users in a room which will then be notified through the new events.
=> Trigger events before/after all received signaling messages.

js/models/participantcollection.js, js/views/participantlistview.js
The participant list was rendered again on every collection event, even if nothing had changed; besides being unnecessary it also caused some flickering and it could also cause the participant menu to be suddenly closed while a moderator had it open to perform some action, like promoting another user.
This pull request fixes it so the participant list is rendered again only when something has actually changed. Moreover, instead of rendering the full list only the specific views of the participants that changed are rendered again.
=> Fix rendering of the participant list

js/models/participantcollection.js, js/views/participantlistview.js
=> [stable14] Fix rendering of the participant list

tests/php/Collaboration/Collaborators/RoomPluginTest.php
I forgot to commit this in #1051 :facepalm:
=> Add unit tests for collaborator search

tests/php/Collaboration/Collaborators/RoomPluginTest.php
=> [stable14] Add unit tests for collaborator search

lib/Controller/RoomController.php
This fails with the new type hinting which expects a "IUser" object.
Error is
```
{"reqId":"9M8MFWmKeN2if6H4LCso","level":3,"time":"2018-09-28T12:40:23+00:00","remoteAddr":"10.1.1.31","user":"--","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/room\/p27wbszi","message":"TypeError: Argument 2 passed to OCA\\Spreed\\Controller\\RoomController::formatLastMessage() must implement interface OCP\\IUser, null given, called in \/apps\/spreed\/lib\/Controller\/RoomController.php on line 279 at \/apps\/spreed\/lib\/Controller\/RoomController.php#368","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"15.0.0.0"}
```
=> Allow calling "RoomController::formatLastMessage" without a current user.

css/style.scss, js/views/participantlistview.js
The participant menu is now closed when clicking anywhere once shown; before it was kept shown when clicking on the participant or when performing an action through an item in the menu itself, which was a strange behaviour for a menu.
Moreover, while waiting for the server response after clicking on an item of the menu now the menu toggle is replaced by a working icon; the button is shown again when the operation finishes, either successfully or with a failure. This lets the user know that the operation is still in progress while also preventing her from doing any further operation on that participant while there is one in progress.
=> Fix interaction with participant menu

js/views/callinfoview.js, lib/Controller/RoomController.php
```php
var_dump(true & 1 !== 0); // int(1)
var_dump((true & 1) !== 0); // bool(true)
var_dump(true & (1 !== 0)); // int(1)
```
=> Fix bool logic for inCall flag

appinfo/info.xml, appinfo/routes.php, css/style.scss, docs/api-v1.md, js/app.js, js/views/roomlistview.js, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Migration/Version4099Date20181001123058.php, lib/Notification/Notifier.php, lib/Participant.php, lib/Room.php, tests/php/CapabilitiesTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Controller/RoomControllerTest.php, tests/php/Notification/NotifierTest.php
=> Notification levels

lib/Controller/PageController.php
By default in [Nextcloud 15 the Content Security Policy prevents the use of JavaScript `eval` function](https://github.com/nextcloud/server/commit/5b61ef9213df0ff67ebd5b9c88a8e1562f367351). This is used in several places in Talk, so for now this restriction is lifted until the code is moved away from `eval`.
Note that this only fixes the main UI of Talk; the Settings page and the _Request password by Talk_ UI in the authentication page of shares are currently broken with current server master. The Settings page will be fixed by @rullzer, while the _Request password by Talk_ UI will be fixed later when the rest of the Talk UI is moved away from `eval`.
=> Override default CSP for now to allow JavaScript "eval"

lib/Controller/PublicShareAuthController.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> Better notifications for password shares

js/views/callinfoview.js
The name of rooms for requesting a password by Talk [is generated by the server](https://github.com/nextcloud/spreed/blob/e3d985da600404442973fcf1cb4cd04534cec023/lib/Controller/RoomController.php#L230) each time a room or the list of rooms is fetched, and it should not be editable by the user. Moreover, the `name` attribute is the raw name from which the `displayName` attribute is generated, and thus the later is the one that should be shown for `share:password` rooms.
=> Fix room name in CallInfoView for "share:password" rooms

appinfo/routes.php, docs/api-v1.md, js/app.js, js/views/participantview.js, lib/Capabilities.php, lib/Controller/RoomController.php, tests/php/CapabilitiesTest.php
I want to have the ability to invite groups to a conversation, as well as users. Re-using the existing endpoint sounds sane to me so this is my attempt.
Be gentle! :)
---
Todos:
=> Add ability to invite groups

lib/Controller/PublicShareAuthController.php, lib/Controller/RoomController.php, lib/Notification/Notifier.php
Requires #1267 
Required by nextcloud/server#11875
Regarding Talk the differences between protecting the password of an e-mail share or a link share are minimal; despite that, this pull request is required by the server changes. The reason is that link shares do not have a value in their `sharedWith` field (when got with the OCS enpoint they do, [although it is set by the `ShareAPIController`](https://github.com/nextcloud/server/blob/ea21aa3f7a12c5d1bd80eea329de3eb695fde4e5/apps/files_sharing/lib/Controller/ShareAPIController.php#L211), internally they have none), so without those changes when the room for the link share was created [the name of the room was set to `null`](https://github.com/nextcloud/spreed/blob/f81f5e0a7c17601a039f820b4d0fa59a561fe993/lib/Controller/PublicShareAuthContro …
=> Add support for sending the password for a link share by Nextcloud Talk

js/richobjectstringparser.js, js/views/chatview.js
* Checkout #1078 
* As a guest do a moderator action on a user
* Avatar of the user should be shown :boom: 
* instead the first letter of moderators name is shown on grey background
The avatar always has to use the data from the avatar element and never from the message actor.
=> Fix avatars of users in guest sytem messages

css/comments.scss
=> Fix vertical position of contacts menu on author row

js/views/chatview.js, lib/Chat/Parser/UserMention.php
=> Fix user mentions with spaces

.eslintignore, Makefile, js/admin/signaling-server.js, js/admin/stun-server.js, js/admin/templates.js, js/admin/templates/signaling-server.handlebars, js/admin/templates/stun-server.handlebars, js/admin/templates/turn-server.handlebars, js/admin/turn-server.js, templates/settings/admin/signaling-server.php, templates/settings/admin/stun-server.php, templates/settings/admin/turn-server.php
=> Move admin templates to compiled handlebars

js/views/callinfoview.js, lib/Controller/RoomController.php, lib/Manager.php
Backport #1231 + #1233 
Fix #1283
=> [stable14] Correctly cast the incall flag to integer

js/publicshareauth.js, js/signaling.js, lib/PublicShareAuth/TemplateLoader.php
In the normal Talk UI [the signaling settings are included by the PageController](https://github.com/nextcloud/spreed/blob/3473a762763e98c0813823f801234030db97593e/lib/Controller/PageController.php#L176) in [the HTML returned by the server](https://github.com/nextcloud/spreed/blob/9bc30ef6ba4d0baa422b7aacf8247afda4ad72ab/templates/index.php#L47). However, when Talk is embedded in other pages (like in the public share authentication page) Talk can alter the HTML returned by the server [only to include the JavaScript files that will load its UI in the browser](https://github.com/nextcloud/spreed/blob/e6678362b42ae367fd71d7f34b3d58ce2784ca02/lib/PublicShareAuth/TemplateLoader.php#L74-L108).
When the signaling connection is created, which [is done when the app is …
=> Fix signaling settings not loaded when requesting the password by Talk

js/publicshareauth.js, js/signaling.js, lib/PublicShareAuth/TemplateLoader.php
=> [stable14] Signaling settings not loaded when requesting the password by talk

lib/Share/RoomShareProvider.php, tests/integration/features/bootstrap/SharingContext.php, tests/integration/features/sharing/get.feature
Fixes #1272
The same code as in server. It makes sure we do not return shares that
are in in the trash as this will result in mounting issues.
=> Filter returned shares on accessibility

js/app.js, js/views/chatview.js, js/views/sidebarview.js, js/views/tabview.js
When the chat view was in the sidebar, the scroll position of the chat view was reset to the top every time that the sidebar was closed and opened again or the chat tab was selected after changing to a different one.
The reason is that detaching an element and attaching it again, which happens in both scenarios, resets the scroll position of the element, so now the scroll position is explicitly saved before closing the sidebar or unselecting the chat tab and restored again after opening the sidebar or selecting the chat tab again.
**How to test (scenario 1):**
- Start a call
- Write enough messages in the chat to make the scroll bar appear
- Select the _Participants_ tab
- Select the _Chat_ tab
**How to test (scenario 2):**
- Start a call
- Write enough messages in the chat to make the …
=> Fix the scroll position of the chat view in the sidebar

js/views/tabview.js
=> Fix getting current tab ID when there are no tabs

css/comments.scss, css/style.scss, js/app.js, js/models/chatmessagecollection.js, js/views/chatview.js, js/views/virtuallist.js, lib/PublicShareAuth/TemplateLoader.php, templates/index-public.php, templates/index.php, tests/acceptance/features/bootstrap/ChatContext.php
Requires #1302
It seemed that this day was never going to come, but finally, here it is :-D
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks:  **This pull request is ready for review!!!** :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:
Each time a new element or a group of elements is added to the document the browser needs to layout it (calculate its position and height), but if the elements use a static or relative positioning (they are part of the flow of the document) it needs to reflow the document too (layout other existing elements again that could be affected or affect the new elements).
When joining a room all the chat messages in the room were loaded and added one by one to the document. Each time a new message was added to the list all the other messages …
=> Improve performance of the list of chat messages

js/webrtc.js
Participants without streams were removed from the main call view [in a previous commit](https://github.com/nextcloud/spreed/pull/914/commits/d4929b7525f506a7a0a10bac5c499045751bc696#diff-df9e9621f81056c7ff54db096571cab0R366). However, as those participants are still listening in the call and they can also share their screen even if the have no
microphone or camera now they are shown again like any other participant in the call.
=> Show again participants without streams in a call

js/signaling.js
When setting a room in the internal signaling a poller is started that synchronizes the room data periodically; that poller should be stopped when the room is left.
Note, however, that the poller should not be stopped when leaving the current room if it was initialized for a room collection instead.
- As userA, share a link with the password protected by Talk
- As userB, open the link and request the password to start the call
- As userA, join the room in Talk and then leave so the room is deleted
- As userB, see the developer console of the browser
Once the UI is updated saying that the conversation has ended the requests to the room stop.
Requests to the room go on slowly but endlessly.
@fancycode …
=> Fix room polling not stopped when leaving the current room

css/style.scss, img/share-window.svg, js/app.js, js/publicshareauth.js, templates/index-public.php, templates/index.php
**Before**:
**After**:
When the user is sharing a screen or window:
=> Fix wording and icons for screensharing options

js/views/tabview.js
Internet explorer does not support the `ChildNode.remove()` method, so the node needs to be removed through its parent (which is also supported by the rest of browsers).
- Use Internet Explorer 11
- Login to Talk
- Join a call in a room
The chat view is removed from the sidebar and goes back to the main view.
An error is logged in the developer console and the chat view is not shown again in the main view.
=> Fix "removeTabHeader" on Internet Explorer

js/filesplugin.js
This pull request fixes a bug introduced when `eslint` issues were fixed in #1323 (it complained that a strict comparison was not being used, and now I have remembered why a strict comparison was not being used :-P ).
When the details view is opened for a file the `shareTypes` of the FileInfo are initially strings; they are converted to integers only once the _Sharing_ tab has been opened. Thus, now the `shareTypes` are always "casted" to integers before performing a strict comparison against the `SHARE_TYPE_XXX` constants.
**How to test**
- In the Files app, share a file with another user
- Reload the Files app
- Open the details view for the shared file
**Results with this pull request**
The header of the _Chat_ tab is visible.
**Results without this pull request**
The header of the …
=> Fix Chat tab not shown in Files app if Sharing tab was not opened

lib/AppInfo/Application.php, lib/Room.php
When there was a ping call [the current room was left as soon as the ping returned with an error 404](https://github.com/nextcloud/spreed/blob/db5861e3902bb895e874f911e9e8d2c43e28682a/js/signaling.js#L660-L667).
Since [the ping was removed](https://github.com/nextcloud/spreed/commit/3e326172f7ce6254cd4a1cd980eb1412f809a992#diff-b203a312c79675f92005f11eb2d9a086R583) the current room is left after receiving three signaling errors in a row, each one with a pause of five seconds before the next request.
However, the biggest delay comes from the signaling not being ended when the user is no longer in the room. When a participant is removed or disconnected from a room the `refresh-participant-list` signaling message is added to all the participants in that room. However, the participant just …
=> End pending signaling when user is no longer in the room

css/files.scss, js/app.js, js/connection.js, js/embedded.js, js/filesplugin.js, js/publicshareauth.js, js/views/emptycontentview.js, js/views/mediacontrolsview.js, js/webrtc.js, lib/Files/TemplateLoader.php
=> Add support for video calls to the talk sidebar in files app

lib/Chat/Parser/SystemMessage.php, lib/Chat/SystemMessage/Listener.php, lib/Controller/FilesController.php, lib/Controller/RoomController.php, lib/Exceptions/UnauthorizedException.php, lib/Files/Listener.php, lib/Room.php
=> Persistent join file rooms

css/style.scss, js/views/roomlistview.js
In the room list now rooms for password requests use the password icon and rooms for files use the file icon.
**Before:**
**After:**
@mario @Ivansss Probably something to be updated in the mobile apps too.
@nextcloud/designers
=> Use special icons for rooms associated to objects

.drone.yml, appinfo/info.xml
So that it will work with current server master. Please review @nickvergessen @Ivansss @danxuliu
=> Increase max-version to 16

js/webrtc.js
Previously the screensharing stream was only sent to other participants that had a `video` peer. Participants without a camera/microphone and using the MCU don't have such a peer on the sender side.
How to reproduce:
- Setup standalone signaling / MCU.
- Join call with user A that has camera / microphone.
- Join call with user B that doesn't have camera / microphone (or doesn't allow access).
- Start screensharing with user A.
Before: No screen is visible for user B.
After: User B sees the screen of user A.
=> Send initial screensharing stream to participants that don't publish video.

tests/integration/features/sharing/update.feature
=> Adjust tests to check that updating a received share is forbidden

js/views/templates.js, js/views/templates/richobjectstringparser_userlocal.handlebars
Browsers merge two or more consecutive spaces, even when they are in different elements. Due to this, when there is a trailing space inside a mention it gets merged with the space after that mention, which causes the mention to visually "touch" the following text despite the space between them. To prevent that now all the spaces were removed from the Handlebars template that renders mentions.
**Before:**
**After:**
=> Fix mentions being too close to the following text

js/views/chatview.js
The editable div inserts non-breaking spaces (url encode %C2%A0) after a mention.
When two mentions are right behind each others, the later one is not matched by the
regex later, because the lookahead on the @ finds only non-breaking content.
Manually adding a space in between the two mentions solves this already.
But instead we replace them with normal spaces before sending them to the server.
Fix #1380
=>  Fix multiple mentions which are used directly behind each others 

js/embedded.js, js/filesplugin.js, js/publicshareauth.js
The `EmptyContentView` expects some events to be triggered in the `localMedia` radio channel while waiting for permissions or when WebRTC is not supported to show the proper message.
- Open the Files app in IE 11 or any other browser that does not support WebRTC
- Share a file with another user
- Open the _Chat_ tab for that file and start a call
**Results with this pull request:**
The empty content message reads _WebRTC is not supported in your browser :-/_ and below it _Please use a different browser like Firefox or Chrome_
**Results without this pull request:**
The empty content message reads _Waiting for userXXX to join the call  …_
=> Fix empty content message in Files app when WebRTC is not supported

css/style.scss
**Before, edit button:**
**After, edit button:**
**Before, input field:**
**After, input field:** (hard to see, but now the elements below it are not moved when the input field is shown)
=> Fix position of input and edit button for room name

css/style.scss, js/views/callinfoview.js
As the rooms associated to a file are also shown in the regular Talk UI now an icon is shown next to the room name to easily go to the file when clicking on it.
For consistency with the server and between the room list and the new icon [the icon in the room list for rooms associated to a file](https://github.com/nextcloud/spreed/pull/1346) is now the _text_ icon instead of the _file_ icon.
@nextcloud/designers
=> Add icon to go to the file associated to a room

css/style.scss, js/views/tabview.js
In Nextcloud 15 icons were added to the tab headers in the sidebar; due to the shared CSS rules this broke the position of icons in the tab headers of Talk.
For consistency with the server, the tab header icons were not fixed to their previous position (to the left of the label), but to the same position used in the sidebar of the server (above the label).
=> Adjust tab header icons to changes in server

css/files.scss, js/filesplugin.js, lib/Controller/FilesController.php, lib/Files/Listener.php, lib/Files/Util.php
Fixes #1338 
Before rooms for files could be created only for files that were explicitly shared. Now, if a file is inside a shared folder, a room can be created for that room too even if the file itself is not explicitly shared. In that case the room is accessible to the same users that can access to the shared folder; if the file is later shared with someone else that user will be able to join the room too.
Unfortunately, the FileInfo that is used in the Files app to know whether a file is shared or not does not provide information about files that are inside a folder shared by the current user (although it does when the files are in a folder shared by a different user to the current user). When that information is not available now a query is made to the server to get that information. …
=> Make rooms for files in shared folders accessible to shared folder users

css/authenticate.css, css/chatview.scss, css/style.scss
The opacity of the submit button for the room name now follows the opacity of the submit button to send new messages (low opacity by default, full opacity when hovered, focused or active).
Additionally, the opacity of the submit button is slightly increased when its input field is focused; this was made to hint that when the input field for the room name is focused pressing enter sets the room name without having to explicitly click on the submit button, although I am not sure if this is a good approach or not. In any case I added it in a separate commit to be easily dropped or reverted if needed ;-)
**Update:** all this was done too for the submit buttons of guest names, passwords, password in the authentication page and new chat messages.
@nextcloud/designers 
**Before:**
**After, …
=> Fix opacity of submit buttons

css/style.scss
Follow up to #1387
After moving the room name into a flex container the room name input no longer expanded to fill the whole width of the sidebar.
=> Fix room name input width

lib/AppInfo/Application.php
This is just a workaround that fixes #1408, the cleaner solution should be to get the list of session ids from the event and pass it along to the signaling server.
=> Pass empty list of session ids when notifying about removed guests.

lib/AppInfo/Application.php, lib/Notification/Hooks.php
@jancborchardt now I got what you meant, this does now:
* Remove "{actor} invited you to {conversation}" notification when the user opened the conversation
* Remove "{user} wants to talk with you"/"A group call started in {conversation}" notification when the participant joins the call
The notifications already vanished when you clicked on them directly instead of going to the place yourself or used an app.
Ref https://github.com/nextcloud/notifications/issues/250
=> Remove notifications when they are done

js/app.js, js/connection.js
Fixes #1445 
Also fixes the browser history in the main Talk UI in these two scenarios:
**Scenario 1:**
- Join conversation 1
- Join conversation 2
- Go back in history
Result with this pull request:
It is possible to go forward in history to the conversation 2 again.
Result without this pull request:
It is not possible to go forward in history.
**Scenario 2:**
- Join conversation 1
- Join conversation 2
- Leave conversation 2
- Go back in history
Result with this pull request:
Conversation 1 is loaded.
Result without this pull request:
The whole Talk UI is reloaded.
=> Fix browser history

js/app.js
**Scenario 1**
- Create a new room / Open in a room as a moderator
- Change room name
The page title is updated with the new name.
The page title keeps showing the old name.
**Scenario 2**
- Join a room
- Leave or delete the room
The page title is set to the default Talk title.
The page title keeps showing the name of the left or deleted room.
=> Fix page title not updated when room name is updated

css/publicshareauth.scss
**Before:**
**After:**
**Before:**
**After:**
=> Fix submit button in public share authentication page

js/views/chatview.js
In order to show the autocompletion it was needed to type at least another character after _@_, so only the mentions that matched that character were shown. Now the autocompletion is shown as soon as _@_ is typed, which shows all the possible mentions in the room.
=> Show autocompletion as soon as "@" is typed

lib/Chat/Parser/SystemMessage.php, tests/php/Chat/Parser/SystemMessageTest.php
Fix #1473
The old comparision was checking the current user vs the current session-user (the same, kk-thx-bye)
=> Correctly compare the correct user to the owner

lib/Share/Helper/ShareAPIController.php, tests/integration/features/sharing/get.feature
The display name of reshares with one-to-one rooms not invited to was always set to the display name of the last participant. However, this happens since 4afa2d7946f121d07610eeb0165b20ee135fb819; before that the first participant was always used. Now the name of both participants in the room is used instead, which also fixes the integration tests that were broken in 4afa2d7946f121d07610eeb0165b20ee135fb819.
=> Fix display name of reshare with one-to-one room not invited to

lib/Files/TemplateLoader.php
Fix #1489 
No problem in master, because this is allowed and valid in 7.1+, but 15 still supports 7.0 where it fails.
=> Cannot use OCP\Util as Util because the name is already in use

lib/Share/Helper/ShareAPIController.php, tests/integration/features/sharing/get.feature
Follow up to #1426 
Views:
* Black - Owner of the files
* White - Owner of the rooms
Shares:
* Shared to room "Playdowns"
* Shared to room without a name set
* Shared in one-to-one conversation between test1 and test2
> ![bildschirmfoto von 2019-01-30 12-14-09](https://user-images.githubusercontent.com/213943/51977815-c02f7a80-2488-11e9-8979-133ee7035f1a.png)
=> Do not show room names when the user is not part of it

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/PublicSharePasswordRequestContext.php, tests/acceptance/features/public-share-auth.feature
[The last scenario fails when the acceptance tests are run without any timeout multiplier](https://github.com/nextcloud/spreed/commit/ad26f2ce9b0ff1b43582b65c93cae7efbf7d22c7#diff-c8c885284913c6339176f4ce788ece13R78); this is not a problem when run in Drone, as a multiplier is used in that case which causes the tests to wait for longer for the conversation to be finished.
The scenario will pass without requiring a timeout multiplier once #1342 is fixed.
=> Add acceptance tests for requesting the password of a link share

css/files.scss, css/style.scss, css/video.scss, js/filesplugin.js
Follow up to #1485
This pull request fixes:
- The video buttons in the public share authentication page and in the Files app
- The navigation toggle during a call in the main Talk UI with dark mode
- The close button during a call in the Files app with dark mode
- The shadows on icons forced to white colour
=> Fix the fix for icons in dark mode

css/publicshareauth.scss, css/style.scss
This pull request fixes the edit button for guest names in public chats and in the public share authentication page, and the input for guest names in the public share authentication page.
**Edit button, before:**
**Edit button, after:**
**Input, before:**
**Input, after:**
=> Fix editable text label for guest names

lib/Controller/CallController.php, lib/Controller/RoomController.php, tests/php/Controller/RoomControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
This requires adjustment in the android app, as it breaks the conversation info.
The information should be fetched after joining the conversation only.
=> Remove room information for users which are not a participant 

js/views/chatview.js
Navigate with Arrow-Up and Arrow-Down through the last messages you sent.
> ![messagenavigation](https://user-images.githubusercontent.com/213943/52411472-4f1d4200-2adc-11e9-941e-8638adf9f901.gif)
This is especially helpful with #1453  where you can not always copy the last message you where typing.
=> Allow to repost the last comment

lib/Controller/SignalingController.php
When a user requests the signaling messages from the internal signaling server first the last ping of the user is updated. Then, after waiting for at most 30 seconds, the list of users active in the room is returned.
That list was based on the users whose last ping was more recent than 30 seconds ago, so when there were no other messages and the waiting timed out the last ping of the current user set when the request started happened 30 seconds ago or more, and thus the current user was not included in the returned list... unles her ping was updated to a more recent value by a different request.
[Requesting the chat messages also updates the last ping of a user](https://github.com/nextcloud/spreed/blob/c75d82525f665e6e373c56605da0e92401ca2ef7/lib/Controller/ChatController.php#L289), which …
=> Fix current user not included in user list returned by signaling

js/webrtc.js
In some circumstances (for example, [if the signaling server provides an incorrect list of users](https://github.com/nextcloud/spreed/pull/1534)) the peer that created the offer can disconnect from the peer that received the offer without causing the peer that received the offer to remove the peer that created the offer.
In that situation, if the peer that created the offer then tried to connect again with the other peer [the other peer created a new `Peer` object](https://github.com/nextcloud/spreed/blob/05905d1972ae35e011ff41c17a914d28bf551140/js/simplewebrtc.js#L18033-L18040) that was used instead of the old one (because the peer that created the offer [removed its original "Peer" object](https://github.com/nextcloud/spreed/blob/339b1dfc05e3ff01c89f58757febb7a7fa97e887/js/webrtc.js#L205 …
=> Fix peer creation when wrong user list was sent to the other peer

lib/Controller/SignalingController.php
Follow up to #1522
When a user requests the signaling messages from the internal signaling server first the last ping of the user is updated. Then, after waiting for at most 30 seconds, the list of users active in the room is returned.
That list was based on the users whose last ping happened around 30 seconds ago or less (it could be a bit longer than 30 seconds, but the described problem remains in that case too); if other user pulled the messages slightly before the current user and that other user did not pull the messages again (or the chat messages, as that updates the last ping too) before the user list was returned that other user was not included in the list, as her last ping happened more than 30 seconds ago.
Now the elapsed time since the last ping for users returned in the …
=> Fix slower active users not included in user list returned by signaling

lib/Controller/SignalingController.php
Follow up to #1543 
`private const` is only valid starting with PHP 7.1.
=> Fix "private const" on PHP 7.0

lib/Room.php
Follow up to #1532  
Otherwise, due to the strict types, a type error is thrown instead of a `ParticipantNotFoundException`.
@nickvergessen Is it needed to change the PHPDoc of [`getParticipant`](https://github.com/nextcloud/spreed/blob/d702aa08415ff8c664b35b1767a55ebad9ddaeba/lib/Room.php#L179) and [`getParticipantBySession`](https://github.com/nextcloud/spreed/blob/d702aa08415ff8c664b35b1767a55ebad9ddaeba/lib/Room.php#L214) from `@param string xxxId` to `@param string|null xxxId`?
=> Allow null sessions when getting participant by session

js/views/mediacontrolsview.js
This pull request fixes a regression introduced in c4c047a3c1a4bc5a622f49880f0b77cd00b2f55c
- Start a call with microphone and camera
- Disable local audio and video
- Reload the page in the browser
- Start a call again
Audio and video are still disabled.
Audio and video are enabled.
=> Fix last local media state not remembered when the UI is reloaded

js/signaling.js
We had 648 log entries for this in sentry since dec 2018:
> ### TypeError
> this.socket is null
=> Delay message sending when socket is null

js/models/room.js
Fix #1537 
Actual fix is https://github.com/nextcloud/server/pull/14178 but we can't help that.
This PR just fixes a follow up problem that occurs afterwards.
> Uncaught TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at n.setEmptyContentMessageWhenWaitingForOthersToJoinTheCall (VM2488 emptycontentview.js:174)
=> Ensure all properties of rooms are set

js/webrtc.js
Fixes #1559
Follow up to #1533
When a screen is shared a new offer is sent, just like when a video (or audio only) connection starts; any offer coming from the same peer has the same id, even if the type of the offer is different and separate Peer objects are created for each offer. Due to this now a peer is stale only if both the id and type of the new offer matches an existing peer; otherwise when the screen offer was received the video peer was seen as stale and removed.
Besides fixing #1559 the first commit also addresses the issues from #1533 but for shared screens instead of videos. However, there is still a pending issue: if the signaling returns a wrong user list to the user A causing it to disconnect from user B while user B is sharing the screen, when user A reconnects only …
=> Fix removal of stale peers when a screen is shared

css/chatview.scss, css/style.scss, js/views/chatview.js, js/views/richobjectstringparser.js, js/views/templates.js, js/views/templates/richobjectstringparser_call.handlebars, lib/Chat/Notifier.php, lib/Chat/Parser/UserMention.php, lib/Controller/ChatController.php
`@all` now creates a notification for everyone and shows up as `<group icon> Everyone` in the chat.
Known issues: In the notification the avatar is `E` for everyone, instead of the group icon. But that would require fixing in the notifications app, and I'm not sure what the best way for this is atm. We could go with ROS group instead of user, but that would complicate the JS on our site a lot, because we would need to render those two the same and even then the icon would not be shown in the notification.
Fix #1412
=> Allow to mention everyone in the conversation 

js/app.js, js/embedded.js
- Create a room and add five or more participants to it
- Create another room with no participants, start a call and enable the video (to guarantee that the last call used had video enabled and thus the next call will have it enabled too, as the setting is remembered)
- Reload Talk UI
- Enter the room with five or more participants
- Start a call in the room with five or more participants
Local video is disabled.
Local video is enabled.
=> Fix disabling video when joining a call in a room with more than five participants

css/chatview.scss
The div needs to be inline-block, so Chrome/Chromium correctly insert
div-ed multi-line-text with new lines.
Otherwise they are just chained together on posting.
See https://stackoverflow.com/a/24689420
Fix #1561
=> Allow multiline text insertion in chrome

lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/Listener.php, lib/Room.php, tests/php/Signaling/BackendNotifierTest.php
The removeParticipantBySession function is called when a user is removed by a moderator and also when the user leaves by themselves, for a hook that performs an action when a user is removed there needs to be a flag to indicate that the moderator removed the user.  I have added a $reason parameter which can be 'remove' for a moderator and 'leave' if the user just left.
=> Add reason for removing participant from room

js/webrtc.js
This pull request fixes a regression introduced when the [support for the MCU was added](https://github.com/nextcloud/spreed/commit/1060fb8c) (Talk 4.0).
I have fixed the issue when there is no MCU, but it seems that it is also present when a MCU is used (at least, based on a test I made in our company instance it is present in latest release, so I guess it is present in master too).
@fancycode @Ivansss Could you fix this when a MCU is being used too? I am not confident enough to mess with the MCU related code without having a local MCU to test against it ;-) Thanks a lot :-)
One thing to keep in mind: when a MCU is used the `Peer` object that represents the screen received from the remote peer has `sharemyscreen` set to `true`, just like the `Peer` object that represents the local screen …
=> Fix sharing own screen when other peer is sharing the screen

lib/Controller/SignalingController.php, lib/Room.php, tests/php/Controller/SignalingControllerTest.php
It could happen that an old session id expired while a user already re-joined a room with a new session id. Once the old session id expired, the user got removed from the room.
Original report by @danxuliu against the standalone signaling server:
-----
- Log in as a user in Nextcloud
- Open the Talk app
- Enter a room
- Reload the page in the web browser
- Wait around 10 seconds
The user is shown as active in the list of participants.
The user is shown as not active in the list of participants. When the user changes from active to inactive the signaling server logs show Closing expired session; although this is followed by Removed session and the ID of the expired session it seems that something else changes and causes the user to be no longer active in the room.
-----
My feedback
A …
=> Fix removing users when an old session id expires in the signaling server.

docs/api-v1.md, js/models/room.js, js/views/roomlistview.js, lib/Controller/RoomController.php, lib/Room.php, tests/acceptance/config/behat.yml, tests/acceptance/features/conversation.feature, tests/integration/features/conversation/delete-room.feature, tests/integration/features/conversation/one-to-one.feature, tests/integration/features/conversation/remove-participant.feature
> * Delete - is only available to logged in moderators and owners
> * Leave - is always shown, when Delete is not shown, or
when there are other other users and it's not one-to-one
Fix #1435
=> Adjust the logic for delete/leave buttons

js/views/emptycontentview.js
Follow up to #1588 
Before, deleting a room and removing oneself from a room had the same behaviour: if the room was the active one it was first left and, then, the room was destroyed. However, while that still happens when deleting a room, [when removing oneself from a room now the room is first destroyed and, then, the room is left](https://github.com/nextcloud/spreed/blob/a49db6a8053e0e015b4648421a35c2e2594c4762/js/models/room.js#L113-L132); as destroying the room can be rejected by the server it is necessary to wait until the room is destroyed to leave it and update the UI accordingly.
The empty content view expected that a room was always left before being destroyed, so the change in the order of events caused that when the room was destroyed the initial message was set, but when it …
=> Fix empty content message when leaving a room

.l10nignore
=> Ignore generated and minified JS files during l10n sync

js/views/chatview.js, js/views/templates.js, js/views/templates/richobjectstringparser_filepreview.handlebars, lib/Chat/Parser/SystemMessage.php, tests/php/Chat/Parser/SystemMessageTest.php
Left after, right before (size change is unrelated, I zoomed on screenshots to match more icons on a screen)
> ![bildschirmfoto von 2019-03-07 20-31-10](https://user-images.githubusercontent.com/213943/53984021-c31d2b00-4118-11e9-8ab2-96a3c76dfdc8.png)
=> Use the preview information for better fallback icons

js/views/videoview.js
This pull request fixes the video shown behind the avatar (or the avatar shown in front of the video, as you prefer) for a few moments after establishing a connection with a video peer in a call.
It happened because both the avatar and the video element were visible after establishing a connection and before receiving through the data channel whether the video was available or not (which shows and hides the avatar and video as needed).
=> Fix remote video visible behind avatar before being explicitly shown

js/webrtc.js
See https://webrtc.org/web-apis/chrome/unified-plan/ for details.
"Unified Plan" is starting to be the default with Chrome 72 but is not supported completely by the MCU with SimpleWebRTC yet.
=> Force "Plan B" semantics with the MCU.

lib/Controller/PageController.php
Regression from nextcloud/server#14626
* Try to join a public conversation as a guest
=> Fix hardcoded `/call/{token}` handling

docs/api-v1.md, js/views/callinfoview.js, js/views/participantview.js, js/views/roomlistview.js, lib/Capabilities.php, lib/Chat/AutoComplete/SearchPlugin.php, lib/Chat/SystemMessage/Listener.php, lib/Controller/CallController.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Room.php, tests/acceptance/features/conversation.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/callapi/one-to-one.feature, tests/integration/features/chat/one-to-one.feature, tests/integration/features/conversation/one-to-one.feature, tests/integration/features/conversation/remove-participant.feature, tests/integration/features/sharing/hooks.feature, tests/integration/features/sharing/sharees.feature, tests/php/CapabilitiesTest.php
The idea is to make one-to-one rooms persistent:
* No more guests allowed
* You can not add people to it
* You can only leave it, not delete it
If the second user:
* leaves: the room is deleted
* posts a chat message: participant 1 is readded
* starts a call: participant 1 is readded
This prevents misunderstandings like #1528 and is also more in line with the behaviour of other messengers.
=> Persistent one-to-one rooms

css/video.scss, js/views/videoview.js
When a remote peer is added its remote stream is attached to a new video element (even if the remote peer is audio only). Immediately after [that the video element is hidden](https://github.com/nextcloud/spreed/blob/a3a711626ecc2b622228880d7fa2b784ebdf37bc/js/views/videoview.js#L198), and it is kept hidden until an unmute message for the video is received.
Sometimes ([mostly reproducible with Safari](https://github.com/nextcloud/spreed/pull/1524)) even if the remote audio was being received no audio was played if the video element was hidden; in those cases showing the video element (for example, by removing `display: none` from the video element with the developer tools of the browser) caused the audio to start playing (even if there was no video being received).
The issue only happened …
=> Fix hidding video causing audio to not be played

tests/php/Signaling/BackendNotifierTest.php
To allow using the server again afterwards
=> Reset the signaling server settings after unit tests

js/filesplugin.js
- Setup an MCU
- In the Files app, as user A share a file with user B
- Open the Chat tab for the file
- In the Chat tab, start a call as user A
- In the Chat tab, join the call as user B
- Trigger an ICE failure so there is a reconnection (for example, by running one of the browsers in another machine and unplugging and plugin again the cable)
After the reconnection the UI is as expected.
After the reconnection there is a duplicated call button
=> Fix duplicated call button when joining the same room again in Files app

js/signaling.js, js/webrtc.js
(The test steps may not be accurate, so sorry :-P; I am writing them from memory, but I have no time to check them if I want to get the train :-P )
- Setup an MCU
- Start a call as user A
- Join the call as user B
- Trigger an ICE failure so there is a reconnection (for example, by running one of the browsers in another machine and unplugging and plugin again the cable)
One of the users left the call and joined again to make the reconnection; both users can see and hear each other.
One of the users left the call and joined again to make the reconnection; the user who joined again can see and hear the other user, but the user who was kept in the call can not see nor hear the user who reconnected.
- Do not use an MCU …
=> Fix stopping local media when leaving a call

css/publicshareauth.scss, css/video.scss, js/embedded.js, js/merged-share-auth.json, js/publicshareauth.js
This is just a refactoring, so everything should work in the public share authentication page as before.
=> Base "PublicShareAuth" on "Embedded" instead of on "Application"

lib/Chat/Notifier.php
Users are added on mentions in file-rooms,
so they can see the room in their room list and
the notification can be parsed and links to an existing room,
where they are a participant of.
=> Add users to file rooms on mentions

tests/integration/features/sharing/move.feature
This was fixed in https://github.com/nextcloud/server/pull/14691 but should actually have never worked.
=> Dont allow to move mountpoints into mountpoints

js/signaling.js
The RTCSessionDescription removes custom payload attributes in it's toJSON
method. The one value we set is the nick, so we need to toJSON and toObject
the description and add the nick to the payload again.
https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription/toJSON
=> Readd the nick to the payloads of offer/answer

js/webrtc.js
Remove video constraints when creating SimpleWebRTC.
Safari 12.1 doesn't seem to like maxHeight and maxWidth constraints and fails getting local media.
Removing these constraints for now, but we should figure out a way to select video resolution.
=> Remove video constraints.

CHANGELOG.md, appinfo/info.xml, package.json
- Administrators can now define commands which can be used in the chat. See [commands.md](https://github.com/nextcloud/spreed/blob/master/docs/commands.md) for more information  [#1453](https://github.com/nextcloud/spreed/pull/1453)
- `@all` mentions all participants in the conversation  [#1531](https://github.com/nextcloud/spreed/pull/1531)
- Allow to get the last sent message again with `arrow-up`  [#1520](https://github.com/nextcloud/spreed/pull/1520)
- Conversations associated to files now have a link to the file  [#1387](https://github.com/nextcloud/spreed/pull/1387)
- The Talk app can now be restricted to a group of users in the Talk administration settings  [#1585](https://github.com/nextcloud/spreed/pull/1585)
- Show a warning when a call has many participants and no external …
=> v6.0.0 - Changelog + Version bump

css/video.scss
Before:
After:
- Force [`setConnectionStatus`](https://github.com/nextcloud/spreed/blob/e928527ff421cbe4e969d70b2986cec062695fe6/js/views/videoview.js#L127) to always set the failed status with `connectionStatus = ConnectionStatus.FAILED_NO_RESTART;` (or wait patiently for several ICE failures in a row... but this dirty hack is faster ;-) ).
- Start a call with one user
- Join the call with another user
The ICE failed indicator icon shown above the other peer name is white.
The ICE failed indicator icon shown above the other peer name is black.
=> Fix ICE failed indicator icon not forced to white in call

tests/integration/run-docker.sh
Copy of nextcloud/server#14737
=> Ignore node modules when running integration tests in Docker

css/style.scss
The pointer cursor should be used on clickable elements, but clicking on a selected tab header has no effect, so now the default cursor is used instead.
This is Talk specific; for example in the _Files_ app clicking on some tab headers when they are selected does nothing while clicking on others when they are selected reloads the tab. Due to this the CSS was modified here [instead of in server](https://github.com/nextcloud/server/blob/15ae6338644d90a2a8d633892fd0b78acee97576/core/css/apps.scss#L824).
**Before, tab selected:**
**Before, tab not selected:**
**After, tab selected:**
**After, tab not selected (no changes):**
=> Fix cursor on selected tab header

lib/Chat/AutoComplete/SearchPlugin.php, tests/integration/features/chat/mentions.feature
Requires #1676 and #1677 ~~(I will rebase on master the last two commits of this pull request once those two pull requests are merged)~~.
In regular rooms only the current participants are candidates in mentions, but in file rooms the candidates are all the users with access to the file, even if they are not currently participants of the room. However, as the users with access to the file are a superset of the current participants those participants were returned twice. Therefore, now candidates for mentions in file rooms are got only from the users with access to the file instead of in addition to the current participants.
- In the Files app, share a file with another user
- Open the Chat tab for that file
- As the other user, open the Chat tab for the file (so the user joins the room …
=> Fix duplicated candidate mentions in file rooms

tests/integration/features/sharing/get.feature
See https://github.com/nextcloud/server/pull/14605 for more information
=> Resharing behaviour has been adjusted for 16

css/publicshareauth.scss
=> Fix links style in Talk sidebar in public share auth page

css/publicshareauth.scss, js/views/templates.js, js/views/templates/chatview_add_comment.handlebars
Fixes #1541 
This only happens when requesting a password by Talk with a logged in user; guests are fine.
**Before, user:**
**Before, guest:**
**After, user:**
**After, guest (no changes):**
=> Fix misplaced chat view in public share auth page

css/style.scss
Follow up to #1697 
This can be tested by opening a conversation as a guest.
**Before:**
**After:**
=> Remove empty space when the "Add" button is not shown in the sidebar

js/app.js
Fixes a regression introduced in a85b5338834c70
- In a different browser, join the public conversation as a guest
- In the original browser, with the owner of the public conversation, promote the guest to moderator
The sidebar in the guest UI is updated to show the _Participants_ tab.
The guest UI does not change.
=> Do not show the CollectionsView when the participant list is shown

js/views/participantlistview.js
- As user A, create a group room and add user B and user C to it
- In a different browser, join the room with user B
- As user A, promote user B to moderator
The UI is updated for user B, and user B can now moderate user C.
The UI is partially updated for user B, but user B needs to reload the page to be able to moderate user C.
=> Fix participant actions not updated on current participant type changes

lib/Controller/PageController.php
Requires #1706 (I will rebase once it is merged).
Talk no longer uses JavaScript "eval", so the Content Security Policy [can now be configured to prevent its use](https://github.com/nextcloud/spreed/pull/1253).
=> Do not allow JavaScript "eval"

lib/Manager.php, lib/Share/Helper/ShareAPIController.php, tests/integration/features/bootstrap/SharingContext.php, tests/integration/features/sharing/create.feature, tests/integration/features/sharing/get.feature, tests/integration/features/sharing/transfer-ownership.feature
=> Remove conversation names and tokens from reshares when you are not a participant

CHANGELOG.md, README.md, appinfo/info.xml, js/views/chatview.js, lib/Chat/Changelog/Manager.php, lib/Command/Command/Add.php
---
- Administrators can now define commands which can be used in the chat. See [commands.md](https://github.com/nextcloud/spreed/blob/master/docs/commands.md) for more information. You can install some sample commands via the console.  [#1453](https://github.com/nextcloud/spreed/pull/1453)  [#1662](https://github.com/nextcloud/spreed/pull/1662)
- There is now a "Talk updates" conversation which will help the user to discover some features  [#1616](https://github.com/nextcloud/spreed/pull/1616)  [#1662](https://github.com/nextcloud/spreed/pull/1662)
- `@all` mentions all participants in the conversation  [#1531](https://github.com/nextcloud/spreed/pull/1531)
- Allow to get the last sent message again with `arrow-up`  [#1520](https://github.com/nextcloud/spreed/pull/1520)
- Conversations …
=> Final release

js/views/collectionsview.js, js/views/templates.js, js/views/templates/collectionsview.handlebars
Follow up to #1707 
The underscore template must be precompiled now that JavaScript "eval" is not allowed by the Content Security Policy; otherwise the main Talk UI (where the CollectionsView is used) fails to load properly (the _New conversation_ dropdown is not shown).
=> Move underscore template to precompiled Handlebars template

css/style.scss
The default height for input elements, as well as the confirm icons inside them, [has been changed in server to 34px for Nextcloud 16](https://github.com/nextcloud/server/commit/250352012113432e000523170c1874f9afe0ef74); this pull request adjusts the room name input to that new height.
**Before:**
**After:** (hard to see, but now the elements below it are not moved when the input field is shown)
=> Adjust room name input to default height for inputs from server

css/style.scss
This pull request fixes some structure issues in Internet Explorer 11 (the sidebar appearing behind the header and the chat view not stretching to fill the area of the navigation bar in fullscreen); the CSS changes should not affect any other browser except Internet Explorer.
=> Fix sidebar and fullscreen in IE11

js/app.js, js/embedded.js, js/simplewebrtc/bundled.js, js/simplewebrtc/getscreenmedia.js, js/simplewebrtc/localmedia.js, js/webrtc.js
The first commit fixes a regression introduced in #1524. In [LocalMedia v3 it is no longer checked if `getUserMedia` is available before using it](https://github.com/otalk/localmedia/commit/4e2b762f2657f56e00b2ad310f27b983869518a8#diff-e77e08357daa2faadc3f58fce7b6b452L51) (it was done [internally by getUserMedia](https://github.com/otalk/getUserMedia/blob/7ce6444ca9d6cd2c7b67497a14c5dbafef4c3383/getusermedia.js#L20)), so an explicit check was added and an error is thrown if not (just like it was done before).
Note that if there is an ongoing call Internet Explorer 11 still tries to join the call and is shown to other participants, even if WebRTC is not supported; the commit only ensures that the proper message is shown. Fixing this to prevent Internet Explorer to join would require deeper …
=> Fix WebRTC not supported handling

js/simplewebrtc/bundled.js, js/simplewebrtc/getscreenmedia.js, js/simplewebrtc/simplewebrtc.js, js/views/mediacontrolsview.js
The standard `getDisplayMedia` is now used whenever available, although the old behaviour is kept for backwards compatibility.
Note that `getDisplayMedia` spec [forbids limiting the display sources to be chosen by the user](https://w3c.github.io/mediacapture-screen-share/#mediadevices-additions), so the split menu to choose between window and screen is no longer shown in Firefox >= 66 (and, even if the old API was used, it would be useless, as for consistency with the spec [the old `getUserMedia` constraints no longer work](https://bugzilla.mozilla.org/show_bug.cgi?id=1474376)).
This can be tested by sharing the screen in Firefox >= 66, Chromium >= 72 and Edge >= 18 (and also older versions of Firefox and Chromium to check that they still behave as expected).
@Ivansss Could you please …
=> Prefer standard API for screen sharing

js/signaling.js, js/simplewebrtc/bundled.js, js/simplewebrtc/peer.js
This pull request fixes a regression introduced in c02c8c08, as well as the regression introduced in 9f1212ab that it fixed.
Not all the call messages contain a payload, so when a message without payload was tried to be sent an error happened. Instead of checking that and keep the special handling in the signaling object now `sendCallMessage` assumes again that the given payload is serializable as is, so the special cases are handled by the (indirect) callers of `sendCallMessage`.
- Start a call with user A
- Join the call with user B
The user names are shown for the peers in the call screen.
The user names are not shown for the peers in the call screen.
- Start a call with user A
- Join the call with user B
- Share the screen with any user
- Stop sharing the screen*
* It could be tested …
=> Fix signaling messages with no payload and with unserialized attributes

js/simplewebrtc/bundled.js, js/simplewebrtc/simplewebrtc.js
Requires #1738 
This pull request fixes a regression introduced in #1524.
In the old LocalMedia module bundled in the official SimpleWebRTC 2.2.3 [the local screen was not removed before `localScreenStopped` was emitted](https://github.com/nextcloud/spreed/blob/9b082ea8894f54ebd58e0408009ab3f4a5b9b720/js/simplewebrtc.js#L7618-L7624). However, in the current LocalMedia module [it is](https://github.com/nextcloud/spreed/blob/master/js/simplewebrtc/localmedia.js#L286-L287), so `SimpleWebRTC.stopScreenShare` was never called when the screensharing was stopped from the browser (instead of from the Talk UI itself), and thus the Talk UI was not updated neither locally nor for the remote peers.
- Start a call
- Join a call with another user
- Stop sharing the screen with the …
=> Fix stopping screensharing from the browser

lib/Manager.php
This is only a temporary solution. We should try to find out where the rooms origin from
and then either delete them all together, or fix them.
But since they have no token, you can't join them anyway
and therefor wont miss them for now.
Fix #1741
=> Do not "load" conversations without a token

js/webrtc.js
Fixes #1736 
Regression introduced in bff77f9f3fbe74ebd629cd9810dcdffdcc09e30b
Despite its name, `usersInCallMapping` includes all the users in the room, not only those currently in the call. Therefore, when iterating through it, it should be checked whether a user is in the call or not to prevent sending the screensharing offer to peers not in the call.
Note that it is still possible (although highly unlikely) that if a user shares the screen at the same time that another user lefts the call the user that left the call receives the screensharing offer (as the first user would not be aware yet that the second user left the call, so the offer would be sent). This would turn the chat background black for the second user as described in #1736, as once a user lefts a call the signaling events …
=> Fix screensharing offer sent to peers not in the call

js/webrtc.js
Replaces #1739 (as the branch name matched a protected pattern and thus it could not be force pushed to fix an eslint issue).
Backport of #1569
The automatic backport had failed because #1554 was never merged; unfortunately this slipped and currently screen sharing is broken (or, at least, flaky) in _stable15_.
=> [stable15] Fix removal of stale peers when a screen is shared

js/webrtc.js
Replaces #1740 (as the branch name matched a protected pattern and thus it could not be force pushed to rebase).
Backport of #1571
=> [stable15] Fix sharing own screen when other peer is sharing the screen

js/webrtc.js
This fixes a regression introduced in 31cc6de8e8a78440e585c5d4d3aed117a54ee110
Once a result was found all the following stats that had `bytesReceived` were checked, even if their media type did not match. However, note that, while incorrect, this did not cause any practical issue, as the first time that the peer was unmuted the proper stat was checked, and the following incorrect checks just unmuted again an already unmuted peer.
Note that #1583 is NOT fixed by this. Even if joining a call using the MCU with audio and video disabled sometimes works as expected (that is, remote peers see audio and video disabled for the peer that has joined) it is just luck; simply [the audio/video on/off information sent when the connection is completed](https://github.com/nextcloud/spreed/blob/45a66bffcf …
=> Fix condition to ignore stats in "checkMediaPeer"

css/authenticate.css
Since nextcloud/server#14468 the server explicitly sets [the height of confirm icons inside password inputs](https://github.com/nextcloud/server/commit/250352012113432e000523170c1874f9afe0ef74#diff-5e3a8038f073563d61e06df777f2ddb4R257), which overrides [the height set in Talk for submit inputs in the authenticate page](https://github.com/nextcloud/spreed/blob/173e06508cbdb3a708010772aaa4a259d64fce25/css/authenticate.css#L43). Therefore, the height set by the server needs to be overriden to honour the height set in Talk (which matches [the height of the password input in the authenticate page](https://github.com/nextcloud/spreed/blob/173e06508cbdb3a708010772aaa4a259d64fce25/css/authenticate.css#L8)).
**Before**
**After**
=> Fix vertical position of confirm icon in authenticate page

templates/index-public.php, templates/index.php
Avoids warnings in the log about not finding files.
Should probably be backported as well.
=> Select2 is in the main dist file

js/signaling.js, lib/Controller/ChatController.php, tests/integration/features/chat/commands.feature
Fixes #1797, which is a regression introduced in #1453 
When fetching chat messages `ChatController` may not return as many messages as requested. In the past this meant that there were no more messages in the room, but since the introduction of commands [some messages may not be returned because they should not be visible to the participant fetching them](https://github.com/nextcloud/spreed/blob/f1667ac2f77cc56d8e5e69eac0e4f28fd2c5187e/lib/Controller/ChatController.php#L238-L240). Thus, now the number of returned messages does not mean anything regarding whether there are still more messages in the room or not, but this can be known by looking for a `304 Not modified` response (which is only sent when there are no more messages in the room).
When no MUC is used the chat messages are …
=> Fix messages not loaded when commands are used with the MCU

js/app.js, js/connection.js, js/embedded.js, js/signaling.js, js/webrtc.js
Follow up to #1059, #1631 and #1649
The signaling object should not directly modify the UI, and it should not directly perform the handling needed by other parts of the code when pulling messages stops due to repeated failures (an event should be triggered instead, and the interested objects should handle it as needed).
This pull request should not change the behaviour of the moved code; the no MCU warning should still be shown as before (that is, when enabled in the settings and joining a call with more than 4 participants with the internal signaling server), and when a room is deleted the UI should be updated for the users in the room and an ongoing call should be stopped.
=> Move things that should not be there outside of signaling object

css/chatview.scss, js/views/chatview.js, js/views/templates.js, js/views/templates/chatview_comment.handlebars
Fix #1799 
* timestamp is shown after 5 messages or 30 seconds
* author is shown after 20 messages or 1 hour
> ![Bildschirmfoto von 2019-05-10 13-47-57](https://user-images.githubusercontent.com/213943/57525267-85ac6800-732a-11e9-9881-40fed0edbd3d.png)
> ![Bildschirmfoto von 2019-05-10 13-48-49](https://user-images.githubusercontent.com/213943/57525299-9b219200-732a-11e9-924a-ebf88140935c.png)
=> Better grouping and timestamps

js/app.js, js/embedded.js, js/signaling.js
- Setup the MCU
- Create a group or public conversation and add more than 5 users
- Start a call with one user
- Join the call with another user (or guest)
- Enable the video
- Trigger a forced reconnection (for example, by disconnecting the Internet cable in one of the machines, although there are currently some bugs and instead of a forced reconnection you may get no reconnection at all...)
The video is enabled after the reconnection.
The video is disabled again after the reconnection.
- Setup the MCU
- Add `console.log(usersInCallMapping);` to the handler of `usersChanged` event [after the mapping is updated](https://github.com/nextcloud/spreed/blob/d55617ca22595f9771d5f28684b00f4e25a0e703/js/webrtc.js#L300)
- Open your browser console
- Create a conversation
- Start a call with one …
=> Fix status not kept after forced reconnections

js/views/videoview.js
Fixes #1511
This is actually a workaround; the proper fix would be [to get the participant names from the list of participants instead of from the data channel](https://github.com/nextcloud/spreed/issues/991), but unfortunately [guests do not have access to the participants end point](https://github.com/nextcloud/spreed/blob/1b9f73987379ecfc2b80cb6855773cfbf1c53b20/lib/Controller/RoomController.php#L565-L567) (why is this? Could it be changed to get a proper fix in the future?) and the list of participants provided in [the room information does not contain the nicks of the guests](https://github.com/nextcloud/spreed/blob/1b9f73987379ecfc2b80cb6855773cfbf1c53b20/lib/Controller/RoomController.php#L255-L256) (only [how many of them are …
=> Fix flickering spinner on avatars during calls with the MCU

js/app.js, js/connection.js, js/embedded.js, js/signaling.js, js/simplewebrtc/bundled.js, js/simplewebrtc/peer.js, js/simplewebrtc/simplewebrtc.js, js/views/mediacontrolsview.js, js/webrtc.js
Fixes #1798
Until now, when local video was available it was always sent to the other peers (directly, or indirectly through the MCU); even if the video was disabled a black stream was sent. Despite being more lightweight than the full video that black stream still needs to be processed by the clients, which could require lots of resources when several of those black streams are sent in a large group call.
The proper way to handle this would be not to send the video when it is disabled and only send it when it is available and enabled, triggering a renegotiation of the streams whenever the video is enabled or disabled. However, renegotiation is not supported yet in the WebUI nor in mobile apps, so for the time being now video, even if available, is disabled and not sent by default when …
=> Disable video by default when joining calls

js/signaling.js
The first commit is a follow up to 226d59a64403e8f9a399e6042e928316329ada11 to keep the call flags also after joining a pending call.
The second commit is the real fix to the issue (although it requires the first commit to properly keep the call flags).
When the external signaling server is used, [after successfully sending a `joinRoom` message to the Nextcloud server](https://github.com/nextcloud/spreed/blob/8d7a5e03513f9449da9b8062831ebfd8055b26ad/js/signaling.js#L236) a message [is sent too the external signaling server](https://github.com/nextcloud/spreed/blob/8d7a5e03513f9449da9b8062831ebfd8055b26ad/js/signaling.js#L1046); this registers the Nextcloud session in the signaling server, and is needed by the signaling server to be able to properly process further messages from that …
=> Fix joining call before joining room after forced reconnection with external signaling

css/style.scss
rename buttons for guest participants and rooms should always be visible (at least with opacity) to make their very existence more obvious
=> make rename button always visible

js/app.js
Let me quote myself from [the documentation of _virtuallist.js_](https://github.com/nextcloud/spreed/blob/7277141a1ee34477655549af2904855e001343b6/js/views/virtuallist.js#L80-L82):
>  Adding new elements is still possible while the virtual list is hidden, but note that "reload()" must be explicitly called once the container is visible again for the added elements to be loaded.
During a call the chat is moved to a tab in the sidebar, and when a different tab is selected the previous one is detached (and, thus, hidden). Despite having written that documentation above I forgot to reload the message list when the chat tab is selected again :facepalm:
- Open a conversation with user A
- Start a call
- If the chat does not have a scroll bar already write enough messages to make a scroll bar …
=> Fix message list not reloaded after being shown again

js/webrtc.js
When the MCU is used if a participant has no audio nor video streams no peer connection will be created by that participant to send the streams to the MCU, and no peer connections will be created by the rest of the participants to receive the streams of that participant from the MCU. As a VideoView is created for every participant when they join the call and later updated once the peer connection is established the VideoView for participants without streams was always kept in its initial state. Now the VideoView is explicitly set to a "connected without streams" state as soon as it is created for participants without streams.
Note, however, that this shows the avatar and the "audio not available" icon, but it does not show the participant name (except a generic "Guest" for guests), as the …
=> Fix view for participants without streams

js/webrtc.js
In some cases the browser may enter in a faulty state in which [`getUserMedia`](https://github.com/nextcloud/spreed/blob/1145eaeb091f863fc3b96f6088151be891e27062/js/simplewebrtc/localmedia.js#L74) does not return neither successfully nor with an error. It is not possible to detect this except by guessing when some time passes and the user has not granted nor rejected the media permissions, so now a warning is shown to the user when that happens.
However, not having granted nor rejected the media permissions after some time does not guarantee that there is a problem; it could simply be that the user has not done it yet. Therefore, the warning is hidden if the media permissions are finally granted or rejected, or when joining the call has been interrupted (for example, due to changing to a …
=> Show warning when browser silently fails to get user media

css/publicshareauth.scss
This fixes a regression introduced in https://github.com/nextcloud/spreed/pull/1807
The chat messages are expected to have the full width of its content row, except for some space used for the date. However, as [chat messages are left padded](https://github.com/nextcloud/spreed/blob/a54b5b688c23ffdeb65b41f585c4c13a5d21dc13/css/chatview.scss#L220) that padding must be included too in the width; otherwise there could be no room for the date.
This is only a problem in the public share authentication page, as [apps use by default `box-sizing: border-box` in all its elements](https://github.com/nextcloud/server/blob/3c30d293fa1d52ff51581091e3d39a30ac7474d3/core/css/apps.scss#L74-L76).
**Before:**
**After:**
=> Fix message dates in public share authentication page

package-lock.json, package.json, vue/package-lock.json, vue/package.json
=> [stable16] Bump 6.0.2 version also in "package.json" and "package-lock.json" files

js/app.js, js/connection.js, js/embedded.js
This fixes a race condition when (as logged in user) joining a public room that has been created by another user. It can happen that the list of rooms is fetched before the "join room" request finished, so the room is not included in the list, causing `syncAndSetActiveRoom` (https://github.com/nextcloud/spreed/blob/master/js/app.js#L324) to fail.
As a solution, `syncAndSetActiveRoom` is only called when the room was joined to make sure it is included in the list of rooms.
=> Only sync and set active room after user has joined room.

docs/api-v1.md, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Chat/Command/Executor.php, lib/Chat/CommentsManager.php, lib/Chat/Parser/SystemMessage.php, lib/Notification/Notifier.php, tests/php/CapabilitiesTest.php
Requires https://github.com/nextcloud/server/pull/16088
New max length in Talk is 32.000 chars, @Ivansss @mario are you checking the size, do we need to expose it with a capability?
Fix #1906
=> Allow longer chat messages

lib/Listener.php, lib/TalkSession.php
=> Leave call and room when logging out

lib/Chat/Command/Listener.php, lib/Chat/Parser/UserMention.php, tests/integration/features/chat/commands.feature
=> Allow to escape commands

css/style.scss
Fix https://github.com/nextcloud/spreed/issues/1765
=> Prevent sidebar and fullscreen icons from overlapping with the scrollbar (issue 1765)

js/views/chatview.js
Replaces #1950 
Fixes #1938 
The new message field is below the message list, so adding or removing lines from the message being composed changes the height of the new message field and, with it, the height of the message list. This change, however, did not affect the scroll position of the message list, so adding lines to the new message field caused it to overlap the last visible message in the list. Now the height change in the new message field is handled to update the scroll position of the message list and keep the last visible message at the bottom (both when lines are added and removed from the new message field).
=> Keep last visible message when new message field height changes

js/simplewebrtc/bundled.js, package-lock.json, package.json, vue/.babelrc.js, vue/package-lock.json, vue/package.json
See nextcloud/server#15988
The target browsers used by Babel are now got from `browserslist-config-nextcloud`, which will automatically keep them in sync with the server.
This also makes possible to bundle SimpleWebRTC again in Talk when the _spreed_ directory is a child of the server directory of Nextcloud. This was failing since nextcloud/server#15988 was merged because Babel gets the target browsers from the Browserslist configuration, which in turn was read from _package.json_ in the server directory (as [Browserslist uses the `browserslist`key in the _package.json_ in current or parent directories](https://www.npmjs.com/package/browserslist#queries)). However, as `browserslist-config-nextcloud` was not a development dependency of Talk it was not available in _node_modules_, Babel …
=> Use shared Browserslist config

js/app.js
It makes no sense to listen to any other shortcuts apart from **F** because they don't change anything in the chat
=> Only react to shortcuts which can be used and make sense

css/chatview.scss, js/views/chatview.js
In Talk we only parse URLs with a protocol to avoid undesired clickables like composer.json
Therefor the method and regex were copied from OCP.Comments and adjusted accordingly.
* `composer.json` => not clickable :heavy_check_mark: 
* `https://nextcloud.com/` => clickable as `nextcloud.com/` :heavy_check_mark: 
* `http://nextcloud.com/` => clickable as `http://nextcloud.com/`:heavy_check_mark: 
* `(see http://nextcloud.com/)` => clickable as `http://nextcloud.com/` :heavy_check_mark: 
* `https://en.wikipedia.org/wiki/Android_(OS)` => clickable as `https://en.wikipedia.org/wiki/Android_(OS)` :heavy_check_mark: 
cc @blizzz up to you, if we copy the behaviour back to the comments API.
=> Prevent unwanted clickables for file names and others

lib/Chat/Command/Executor.php
Required for commands which use `occ` themselves ( https://github.com/nickv-nextcloud/talk_simple_poll/issues/5 ), so the help is correctly detected in the `--help` output of symfony commands:
```
Description:
Simple polls for Nextcloud Talk
Usage:
talk:poll <token> <userId> <payload>
Arguments:
token                 
userId                
payload               
Options:
-h, --help            Display this help message
-q, --quiet           Do not output any message
-V, --version         Display this application version
--ansi            Force ANSI output
--no-ansi         Disable ANSI output
-n, --no-interaction  Do not ask any interactive question
--no-warnings     Skip global warnings, show command output only
-v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal …
```
=> Support symfony command lines with --help

css/video.scss, js/views/videoview.js, js/webrtc.js
When the ICE connection state changed to disconnected or failed the VideoView was not updated when the MCU was used. However, when the MCU is not used the VideoView is updated to let the user know that there is a problem in the connection with the other peer. Thus, now the code was adjusted to update the VideoView regardless of whether the MCU is used or not.
Besides that, now the opacity of the avatar and the video is reduced when the peer is disconnected; this should give a faster feedback that there are issues in the connection than just showing the loading icon on long disconnections or failures.
Unfortunately, the loading icon can not be shown on the video, so when the video is enabled its appearance is the same whether there is an ICE disconnected, a long disconnection or an ICE …
=> Update VideoView on ICE disconnected/failed with MCU

Makefile, js/simplewebrtc/bundled.js, package-lock.json, package.json
Follow up to #1960
Since 7.2.5 the `main` property in the _package.json_ of WebRTC adapter (which [is used by Browserify to resolve the package](https://github.com/browserify/browserify/blob/32d0a054275cd0f3cf8d138d78d24e2014ed3721/readme.markdown#packagejson)) [points to an ES6 file which does not provide "module.exports" but "exports.default"](https://github.com/webrtcHacks/adapter/pull/975). Due to this [uses of `var adapter = require('webrtc-adapter');`](https://github.com/otalk/attachMediaStream/blob/3818fd464366cbb98c50b4c91a891852e08e606c/attachmediastream.js#L1) now fail, as the properties of the module are loaded in `adapter.default` instead of in `adapter`. To restore the previous and expected behaviour [a Babel plugin](https://www.npmjs.com/package/babel-plugin-add-module-export …
=> Bundle SimpleWebRTC with WebRTC adapter 7.2.5

css/style.scss, js/views/participantlistview.js
@skjnldsv layout is broken becuase sidebar navigation and contacts menu collide, can you help solve this?
Fix #1795
=> Use the contacts menu in the participant list

package.json
The /compile bot first installs the NPM packages with [`npm init`](https://github.com/skjnldsv/npmbuildbot/blob/68cb24ddcd90e6a1d14940dd37f82b7452a3330b/lib/compile.js#L5) and then performs the build with [`npm run build`](https://github.com/skjnldsv/npmbuildbot/blob/68cb24ddcd90e6a1d14940dd37f82b7452a3330b/lib/compile.js#L20), which executes the command defined in `scripts->build` in _package.json_.
Currently `npm init` does not install all the NPM packages needed by Talk; it is necessary to run it [both in the root folder and in the _/vue_ folder](https://github.com/nextcloud/spreed/blob/de78f1040bf9538870679dd2f18b6be29a851a18/Makefile#L37). Due to this `make npm-init` needs to be run from the build script to install all the needed packages before performing the actual build.
**Edit:** …
=> Make build system compatible with /compile bot

css/chatview.scss
This pull request fixes a regression introduced in #1807
=> Fixed inconsistent date tooltips in messages

js/views/mediacontrolsview.js
Requires nextcloud/server#16369
[`OC.Notification.showTemporary` expects a string as its first parameter](https://github.com/nextcloud/server/blob/2d0337332d64065c5bf36dfb775c48976c0f730d/core/src/OC/notification.js#L139) (even if it contains HTML markup), but a jQuery object was passed instead; until now this just happened to work due to the internal implementation of that method, but this no longer works since [the switch to Toastify in Nextcloud 17](https://github.com/nextcloud/server/pull/15124).
- Use Chromium < 72 without the screensharing extension
- Start a call
The notification shows _Screensharing extension is required to share your screen._; clicking on it opens the extension page.
The notification shows _[Object object]_.
=> Fix parameter passed to OC.Notification

js/app.js
Follow up to #1946 
Note that the fullscreen shortcut could be used in the starting page. However, that would hide the navigation bar and no room could then be joined, so it would not make much sense. Therefore, the shortcuts are totally disabled in the starting page instead of fixing calling "get('participantFlags')" on a null room.
- Open Talk (without joining any room)
- Press a key
No errors appear in the browser console.
`this.activeRoom is null` is shown in the browser console.
=> Fix using "activeRoom" in the shortcut handler before joining a room

js/webrtc.js
This pull request fixes an issue with the internal signaling server, although it serves as a basis for a later fix with the external signaling server.
It prevents Peer objects from being created after the current participant left a call (as WebRTC still listens to the signaling events, so offers are still handled in the normal way; the proper fix would be to disconnect WebRTC from the signaling, but that requires deeper changes), and it also cancels the delayed peer creation if the other participant left the call (as in that case it makes no sense to still create a peer for that participant if no offer was received from him).
@Ivansss Note that I did not include in this pull request the fix to ignore a received offer if that offer comes from a participant not in the call; I am a little …
=> Fix peer creation for participants no longer in the call

lib/AppInfo/Application.php, lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
Ref nextcloud/server#15040
Fix #577
=> Adjust notifier to Nextcloud 17

js/signaling.js
`syncRooms` returns a deferred object, but if the request failed the deferred object was not rejected; due to this `internalSyncRooms` only handled successful synchronizations, but if a synchronization failed the `_pendingSyncRooms` property was never cleared, and thus further calls to "internalSyncRooms" did nothing (as it assumed that the previous synchronization was still being performed even if it failed already). This silently broke the UI, causing issues like no updates in the room list, not being able to change to another room or apparently taking forever to leave a call.
Besides properly rejecting the deferred object in `syncRooms` when the request fails this pull request adds automatic retry of room synchronization similar to the one used when pulling chat messages or connecting …
=> Fix room synchronization after failure

css/video.scss, js/views/mediacontrolsview.js, js/views/templates.js, js/views/templates/mediacontrolsview.handlebars
The volume is shown as a vertical bar next to the audio icon that grows and shrinks (with a fixed bottom position) depending on the volume level. The bar is coloured with a gradient from green to yellow to red for better clarity of the current volume.
The previous way of indicating speech (a pulse animation in the audio icon) has not been modified; this is an additional visualization (only for the local audio) to provide a more noticeable feedback to the user.
I am not sure if adding a transition to the height with something like `transition: 'height 0.5s ease';` to `#muteWrapper .volume-indicator` makes it look nicer or not.
I am not sure either if the volume bar should be always shown with the same opacity or if it should be slightly dimmed when the local audio is not enabled (currently …
=> Add volume indicator for the local audio

js/signaling.js
When the WebSocket is disconnected from the external signaling server [it is automatically reconnected to it](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L783-L790); if [a forced reconnection was queued while the WebSocket was disconnected](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L863-L871) it was supposed to be performed [as soon as it was reconnected](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L985-L989). However, `_forceReconnect` tracks whether there is a pending forced reconnection, and as it was set to false when `Signaling.Standalone.connect()` was called the queued forced reconnection never happened after a WebSocket …
=> Fix pending forced reconnection after WebSocket reconnection

js/views/chatview.js
We shouldn't consume the trailing space,
otherwise the next link has no leading space
Fix #2022
=> Fix link detection

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json, vue/package-lock.json, vue/package.json
- Chat messages can now be longer than 1.000 characters  [#1901](https://github.com/nextcloud/spreed/pull/1901)
- Users matching the autocomplete at the beginning of their name are now sorted to the top  [#1968](https://github.com/nextcloud/spreed/pull/1968)
- Only strings starting with http:// or https:// are now made clickable as links  [#1965](https://github.com/nextcloud/spreed/pull/1965)
- Fix layout issues of the chat on the share authentication page  [#1901](https://github.com/nextcloud/spreed/pull/1901)
- Fix issues with calls when a user logs out while being in a call  [#1947](https://github.com/nextcloud/spreed/pull/1947)
- Fix a problem when joining a public conversation as a non-invited logged-in user  [#1914](https://github.com/nextcloud/spreed/pull/1914)
- Fix missing …
=> Release v6.0.3

tests/drone-run-acceptance-tests.sh, tests/drone-run-integration-tests.sh, tests/drone-run-php-tests.sh
As found by @tobiasKaminsky the diff is empty on merges:
https://drone.nextcloud.com/nextcloud/spreed/2814/19/4
So in that case all tests should be executed.
=> Run all tests on merges

appinfo/info.xml, appinfo/routes.php, docs/capabilities.md, docs/chat.md, docs/conversation.md, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Chat/CommentsManager.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Manager.php, lib/Migration/Version7000Date20190724121136.php, lib/Migration/Version7000Date20190724121137.php, lib/Participant.php, lib/Room.php, tests/php/CapabilitiesTest.php, tests/php/Chat/ChatManagerTest.php
=> 🆕 Read marker handling based on ID and settable via API

docs/chat.md, js/models/chatmessage.js, lib/Chat/ChatManager.php, lib/Chat/Notifier.php, lib/Chat/Parser/SystemMessage.php, lib/Controller/ChatController.php, lib/Controller/RoomController.php, lib/Model/Message.php, lib/Notification/Notifier.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/reply.feature, tests/php/Chat/ChatManagerTest.php, tests/php/Chat/NotifierTest.php, tests/php/Chat/Parser/SystemMessageTest.php, tests/php/Controller/ChatControllerTest.php, tests/php/Notification/NotifierTest.php
PR might be delayed if the UI is not ready for 17.
For the UI maybe @jenniferpiperek and @jancborchardt have some comments? :)
From my PoV:
* There should be a reply button (or hidden in a … menu) on each message (future stuff may come too, like delete, etc), on mobile apps swiping to left (telegram) or right (whatsapp, viber) should be a shortcut to additional long press
* When starting to reply, a hint or the message itself is displayed on the new comment form, so you see what you are replying to (check the chat apps from above)
* The parent message is put as a one-liner in the top of the original message (trimmed), in a perfect world (maybe in Vue.JS) clicking the parent would jump to that message (like in any chat app)
---
To reply on this PR apply the following patch (219 being the …
=> ↩️ Reply to messages

js/simplewebrtc/bundled.js, js/simplewebrtc/simplewebrtc.js, js/views/videoview.js, js/webrtc.js
Chromium does not play the audio in a video element before the video is available. Due to this, when the remote peer had audio and video available if both were disabled (for example, when the remote peer has just joined the call) and then the audio was enabled the audio from the remote peer was not heard in Chromium until the video was also enabled. Instead of using a video element for both the audio and the video now an audio element was added to play the audio tracks of the remote stream.
The change is applied to all browsers, though, as using an audio element for the audio tracks makes sense in all of them (even if until now they worked fine except for Chromium).
- Create a new public conversation
- Start a call as the owner in that conversation from a machine with audio and video (or …
=> Fix audio not played before video is received in Chromium

README.md
`make-build-js` was missing from the development env instructions. 
=> Added a missing instruction to the development setup

js/views/editabletextlabel.js
Fixes #1977
The setter methods in EditableTextLabel (indirectly) update its HTML elements using `getUI()`. Those setters may be used before the label is first rendered (for example, to set up some default values in the initialization of a parent view), so `bindUIElements()` needs to be called to prevent `getUI()` from failing due to `this._ui` not being defined yet in those cases (note that no UI elements will be actually bound, as before the first render they have not been created yet, but that is not a problem due to the way in which the elements are updated from the setters).
_But, wait... what does all that have to do with #1977?_ A little context first.
- with almost every browser, `t('X', 'Y') === t('X', 'Y')` is true
- with Chromium >= 73 with experimental web platform features …
=> Fix setters failing in EditableTextLabel before first render

js/views/callinfoview.js, js/views/roomlistview.js
This fixes a repeated copy of a link when clicking on the copy link button (mostly noticeable as a slow down in older Firefox versions, although the underlying issue happens in every browser).
When the Clipboard object is created it attaches event listeners to the given element or to all the elements that match the given DOM selector. As all the clipboard buttons in the Talk UI (except the one in the empty content view) have the `clipboard-button` CSS class all the Clipboard objects listened to clicks on all the buttons, so clicking on a single button triggered as many copies as buttons and thus Clipboard objects were in the page. Now the Clipboard objects attach listeners only to their corresponding clipboard button.
Besides that, the previous Clipboard object is now explicitly destroyed …
=> Fix copying to clipboard

Makefile, js/simplewebrtc/bundled.js, package-lock.json, package.json
Backport of #1980 
This fixes calls with [latest Firefox and Chromium versions](https://github.com/webrtcHacks/adapter/commit/2879423570523c4c797e5d1f3060b100c0c84cb7) when no MCU is used.
- Start a call in Firefox 68
- Join the call in an older Firefox or Chromium version
No errors in the browser console. Leaving and joining the call again with the older browser works as expected.
A similar message to _Failed to construct 'RTCIceCandidate': The 'candidate' property is not a string, or is empty_ is shown in the console of the older browser. After leaving and joining the call again with the older browser it is not possible to connect any more with Firefox 68.
=> [stable16] Bundle SimpleWebRTC with WebRTC adapter 7.2.5

lib/Signaling/Listener.php, tests/php/Signaling/BackendNotifierTest.php
The signaling backend was not notified when the password, type or read only state of the room was modified so, in turn, the signaling backend did not notify the clients about those changes.
This could be seen in the WebUI when the external signaling server was used, as in that case [calling `syncRooms` does nothing until the signaling server notifies the clients](https://github.com/nextcloud/spreed/blob/9d427613335109ce360071d7d4d55c85d9cc6350/js/signaling.js#L1220), so there is no fetch, the attributes are not updated and thus the UI is not updated either.
- Setup the external signaling server
- Create a group room
- Make the room public
The UI is updated to reflect that the room is now public.
The UI is not updated to reflect that the room is now public (there are no buttons to copy the …
=> Fix missing notifications to signaling backend for some room events

lib/Controller/FilesController.php, lib/Files/Listener.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/mentions.feature, tests/integration/features/conversation/files.feature, tests/integration/features/conversation/join-leave.feature
Follow up to #1344 
This fixes the code so it behaves as stated in the documentation.
In practice currently this should make no difference, as in the Files app the user joins the room immediately after getting its token; however, this makes possible to get the token without joining the room, which will be needed in the future [to improve the UX of the Files app](https://github.com/nextcloud/spreed/issues/1366).
Besides the fix itself the integration tests were adjusted and extended.
=> Add user to file room when joining it instead of when getting its token

js/models/room.js, js/views/callinfoview.js
This pull request is a refactoring that has almost no behaviour changes, except for a minor difference: now when a room is renamed, if the internal signaling server is used all the rooms are fetched instead of only the renamed one, and if the external signaling server is used the rooms are fetched only once instead of twice.
It needs to be backported to _stable16_, as it serves as the base for further fixes.
=> Move requests from CallInfoView to room model

css/style.scss, js/views/callinfoview.js, js/views/editabletextlabel.js, js/views/templates.js, js/views/templates/callinfoview.handlebars, js/views/templates/editabletextlabel.handlebars
Instead of immediately updating the UI on some actions (setting the room as public or private, setting the password, and renaming the room) now a loading spinner is shown in the appropriate element until the server sent a successful response; if the action failed then an error message is shown.
This fixes the old behaviour of updating the UI to the new state and then suddenly and silently reverting back to the previous one if the operation happened to fail.
=> Provide feedback to the user when some operations are in progress

lib/Controller/ChatController.php
**Before:**
Read marker was updated even when receiving chat history, so the read marker was wrongly updated with the last messageId from the chat history.
**Now:**
Read marker is only updated when receiving new messages (lookIntoFuture).
Also the read marker is updated before receiving the first (lookIntoFuture) response with `lastKnownMessageId`.
Regression from https://github.com/nextcloud/spreed/pull/1214
=> Only update read marker when receiving new messages.

css/style.scss, js/views/callinfoview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars, tests/acceptance/features/bootstrap/ConversationInfoContext.php
Draft until #2122 is merged (first commit of this pull request is _Move checkbox to change between public and group room to a menu_)
This pull request provides [the groundwork needed to set the lobby state in the UI using a menu](https://github.com/nextcloud/spreed/pull/1926#issuecomment-506962798)
=> Move room moderation actions to a menu

lib/Controller/PageController.php, lib/Controller/RoomController.php, tests/acceptance/features/conversation-public.feature
This pull request was extracted from [the lobby pull request](https://github.com/nextcloud/spreed/pull/1926), as the change is not needed for the current lobby UI but it should be kept anyway.
As mentioned in [the lobby pull request](https://github.com/nextcloud/spreed/pull/1926#issuecomment-525259604):
> The commit itself introduced a regression when joining a password protected conversation as a logged in user (I have added an acceptance test that shows it); I fixed it for logged in users following the change you made for guests... but please check it :-)
Besides that I have added some acceptance tests that check that it is possible to join a password protected room again without having to enter again the password. @nickvergessen I am not sure if that is the expected behaviour (as [it …
=> Get password from session if not given when joining room

js/filesplugin.js, js/models/room.js, js/publicshareauth.js, js/views/chatview.js, js/views/participantlistview.js, js/views/richobjectstringparser.js, js/views/templates.js, js/views/templates/richobjectstringparser_userlocal.handlebars, lib/Chat/AutoComplete/SearchPlugin.php, lib/Chat/Parser/UserMention.php, lib/GuestManager.php, lib/Manager.php, tests/acceptance/features/app-files.feature, tests/acceptance/features/bootstrap/ChatContext.php, tests/acceptance/features/bootstrap/ParticipantListContext.php, tests/acceptance/features/chat.feature, tests/acceptance/features/public-share-auth.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/mentions.feature, tests/php/Chat/AutoComplete/SearchPluginTest.php, tests/php/Chat/Parser/UserMentionTest.php, tests/php/Controller/SignalingControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
* `@"guest/<sha1(webrtc session id)>"` is used to mention a guest
* After reloading the chat, the mentions are not for "you" anymore. This is because we don't reuse the session id, so you get a new one (see #1793 )
=> 👤🏷️ Guest mentions 

js/views/chatview.js
The avatars were not usually 128px width and height because `imageplaceholder` uses the height of the element and, if it is not available (for example, because the element was never shown), it uses
the given size. In most cases the `ChatView` was rendered after being shown, but in some special cases it could be rendered before being shown and then shown, which caused the large avatars.
=> Fix self avatar size for guests

lib/Controller/FilesController.php, lib/Files/Listener.php, lib/Files/Util.php, tests/php/Files/UtilTest.php
=> Support file calls in groupfolders

js/app.js, js/embedded.js, js/merged-files.json, js/merged-guest.json, js/merged-share-auth.json, js/merged.json, js/simplewebrtc/bundled.js, js/simplewebrtc/localmedia.js, js/views/mediacontrolsview.js, js/views/speakingwhilemutedwarner.js
Fixes #285
If the user is speaking while muted now an `OC.Notification` is shown (the notification is not immediate, though; it only appears after three seconds of "speech" (not actual speech, but just sounds above some volume threshold)); in the future it could be more integrated with the local video view if needed, but for now I would say that the `OC.Notification` is good enough.
However, if the browser is hidden the `OC.Notification` (or one integrated in the local video view) is not useful, as the user would not be able to see it. In those cases a browser notification is used instead, as it is visible even if the browser is hidden (provided the user grants access to notifications from the site; if not the OC.Notification is shown as a fallback, even if in most cases it will not be …
=> Warn the user if speaking while muted

js/views/callinfoview.js
Bug from #1926 
Sending a request to the server to set the same lobby state is valid, but unneeded. Moreover, the `CallInfoView` is rendered again only when the lobby state changes, so if the same state is set again a loading spinner will be shown instead of the radio button until something else changes in the room.
- Create a conversation
- Enable for all participants
No request to set the lobby state is sent, and the radio button for _All participants_ is not modified.
A request to set the lobby state is sent, and the radio button for _All participants_ becomes a loading spinner.
- Create a conversation
- Enable for moderators only
- Enable again for moderators only
The request to set the lobby state is not sent again, and the radio button for _Moderators only_ is not modified.
Another …
=> Fix setting again the same lobby state in the UI

js/views/mediacontrolsview.js
Bug from #2021
- Start a call
- Do not grant access to the microphone
The volume indicator is not shown
The volume indicator is shown
=> Fix volume indicator shown when audio is not available

lib/Controller/FilesController.php, lib/Files/Listener.php, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/mentions.feature, tests/integration/features/conversation/files.feature, tests/integration/features/conversation/join-leave.feature
Backport of #2084 
The code change makes no difference in practice, but the extra tests are nice to have in _stable16_ too to ease other backports.
=> [stable16] Add user to file room when joining it instead of when getting its token

css/style.scss, js/views/callinfoview.js, js/views/editabletextlabel.js, js/views/tabview.js, js/views/templates.js, js/views/templates/callinfoview.handlebars, js/views/templates/editabletextlabel.handlebars, js/views/templates/participantlistview.handlebars, js/views/templates/sidebarview.handlebars, js/views/templates/tabview_header.handlebars, tests/acceptance/features/bootstrap/ParticipantListContext.php
Backport of #2122 
It had to be done manually because #1822 is Talk 7 only; I just changed one CSS locator and dropped three commits.
=> [stable16] Fixes for keyboard navigation

lib/Activity/Listener.php, lib/Chat/Parser/SystemMessage.php, lib/Room.php
Also found a way to show the call summary after the last leave message, since the behaviour does not require an active session anymore since #2012 
Fix #1166
=> Show a call summary when only guests joined

js/app.js, js/views/chatview.js
Follow up to #1953 
- Send a chat message of several lines
- Send several chat messages with different numbers of lines
- Loop through the previous messages with arrow up/down
- Make the browser window narrow and reload the conversation
- Type, without sending it, a message with several lines
- Widen the browser window as much as possible
- Type another character
- Start a call
- Type, without sending it, a message with several lines
- Type another character
The chat is kept at the same scroll position.
The chat jumps back.
=> Fix chat jumping back when typing a new message

js/views/callbutton.js
Follow up to #2188 
- Setup the external signaling server
- Set the _Start calls_ setting to _Everyone_
- Open the public conversation as a guest
The call button is enabled.
The call button is not enabled (because [initially a limited set of properties about the room is received](https://github.com/nextcloud/spreed/blob/57747a0d7ae43418fa241c8bf8c0b5d4378b4466/lib/Controller/RoomController.php#L164-L197), which are then updated once the participant actually joins the room, but when that happens the button was already rendered).
- Create a group conversation
- Add a user to that conversation
- Open the public conversation as the user
- Set the _Start calls_ setting to _Moderators_
The call button is (eventually, once the rooms are synchronized again) enabled. …
=> Render call button again when "canStartCall" changes

js/app.js
Fixes a regression introduced in #1926 (specifically, 0ab60ec44651f56c251d2206a4a6e6e89f534bc7)
- Join the conversation as a guest
- As a moderator, promote the guest to moderator
The participant list is shown for the guest.
The participant list is not shown for the guest (although the moderation menu is).
=> Do not remove other event handlers when setting the active room

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
1. Write a message longer than 1000  chars in a one-to-one conversation
or 
1. Mention someone in a chat message that is longer than 1000 chars
Works fine
Notification parsing does boom:
https://sentry.io/organizations/nextcloud-gmbh/issues/1173980740/?project=1500477
> OCP\Comments\MessageTooLongException
> Comment message must not exceed 1000 characters
The `OCA\Talk\Chat\CommentsManager` is overwriting the maximum length in the `getCommentFromData()` method.
=> Fix "MessageTooLongException" when mentioning someone in a long comment

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
=> [stable17] Fix "MessageTooLongException" when mentioning someone in a long comment

tests/integration/features/sharing/hooks.feature
Since nextcloud/server#16761 a user with access to a file is able to get any of its shares.
=> Adjust integration test to changes in access to shares in server

css/files.scss, css/publicshare.scss, css/video.scss, js/publicshare.js
This fixes the regressions introduced in 6b04fb7 (promoted avatar was not shown above the other avatars, avatars in a large call were not stacked on each other so they overflowed the window), fixes the issue that 6b04fb7 was meant to fix, and also fixes an issue with guest avatars in the Files app.
- Start a call
- Join the call with another two users
The promoted avatar is above the other avatars
The promoted avatar is at the same height as the other avatars
- Join a call with several participants (five or more)
- Resize the window so it is narrow (or add several other participants)
The avatars are stacked and the local participant is visible (the local media buttons may be partially hidden, though; that will be fixed in another pull request)
Some avatars are fully visible (not stacked), …
=> [stable17] Fix position and size of avatars

src/components/MessagesList/MessagesGroup/Message/Message.vue
Since vue's `@mouseover` and `@mouseleave` listeners fall back to tap listeners on mobile we don't need to implement any logic that manages the show/hide of the actions
=> Remove unnecessary logic to show/hide the actions on mobile

lib/PublicShare/TemplateLoader.php
Requires nextcloud/server#17575
The Talk sidebar is only shown for file shares, so there is no need to load it for folder shares. Moreover, this also prevents some of the hacks used to show the Talk sidebar to mess with the layout used for folders.
=> Do not load Talk sidebar in public share page of folder shares

lib/PublicShare/TemplateLoader.php
Backport of #2339 
Requires nextcloud/server#17597
Fixes #2282 
Fixes #2293
Note that the `Files_Sharing::loadAdditionalScripts` event only includes the share since Nextcloud 17.0.1, so it is needed to handle the event without parameters to keep compatibility with Nextcloud 17.0.0 (in that case the Talk sidebar will still be loaded for folder shares).
=> [stable17] Do not load Talk sidebar in public share page of folder shares

src/components/Navigation/ConversationsList/Conversation.vue, src/components/Navigation/ConversationsList/ConversationsList.vue
For now I went with a `FAVORITE` prefix for the favorites in the conversation list.
I prefered the yellow star, but not sure how we can fit that into the app navigation items component.
Afterwards the conversations are sorted by last activity, just like they used to be.
~~Captions have been adjusted to match the style from the settings page. Looks much better I think, but open to discuss this~~. => https://github.com/nextcloud/spreed/pull/2349
=> Sort conversations by favorite and last activity

src/components/Navigation/GroupsList/GroupsList.vue, src/components/Navigation/Hint/Hint.vue, src/components/Navigation/Navigation.vue
The user themself is also removed from the list now, because you can not one-to-one conversation yourself
> ![Bildschirmfoto von 2019-10-23 16-31-47](https://user-images.githubusercontent.com/213943/67405967-bbca6500-f5b5-11e9-8a48-49325abbf605.png)
Requires: #2353 and #2354
=> Start group conversations

src/components/Navigation/ConversationsList/Conversation.vue
Before | After
---|---
I wouldn't even add the avatar there, so this can use the simple text parsing
=> Parse parameters in subtitle message

src/components/Navigation/ActionCaption/ActionCaption.vue, src/components/Navigation/ConversationsList/Conversation.vue
* Fixed captions
* Fixed separators
* Visible state of the notification option (as in 17)
=> Finish action menu

src/components/MessagesList/MessagesList.vue, src/components/NewMessageForm/NewMessageForm.vue
Otherwise the last read message id will be set to a timestamp and you will never have unread messages again
=> Ignore temporary message ids on get-last-known

css/publicshare.scss, js/publicshare.js, tests/acceptance/features/bootstrap/TalkPublicShareContext.php, tests/acceptance/features/public-share.feature
Before as soon as the public share page loaded the user or guest automatically joined the conversation. Now the conversation must be explicitly joined by clicking a button in the Talk sidebar.
However, the current approach still has a problem: if the conversation was not created yet as soon as the public share page is loaded the conversation is created, even if the user does not join it. When the conversation is created a system message is shown, so this could still be used for "stalking" (knowing when the recipient of a link share opened it for the first time).
This could be fixed by:
- Not adding the "XXX created the conversation" system message for file rooms (which I am not sure if it is very useful/needed in that case anyway).
- Splitting getting the token for a file room and …
=> [stable17] Do not immediately join the conversation in public share pages

css/publicshare.scss, js/publicshare.js
Fixes #2313 
As discussed with @jancborchardt now an icon is shown in the header of the public share page that makes possible to show and hide the Talk sidebar.
For 18 it would be nice to add an API that apps with an UI embedded in the public share page, like Text, can use to better integrate the button. But for the time being this is good enough ;-)
@jospoortvliet FYI
=> Make possible to show and hide the Talk sidebar in public share pages

js/app.js
- Start a call in the main Talk UI
- Send enough messages to show a scroll bar in the message list
- Hide the sidebar
- Join the conversation with another user
- Send a new message
- Show the sidebar again
The message list can be scrolled to the bottom and the new message is shown
The message list is already at the bottom but the new message is not shown
Backport to stable16?
=> Fix new messages not loaded if they arrive while the sidebar is hidden

js/filesplugin.js, js/publicshare.js
Related to #2347 
Fixes #1366 
Before as soon as the chat tab loaded if the file was shared the user automatically joined the conversation. Now the conversation must be explicitly joined by clicking a button in the chat tab. This prevents accidentally joining a room or even creating them when opening the details of a different file.
Note that in this current version the user always needs to explicitly click the _Join_ button to see the chat messages (except if she changed to a different tab and went back to the Chat tab). It would be better if the chat messages are automatically shown if the conversation is already created and the user has already joined, but for now always having to join should be good enough (and better than accidentally creating/joining the conversation).
=> [stable17] Do not immediately join the conversation in Files app

.drone.yml
The NPM major version was recently bumped in the _node:lts_ Docker image, so CI started to fail due to unclean JavaScript builds. The server seems to require the previous version due to incompatible dependencies, so for consistency the JavaScript files are still built and checked with the previous version instead of updating them to the new one.
Besides that  NPM dependencies in CI are now installed using `npm ci` instead of `npm install`. According to [its documentation](https://docs.npmjs.com/cli/ci) "_npm ci will never write to package.json or any of the package-locks_", so this should solve [the issue of `option: true` sometimes being wrongly removed from the _package-lock.json_ in CI builds](https://github.com/nextcloud/spreed/pull/2065#issuecomment-518183575).
=> Use nextcloudci Docker image for node

package-lock.json, package.json, src/components/MessagesList/MessagesGroup/Message/Message.vue
Fix #1744 
Quick testing showed most apps allow 2 or 3 emojis
> ![Bildschirmfoto von 2019-11-08 16-27-39](https://user-images.githubusercontent.com/213943/68488475-65ac2180-0245-11ea-8b94-b6abe21ac755.png)
=> Make single emojis bigger

js/views/callinfoview.js
Follow up to #2289
The DatetimePicker was loaded in the UI for guests, but as the needed files were not included in _merged-guest.json_ the UI for guests was broken. As the DatetimePicker is never shown in the UI for guests now it is loaded only in the main Talk UI used by logged in users.
=> Fix DatetimePicker for guests

js/publicshare.js
Follow up to #2347 
The join button was initially disabled in public share pages and enabled once the Talk sidebar was fully shown. As the Talk sidebar is shown using a transition showing the Talk sidebar had to be delayed after the page load, as in some cases the transition was ignored and the sidebar was immediately shown. When that happened, as there was no transition, the join button was never enabled.
However, despite using a delay of one second in some cases (apparently if the system load is high) the transition did not happen either. Instead of increasing the delay even more, which does not guarantee anything, now the join button is enabled since the beginning.
=> [stable17] Enable join button by default in public share pages

tests/acceptance/features/app-files.feature, tests/acceptance/features/bootstrap/FilesAppChatTabContext.php, tests/acceptance/features/public-share.feature
Follow up to #2347 and #2423 
Now the conversation needs to be explicitly joined by pressing a button in the Files app and the public share page.
=> [stable17] Adjust acceptance tests to changes in Files app and public share page

src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
1. As user1 create a conversation with user2
2. As user2 write something in the chat
3. Delete user2
4. As user1 check the chat
`>_` Bot avatar
`X` Guest style avatar
=> Fix the avatar of deleted users

package.json, src/components/MessagesList/MessagesGroup/Message/MessagePart/PlainText.vue, src/components/NewMessageForm/NewMessageForm.vue
Fix #2388 
Post a message:
```
Hi
<strong>this should not be strong</strong>
But this is on a new line with an empty one before.
```
```
Hi  <strong>this should not be strong</strong> But this is on a new line with an empty one before.
```
```
Hi
<strong>this should not be strong</strong>
But this is on a new line with an empty one before.
```
=> Correctly render newlines in text

css/style.scss
**Before (wide screen):**
**After (wide screen):**
**Before (narrow screen):**
**After (narrow screen):**
**Padding before:**
**Padding after:**
=> [stable17] Fix moderation menu width when date picker is not shown

src/components/Sidebar/Participants/ParticipantsList/Participant/Participant.vue
2. Look at the participant list and search for `(moderator)` next to your name
Regression from https://github.com/nextcloud/spreed/commit/e7453a8102716a96a9a790a278fcfd53fd2ec235#diff-bc1cb9aced147cca84ef194eba1170f6R105 where participantType was read from the wrong property
=> Fix participant type detection

src/App.vue, src/components/TopBar/CallButton.vue, src/services/callsService.js, src/store/actorStore.js, src/store/conversationsStore.js, src/store/participantsStore.js
- This does not work for guests at all
- The information for the current user should be taken from the conversation endpoint to populate the current user at least
=> Start with the call service

js/simplewebrtc/bundled.js, js/simplewebrtc/localmedia.js
Fixes a regression introduced in #2016
The local stream used to capture the microphone is cloned to be used by the audio monitor. When the call is left the original stream was stopped, but the cloned one not, so the microphone was still being captured. Now the cloned stream is a linked clone, so when the original stream is stopped the clone is stopped too.
- Start a call
The indicator of active media capture is no longer shown by the browser.
The indicator of active media capture is still shown by the browser.
=> [stable17] Fix local media not stopped when leaving a call

css/files.scss, css/publicshare.scss, css/publicshareauth.scss, css/video.scss, js/embedded.js, js/publicshare.js
This pull request fixes several issues with screen sharing in the Talk sidebar:
- Fixes screens shared by others not shown in the Talk sidebar in Files app and public share pages
- Fixes videos overlapping the shared screens in the Talk sidebar
- For consistency with Files app, removes the _Share screen_ button in public share pages (as due to a bug in the local video container width it was visible only when other screens were already shared, so for the time being the button is now always hidden)
- Fixes changing between the screen shared by the current participant and the screen shared by the other participant in the public share authentication page
- Removes an unneeded empty scroll bar in all share screens (also in the main Talk UI)
- Protect the link with a …
=> [stable17] Fix shared screens in Talk sidebar

css/files.scss, css/publicshare.scss, css/publicshareauth.scss, css/style.scss, css/video.scss
The Talk sidebar loads the _videos.scss_ file wherever it is used. As the rules were too broad they were applied to elements not in the Talk sidebar, for example, when playing videos in the Files app through the Viewer.
@skjnldsv Sorry for the delay, here you have the fix :-)
=> [stable17] Fix too broad CSS rules for video elements

lib/Share/RoomShareProvider.php, tests/integration/features/bootstrap/SharingContext.php, tests/integration/features/chat/mentions.feature, tests/integration/features/chat/system-messages.feature, tests/integration/features/conversation/files.feature, tests/integration/features/conversation/lobby.feature, tests/integration/features/sharing/create.feature, tests/integration/features/sharing/delete.feature, tests/integration/features/sharing/get.feature, tests/integration/features/sharing/hooks.feature, tests/integration/features/sharing/move.feature, tests/integration/features/sharing/transfer-ownership.feature
* User and group shares are not accepted before assuming they work
* The accept state was not set on the object after loading a share from the database
=> Fix sharing integration tests and loading shares

js/views/videoview.js, js/webrtc.js
Replaces #1881
When the MCU is used and the connection with another participant failed until now there was no reconnection. Now a new offer is periodically requested until the connection is established again.
Note that even if the previous offer arrives after a new one is requested everything still works as expected. The MCU closes the previous connection whenever it sends a new offer, so if a previous offer arrives and a connection is made it will be closed as soon as the new offer is sent and reconnected again when the new offer is handled. Although receiving the previous offer would have stopped the periodic request of offers even if the new one failed the peer will eventually change to the ICE failed state, which will start a new reconnection routine.
In a related change, when the MCU …
=> [stable17] Request offer again when receiving peer fails

tests/integration/run-docker.sh
Support for PHP 7.1 was dropped in server.
=> Bump default Docker image used in helper script to run integration tests

src/App.vue, src/components/RightSidebar/RightSidebar.vue
=> Add chat in sidebar when in call

lib/AppInfo/Application.php, lib/Flow/Operation.php, src/PostToConversation.vue, src/constants.js, src/flow.js, src/views/FlowPostToConversation.vue, webpack.common.js
for #2414 
fyi @juliushaertl @nickvergessen
=> add post to conversation flow operator

src/App.vue, src/utils/signaling.js
Guests dont load the participants tab, so they failed on
finding themselves in the participant list to update the call flags.
Now they add themselves on loading the conversation.
Fix #2555
=> Fix guests joining a call

appinfo/info.xml
since #2487  is merged, Talk should also be enlisted in the new [Flow category](https://apps.nextcloud.com/categories/workflow) on the appstore.
=> add to Flow category

lib/Flow/Operation.php
Follow up to #2487
This makes the app compliant again.
=> Replace private OC_Util with OCP/Util

src/services/callsService.js, src/services/participantsService.js, src/utils/webrtc/index.js
The signaling object is created after the signaling settings are fetched. As the settings are fetched as soon as the application starts it was assumed that the signaling object was always available when it was going to be used, but that may not be the case if the request to fetch the settings take longer than expected.
Now the signaling object is guarded behind an async function that returns it if it is available or fetches the settings and then returns the object once available. Also, if a new signaling object is tried to be created while the settings are being fetched it will also wait until the first request succeeded and return the same object in all cases.
- Add `sleep(5);` before [returning the signaling settings from the server](https://github.com/nextcloud/spreed/blob/81db771748c2a …
=> Fix using signaling before its settings are fetched

src/components/ChatView.vue, src/components/RightSidebar/RightSidebar.vue, src/views/MainView.vue
When a call was started and the chat view was moved to the right sidebar the chat view did not fill the available space.
Besides that, for consistency with how the scroll bar behave in the chat view (it is shown for the message list only instead of for the whole sidebar, as otherwise it would be cumbersome to use) now all the tab contents show their own scroll bar if needed (instead of using a scroll bar for the whole sidebar).
=> Fix chat view in right sidebar

src/components/NewMessageForm/NewMessageForm.vue, src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue, src/views/RoomSelector.vue
`overflow: scroll;` always* shows the scroll bars, even if they are not needed; if the scroll bars should be shown only when needed `overflow: auto;` should be used instead.
*In newer browsers `overflow: scroll;` behaves like `overflow: auto;`, so this change makes no difference in those cases, but older browsers respect the [expected behaviour](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Values).
=> Replace "overflow: scroll;" with "overflow: auto;"

src/components/NewMessageForm/NewMessageForm.vue
- Open a conversation
- Send a new message
No errors are shown.
`Missing required prop: "isReplyable"` error is shown.
=> Fix "isReplyable" not set for temporary messages

css/icons.scss
Setting the background like it was done basically added plain text to the scss breaking everything until the first `}` so the reply icon class did not work.
Fix #2567
=> Fix broken scss file breaking the icon-reply

src/FilesSidebarTabApp.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/services/filesIntegrationServices.js, src/store/tokenStore.js, src/views/FilesSidebarTab.vue
Known issues:
- If the chat tab is opened again after a file is shared the button will still be "_Share this file_" instead of "_Join conversation_". It seems that the FileInfo is not properly updated in the server when a file is shared (or unshared). This needs to be further investigated, but it seems to be an issue in the server and not in Talk.
- The chat tab is shown for folders with a "_Conversations are not available for folders_" message (not localized). The tab will not be shown once #2605 is merged, but as it requires a change in server which was not ready for beta 3 that temporary warning is shown for now (to be able to release a Talk version that can be used with beta 3 of server).
- Chat input is not focused after the chat view is shown.
- This only adds the chat tab; calls in …
=> Add chat tab to sidebar in Files app

src/components/RightSidebar/RightSidebar.vue
=> Fix sidebar's title alignment

src/components/CallView/Video.vue
Before the connection is established the avatar still shows the `a` for me.
After a connection is established it correctly shows `H`for the displayname now.
Any idea where the first wrong avatar is loaded @danxuliu ?
=> Set the correct placeholder avatar

src/flow.js
As discussed @juliushaertl 
Not tested just quickly changed. Nextcloud Talk should of course have the Nextcloud color (not themed), not a random "tomato" color. ;)
=> Update Talk action to Nextcloud blue

src/components/LeftSidebar/ConversationsList/Conversation.vue
Fix #2657 
Before | After
---|---
=> Bring back the bubble for the unread counter

src/FilesSidebarTabApp.vue, src/mainChatTab.js, src/mainSidebarTab.js
Based on https://github.com/nextcloud/server/pull/18449
=> Hide chat tab for folders

src/components/RightSidebar/Participants/ParticipantsTab.vue
When getting the participants the token must be stored in a local variable. Otherwise the token could be updated while waiting to fetch the participants, so using the property would cause the fetched participants to be added to the new token instead of to the original one.
Even if the participants are then fetched again and the store content is fixed, due to the reactivity system of Vue setting the participants associated to the wrong token, even if briefly, can lead to surprising and hard to debug behaviours.
Note that I have not checked the rest of the code for similar problems, so this could be lurking around somewhere else.
- Add `sleep(5);` to the beginning of [`RoomController::getParticipants()`](https://github.com/nextcloud/spreed/blob/f565bdb3e3df70fd4793b6ca82ca00dc5b4543d2/lib/Co …
=> Fix participants added to the wrong token

templates/settings/personal/clients.php
To be tested together with https://github.com/nextcloud/firstrunwizard/pull/251, see screenshots there. :)
Please review @nextcloud/designers-talk
=> Fix design of firstrunwizard settings page section

src/components/Caption.vue, src/components/LeftSidebar/ActionCaption/ActionCaption.vue
Before, the separators actually made it look like the headings belong to the elements _above_ them, which is of course not the case. Simple whitespace separation is enough here, so we can remove the borders. :)
Also looks much more like Nextcloud style, light and not so boxy. Please review @nextcloud/designers-talk
=> Remove bottom border for search result category captions

src/components/RightSidebar/RightSidebar.vue
The CSS rules added in cbad9718ce and 1dc4b61b25 (both from #2608) were mistakenly* removed in 7620c3c279, so they are added again for proper scrolling and padding of the chat view in the right sidebar.
*@ma12-co I assume that it was a mistake made during the rebase, as those rules seem unrelated to the fix of the sidebar title, and as removing them causes the whole right sidebar to be scrolled when the chat is scrolled.
=> Add again CSS rules for scrolling and padding in right sidebar

src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/LeftSidebar/SearchBox/SearchBox.vue, src/components/MessagesList/MessagesList.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue
Several EventBus event handlers were registered in the components, but never unregistered. Due to this even when the components were destroyed the handlers were still active, so the references to the components prevented them to be garbage collected.
Moreover, as the handlers were still active they were still called when their associated event was triggered, which could cause for example an infinite loop of requests to get new messages (as the store was disconnected and thus the MessagesList component [never got an updated last known message ID, so it requested again and again new messages](https://github.com/nextcloud/spreed/blob/5368f4a98a95d3193c59a03513668cdcee7acbca/src/components/MessagesList/MessagesList.vue#L313)).
- Open the Network tab of the browser development tools
- Join a …
=> Fix leak of components due to EventBus event handlers

src/App.vue, src/store/conversationsStore.js, src/store/participantsStore.js
This pull request fixes adding the same participant again and again to the store when using the guest page. It also fixes adding again the participant with the previous session as well as the participant with the new session both associated to the current guest when reloading the guest page.
Besides that it cleans up the initialization code of guest pages, as the conversations should be fetched only after the guest has joined the conversation, and not the other way round.
=> Fix duplicated participants in store when using guest page

src/components/ConversationIcon.vue, src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
- Fix alignment and proper sizing of the elements
- Reduced star size for better antialiasing
| Before | After |
|:---------:|:------:|
|![Kazam_screenshot_00001](https://user-images.githubusercontent.com/14975046/71823553-c5814600-3097-11ea-87f7-9bb5b7bac1a8.png)|![Kazam_screenshot_00000](https://user-images.githubusercontent.com/14975046/71823551-c5814600-3097-11ea-949b-38f2660a22f7.png)|
=> Small fixes on the ConversationIcon design

src/components/MessagesList/MessagesGroup/Message/MessagePart/DefaultParameter.vue, src/components/MessagesList/MessagesGroup/Message/MessagePart/PlainText.vue
Fix #2660 
Code is copied from the old code:
https://github.com/nextcloud/spreed/blob/stable-pre-vue/js/views/chatview.js
=> Make links clickable again

package-lock.json, package.json, src/App.vue, src/components/MessagesList/MessagesList.vue, src/main.js, src/store/windowVisibilityStore.js
Fixes #2636
Fixes #2681
The issues are fixed  by removing the virtual scroller
plus auto-scrolls the message list to the bottom when receiving new messages `&&`:
* the list was already scrolled to the bottom before receiving the new messages;
* the browser window is active.
=> Fix scrolling issues

src/components/MessagesList/MessagesList.vue
Requires #2637 and #2665
Fixes a regression introduced in 3730748849
The MessagesList component only started getting the messages after a conversation was joined. Due to this the messages were not updated after joining a call, as the original MessageList component was removed from the main view and a new component was added to the sidebar, but as the conversation was not changed the new MessagesList component did not fetch new messages and only showed those that were already in the store.
Now getting the messages is done based on the conversation token and whether the current participant is a participant of the conversation or not. Both checks are needed and independent; when "token" changes that signals a change in the current conversation, and when "isParticipant" changes that signals …
=> Fix getting messages in MessagesList

src/components/LobbyScreen.vue, src/components/MessagesList/MessagesList.vue, src/components/RightSidebar/Participants/ParticipantsTab.vue, src/components/RightSidebar/RightSidebar.vue, src/mixins/isInLobby.js, src/services/conversationsService.js, src/store/conversationsStore.js, src/views/MainView.vue
Requires #2666
Fixes #2582
Fixes #2583
This pull request adds the input to the moderation menu to set the lobby timer and shows the lobby screen when joining as a non moderator a conversation with the lobby active.
Note that this adds checks about being in the lobby to MessagesList and ParticipantsTab to prevent fetching data from the server. This is a temporary and quick fix that follows the current code, but this should be properly fixed later (views should not be concerned about the state of a conversation to try to fetch data from the server or not, this should be abstracted away and handled outside the views).
Known issues:
- When the lobby is enabled in the moderation menu the lobby timer picker is shown; this messes with the menu size and it is partially hidden. Once closed and …
=> Add lobby screen and lobby timer input

templates/index.php
The `TemplateLayout` class only sets `user_uid` if the template is
rendered for a user, error and guest, but not for public pages. Hence
there should be a fallback for when the array index doesn't exist.
Issue discovered by Sentry.
=> Fix invalid index on public call pages

css/icons.scss, src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
There is an error in the console about `user` property being required. This is [a bug in the UserBubble component](https://github.com/nextcloud/nextcloud-vue/issues/796).
The avatar for guests uses the generic user icon instead of the _?_ character. Again this is a limitation of the UserBubble component, as [it is currently not possible to set a specific character for the avatar](https://github.com/nextcloud/nextcloud-vue/issues/797).
=> Fix mentions to all and guests not using user bubbles

src/FilesSidebarTabApp.vue, src/mainChatTab.js, src/services/participantsService.js
Follow up to #2666 and #2692
- Open the chat tab of a shared file (if you are sharing it for the first time reload, as there is currently a bug in the server that causes the placeholder in the chat tab to not be updated)
- Join the conversation
The messages are shown.
The message list is empty.
=> Fix getting messages in MessagesList in Talk sidebar

css/At.scss, css/icons.scss, css/merged-files.scss, css/merged.scss, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/mixins/vueAtReparenter.js
Follow up to #2691 
This pull request mainly fixes the autocompletion in the chat tab of the Files app. Basically it removes the default vue-at style sheet and replaces it with a custom one that only affects Talk candidate mentions, as the selectors used in the default one were too broad and affected too the autocompletion in the comments tab.
In a similar way the selectors used in the comments tab are too broad too and affect Talk candidate mentions, so some of these rules had to be overriden for that element.
Although I tried to dynamically change the vue-at style sheet it did not fully work (most rules were fine, but for some reason the text was not properly aligned, may be related to the order of the rules that is not the same in the original CSS file and in the JavaScript objects), …
=> Fix autocompletion issues

src/App.vue, src/FilesSidebarCallViewApp.vue, src/FilesSidebarTabApp.vue, src/services/participantsService.js, src/utils/webrtc/index.js
* Enter a chat
* Click on another app in the top menu
* Check with another participant whether you are still active in the conversation (or look at the database directly)
Fix #2621
=> Leave conversation when navigating away

lib/Chat/Parser/SystemMessage.php
Fix #2733
> ### Re-setup the filesystem in case a share message failed
> 
> This happens when your request is already waiting for new chat messages.
> The filesystem is already set up, so the share will not be discovered
> unless the mount points are initialised freshly
=> Fix shares done via talk

css/merged-share-auth.scss, css/publicshareauth.scss, src/mainPublicShareAuthSidebar.js
The autocompletion panel is reparented to the body element and placed using an absolute position. However, as the body element used a flex layout the absolute position of the panel was ignored. Therefore now all the body elements are wrapped in another div element, which becomes the flex element and acts like the body element, so the real body element is no longer flex and reparenting the autocompletion panel to it then works as expected.
##How to test
- Add a password to the share
- Enable video verification in the share
- In a private window, open the link of the share
- Type "@" and then "a"
The autocompletion panel appears as expected.
The autocompletion panel appears below the rest of the content.
=> Fix autocompletion of mentions in public share auth page

src/components/MessagesList/MessagesGroup/Message/MessagePart/PlainText.vue
Post code, e.g.:
```
export default {
name: 'PlainText',
props: {
data: {
type: Object,
required: true,
},
},
computed: {
text() {
return this.clickableLinks(escapeHtml(this.data.text))
},
},
```
Before | After
---|---
=> Preserve whitespace when posting code

.drone.yml
The output to be ignored:
```
Analysing …/spreed/lib/Chat/Parser/SystemMessage.php
2 errors
line  277: OC_Util - Static method of private class must not be called
line  278: OC_Util - Static method of private class must not be called
App is not compliant
```
=> Fix drone test

lib/Controller/PageController.php
Fix #2777
1. Open the contacts menu in the top
2. Click on the "Talk to …" option for a user
Conversation opens
You are redirected to `index.php/apps/spreed?token=…` which is not recognized by the router and therefor not opening the conversation
=> Fix redirect on "Talk to …" links

src/components/MessagesList/MessagesGroup/MessagesGroup.vue
The sticky avatar currently jumps a bit since it already has enough spacing though the margin that is applied. Therefore setting the top to 0px makes sure that it is not jumping around when scrolling but just staying attached to the top.
Really neat design detail btw. :heart:
=> Avoid jump when avatar gets sticky

lib/Chat/Notifier.php
Steps
* Create a public share
* Create a flow to post to a channel on uploads
* Upload as a guest on the public share (with https://github.com/nextcloud/server/pull/19186 applied)
* Wait for the notification on your user
> ![https://i.imgflip.com/1c1uej.jpg](https://i.imgflip.com/1c1uej.jpg)
Fix #2861
=> Fix flow notifications

src/components/MessagesList/MessagesList.vue, src/services/messagesService.js, src/store/messagesStore.js, src/utils/signaling.js
Fixed errors:
* Chat was initialised twice, the later request would cancel the first one and therefor slowing the loading down a lot
* Chat headers were ignored. So in case someone used 200 commands in a row, the chat would load infinitly for all other users
=> Improve chat loading

src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/LeftSidebar/LeftSidebar.vue
How to test: 
1) Initiate a search for a conversation;
2) click on an existing conversation;
Before this pr: 
The search filter is still applied and the conversations are still filtered;
After this pr: 
The search filter is cleared and the search operation is ended
=> End search operation when selecting a conversation

src/components/MessagesList/MessagesGroup/MessagesGroup.vue, src/components/Quote.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Using "username" like on > 200 strings over the whole Nextcloud project.
Signed-off-by: rakekniven mark.ziegler@rakekniven.de
=> l10n: Changed spelling of "user name" to "username" 

src/components/MessagesList/MessagesList.vue
It's more what people expect than having to see that the window
is scrollable and not at the bottom. We might revert this, when the
"Unread messages" marker was implemented, but I don't think we should
=> Also scroll on inactive tabs

lib/Chat/Notifier.php, lib/Controller/RoomController.php, lib/Settings/Admin/GeneralSettings.php, src/views/AdminSettings/GeneralSettings.vue, tests/php/Chat/NotifierTest.php, tests/php/Controller/RoomControllerTest.php
Fix #2069
Fix #2085 
@nickvergessen 
Thanks for your great help 👍 
What do you think about the code?
Now the added users have no preselection here:
=> 1st try default group notification setting

src/App.vue, src/FilesSidebarTabApp.vue, src/PublicShareAuthSidebar.vue, src/PublicShareSidebar.vue, src/components/LeftSidebar/ConversationsList/Conversation.vue, src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/store/conversationsStore.js
1) Open a conversation;
2) Write some messages;
3) Look at the message preview in `Conversation` component;
The preview message is not updated until the whole `ConversationList` refreshes (which happens every 30 seconds).
The conversation updates immediately.
=> Immediately update last message preview in conversation list

src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
Duplicate keys detected: ''. This may cause an update error.
1. Create a public conversation
2. Join as 2 guests
3. As one of them set a name
4. As the creator of the conversation check the participants tab for the updated name :heavy_multiplication_x: 
5. Check your browsers console:
```
[Vue warn]: Duplicate keys detected: ''. This may cause an update error.
found in
---> <ParticipantsList> at src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
<CurrentParticipants> at src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
<ParticipantsTab> at src/components/RightSidebar/Participants/ParticipantsTab.vue
<AppSidebarTab>
<AppSidebar>
<RightSidebar> at src/components/RightSidebar/RightSidebar.vue
<Content>
<App> at src/App.vue
<Root> …
```
=> Fix guest collisions

src/utils/signaling.js
… otherwise the call is in a mixed state and you are still shown
as in the call and the conversation still has a call.
1. Go to a conversation and start a call
2. Navigate to another converesation
3. Check the network log (failed leave call request) and database participants table
=> Await that the call was left before leaving the conversation

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
@ma12-co @jancborchardt was it intentionally to keep 13 as a size on the input? Or an oversight?
=> Fix font-size of the chat input

src/views/FilesSidebarCallView.js
The secondary view registration requires its views to have an id property set https://github.com/nextcloud/server/blob/b476659ac888618fdb01c1316db073237c9222d3/apps/files/src/services/Sidebar.js#L69
To reproduce enable the talk app and try to access the system tags in the files sidebar.
Related fix for system tags https://github.com/nextcloud/server/pull/19511
=> Make sure the secondary view has an id

package-lock.json, package.json, src/components/NewMessageForm/NewMessageForm.vue, src/services/DavClient.js, src/services/filesSharingServices.js
=> File upload

src/components/RightSidebar/Participants/ParticipantsTab.vue, src/services/participantsService.js
Avoid duplicating getparticipants requests when quickly switching between conversations.
=> Cancel getparticipants requests once changing conversation

appinfo/routes.php, docs/capabilities.md, lib/Capabilities.php, lib/Config.php, lib/Controller/PageController.php, lib/Controller/SettingsController.php, src/components/LeftSidebar/LeftSidebar.vue, src/components/NewMessageForm/NewMessageForm.vue, src/services/settingsService.js, src/store/fileUploadStore.js, tests/php/CapabilitiesTest.php
=> Allow to select an attachment folder

css/icons.scss, src/components/TopBar/CallButton.vue
=> Add an icon to the call button to draw more attention

src/components/NewMessageForm/NewMessageForm.vue, src/store/fileUploadStore.js
1) Create a conversation with no previously shared files 
2) Upload a file;
3) Upload a second file;
When sharing the second file, the first file is re-shared before the second.
When sharing the second file, only the second file is shared.
=> Prevent resharing of the same file

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Regression from #2953 
1. Type `@all` into the chat and use enter to autocomplete the suggestion
2. Empty mention is inserted: 
Fix #3006
=> Fix mentions inserted by vue-at

src/utils/signaling.js, src/utils/webrtc/webrtc.js
=> Get rid of underscore, jQuery and the console.log statements

src/components/RightSidebar/RightSidebar.vue
Only logged in moderators can add participants to a conversation, so the search box should be shown only to them.
=> Fix search box to add participants shown to regular participants

docs/events.md, lib/Chat/SystemMessage/Listener.php, lib/Controller/CallController.php, lib/Controller/SignalingController.php, lib/Events/SignalingRoomPropertiesEvent.php, lib/Room.php, lib/Signaling/BackendNotifier.php, src/App.vue, src/views/MainView.vue, tests/php/Controller/SignalingControllerTest.php, tests/php/Signaling/BackendNotifierTest.php
This makes it easier to extend the properties in the future (@danxuliu might need this for #2146).
Also dispatch an event so other apps can extend the properties to return.
=> Get room properties for the signaling server from separate function.

CHANGELOG.md
- Add a link to the file in the conversation info for file conversations  [#2974](https://github.com/nextcloud/spreed/pull/2974)
- Fix copy and paste behaviour with WebKit based browsers  [#2982](https://github.com/nextcloud/spreed/pull/2982)
- Improve chat loading for guests to be fast again  [#3026](https://github.com/nextcloud/spreed/pull/3026)
- Improve reaction time to conversation status changes for guests  [#3038](https://github.com/nextcloud/spreed/pull/3038)
- Fix collision on (empty) tab id with systemtags app in the sidebar  [#2964](https://github.com/nextcloud/spreed/pull/2964)
- Focus the chat input in the sidebar when opening the chat tab  [#2975](https://github.com/nextcloud/spreed/pull/2975)
- Also end call state of conversation when the last user leaves, has a timeout or …
=> Add changelog for v8.0.5

src/components/CallView/Video.vue, src/utils/webrtc/models/CallParticipantModel.js, src/utils/webrtc/simplewebrtc/simplewebrtc.js
This is a regression introduced [during the move of the call view to Vue.js](https://github.com/danxuliu/spreed/commit/56c6aeb1d240716a938af2a40ad1b901be2109d4).
SimpleWebRTC automatically created audio and video elements when a new stream was added. Before the move to Vue.js those elements were the ones used by the views, but it was changed so the views created and managed their own elements. However, although the elements created by SimpleWebRTC were ignored they were still active.
Ironically this turned out to be a feature, because the elements created by the views are destroyed when their view is removed. This happens, for example, when closing the sidebar in the Files app during a call, which stopped the audio being played by the audio element created by the Video view. However, as …
=> Fix duplicated audio elements

lib/AppInfo/Application.php, lib/Share/Listener.php, lib/Share/RoomShareProvider.php, tests/integration/features/bootstrap/SharingContext.php, tests/integration/features/sharing/create.feature, tests/integration/features/sharing/delete.feature, tests/integration/features/sharing/get.feature, tests/integration/features/sharing/hooks.feature, tests/integration/features/sharing/move.feature, tests/integration/features/sharing/restore.feature, tests/integration/features/sharing/transfer-ownership.feature, tests/integration/features/sharing/update.feature
=> Receive shares in Talk/ folder

src/views/MainView.vue
> The "computed" property should be above the "watch" property on line 51
=> Fix ESlint warning

lib/Controller/PageController.php, src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Fix #2002
At this time the Viewer can open only internal files, which are available only for registered users. Therefore the Viewer is not loaded for guests.
Also, for the time being, due to a limitation in the Viewer API, when a file is opened the Viewer allows the user to iterate through all the files in the directory of that file instead of through all the files in the conversation, as it would have been expected.
Both issues will be solved in future releases of the viewer, so when that happens how the viewer is used will be updated in Talk.
=> Add support for opening files through viewer

src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/MessagesList/MessagesList.vue
Color used is `background-color: var(--color-primary-light);` so don't get confused by the orange:
> ![Bildschirmfoto von 2020-02-17 15-20-20](https://user-images.githubusercontent.com/213943/74662321-004bc300-519a-11ea-9bba-2be4f8059229.png)
Fix #534
=> Add join call button to chat view

src/components/LobbyScreen.vue, src/components/RightSidebar/RightSidebar.vue, src/components/SetGuestUsername.vue
=> Add ability to set guest name in lobby

lib/Share/RoomShareProvider.php
Apparently this can happen when a external mount was shared
that is later not available anymore
Ref https://help.nextcloud.com/t/nextcloud-talk-kills-nextcloud-after-update-to-v18-0-3/75257
=> Also bail out when the path is actually null

src/components/RightSidebar/RightSidebar.vue
The content of AppSidebar only shows non-AppSidebarTab components
when there is no AppSidebarTab. So as soon as a guest joined the call
and the Chat was moved into a sidebar tab, the rename option was gone
> ### After
> ![Bildschirmfoto von 2020-03-26 18-30-18](https://user-images.githubusercontent.com/213943/77677902-a5736b80-6f90-11ea-9aef-2d56e416f39f.png)
=> Guest name option is missing in calls

src/components/CallView/CallView.vue, src/components/CallView/Video.vue
This fixes a regression introduced in #2734
- Start a call with a logged in user
- Join the call with a guest
In the browser of the logged in user the avatar for the guest is translucent and shows a loading icon until the connection is established.
In the browser of the logged in user the avatar for the guest always has full opacity and no loading icon, so there is no way to differentiate when the user is connecting or already connected.
=> Fix guest avatar when not connected in a call

src/utils/webrtc/webrtc.js
When the MCU is used, if a participant does not send audio nor video streams the self Peer to connect to the MCU is not created. Due to this requesting an offer from that participant never succeeds, and thus a Peer to get the streams will never be created.
- Setup the MCU
- Start a call with a user
- Join the call with a guest and reject the media permissions
No offers are requested from the guest.
In the browser console of the user _No offer received for new peer, request offer again_ appears again and again (every 10 seconds).
=> Fix trying to create Peer for participant without streams

src/components/RightSidebar/RightSidebar.vue
The content of AppSidebar only shows non-AppSidebarTab components
when there is no AppSidebarTab. So as soon as a guest joined the call
and the Chat was moved into a sidebar tab, the rename option was gone
Backport of #3168
=> [stable18] Guest name option is missing in calls

src/utils/webrtc/models/LocalMediaModel.js
same behaviour as with the old (17) UI.
It's on by default on the first visit and afterwards remembers the state (on a per conversation level as discussed with @jancborchardt ).
Once https://github.com/nextcloud/nextcloud-browser-storage is there, we shall use that, for now we access it directly like in the old days.
Fix #2485
=> Start with the last camera/microphone active state

src/components/MessagesList/MessagesGroup/Message/Message.vue
=> Improve reply feature's user experience

babel.config.js, webpack.common.js
Got further until:
> Assignment to read-only properties is not permitted in strict mode.
from line
https://github.com/nextcloud/spreed/blob/3f56ae160638ef37e1040b1f16e544ddddca559a/src/utils/webrtc/simplewebrtc/getscreenmedia.js#L26
=> Compile some more libs to make IE load

src/utils/webrtc/simplewebrtc/peer.js
This fixes a regression introduced in #3153 
If the state can not be loaded (for example, if the server did not set the value, which happens when Talk is used in other apps) `loadState` throws an exception. This caused the creation of the offer to fail and thus prevented the peers to connect.
This pull request just ensures that the connection will go on if the value can not be found. @nickvergessen Feel free to set the initial state in the server also when Talk is used in other apps.
Steps below refer to the Files app, but it happens too in video verification and the Talk sidebar in public share pages.
- Share a file with a user
- Join the conversation in the Files app
- Start a call
- With the other user, join the call in the Files app
Both users connect with each other.
Both users kept …
=> Fix peers not connecting when talk is embedded in other pages

lib/Controller/PageController.php, lib/Files/TemplateLoader.php, lib/PublicShare/TemplateLoader.php, lib/PublicShareAuth/TemplateLoader.php
This fixes a regression introduced in Talk 8 (although it happened too in the Talk sidebar in previous versions, but in those cases it was a bug).
In Chromium < 72 an extension is needed to share the screen. Once installed, [the extension enables itself only in those pages that contain an element with id `app` and class `nc-enable-screensharing-extension`](https://github.com/nextcloud/spreed-screensharing-chrome-extension/blob/8322906269d649550c0d673cc1d1708a6b642186/extension/detector.js#L29-L33) when [the document is loaded](https://github.com/nextcloud/spreed-screensharing-chrome-extension/blob/513880aabfd3a4a94f7e1b69f38937844d08e949/extension/manifest.json#L27).
As the element can not be added after the document has loaded and the screen sharing should work also when Talk is enabled …
=> Fix missing element for Chromium screensharing extension

lib/Controller/PageController.php
The template does not use those variables, so let's remove them for now:
https://github.com/nextcloud/spreed/blob/2f154e5b3fedcd5c3ccde84f9b692725063acf00/templates/index.php
If they are ever used again it will use initial state.
=> Remove unused template parameters

src/mixins/browserCheck.js
1. Be on Edge: See a warning to use "…, Microsoft Edge, …" instead
1. Be on Safari: See a warning to use "…, Safari" instead
1. Be on Safari 5 (last windows version) or <12 (not WebKit based): Call button is enabled but clicking it says "WebRTC is not supported by your browser"
=> Don't show a warning to use the same browser

lib/Controller/PageController.php
1. As a guest open `/index.php/apps/spreed/`
2. Be greeted by:
```
Remote Address: 127.0.0.1
Request ID: r3N4WLXqWiYKNzADk5mj
Type: Symfony\Component\Routing\Exception\InvalidParameterException
Code: 0
Message: Parameter "token" for route "spreed.pagecontroller.showCall" must match "[^/]++" ("" given) to generate a corresponding URL.
File: /home/nickv/Nextcloud/19/server/3rdparty/symfony/routing/Generator/UrlGenerator.php
Line: 193
```
=> Don't break when showing the login mask to users

src/utils/webrtc/webrtc.js
=> Add an error message when no bytes were received in all states of a peer connection

lib/Controller/RoomController.php, src/services/conversationsService.js
1. In Tab 1 open Talk
2. Modify the info.xml of Talk to send Nextcloud into maintenance mode
3. Now see a "showError" `Nextcloud is in maintenance mode, please reload the page` (**don't** do that)
4. Change version back
5. In Tab 1 message disappears on next room list refresh
6. Change version again
7. In Tab 2 run the update
8. In Tab 1 see a "showError" `Nextcloud Talk was updated, please reload the page` popping up
Should help with users that have the tab open for a long time.
=> Notify the users to reload when an update happened in the background

src/App.vue
Otherwise when you write a message and immediately navigate away,
the next refresh of the room list will always tell you that messages
have been posted.
2. Post a chat message and switch to another tab before the room list is refreshed
Tab is marked with `*` after the room list is refreshed
Tab is not marked.
Fix #3256
=> Don't mark the window/tab unread for own messages

appinfo/routes.php, lib/Collaboration/Resources/ConversationProvider.php, lib/Controller/PageController.php, lib/GuestManager.php, lib/Notification/Notifier.php
=> Move routes to app

docs/capabilities.md, docs/chat.md, lib/Capabilities.php, lib/Chat/ChatManager.php, lib/Controller/ChatController.php, lib/Model/Message.php, src/components/NewMessageForm/NewMessageForm.vue, src/services/messagesService.js, src/store/messagesStore.js, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/features/chat/reference-id.feature, tests/php/CapabilitiesTest.php, tests/php/Chat/ChatManagerTest.php, tests/php/Controller/ChatControllerTest.php
Apply the following patch to simulate a lot of notifications being sent:
```diff
diff --git a/lib/Controller/ChatController.php b/lib/Controller/ChatController.php
index d0bf74ee..ef984dd5 100644
--- a/lib/Controller/ChatController.php
+++ b/lib/Controller/ChatController.php
@@ -191,6 +191,8 @@ class ChatController extends AEnvironmentAwareController {
if ($parentMessage instanceof Message) {
$data['parent'] = $parentMessage->toArray();
}
+
+               sleep(10);
return new DataResponse($data, Http::STATUS_CREATED);
}
```
=> Handle the new reference id for snappier chat feeling

src/services/signalingService.js, src/utils/signaling.js
Split from #3338 for faster merging
When you navigated away, the signaling is currently not stopped, but does something else.
But because the 404 detection failed as well, we retried signaling 3 more times before stopping.
=> Fix internal signaling status code detection

lib/Controller/PageController.php, lib/Files/TemplateLoader.php, lib/PublicShare/TemplateLoader.php, lib/PublicShareAuth/TemplateLoader.php, lib/TInitialState.php, src/components/LeftSidebar/LeftSidebar.vue, src/store/fileUploadStore.js
Fixes #3244
Extracted from #3292
=> Create the initialState in a single location

tests/integration/features/sharing/transfer-ownership.feature
When transferring ownership of a share [now](https://github.com/nextcloud/server/pull/20360) the name includes the display name of the original owner instead of his ID.
=> Adjust transfer ownership integration tests to changes in server

lib/Controller/PageController.php, lib/Files/TemplateLoader.php, lib/PublicShare/TemplateLoader.php, lib/PublicShareAuth/TemplateLoader.php, lib/TInitialState.php
=> [stable18] Create the initialState in a single location

src/utils/webrtc/webrtc.js
As the catch did not have any function the caught error was logged by default by the browser. However, when a connection is established with the HPB it is perfectly normal that no bytes are received at first, so there is no point in logging that. There are some corner cases in which a connection may be established but no bytes are ever received, but in that case it can be detected by other means and the messages just flood the log providing no value and making more difficult to debug the issue. Due to all that now the "No bytes received" messages are no longer shown in the logs.
=> Prevent "No bytes received" to be logged by default

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Followup to #3370 
Brings back the Text app when clicking on a text file in talk, without slowing down the image viewer again.
=> Fix the Text app loading files

src/App.vue
Regression from f981a352288429e670c106459ea8717661882cbd
1. Create 2 conversations A and B
2. Open conversation A and check the page title
3. Open conversation B and check the page title
4. Open another tab or window
5. Bring back the conversation B tab and check the page title
=> Page title does not update immediately

src/FilesSidebarTabApp.vue, src/PublicShareAuthSidebar.vue, src/PublicShareSidebar.vue, src/utils/signaling.js
=> Don't try to reconnect the socket when we closed it intentionally

src/utils/webrtc/SentVideoQualityThrottler.js, src/utils/webrtc/VideoConstrainer.js, src/utils/webrtc/index.js, src/utils/webrtc/models/CallParticipantCollection.js, src/utils/webrtc/models/CallParticipantModel.js, src/utils/webrtc/models/LocalCallParticipantModel.js, src/utils/webrtc/models/LocalMediaModel.js
Requires #3418
Video conference, by its very nature, requires a lot of resources in the clients, and not only in the server. In fact, when there are a lot of participants in a call, usually the CPU of the client becomes the bottleneck, as it struggles to decode all the incoming videos as well as encoding the one being sent.
In order to (try to) reduce the overall resources needed, but specially the load on the CPU of the clients, now the quality of the sent video is automatically adjusted based on the number of participants with audio and video in a call. The video quality of someone actively speaking (not just with audio enabled) is always kept at a high quality, but for the rest of the participants the quality is reduced; how much depends on the number of participants with audio and/or …
=> Change video quality based on the number of participants

lib/Chat/Command/Executor.php
There is a bug when showing /help with alias command, since I presume an alias is just another way to write the command. I decide to skip the alias: when showing help
I also added the command name in the output to show the user what comand to input.
=> Executor /help bugfixe

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue, src/utils/clipboard.js
=> Handle pasting screenshots to the chat message form

src/App.vue
The room freed by the header vanishing was not filled up:
Fixed:
=> Fix fullscreen having a black bar on top

src/components/TopBar/TopBar.vue
- Wording and design detail fixes
- Fix order of top right controls so the primary button isn’t just inbetween icons.
Before | After
---- | ----
=> Design fixes of top right controls

src/utils/webrtc/simplewebrtc/localmedia.js
`getUserMedia` is first called for both audio and video and then, if the camera was not found, it was called again only for audio. In some cases (for example, in Windows if the camera device is being used by another application, or if permissions for the camera are not granted at a system level) it could happen that a camera device is found but it can not be accessed by the browser. If that happened `getUserMedia` was not called again only for audio and the microphone was also seen as not available, even if the problem was only with the camera.
This would still need more love regarding the [error shown to the user](https://github.com/nextcloud/spreed/blob/a611336813570773d1b7292de7f3787d9652e366/src/utils/webrtc/webrtc.js#L812) if the device is found but can not be accessed, but for that …
=> Fix microphone not available when camera can not be accessed

src/components/RightSidebar/RightSidebar.vue
Before this error appeared when no conversation was selected
> Error in callback for watcher "conversation": "TypeError: this.$store.getters.conversation(...) is undefined"
Or sould we add an argument to the watcher and use the value from there?
=> Don't access the store recursively again

src/components/CallView/shared/Screen.vue, src/components/CallView/shared/Video.vue, src/utils/webrtc/models/LocalCallParticipantModel.js, src/utils/webrtc/webrtc.js
Fixes #3387
Guest names still do not work when the guest has no audio nor video available (as in that case there is no data channel to send the name); that will have to wait until it is possible to link the external signaling server session ID and the Nextcloud session ID.
=> Fix guest names in call view

appinfo/info.xml, lib/BackgroundJob/ResetAssignedSignalingServer.php, lib/Config.php, lib/Controller/PageController.php, lib/Controller/SignalingController.php, lib/Files/TemplateLoader.php, lib/Manager.php, lib/Migration/Version8000Date20200407115318.php, lib/PublicShare/TemplateLoader.php, lib/PublicShareAuth/TemplateLoader.php, lib/Room.php, lib/Signaling/BackendNotifier.php, lib/Signaling/Listener.php, lib/Signaling/Manager.php, lib/TInitialState.php, src/App.vue, src/components/LeftSidebar/ConversationsList/Conversation.vue, src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/services/participantsService.js, src/services/signalingService.js, src/utils/signaling.js, src/utils/webrtc/index.js, src/utils/webrtc/simplewebrtc/simplewebrtc.js, src/utils/webrtc/webrtc.js, src/views/MainView.vue, tests/php/Controller/SignalingControllerTest.php, tests/php/RoomTest.php, tests/php/Signaling/BackendNotifierTest.php
=> Extend the signaling setting API to allow somewhat clustering

src/utils/webrtc/webrtc.js
Ref https://github.com/nextcloud/spreed/issues/1583
So this is now triggered all the time by the video-quality checking I guess.
Also it caused "black" blocks for people with disabled videos on the grid view when someone joins.
=> Assume video is off if the received video bytes are very low

lib/Activity/Provider/Base.php, tests/php/Activity/Provider/BaseTest.php
Fix #3523 
Before | After
---|---
In case we decide to backport this to stable18, the route needs to be changed.
=> Make activities link to the conversation

src/components/ChatView.vue
If a drag and drop events does not involve files the drop hint should not be shown, and the drop event does not need to be handled either. The drag event may not contain yet the files in its `dataTransfer.files` property, but [at least one of the types included in its `dataTransfer.types` property will be _Files_](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/types#Return_value).
- Join a conversation
- Select some text in the sidebar (like a participant name)
- Drag and drop the name on the chat
Nothing happens.
The drop hint is shown, and once the text is dropped an error is shown in the browser console.
Fixes #3431
=> Ignore drag and drop events if files are not involved

src/mainPublicShareSidebar.js
The `.header-right` element [may not exist in the public share page if there are no header actions](https://github.com/nextcloud/server/blob/74d40233f5d20429483de113dbf1242ca6669c0a/core/templates/layout.public.php#L58), for example, [if the downloads of the share are hidden](https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/apps/files_sharing/lib/Controller/ShareController.php#L506). In that case the `.header-right` element needs to be explicitly added.
- Create a new public link share
- Hide downloads in the share
- Open the link in a private window
The Talk sidebar is shown in the public share page.
The Talk sidebar is not shown in the public share page.
=> Fix Talk sidebar in public share pages without header actions

lib/Flow/Operation.php
Fixes sending messages though flow operations that have caused an error otherwise due to the new sendMessage parameter.
=> Add empty referenceId when sending a message though flow

docs/TURN.md
In order to know if a TURN server is working it is useful to actually test the data transfer through the TURN server instead of just checking if it generates relay candidates.
[When an RTCPeerConnection is created](https://github.com/nextcloud/spreed/blob/848f55bdff583c0f30c8babbb129cd70e31fe859/src/utils/webrtc/simplewebrtc/peer.js#L36) an RTCConfiguration can be provided to configure it. One of the values it accepts is [`iceTransportPolicy`](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration#RTCIceTransportPolicy_enum), which can be either set to `all` to gather all types of candidates or to `relay` to only gather relay candidates.
Note that the types of candidates used during a call can not be limited by just sending specific candidate types to the other peer during the …
=> Add documentation about testing the TURN server

css/icons.scss, src/App.vue, src/components/CallView/shared/Video.vue
It's at least a bit better, but the `…` is very small so the shadow is also small
=> Add drop shadow again on icons in the topbar too

src/components/ConversationsOptionsList.vue, src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/LeftSidebar/LeftSidebar.vue
Talk is the only app that have multiple uls within the app-navigation. 
```
ul (Main navigation list)
li (Conversations caption)
ul (Conversations list)
li (Conversation)
li (Conversation)
...and so forth
```
This patch overrides the `.app-navigation ul` rules coming from the vue library, that are targeted to all `ul` in the navigation, making them all scrollable and sometimes causing double scrollbars to be displayed
Fix #3539
Fix #3556
=> Fix double scrollbar

lib/Manager.php
1. Have a conversation with many participants (or fake it by extending the string here: https://github.com/nextcloud/spreed/blob/c9bc798a4fb53dbfa174a861f32495fa1e8efa48/lib/Manager.php#L778 )
2. In the database clear the room name from oc_talk_rooms (to simulate old server)
3. Try to load the UI and check the room list
Loading circle for ever
List is loaded
=> Correctly trim user list on name generation

src/utils/webrtc/webrtc.js
When the external signaling server is used the incoming audio and video stream is checked to know if there is actually audio and video being received. However, that check was performed also for the screen peer. As the audio/video peer and the screen peer of the same participant have the same id [that caused the video to be marked as available](https://github.com/nextcloud/spreed/blob/0dd47e5dcbac8fc540665e40213a6b5bc6dabbbb/src/utils/webrtc/webrtc.js#L661-L664) even if the other participant was not sending any video. Now the check is performed only on the audio/video peer.
=> Fix video marked as available due to screen sharing

src/utils/webrtc/simplewebrtc/webrtc.js
When the `unshareScreen` signaling message is received [an internal `unshareScreen` with the id of the peer that sent the message is emitted](https://github.com/nextcloud/spreed/blob/848f55bdff583c0f30c8babbb129cd70e31fe859/src/utils/webrtc/simplewebrtc/peer.js#L251). However, when the internal `unshareScreen` was handled the id of the other peer was expected to be in the `from` property instead of the `id` property. As the `id` property was undefined [this caused that all the screen peers were processed](https://github.com/nextcloud/spreed/blob/3f56ae160638ef37e1040b1f16e544ddddca559a/src/utils/webrtc/simplewebrtc/webrtc.js#L132-L136) and ended instead of only the one that sent the message.
=> Fix unsharing screen of other peers when one screen was unshared

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Follow up to #3370 and #3409
When an explicit file list is given the Viewer uses the attributes included in it, but only the `filename` and the `basename` were provided. Now [all the known file attributes](https://github.com/nextcloud/server/blob/787c2a17e3874a02388bd7bf493f4263b43b93c1/lib/public/RichObjectStrings/Definitions.php#L245-L280) which are also used by the Viewer are provided.
This makes possible to get rid of [the hack to open the Text files](https://github.com/nextcloud/spreed/pull/3409), as the missing [attributes needed by Text](https://github.com/nextcloud/text/blob/1061537667fc37e4a0c0500920cc680fe4af92af/src/components/ViewerComponent.vue#L37-L58) were `fileid` and `mime` (technically when a single file is given in the file list [the mime type is set by the Viewer …
=> Fix file attributes passed to viewer

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue, src/components/RightSidebar/RightSidebar.vue, src/main.js
The Viewer expects that, if the app has a sidebar, an `OCA.Files.Sidebar` object exists. This object should contain a `state.file` property with the name of the file currently shown (or an empty string if the sidebar is closed), and `open` and `close` functions to be called by the Viewer when opening and closing the sidebar is triggered by the Viewer.
The sidebar adjusts its width to the width of the sidebar once the opening ends. The sidebar comes from nextcloud/vue, and its opening is animated with a transition, so `OCA.Files.Sidebar.open` needs to wait until the transition ends to be resolved.
Besides the `OCA.Files.Sidebar` object [the Viewer also expects that the sidebar element in the DOM has an `app-sidebar` id](https://github.com/nextcloud/viewer/blob/015809170a0104f57e5704a956e1e6 …
=> Show sidebar when Viewer is opened

css/icons.scss
=> … menu icon in app navigation is white when in a call

src/utils/signaling.js, src/utils/webrtc/index.js
Replaces #3584
This ensures that the call status in the store will match the call status in the server. Although in other cases updating the local status before the server acknowledges it makes it feel snappier in the case of the call status it feels strange, as the call view would be shown empty without any hint that joining the call is still in progress.
Note that there is still an issue if the user tries to join the call before even getting the signaling settings (as in that case [`signalingJoinCall` just returns](https://github.com/nextcloud/spreed/blob/9570c3a9e492203363e46f31dfc8a33fac136993/src/utils/webrtc/index.js#L155) and `joinCall` continues as if the operation finished), but that is something for another pull request. In any case, when that happens, once the user joins the …
=> Make joining the call synchronous

src/utils/signaling.js
Ref https://github.com/nextcloud/server/blob/b9bc2417e7a8dc81feb0abe20359bedaf864f790/core/src/OC/navigation.js#L22-L27
=> Replace deprecated OC.redirect() with the correct way to redirect

src/App.vue, src/FilesSidebarCallViewApp.vue, src/PublicShareAuthSidebar.vue, src/PublicShareSidebar.vue, src/components/TopBar/CallButton.vue, src/mixins/talkHashCheck.js, src/services/conversationsService.js, src/store/index.js, src/store/talkHashStore.js
1. Load a conversation
2. Modify a config or place `context.commit('setInitialNextcloudTalkHash', hash + hash)` in
https://github.com/nextcloud/spreed/blob/fcd7960c18709fa516cc1757395cf8ff26a72fd7/src/store/talkHashStore.js#L65 before step 1
3. After the next room (list) refresh you should see `X-Nextcloud-Talk-Hash marked dirty:  RANDOM_SHA1` in the console
4. "Start call" button is now disabled
5. Clicking on another conversation will make a page reload
Fix #3672
=> Reload page on changing conversation and disable start/join call when Talk hash is dirty

src/components/LeftSidebar/ConversationsList/Conversation.vue
The real fix for #2815 
Before | After
---|---
Requires master of Nextcloud to be https://github.com/nextcloud/server/pull/20976 or later
=> Don't break LessThan3 in last message

src/components/CallView/shared/LocalVideo.vue, src/components/SetGuestUsername.vue
1. As a guest join a conversation
2. Set a guest user name
3. Do a page refresh (e.g. because being prompted by the "Talk was updated" notice)
4. Check that your name is still set
=> Store the guest name in browser storage

src/App.vue
Follow-up to https://github.com/nextcloud/spreed/pull/3484, where the sidebar height rule was overwritten by other changes. cc @nickvergessen @ma12-co as discussed. :)
=> Fix fullscreen having a black bar on bottom of sidebar, ref #3484

src/components/LeftSidebar/LeftSidebar.vue, src/components/LeftSidebar/SearchBox/SearchBox.vue, src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
When adding participants, search isn't performed over contacts in the address book but in fact over users in the system.
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>
=> Replace "contacts" with "users"

src/components/RightSidebar/RightSidebar.vue
Apply the following patch to make the problem occur more often:
```diff
diff --git a/src/components/LeftSidebar/ConversationsList/ConversationsList.vue b/src/components/LeftSidebar/ConversationsList/ConversationsList.vue
index 6ca3a596..d95ef7d3 100644
--- a/src/components/LeftSidebar/ConversationsList/ConversationsList.vue
+++ b/src/components/LeftSidebar/ConversationsList/ConversationsList.vue
@@ -88,7 +88,7 @@ export default {
if (!this.isFetchingConversations) {
this.fetchConversations()
}
-               }, 30000)
+               }, 3000)
EventBus.$on('routeChange', this.onRouteChange)
EventBus.$on('shouldRefreshConversations', this.debounceFetchConversations)
```
Then try to rename a conversation and take longer than 3 seconds with the open input and modified text => :boom:  => Your …
=> Don't overwrite the conversation name while renaming

src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
Before | After
---|---
n-th menu stays open | menu on the same participant stays open
=> Make the key for participants stable

lib/Command/Room/TRoomCommand.php
We can't deal with guest participants in CLI commands (we rely on user ids) and `array_map()` currently returns a empty string for guest participants that is stripped later anyway. This fix makes this behaviour just more explicit.
I don't think that we should support guest participants in CLI commands in general anyway, can't think of a reasonable use case. What do you guys think?
Guess we should backport this to stable19, too.
=> Fix talk:room:* command completion for participant options

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Was only noticable when your servers post request was blasing fast.
You didn't switch conversations then, as we checked the participant index with teh right token, but when getting the actual participant we took another token.
=> Use the correct token to check the participant

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
This PR fixes sorting of talk participants in a conversation by display name.
=> Sort participants by display name

lib/Notification/Listener.php
Backportable hack for the biggest issue of https://github.com/nextcloud/spreed/pull/3743
This can be backported easily and when the notifications app is running https://github.com/nextcloud/notifications/pull/651 it will help making everything faster
=> Dispatch an event to signal interest in defering the notifications

lib/Room.php
Since sessions are unique globally (apart from '0' which is filtered out before)
we can update the ping only based on the index instead of
index + additional where check
See https://github.com/nextcloud/spreed/pull/3285#issuecomment-639433523 for analysis
=> Make sure pinging session ids only uses indexes

src/utils/webrtc/simplewebrtc/localmedia.js
When getting the local media it is first tried to get both microphone and camera and, if that fails, then it is tried to get only the microphone.
However, this was done only when certain errors happened while trying to get both the microphone and the camera. Now, [no matter the error](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Exceptions), it is tried too to get only the microphone; if the media is still unavailable it will fail again, but this should help with some further scenarios not covered yet in the previously handled errors in which camera is not available but microphone is.
Found while testing #3730 with Firefox 77 with microphone but no camera, as in that case a `NNotAllowedError` was triggered when _resistFingerprinting_ was enabled (if it was …
=> Always try to use microphone if camera failed

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
Currently when a call is started, we run:
1. O(n) queries to get the same room for every one
2. O(n) queries to check if the participant is in the conversation
We can reduce 1. to O(1) and remove 2. as we just looped outside over the participants to generate these notifications to begin with.
=> Less database queries when parsing multiple notifications

CHANGELOG.md
- Store the guest name in browser storage again and read it from there  [#3709](https://github.com/nextcloud/spreed/pull/3709)
- Automatically switch to promoted view upon screenshare  [#3711](https://github.com/nextcloud/spreed/pull/3711)
- Added autocomplete support for talk:room:* commands  [#3728](https://github.com/nextcloud/spreed/pull/3728)
- Reload page on changing conversation and disable start/join call when Talk UI needs reloading  [#3699](https://github.com/nextcloud/spreed/pull/3699)
- Show sidebar when Viewer is opened  [#3679](https://github.com/nextcloud/spreed/pull/3679)
- Properly sort participants by display name again  [#3763](https://github.com/nextcloud/spreed/pull/3763)
- Make joining the call synchronous to avoid toggling in and out of the callview …
=> Add changelog for v9.0.1

src/components/TopBar/TopBar.vue
*videos* is a *countable* word, hence *number* should be use instead of *amount*.
Ref https://writingexplained.org/amount-vs-number-difference
=> Use 'number' for countable 'videos'

package-lock.json, package.json, src/components/CallView/Grid/Grid.vue, src/components/CallView/shared/LocalVideo.vue, src/components/CallView/shared/Video.vue, src/components/CallView/shared/VideoBackground.vue, src/store/callViewStore.js
Add same amount of relative blur regardless of the actual size of the image.
fix #3542
Before:
After:
=> Equalize background blur

lib/Share/RoomShareProvider.php
Backport of #3622 
This seems to work (before it entered [the `else`, now it enters the `if`](https://github.com/nextcloud/server/blob/v18.0.6/apps/files_sharing/lib/SharedMount.php#L240-L243)), and [the equivalent code in the `DefaultShareProvider.php` is there since Nextcloud 11](https://github.com/nextcloud/server/blob/14a561ddad8bbd6ae1d524a49c70a7926c06310f/lib/private/Share20/DefaultShareProvider.php#L851-L857).
But I do not really know if this could lead to any issue in Nextcloud 18, so a review from the masters is more than welcome :-)
=> [stable18] If available create a cacheentry

lib/Notification/Notifier.php, tests/php/Notification/NotifierTest.php
With the upcoming force to user iOS SDK 13, the iOS app can not contact the server anymore (as web requests are killed off in the presenter for notifications) to get more details. So we need to put all details into the pushed subject for mobile apps.
=> Improve push notifications for upcoming iOS/Apple changes

src/components/MessagesList/MessagesGroup/Message/Message.vue
See:
https://github.com/nextcloud/server/blob/eaf4724acc3b4720239d789f6028526945b8bba0/core/src/OC/util.js#L119-L123
`@nextcloud/moment` is already included in our package anyway
Less log spam with chat messages
=> Replace OC.Util.formatDate with the actual moment function

appinfo/routes.php, docs/participant.md, lib/Controller/PageController.php, lib/Controller/RoomController.php, lib/Controller/SignalingController.php, lib/Room.php, src/App.vue, src/FilesSidebarCallViewApp.vue, src/FilesSidebarTabApp.vue, src/PublicShareAuthSidebar.vue, src/PublicShareSidebar.vue, src/components/TopBar/CallButton.vue, src/mixins/duplicateSessionHandler.js, src/mixins/isInCall.js, src/router/router.js, src/services/SessionStorage.js, src/services/participantsService.js, src/store/participantsStore.js, src/utils/signaling.js, src/views/MainView.vue, src/views/SessionConflictView.vue
=> "409 Conflict" on joining a second time in the same conversation

lib/Listener/BeforeUserLoggedOutListener.php
- Do not use the HPB
- As user A, create a group conversation and invite user B
- In a private window, log in with user B and open the conversation
- As user A, remove user B from the conversation
- As user B, log out quickly (before the "Conversation not found" page is shown)
The user is logged out.
An error occurs during the log out and the user is not logged out.
=> Fix logout failure if active session was removed from room

src/components/CallView/shared/VideoBackground.vue
Before bluring of local avatars is missing in Chrome/Chromium after toggling between grid view and promoted view.
=> Correctly initialise blur in chrome/chromium

css/icons.scss, src/components/CallView/shared/LocalMediaControls.vue, src/components/CallView/shared/LocalVideo.vue, src/utils/webrtc/analyzers/AverageStatValue.js, src/utils/webrtc/analyzers/CallAnalyzer.js, src/utils/webrtc/analyzers/ParticipantAnalyzer.js, src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js, src/utils/webrtc/index.js, src/utils/webrtc/models/CallParticipantModel.js, src/utils/webrtc/models/LocalCallParticipantModel.js, src/utils/webrtc/webrtc.js
This shows a warning icon and a tooltip when the HPB is used and the connection quality of the sent audio is very bad (enough to most likely cause robo voice, or no voice at all). Similarly the quality of the video and/or the screen are also checked and a warning is shown if it is likely that the video is not smooth.
The analyzer checks the RTC stats, so it explicitly checks the network load, but it implicitly checks the system load too, as in that case there will be also packet losses and higher round trip times.
Please refer to the code documentation for details.
Pending:
Follow up pull request:
- Warn the user too when the connection quality of the received audio is bad, and when the sent audio is bad and the HPB is not used. The problem is that the browser generates the RTP stats in …
=> Warn user on high load

src/utils/webrtc/analyzers/ParticipantAnalyzer.js
Follow up to #3839 
The event listeners where not properly stopped when a Peer was set, so if the same Peer was set twice the listeners were duplicated, which in turn could lead to errors due to only one of them being removed.
- Start call
- Leave call
- Start call
- Leave call
- Start call
The call is started.
The call is not started. Browser console shows an error about calling `setAnalysisEnabledAudio` on a null object.
=> Fix duplicated event listeners in ParticipantAnalyzer

src/components/CallView/shared/LocalVideo.vue, src/utils/webrtc/models/LocalMediaModel.js, src/utils/webrtc/simplewebrtc/localmedia.js, src/utils/webrtc/simplewebrtc/simplewebrtc.js
When getting the user media for the first time both audio and video are requested. If video is not available then the user media is got again requesting only audio. However, as the media constraints were reused in any following user media request as soon as video failed once it was never requested again. Therefore if a camera was plugged in later it was ignored until Talk was restarted.
Now getting the user media always tries first with both audio and video and then fallbacks to trying only with audio, even if video was not available in a previous request.
Besides that, now an error message is shown to the user if the video could not be got (except if the reason is that there is no camera).
- Start a call without a camera
- Plug in the camera (and wait a little so the …
=> Do not reuse media constraints between independent media requests

css/icons.scss, src/components/CallView/shared/LocalMediaControls.vue, src/components/CallView/shared/LocalVideo.vue
Use:
```diff
diff --git a/src/components/CallView/shared/LocalVideo.vue b/src/components/CallView/shared/LocalVideo.vue
index 317b113d0..cfacbb433 100644
--- a/src/components/CallView/shared/LocalVideo.vue
+++ b/src/components/CallView/shared/LocalVideo.vue
@@ -176,18 +175,21 @@ export default {
},
senderConnectionQualityAudioIsBad() {
+                       return true
return callAnalyzer
&& (callAnalyzer.attributes.senderConnectionQualityAudio === CONNECTION_QUALITY.VERY_BAD
|| callAnalyzer.attributes.senderConnectionQualityAudio === CONNECTION_QUALITY.NO_TRANSMITTED_DATA)
},
senderConnectionQualityVideoIsBad() {
+                       return true
return callAnalyzer
&& (callAnalyzer.attributes.senderConnectionQualityVideo === CONNECTION_QUALITY.VERY_BAD
|| …
```
=> Dedicated connection warning icon

src/components/CallView/LocalVideo.vue, src/utils/webrtc/models/LocalMediaModel.js, src/utils/webrtc/simplewebrtc/localmedia.js, src/utils/webrtc/simplewebrtc/simplewebrtc.js
=> [stable18] Do not reuse media constraints between independent media requests

css/icons.scss, package-lock.json, package.json, src/components/CallView/LocalMediaControls.vue, src/components/CallView/LocalVideo.vue, src/utils/webrtc/analyzers/AverageStatValue.js, src/utils/webrtc/analyzers/CallAnalyzer.js, src/utils/webrtc/analyzers/ParticipantAnalyzer.js, src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js, src/utils/webrtc/index.js, src/utils/webrtc/models/CallParticipantModel.js, src/utils/webrtc/models/LocalCallParticipantModel.js, src/utils/webrtc/webrtc.js, webpack.common.js
Requires #3926 
Backport of #3839, #3911 and #3907
=> [stable18] Warn user on high load

CHANGELOG.md
=> Changelog of july 21 updates

src/utils/webrtc/models/CallParticipantModel.js
Fixes (in the WebUI, but changes in the mobile apps are needed) #3937
When Janus is used even if it is possible to open several data channels with different labels and send data on them all the messages are received in the first data channel opened.
Although currently several data channels are opened in Talk in practice only the "status" data channel is used (and messages received in data channels with a different label are ignored). This is also the first data channel opened when Janus is used, so until now everything happened to work (with Janus 0.4.3).
However, with newer Janus versions the data channel messages are received instead on a data channel opened by Janus, which is named "JanusDataChannel". It is not possible to change that behaviour on Janus except by patching it, so for …
=> Fix speaker promotion with newer Janus versions

lib/Chat/ChatManager.php, lib/Chat/SystemMessage/Listener.php, src/services/filesSharingServices.js, src/utils/fileUpload.js, src/utils/temporaryMessage.js
=> Handle referenceId for system messages e.g. when uploading a file

src/components/AvatarWrapper/AvatarWrapper.vue
Fix #2575 
Before | After
---|---
=> Fix opacity of offline-user avatar menu

docs/standalone-signaling-api-v1.md, lib/Signaling/BackendNotifier.php, tests/php/Signaling/BackendNotifierTest.php
With https://github.com/strukturag/nextcloud-spreed-signaling/pull/28 the signaling server supports multiple backends, i.e. you can run a single signaling server for multiple Nextcloud instances. When a backend request reaches the signaling server, it must know from which Nextcloud instance it was sent - this PR adds the necessary header to the request.
Please also backport this to all supported versions of Talk.
=> Pass base URL of Nextcloud to signaling server in backend requests.

css/unified-search.scss, lib/AppInfo/Application.php, lib/Search/ConversationSearch.php, lib/Search/ConversationSearchResult.php, lib/Search/UnifiedSearchCSSLoader.php
Bright | Dark
---|---
Fix #3493
=> Conversations in Unified Search

CHANGELOG.md
- Fix compatibility with Janus 0.10.4 and the newest High-performance backend  [#3940](https://github.com/nextcloud/spreed/pull/3940)  [#3979](https://github.com/nextcloud/spreed/pull/3979)
- Allow Internet Explorer 11 to render the page again  [#3967](https://github.com/nextcloud/spreed/pull/3967)  [#3982](https://github.com/nextcloud/spreed/pull/3982)
- Only show the browser warning when interacting with Nextcloud Talk features  [#3978](https://github.com/nextcloud/spreed/pull/3978)
- Avatar menu is opaque for participants that are offline  [#3959](https://github.com/nextcloud/spreed/pull/3959)
- Always allow to communicate with the HPB even when it's a local url  [#3965](https://github.com/nextcloud/spreed/pull/3965)
=> Add Changelog for 9.0.3

src/components/MediaDevicesPreview.vue, src/components/MediaDevicesSelector.vue, src/components/RightSidebar/RightSidebar.vue, src/utils/webrtc/MediaDevicesManager.js, src/utils/webrtc/index.js, src/utils/webrtc/simplewebrtc/localmedia.js
Requires #3912
Fixes #358
This pull request adds a new _Preview_ tab to the right sidebar to select the audio and video devices to be used when a call is started, and also to be able to check whether the devices are properly working (or whether your lack of pants is visible or not before starting the call).
The `MediaDevices` Web API [provides device labels only if a stream is active or if permanent media permissions have been granted](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/label). Due to this a fallback label is generated to be used when the actual device label is unknown. This fallback label is persistent for the whole session, so if a device is connected, disconnected and connected again later after other devices have also been connected the same fallback …
=> Make possible to select input media devices before calls

css/At.scss, docs/chat.md, docs/participant.md, lib/Controller/ChatController.php, lib/Controller/RoomController.php, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue, src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue, src/mixins/userStatus.js, src/services/mentionsService.js, src/services/participantsService.js, tests/php/Controller/ChatControllerTest.php, tests/php/Controller/RoomControllerTest.php
* Status shown when away or dnd
* Status shown when away or dnd
* People with status sorted to the end of their section (moderator, online, user status)
> ![Bildschirmfoto von 2020-08-05 17-10-03](https://user-images.githubusercontent.com/213943/89430016-9373b780-d73e-11ea-8f9d-457b05917d35.png)
=> 💬 Status adaption for Nextcloud 20

css/icons.scss, lib/AppInfo/Application.php, lib/Dashboard/TalkPanel.php, lib/Dashboard/TalkWidget.php, package-lock.json, package.json, src/App.vue, src/dashboard.js, src/views/Dashboard.vue, webpack.common.js
For https://github.com/nextcloud/server/pull/21346
This implements a basic dashboard panel for Talk that lists the recent conversations. 
cc @nickvergessen @jancborchardt @ma12-co
=> 🍱 Dashboard adaption for Nextcloud 20

src/components/AdminSettings/HostedSignalingServer.vue, src/components/AdminSettings/SignalingServer.vue, src/components/AdminSettings/SignalingServers.vue
=> Relabel the sections to high-performance backend to avoid confusion

src/utils/signaling.js
This fixes a regression introduced in https://github.com/nextcloud/spreed/pull/3591/commits/eba73a3950c546bea7d47ede695dc030d55c72ad
When a reconnection is forced and the standalone signaling server is used [the participant joins again the conversation](https://github.com/nextcloud/spreed/blob/eba73a3950c546bea7d47ede695dc030d55c72ad/src/utils/signaling.js#L728) to get a new session, and then the websocket to the standalone signaling server is closed, which causes the reconnection with the signaling server. However, when the participant is a guest and joins again the previous session gets a `disinvite` message, which causes the browser [to be redirected to the main Talk page](https://github.com/nextcloud/spreed/blob/eba73a3950c546bea7d47ede695dc030d55c72ad/src/utils/signaling.js#L1126-L112 …
=> Fix forced reconnections for guests when the HPB is used

src/components/RightSidebar/RightSidebar.vue
Combine projects and settings into settings for the upcoming bridge settings from #4010 
Also had to change the id from `settings` to `settings-tab` as there was server css kicking in
`id="settings"` | `id="settings-tab"`
---|---
=> Add a combined settings tab

package-lock.json, src/App.vue, src/components/LeftSidebar/LeftSidebar.vue, src/components/MediaDevicesPreview.vue, src/components/MediaDevicesSelector.vue, src/components/RightSidebar/RightSidebar.vue, src/components/SettingsDialog/SettingsDialog.vue
=> Move talk global settings to settings dialog

src/components/MediaDevicesPreview.vue, src/utils/webrtc/MediaDevicesManager.js, src/utils/webrtc/index.js, src/utils/webrtc/models/LocalMediaModel.js, src/utils/webrtc/shims/MediaStream.js, src/utils/webrtc/shims/MediaStreamTrack.js, src/utils/webrtc/simplewebrtc/localmedia.js, src/utils/webrtc/simplewebrtc/peer.js, src/utils/webrtc/webrtc.js
Requires #4028 
Follow up to #3913
Fixes #358
When an input device is changed during a call the old audio or video track is stopped, a new one is requested, and then the old track is replaced by the new one in the RTCPeerConnection. (Surprisingly) In most cases just replacing the track causes the new track to be used (and if the new track is null then the sent media is simply stopped), nothing else is needed. If the new track is not compatible with the old one (for example, if the video uses a different orientation) a renegotiation is needed. Proper renegotiation is not currently supported by the web UI nor the mobile applications, so in this case a reconnection is forced.
Renegotiation is also needed if the call is started without audio or video and then an audio or video input device is …
=> Make possible to select input media devices during calls

src/components/TopBar/TopBar.vue
Note that this button is just a shortcut; it just force mutes the other participants all at once, instead of having to mute them one by one. Also, it only applies to the participants currently in the call; if another participant joins later that participant may not be muted.
=> Add button to moderation menu to mute all the other participants

src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/views/Dashboard.vue
```
/spreed/src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
49:80  warning  Expected 1 line break before closing tag (`</template>`), but 2 line breaks found  vue/multiline-html-element-content-newline
✖ 1 problem (0 errors, 1 warning)
/spreed/src/views/Dashboard.vue
34:21  warning  Expected 1 line break after opening tag (`<template>`), but no line breaks found    vue/singleline-html-element-content-newline
34:60  warning  Expected 1 line break before closing tag (`</template>`), but no line breaks found  vue/singleline-html-element-content-newline
✖ 2 problems (0 errors, 2 warnings)
```
=> Fix eslint warnings

src/components/MediaDevicesSelector.vue
Follow up to #4032 
The watcher that updated the selected option based on the `deviceId` passed to the component was not executed when the component was mounted, so it was undefined until something else modified that device ID.
This was not noticeable when the MediaDevicesPreview was shown in the sidebar, as in that case it was mounted once when the UI was loaded and never destroyed, but once moved to the SettingsDialog the component is created and destroyed whenever the dialog is open or closed.
- Open the settings dialog
- Close the settings dialog
- Open the settings dialog
The same devices that were selected before closing the dialog will be selected once it is opened again.
There will be no devices selected.
=> Fix MediaDevicesSelector not updated when mounted

src/components/MediaDevicesPreview.vue, src/utils/webrtc/MediaDevicesManager.js
Follow up to #3913
`Promise.finally` is available in older browsers for "hand-made" promises, probably due to a shim or to the code being transpiled (I have not checked). However, it is not available for internal promises returned by `navigator.mediaDevices.getUserMedia()`.
Moreover, in some browser versions (Firefox >= 58 && <= 68) there seems to be a clash between the internal promise and the shimed/transpiled one, as `Promise.finally` is available for `getUserMedia` promises, but not when used in Nextcloud.
Due to all that `finally` uses were replaced by a function called at the end of `then` and `catch`.
- Firefox < 58:
- Empty browser page:
- `new Promise((resolve, reject) => { setTimeout(() => { resolve() }, 1000) }).then(() => { console.log('Done') }).finally(() => { …
=> Do not use "finally" on promises returned by "getUserMedia"

CHANGELOG.md, appinfo/info.xml
- Implement unified search for messages  [#4017](https://github.com/nextcloud/spreed/pull/4017)
- Support for user status  [#3993](https://github.com/nextcloud/spreed/pull/3993)
- Moderators can now mute all participants in the moderator menu  [#4052](https://github.com/nextcloud/spreed/pull/4052)
- Allow changing the camera and microphone during a call  [#4023](https://github.com/nextcloud/spreed/pull/4023)
- Show upload progress and a preview when sharing a file into the chat  [#3988](https://github.com/nextcloud/spreed/pull/3988)
- Add a dashboard widget with unread mentions and active calls  [#3890](https://github.com/nextcloud/spreed/pull/3890)
- Add an emoji picker to the chat  [#3994](https://github.com/nextcloud/spreed/pull/3994)
- Hosted high-performance backend trial option in …
=> Add changelog for 10.0.0-beta.1

src/utils/webrtc/simplewebrtc/webrtc.js, src/utils/webrtc/webrtc.js
The Web UI sends `speaking` and `stoppedSpeaking` messages through the `status` and `hark` data channels, but the messages are simply ignored when received in the `hark` data channel. The Android and iOS apps do not even use the `hark` data channel, neither for sending nor for listening, so it can be fully removed.
Moreover, with latest Janus versions the peers receive all data channel messages in the `JanusDataChannel` data channel, no matter on which data channel they were originally sent. As the `speaking` and `stoppedSpeaking` messages are sent through the `status` data channel sending them too through the `hark` data channel caused the messages to be handled twice.
=> Get rid of "hark" data channel

src/components/CallView/Grid/Grid.vue, src/components/CallView/shared/LocalMediaControls.vue, src/components/CallView/shared/Video.vue, src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue, src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue, src/components/MessagesList/MessagesList.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/UploadEditor.vue
Also adds smooth scroll to the whole messageslist
=> Add scroll to bottom button

src/components/MessagesList/MessagesList.vue, src/components/TopBar/CallButton.vue
Follow up to #3931 
Before | After
---|---
=> Fix button color with bright primary color

src/components/CallView/CallView.vue
Fix #4078 
* Shown when the remote user has no video (before always for remote screenshares)
* Shown when the remote user has a screenshare and video
* Shown when you have a screenshare
=> Show other persons video when they share their screen

src/components/CallView/Grid/Grid.vue, src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue, src/components/MessagesList/MessagesList.vue
>  [Vue warn]: Property or method "scrollTobottomAriaLabel" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
>  [Vue warn]: Invalid prop: type check failed for prop "size". Expected Number with value 24, got String with value "24".
=> Fix scroll to bottom aria label

appinfo/routes.php, lib/Controller/MatterbridgeController.php, lib/MatterbridgeManager.php, src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue, src/services/matterbridgeService.js
Matterbridge process state is updated and displayed when saving bridge config and when showing log file content.
Seeing log file content is mandatory when setting up Ms-teams as Matterbridge provides a link to finalize sign-in in those logs.
Not sure about the "show mattberbridge log" button text and location.
=> Show bridge process state and log

lib/Controller/MatterbridgeSettingsController.php, lib/Exceptions/WrongPermissionsException.php, lib/MatterbridgeManager.php, lib/Settings/Admin/AdminSettings.php, src/components/AdminSettings/MatterbridgeIntegration.vue
File permissions are not preserved when Php extracts the talk_matterbridge app so the included binaries have 644 rights.
So we can either:
* Do it like this PR: add execution permission to the binary in Talk when checking its version. Might be a little bit repetitive but it's safe.
* Or do it in every talk_matterbridge migration scripts.
* Or do it via a post upgrade script (repair step) in talk_matterbridge.
I prefer the first solution because it's safer. It covers the cases where rights are changed or file is overwritten by a daring user after enabling matterbridge integration.
=> Make sure matterbridge binary is executable

CHANGELOG.md, appinfo/info.xml
* [spreed#3931](https://github.com/nextcloud/spreed/pull/3931) Add scroll to bottom button
* [spreed#4064](https://github.com/nextcloud/spreed/pull/4064) Use v-tooltip instead of popover for new group conversation's tooltip
* [spreed#4068](https://github.com/nextcloud/spreed/pull/4068) Get rid of "hark" data channel
* [spreed#4071](https://github.com/nextcloud/spreed/pull/4071) Make sidebars' captions bold
* [spreed#4073](https://github.com/nextcloud/spreed/pull/4073) Bump webpack-node-externals from 2.5.1 to 2.5.2
* [spreed#4074](https://github.com/nextcloud/spreed/pull/4074) Bump sass-loader from 9.0.3 to 10.0.1
* [spreed#4075](https://github.com/nextcloud/spreed/pull/4075) Add version recommendation, quota notes and test details to TURN server documentation
* …
=> Add changelog for 10.0.0-beta.2

src/components/LeftSidebar/ConversationsList/ConversationsList.vue, src/components/LeftSidebar/LeftSidebar.vue, src/components/LeftSidebar/SearchBox/SearchBox.vue, src/mixins/arrowNavigation.js
I was unable to manage a "fake hover" state which I guess should then also be keyboard navigateable.
But at least I got enter to work 😬
Fix #2816
=> Keyboard navigation for conversation search

lib/MatterbridgeManager.php
refs #4098 
Just using `nice -n19` to launch matterbridge processes.
=> Give low priority to matterbridge processes

lib/MatterbridgeManager.php
Matterbridge is supposed to watch changes in its config file but, for example, it does not disconnect from a removed part and continues forwarding messages there.
I think it safer to kill it and relaunch a new process when editing the config file.
=> Kill matterbridge before editing the config file

lib/Migration/Version2001Date20180103144447.php
Ref https://github.com/nextcloud/server/pull/22643
Since we always set it to `'0'` anyway, this is only an issue when updating from a previous version on Oracle. Since it didn't install, that is a non issue and we don't need to update the default on current versions.
=> Add a default on NotNull column

lib/Controller/ChatController.php, lib/Controller/RoomController.php, tests/php/Controller/ChatControllerTest.php
=> Don't leak the status when the app is disabled for the user

package-lock.json, package.json, src/views/Dashboard.vue
Now with 5 items on the half empty content view
Unluckily we didn't add the button option in the dashboard when it is completly empty, so can't get rid of that yet.
=> Bump vue-dashboard library

src/components/MessagesList/MessagesList.vue
Besides the memory leak fixed here, which was always reproducible, there seems to be another one related to the message list that happens sometimes (and apparently with Chromium, but not with Firefox :shrug:). After a lot of time and effort I have not been able to reproduce it reliably nor find why it happens either (it seems to be related to XMLHttpRequests/Axios and `getNewMessages()`, but other than that I am still clueless), so I give up for now :-(
- In Firefox, open a conversation with lots of messages
- Open the developer tools
- Take a memory snapshot; its size will be around 100MB
- Start and leave a call five times in a row
- In a different tab, open _about:memory_ and trigger a garbage collection (_Free memory -> GC_)
- In the previous tab, take another memory snapshot
The size …
=> Fix memory leak in message list

src/components/TopBar/TopBar.vue
Even if their code is identical two arrow functions are different instances, so the original one was not properly deregistered.
This caused a memory leak of the chat view or call view if the lobby is enabled while the user is in a conversation (due to the parent component reference of Vue, as that causes [the siblings of the `TopBar`](https://github.com/nextcloud/spreed/blob/389d7b6bfc16a29ced52cb41b0e7fbb5facbb4c9/src/views/MainView.vue#L5-L13) to be retained too).
=> Fix event handler deregistration in TopBar

src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue, src/store/participantsStore.js
1. Go to any page that uses the Avatar component to show your own avatar, e.g. a Talk conversation participant tab
2. Change your status
3. Wait until your avatar shows the new status :skull_and_crossbones: 
With this PR the text + emoji-icon will update. The dot-icon on the avatar will work after https://github.com/nextcloud/nextcloud-vue/pull/1405
Relevant event is emitted in server:
https://github.com/nextcloud/server/pull/22801
Fix #4132
=> Listen to the user status event to update the status immediately

src/components/CallView/shared/LocalMediaControls.vue, src/utils/webrtc/SpeakingWhileMutedWarner.js, src/utils/webrtc/analyzers/CallAnalyzer.js, src/utils/webrtc/analyzers/ParticipantAnalyzer.js, src/utils/webrtc/models/CallParticipantCollection.js, src/utils/webrtc/models/CallParticipantModel.js
Although this fixes some memory leaks the more relevant fixes are the event handler leaks, as they caused WebRTC events to be dispatched to objects from previous calls (although this **should** not have caused performance issues anyway due to the event handlers being pretty lightweight and the Vue components ignoring the models once they were no longer part of the `CallParticipantCollection`).
There are still some call related leaks, but I do not know yet how to fix them (or if they are actually browser bugs rather than Talk bugs), so something for another pull request.
=> Fix memory and event handler leaks in calls

src/components/MessagesList/MessagesList.vue
When getting new messages, [no matter if it succeeds or fails](https://github.com/nextcloud/spreed/blob/bbd0277f1057fb5c2cbe5431349c43cbfa6eec18/src/components/MessagesList/MessagesList.vue#L488-L509), another request is triggered again after a small delay. When the `MessagesList` component is destroyed the current request is cancelled, which [would stop further requests](https://github.com/nextcloud/spreed/blob/bbd0277f1057fb5c2cbe5431349c43cbfa6eec18/src/components/MessagesList/MessagesList.vue#L479-L482). However, if the `MessagesList` is destroyed during that delay there will be no current request yet, so once the timeout ends the request will start anyway, and thus the request loop will continue again and again.
This can be typically triggered [if the lobby is enabled while the user …
=> Fix getting messages again after the component was destroyed

src/utils/webrtc/simplewebrtc/localmedia.js, src/utils/webrtc/simplewebrtc/simplewebrtc.js
Follow up to #4052 
Before the UI only allowed to send the `forceMute` message to participants that were not muted. Now that moderators can mute all the other participants at once the message may be received by participants that are already muted, so it needs to be ignored in that case. Otherwise the user would see a _You have been muted by a moderator_ notification even if already muted.
Pending:
=> Ignore "forceMute" message if already muted

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
- Internet Explorer 11 unable to load the interface  [#3983](https://github.com/nextcloud/spreed/pull/3983)
- Speaker promotion with newer Janus versions  [#3952](https://github.com/nextcloud/spreed/pull/3952)
- Prevent infinite loop when opening a data channel and retransmitting old messages  [#4070](https://github.com/nextcloud/spreed/pull/4070)
- Installation on Oracle fails  [#4130](https://github.com/nextcloud/spreed/pull/4130)
- Fix clientside memory leaks due to missing unsubscribe of events when destroying interface components  [#4149](https://github.com/nextcloud/spreed/pull/4149)  [#4161](https://github.com/nextcloud/spreed/pull/4161)  [#4163](https://github.com/nextcloud/spreed/pull/4163)
=> Add changelog for 8.0.11

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
- Moderators can now mute all participants with a single button in the moderator menu  [#4054](https://github.com/nextcloud/spreed/pull/4054)
- Prevent infinite loop when opening a data channel and retransmitting old messages  [#4069](https://github.com/nextcloud/spreed/pull/4069)
- Installation on Oracle fails  [#4129](https://github.com/nextcloud/spreed/pull/4129)
- Fix clientside memory leaks due to missing unsubscribe of events when destroying interface components  [#4148](https://github.com/nextcloud/spreed/pull/4148)  [#4156](https://github.com/nextcloud/spreed/pull/4156)  [#4160](https://github.com/nextcloud/spreed/pull/4160)  [#4162](https://github.com/nextcloud/spreed/pull/4162)
=> Add changelog for 9.0.4

CHANGELOG.md, appinfo/info.xml
Signed-off
- Keyboard navigation for conversation search  [#3955](https://github.com/nextcloud/spreed/pull/3955)
- Don't leak the status to users that can't use the user status app  [#4137](https://github.com/nextcloud/spreed/pull/4137)
- Installation on Oracle fails  [#4127](https://github.com/nextcloud/spreed/pull/4127)
- Fix clientside memory leaks due to missing unsubscribe of events when destroying interface components  [#4139](https://github.com/nextcloud/spreed/pull/4139)  [#4140](https://github.com/nextcloud/spreed/pull/4140)  [#4154](https://github.com/nextcloud/spreed/pull/4154)  [#4155](https://github.com/nextcloud/spreed/pull/4155)
- Try to be more safe again errors when trying to get the Talk folder for attachments  [#4165](https://github.com/nextcloud/spreed/pull/4165)
- …
=> Add changelog for 10.0.0-rc.1

lib/GuestManager.php
Should remove all those queries from our query log:
```sql
SELECT * FROM `oc_talk_guests` WHERE `session_hash` IN (NULL)
```
Called from
https://github.com/nextcloud/spreed/blob/291e2c75f7b97cd8c1194b5a54cbf6b97193e981/lib/Controller/RoomController.php#L877-L881
=> If there are no sessions, we don't need to run a query

src/components/UploadEditor.vue
I think its more clear if we name the upload button at the second step of sending a file to chat as send, instead of upload, since it give you the impression you will upload a new file and not send it to the chat.
=> Change the upload button name from upload to send

lib/Collaboration/Resources/ConversationProvider.php, lib/Controller/PageController.php, lib/Controller/SignalingController.php, lib/Manager.php, lib/Notification/Notifier.php, lib/Share/Helper/DeletedShareAPIController.php, lib/Share/Helper/ShareAPIController.php, lib/Share/RoomShareProvider.php, tests/php/Notification/NotifierTest.php
Should reduce the number of those queries a lot:
```sql
SELECT * FROM `oc_talk_participants` WHERE (`user_id` = 'xxx') AND (`room_id` = '1234')
```
and will instead left join the participant on the initial query. That in itself is not a big help. But in case we ask for the same participant more than once (hint, happens every time), we save N-1 queries
it was 1122 queries of the 7873 in our query log
=> Less participant queries

lib/Controller/RoomController.php
The idea of this option was to not show the "leave" button when
you are the last "non-guest" user, so you need to delete it instead.
However this "neat" functionality could be out of date info,
if the other user already left in parallel.
So it doesn't qualify for the O(n) queries every 30 seconds.
=> Save the query to count the user for moderators per room every 30sec

lib/BackgroundJob/ExpireSignalingMessage.php, lib/BackgroundJob/RemoveEmptyRooms.php
=> Add missing parent::__construct() call to all background jobs

src/utils/webrtc/MediaDevicesManager.js, src/utils/webrtc/simplewebrtc/localmedia.js
Follow up to #3913
Before the selected input devices were used as long as the device was still available and Talk was still open. However, if the device was disconnected and connected it was not automatically selected again, even if Talk was still open. Now the last selected device of each kind is remembered, so it will be automatically used if available when joining a call, even if it was disconnected and connected or if Talk was closed and opened.
Additionally, if audio or video devices were explicitly disabled this will also be remembered and respected when Talk is open again.
Note that the last selected device is automatically used if available when joining a call, but it will not be automatically used if it becomes available during a call. While it would be possible to do that at …
=> Remember selected input devices

src/FilesSidebarTabApp.vue
Fixes #4221
Due to [changes in nextcloud-vue 2.4.0](https://github.com/nextcloud/nextcloud-vue/commit/124543828c047bd6852676247e68d5c1fbf4bda3) the scroll bar was shown for the whole sidebar in the Files app. Now it is shown again only for the chat tab.
Besides that, due to [changes in nextcloud-vue 2.0.0](https://github.com/nextcloud/nextcloud-vue/commit/33f4af39f14648429650db6ca3319786188ec3a6) the message and button to join the conversation was shown too low and it had no scroll bar if there was not enough space. Now it is centered in the chat tab and shows a scroll bar if needed.
=> Fix height in Talk sidebar in Files app

src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
Added missing "nowrap" and increased width.
Fixes https://github.com/nextcloud/spreed/issues/3947
=> Fixed contact selection bubble wrapping

src/components/RightSidebar/RightSidebar.vue
When scrolling up, the participants are not visible any more above the
search box.
This is a minimal quick-fix.
A proper way might need to reconsider the structure of the panel and move the scrolling container to start below the search box (vertically).
=> Fix participants list search box overlap

package-lock.json, package.json, src/App.vue, src/FilesSidebarCallViewApp.vue, src/FilesSidebarTabApp.vue, src/PublicShareAuthRequestPasswordButton.vue, src/PublicShareSidebar.vue, webpack.common.js
=> Import dialogs scss

src/components/TopBar/CallButton.vue
It causes unnecessary load on Chrome browser.
Discovered and confirmed by @danxuliu
=> Remove pulse animation from call button

src/components/RightSidebar/Participants/ParticipantsTab.vue
Adjusted placeholder text of the search box at the top of the
participant list, to make it clearer that one can also simply search for
participants, not only add new ones.
@nickvergessen as discussed when mentioned in the context for the conference with 400+ participants.
Later on we might also want to show that field for regular users just for the search, raised here: https://github.com/nextcloud/spreed/issues/4299
=> Clarify participant search box in conversation

lib/Collaboration/Resources/Listener.php
- In the files app, link a file to a conversation
- In Talk, open that conversation
- Add a user to the conversation
No errors are shown in the logs
Errors `Undefined index: user_id at /var/www/html/apps/spreed/lib/Collaboration/Resources/Listener.php#68` and `#69` are shown in the logs
=> Fix key name in collaboration resource listener for add user event

src/components/ConversationIcon.vue
=> Fix menu position for left sidebar avatars

lib/Chat/CommentsManager.php
=> Comments manager uses the PSR logger now

src/components/TopBar/TopBar.vue
Fixes #3424
Due to [a change in the underlying component](https://github.com/nextcloud/nextcloud-vue/pull/861) (_@nextcloud/vue_ 1.3.1 works fine in _stable18_, but the issue appears when bumping it to 1.4.0) a date given as a timestamp is no longer automatically converted to a Date object, so it needs to be explicitly done.
=> Fix lobby date not shown in moderation menu

src/components/NewMessageForm/NewMessageForm.vue, src/store/fileUploadStore.js
After starting an upload or sharing a file, set the focus back to the message field.
=> Focus message field after upload or sharing file

src/components/RightSidebar/RightSidebar.vue, src/store/conversationsStore.js
After renaming a conversation, set the name back into the state for
immediate display instead of waiting for the next signal/event many
seconds later.
I fixed this because it annoyed me to not see the change immediately, made it look broken.
Maybe this implementation is too naive and there is more complexity on the server side than I saw ?
So far I didn't understand the difference between "name", "displayName" and "roomName", but "displayName" is what gets displayed. Are there other scenarios I need to understand and test ?
=> Update conversation name directly after call returns

src/components/ChatView.vue, src/components/MessagesList/MessagesGroup/Message/Message.vue, src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue, src/components/NewMessageForm/NewMessageForm.vue, src/components/TopBar/CallButton.vue, src/components/TopBar/TopBar.vue, src/services/conversationsService.js, src/store/conversationsStore.js
Added logic for setting a conversation to read-only.
Fixes https://github.com/nextcloud/spreed/issues/1647
- to be discussed as one might prefer to call it "(locked)", "(archived)" or whatever and the suffix interferes with renaming. maybe lock icon still better
=> Add checkbox for locking conversation

src/utils/webrtc/simplewebrtc/simplewebrtc.js, src/utils/webrtc/webrtc.js
When the HPB is used it is possible to know when the local participant has established a connection with a remote participant, but it is not possible to know when a remote participant established a connection with the local one.  The initial state (audio and video on or off) was sent just once when the local participant establishes a connection with the remote one, which caused that, in some cases, the message was received by the remote participant before a connection was established with the local one and thus ignored.
Even if there is code to try to locally detect the initial media state of the remote participant it has shown to not be as reliable as desirable, which causes a wrong media state to be sometimes shown for remote participants until the participant changes it again (or …
=> Improve setting initial audio and video status when the HPB is used

src/components/CallView/shared/VideoBackground.vue
Whenever the speaker changes, the avatar background can flicker due to
HTTP calls. This fix improves it a bit by caching the information
whether the user has an avatar or not, so allows a less delayed loading of
the avatar background.
This only affects the avatar background.
For the avatar itself, you also need https://github.com/nextcloud/nextcloud-vue/pull/1457 in place.
Best is to test both together.
=> Cache hasAvatar to avoid call background flickering

src/components/CallView/CallView.vue
When selecting the already promoted screen, this prevents an additional
video element to be rendered which would duplicate whatever the user is
already seeing.
Fixes https://github.com/nextcloud/spreed/issues/4382
@ma12-co can you verify the reasoning ? Not sure if there are other potential flaws/holes.
I only saw this happen for screen sharing, not regular videos.
=> Don't render extra videos when selecting promoted

src/assets/variables.scss, src/components/CallView/CallView.vue, src/components/CallView/Grid/Grid.vue, src/components/CallView/shared/LocalMediaControls.vue, src/components/CallView/shared/LocalVideo.vue
To be able to focus on the video / screen of the current presenter.
Fixes https://github.com/nextcloud/spreed/issues/4245
=> Add ability to collapse the grid view

src/components/CallView/shared/EmptyCallView.vue
Make it the same grey like the stripe background and adjust text color
to be readable.
Fixes https://github.com/nextcloud/spreed/issues/4388
=> Fix empty call background color

lib/MatterbridgeManager.php
On Busybox (used by Alpine Linux used by Nextcloud Docker image), `ps` command has a slightly different syntax.
* fix `ps` call when tying to kill zombie bridge processes
* use a larger filter when searching for zombie processes
* fix `ps` call when determining if a process is running
This syntax has been tested on Alpine Linux, Debian and Ubuntu.
refs #4337
=> Use generic syntax when calling 'ps' command

src/components/CallView/shared/EmptyCallView.vue
Use hard-coded values instead of variables to keep it static regardless
of theme or dark mode.
The final result is the same like in https://github.com/nextcloud/spreed/pull/4408 in regular mode
=> Adjust empty call view colors

src/components/MessagesList/MessagesList.vue, src/components/NewMessageForm/NewMessageForm.vue
fix: #4378 
fix: #4377
Removes global smooth scrolling of the container and smooth scrolls it only when needed
=> Fix chat scrolling

lib/Files/TemplateLoader.php, webpack.common.js
`mainFilesSidebar.js` and `mainFilesSidebarLoader.js` were both bundled in separate files, and both files were loaded on their own. Due to this each loaded file had its own instance of the JavaScript modules instead of using a shared one, which for example caused conversations to not be properly left when the sidebar of a folder was opened. Now both files are bundled in a single file, so all the elements act on the same shared state.
Note that the steps below refer to one scenario in which the bug can be noticed, but there are others (for example, with the HPB it prevents joining calls when opening the chat tab of a file again after opening the sidebar in a directory). And independently of those issues it causes an unneeded built JavaScript file of 1MiB to be loaded in the Files app. Due …
=> Fix isolated modules in Files app sidebar
