- tests/integration/run.sh
Tested that Drone fails; see results of [removed commits](https://github.com/nextcloud/spreed/compare/dd373519ea65d0a09e1a9026a1467c0c6967e6a9..71304320902ccdea37b84fd8abca30d7dbda4992): https://drone.nextcloud.com/nextcloud/spreed/9501 https://drone.nextcloud.com/nextcloud/spreed/9502
> Abort integration tests if Talk or helper apps can not be installed

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/EmptyCallView.vue
This is meant to be tested with server in fd178b92f63^ (as Talk master is not yet compatible with the Files sidebar changes introduced in nextcloud/server@fd178b9).
Although this became specially noticeable after #4408 it was already broken in previous versions (as the call view height was reduced when someone else joined the call), hence the backport to _stable20_ (it also happens in _stable19_ and _stable18_, so feel free to backport to them too if you want, but as it is "just" a style issue I only backported to _stable20_ to begin with).
**Before:**
**After:**
> Fix empty call view position in sidebar

- lib/Controller/RoomController.php
- src/App.vue
- src/views/SessionConflictView.vue
> Only show the conflict warning when the session was in a call

- src/components/MessagesList/MessagesList.vue
Copying an array just for the sake of reverse iteration is a bit wasteful, especially with bigger arrays.
Tested by sending quickly multiple messages. They were all properly replaced in the list. (hope it's the correct test case)
> Don't copy array for reverse iteration

- src/views/Dashboard.vue
> Show favorite conversations at the top of the dashboard empty content

- docs/capabilities.md
- lib/Capabilities.php
- lib/Chat/Parser/SystemMessage.php
- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- tests/php/CapabilitiesTest.php
- tests/php/Chat/Parser/SystemMessageTest.php
As this touched the same code, I've gathered them into a single PR.
Chat previews now expanded with aspect ratio
Instead of cropping the previews in the conversation to a square, they are now using a limited height but their width is computed based on aspect ratio. This is done by passing different arguments to the previews endpoint so it delivers a preview with the matching size.     
Also expanded image preview height to 384 as it looks better.
Fixes https://github.com/nextcloud/spreed/issues/3746
Use direct URL to render GIFs (animated!) when they have a small size.
The maximum size is configurable with `occ config:app:set spreed max-gif-size --value=X` and exposed as the capability `spreed.config.previews.max-gif-size`
Fixes https://github.com/nextcloud/spreed/issues/1805
Guest users …
> Improve previews for guests + GIF support

- lib/Chat/AutoComplete/Sorter.php
- lib/Chat/ChatManager.php
- lib/Chat/Parser/UserMention.php
- lib/Manager.php
- lib/Notification/Notifier.php
- psalm.xml
- tests/psalm-baseline.xml
- tests/stubs/oc_comments_manager.php
Fixes https://github.com/nextcloud/spreed/issues/4481
The application's container will now always map ICommentsManager to
the app's CommentsManager instance instead of the one from server.
All the usages were replaced to use ICommentsManager now except for
lib/Manager which requires access to the extra method.
This made it possible to reduce the number of skipped Psalm warnings and
made sure there is no possible mix up of manager classes.
Signed-off-by: Vincent Petry <vincent@nextcloud.com>
> Always use CommentsManager from the app

- package-lock.json
- package.json
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
This brings in:
- the new edit component (which we can replace later in https://github.com/nextcloud/spreed/pull/4333)
- Scrollable app sidebar (which is the reason for major bump)
- Avatar caching.
- Other small things
I did a quick test to see if all still works:
Obsoletes https://github.com/nextcloud/spreed/pull/4457
> Bump @nextcloud/vue to 3.1.0

- src/components/CallView/shared/LocalVideo.vue
- src/utils/webrtc/webrtc.js
Added default timeout instead of permanent for messages related to
denied permissions.
Fixes https://github.com/nextcloud/spreed/issues/4407
> Improve call error messages UX

- src/components/NewMessageForm/NewMessageForm.vue
- src/store/fileUploadStore.js
- src/utils/fileUpload.js
- src/utils/temporaryMessage.js
Use the modified date and extension from the file itself
to generate a new file name.
This is a better alternative than accepting the default name
"image.png".
Fixes https://github.com/nextcloud/spreed/issues/3543
> Auto-rename pasted files

- src/components/NewMessageForm/NewMessageForm.vue
Fixes https://github.com/nextcloud/spreed/issues/4492
Seems this is already enough, tested on Firefox and Chromium.
> Remove double scrollbar in call chat view

- package-lock.json
- package.json
- src/components/CallView/shared/VideoBackground.vue
Fixes https://github.com/nextcloud/spreed/issues/4501
Brings in:
- fix for high energy impact: https://github.com/nextcloud/spreed/issues/4501
- fix for avatar flickering (caching hasAvatar): https://github.com/nextcloud/spreed/issues/4284
- backport of background avatar flickering: https://github.com/nextcloud/spreed/pull/4379 (because it goes with the above)
Regression testing:
Test for additions:
> [stable20] Update nextcloud-vue from 2.6.8 to 2.8.2

- src/components/TopBar/CallButton.vue
- src/store/callViewStore.js
Fixes https://github.com/nextcloud/spreed/issues/3824
Please note that joinCall and leaveCall are actions already defined in the participantsStore.
Nevertheless, vuex will call the action on both the stores! :smile:
> Remember grid view state per call

- src/store/callViewStore.js
> Fix remembered grid state per call

- src/components/NewMessageForm/NewMessageForm.vue
There was a mix up of handlers that made all uploads be automatically
renamed.
This properly rewires the handlers to only autorename whenever the event
was a paste.
> Only autorename uploads on paste

- src/components/UploadEditor.vue
Makes it possible to submit directly with enter after pasting
Fixes https://github.com/nextcloud/spreed/issues/4536
> Focus on submit button by default in upload dialog

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Follow up to #4472 
- refactor preview type handling to make it more accessible instead of having to rely on multiple flags
- detect mime icon and failed cases and adjust the icon height accordingly
1. Create a text file "corrupt-image.txt" with some contents and rename to "corrupt-image.jpg"
1. Create another text file "data.dat"
1. Upload both to a converstion
Tiny mime type icon and tiny failed icon
Bigger mime type icons
> Fix mime icon and failed icon height

- src/components/NewMessageForm/NewMessageForm.vue
To upload files a hidden file input is "clicked", which shows the browser dialog to pick the files, and [the `change` event of the file input is listened to to know the selected files](https://github.com/nextcloud/spreed/blob/6a92e53b8c8556d25c5504ac7e3e414867438be0/src/components/NewMessageForm/NewMessageForm.vue#L31).
However, although Firefox always emits the `change` event when files are selected, Chromium only emits the `change` event if the selected files have changed since the last time. Due to this if a file was uploaded and then the same file was tried to be uploaded again nothing happened.
Now the value of the file input is cleared (which also clears the files from the file input) after the files are handled to ensure that there is no previous state when the browser dialog is …
> Fix uploading same file twice in a row in Chromium

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/components/NewMessageForm/NewMessageForm.vue
Fixes an issue where a chat in the files sidebar would trigger a warning
because the conversation list element don't exist there. See https://github.com/nextcloud/spreed/pull/4291#issuecomment-708979771
When posting a message, an event is now triggered so other components
could react on it.
The conversation list will now take the responsibility of scrolling the
current conversation into view after posting, instead of the
NewMessageForm.
The behavior is also adjusted to always scroll regardless where the
conversation is located in the list.
@ma12-co not sure why this was limited to only when it moves to the top.
I tested also by clicking on a conversation at the bottom of list, then scrolling up, then posting: it will now scroll down to highlight the conversation even when at the bottom. …
> Rework scroll into view of conversation after post

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Instead of displaying file names below attachments in a conversations,
like for images, it is now displayed only on hover in a tooltip.
Howver, in the upload editor the file names are still shown as they can
be helpful in that situation.
This cleans up the message list a bit and also solves some layout issues
with images in narrow views like the sidebar.
~~Fixes https://github.com/nextcloud/spreed/issues/4494~~ the latter ticket will still exist for cases where file name is visible
> Move the filename of attachments to a tooltip

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/SettingsDialog/SettingsDialog.vue
> Use new app settings components

- lib/Chat/Command/Executor.php
- lib/Chat/Command/Listener.php
- Add a Talk command available only for moderators
- Join a conversation as a user or guest
- Send the command
_The command does not exist_ is shown only for that participant
The raw command (for example, _/calc 1+2_) is shown for everyone
- Add a Talk command available only for moderators
- Join a conversation as a user or guest
- Send a "/help" message
Only the commands that the participant is allowed to use are shown
The list of available commands also include those that the participant is not allowed to use
> Fix handling of unavailable commands

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/TopBar/TopBar.vue
- src/store/callViewStore.js
When a presentation starts (screen share), remember the grid + stripe
state then switch to presenter mode (no grid + no stripe).
When the presentation stops (last screen share stops), restores the grid
+ stripe state, unless the user has changed the state during the
presentation.
Stripe mode is now also remembered for each call.
Fixes https://github.com/nextcloud/spreed/issues/4441
> Remember call view state during presentation

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Added ellipsis on long participant names.
Added conditional tooltip on participant + status:
Whenever the participant name or status is ellipsized, a tooltip will be available for those entries.    
To check the "is ellipsized" condition, a ResizeObserver is used to update. To avoid trying to measure and update too many participants in the list, the observer only activates after 10+ characters, which is the limit of chinese characters that still fit within the sidebar minimum width of 300px.
Note that in the future once we use virtual scroll for the participant list, we likely won't need to worry about resize optimization.
Fixes https://github.com/nextcloud/spreed/issues/4500
Note: if the user name has no space, the tooltip breaks the layout, this is a bug in the tooltip library and needs …
> Fix long participant name + status in participant list with tooltip

- src/components/ChatView.vue
This brings back the scrolling behavior to the "scroller" element, so
that the matching logic can rely on it.
This also makes the message form align to the bottom whenever there are
not enough chat messages to expand the container vertically.
Fixes https://github.com/nextcloud/spreed/issues/4527
Obsoletes https://github.com/nextcloud/spreed/pull/4529
> Fix sidebar chat scroll container + size

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Whenever a video preview of GIF preview (not direct) is displayed, add a play button to make it clear that what is here is not a picture but a playable video.
When testing, make sure to have the `Movie` preview provider enabled.
> Add play button on top of video or gif previews

- src/components/RightSidebar/RightSidebar.vue
Added tooltip for room names in case they are too long.
Note: the tooltip appears regardless of length.
> Add tooltip for long room names.

- src/components/TopBar/TopBar.vue
When in chat view, increase the space on the right of the top right to
make sure the user can still grab the scroll bar.
In call view that space is set back to zero.
Fixes https://github.com/nextcloud/spreed/issues/4586
> Increase top bar space from the right

- src/components/LoadingPlaceholder.vue
Fixes https://github.com/nextcloud/spreed/issues/4553
Replaced the SVG gradient animation with a CSS opacity animation that fades between two lists, one with the regular gradient and one with the reversed one.
See ticket for details about analysis.
The fix reduces the CPU load for me from 54% to ~20 %
> Improve loading placeholder animation performance

- lib/Signaling/BackendNotifier.php
Seems the non deprecated way we use is https://github.com/nextcloud/server/pull/24037
is more case sensitive.
In any case. This hopefully fixes it.
> Fix casing of IURLGenerator to fix DI

- src/FilesSidebarTabApp.vue
Due to recent changes to the scroll component, the
call button in sidebar chat needs to be
adjusted to float on top of the chat.
Before:
After:
Note: the double scrollbar is unrelated. The bigger scrollbar is the one from the files app as I have enough files to make it scroll.
Fixes https://github.com/nextcloud/spreed/pull/4530#issuecomment-726682617
> Fix call button overlap in sidebar chat

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
Whenever only the URL hash changes despite the token staying the same, a
route change event is still triggered.
This fix avoids leaving and re-joining the same conversation.
Fixes an issue where clicking a search result would trigger both the
event that leaves the conversation within a route change and a page
unload event, which also leaves the same conversation.
Fixes https://github.com/nextcloud/spreed/issues/4592
- searching within current conversation: https://github.com/nextcloud/spreed/issues/4592#issue-742379306
- joining non-current conversation X through search link, then clicking X again to clear the hash: https://github.com/nextcloud/spreed/issues/4592#issuecomment-726745488
> Don't leave conversation on URL hash change

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
In the conversation view, regular users can now also search/filter in
the sidebar. They don't get the option to add participants like
moderators do.
Fixes https://github.com/nextcloud/spreed/issues/4299
Can search and add.
Can only search/filter.
Note: the "Participants" header is removed as it doesn't make sense with only one result section.
No search box, as before.
> Allow regular users to filter participants

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/Quote.vue
Fixes https://github.com/nextcloud/spreed/issues/4516
When clicking on a quote, we scroll to it and now there's a new
highlight animation that fades out
The animation and scrolling logic was moved from the Quote vue to the
Message vue. The Quote vue will now only send an event to tell that we
want to focus a specific message.
A DOM-level method was used for triggering the highlight to be able to
access it with document.getElementById() as it's cheaper than trying to
look up the message by id within the collection of MessagesList.
If the latter is not wanted we should then rework the messages structure inside of MessagesList to have the messages in an associative array with message id as key. Or build yet another index-like structure to be able to find the messages. So far for this use …
> Highlight quote after scrolling to it

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/Quote.vue
Fixes https://github.com/nextcloud/spreed/issues/4494
- Removes spacing of label under the preview 
- Reduce "small" preview size from 64 to 32 to prevent scrollbars in the reply box
- Attempt to move the preview size values to SCSS variables to be imported also in JS
The latter with SCSS variables doesn't work, the imported structure is always an empty hash.
This should work according to many sources:
- https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript
- https://css-tricks.com/getting-javascript-to-talk-to-css-and-sass/
- https://stackoverflow.com/questions/56523785/exporting-scss-variables-to-js-auto-looping-variables
- https://github.com/webpack-contrib/css-loader (search for ":export")
I guess I'll revert the last commit and stick to hard-coded values …
> Fix preview spacing

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Fixed call icon vertical alignment.
Adjusted ellipsis width calculation to take the icon into account when
present.
@nickvergessen as discussed
with status line:
> Adjust call icon positioning in participant list

- src/components/CallView/CallView.vue
1. Setup a call with three participants
1. Have participant 1 share the screen
1. Wait for screen share to appear
1. Have participant 2 switch to grid view
The screen share appears both in the grid and big on top of it.
The screen share does not appear big on top but only inside the grid.
Regression from Talk 10.0
> Don't show big screen share while in grid mode

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
When the URL changes, the check whether we switched conversations need
to read the token for the correct attribute, which is "params".
Fixes https://github.com/nextcloud/spreed/issues/4631
> Grab the token from the correct attribute

- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/simplewebrtc/simplewebrtc.js
- src/utils/webrtc/webrtc.js
Requires #4181
~~(Kept as draft until #4181 is merged, but ready to review nevertheless)~~
Since the introduction of the HPB the nick has been sent over and over again every second, as it is not possible to know when other participants have established a data channel connection (and neither to associate a signaling id with a Nextcloud id to get the nick from the participant list).
However, it is possible to know when other participants join the call, and it is safe to assume that the other participant established a connection with the local one after a "reasonable" amount of time.
As sending the nick every second is too aggressive (specially in calls with a lot of users) now the nick is sent when the local participant establishes a connection with the remote one and, as that does not …
> Stop sending the nick through data channels after some time

- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/CallView/CallView.vue
Fixes chat in sidebar for video verification and when chatting about a
file from a public link.
I tried to set "position: relative" for chatView in general but it would then break scrolling during a logged in call, so I went for a more localized solution (for now).
Fixes https://github.com/nextcloud/spreed/issues/4636
Note: the video won't appear in video verification because of that other bug related to "disable grid view in sidebar": https://github.com/nextcloud/spreed/pull/4573
> Fix public page calls

- src/components/Caption.vue
- src/components/ChatView.vue
- src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/Quote.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/TopBar/TopBar.vue
See individual commit descriptions.
I originally tried to go further and add invisible text to make it say "Message from Alice: hello" but somehow the screen reader doesn't read it in once sentence.
Also I was hoping that ul/li would make navigation easier like making it read each row in the participant list or messages list, but it rather reads individual blocks inside a row. Maybe we'll need to introduce links there at some point... would make it possible to link to messages. In the conversation list we have links and it works well there.
Needs further separate research.
> A few accessibility tweaks

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/Video.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/UploadEditor.vue
The vue material design icons library sets a default title to the icon
components. This fix sets this to empty to prevent the browser tooltip
to appear.
No more tooltip
Discovered here: https://github.com/nextcloud/spreed/pull/4621#discussion_r525302207
> Set empty title for material design icons

- src/App.vue
- src/FilesSidebarCallViewApp.vue
- src/PublicShareSidebar.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/TopBar/CallButton.vue
- src/mixins/isInCall.js
- src/mixins/participant.js
- src/views/MainView.vue
To remove duplication of the "get current participant" logic all over
the place and also for future use.
Open issue:
Tested based on the diff:
> Introduce participant mixin

- lib/Controller/SignalingController.php
> Load new participants by actor when the session does not exist yet

- src/components/CallView/CallView.vue
Fix copy-paste issue, replacing "$on" with "$off" when unmounting the
call view.
Might need a backport or cherry-pick in case this will be part of a bigger backport related to SIP.
> Unregister refreshPeerList on unmount

- docs/participant.md
- lib/Controller/RoomController.php
- lib/PublicShareAuth/Listener.php
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/password-request.feature
This fixes a regression introduced in 4afa2d7946, as well as an UI fix that I thought that was a regression but seems to have been missing since the beginning :facepalm:.
The active guests are only those who are currently in a call, and not those who are currently in the conversation. Therefore other guests or users were not prevented from joining a password request conversation if a guest was in the conversation but not in the call.
Fortunately in practice this was not a problem, as the Web UI starts a call immediately after joining the conversation, which made the guest immediately active and thus prevented others from joining.
Besides that it adds integration tests for password request conversations.
Pending:
> Fix user management in password request rooms

- src/components/CallView/CallView.vue
When in sidebar, use the same size as the video for properly centering
the media controls.
Fixes https://github.com/nextcloud/spreed/issues/4668
This was caused by the changes related to the stripe collapsing.
> Adjust local media control position in sidebar

- src/components/CallView/CallView.vue
- src/components/CallView/shared/LocalVideo.vue
Remove hover effect and ignore clicks on a local video when in sidebar
mode, to prevent following self.
Fixes https://github.com/nextcloud/spreed/issues/4574
> Disallow following self in sidebar mode

- src/App.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/ConversationSettings/ModerationSettings.vue
- src/components/ConversationSettings/SipSettings.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBar.vue
- src/store/conversationsStore.js
For https://github.com/nextcloud/spreed/issues/4007
See https://github.com/nextcloud/spreed/pull/4576#issuecomment-731219492
- ~~remove lobby + locking panels while in call~~
> Move conversation menu options to a dialog

- composer.json
1. Run `composer install`
2. Run `psalm --threads=1 lib/Controller/SignalingController.php`
No errors
```
ERROR: UndefinedClass - lib/Controller/SignalingController.php:53:35 - Class or interface OCP\AppFramework\OCSController does not exist (see https://psalm.dev/019)
class SignalingController extends OCSController {
------------------------------
1 errors found
------------------------------
Checks took 0.69 seconds and used 115.912MB of memory
Psalm was able to infer types for 95.2155% of the codebase
```
No errors reported.
This is because passing in a single file makes it ignore the directories that are included in psalm.xml.
According to the psalm docs, it uses the autoloader from composer to locate those packages. However, our autoloader did not include neither …
> Help psalm find context when running single files

- src/components/CallView/CallView.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoBottomBar.vue
Don't show controls when following own video.
Fix missing label for going back.
Fixes https://github.com/nextcloud/spreed/issues/4688
After seeing this I was bothered that my own video was still visible, so I directly looked into hiding it, which led me to do this for all the follow modes:
After following, start presentation mode which will internally remember the last state. When unfollowing, stop presentation mode which will restore the previous state, unless tempered with previously.
This will now also automatically collapse the stripe and the own video when following.
This adresses the comment in https://github.com/nextcloud/spreed/issues/3518#issuecomment-676600694
> Fix follow self + remember state after unfollowing + collapse stripe

- package-lock.json
- package.json
Brings in the fix for using material design icons in ActionButtons, needed by #4569
> Bump @nextcloud-vue from 3.3.0 to 3.3.1

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fixes copying of multiple messages.
Now only the message bodies are included and no more timestamps.
1. Send a message "one message"
2. Send a message "second line"
3. Send a message "third, repeat"
4. With the mouse, start dragging before the "o" and down to the end of "repeat" to select the messages
5. Right click + copy
6. Paste into a text editor
Timestamps included:
```
one message
second line
15:41
third, repeat
```
No more timestamps:
```
one message
second line
third, repeat
```
> Don't select timestamp but selecting messages

- src/App.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/TopBar/TopBar.vue
When holding a shortcut key like "m" for mute, don't repeat the call to
the handler to avoid flickering.
1. Start a call with a webcam
1. Hold the "v" key
Disco!
No more disco.
> Don't repeat calls to handler when using short keys

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/sip-dialin.feature
> Integration tests for sip

- lib/MatterbridgeManager.php
- src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
[Matterbridge sample config file](https://github.com/42wim/matterbridge/blob/0d7315249d20bf9856605068074a7b6c6bcce835/matterbridge.toml.sample#L1825) mentions an incorrect config key for the channel.
This fix has been tested in #4719.
> Fix telegram channel config key

- appinfo/info.xml
- docs/capabilities.md
- docs/chat.md
- docs/constants.md
- docs/conversation.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Config.php
- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Controller/SettingsController.php
- lib/Migration/Version11000Date20201204110210.php
- lib/Model/Attendee.php
- lib/Model/AttendeeMapper.php
- lib/Participant.php
- lib/Service/ParticipantService.php
- lib/TInitialState.php
- psalm.xml
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/constants.js
- src/services/messagesService.js
- src/services/settingsService.js
- src/store/conversationsStore.js
- src/store/index.js
- src/store/settingsStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/read-status.feature
- tests/php/CapabilitiesTest.php
> ✔️✔️ Read status for chat messages

- lib/Share/Helper/ShareAPIController.php
With this and https://github.com/nextcloud/server/pull/24605/commits/8131965b740377cad5c64910ea76070cbf81868a from https://github.com/nextcloud/server/pull/24605 it is now possible to navigate to a talk room from the files sidebar by clicking on the share entry.
> Link shared room in the files sidebar sharing tab

- appinfo/info.xml
- lib/GuestManager.php
- lib/Migration/Version11000Date20201209142525.php
- lib/Migration/Version11000Date20201209142526.php
- lib/Migration/Version2001Date20171026134605.php
- lib/Signaling/Messages.php
- psalm.xml
- tests/integration/spreedcheats/lib/Controller/ApiController.php
> Create a new table for internal signaling and guest names with a PK

- lib/Migration/Version11000Date20201209142525.php
Regression from #4735 
Only breaks on Oracle and SQLite, where index names have to be database-wide unique
Extracted from #4589 to make sure @jancborchardt can update on sqlite
Not adding a migration as it has not been released.
> Use a unique index name

- tests/integration/run.sh
From https://github.com/nextcloud/spreed/pull/4706
> [stable20.1] Abort php test server on ctrl+c

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/services/conversationsService.js
- src/utils/cancelableRequest.js
The code is in the very last commit if you want to have a peek.
> Cancel search while typing

- docs/chat.md
- lib/Controller/ChatController.php
- tests/php/Controller/ChatControllerTest.php
We need to set the status code to 200 when the header is modified,
because as per "section 10.3.5 of RFC 2616" entity headers shall be
stripped out on 304: https://stackoverflow.com/a/17822709
This means the header would not be sent to the clients at all, so
they wouldn't update the read marker when idling in the chat.
For the web interface this is not needed, as we update the info
every 30 seconds with the conversation list refresh and can therefor
save the query
> Allow to respond with modified common read value on "not modified" messages

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Fixes https://github.com/nextcloud/spreed/issues/4758
I've tested this with all three buttons
> Close participant context menu after action

- .github/workflows/oci.yml
- lib/Manager.php
- lib/Migration/CreateHelpCommand.php
- lib/Model/CommandMapper.php
- lib/Model/SelectHelper.php
- lib/Room.php
- lib/Service/CommandService.php
- lib/Service/ParticipantService.php
> Test against oracle

- lib/PublicShareAuth/TemplateLoader.php
Whenever the video verification has not been set for a share, do not
display the button "Request password" in the public link page.
Somehow it looks like there was no test anywhere before, maybe it was always missing ?
Fixes https://github.com/nextcloud/spreed/issues/4523
> Remove request password button when verif disabled

- lib/Listener/CSPListener.php
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/Video.vue
- src/components/CallView/shared/VideoBackground.vue
- src/store/callViewStore.js
- src/utils/imageBlurrer.js
- src/utils/imageBlurrerWorker.js
- webpack.common.js
The CSS blur filter used in the VideoBackground component causes a severe performance hit in Chromium (the performance hit is higher the larger the image, and the larger the radius (which happens with larger images, the perfect storm :-P )).
To solve that, and given that Chromium has support for OffscreenCanvas, now the blurred background is generated instead using an OffscreenCanvas in a worker. Generating the blurred image in a normal canvas already improves the performance a lot, but it is still somewhat slow, so it needs to be done in a worker to not block the UI thread during the generation. Due to the slowness a cache for blurred backgrounds was added too.
Pending:
- Although blurring the canvas is way faster in Chromium it still lags a bit, so it might be better to offload the …
> Fix Chromium performance hit in calls due to blur filter

- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/Screen.vue
- src/components/CallView/shared/Video.vue
- src/components/MediaDevicesPreview.vue
Disabled in grid view, own video and also the media settings.
Fixes https://github.com/nextcloud/spreed/issues/4754
Tested in Chromium 87.
You need to right click to see the "Picture in Picture" option.
Note that in grid view for some reason right click doesn't show the same menu, so I used the inspector to verify.
In promoted view the video context menu works and allows picture in picture mode.
Doesn't work in Firefox because of https://bugzilla.mozilla.org/show_bug.cgi?id=1611831
> Disable PIP for non-promoted videos

- docs/participant.md
- lib/Controller/RoomController.php
- lib/PublicShareAuth/Listener.php
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/password-request.feature
> [stable18] Fix user management in password request rooms

- docs/participant.md
- lib/Controller/RoomController.php
- lib/PublicShareAuth/Listener.php
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/password-request.feature
> [stable19] Fix user management in password request rooms

- docs/participant.md
- lib/Controller/RoomController.php
- lib/PublicShareAuth/Listener.php
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/password-request.feature
> [stable20] Fix user management in password request rooms

- docs/participant.md
- lib/Controller/RoomController.php
- lib/PublicShareAuth/Listener.php
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/password-request.feature
> [stable20.1] Fix user management in password request rooms

- CHANGELOG.md
- appinfo/info.xml
- Implement read status for messages including a privacy setting  [#4231](https://github.com/nextcloud/spreed/pull/4231)
- Implement multiple requirements to prepare for SIP dial-in  [#4612](https://github.com/nextcloud/spreed/pull/4612)  [#4682](https://github.com/nextcloud/spreed/pull/4682)  [#4689](https://github.com/nextcloud/spreed/pull/4689)
- Allow moderators to make conversations "listable" so users can join themselves  [#4706](https://github.com/nextcloud/spreed/pull/4706)
- Add the possibility for conversation descriptions  [#4546](https://github.com/nextcloud/spreed/pull/4546)
- You can not push to talk/mute with the space key  [#4328](https://github.com/nextcloud/spreed/pull/4328)
- Conversations can now be locked in the moderator settings preventing further chat messages and …
> Add changelog for 11.0.0-alpha.1

- package-lock.json
- package.json
- src/components/RightSidebar/Description/Description.vue
- src/components/RightSidebar/RightSidebar.vue
- src/services/conversationsService.js
- src/store/conversationsStore.js
Fix #3432
Based on #4587
requires from vue lib: https://github.com/nextcloud/nextcloud-vue/pull/1584, https://github.com/nextcloud/nextcloud-vue/pull/1566, and https://github.com/nextcloud/nextcloud-vue/pull/1592
current state:
> Conversation description - front-end

- lib/MatterbridgeManager.php
Some folks in #4549 have problems because the bridge bot password is too simple for their password policy. Generating a password with at least one uppercase letter, one lowercase, one digit and one symbol solves this issue.
> Make bridge bot password more complex

- tests/integration/features/bootstrap/CommandLineTrait.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/find-listed.feature
- tests/integration/features/conversation/join-listable.feature
- tests/integration/features/conversation/set-listable.feature
- tests/integration/spreedcheats/appinfo/routes.php
- tests/integration/spreedcheats/lib/Controller/ApiController.php
Removed cheat that used GuestManager directly from the guests app.
Now using occ guests:add to create guest account users.
> Integration tests use occ guests:add to create guests

- .github/dependabot.yml
- package-lock.json
- package.json
Reverts nextcloud/spreed#4811
Because of https://github.com/nextcloud/spreed/issues/4818
> Revert "Bump @babel/preset-env from 7.12.10 to 7.12.11"

- src/services/conversationsService.js
Use searchText instead of searchTerm in in method signature to be
consistent with other search methods.
Fixes listable search by passing in the search terms correctly.
> Fix listable search request

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/components/LeftSidebar/LeftSidebar.vue
Fixes https://github.com/nextcloud/spreed/issues/4833
Scroll to conversation only in specific cases:
- scroll into view when joining a conversation from the search results
- scroll into view initially when loading the page
- don't scroll on click
- don't scroll when posting or receiving a message
To test this, make sure to have a lot of favorite channels at the top, then join a channel that would appear at the bottom.
I already lost some time trying to make the scrolling itself work, so now I've left a timeout in there. Not sure what the left sidebar list is doing that prevents us to scroll it earlier even when the element already exists. To be researched later separately...
> Scroll to conversation only in specific cases

- src/components/ConversationSettings/LinkShareSettings.vue
Also rename the button from "Copy public link" to "Copy conversation
link" since now a conversation can also be joined when listable. Or simply when telling someone "let's meet in this room" even when they are already a participant but might not have it open directly.
Fixes https://github.com/nextcloud/spreed/issues/4824
> Hide password hint when guest not allowed

- src/components/MessagesList/MessagesGroup/Message/Message.vue
The time element is part of the layout and is what is making the
messagte text wrap. So when we hide the time we need to keep its element
visible to also keep the layout. This is achieved now by using
"visibility:hidden" instead of removing the element completely.
Fixes https://github.com/nextcloud/spreed/issues/4823
> Fix row wrapping on hover

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/components/NewMessageForm/NewMessageForm.vue
Fixes issue with errors in console due to the missing event handler
function.
Follow up from https://github.com/nextcloud/spreed/pull/4836
Interestingly, the comment above the event shows that there was a past decision to scroll the conversation list on posting. The decision was changed in https://github.com/nextcloud/spreed/issues/4833
> Remove unused newMessagePosted event

- src/components/MessagesList/MessagesList.vue
The sidebar chat mode doesn't have `this.$route` defined, probably because the main page is the files app which is not Vue JS.
To avoid the error, this fix adds a "?" to make it conditional and avoid the warning.
We don't have a way to link to and focus messages in sidebar mode anyway.
> Fix console error about missing hash in sidebar mode

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/EmptyCallView.vue
- src/components/CallView/shared/LocalMediaControls.vue
- Fixed call warning icon position as it was overlapping with the new three dots menu
- Removed actions menu (raise hands) from sidebar mode
- Improved empty call view in sidebar mode by reducing the sizes
and here the call warning icon properly positioned in grid view and speaker view:
> Call warning + empty call view tweaks

- lib/Service/ParticipantService.php
The sessions were left joined to the attendees, so all the attendees in the conversation that were not active were not included in the result.
~~Pending:~~ Future:
- Add integration tests ~~(at least, if they can be added quickly)~~ - They require some work, so something for later
- Install and enable the notifications app
- Create a one-to-one conversation with another user
- Change to a different conversation
- In a private window, log in as the other user
- Open the one-to-one conversation
- Write a message
The notification app shows a notification with the written message
No notification is shown
- Install and enable the notifications app
- Set the notification level of the conversation to "All messages"
- Change to a different conversation
- In a …
> Fix notifications based on the notification level

- lib/Service/ParticipantService.php
Similar to #4825
The sessions were left joined to the attendees, so all the attendees in the conversation that were not active were not included in the result.
- Install and enable the notifications app
- Change to a different conversation
- In a private window, open the public conversation
- Start a call
The notification app shows a notification about a started call
No notification is shown
> Fix notifications based on the participants not in a call

- docs/capabilities.md
- lib/Capabilities.php
- tests/php/CapabilitiesTest.php
Fixes https://github.com/nextcloud/spreed/issues/4834
Added capability to signal the existence of the v3 API.
**NOTES**:
- I changed the docs to say Talk 10.1 for the "sip-support" capability and "conversation-v3" because we only backported these to stable20.1, not stable20.
- the existence of "conversation-v3" doesn't mean that all the other features in v3 are available but only that this endpoint version exists. For specific features, these need to check their corresponding capabilities (ex: "listable-rooms", "chat-read-status")
> Add conversation-v3 capability for API v3

- src/components/CallView/CallView.vue
Follow up to #4685
[There is no `unmounted` lifecycle hook in Vue](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram); after a component is mounted it can only be destroyed.
This fixes a memory leak of the CallView, as the reference was retained forever by the EventBus.
> Unregister "refreshPeerList" event when CallView is destroyed

- src/utils/imageBlurrer.js
Fixes #4813 
Follow up to #4678 
Safari does not support the CSP "worker-src" directive, so it failed to create the worker, which caused Talk to fail to load. Now the worker will be loaded only when needed (so only in Chromium), and even if the worker fails to load everything will keep going (a synchronous blurrer will be used instead of the asynchronous one from the worker).
~~Besides that the CSP "child-src" directive was added too as [it is supported by Safari](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src#Browser_compatibility) and [it is used as a fallback when "worker-src" is not available](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src). Given that Safari does not use the worker and that …
> Fix loading worker on browsers without CSP "worker-src" directive

- src/components/CallView/shared/VideoBackground.vue
Follow up to #4678
`blurredBackgroundImageSource` is not used when the CSS blur filter is used, so there is no need to load it in that case.
This also fixes an error shown in older Edge versions (not Chromium-based) due to `createImageBitmap` not being available.
> Do not load the blurred background source if not needed

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
fix #4858 
As discussed in design review: 
> Fix settings confusion

- lib/MatterbridgeManager.php
It can lead to generate an invalid Matterbridge toml config file.
> Avoid double quotes in bridge bot app password

- lib/Manager.php
- lib/Share/RoomShareProvider.php
- tests/psalm-baseline.xml
Saves a lot of work on propfinds for example
> Do not load full room object for share queries

- src/components/CallView/CallView.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/store/callViewStore.js
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalMediaModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
Fixes https://github.com/nextcloud/spreed/issues/4770
Participants who raised their hand will appear on top of the list.
For this, the "raisedHand" state was exended to also include a timestamp. The timestamp is sent by whoever raised the hand to have consistent values across participants.
Tested with regular users and also guest users without accounts.
Please use internal signaling when testing because with HPB it doesn't work because of https://github.com/nextcloud/spreed/issues/4777
> Sort participants by raised hands

- src/assets/variables.scss
- src/components/ChatView.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/Description/Description.vue
> New message form facelift

- lib/Chat/SystemMessage/Listener.php
> No system message when a self-joined user leaves

- src/components/NewMessageForm/NewMessageForm.vue
- src/components/Quote.vue
Fixes https://github.com/nextcloud/spreed/issues/4174
> Added quote border difference when own message is quoted

- src/components/RightSidebar/Description/Description.vue
The conversation descriptionText attribute must be initialized when the
component is created as the watcher is only called on updates, not
creation.
Fixes https://github.com/nextcloud/spreed/issues/4809
> Properly initialize descriptionText with description

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
So far, the stripe was designed to not duplicate the video of whoever is
displayed in the top. However, when a screen share is in progress, that
user's video must move to the stripe so we can see them.
Fixes https://github.com/nextcloud/spreed/issues/4817
Left side is the user sharing the screen (admin). Own video is visible in the stripe and also the green video from the other user.
Right side is the user receiving the screen share (alice). The video of "admin" is visible also in the stripe.
So far so good, however when you expand the window width, it looks bad:
Thoughts @ma12-co ?
> Allow single video in stripe if screen share in progress

- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/AllowedGroups.vue
Fix #4683
To create such a group use Nextcloud 18 or higher occ:
```
GROUPID=$(uuidgen)
GROUPID="group${GROUPID:8:28}"
./occ -vvv group:add $GROUPID --display-name "Dragon Crew"
```
Before | After
---|---
> Correctly use the displayname for groups in admin settings

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/remove-self.feature
Fix #4490 
To check out it works, revert https://github.com/nextcloud/spreed/pull/4489 and run the test:
Without #4489 
```
Then user "participant2" gets room "room" with 404 (v3)               # FeatureContext::userGetsRoom()
Failed asserting that 200 matches expected 404.
💥
```
```
Then user "participant2" gets room "room" with 404 (v3)               # FeatureContext::userGetsRoom()
✔️
```
> Add an integration test for when the last moderator leaves

- src/components/ConversationSettings/LockingSettings.vue
- src/components/ConversationSettings/SipSettings.vue
🙈 I wonder why `LockingSettings.vue` and `SipSettings.vue` are so different when they do the same thing :D
> Cannot disable sip

- lib/Controller/RoomController.php
- lib/Manager.php
1. Create a group conversation
2. Enable SIP
3. Try to dial-in
4. On the SIP server see `DEBUG:workflow.YeAltb1L5mKn:The meeting number '7979592938' is not valid ({'success': False, 'error': 'conference_not_found'})` 💥
> Allow SIP dial-in in non-public conversations too

- .github/dependabot.yml
- package-lock.json
- package.json
- webpack.common.js
In the listed order, every time I added a new exclude, a new one popped up. So I added them one by one.
Now in this PR we've reached a state where the Talk page loads in IE 11 but is missing some controls, likely due to the many JS errors happening in nextcloud-vue components (but no more syntax errors).
> Transpile more deps for IE 11

- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
Fixes https://github.com/nextcloud/spreed/issues/4572
When a conversation is deleted through an action, also delete the matching messages for consistency.
This also prevents the corresponding vues to try to access the deleted conversation.
Note: the proposed code works by defining an action in messagesStore with the same name as the one in the conversationsStore. The dispatching of actions will trigger on all the stores, which then makes this magic happen :-)
I noticed also that "purgeConversations" is also not clearing the messagesStore but decided against adding it here, as it might have side effects. I'll raise a tech debt ticket later to discuss this unrelated bit.
> Delete messages from store for deleted conversation

- src/components/CallView/Grid/Grid.vue
- src/components/TopBar/TopBar.vue
Although the grid component is capable of performing pagination until now it was enabled only in stripe mode. When the call view was in grid mode and the participants did not fit a notification was shown to the user, but the buttons to change between grid view pages were not shown. However, (with some tweaks) the pagination does not require the grid view to be in stripe mode to work, so the buttons are now shown when needed also in the main grid view (centered vertically instead of close to the top, as they would clash with the top bar buttons).
The notification was removed too, as now it does not make sense, at least with its previous message. However I wonder if we should still show the notification with a different message (something like "Too many participants to fit in the window. …
> Enable pagination for main grid view

- src/components/RightSidebar/Description/Description.vue
> Allow line breaks and links in the description

- src/components/CallView/shared/VideoBackground.vue
Follow up to #4379
The avatar endpoint returns a picture for both default and custom avatars, and [the Avatar component does not differentiate between them; as long as a picture is returned by the endpoint the "user has avatar" flag is set to true](https://github.com/nextcloud/nextcloud-vue/commit/15c72125d218add990b1d460a15d528b2736321f).
However, the VideoBackground component only considered an avatar as having a picture if it was a custom picture, so it would not show the picture if it was not previously loaded (which should not happen in practice, as Avatar components were loaded before the call was started).
> Fix "user has avatar" flag set as false for default user avatars

- src/components/LeftSidebar/LeftSidebar.vue
1. Open a conversation:
2. Search as another user:
It said "Listed conversations"
Was missed in #4771
> Fix open conversations heading

- src/components/LeftSidebar/SearchBox/SearchBox.vue
> allow some more padding for the search abort button

- src/components/MessagesList/MessagesList.vue
Before scrollTo() was used, but this does not work when the window is not visible.
So now when the chat is in the background we scroll only half a line and stop following.
The user will see that something happened and have the anchor to jump to the bottom.
Same author (half a line) | New author (half avatar)
---|---
cc @ma12-co @jancborchardt  The main question is if the "scroll only half" behaviour is actually wanted, or if we should just scrolldown fully (as it was attempted to, but didn't do because scrollTo() only works on visible windows)
> Fix scrolling chat when in the background

- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
When clicking outside the at-mention dropdown or exiting the input
field, the at-mention dropdown is now closed automatically.
Fixes https://github.com/nextcloud/spreed/issues/2758
Also see https://github.com/nextcloud/spreed/issues/2758#issuecomment-763488114
> Close at-mention dropdown on blur

- package-lock.json
- package.json
Brings in the updated Avatar component which now uses Popover.
Fixes issue with dropdown menu overlap with other avatars in the
messages list.
Fixes https://github.com/nextcloud/spreed/issues/4147
> Bump @nextcloud-vue to 3.5.1

- README.md
- src/mixins/browserCheck.js
This adds Opera to the popup  "The browser you're using is not fully supported by Nextcloud Talk. Please use the latest version of Mozilla Firefox, Microsoft Edge, Google Chrome or Apple Safari." and removes the popup (for Opera).
Note: Opera v36 is based on Chromium v49.
> Remove "unsupported browser" warning for Opera

- src/components/ConversationSettings/LobbySettings.vue
Fixes https://github.com/nextcloud/spreed/issues/4983
- Bug: Lobby timer can now be cleared. When doing so it is saved directly.
- UX: Adjusted minute selection to have an interval of 5.
- UX: Adjusted default date to be the start of the next hour.
- UX: Removed extra click for confirmation as we anyway have the save button.
- Internal: Changed the data type for communicating with date picker to use timestamps, since this is what we store anyway.
> Fix lobby time input

- src/assets/buttons.scss
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/services/messagesService.js
- src/store/messagesStore.js
- src/utils/temporaryMessage.js
Fix #2454 
Also supports parallel errors much better now. If previous you would send each line as a message:
```
Lorem
ipsum
dolor
sit
amet
```
And they all failed e.g. due to network, you got "amet" recovered into the input while the rest is gone. Now you have to click on them one by one, but therefore can also recover them all.
> Allow to resend temporary messages if the failure was not permissions

- src/components/RightSidebar/LobbyStatus.vue
- src/components/RightSidebar/RightSidebar.vue
Fixes https://github.com/nextcloud/spreed/issues/4981
Fixes https://github.com/nextcloud/spreed/issues/4982
Note: I tried adding more information like the remaining time until meeting start, but it would take too much space and make the sidebar look too crowded. Also the moment library doesn't generate nice compact human readable texts for remaining durations. So if we do want this: needs further research.
> New button to disable lobby in sidebar

- src/components/CallView/Grid/Grid.vue
- src/components/TopBar/TopBar.vue
> [stable20.1] Enable pagination for main grid view

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/store/fileUploadStore.js
Display a notification and adjust the tooltip message accordingly when
an insufficient storage error is detected.
Note: no resuming for now as it's more complicated than just resending the message as we'd need to retrigger the upload.
To test you can use a guest user or with a user with 0 quota: https://github.com/nextcloud/spreed/issues/4138
Part of https://github.com/nextcloud/spreed/issues/4138
> Catch upload 507 errors

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessageForm/NewMessageForm.vue
- Fix gif preview max size capability check
- Add extra capability check for allowing attachments
To test, change https://github.com/nextcloud/spreed/blob/bugfix/noid/actually-check-caps-for-upload/lib/Capabilities.php#L93 and make it return false.
> Fix capabilities checks

- src/components/CallView/shared/LocalVideo.vue
> [stable20.1] Fix local video positioning

- lib/Room.php
1. Add breakpoint at
https://github.com/nextcloud/spreed/blob/459858a69527311bf60ffa553d45ba2a7eeec032/lib/Activity/Listener.php#L111
2. Add breakpoint at
https://github.com/nextcloud/spreed/blob/459858a69527311bf60ffa553d45ba2a7eeec032/lib/Activity/Listener.php#L125
3. Start a call with 2 users
4. Leave call with both users
5. Wait until both requests are at breakpoint 1
6. Wait until both requests are at breakpoint 2
7. Request 1 step until
https://github.com/nextcloud/spreed/blob/459858a69527311bf60ffa553d45ba2a7eeec032/lib/Activity/Listener.php#L132
8. Request 2 step and and it should return on
https://github.com/nextcloud/spreed/blob/459858a69527311bf60ffa553d45ba2a7eeec032/lib/Activity/Listener.php#L129
Before this PR you will not enter the if in request 2 and therefor generate 2 …
> Prevent duplicate call summaries

- package-lock.json
- package.json
Fixes scrollbar issue due to old workaround for popovers, which was
removed in that version.
Fixes https://github.com/nextcloud/spreed/issues/5045
> Bump @nextcloud/vue from 3.5.3 to 3.5.4 and fix scrollbar

- lib/Chat/Parser/UserMention.php
- tests/integration/features/chat/rich-messages.feature
- tests/php/Chat/Parser/UserMentionTest.php
1. Post message `Mention to @sub and @subname`
2. Post message `Mention to @subname and @sub`
Before | After
---|---
> Mention sub name users

- lib/TInitialState.php
- src/components/NewMessageForm/NewMessageForm.vue
- src/store/fileUploadStore.js
Whenever a user has zero quota, for example like guest app users, don't
display the upload button.
The quota value is retrieved for the attachment folder.
Fixes https://github.com/nextcloud/spreed/issues/4138
> Hide upload button with zero quota

- src/components/CallView/Grid/Grid.vue
Before | After
---|---
The main problem is when the button is on e.g. white screenshare, see #5016  for screenshots
Fix #5016
> Add hover effects for grid collapser

- src/store/messagesStore.js
1. Create a one to one chat
2. Delete all messages from `oc_comments`
3. Update last_message field in `oc_talk_rooms` to 0
4. Open the chat in the UI again
5. Try to post something
📤
💥 
```
[Vue warn]: Error in v-on handler (Promise/async): "TypeError: right-hand side of 'in' should be an object, got undefined"
found in
---> <AdvancedInput> at src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
<NewMessageForm> at src/components/NewMessageForm/NewMessageForm.vue
<ChatView> at src/components/ChatView.vue
<MainView> at src/views/MainView.vue
<AppContent>
<Content>
<App> at src/App.vue
<Root>
```
This can currently only happen with conversations that where created be before we had chat.
But might be relevant in the future again when we allow to truncate the complete chat (for that …
> Allow to post in completely empty chats

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Before | After
---|---
Should prevent some group conversations that are created by accident from time to time, when you think you are just searching for it.
* Prefills the conversation name with the search result label
* Selects the group/circle already as participant
> Bring up the "new group conv" dialog for group results

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/init.js
- src/main.js
- src/mainFilesSidebar.js
- src/mainFilesSidebarLoader.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
- src/store/index.js
- src/store/messageActionsStore.js
How to test: 
* Open the developer console and type:
```
window.OCA.Talk.registerMessageAction({
label: 'test',
callback: (messageAPIData) => console.log(messageAPIData),
icon: 'icon-user',
})
```
* Open a message 3 dot menu;
* Click on the added action;
* Check if the response object is logged in the console
> Allow other apps to register message actions

- appinfo/routes.php
- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/Parser/Listener.php
- lib/Chat/Parser/SystemMessage.php
- lib/Controller/ChatController.php
- lib/Model/Message.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/services/messagesService.js
- src/store/messagesStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/delete.feature
- tests/php/CapabilitiesTest.php
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Controller/ChatControllerTest.php
> Delete chat messages

- src/components/LeftSidebar/ConversationsList/Conversation.vue
As proposed by Jan here: https://github.com/nextcloud/mail/pull/4382#issuecomment-771586047 
all menu action items should have the same colour when they are dark.
> Update favorite dark icon

- lib/Chat/SystemMessage/Listener.php
- lib/Collaboration/Collaborators/Listener.php
- lib/Controller/RoomController.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/add-participant.feature
- tests/php/Chat/SystemMessage/ListenerTest.php
Fixes https://github.com/nextcloud/spreed/issues/3462
> Allow converting self-joined users participants to regular participants

- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Follow up to #5059
`showModal()` was being called as the handler for the `on-click` event and the `EventBus.$on('NewGroupConversationDialog')`. As the first one always provides the event as the first parameter the item was always defined, but it never contained a label, so the model became undefined and thus the dialog failed to open.
Now the method was split in two, one to be used to just show the modal and another one that also takes into account the item being given.
- Open Talk
- Click the button to create a new conversation
The dialog is opened.
The dialog is not opened.
> Fix new conversation dialog when no item is selected

- appinfo/routes.php
- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/Parser/SystemMessage.php
- lib/Controller/ChatController.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/rich-object-share.feature
- tests/php/CapabilitiesTest.php
- tests/php/Controller/ChatControllerTest.php
Sample request:
```
curl -k https://localhost/ocs/v2.php/apps/spreed/api/v1/chat/XXXXX/share \
-u admin:admin \
-H "OCS-ApiRequest: true" \
-d 'objectType=deck-card'\
-d 'objectId=9'\
-d 'metaData={"type":"deck-card","id":"9","name":"Card title","boardname":"Board name","stackname":"Stack name","link":"https:\/\/nextcloud21.local\/index.php\/apps\/deck\/#\/board\/2\/card\/9"}'
```
As per discussion in the chat, for now it is "garbage-in garbage-out". The resolution for that is extending the rich-object part in the server to allow to "parse"/"verify" data by each app even allowing them to return "Not accessible" or something alike as currently hard coded for files.
> Allow to share RichObjects to chats

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- Removed message hover higlight for deleted messages;
- Removed date;
- Removed background highlight;
- Remove delivered checkmark;
> Improve deleted messages look

- appinfo/info.xml
So I'm pretty sure this is the fix.
Attachment folder worked 100% of the time I tested deck, which does everything exactly the same, but is already registered as "dav" because it uses the dav API of comments?
https://github.com/nextcloud/deck/blob/b0135a71ede5eb1d95d9aa9b1b6ceb458c8198ce/appinfo/info.xml#L25
After some logging and debugging I could confirm that in the broken cases the write was ALWAYS on a propfind from the desktop client and logging at:
https://github.com/nextcloud/server/blob/d89a75be0b01f0423a7c1ad2d58aac73c3cc1f3a/apps/files_sharing/lib/SharedMount.php#L119
Confirmed `OC_App::isAppLoaded()` is false for "spreed" and true for "deck". I uploaded 3 more files after changing this on c.nc.c and they all worked, even though the request was from the client.
So the problem …
> Fix "Talk/ folder not working for attachments"

- css/icons.scss
- src/PublicShareAuthRequestPasswordButton.vue
- src/components/CallView/CallView.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/MediaDevicesPreview.vue
- src/components/TopBar/TopBar.vue
Fixes https://github.com/nextcloud/spreed/issues/5021
> Replace call icons in buttons bar with material design icons

- lib/Config.php
- lib/Controller/SignalingController.php
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/TurnServers.vue
- tests/php/ConfigTest.php
Until now no scheme could be configured to connect to the TURN server, so `turn:` was used by default. The `turns:` scheme defines a connection over TLS, which in some cases is needed by clients behind a very restrictive firewall that only allows TLS connections. However, encrypted TURN connections also require a certificate to be set in the TURN server, which may not be always available. Moreover, encrypted TURN connections also require a domain. Due to all this now it is possible to set the TURN server scheme to `turn:`, `turns:` or both, so the administrator can set the best suiting one.
Already configured TURN servers that have no scheme configured yet defaults to `turn:` to keep the same behaviour as before. New configured TURN servers also default to `turn:`, as `turns:` has some …
> Add support for "turns:" scheme

- tests/integration/features/conversation/find-listed.feature
Fix the test to actually use the variable from the example list.
> [stable21] Fix find-listed integration test outline

- src/components/AdminSettings/TurnServer.vue
1. Have a turn that only has working UDP (no TCP)
2. Configure it in admin settings for both
3. Use the test function
Reported error for TCP
Reported as working
> Split reporting of candidates by protocol

- src/components/CallView/Grid/Grid.vue
Regression introduced in 14b4630ff790 during the backport (the component was placed inside the v-else instead of after it).
- Start a public call
- Switch to grid view
The local video is shown in the grid.
The local video is not shown in the grid.
> [stable20.1] Fix local video not shown in grid view

- src/components/CallView/Grid/Grid.vue
Regression introduced in #4958
If the number of pages was -1 (which happens if there are no remote videos and thus "slots" becomes -1) the current page became -2.
- Start a public call
- Join the call again
In the original window the guest is shown.
In the original window the guest is not shown. Changing to speaker mode and then back to grid view shows the guest again (because that resets currentPage to 0).
> Prevent current page in grid to become negative

- src/FilesSidebarTabApp.vue
- src/components/UploadEditor.vue
- src/store/fileUploadStore.js
Follow up to #3988
Extracted from #4291 for tidiness and easier backporting.
> Add upload editor in files sidebar mode

- src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
> Improve deck card UI

- appinfo/info.xml
- lib/Activity/Listener.php
- lib/Controller/RoomController.php
- lib/Manager.php
- lib/Migration/Version11001Date20210211111527.php
- lib/Model/SelectHelper.php
- lib/Room.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/group.feature
- tests/php/RoomTest.php
> Provide information for incoming call screens

- lib/AppInfo/Application.php
- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Listener/UserDisplayNameListener.php
- lib/Service/ParticipantService.php
Could help a bit with https://github.com/nextcloud/server/pull/25440
Next step (for follow up PR) is to store the guest name also in this table and retain the attendee instead of the guests_name entry, so we can get rid of that table all together, but I don't want to backport that really.
> Store and use display name from attendees table

- lib/Controller/CallController.php
- src/components/CallView/shared/Video.vue
Fix #5109 
The idea of this was to show the email address of invited SIP users, but in case of normal guests it's a bigger harm, so for now let's not do this.
In the future we might instead save the email address also as a display name for SIP invites.
> Show "Guest" instead of session hash for guests

- lib/Controller/PageController.php
- templates/index.php
`user_uid` doesn't seem to be set automatically, so the event to dispatch for loading scripts for the projects integration is never emitted (in [tempates/index.php](https://github.com/nextcloud/spreed/blob/84d42604e60aa1c31ecf698dcc069f36c494148a/templates/index.php#L10))
I can't find where this broke currently so there might be a different way to solve this depending on what changed, however this at least makes it work again :)
> Make sure that project resources scripts event is properly emitted

- lib/Activity/Listener.php
- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Model/AttendeeMapper.php
- lib/Room.php
- lib/Service/ParticipantService.php
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/components/Quote.vue
- src/components/SetGuestUsername.vue
- src/store/actorStore.js
- src/utils/temporaryMessage.js
- tests/php/Controller/ChatControllerTest.php
- Move the storing of the displayname from oc_talk_guestnames to oc_talk_attendees for guests as well
- Make clicking a SIP link identify the guest as the invited email attendee (will break current SIP dual-join work around)
> Reuse attendee for guests

- CHANGELOG.md
- Allow resending email invitations  [#5052](https://github.com/nextcloud/spreed/pull/5052)
- Added support for turns:// protocol  [#5087](https://github.com/nextcloud/spreed/pull/5087)
- Bring up the conversation creation-dialog when clicking on a group to prevent accidentally spam  [#5062](https://github.com/nextcloud/spreed/pull/5062)
- Fixed a bug that would prevent attachments going into the Talk/ folder  [#5077](https://github.com/nextcloud/spreed/pull/5077)
- Split the turn test to report whether UDP and/or TCP work  [#5104](https://github.com/nextcloud/spreed/pull/5104)
- Fix collaboration resource options not loading  [#5140](https://github.com/nextcloud/spreed/pull/5140)
- Hide the upload option when the user has no quota assigned …
> Changelog for 11.0.0-RC1

- src/components/LeftSidebar/ConversationsList/Conversation.vue
Pushed separately so we can backport and reduce user's frustration
> Close left sidebar menu after leave or delete

- lib/AppInfo/Application.php
- lib/Deck/DeckPluginLoader.php
- src/collections.js
- src/deck.js
- src/main.js
- src/services/messagesService.js
- src/views/RoomSelector.vue
- webpack.common.js
Added deck action for sharing/linking that uses the RoomSelector.
Improved RoomSelector
Fixes https://github.com/nextcloud/spreed/issues/5106
Requires https://github.com/nextcloud/deck/pull/2772 (+ info.xml max-version hack) for testing.
Issues for later:
- adding conditional tooltip in case of ellipsis: would require having a reusable Conversation.vue in the future
Open topics:
- is the registration for the script in the right place or do we want another special event-thingy for deck to tell us when to register ? (like OCA\Files\Event\LoadSidebar)
> Add sharing deck card with a conversation

- appinfo/info.xml
- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Controller/CallController.php
- lib/Controller/GuestController.php
- lib/Controller/RoomController.php
- lib/GuestManager.php
- lib/Migration/Version11000Date20201209142525.php
- lib/Migration/Version11001Date20210212105406.php
- lib/Model/Attendee.php
- lib/Model/AttendeeMapper.php
- lib/Notification/Notifier.php
- tests/integration/spreedcheats/lib/Controller/ApiController.php
- tests/php/Chat/AutoComplete/SearchPluginTest.php
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Chat/Parser/UserMentionTest.php
- tests/php/Notification/NotifierTest.php
* ⚠️ Warning for changelog: This drops the guest names on existing chat messages and there is nothing we can do about it.
Purely internal changes, frontend and mobile apps should not be affected as the public API is unchanged.
> Store guest display names on attendees

- lib/Controller/CallController.php
- lib/Service/ParticipantService.php
Should save some load as we don't create objects and select items we then throw away
> Limit the session list on the database instead of selecting all attendees

- lib/Room.php
When updating the last_read_message in the database, we now also update it in
the Room object like it is done for other properties.
Fixes an issue when creating a room with participants that the latter
received a last_read_message id of zero. This is because the code path for
creation is done within a single API call, and while the room got
created, the last message id in Room was still 0 when read out for
setting to the participants in addUsers().
Indirectly related to https://github.com/nextcloud/spreed/pull/3825 and affects its proper functioning.
1. Copy this SQL query for testing: `select token, actor_id, last_read_message, (select message from oc_comments c where c.id=a.last_read_message) message, last_mention_message, last_message from oc_talk_attendees a, oc_talk_rooms r where …
> Update Room object last message after setting

- src/components/MessagesList/MessagesList.vue
Whenever the old messages are already loading initially when opening a
conversation, a scroll event might call getOldMessages again which would
cancel the previous one.
The initial old messages load is using includeLastKnown=1 while the others use
0. So if it gets cancelled, we will miss the "last known" message as it
won't be included in subsequent calls.
This fix prevents repeated calls to getOldMessages to avoid the above
issue.
See https://github.com/nextcloud/spreed/pull/3825#issuecomment-780719458 for semi-reliable reproduction steps and https://github.com/nextcloud/spreed/pull/3825#issuecomment-781319116 for some information.
The handleScroll method was sometimes calling getOldMessages(false) while we still had getOldMessages(true), which led to having a missing message in the …
> Prevent loading old messages twice on scroll

- CHANGELOG.md
- docs/capabilities.md
- Integrate with Deck to allow posting Deck cards to Talk conversations  [#5201](https://github.com/nextcloud/spreed/pull/5201)  [#5202](https://github.com/nextcloud/spreed/pull/5202)  [#5203](https://github.com/nextcloud/spreed/pull/5203)
- Allow other apps to register message actions, e.g. Deck can create a Deck card out of a chat message  [#5204](https://github.com/nextcloud/spreed/pull/5204)
- Allow to delete chat messages  [#5205](https://github.com/nextcloud/spreed/pull/5205)  [#5206](https://github.com/nextcloud/spreed/pull/5206)
- Add information about callFlags of a conversation to the API so mobile clients can show if it's a audio or video call  [#5208](https://github.com/nextcloud/spreed/pull/5208)
- Prevent loading old messages twice on scroll which could skip some messages …
> Changelog for 11.0 and 11.1

- CHANGELOG.md
- Added pagination to the gridview in case there are too many participants  [#4991](https://github.com/nextcloud/spreed/pull/4991)
- Replace blur with average color in video backgrounds to improve performance on Chrome based browsers  [#5011](https://github.com/nextcloud/spreed/pull/5011)
- Allow SIP dial-in in non-public conversations too  [#4955](https://github.com/nextcloud/spreed/pull/4955)
- Drop guest moderators when changing a conversation to group conversation  [#5231](https://github.com/nextcloud/spreed/pull/5231)
- Fix collaboration resource options not loading  [#5141](https://github.com/nextcloud/spreed/pull/5141)
- Fixed a bug that would prevent attachments going into the Talk/ folder  [#5078](https://github.com/nextcloud/spreed/pull/5078)
- Fix mentioning of users with …
> Add changelog for 9.0.8, 10.0.6 and 10.1.2

- src/components/AdminSettings/TurnServer.vue
> Revert "Split reporting of candidates by protocol"

- src/components/AdminSettings/TurnServer.vue
> Revert "[stable21] Split reporting of candidates by protocol"

- CHANGELOG.md
- appinfo/info.xml
- Fix collaboration resource options not loading  [#5143](https://github.com/nextcloud/spreed/pull/5143)
- Fixed a bug that would prevent attachments going into the Talk/ folder  [#5080](https://github.com/nextcloud/spreed/pull/5080)
> [stable19] Add changelog for 9.0.9

- CHANGELOG.md
- appinfo/info.xml
- Replace blur with average color in video backgrounds to improve performance on Chrome based browsers  [#5012](https://github.com/nextcloud/spreed/pull/5012)
- Drop guest moderators when changing a conversation to group conversation  [#5228](https://github.com/nextcloud/spreed/pull/5228)
- Fix collaboration resource options not loading  [#5142](https://github.com/nextcloud/spreed/pull/5142)
- Fixed a bug that would prevent attachments going into the Talk/ folder  [#5079](https://github.com/nextcloud/spreed/pull/5079)
- Fix mentioning of users with subnames, e.g. "foo" and "foobar"  [#5051](https://github.com/nextcloud/spreed/pull/5051)
- Add upload editor in files sidebar mode  [#5111](https://github.com/nextcloud/spreed/pull/5111)
> [stable20] Add changelog for 9.0.8 and 10.0.6

- CHANGELOG.md
- appinfo/info.xml
- Added pagination to the gridview in case there are too many participants  [#4991](https://github.com/nextcloud/spreed/pull/4991)
- Replace blur with average color in video backgrounds to improve performance on Chrome based browsers  [#5011](https://github.com/nextcloud/spreed/pull/5011)
- Allow SIP dial-in in non-public conversations too  [#4955](https://github.com/nextcloud/spreed/pull/4955)
- Drop guest moderators when changing a conversation to group conversation  [#5231](https://github.com/nextcloud/spreed/pull/5231)
- Fix collaboration resource options not loading  [#5141](https://github.com/nextcloud/spreed/pull/5141)
- Fixed a bug that would prevent attachments going into the Talk/ folder  [#5078](https://github.com/nextcloud/spreed/pull/5078)
- Fix mentioning of users with …
> [stable20.1] Add changelog for 9.0.8, 10.0.6 and 10.1.2

- src/components/CallView/shared/LocalVideo.vue
- src/utils/webrtc/webrtc.js
`TOAST_PERMANENT_TIMEOUT` and `TOAST_DEFAULT_TIMEOUT` [were introduced in @nextcloud/dialogs v3.0.0](https://github.com/nextcloud/nextcloud-dialogs/pull/210/files#diff-5ee1d2d88420bdeb09a041d59aa56371580418b4c010624dba16594ea0f463a4R36-R37), so they are not available yet in [the version used by Talk 10](https://github.com/nextcloud/spreed/blob/v10.0.6/package.json#L23).
Note too that the timeout units was changed from seconds to milliseconds in v3.0.0, so the default timeout here needs to be specified in seconds.
> [stable20] Fix toast timeout

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>
solves: #2800
works only in group chats, not for guest and my own messages
continuation of https://github.com/nextcloud/spreed/pull/4477
> Private reply without quote

- lib/Command/Room/TRoomCommand.php
> Reduce complexity for autocomplete suggestions

- lib/Signaling/Listener.php
> Use addMessageForAllParticipants instead of looping manually

- lib/Controller/SignalingController.php
- lib/Service/ParticipantService.php
- lib/Signaling/BackendNotifier.php
- lib/Signaling/Messages.php
> Base queries on sessions where it makes sense

- src/components/ChatView.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/TopBar/CallButton.vue
- src/init.js
- src/store/tokenStore.js
Immediately display messages from the clicked conversation even if not joined yet with the signaling server.
In order to avoid errors, the call button and the newmessagegorm components are disabled while opening the new session.
TODO: 
https://user-images.githubusercontent.com/26852655/107543910-90f88b80-6bc1-11eb-8c58-16d7d43e6000.mp4
> Fix conversation switching lag

- lib/Controller/RoomController.php
When a user is blocked by the lobby, they now don't see the call icon in
case moderators are having one.
Fixes https://github.com/nextcloud/spreed/issues/5214
> Hide call icon when blocked by lobby

- src/components/CallView/shared/LocalMediaControls.vue
- src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/TopBar/TopBar.vue
Fullscreen mode is applied on the "#content-vue" container, so now all
relevant Actions components are using that as container too.
This makes the actions menu visible also in fullscreen mode.
Partial fix for https://github.com/nextcloud/spreed/issues/5027 only for the Actions components.
Others will need nextcloud-vue updates, see https://github.com/nextcloud/spreed/issues/5027#issuecomment-786675267
Note: the property explicitly wants a String selector
> Fix Actions menus in fullscreen mode

- src/FilesSidebarTabApp.vue
When reselecting the chat tab, some changes might have happened in other
tabs like sharing. This refreshes the view when this happens.
1. Upload a file
2. Open the Chat tab and see the message about sharing the file first
3. Go to sharing tab
4. Share with another user
5. Go back to the sharing tab
The tab still says that you need to share. Need to refresh the page to fix it.
The chat tab now says "Join this conversation".
I've also checked that switching back and forth while a chat is open keeps the room open and doesn't go back to the "Join the conversation" button.
Note: I think there was a bug report somewhere but couldn't find it any more.
> When reselecting the chat tab, reevaluate fileinfo

- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/views/MainView.vue
Follow up from @ma12-co's removal of the property: https://github.com/nextcloud/spreed/commit/3748a6b969a0187cb6434ceb3757265f29454445#diff-3836025d8a95ea6ee32db4350094d4371beeee2384ff8752007852ef0572cc47L73
> Remove obsolete usage of token attr in ChatView

- lib/Controller/RoomController.php
- lib/Service/ParticipantService.php
- src/components/ConversationSettings/LobbySettings.vue
- src/components/ConversationSettings/LockingSettings.vue
Also only trigger events and update the session flags
if they actually changed, as some callers might not check for differences.
> When locking a conversation, kick out everyone

- src/App.vue
- src/FilesSidebarCallViewApp.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/mixins/sessionIssueHandler.js
- src/utils/signaling.js
When the current conversation was deleted while in a call, the redirect
now targets the not-found page instead of the one about duplicate
session.
Added event bus handler for the not found page which now also removes
the session store's conversation token.
Fixes https://github.com/nextcloud/spreed/issues/4552
> Fix redirect when deleting current conversation

- package-lock.json
- package.json
Unblocks https://github.com/nextcloud/spreed/pull/5288 and https://github.com/nextcloud/spreed/pull/5291
> Bump @nextcloud/vue from 3.6.0 to 3.7.0

- CHANGELOG.md
- Fixed a bug in the migration that could prevent copying all participants to the attendee table  [#5244](https://github.com/nextcloud/spreed/pull/5244)
- Fixed a bug in the migration that could prevent copying all participants to the attendee table  [#5245](https://github.com/nextcloud/spreed/pull/5245)
> Add changelog for 11.1.1 and 10.1.3

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Moved reply button outside the actions menu in the message row.
This way it is quicker for the user to find and click.
Fixes https://github.com/nextcloud/spreed/issues/5297
Regular row:
Tall row:
As menu:
> Direct reply button in message row

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/AvatarWrapper/AvatarWrapperSmall.vue
- src/components/ConversationIcon.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/components/UploadEditor.vue
Many popup components are usually appending themselves to the document
body. This doesn't work in fullscreen mode where we use another
component as the root.
This fix sets the "container" property for all relevant popup components
to make sure they can be visible in fullscreen mode.
Partial fix of https://github.com/nextcloud/spreed/issues/5027
> Use container property to fix popups in fulllscreen mode

- lib/Controller/RoomController.php
- tests/integration/features/bootstrap/FeatureContext.php
> Fix listed room test

- lib/Service/ParticipantService.php
This fixes a regression introduced in 3bfb611d9d
When the connection between a client and the external signaling server is interrupted [the signaling server may unregister its session](https://github.com/strukturag/nextcloud-spreed-signaling/blob/043691d7037049eb8a9144f8dcada49b1beb187e/src/signaling/hub.go#L1902-L1904), even if the Nextcloud session is still active. Once the client reconnects it will join the room again, which will generate a new signaling session for it.
If the connection between the browser and the external signaling server is interrupted during a call [the browser will automatically rejoin the call after joining the conversation again](https://github.com/nextcloud/spreed/blob/2999b5d66559817e57f52be5e02f9cd859da8cc0/src/utils/signaling.js#L998) (I have not checked the …
> Fix not joining call again on reconnection with HPB

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
1. Create a conversation with 5 people
2. Reload the page with open network tab:
3. Before:
4. After:
> Inject the preloaded user status into the avatar component

- src/components/LeftSidebar/ConversationsList/Conversation.vue
> Fix action caption

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>
solves: #5097
> copy msg link to clipboard

- src/utils/signaling.js
Until now an error notification was shown if the connection of the websocket to the external signaling server failed. However, if the websocket connection succeeded but then there was an error when actually connecting to the signaling server at an application level (the hello message response was an error) no error notification was shown in the UI. Now the error notification is also shown in that case, and it will not be removed (no matter if originally it happened due to an error in the websocket or in the connection) until the connection has succeeded.
Besides that, several errors in a row in the hello response usually point to a misconfigured signaling server that can not connect to the Nextcloud server. The error message now also takes into account the number of hello response errors …
> Show error notification also when hello signaling message fails

- src/components/CallView/CallView.vue
- src/components/CallView/shared/Video.vue
When a remote participant loses the connection her avatar and video were expected to be dimmed, but this did not happen due to a bug with the CSS classes.
Besides that this pull request also adds a loading icon on videos too (as a loading icon was already shown on avatars) when the connection is lost. However, the loading icon on videos is twice as large as, at least in my opinion :-) , they looked too small and were not noticeable otherwise (as they are "framed" by the whole video, which is larger than the avatar).
There is another slight difference between the loading icon on videos and avatars: the loading icon on avatars is dimmed, while the icon on videos is not. The right approach would be not to dimm the loading icon on avatars, but for simplicity it was kept like that (it would …
> Fix UI feedback when remote participants lose connection

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/ChatView.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/RightSidebar.vue
- src/services/messagesService.js
- src/store/conversationsStore.js
- src/store/messagesStore.js
~~Fix #1788~~
Fixes https://github.com/nextcloud/spreed/issues/1164
> Add unread message marker in the chat view

- lib/Model/Message.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fixes issue by removes "Reply" direct button on locked rooms.
Allows copy message link and mark as unread in locked rooms.
When unlocked:
When locked:
> Allow some actions on locked rooms

- src/components/NewMessageForm/NewMessageForm.vue
- src/store/quoteReplyStore.js
Save the message from the current input field by conversation into the
store.
This makes it possible to keep the message when switching the
conversation.
Also fixes an issue where joining or leaving a call would clear the
message due to the field being destroyed and recreated between the
message list and the sidebar.
Fixes https://github.com/nextcloud/spreed/issues/5372
There's a small issue: when the field is populated, the cursor appears at the beginning.
Given [how complicated it is to set the cursor at the end](https://stackoverflow.com/questions/4233265/contenteditable-set-caret-at-the-end-of-the-text-cross-browser) we might want to pass on that one, considering that we'll also replace the field with a better version of it in https://github.com/nextcloud/spreed/pull/4333
The store …
> Keep pending input message per conversation

- .github/workflows/dependabot-approve.yml
As suggested by @miaulalala to fix dependabot failures like https://github.com/nextcloud/spreed/pull/5386/checks?check_run_id=2153492914
> Fix auto-approve for dependabot

- appinfo/routes.php
- composer.lock
- lib/Capabilities.php
- lib/Controller/TempAvatarController.php
- tests/php/CapabilitiesTest.php
- tests/psalm-baseline.xml
```
curl -k -H "OCS-APIRequest: true" -u admin:admin 'https://nextcloud22.local/ocs/v2.php/apps/spreed/temp-user-avatar' -X POST -F 'files[]=@/home/nickv/avatar.jpg'
```
```
curl -k -H "OCS-APIRequest: true" -u admin:admin 'https://nextcloud22.local/ocs/v2.php/apps/spreed/temp-user-avatar' -X DELETE
```
Not adding documentation because it's being wiped soon again and will be removed without any close done time once the one from server is there.
> Temporary OCS API for user avatar upload and delete

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
This fix re-fetches the current conversation to make sure that harder to compute values are re-fetched from the server like unreadMessages, unreadMention, etc.
This introduces a new store action "fetchConversation".
I've adjusted some of the service's "fetchConversation" usage and moved them to use this new store action instead.
(moving the non-store stuff step by step to the store to avoid repeating logic)
Fixes https://github.com/nextcloud/spreed/issues/5375
While testing, I noticed unrelated console errors for guests due to unread marker. I'll fix this separately
> Faster update of left sidebar after marking as unread

- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/UploadEditor.vue
```
/home/nickv/Nextcloud/22/server/appsbabies/spreed/src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
76:7  warning  Attribute "container" should go before "@close"  vue/attributes-order
/home/nickv/Nextcloud/22/server/appsbabies/spreed/src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
39:4  warning  Attribute "container" should go before "@close"  vue/attributes-order
/home/nickv/Nextcloud/22/server/appsbabies/spreed/src/components/UploadEditor.vue
26:3  warning  Attribute "container" should go before "@close"  vue/attributes-order
```
> Fix order to reduce eslint warnings

- src/services/settingsService.js
- src/store/fileUploadStore.js
- src/store/helper.js
- src/store/settingsStore.js
- src/store/soundsStore.js
Copied from https://github.com/nextcloud/server/blob/3e624dc39966f54c6d418eee2e8141fc5c21f751/core/src/login.js#L48-L54
Don't know when it started, but the current admin page doesn't load anymore due to combination of things. services now use the store and the store loads initial state, but that is only initialised on the talk controllers, not in settings.... going with a default value now solves this.
> Don't fail loading the store when some initial states are not there

- CHANGELOG.md
- Added a temporary OCS Api for clients to upload avatars  [#5401](https://github.com/nextcloud/spreed/pull/5401)
- Direct reply button in message row  [#5361](https://github.com/nextcloud/spreed/pull/5361)
- Show error notification also when hello signaling message fails  [#5344](https://github.com/nextcloud/spreed/pull/5344)
- Fix UI feedback when remote participants lose connection  [#5345](https://github.com/nextcloud/spreed/pull/5345)
- Handle failed server requests more gracefully  [#5455](https://github.com/nextcloud/spreed/pull/5455)
- Only use the local file as preview for some types when uploading  [#5423](https://github.com/nextcloud/spreed/pull/5423)
- Fix an issue with the migration to the new attendees table  [#5427](https://github.com/nextcloud/spreed/pull/5427)
- Fix the …
> Changelog for 11.2.0, 11.1.2, 10.1.4 and 10.0.7

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/issue_template.md
As a matter of fact, without that additional empty line, the fenced code blocks within the details blocks are not shown correctly on GitHub.
> Issue templates | Add empty line to details blocks

- docs/participant.md
- lib/Controller/RoomController.php
- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/store/callViewStore.js
- src/store/conversationsStore.js
- Expose session ids as array in participants API
- The sessionId attribute is now removed from the participant list API response in favor of the sessionIds array.
- The raised hand state in the participant list is now retrieved based on the multiple sessions of a participant
As discussed in https://github.com/nextcloud/spreed/issues/5349#issuecomment-795624906, v4 of the API has not crystalized yet so it's ok to make changes in this PR.
Fixes https://github.com/nextcloud/spreed/issues/5349
Testing if raised hand appears when triggered from both sessions of a single user:
> Fix raised hand detection for multiple session, adjusted participant list response

- src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
When attending a conversation as guest, the menu of the avatars shown
before messages is now disabled. The menu would anyway not show any
entries.
Fixes https://github.com/nextcloud/spreed/issues/5399
> Disable avatar menu in messages as guest

- src/main.js
Fixes https://github.com/nextcloud/spreed/issues/5027
This sets the default tooltip container to not be the body but the Vue element that we select in fullscreen mode.
I've verified that the scope of this default is only available in the talk app by adding log statements in the notifications app and log that setting while in the talk app. In the notifications app the default stays body.
This confirms that library specific globals are only available in the library scope in which it was included/compiled and since every app bundle its own version of nextcloud/vue with the tooltip, then we're fine.
> Make tooltips work in fullscreen mode

- jest.config.js
- package-lock.json
- package.json
- src/store/callViewStore.spec.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/store/index.js
- src/store/storeConfig.js
Added more JS tests for stores.
Extracted global store config to a separate file to be able to include it in
tests.
Up to 56 tests now :tada:
> More JS tests for stores

- src/components/MessagesList/MessagesList.vue
Fix #4939 
Before | After
---|---
I also expended the function instead of having a giant chain of && which was not debuggable/readable
> Always group system messages, independent from author

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
The reply to box is too small to contain a play button, so remove it
there.
Before:
After:
> Remove play button in reply to for video previews

- src/services/messagesService.js
- src/services/messagesService.spec.js
For timeout cancelling to work, the options need to be passed to the
request object.
Fixes https://github.com/nextcloud/spreed/issues/5527
We might want to backport.
> Fix cancelling postNewMessage

- src/mainFilesSidebar.js
- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
The observe-visibility extension was missing in many entry points
resulting in repeated console warnings.
The directive usage in the message list was introduced as part of #3825
> Register visibility observer in all entry points

- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
This was missed in https://github.com/nextcloud/spreed/pull/4253
1. As a user with Z as first char go into a chat that has other users
2. Set your user status to offline
3. As another user go to the chat and check the sidebar
User is marked online but sorted at the bottom
Before | After
---|---
> Fix sorting of users that are online with user status offline

- src/services/settingsService.js
- src/store/soundsStore.js
Adjust setPlaySounds service function to not rely on the store.
This will make it possible to write JS unit tests without having to inject a global store mock.
> Remove store usage in settingsService

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/mainFilesSidebarLoader.js
- src/services/participantsService.js
- src/store/participantsStore.js
Moved joinConversation, leaveConversation and a few other dependencies
to the participantsStore.
Removes the dependency to the store from participantsService.
There's a slight change of behavior: joinConversation in the service now
also connects to signaling, and only when this is done the first
action dispatch are done. In the previous implementation the store
already received some updates before we even connected to signaling, see https://github.com/nextcloud/spreed/pull/5529/files#diff-e0f25089223beb2eb4703995c475f60ab752fa3a0053b63b848a03bff7cd5c16R46
Tests:
> Decouple participantsService from the store

- src/store/fileUploadStore.js
DiscardUpload must pass args in the correct way.
Renamed fileId to temporaryMessageId for clarity.
Changed console.debug to console.error when sharing file for consistency
with the console.error from the upload.
Found while working on tests in https://github.com/nextcloud/spreed/pull/5522
1. Select 3 files for upload
2. Discard the dialog
3. Check `OCA.Talk.instance.$store.state.fileUploadStore.uploads` in the browser console
Stray upload, not deleted properly.
Empty, upload was properly deleted.
> Fix discard upload call + naming tweaks

- .eslintrc.js
- jest.config.js
- package-lock.json
- package.json
- src/store/fileUploadStore.spec.js
- src/store/guestNameStore.spec.js
- src/store/newGroupConversationStore.js
- src/store/newGroupConversationStore.spec.js
- src/store/quoteReplyStore.spec.js
- src/store/sidebarStore.spec.js
- src/test-setup.js
Brings in the following:
- fileUploadStore tests
- guestNameStore tests
- newGroupConversationStore tests
- quoteReplyStore tests
- sidebarStore tests
For the other stores not covered:
- they are too trivial (just getters/setters)
- they are blocked by global store usage (requireshttps://github.com/nextcloud/spreed/pull/5526)
- they are not fully testable because of the initial loadState / BrowserStore.getItem: we might want to move to a more explicit way of loading state with a "loadState" action of sorts => to be considered separately
~~Currently blocked because "temporaryMessage" is accessing the global store and I didn't find a way to set the current mocked store to the global module.~~
~~Maybe need to refactor those usages and always receive the store injected in the function.
At …
> More JS store tests featuring fileUploadStore and a few simple ones

- src/components/CallView/shared/LocalMediaControls.vue
- src/store/callViewStore.js
The flag that keep track of whether the quality warning tooltip was dismissed was a local data of the _LocalMediaControls_ component, so it was reset when a new instance of the component was created again. As a new instance could be created several times during the same call (for example, when switching between speaker and grid mode) the warning tooltip could appear again after being dismissed. Now the flag is kept in the store and shared between different instances.
- Start a call on a flaky connection
- Wait until the quality warning is shown and dismiss it
- Switch between speaker mode and grid mode
The quality warning icon is shown again, but the tooltip is not shown (unless hovering on the icon)
The quality warning tooltip appears again
> Fix quality warning tooltip not staying dismissed

- src/utils/webrtc/VideoConstrainer.js
When a call started and the _VideoConstrainer_ was created the video track was assumed to be already in high quality, so when the _VideoConstrainer_ was asked to apply again the high quality constraints it just ignored the request. However, in some cases the browser does not initialize the camera in high quality, so the camera was kept in a lower quality for as long as the high quality was kept being requested.
Moreover, even if the browser initialized the camera with high quality that quality might not be exactly the same as the one set when applying the high quality constraints, so even in those cases the constraints should be applied anyway for consistency.
- Connect a high quality camera
- Start a call
- Enable the video
- In the browser console, run …
> Fix initial camera quality

- src/components/LeftSidebar/ConversationsList/Conversation.vue
1. Open `index.php/apps/spreed/`
2. Search for an open conversation you did not join yet
3. Right click "Copy link addresss"
`index.php/call/1234567890`
`index.php/apps/spreed/#`
> Allow to copy the link of an open conversation

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/services/conversationsService.js
- src/services/messagesService.js
- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/store/talkHashStore.js
Removes dodgy global store usage from `messagesService`.
Moves `fetchConversations`, `fetchMessages`, `lookForNewMessages` and `postNewMessages` to the `messagesStore`.
The logic was mostly copy pasted there and rewired to use the correct variable.
- BUG: cancelling the postNewMessage doesn't work after timeout (no exception thrown), but also did not work on master, to be investigated separately => raised as https://github.com/nextcloud/spreed/issues/5527
> Decouple conversations and messages services from the global store

- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
> [stable21.1] Fix sorting of users that are online with user status offline

- src/utils/webrtc/webrtc.js
Only tested with two browsers on Linux, should be also tested between on different OS and browser and mobile apps (cc @Ivansss).
Fixes #3790
> Disable use of deprecated "Plan-B" semantics if HPB is used.

- CHANGELOG.md
- Fix redirect when deleting the current conversation  [#5315](https://github.com/nextcloud/spreed/pull/5315)
- Reset the page title when the conversation is not found  [#5493](https://github.com/nextcloud/spreed/pull/5493)
- Fix quality warning appearing again in certain conditions  [#5552](https://github.com/nextcloud/spreed/pull/5552)
- Fix camera quality starting bad in Chrome browsers  [#5556](https://github.com/nextcloud/spreed/pull/5556)
- Allow to copy the link of open conversations which the user didn't join  [#5562](https://github.com/nextcloud/spreed/pull/5562)
- Fix search focus when typing in the conversation search  [#5566](https://github.com/nextcloud/spreed/pull/5566)
- Fix sorting of users which set their user status to offline …
> Add changelog for 11.2.1

- src/utils/webrtc/MediaDevicesManager.js
Fixes #4414
If a device is currently active and a different one is requested Firefox returns the currently active device. To overcome this [all the tracks of the same device kind as the requested one are stopped before performing the request](https://github.com/nextcloud/spreed/blob/0926044bca3b2ffb1d4c254b4e398a33ea9592d1/src/utils/webrtc/MediaDevicesManager.js#L403).
However, a device is also "active" as long as any other device returned in the same `getUserMedia` request is active. Both audio and video are requested at once when a call is started, so during calls it was needed to stop both devices first to be able to switch just one of them.
Moreover, since Firefox 88 [there is a grace period for requesting again the media permissions to the user once a track …
> Fix switching devices in Firefox

- lib/Config.php
- lib/Controller/SignalingController.php
- tests/php/ConfigTest.php
- Provide multiple STUN servers to webrtc client when specified in the nextcloud backend instead of just 1 random one
> Provide multiple STUN servers to webrtc client

- lib/Config.php
- lib/Controller/SignalingController.php
- tests/php/ConfigTest.php
For now, Nextcloud Talk gets _one_ random turnservers of the specified turnservers in the backend.
This patch provides all in the backend specified turnservers to the client. So the chance might be higher, that calling in restricted cooperate networks will works successfully (btw, it's up to the client which turnserver to use).
Would probably fix https://github.com/nextcloud/spreed/issues/5267
Fix #3676
> Provide multiple TURN servers to webrtc client

- jest.config.js
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/test-setup.js
> JS tests for Message component

- lib/Chat/Parser/SystemMessage.php
> Fix guests without a name in system messages

- webpack.common.js
The material design icon loaders were affected by a recent change and we
need to stop excluding them for the compilation to work again.
Fixes https://github.com/nextcloud/spreed/issues/5489.
Thanks @juliushaertl for this solution.
I've tested with nextcloud-vue master as per steps in the ticket and it works fine with npm link.
Also retested with v3.9.0 from the original package.json and it works fine.
I've verified in both cases that the material design icons in the call view appear properly.
> Fix compatibility with nextcloud-vue v4.0.0 alpha

- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/Description/Description.vue
- src/components/RightSidebar/RightSidebar.vue
https://user-images.githubusercontent.com/26852655/117831559-94f18380-b26c-11eb-852f-24d466482f8c.mp4
> Move description editor to conversation settings dialog

- src/components/RightSidebar/RightSidebar.vue
Fixes a JS error due to missing handlers.
This was missing from https://github.com/nextcloud/spreed/pull/5605
Fixes https://github.com/nextcloud/spreed/issues/5631
> Remove leftover routeChange handlers

- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/test-setup.js
See skipped tests for more TODOs
> Add JS tests for conversation component

- appinfo/routes.php
- docs/internal-signaling.md
- lib/Capabilities.php
- lib/Controller/SignalingController.php
- src/services/signalingService.js
- src/utils/signaling.js
- tests/php/CapabilitiesTest.php
Requires #5491 and #5503
~~This is a breaking change for Talk 12.~~ The settings endpoint version was bumped, so clients can still use the previous API if needed.
The format resembles the `RTCIceServer` format, so the returned values can be directly used by the WebUI like done until now. Mobile clients will need to be adjusted, though.
**Important:** The [RTCIceServer MDN page](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer) states that `Avoid specifying an unnecessarily large number of URLs in the urls property; the startup time for your connection will go up substantially. Every server in the list will be contacted and tried out before one is selected to be used for negotiation.` It should be verified whether that applies too when using trickle ICE or not; if it does then …
> Unify stun and turn server urls

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
The method isSelf is relying on this.userId which never exists.
However, the method still works because of the session id array check
which works both for guests and logged in users.
Found while working on JS tests in #5637 
An alternative fix could be to use `this.currentParticipant.actorId` instead of `this.userId` but I'm not sure if it's really better and would cause other side effects.
Tests (done with some extra logging):
> Remove unused userId in Participant component

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/test-helpers.js
> JS tests for Participant component

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
Note: the metadata is not important in the test, only the fact that we correctly pass it in and associate with a `Location` component.
> Add Message.vue test for passing in geo-location object

- lib/AppInfo/Application.php
- lib/Flow/Operation.php
- lib/Flow/RegisterOperationsListener.php
Maybe that helps with:
https://github.com/nextcloud/spreed/issues/5518#issuecomment-826564931
```
{
"reqId": "cQy6L3Q7Syn0PWVL9M8d",
"level": 4,
"time": "2021-04-25T12:56:49+00:00",
"remoteAddr": "",
"user": "--",
"app": "no app in context",
"method": "",
"url": "--",
"message": {
"Exception": "Error",
"Message": "Class 'OCA\\Talk\\Flow\\Operation' not found",
"Code": 0,
"Trace": [
{
"file": "/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
"line": 176,
"function": "boot",
"class": "OCA\\Talk\\AppInfo\\Application",
"type": "->"
},
{
"file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
"line": 197,
"function": "bootApp",
"class": "OC\\AppFramework\\Bootstrap\\Coordinator",
"type": "->"
},
{
"file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
"line": …
```
> Register flow operation via dedicated event

- src/App.vue
- src/assets/variables.scss
- src/components/ChatView.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
- src/store/sidebarStore.spec.js
https://user-images.githubusercontent.com/26852655/117680564-32837f00-b1a9-11eb-9e8f-40bd4f1aabed.mp4
> Add meaningful conversation info to topbar. 

- src/utils/webrtc/simplewebrtc/localmedia.js
- src/utils/webrtc/webrtc.js
Forced reconnections, which are needed to start sending audio or video if the call was joined without audio or video, do not always work if the HPB is not used. This is unrelated to this pull request and it will be addressed separately.
- Open Talk settings
- Disable both audio and video
- Join a call
No error is shown, as both devices were explicitly disabled
An error about not being able to access microphone nor camera is shown
- Open Talk settings
- Disable both audio and video
- Join a call
- Open Talk settings
- Select audio and/or video devices
In the local video the audio and video buttons are enabled. Clicking on them enables audio and/or video (which requires a reconnection)
In the local video the audio and video buttons are kept disabled, so neither audio nor video can be …
> Fix switching devices during a call if started without audio nor video

- src/components/Description/Description.vue
Fixes https://github.com/nextcloud/spreed/issues/5479
> Don't cancel editing when clicking outside description

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Fixes https://github.com/nextcloud/spreed/issues/5672
> Encode dav path segments for direct preview

- src/utils/webrtc/models/CallParticipantModel.js
This fixes a memory leak, as the reference to the Peer object was retained forever by the webrtc object.
- Add `console.log('Handling raised hand')` as the first line inside [`_handleRaisedHand`](https://github.com/nextcloud/spreed/blob/deb2494193a51321273070b39739e625651d40ea/src/utils/webrtc/models/CallParticipantModel.js#L250)
- Start a call
- Open the conversation in a private window (all the following steps should be done in the private window)
- Join the call
- Join the call
- Join the call
- Raise the hand
In the original window a single _Handling raised hand_ message is printed in the console
In the original window three _Handling raised hand_ messages are printed in the console
> Fix raised hand handler not detached when peer is destroyed

- .drone.yml
Ref: https://github.com/nextcloud/server/pull/27211
> Use GHCR for PHP 7.3 images

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Backport of https://github.com/nextcloud/spreed/pull/5673 to stable21.1.
Conflicts solved:
- package.json + package-lock.json
- I've removed the test file
> [stable21.1] Encode dav path segments for direct preview

- docs/chat.md
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- tests/psalm-baseline.xml
> Allow to specify meta-data for sharing

- src/store/participantsStore.spec.js
The test needs to wait for the async function. Otherwise the test would finish before the test function was executed, which could cause the test to silently fail.
> Wait for async test functions

- src/utils/webrtc/simplewebrtc/peer.js
Little cleanup of the legacy SimpleWebRTC code.
> Remove unneeded webrtc code

- src/components/NewMessageForm/NewMessageForm.vue
Use attachment icon from material design for file uploads.
Also fixes an alignment issue with nextcloud-vue 4.0.0.
Part of https://github.com/nextcloud/spreed/issues/5492 to prepare for the 4.0.0 upgrade.
Before:
After:
Note: the icon is not visually identical and is rotated differently. If that's an issue we could use CSS to rotate it...
> Upload icon is now material design "attachment"

- src/components/CallView/shared/LocalMediaControls.vue
Remove fill color to avoid white on grey.
Before:
After:
> Fix color of screen share menu icons

- CHANGELOG.md
- Inject the preloaded user status into the avatar component  [#5694](https://github.com/nextcloud/spreed/pull/5694)
- Fix switching devices in Firefox  [#5580](https://github.com/nextcloud/spreed/pull/5580)
- Fix switching devices during a call if started without audio nor video  [#5662](https://github.com/nextcloud/spreed/pull/5662)
- Redirect to not-found page while in a call  [#5601](https://github.com/nextcloud/spreed/pull/5601)
- Regenerate session id after entering conversation password  [#5638](https://github.com/nextcloud/spreed/pull/5638)
- Fix a problem when a deleted user is recreated again  [#5643](https://github.com/nextcloud/spreed/pull/5643)
- Encode dav path segments for direct GIF preview  [#5674](https://github.com/nextcloud/spreed/pull/5674)
- Fix raised hand handler …
> Changelog for 11.3.0, 11.2.2, 10.1.5, 10.0.8 and 9.0.10

- CHANGELOG.md
- appinfo/info.xml
- Inject the preloaded user status into the avatar component  [#5694](https://github.com/nextcloud/spreed/pull/5694)
- Fix switching devices in Firefox  [#5580](https://github.com/nextcloud/spreed/pull/5580)
- Fix switching devices during a call if started without audio nor video  [#5662](https://github.com/nextcloud/spreed/pull/5662)
- Redirect to not-found page while in a call  [#5601](https://github.com/nextcloud/spreed/pull/5601)
- Regenerate session id after entering conversation password  [#5638](https://github.com/nextcloud/spreed/pull/5638)
- Fix a problem when a deleted user is recreated again  [#5643](https://github.com/nextcloud/spreed/pull/5643)
- Encode dav path segments for direct GIF preview  [#5674](https://github.com/nextcloud/spreed/pull/5674)
- Fix raised hand handler …
> [stable21.1] Changelog for 11.3.0

- CHANGELOG.md
- appinfo/info.xml
- Regenerate session id after entering conversation password  [#5639](https://github.com/nextcloud/spreed/pull/5639)
- Fix a problem when a deleted user is recreated again  [#5644](https://github.com/nextcloud/spreed/pull/5644)
- Encode dav path segments for direct GIF preview  [#5692](https://github.com/nextcloud/spreed/pull/5692)
- Fix raised hand handler not detached when a participant leaves  [#5677](https://github.com/nextcloud/spreed/pull/5677)
- Register flow operation via dedicated instead of legacy event  [#5651](https://github.com/nextcloud/spreed/pull/5651)
> [stable21] Changelog for 11.2.2

- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/simplewebrtc/simplewebrtc.js
- src/utils/webrtc/simplewebrtc/webrtc.js
- src/utils/webrtc/webrtc.js
`webrtc.sendToAll` only sends the signaling message to participants for which there is a Peer object. Due to this now it also emits and event that is handled by the WebRTC wrapper to send the message too to the rest of participants in the call that do not have a Peer object.
Sending signaling messages to participants without peers is currently needed for "raise hand" messages, and it will be needed for mute/unmute messages once the data channels are removed.
This pull request also fixes receiving raised hand events from participants without a Peer object, which could be useful in the webcast mode.
~~Besides the fix also some unneeded code was removed.~~ Extracted to its own [pull request](https://github.com/nextcloud/spreed/pull/5679).
Pending:
- As user A, start a call …
> Fix not sending signaling messages to participants without a Peer object

- src/App.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
Map multiple cancel functions to temporary message
When sending multiple messages in a row, and all are pending or time out, they each need a specific cancel function to match their specific request.
Fixes issue where one message timing out would cancel the other messages as well.
There's now also an unload warning when trying to leave the page while messages are being sent, to avoid potential data loss.
To test, use this patch:
```diff
diff --git a/src/services/messagesService.js b/src/services/messagesService.js
index 630445f23..a938109cf 100644
--- a/src/services/messagesService.js
+++ b/src/services/messagesService.js
@@ -75,6 +75,11 @@ const lookForNewMessages = async({ token, lastKnownMessageId }, options) => {
* @param {object} options request options
*/
const postNewMessage = …
```
> Cancel temporary messages individually and warn before leaving while sending

- appinfo/routes.php
- docs/call.md
- lib/Controller/CallController.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Signaling/Listener.php
- src/utils/signaling.js
- src/utils/webrtc/webrtc.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/update-call-flags.feature
Note that enable and disable a device refers to switching audio and video between none and a specific device in Talk settings, not to enable and disable audio and video in the controls.
The issues are there also in previous Talk versions. However one of the fixes requires a new endpoint to update the call flags (updating the call flags when a device is disabled), and currently it is just an aesthetic issue (in the future it might be needed to grant and revoke publishing permissions without having to force a reconnection), so (for once :-P ) I would vote to not backport it.
- Do not set up the HPB
- Open Talk settings, enable the audio device and disable the video device
- Start a call
- Open the Network tab in the developer console
- Open Talk settings and enable the video device
The join …
> Fix call flags updates

- docs/constants.md
- docs/conversation.md
- docs/participant.md
- lib/Model/Attendee.php
- src/constants.js
* Circles are currently not stored and returned due to #5670 
* But by adding them already the mobile clients are future proof and we don't have to update the API with a v5 after the PR is merged
> Document circles too

- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/simplewebrtc/simplewebrtc.js
When the HPB is used the peer connections for the other participants only receive the media, but do not send any on them (the data is sent on a single dedicated sending peer). Therefore there is no need to add tracks to those peers, nor listen to changes in the local tracks to update them.
The "broadcaster" property was already set before only on sending peers, so nothing is changed in that regard either.
Note that this should not change anything performance wise, as the browser is expected to be clever enough to do nothing with the streams if the peer is not sending them. But you never know :-P
> Do not add tracks for receiver only peers

- src/utils/webrtc/webrtc.js
In webrtc/index.js we import the function as WebRtc.
The name of the function at export time is semantically irrelevant but
having it correct might help when grepping.
In theory we could also remove that name altogether.
Tested with HPB to make sure this doesn't break.
> Fix casing of exported initWebRTC function

- lib/Middleware/InjectionMiddleware.php
In some concurrent request scenarios, the session of a participant might
expire just after its id got retrieved. To avoid unexpected behavior, if
the participant could not be found by session id, fall back to getting
it by user id.
Fixes issue where a room can sometimes not be deleted from the UI due to
a concurrent request that removes the session id.
Fixes https://github.com/nextcloud/spreed/issues/5733
> Fall back get participant in case session is gone

- lib/Controller/RoomController.php
When retrieving the conversation list for a user, there is a
time window between retrieving the list and the participant information.
If in that time window, a concurrent request removes the user from the
room, or even the room got deleted, this could cause a
ParticipantNotFoundException.
This fix prevents the latter exception to make the whole call return a
404. Instead, it skips the obsoleted entry and carries on with the list.
Similar race condition like with https://github.com/nextcloud/spreed/issues/5733.
Not reproducible though.
> Ignore current participant when listing rooms if removed concurrently

- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
When deleting a conversation, the route change would implicitly trigger
a leave request which ran in parallel to the conversation deletion one,
causing random issues in some systems like the latter returning a 404
instead of proceeding with the deletion.
This fix removes the route change on deletion. The new behavior will
implicitly redirect to the "not-found" page since the session does not
exist any more. The latter behavior is now aligned with the "Leave
conversation" action which also redirects to "not-found" page.
Fixes https://github.com/nextcloud/spreed/issues/5733
See ticket for details about the race condition and also alternative approaches that were considered but discarded.
> Don't trigger leave event when deleting conversation

- src/utils/webrtc/analyzers/ParticipantAnalyzer.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
~~Still in draft; I need to check if there is a better place to reset the stats (for example, when the ICE connection state changes), and check if it also works as expected when switching devices.~~ - It is better to reset the stats just before the analysis is started. 
Regarding switching devices I found a different issue related to stats being reset when they should not (when it is sent to other participants whether audio and video is enabled or disabled), so this needs to be fixed first before being able to check switching devices. Anyway, this will be done in another pull request.
- Start a call
- Wait 10-15 seconds and stop the screen share
- Share the screen again
The connection quality warning will not be …
> Fix connection quality stats not reset when setting a new peer connection

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
There is not a lot use in updating the participant list every 2 seconds,
when the list is not display, the sidebar closed or even the window hidden.
> Slow down the participant list update when not visible

- src/App.vue
Currently when a call with 40 people is started and they join one by one
with 3.1s difference, each of the participant will fetch the conversation
40 times resulting in 1.6k requests.
At the same time the info doesn't really change anymore as the participant
details of other participants have been removed from the room API with
version 3. A refreshing of the room therefor only makes sense once
to update the hasCall and callFlag attributes.
The conversations callFlag however is not used at the moment and the worst
that could happen without the refreshing is the values updating on the next
refreshing of the complete room list which is done every 30 seconds.
> Don't refresh the room when the participant list changes

- src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
- src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/UploadEditor.vue
- src/store/fileUploadStore.js
> Display voice message preview before uploading

- lib/Chat/Parser/SystemMessage.php
- psalm.xml
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- tests/php/Chat/Parser/SystemMessageTest.php
> Better vcard files

- src/components/TopBar/TopBar.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
Fixes https://github.com/nextcloud/spreed/issues/3110
When the sidebar is closed while in call, there will be an unread messages counter on top of the "open sidebar" button:
It is blue for new mentions and grey if there are no mentions.
Additionally, the first time a new unread message arrives or a new mention, a notification will be displayed.
> New messages indicator while in call

- src/App.vue
- src/components/TopBar/TopBar.vue
To avoid overlapping with the top bar, the toastify notification is
shifted down.
Doesn't look that fantastic though, wondering if we should move the notifications to the bottom instead. The latter might need more involved changes as it would require support for global toastify options in nextcloud-dialogs.
> Offset toastify when top bar is visible

- src/components/CallView/shared/LocalVideo.vue
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/webrtc.js
When the connection with other participants is lost those participants are shown dimmed and with a loading spinner. However, when the MCU is used that only covers receiving audio and video from those participants. Other participants can not hear or see the local participant until the sender peer object has connected. Therefore now the local video / avatar is dimmed and shows a loading spinner like done with the remote participants when the sender peer object is not connected.
When the MCU is not used the connections are peer to peer between partipants, so the already existing dimming and loading spinner on the remote participants views already show whether those participants can hear and see the local participant or not.
Note that currently if you are alone in a call and a forced …
> Add UI feedback when local participant is not connected

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
When switching between regular mode and call mode, the two MessagesList
view instances are concurrently disturbing each other's
lookForNewMessages call.
To fix this, we now introduce a requestId for those requests to which we
pass in the chatIdentifier, extended by a generated view id. This brings
back the old behavior for now.
In the future we should look into keeping the polling request and
sharing it between the two Vues, which requires some refactoring of the
polling logic and timeouts.
Fixes https://github.com/nextcloud/spreed/issues/5764
> Fix concurrency when cancelling lookForNewMessages

- src/App.vue
Use margin-top to avoid overriding the top value which has different
values depending on how many notifications are visible.
Fixes https://github.com/nextcloud/spreed/issues/5819
> Fix toastify offset approach

- src/components/RightSidebar/RightSidebar.vue
- src/main.js
Fixes #5810 
In Nextcloud 22 [`setFullScreenMode()` was added to `OCA.Files.Sidebar`](https://github.com/nextcloud/server/blob/c03a14934b543c6734e5458f814997e419cf808b/apps/files/src/sidebar.js#L61). That method [is expected and used by the viewer](https://github.com/nextcloud/viewer/blob/eba1a1bd3240ad825cd324254871438bebf0d587/src/views/Viewer.vue#L369), so it needs to be there even if the sidebar style is not changed to put it in full screen mode.
Besides that, in Nextcloud 22 [the viewer also reacts to `files:sidebar:opened` and `files:sidebar:closed` events](https://github.com/nextcloud/viewer/blob/eba1a1bd3240ad825cd324254871438bebf0d587/src/views/Viewer.vue#L343-L344) to adjust its width based on the sidebar.
At least for me the "opened" event from `AppSidebar` component does not …
> Adjust viewer and sidebar to changes in Nextcloud 22

- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/NewMessageForm/NewMessageForm.vue
Don't set focus on message element when scrolling to the first unread
message as this conflicts with focusInput() from the message form.
> Set focus to message only when anchor is set

- src/components/NewMessageForm/NewMessageForm.vue
> Bring back voice-message icon after chat input is cleared

- src/components/ConversationSettings/LinkShareSettings.vue
Fixes https://github.com/nextcloud/spreed/issues/5820
Before:
After:
> Replace settings button icons with material design icons

- docs/conversation.md
- lib/Controller/RoomController.php
- src/components/ConversationIcon.vue
- src/services/conversationsService.js
1. Open Talk
2. Create one-to-one conversations with X users
3. Reload talk front page
X requests for user statuses (most with 404)
User status is preloaded via conversations API and no additional requests are needed
> Populate user status for one to one conversations via the backend call already

- src/utils/webrtc/simplewebrtc/localmedia.js
- src/utils/webrtc/simplewebrtc/peer.js
Requires #5659 (actually it does not require it, but touches same code)
When the media is disabled now the sent track for the device is replaced by a null track. As it just replaces a track no reconnection is needed, and the previous connection is kept open, although without sending data.
At least, in theory. In practice this does not make any difference in Firefox, as Firefox automatically stops the streams as much as possible when the device is disabled. Unfortunately even without audio and video tracks if the connection is open Firefox still uses around ~5 KB/s (apparently depends on the video resolution).
On the other hand, Chromium seems to properly stop the data stream, as the bandwidth is now reduced from ~8 KB/s to ~300 B/s when both audio and video are disabled. Thus in a 30 …
> Stop sent streams when media is disabled

- src/components/TopBar/TopBar.vue
Move the conversation icon outside of the conversation header so that it
doesn't get cut.
Fixes issue where the status icon was cut.
Fixes issue where clicking the avatar would open the settings dialog
instead of the avatar menu. (mentioned in https://github.com/nextcloud/spreed/issues/5790#issuecomment-865280442)
Fixes https://github.com/nextcloud/spreed/issues/5826
Tests:
> Move conversation icon out of conversation header

- src/components/ConversationIcon.vue
- src/components/ConversationsOptionsList.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/views/Dashboard.vue
- src/views/RoomSelector.vue
Disable avatar menu in conversation lists to avoid interaction glitches.
The only place where it's enabled currently is in the top bar.
Tests with one on one conversation:
Fixes https://github.com/nextcloud/spreed/issues/5790
> Disable avatar menu in most conversation lists

- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
Rely on the event chain from the components instead of listening to
native events. The latter's problem is that it would also fire when the
user is clicking on the three dots menu.
Fixes https://github.com/nextcloud/spreed/issues/5100
> Fix left sidebar click event handling

- src/components/MessagesList/MessagesList.vue
1. Have a one-to-one conversation with some messages
2. Read them
3. Go to another conversation
4. Come back
5. Reload the page
You are in the middle of the chat
You are at the bottom of the chat
> Fix scrolling to bottom in already read conversations

- src/components/NewMessageForm/NewMessageForm.vue
Moved emoji picker div into the input div so we can use its relative
position.
Fixes https://github.com/nextcloud/spreed/issues/5765
Tests for emoji icon alignment:
> Fix emoji picker icon in guest mode

- src/components/RightSidebar/RightSidebar.vue
When switching conversations, the participant list's scroll container is
scrolled back to the top instead of keeping an arbitrary position.
Fixes https://github.com/nextcloud/spreed/issues/5841
> Scroll participant list to top on token change

- src/components/SettingsDialog/SettingsDialog.vue
- src/store/soundsStore.js
Use the correct attributes and values when saving.
Strange that eslint didn't complain in both cases...
> Fix saving sound settings

- src/components/NewMessageForm/NewMessageForm.vue
Guests currently have no way of uploading files, pictures, so voice
recordings fall under the same category.
Fixes https://github.com/nextcloud/spreed/issues/5848
> Remove voice recording for guests

- src/components/TopBar/TopBar.vue
The conversation icon must be hidden during a call
> Fix conversation icon visibility while in call

- src/App.vue
Only display a warning when leaving the page completely, which would
abort pending sending operations.
Switching between conversations will keep sending in the background so
no warning is needed.
Fixes: https://github.com/nextcloud/spreed/issues/5842
Test:
> Fix unload warning with pending messages

- src/components/MessagesList/MessagesList.vue
Fixes side effects that seem to affect the files app.
Fixes https://github.com/nextcloud/spreed/issues/5858
I've also verified the whole codebase and didn't find any other such imports to fix.
We are already using `isEqual` in two places and it was already imported safely.
> Safely import lodash function

- src/components/CallView/shared/LocalMediaControls.vue
- src/components/missingMaterialDesignIcons/CancelPresentation.vue
- src/components/missingMaterialDesignIcons/PresentToAll.vue
> Fix screenshare icon not crossing out when a screen is shared

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoBottomBar.vue
Fix #5861 
1. Start a call (single user)
2. Share your screen (you see it)
3. Swich to grid view (it's hidden)
4. Open the screenshare menu
5. Click on "Show your screen"
You see your screen
Nothing
1. Start a call (single user)
2. Share your screen (you see it)
3. Join with user 2
4. Also share the screen (everyone sees the own screen)
5. As user 2 unshare the screen
Everyone sees screen of user 1
user 1 sees the grid view (although they saw their own screen before)
user 2 sees the screen of user 1 but the bottom row is not collapsed
**Talk app version:** 4974b3d1f7e0bb444dabea963db97e3fb860135f
> Fix selecting the own screen in the gridview

- src/components/MessagesList/MessagesList.vue
We should scroll as soon as we have the old messages / context loaded.
For newer messages, don't scroll up again to the read marker in case
there is one.
It happened to me on c.nc.com that even though I scrolled down after seeing the read marker, the chat scrolled up again to focus on the read marker. I suspect that it's related to the call I've removed in this PR.
@nickvergessen this is what we discussed yesterday and weren't sure if we wanted to keep. Let's remove it for now.
I'll retest:
> Only scroll to focussed message once

- lib/BackgroundJob/CheckMatterbridges.php
- lib/MatterbridgeManager.php
> Don't spam the log when matterbridge is disabled

- src/components/NewMessageForm/NewMessageForm.vue
Fix CSS syntax error that prevented the emoji picker to stick to the
bottom.
Before:
After:
Please note that if you type multiple lines it will stick at the bottom. Since the "bottom" rule was already there I'll assume that this was already by design, just not activately properly:
Fixes https://github.com/nextcloud/spreed/issues/5870
> Fix emoji picker vertical position

- src/components/MessagesList/MessagesList.vue
For the initial scroll to work, the first call to getOldMessages must
fetch messages beyond the read marker itself. Otherwise the marker will
appear at the bottom of the screen as there aren't any new messages yet
until `lookForNewMessages` runs.
Fixes https://github.com/nextcloud/spreed/issues/5872
Tests with conversation that has a lot of new unread messages:
> Fix initial scroll of unread messages marker

- src/components/NewMessageForm/NewMessageForm.vue
> Add a debug command to generate an arbitrary number of chat message

- README.md
The original TURN instruction URL (https://nextcloud-talk.readthedocs.io/en/latest/TURN/) will show this:
And it should be this (https://nextcloud-talk.readthedocs.io/en/latest/TURN.html):
> Fix TURN's url in README.md

- src/utils/webrtc/analyzers/AverageStatValue.js
- src/utils/webrtc/analyzers/AverageStatValue.spec.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Fixes #5362
The logs are printed when the PeerConnectionAnalyzer changes to a state that causes a connection quality warning to be shown (very bad quality or not transmitted data).
Currently the connection quality is analyzed only when the HPB is used and only for the sender participant, so there will be at most a single PeerConnectionAnalyzer. Due to this, for simplicity, for now the stats are logged without any participant identifier.
> Add logs for connection quality warning

- src/components/RightSidebar/RightSidebar.vue
The converstion watcher is triggered even for attribute changes, so we
now use the token watcher instead for scrolling up so it only happens
when meaningful.
Note: the conversation display name watcher still needs to watch for "conversation" as the name might change while the token doesn't.
Fixes https://github.com/nextcloud/spreed/issues/5904
> Listen to token changes instead of conversation object

- src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
> Fix recording voice messages on Safari

- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Requires #5884 ~~(kept as draft until that is merged, but ready for review nevertheless)~~
The stats reported by the browser can sometimes stall for a second (it is unclear whether the browser does not update the stats or Janus does not send them, though). When that happens the stats are still reported, but with the same values as in the previous report. As there were no transmitted packets the "very bad quality" state was (wrongly) triggered.
To solve this now if there were no transmitted packets in the last report the analysis is kept on hold. If in the next report the number of packets has changed then the previous report is considered to have stalled and the new values are distributed between the previous and current report. If the number of packets is still zero then the previous …
> Fix connection quality warning shown due to stalled stats

- src/components/CallView/CallView.vue
- src/constants.js
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/simplewebrtc/simplewebrtc.js
- src/utils/webrtc/simplewebrtc/webrtc.js
- src/utils/webrtc/webrtc.js
Initial version for some testing.
Stream selection:
- in grid mode, the medium quality will be subscribed for all videos
- in normal mode, the high quality will be subscribed for the selected video
- in normal mode, the low quality will be subscribed for all other videos
This has some nice bandwidth savings (receiving side) and with that also CPU usage is reduced:
Should be backwards compatible for mobile clients which will receive the highest layer (the same as before).
Requires https://github.com/strukturag/nextcloud-spreed-signaling/pull/104
Open issues:
Fixes #5509
> Add support for simulcast streams.

- CHANGELOG.md
- Add support for simulcast streams when the high-performance backend is used  [#5535](https://github.com/nextcloud/spreed/pull/5535)
- Allow users to have multiple session in the same conversation  [#5194](https://github.com/nextcloud/spreed/pull/5194)
- Voice messages, location sharing and contacts sharing  [#5610](https://github.com/nextcloud/spreed/pull/5610)  [#5573](https://github.com/nextcloud/spreed/pull/5573)  [#5731](https://github.com/nextcloud/spreed/pull/5731)
- Play a sound when a participant joins or leaves the call  [#5410](https://github.com/nextcloud/spreed/pull/5410)
- Add unread message marker in the chat view  [#3825](https://github.com/nextcloud/spreed/pull/3825)
- Show a "new message" indicator while being in the call …
> Add changelog for 12.0.0-rc.1

- src/utils/webrtc/analyzers/AverageStatValue.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Backport of #5884 and #5885
Tested and works :+1:
> [stable21] Fix connection quality warning shown due to stalled stats

- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Resolved https://github.com/nextcloud/spreed/issues/5937
I am not sure if this will cause incompatible between different browsers,
but at least I tested it on Chrome it seems great!
Signed-off-by: Jim Lin <b04705003@ntu.edu.tw>
Related information: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
> Prevent submitting the message when the user is composing

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
>  Initialize the wav encoder in the entry points instead of in the audiorecorder component

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
Added condition to detect the last message when deciding whether to
render the read marker.
Fixes issues when the last message is a deleted one or a command and
where the marker was displayed.
Fixes https://github.com/nextcloud/spreed/issues/5959
> Never show read marker on the very last message

- lib/Chat/ChatManager.php
- lib/Controller/ChatController.php
- tests/integration/features/chat/delete.feature
- tests/php/Chat/ChatManagerTest.php
> [stable22] Unshare all items directly when deleting a room

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
Whenever there are several pages of unread messages, the
"lookForNewMessages()" call will not return all the results at once.
In case there are results left to load, the read marker is not reset by
the false when "isSticky" (aka scrolled to bottom) happens.
When loading new messages, we now only increase the conversation counter
when the latter was out of sync with the current messages list.
Fixes https://github.com/nextcloud/spreed/issues/5960
Make sure to check the steps there when testing as it requires 300+ messages as lookForNewMessages only returns 100 results at a time.
> Fix read marker and counter issues with pending pages

- src/components/MessagesList/MessagesList.vue
The scroll handler checks if the unread marker was seen before doing
updates after scrolling down. After updating the read marker in the
store, its value becomes different than the visual one. Because of this,
the check for seen was done on the wrong element and would always be
false.
This fix makes the handler use the visual marker instead of the store
one when checking for update. This makes sure that the marker will
continue to be updated when scrolling down, but will only allow
increasing the message id past the non-visual one to prevent bringing
the marker back up.
For reference, here is where the check is done: https://github.com/nextcloud/spreed/blob/bugfix/5814/fix-unread-marker-discrepancy/src/components/MessagesList/MessagesList.vue#L698
Fixes …
> Use visual last read message id in scroll handler

- src/collections.js
Use async loading of the roomlist component for the collections endpoint as otherwise the imports of dependent components from `@nextcloud/vue` takes up quite some time when loading the files app initially without triggering the display of the room selector.
| Before | After | 
| ------ | ----- |
| ![talk-collections-old](https://user-images.githubusercontent.com/3404133/124887875-e2247400-dfd5-11eb-8bae-1f773024ef85.png) | ![talk-collections-new](https://user-images.githubusercontent.com/3404133/124887877-e2247400-dfd5-11eb-85fb-a67d292782af.png) |
> Use async import for vue component on collections entrypoint

- src/utils/webrtc/simplewebrtc/localmedia.js
Follow up to #5551
Due to [a bug in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=946490) it is not possible to increase the resolution of a track once it has been cloned.
When the video was initially requested by Talk no resolution was specified, so Chromium returned a video track with a ~640x480 resolution, no matter the maximum resolution of the camera. As the track was immediately cloned, due to the bug, the maximum resolution of the track was limited to ~640x480.
Now, if Chromium or a derived browser is used, the video is requested with a loose constraint for a high resolution, so if the camera does not have such resolution it will still return the highest resolution available without failing. If the track is then cloned then it will be possible to decrease and …
> Fix initial camera quality with Chromium

- src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
- src/store/audioRecorderStore.js
- src/store/storeConfig.js
> Wait for the wav encoder to be initialized before allowing recordings

- CHANGELOG.md
- Unshare all items directly when deleting a room  [#5975](https://github.com/nextcloud/spreed/pull/5975)
- Fix date picker for lobby not being visible  [#5984](https://github.com/nextcloud/spreed/pull/5984)
- Fix initial camera quality with Chromium and Chromebased browsers  [#6000](https://github.com/nextcloud/spreed/pull/6000)
- Wait for the wav encoder to be initialized before allowing recordings  [#6012](https://github.com/nextcloud/spreed/pull/6012)  [#6014](https://github.com/nextcloud/spreed/pull/6014)
- Fix displaying moderation options in one-to-ones  [#6008](https://github.com/nextcloud/spreed/pull/6008)
- Never show read marker on the very last message  [#5969](https://github.com/nextcloud/spreed/pull/5969)
- Add UI feedback when local participant is not connected …
> Add changelog for 12.0.1, 11.3.1, 10.1.5, 10.0.9

- docs/constants.md
- lib/Chat/MessageParser.php
- lib/Controller/ChatController.php
- lib/MatterbridgeManager.php
- lib/Model/Attendee.php
- src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
- src/components/MessagesList/MessagesList.vue
- src/constants.js
~~Requires https://github.com/42wim/matterbridge/pull/1506.~~ **Now merged!**
The way the current iteration works is that messages received from the `bridge-bot` user is labeled as Actor Type `bridged`. Actor Type `bridged` messages store the message author name in the Actor Id field in `oc_comments`. When serving to the frontend, this is slightly changed to put what is in Actor Id into Actor Display Name and set the Actor Id to `bridge-bot` (the reason it was done this way was to simplify the changes that would need to be made to clients).
**As far as clients have to care, the only difference is the addition of the Actor Type `bridged` and that for `bridged` messages, the Actor Display Name can be different for every message.**
> Show name for bridged messages

- appinfo/info.xml
- appinfo/routes.php
- lib/BackgroundJob/RemoveEmptyRooms.php
- lib/Controller/FederationController.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Manager.php
- lib/Migration/Version13000Date20210625232111.php
- lib/Model/Attendee.php
- lib/Model/AttendeeMapper.php
- lib/Model/Invitation.php
- lib/Model/InvitationMapper.php
- lib/Model/SelectHelper.php
- lib/Notification/Notifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- psalm.xml
- tests/php/Notification/NotifierTest.php
- tests/php/RoomTest.php
For #5723
Also have a version that avoids adding and extra table here: https://github.com/nextcloud/spreed/tree/enh/5723%2Fadd-database-single
> Implement Recieving Room Shares

- src/utils/webrtc/webrtc.js
Updated version of #2488
Follow up:
- [Handle out of order answers](https://github.com/nextcloud/spreed/issues/5930) - This will require some deeper changes and it should not be a very common case, so let's do it in a follow up
- Modify the code of the external signaling server to simulate a lot of failures (sorry for the formatting, I did not find a way to use lists and blocks of code)
- In `hub.go`
- Add "math/rand" to the [imports at the top](https://github.com/strukturag/nextcloud-spreed-signaling/blob/e40e86f32c1b4fe05d3528eab7ea21e5b8da6912/hub.go#L34)
- Replace [`mc, err = session.GetOrCreatePublisher(ctx, h.mcu, data.RoomType)`](https://github.com/strukturag/nextcloud-spreed-signaling/blob/e40e86f32c1b4fe05d3528eab7ea21e5b8da6912/hub.go#L1677)
in _processMcuMessage_ with
`if …
> Send offer again when own peer is not initially connected

- src/utils/webrtc/VideoConstrainer.js
The previous minimum frame rate was wrongly got from the maximum frame rate, so when the minimum frame rate was compared after decreasing it it was always seen as changed. Due to this the constraints will be applied again even if they did not actually change due to having reached the minimum capped value, which would end in an infinite loop if the constraints could not be applied and the minimum frame rate was (tried to be) decreased again.
Besides that, the minimum value of the constraints was wrongly capped using `min` instead of `max`, so in practice the first time that the value was decreased it was already set to the minimum capped value.
> Fix infinite loop when the constraints can not be decreased

- lib/Listener/CSPListener.php
Audio recording previews use a blob, so the Content Security Policy must allow media from blobs to be able to play it.
This was not a problem in the main Talk UI, as in that case the Content Security Policy [already allowed media from blobs](https://github.com/nextcloud/spreed/blob/63fe1ac0d71cd660bee3df5ff3d304d5aca4871e/lib/Controller/PageController.php#L264).
- Share a file
- Open the _Chat_ tab
- Start a conversation
- Record an audio message
The preview dialog is shown and the audio recording can be played.
The preview dialog is shown but the audio recording can not be played. Browser console shows an error similar to `The page’s settings blocked the loading of a resource at blob:https://192.168.57.21:8443/5a589af9-ab9f-4e6e-8785-fa3da9684ee7 (“media-src”).`
> Fix blocked audio recording preview when Talk is embedded in the sidebar

- src/App.vue
- src/FilesSidebarTabApp.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
[The audio encoder is initialized when the AudioRecorder component is mounted](https://github.com/nextcloud/spreed/pull/5970), and the store keeps track of whether the audio encoder was already initialized to not do it again.
However, [the audio encoder was also unconditionally registered in the main components of the main and sidebar Talk UIs](https://github.com/nextcloud/spreed/pull/5966) (ironically to also fix the duplicated registration :-P ), which caused a duplicated registration when the audio encoder was initialized (as the store did not "know" that it was already registered).
Due to all this the unconditional registration is removed (which also avoids registering the audio encoder when it will not be needed, like when the current user is a guest without upload permissions).
> Fix duplicated registration of audio encoder

- docs/TURN.md
Update the TURN server documentation with some additional useful information how to check if the TRUN server is setup correctly and reachable from the outside.
> Update TURN server documentation

- src/components/MessagesList/MessagesGroup/Message/Message.vue
The forward action shows the RoomSelector, which [fetches the room list](https://github.com/nextcloud/spreed/blob/f4f891ad3745f864545d07fb6491257977747e27/src/views/RoomSelector.vue#L125-L130), but that is not allowed for guests.
- Join the conversation as a guest
- Send a message
- Show the menu for the message
The _Forward_ action is not shown.
The _Forward_ action is shown. Clicking on it shows an empty room selector.
> Hide forward action for guests

- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
When the audio/video or the screen peers were cleared the connection quality data was not reset. Due to this the connection quality warning would be kept shown if, for example, the screen share was stopped while the warning was being shown.
Pending:
- Use Firefox (Chromium stops the screen sharing when the shared window is closed, but [Firefox does not do that yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1682232))
- Start a call
- Close the shared window
- Wait until the connection quality warning appears (the warning appears because no more data is being sent, although the screen share is still active)
- Stop the screen share
The connection quality warning is hidden
The connection quality warning is still shown
> Fix connection quality warning still shown after media is stopped

- src/utils/webrtc/MediaDevicesManager.js
Before this only the deviceId was used to pick a device.
If not it fell back to the first device in the list.
Now we first try to find the previous device based on the label.
> Add some logging to the device selection

- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
Due to a bug in Chromium (probably [because "failed" is remapped to "disconnected"](https://chromium.googlesource.com/chromium/src/+/c6c955531d2b7ef3f38c149edc6fbaa537e1564b/third_party/blink/renderer/modules/peerconnection/rtc_ice_transport.cc#439), although I have not checked if that is actually the reason) the "iceConnectionState" of a RTCPeerConnection may get stuck as "disconnected" even if the connection has already failed. However, in that case "connectionState" does change to "failed", so now its listened too to changes in "connectionState" to handle that case.
~~Note that listeners to "iceConnectionState" still needs to be kept, as "connectionState" was added to Firefox only in recent versions.~~ -> Turns out that MDN fooled me and it was already available at least in Firefox 68 …
> Work around Chromium bug of iceConnectionState stuck as "disconnected"

- src/FilesSidebarTabApp.vue
This reverts commit 81d76dde09a89a68b113a0288583c964d13b8758.
The changes were needed due to the chat view having an absolute position. [Since Talk 12 that is no longer the case](https://github.com/nextcloud/spreed/commit/7daf60f53833d1d7eb2bf49b054d3e968854add3#diff-3836025d8a95ea6ee32db4350094d4371beeee2384ff8752007852ef0572cc47L160), so these changes just caused an unneeded margin.
**Reviewers:** the height of the button seems to be slightly smaller now, but I do not know why.
**Before:**
**After:**
> Fix unneeded top margin in Files sidebar chat

- CHANGELOG.md
PRs to be backported before:
- Improved device preference storing to better recover after switching between docking-station and normal usage with a device  [#6179](https://github.com/nextcloud/spreed/pull/6179)
- Fix laggy video with Full HD 60 FPS webcams in Chrome and Chromium  [#6159](https://github.com/nextcloud/spreed/pull/6159)
- Fix infinite loop when video constrains can not be satisfied  [#6125](https://github.com/nextcloud/spreed/pull/6125)
- Fix connection quality warning after media was stopped  [#6147](https://github.com/nextcloud/spreed/pull/6147)
- Hide forward action for guests  [#6143](https://github.com/nextcloud/spreed/pull/6143)
- Don't select the own video when trying to open the video settings  [#6158](https://github.com/nextcloud/spreed/pull/6158)
- Fix issues with …
> Add changelog for 12.1.1

- src/components/MediaDevicesSelector.vue
- src/utils/webrtc/MediaDevicesManager.js
This will allow a laptop to recover after being disconnected from
a docking-station for one call and being docked afterwards again
to use the previous selected device again.
> Don't save device selection when there is only one device

- src/components/MediaDevicesSelector.vue
- src/utils/webrtc/MediaDevicesManager.js
This will allow a laptop to recover after being disconnected from
a docking-station for one call and being docked afterwards again
to use the previous selected device again.
Backport #6160
> [stable22.1] Don't save device selection when there is only one device

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
> Changed spelling of OpenStreetMap

- src/components/MessagesList/MessagesList.vue
Depending on invocation order otherwise the computed
could be first used before the element was mounted to the DOM.
That would cache the computed and cause the element
to never exist although it was added to the DOM afterwards.
The problem with a cached "null" is that
"first unread message has not been seen yet, so don't move it"
then always exited the updating of the readmarker.
---
Might not solve the read-marker topic completely. I still have the issue on the company instance where I wonder why the following code would exit on the first already seen message instead of the message that is last fully displayed on the screen:
https://github.com/nextcloud/spreed/blob/050b0901e49fe4071b4ea66c9fcf740cf7e4439d/src/components/MessagesList/MessagesList.vue#L634-L644
But after talking with …
> Move unreadMessageElement from computed to a method

- CHANGELOG.md
- Add "Create conversation" button on first page of dialog when creating a public conversation  [#6206](https://github.com/nextcloud/spreed/pull/6206)
- Add some validation for shared geo-locations  [#6242](https://github.com/nextcloud/spreed/pull/6242)
- Move unreadMessageElement from computed to a method  [#6241](https://github.com/nextcloud/spreed/pull/6241)
- Fix logged-in users are unable to join a password protected public conversation  [#6230](https://github.com/nextcloud/spreed/pull/6230)
- Don't toggle the video on/off when pasting files into the chat and first releasing the CTRL key  [#6198](https://github.com/nextcloud/spreed/pull/6198)
- Disable recording voice messages on readonly conversations  [#6182](https://github.com/nextcloud/spreed/pull/6182)
- Add some validation for …
> Add changelog for 10.0.10, 10.1.7, 11.3.2, 12.1.2 and 12.2.0

- tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
- tests/php/Chat/SystemMessage/ListenerTest.php
- tests/php/Notification/NotifierTest.php
Run tests using PHPUnit 9.5.6
Replaced all calls to method `at` by more specific functions
close #6228
> Fix: remove warnings on phpunit9.5.6

- lib/Service/ParticipantService.php
Happened to me multiple times with the iOS app which sends the add requests in parallel
Can really write a test for it, but the flow is basically the following:
Request to add group with user "test1" | Request to add user "test1"
---|---
Gets list of participants | Gets list of participants
Gets group members | …
… | Adds user
Adds each user 💥 | ✅ 
Before:
```
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 53-users-admin for key oc_talk_attendees.ta_ident
```
> Don't error hard when adding users to room

- appinfo/info.xml
- docs/capabilities.md
- docs/conversation.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Controller/RoomController.php
- lib/Migration/Version13000Date20210901164235.php
- lib/Model/Attendee.php
- lib/Model/AttendeeMapper.php
- lib/Model/SelectHelper.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/mentions.feature
- tests/php/CapabilitiesTest.php
This allows the UI can show the user bubble depending on user vs. all mentions
Backend for #4623
> Add a flag for the direct mentions

- tests/integration/features/chat/read-status.feature
Before this was shown in the output:
```
--- FeatureContext has missing steps. Define them with these snippets:
/**
* @Given user :arg1 creates room :arg2 (v3)                                                                                                                                                                                                                                
*/                                                                                                                                                                                                                                                                         
public function userCreatesRoomV($arg1, $arg2, TableNode $table) …
```
> Fix missing step in read-status integration tests

- src/utils/webrtc/simplewebrtc/localmedia.js
The `stopped speaking` events emitted by the audio monitor are not immediately relayed, but once a grace period of one second has elapsed. However, when the user starts to speak again the timeout was not cleared, so the `stopped speaking` event was emitted even if the user started to speak again.
This could mess with the components that rely on the `stopped speaking` event, like the _speaking while muted_ warner.
- Start a call
- Mute yourself
- Say "AAAAAA" to the microphone until the _speaking while muted_ warning appears
- Stop briefly (less than a second)
- Say "AAAAAA" again for some seconds
The _speaking while muted_ warning is kept shown until you stop saying "AAAAAA" for the second time
The _speaking while muted_ warning disappears even if you are saying "AAAAAA" for a second time
> Fix "stopped speaking" events still emitted once started to speak again

- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
Fix #4623 
requires https://github.com/nextcloud/nextcloud-vue/pull/2208 to be released
> Differentiate between direct mentions and group nmentions

- lib/Chat/ChatManager.php
- lib/Controller/ChatController.php
- tests/php/Chat/ChatManagerTest.php
- tests/php/Controller/ChatControllerTest.php
I moved the logic of add `@all` on the mentions array to a specialist method and refactored the logic to make more clean to add new mentions types and of course, I added `@here`
When I do a GET to `/api/{apiVersion}/chat/{token}/mentions` with query string `?search=here`
The response object will need a element on data property with `id: all`
> Moved code to specialist method and add fallback to all

- src/utils/webrtc/simplewebrtc/localmedia.js
If a call is started and no audio nor video device is selected there will be no stream in the local media. If a device is then selected a new MediaStream will be created to add the track to it. However, the event did not include the stream that the track was added to but a null object, so when the event was handled [calling `RTCPeerConnection.addTrack()` failed due to being given a null stream](https://github.com/nextcloud/spreed/blob/bf078427d5bf60b65bd60d17e979511c5a28b8e4/src/utils/webrtc/simplewebrtc/peer.js#L878). Now the event includes the stream that the track was added to, which will be either the already existing stream or the one just created.
Although `addTrack` failed in `master` and Talk 12 enabling the device happened to work [due to the exception being …
> Fix null stream given to RTCPeerConnection.addTrack

- src/utils/EmitterMixin.js
- src/utils/webrtc/MediaDevicesManager.js
- src/utils/webrtc/analyzers/CallAnalyzer.js
- src/utils/webrtc/analyzers/ParticipantAnalyzer.js
- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
- src/utils/webrtc/models/CallParticipantCollection.js
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/models/LocalMediaModel.js
The EmitterMixin is not a Vue mixin but a raw JavaScript mixin, so it is stored in "src/utils" rather than in "mixins".
The emitter code was almost the same in all classes, except that some classes allowed triggering events without parameters and others did not. The mixin uses the most generic code, that is, the one that also allows triggering events without parameters.
> Extract common emitter code to mixin

- lib/Activity/Setting.php
* Chat mentions have custom notifications
* Calls have custom notifications and vanish when you participated
* Invites to new conversations have custom notifications
There are no other activities
Fix #6302
> Don't allow to get pushes for Talk activity

- lib/Chat/Notifier.php
- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Model/Session.php
- lib/Service/ParticipantService.php
- tests/php/Chat/NotifierTest.php
1. As user 1 create a chat with user 2
2. Set the setting to be notified for all messages
2. Join with the android/ios app into a chat
3. Join the call and kill the app
4. Optional: Make sure there is still a session entry in oc_talk_sessions
5. Wait 30 seconds
5. As user 2 open the chat 
6. Write a message into the chat (without mentioning the user)
1. As user 1 create a chat with user 2
2. Set the setting to be notified for all messages
2. Switch to a different conversation
3. Manually create a valid session entry in oc_talk_sessions for user 1 with a last_ping far in the past
5. As user 2 open the chat 
6. Write a message into the chat (without mentioning the user)
No notification for user 1
Notification for user 1
> Ignore sessions older than 30 seconds on notifications again

- lib/BackgroundJob/RetryJob.php
- lib/Chat/Notifier.php
- lib/Controller/RoomController.php
- lib/Exceptions/CannotReachRemoteException.php
- lib/Exceptions/RoomHasNoModeratorException.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Federation/Notifications.php
- lib/Manager.php
- lib/Model/AttendeeMapper.php
- lib/Service/ParticipantService.php
- lib/Service/RoomService.php
- tests/php/Federation/FederationTest.php
For #5723 
This adds the backend for sending room shares.
Also includes tests for some of the sending and receiving functions.
> Add sending room shares support

- src/components/CallView/Grid/Grid.vue
Follow up to #6419
When `videosCap` is set it was always applied, no matter the actual number of videos. Due to this, even if there was just a single remote video, as the available size was calculated based on the limit rather than on the actual number of videos a mostly empty grid was shown.
- Start a call
The space is equally distributed between the remote user and the local user
A mostly empty grid is shown; the remote and local participants are each shown in a small area
> Fix grid when the number of videos is below the limit

- docs/chat.md
- lib/Activity/Listener.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Controller/CallController.php
- lib/Events/ModifyEveryoneEvent.php
- lib/Events/ModifyRoomEvent.php
- lib/Room.php
- lib/Service/ParticipantService.php
- src/components/TopBar/CallButton.vue
- src/services/callsService.js
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/utils/signaling.js
- src/utils/webrtc/index.js
- src/utils/webrtc/webrtc.js
- tests/php/Chat/Parser/SystemMessageTest.php
---
---
Fixes https://github.com/nextcloud/spreed/issues/5395
> 📅 End meeting for all

- composer.lock
- lib/Controller/ChatController.php
- psalm.xml
- tests/php/Controller/ChatControllerTest.php
Follow up to #6410 based on new public API from server in 23 https://github.com/nextcloud/server/pull/29444
Fix #6420
> Use public API of trusted domain helper

- lib/Profile/TalkAction.php
Use a more descriptive displayId for the profile action, "Reach me via Talk" instead of just "Talk", so that it's clearer when users are configuring their profile settings, as suggested by @nimishavijay
i.e.
> Use a more descriptive displayId

- src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Fix #6277 
Besides the fix below there is still another issue found in #6277, but that will be fixed in another pull request (that issue prevents the connection warning from appear, this pull request fixes the connection warning appearing when it should not).
With simulcast the connection stats reported by Firefox only contain one `outbound-rtp` and one `remote-inbound-rtp` stat for video, just like when simulcast is not in use. However, the stats reported by Chromium contain several entries, one for each stream quality. As the PeerConnectionAnalyzer assumed that a single entry of each kind will be reported the stat for the last stream overrode the other ones.
Moreover, in some cases no packets could be sent in one of the streams, yet the others could be working fine, so the receivers …
> Fix connection analyzer when using simulcast with Chromium

- lib/TInitialState.php
- package-lock.json
- package.json
- src/utils/webrtc/simplewebrtc/peer.js
When `prefer_h264` is set the SDP is modified to place H.264 as the preferred codec. However, this change in the SDP clashes with the changes done to enable simulcast with Chromium and sometimes causes creating the offer to fail. Given that preferring H.264 has no effect when the HPB is used (as only VP8 is supported in that case) and that simulcast can be enabled only with the HPB now `prefer_h264` is ignored when simulcast is used.
- Set up the HPB (a recent version with support for simulcast)
- Enable preference for H.264 with `occ config:app:set spreed prefer_h264 --value=yes`
- Open a conversation in Chromium
- Start a call with a hardware camera (virtual cameras work fine; maybe some hardware cameras work fine too, I do not know)
The connection is established.
The connection is not …
> Ignore preference for H.264 when simulcast is used

- lib/Controller/SignalingController.php
Fix #6445 
Fix #6446 
Otherwise it exists here:
https://github.com/nextcloud/spreed/blob/1e1cd5e25f785c32f33fc8af63b9d887d9d2a408/src/utils/webrtc/webrtc.js#L966-L968
> Reconnect when permissions change with internal signaling

- src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
[`PermissionsEditor` expects that a display name is given when shown for a participant](https://github.com/nextcloud/spreed/blob/0d71899cb3df0c87bbba3c786bacbaa126c20456/src/components/PermissionsEditor/PermissionsEditor.vue#L140). Display name of unnamed guests is empty, so the default "Guest" string needs to be provided in that case.
- Open a conversation as a moderator
- In a private window, join the conversation as a guest
- As the moderator, edit permissions for the guest
The permissions editor dialog is shown.
The permissions editor dialog is not shown; `you need to fill either the conversationName or the displayName props` is shown in the browser console
> Fix permissions editor dialog for unnamed guests

- lib/AppInfo/Application.php
- lib/Config.php
- lib/Controller/RoomController.php
- lib/Federation/FederationManager.php
- lib/Federation/Notifications.php
- lib/TInitialState.php
- src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
- src/services/conversationsService.js
- src/services/conversationsService.spec.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
- tests/php/Federation/FederationTest.php
> Start with integration tests for invites

- src/components/CallView/shared/Video.vue
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/webrtc.js
**Reviewers:** please note that this adds _translateable_ strings!
Until now when a participant was not connected a loading spinner was shown on that participant. Now an explicit message is shown when there are connection problems (which may heal by themselves) and when the connection is tried to be established again to solve the problems (either because the connection actually failed, or because the problems did not heal by themselves after several seconds, even if the connection has not failed yet).
`.connection-message` needs to take into account whether the video or the avatar is shown to place the message at the right height.
**Example with video:**
**Example with avatar:**
- Do not setup the HPB
- Start a call
- In a different machine, join the call
- Unplug the Internet cable from …
> Show message about problems in the connection with another participant

- src/components/CallView/shared/LocalMediaControls.vue
- src/components/DeviceChecker/DeviceChecker.vue
- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.worker.js
- src/utils/media/pipeline/VirtualBackground.js
- src/utils/webrtc/models/LocalMediaModel.js
- src/utils/webrtc/simplewebrtc/localmedia.js
Follow up to #6322
Fixes #6481
Until now it was checked if the blur background was supported based on whether Web Assembly was available in the browser and whether the browser supported the needed canvas filter. This could be done statically, without having a VirtualBackground object. However, to blur the background once the VirtualBackground object is created it is also needed to download and compile a TFLite model; this could fail, for example, if the web server is not properly configured to send .wasm files. Now if virtual background is supported but the model failed to load it behaves as if virtual background is not supported.
No user facing message is shown if the model could not be loaded, as there might be other reasons other than a server misconfiguration why that could happen. …
> Fix empty video when blur background model could not be loaded

- lib/Activity/Listener.php
- src/components/TopBar/CallButton.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
> Overwrite hasCall based on chat messages

- css/icons.scss
- src/FilesSidebarCallViewApp.vue
- src/PublicShareAuthSidebar.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBar.vue
> Add the topbar in the sidebars

- src/components/DeviceChecker/DeviceChecker.vue
- src/utils/media/pipeline/VirtualBackground.js
- src/utils/webrtc/index.js
- src/utils/webrtc/models/LocalMediaModel.js
Before | After
---|---
Should still be enough but it's not just a blurry almost single color soup around you, as discussed with @marcoambrosini 
Also background blur is now disabled by default due to it's performance impact.
> Reduce the bluring so it's not "You on a single color" and disable by default

- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/models/LocalMediaModel.js
Fixes #6527
`change:XXX` events should be emitted only if XXX actually changed. In most cases the duplicated events were not a problem, but when background blur was enabled in a call with more than 5 participants it could cause the browser to crash.
SentVideoQualityThrottler starts listening to events when video becomes available, so if `change:videoAvailable(true)` was emitted again the event handlers were duplicated. One of the handlers was set for the `speaking` event, which causes the video quality to be adjusted if needed. When background blur is enabled adjusting the video quality restarts the effect, which causes the video stream to be recreated, which in turn caused `change:videoAvailable(true)` to be emitted.
Due to all this, whenever the user spoke in a large call after another …
> Do not emit "change" events if attribute did not change

- lib/Chat/SystemMessage/Listener.php
After a meeting is ended for all, the individual devices still trigger
the leaveCall routine. This printed a "call_left" message, although
the session has already left due to the moderator.
So in case the call flags of the sessions don't change, we no longer
create those system messages.
1. No HPB
2. Create a group conversation with restricted permissions
3. Start a call as a moderator
4. Join with multiple users
5. As moderator and the meeting
* You started a call
* Bennet Bernetto joined the call
* Carmèn Máría Cruz joined the call
* Ahri Fox joined the call
* Laura Adams ended the call with Ahri Fox, Bennet Bernetto and Carmèn Máría Cruz (Duration 1:08)
* Carmèn Máría Cruz left the call
* Ahri Fox left the call
* Bennet Bernetto left the call
* You started a call
* Ahri Fox joined the …
> No individual leave message when the meeting was ended for all

- src/components/DeviceChecker/DeviceChecker.vue
Otherwise this is a false positive from initially loading the device list
Fix #6500
> Only enable devices when the device selection is shown

- src/components/CallView/shared/LocalMediaControls.vue
1. Join a call
2. Disable mic
3. Scream for seconds
Grey scale volume indicator
green-yellow-red scale volume indicator
> Make the volume indicator grey again when mic is disabled

- src/components/TopBar/TopBar.vue
> Fix topbar height

- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.worker.js
- src/utils/media/pipeline/VirtualBackground.js
When the background blur was enabled and the video quality was changed (due to being in a call with more than five participants and started or stopped speaking) the video flickered (a black screen appeared in between).
There are three sources for the flickering:
- A previous segmentation being processed after the input stream was changed but before the input video finished loading
- The output stream being captured before the first frame was drawn
- Changing between two different output streams
Old segmentations are now discarded based on a frame id; when the input stream is changed the frame id is reset, so if the received segmentation data is for a higher frame id it comes from the previous stream and thus can be ignored (that is, the frame is not rendered).
It seems that the flickering …
> Fix flickering with background blur when changing quality

- CHANGELOG.md
- Fix several issues with the new call view and media controls  [#6554](https://github.com/nextcloud/spreed/pull/6554)  [#6571](https://github.com/nextcloud/spreed/pull/6571)  [#6576](https://github.com/nextcloud/spreed/pull/6576)  [#6575](https://github.com/nextcloud/spreed/pull/6575)
- Don't always enable devices when the device picker is shown  [#6567](https://github.com/nextcloud/spreed/pull/6567)
- Opening the conversation settings via the conversation list opened with wrong data  [#6584](https://github.com/nextcloud/spreed/pull/6584)
- Fix issues with the background blurring  [#6586](https://github.com/nextcloud/spreed/pull/6586)
- Fix call summary in one-to-one conversations  [#6564](https://github.com/nextcloud/spreed/pull/6564)
- The video will "zoom in and out" when more than 4 …
> Add changelog 13.0.0-rc.3

- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
Follow up to #6569 
The input track is played in a video element which, in turn, is drawn on the canvas used to calculate the segmentation mask and on the output canvas. When the resolution of its input track changes a video element may still play the track using the old resolution for some frames (it happens with real hardware cameras, although apparently not with virtual devices), even if `track.getSettings()` already returns the new resolution.
Due to this mismatch, when the resolution of the input track changed (for example, due to a quality change in a call with several
participants), the video could zoom in and out, as the output canvas size was based on the new size, while the video element drawn on it was still using the old size.
Fortunately, the `videoWidth` and `videoHeight` …
> Fix video zoom jump with background blur when changing resolution

- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
The blur value was a fixed value that did not change depending on the input video size. Due to this the background of lower resolution videos looked more blurry than the background of higher resolution videos, and this was specially noticeable when the same video changed its resolution. Now the blur is proportional to the input video size, so the blurred background always looks the same even if the resolution changes (provided the same aspect ratio is kept between the different resolutions).
**Reviewers:** The blur factor is based on a 720 pixels wide video. The [default blur value](https://github.com/nextcloud/spreed/blob/c3721fde8fb481412d44364424b3080af6fa3110/src/utils/media/pipeline/VirtualBackground.js#L154) might need to be [adjusted …
> Make background blur proportional to the input video size

- src/utils/media/pipeline/MediaDevicesSource.js
This fixes a regression introduced in fc7cbad18a9e1c4dcbcc5209886a3abee6a1cf23
When the MediaDevicesSource node is active and a media device changes the current stream is replaced by a stream from the new selected device. This is an asynchronous operation, so changing the stream again on further device changes is deferred until the previous one finished.
However, when the changed device was the same as the current device the pending request count was not cleared and thus any further device change was ignored until the page was reloaded.
In general the scenario addressed here should not happen. But... in theory it could potentially happen if the browser emitted two `devicechange` events immediately one after the other (the second one should be handled even before a promise triggered by the …
> Fix media never requested again when changing again to current device

- src/utils/media/pipeline/MediaDevicesSource.js
Requires #6604 (it does not require it, but the test steps do)
This has been wrong [since the beginning](https://github.com/nextcloud/spreed/commit/c81c912488914f699a2f8fa45b75105b6692201e) :facepalm: but in the past it happened to work in most cases due to a lucky code flow. However, [since the refactoring](https://github.com/nextcloud/spreed/commit/b8fc1b28f32ac72cb8212b0a71e2c6a22403efcd) it no longer worked due to requiring both call parameters to be properly defined.
As the method was [recursively called from the handler of the previous "getUserMedia" promise](https://github.com/nextcloud/spreed/blob/43609c705a28cc884b60e8c6189ff66cd308ad5d/src/utils/media/pipeline/MediaDevicesSource.js#L324) trying to [access "getUserMedia()" on a …
> Fix pending device not requested once current request finishes

- CHANGELOG.md
- The segmentation model of the background blur was replaced  [#6597](https://github.com/nextcloud/spreed/pull/6597)
- Fix missing default permissions when opening the permissions editor  [#6614](https://github.com/nextcloud/spreed/pull/6614)
- Fix issues with device selection after muting, disconnecting and more  [#6601](https://github.com/nextcloud/spreed/pull/6601)  [#6609](https://github.com/nextcloud/spreed/pull/6609)  [#6615](https://github.com/nextcloud/spreed/pull/6615)
- Fix issues with the background blurring  [#6594](https://github.com/nextcloud/spreed/pull/6594)  [#6600](https://github.com/nextcloud/spreed/pull/6600)
> Add changelog for 13.0.0-rc.4

- src/mixins/devices.js
Fixes #6630
Requesting a stream is an asynchronous operation, and it may take a while to be fulfilled (for example, if the user needs to grant the browser permission to use the device). When the Talk settings and the device checker dialogs are closed the streams being used are stopped, but this will have no effect if the promises that returns the streams are fulfilled after that. In that case the streams need to be explicitly stopped once finally got.
The steps below refer to an additional scenario besides what is described in #6630.
- If they are granted, revoke permanent permissions in the browser so it asks again when audio or video is requested
- Open Talk settings; the browser will ask for permissions, ignore it for now
- It can be reproduced too with the device checker
- Close Talk …
> Fix devices not released when got after the dialog was closed

- lib/Notification/Notifier.php
- tests/php/Notification/NotifierTest.php
* Ref https://github.com/nextcloud/desktop/issues/2908
* Ref https://github.com/nextcloud/notifications/issues/637
@thisIsTheFoxe please confirm your PR has been adjusted before it was merged into the iOS app
> Expose message id for desktop client and notifications quick reply

- CHANGELOG.md
12.2.2 list is shorter then the milestone, because 22.1 and 22 were merged inbetween and also some stuff that was merged for 22 but was before already released with 12.2.1
---
- Show user status and message as description in 1-to-1 conversations  [#6369](https://github.com/nextcloud/spreed/pull/6369)
- Allow apps to override/modify the TURN server list  [#6428](https://github.com/nextcloud/spreed/pull/6428)
- Fix connection analyzer when using simulcast with Chromium  [#6530](https://github.com/nextcloud/spreed/pull/6530)
- Properly allow sha256 checksums for reference ids as advertised  [#6406](https://github.com/nextcloud/spreed/pull/6406)
- Fix forwarding object shares to other conversations  [#6398](https://github.com/nextcloud/spreed/pull/6398)
- Fix invisible emoji picker on Safari …
> Add changelog for 11.3.4 and 12.2.2

- src/utils/media/pipeline/TrackSourceMixin.js
- src/utils/media/pipeline/VirtualBackground.js
- src/utils/media/pipeline/VirtualBackground.spec.js
Fixes #6650
When an output track was stopped it was automatically removed. When the virtual background is disabled the input track is bypassed to the output, but first the effect is stopped. This caused a null track to be temporary set as the output track before setting the input track which, in turn, caused different issues in other parts of the code (like causing the video to hang in the device checker due to the stream being removed, disabling the video during calls when disabling the background blur due to the null stream being handled as "no video", or reconnecting when disabling the video during calls if background blur was enabled due to a loop in the event handling which caused the events to be handled in the wrong order).
To prevent all that now, when the virtual background is …
> Fix output track when disabling virtual background

- src/components/MessagesList/MessagesList.vue
- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
Reverts #6686
Reverts #6641
Please refer to the commit messages for details.
- Create a public conversation and add user A
- Create a one to one conversation with user B
- Create a public conversation and add user B
- In a private window, log in as user A
- In another browser, log in as user B
- In the original window, open the main Talk view (_apps/spreed/_)
- Join the first public conversation
- Join the one to one conversation
- Join the second public conversation again
- Join the one to one conversation
- Join the first public conversation
There are no errors
`Participant not found in conversation XXX` is shown in the console, where XXX is the one to one conversation token and the participant is user A
> Fix unsubscribing listener for status updates

- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
Backport of #6690 
#6689 was not merged yet, so that pull request was closed and the commit from #6690 that reverted it was dropped.
> [stable23] Fix unsubscribing listener for status updates

- CHANGELOG.md
- Fix various issues with enabling/disabling the camera and background blur  [#6688](https://github.com/nextcloud/spreed/pull/6688)
- Fix unregistering of user status listener which lead to a memory leak with Nextcloud 23  [#6643](https://github.com/nextcloud/spreed/pull/6643)
- Device not released when closing settings dialog immediate after opening  [#6638](https://github.com/nextcloud/spreed/pull/6638)
- Disable emoji picker in read-only conversations  [#6662](https://github.com/nextcloud/spreed/pull/6662)
- Make conversation settings scrollable again  [#6682](https://github.com/nextcloud/spreed/pull/6682)
- Make the pagination buttons more and clearly visible in the grid view  [#6695](https://github.com/nextcloud/spreed/pull/6695)
> Add changelog for 13.0.1

- src/utils/media/pipeline/VirtualBackground.js
- src/utils/media/pipeline/VirtualBackground.spec.js
Fixes #6702
When the background blur was enabled and the input track was disabled the blur effect was started. Starting the effect caused the output track to be enabled (which was just a blurred black stream), and this caused* the local video to be enabled. Now the effect is not started and the output track is not modified if the background blur is enabled when the input track is disabled.
*Things were actually a bit more fun. When participants join a call it is not possible to know when those participants are ready to receive messages, so the current media state is sent several times with an increased delay between each message. This is done by [emitting `videoOn` or `videoOff` depending on whether the video is enabled or not](https://github.com/nextcloud/spreed/blob/362b956001c2e20fa128a …
> Fix enabling background blur when input track is disabled

- src/components/MessagesList/MessagesList.vue
This can happen if the browser is fast enough to close the sidebar
when switching from a one-to-one to a group conversation.
Fix #6715
> Prevent handleScroll on initial loading of a conversation

- src/utils/sounds.js
Regression from #6713 
> /apps/spreed/img/join_call.wav:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> Uncaught (in promise) DOMException: Failed to load because no supported source was found.
> FIx path to files

- src/components/SettingsDialog/SettingsDialog.vue
Changed the word "Video" to "Camera" for the keyboard shortcut in the application options.
> l10n: Change "Video" to "Camera"

- README.md
The readme previously pointed to the commercial SimpleWebRTC product, that has little in common with the deprecated open source library.
> docs(readme): point to SimpleWebRTC library

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/TopBar/CallButton.vue
There were still some 24px icons around, this pr gets rid of those.
> Fix material design icon sizes

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
The display name is not set for unnamed guests, so the computed name (which is the one shown in the participant list) should be used instead.
- In a private window, join the conversation as a guest
- In the original window, grant all permissions to the guest
The notification shows `Permissions granted to Guest`
The notification shows `Permissions granted to`
> Fix empty name for unnamed guests in permissions change notifications

- src/components/CallView/shared/LocalVideo.vue
- src/utils/signaling.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
Fixes #5929
When a participant joins a call with audio but not video and then selects a camera during the call [the call flags are updated](https://github.com/nextcloud/spreed/blob/362b956001c2e20fa128a503f7c3e5f1d6680912/src/utils/webrtc/webrtc.js#L1318) and then [a forced reconnection is used](https://github.com/nextcloud/spreed/blob/362b956001c2e20fa128a503f7c3e5f1d6680912/src/utils/webrtc/webrtc.js#L956) to update the connection (as proper renegotiation is not implemented yet). However, the signaling message that is triggered after the call flags are updated can be received once the forced reconnection has started and [all the participants were already removed](https://github.com/nextcloud/spreed/blob/362b956001c2e20fa128a503f7c3e5f1d6680912/src/utils/webrtc/webrtc.js#L910); as the …
> Make own peer related code more robust

- src/components/CallView/shared/VideoBackground.vue
Since we don't blur the avatar anymore, I wonder if we should get rid of that request and just use the default color from the two letter avatar.
Yes it's less related to the avatar image, but it helps with performance and most other solutions just use a black background.
> Reduce the set of avatar sizes used

- src/utils/signaling.js
> Don't update the participant list when only you joined

- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-2/one-to-one.feature
- tests/integration/features/conversation-2/sip-dialin.feature
- tests/integration/features/conversation/limit-creation.feature
- tests/integration/features/federation/invite.feature
- tests/php/Service/RoomServiceTest.php
How test:
Background: user1 and user2 exists
Scenario:
- Login with User1
- Open Talk app
- Search by user2
- Define this app settings values:
| appid | configkey                                     | configvalue |
| ----- | --------------------------------------------- | ----------- |
| core  | shareapi_restrict_user_enumeration_full_match | no          |
| core  | shareapi_allow_share_dialog_user_enumeration  | yes         |
| core  | shareapi_restrict_user_enumeration_to_group   | yes         |
| core  | shareapi_restrict_user_enumeration_to_phone   | yes         |
- Click on user1 on search result
- You will need see 4xx error on Network tab on response of request to create conversation
> **PS**: If you define the app settings before do a search for user2 you will never see the user2
> Check share restrictions on one to one conversation

- appinfo/routes/routesChatController.php
- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/CommentsManager.php
- lib/Controller/ChatController.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/unread-messages.feature
- tests/php/CapabilitiesTest.php
Ref https://github.com/nextcloud/talk-android/pull/1752#issuecomment-1002756845
cc @mahibi @Ivansss shall I create you issues in your repo top use this on the conversation list when the item is fully read?
> Allow to mark a conversation as unread

- src/components/TopBar/TopBar.vue
1. User A starts 1-to-1 with User B
2. User A sees User B as offline in top bar
3. User A navigates away
4. User B opens the 1-to-1
5. User B sees User A as online (although they are offline)
> Fix peer user not showing as offline in one-to-one conversations

- src/utils/webrtc/simplewebrtc/simplewebrtc.js
- src/utils/webrtc/webrtc.js
This pull request just removes some unneeded code; everything should work as before (note that [there are some issues when switching between screenshares](https://github.com/nextcloud/spreed/pull/6831), they are unrelated to the changes here).
The most notable removal is an additional and unneeded video element that was created for local screenshares. Until now this had no noticeable effect, but [now that screen shares can have audio too](https://github.com/nextcloud/spreed/pull/6810) it caused the audio of the local screenshare to be played, which could cause a little echo.
> Remove unneeded SimpleWebRTC code

- src/components/CallView/shared/Screen.vue
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/simplewebrtc/getscreenmedia.js
Currently only works in Chrome and Chrome based browsers
and is limited to sharing a ChromeTab or the full system sound.
Fix #3546
> Allow to share audio of screenshares

- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Reverts nextcloud/spreed#6789
Fix #6318
> Revert "6318: fixed mention complete with mouse clicking"

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoBottomBar.vue
- Start a call with user A
- Join the call with user B
- Join the call with user C
- As user A, share a window
- As user B, share a different window
- As user C, share yet another different window (or the whole screen)
- Switch between the screen shares in speaker mode by clicking on the "Show screen" icon on each remote participant or the "Show my screen" menu entry in the top bar
It is possible to switch between the different screen shares.
The local screen share is always shown.
> Fix switching between screenshares

- src/utils/webrtc/webrtc.js
This pull request fixes a regression introduced in https://github.com/nextcloud/spreed/pull/6771/commits/57bca1628062da11f429443b91d47c3bd6d39719
- Start a call
- Stop sharing the screen
The screenshare is stopped in both participants
The screenshare is not stopped in the receiver participant
> Fix screenshare not stopped in receiver participants with HPB

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fix #5486
Adds a buttons bar for message actions in prep for message reactions
https://user-images.githubusercontent.com/26852655/149757685-6e12f719-648d-4108-b896-b47a354c1b81.mov
> Create message buttons bar

- CHANGELOG.md
- Fix stopping a screenshare for recipients  [#6857](https://github.com/nextcloud/spreed/pull/6857)
- Fix switching between screenshares  [#6850](https://github.com/nextcloud/spreed/pull/6850)
- Fix mentions inside brackets  [#6869](https://github.com/nextcloud/spreed/pull/6869)
- Allow using mentions with the mouse  [#6838](https://github.com/nextcloud/spreed/pull/6838)
- Deduplicate round trips when a moderator ends the meeting for everyone  [#6841](https://github.com/nextcloud/spreed/pull/6841)
- Fix message menu misbehaving when the message scrolls outside of the viewport  [#6855](https://github.com/nextcloud/spreed/pull/6855)
> Add changelog for 13.0.3

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessageForm/NewMessageForm.vue
Follow up to #6119
Work around for #6151 until https://github.com/nextcloud/nextcloud-dialogs/issues/427 and https://github.com/nextcloud/viewer/issues/995 are fixed
By default the file picker and the viewer are siblings of the fullscreen element, so they are not visible when in fullscreen mode. It is not possible to specify the parent nor to know when the file picker or the viewer were actually opened, so for the time being they are reparented if needed shortly after calling them.
This is just a temporary hack until it is possible to specify the parent element, but that would require changes in the Vue library, the viewer and the server dialogs, so this horrible code will have to do for now :cry: 
A slightly better work around would be to look for the element to reparent several times in …
> Reparent file picker and viewer in fullscreen mode

- tests/integration/run-docker.sh
PHP 7.3 support was dropped for Nextcloud 24. The Docker image is updated to the same image used for integration tests in CI (personally I would prefer an explicit tag rather than `latest`, but they are not available :shrug:).
> Update image in script to run local integration tests in Docker

- .drone.yml
- appinfo/routes.php
- appinfo/routes/routesReactionController.php
- docs/capabilities.md
- docs/chat.md
- docs/index.md
- docs/reaction.md
- lib/Capabilities.php
- lib/Chat/Notifier.php
- lib/Chat/Parser/Listener.php
- lib/Chat/Parser/ReactionParser.php
- lib/Chat/ReactionManager.php
- lib/Controller/ChatController.php
- lib/Controller/ReactionController.php
- lib/Exceptions/ReactionAlreadyExistsException.php
- lib/Exceptions/ReactionNotSupportedException.php
- lib/Exceptions/ReactionOutOfContextException.php
- lib/Manager.php
- lib/Model/Message.php
- lib/Notification/Notifier.php
- mkdocs.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/reaction/react.feature
- tests/php/CapabilitiesTest.php
- tests/php/Chat/NotifierTest.php
- tests/php/Controller/ChatControllerTest.php
Implement #1920
* When get messages from API, the API will return one more property on message (reaction)
* The reaction message is returned as system message and marked to don't reply
* When the author of reaction delete the reaction, the message will be displayed on on clients same as deleted message
* Don't display messages of type `reaction` and `reaction_deleted`
* When receive the response of endpoint `GET /api/{apiVersion}/chat/{token}` (`receiveMessages`) with `reaction` or `reaction_deleted`, get the id of parent message on reaction and update this.
> **P.S.**: Use the `delete` message type as example to change the reactions counter:
> https://github.com/nextcloud/spreed/blob/091575237c17945b37c7c72ba53c5ad85b1961ae/src/store/messagesStore.js#L255-L258
* Look the tests scenarios …
> Api reactions to message

- src/utils/sounds.js
Fixes a regression introduced in f90f2e7745d6951a50577f6d931b5bb2dd80339b
I have also noticed that if sounds are disabled once the waiting sound started the interval would not be stopped until something else stops it (like leaving the call or another user joining it). I have added a fix for that too, although it is not a big deal and it could be even argued that the interval should be kept running just in case the user enables the sounds again, so feel free to keep it, change it or drop it :-)
- Start a call
- Wait one minute
_Stop waiting sound_ is printed in the console
_Stop waiting sound_ is printed in the console, followed by _Playing waiting sound_ and an error about a null access to `backgroundAudio`
- Start a call
- Open Talk settings and disable sounds …
> Fix stopping waiting sound

- src/components/SettingsDialog/SettingsDialog.vue
Fixes a regression introduced in #6759
- Open Talk settings
No error is printed in the console
[`Error: When using groups of checkboxes, the updated value will be an array`](https://github.com/nextcloud/nextcloud-vue/blob/866c3c030a4a7ebc8203f3e2597fcf12bfe81be7/src/components/CheckboxRadioSwitch/CheckboxRadioSwitch.vue#L345) is printed in the console
> Fix unneeded checkbox name for checkbox not in group

- lib/BackgroundJob/CheckHostedSignalingServer.php
- lib/BackgroundJob/CheckMatterbridges.php
- lib/BackgroundJob/CheckReferenceIdColumn.php
- lib/BackgroundJob/ExpireSignalingMessage.php
- lib/BackgroundJob/RemoveEmptyRooms.php
- lib/BackgroundJob/ResetAssignedSignalingServer.php
Close #6874
| Job                          | interval | status           | detail                                                |
| ---------------------------- | -------- | ---------------- | ----------------------------------------------------- |
| CheckHostedSignalingServer   | 1 hour   | TIME_SENSITIVE   | Check the status of hosted signalign servers          |
| CheckMatterbridges           | 15 min   | TIME_SENSITIVE | Kill zombie bridges                                   |
| CheckReferenceIdColumn       | 1 hour   | TIME_INSENSITIVE | Check if column reference_id exists on comment table. |
| ExpireSignalingMessage       | 5 min    | TIME_SENSITIVE   | Expire signaling message                              |
| RemoveEmptyRooms             | 5 min    | TIME_INSENSITIVE | Remove empty …
> Define if job is time sensitive

- lib/Notification/Listener.php
1. Create 70 users:
```sh
i=10
while [ $i -ne 70 ]
do
i=$(($i+1))
echo "$i"
USERID=$(uuidgen)
OC_PASS="123456" occ -vvv user:add --password-from-env --display-name "Dummy #$i" -g "dummies" $USERID
occ -vvv user:setting $USERID settings email "test$i@yourdomain.tld"
done
```
2. Create a conversation as admin with group "dummies"
3. Start a call
4. Measure time around the section of the diff:
```php
// Add this before the begin of the transaction
$start = microtime(true);
```
```php
// Add this after the commit of the transaction
$end = microtime(true);
\OC::$server->getLogger()->error('notify: ' . ($end - $start));
```
5. Measure the time again with the beginTransaction and commit being commented out
With transaction | Without transaction
---|---
~0.11s | ~0.65s
This is at least …
> Wrap notification generation in a transaction

- lib/Activity/Listener.php
1. Create 70 users:
```sh
i=10
while [ $i -ne 70 ]
do
i=$(($i+1))
echo "$i"
USERID=$(uuidgen)
OC_PASS="123456" occ -vvv user:add --password-from-env --display-name "Dummy #$i" -g "dummies" $USERID
occ -vvv user:setting $USERID settings email "test$i@yourdomain.tld"
done
```
2. Create a conversation as admin with group "dummies" (and check the database queries of this request)
Left is before, right is with this patch
> Only calculate the room name once instead of loading all participants

- lib/Model/SessionMapper.php
- lib/Service/ParticipantService.php
* Replaces O(n) queries with a single query in the "End meeting for all" case
> Reset all in_call flags in one go

- src/components/DeviceChecker/DeviceChecker.vue
The tooltip depended on the wrong property, so it was not updated as needed.
> Fix blur background tooltip not updated in device checker

- src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js
- src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
- src/mixins/getParticipants.js
- src/store/conversationsStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-2/set-permissions.feature
The permissions dialog for participants was using `attendeePermissions` rather than `permissions`, so the dialog showed the default permissions for participants without specific permissions even if conversation permissions were set.
Besides that, the participant list is now reloaded on conversation and call permissions change, as due to the permission chain the actual participant permissions may have changed.
Finally, I have added some integration tests for setting conversation permissions when participant permissions are set; I found a bit surprising that this resets the participant permissions, so better have an explicit test for that behaviour :-)
- Join a conversation as a moderator
- If there is none, add a regular user to the conversation
- Open the conversation settings
- Set some …
> Fix loaded values in permission dialog for participants

- lib/Chat/Notifier.php
- tests/php/Chat/NotifierTest.php
1. Create 70 users:
```sh
i=10
while [ $i -ne 70 ]
do
i=$(($i+1))
echo "$i"
USERID=$(cat /proc/sys/kernel/random/uuid)
OC_PASS="123456" occ -vvv user:add --password-from-env --display-name "Dummy #$i" -g "dummies" $USERID
occ -vvv user:setting $USERID settings email "test$i@yourdomain.tld"
done
```
2. Create a conversation as admin with group "dummies" (and check the database queries of this request)
3. Post a message with `@all`
Message | Before | After
---|---|---
`chat` | 16 | 16
`@employee2` | 23 | 23
`@all` | 367 | 90
Compare query log:
> Inject room and attendee into chat notifier

- src/utils/webrtc/webrtc.js
When the call flags were updated after a renegotiation the senders were checked to decide the flags to set. However, only the track attribute was checked; when a track is disabled the track is nullified in the sender and stored in `trackDisabled` instead, so the call flags were not properly set if any of the tracks was disabled when a new one was added.
Note that when a local track is replaced the call flags are updated and, in that case, the right flags are used, so sometimes this issue could be masked by that.
- Comment the code to [update the call flags when a local track is replaced](https://github.com/nextcloud/spreed/blob/43ebbd09a2b9139601b945a1ab77fc95a30a5290/src/utils/webrtc/webrtc.js#L1335-L1339)
- Start a call with audio but no video
- Disable audio (if it was …
> Fix call flags update when track is disabled

- src/utils/media/pipeline/TrackEnabler.js
- src/utils/media/pipeline/TrackEnabler.spec.js
- src/utils/media/pipeline/TrackToStream.js
- src/utils/media/pipeline/TrackToStream.spec.js
- src/utils/webrtc/index.js
- src/utils/webrtc/models/LocalMediaModel.js
Call flags may not be updated to the right values without #7013
Since defe61742 when a media device (microphone or camera) is selected during a call in which the user joined without media of that kind the media is automatically enabled. This is an unexpected behaviour for the user, so even if a media device is selected it should be kept disabled until explicitly enabled by the user.
However, just reverting the commit to explicitly disable again the media is not a valid approach, as in some scenarios the event handler could disable again the media that was being enabled even before the other event handlers were executed (thus causing them to handle first the disabled event and then the enabled event), which ends messing up the state of the objects.
For example, when joining a call with …
> Fix media automatically enabled after selecting a device during a call

- CHANGELOG.md
- appinfo/info.xml
- Fix several modals, dialogs and popovers in fullscreen mode [#6885](https://github.com/nextcloud/spreed/pull/6885)
- Fix issues when permissions of a participant or conversation are changed right before joining a call [#6996](https://github.com/nextcloud/spreed/pull/6996) [#7018](https://github.com/nextcloud/spreed/pull/7018)
- Fix media automatically enabled after selecting a device during a call [#7017](https://github.com/nextcloud/spreed/pull/7017)
- Fix call flags update when track is disabled [#7016](https://github.com/nextcloud/spreed/pull/7016)
- Show the version number also when the HPB backend is not older [#6890](https://github.com/nextcloud/spreed/pull/6890)
- Correctly stop waiting sound when someone joins the call [#6919](https://github.com/nextcloud/spreed/pull/6919)
- …
> Add changelog for 11.3.6, 12.2.4 and 13.0.4

- .github/workflows/phpunit.yml
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Notification/Notifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- tests/php/Service/ParticipantServiceTest.php
MySQL docs:
> Reject queries for which the select list, HAVING condition, or ORDER BY
list refer to nonaggregated columns that are neither named in the GROUP BY
clause **nor are functionally dependent on (uniquely determined by) GROUP BY columns**.
MariaDB docs:
> For SELECT ... GROUP BY queries, disallow SELECTing columns which are
not referred to in the GROUP BY clause, unless they are passed to an
aggregate function like COUNT() or MAX(). Produce a 1055 error.
> Group on PHP level as MariaDB can not handle this correctly

- .drone.jsonnet
- .drone.yml
> Try setting only full group by option integration

- .drone.yml
- .github/workflows/phpunit.yml
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Notification/Notifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- tests/php/Service/ParticipantServiceTest.php
> [stable23] Set MySQL ONLY_FULL_GROUP_BY config and run on MySQL for PRs

- lib/Share/Helper/ShareAPIController.php
- tests/integration/features/bootstrap/SharingContext.php
Otherwise the comment from the catch block applies:
"Removing the conversation token from the leaked data if not a participant ..."
> Only add the share_with_link url when the link is accessible

- .drone.yml
- .github/workflows/phpunit.yml
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Notification/Notifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- tests/php/Service/ParticipantServiceTest.php
Backport of #7032 
Backport of #7036
> [stable22] Set MySQL ONLY_FULL_GROUP_BY config and run on MySQL for PRs

- src/components/CallView/shared/VideoBackground.vue
WIP, Marco wants to get the average color from an existing image we might have loaded already.
Otherwise we go with this for 24
Before | After
---|---
> Don't use the avatar for the callview background, to save O(n^2) requests

- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Controller/ChatController.php
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/file-share.feature
- tests/integration/features/chat/rich-object-share.feature
- tests/php/CapabilitiesTest.php
- tests/php/Chat/ChatManagerTest.php
Remarks:
- Moderators and owner of the share will unshare the share completely, others can only remove the message
- Files currently always remain available for the owner as per long discussions in the past, because we can not know if the file is used in any other way in parallel.
> Allow to delete shared files and objects

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/store/reactionsStore.js
> Fix detection if the user (not author) reacted already

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
using event.composedPath() instead of event.path to fix
````
Uncaught TypeError: event.path is undefined
handleClickOutside MessageButtonsBar.vue:483
c vue-outside-events.min.js:9
bind vue-outside-events.min.js:9
VueJS 25
> Fix closing MessageButtonsBar on Firefox

- src/utils/media/pipeline/MediaDevicesSource.js
- src/utils/media/pipeline/MediaDevicesSource.spec.js
- src/utils/webrtc/models/LocalMediaModel.js
- src/utils/webrtc/simplewebrtc/localmedia.js
- src/utils/webrtc/webrtc.js
Fixes #7048
Until now the WebUI code treated audio and video permissions as a combined permission: either both were enabled or both were disabled. This was inherited from the initial implementation, but it is no longer the case; it is possible to have audio permissions without video permissions and the other way around.
Besides that this pull request also fixes some other related issues.
Unfortunately there are a lot of possible combinations between permissions and devices, as can be seen by the scenarios below (which only include those that currently fail, there are even more :cry:).
Pending:
- Remove audio and video permissions by default in a conversation
- Start a call as a moderator
- In a private window, open the conversation as a guest
- Join the call with both …
> Fix reconnections on single media permission changes

- docs/Talkbuchet.js
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/StunServers.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/TurnServers.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/utils/signaling.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- src/utils/signaling.js
When a forced reconnection is triggered and the HPB is not used there are several race conditions that can prevent the participant from automatically joining the call again, or prevent other participants to establish the connection again with that participant.
First, when the call was joined again it was not waited for the call to be left first, so it could happen that the leave and join request were sent and the join request ended being processed first, so once the leave call request was processed the participant did not join.
Second, if joining the call takes too long the `inCall` property for the participant who is reconnecting could be _not in the call_ when the `usersInRoom` signaling message is sent. If that happens the WebUI could understand that as [the call having being ended by …
> Fix forced reconnections when the HPB is not used

- .drone.jsonnet
- .drone.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/notifications.feature
- tests/integration/features/conversation/add-participant.feature
- tests/integration/run.sh
- tests/integration/spreedcheats/lib/Controller/ApiController.php
> Add integration tests for notifications

- lib/Notification/Notifier.php
- tests/integration/features/chat/notifications.feature
> Remove notifications for deleted messages

- tests/php/phpunit.xml
Following the sample of https://github.com/nextcloud/server/pull/31750
> Make tests fail when deprecated php functions are used

- lib/Chat/Parser/SystemMessage.php
- tests/integration/features/reaction/react.feature
> Remove reactions from deleted messages

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/store/messagesStore.js
- src/store/reactionsStore.js
> Reset reaction details list when a reaction is added or removed

- docs/Talkbuchet.js
Until now the script had to be edited to set the right configuration parameters and then copied and pasted on the browser console; running the script again required reloading the page and pasting it again, even if the parameters where not modified. 
Now the constants were changed to variables and helper functions were added to set them, so the script can be pasted without changes and the configuration can be adjusted by calling the helper functions. Moreover, as there is now an explicit function to start the siege the script can be run several times and with different parameters without having to reload the page and paste it again.
> Adjust Talkbuchet to be runnable with different parameters

- lib/Share/RoomShareProvider.php
[Null coalescing assignment operator](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.null-coalescing-assignment-operator) was implemented on PHP7.4 and make the code more clean.
```php
return static function (ContainerConfigurator $containerConfigurator): void {
$parameters = $containerConfigurator->parameters();
$parameters->set(Option::PATHS, [
__DIR__ . '/lib',
__DIR__ . '/tests/php',
]);
$parameters->set(Option::BOOTSTRAP_FILES, [
__DIR__ . '/vendor/autoload.php',
__DIR__ . '/../../lib/composer/autoload.php',
__DIR__ . '/../../3rdparty/autoload.php',
]);
$services = $containerConfigurator->services();
$services->set(NullCoalescingOperatorRector::class);
};
```
> Convert to null coalescing assignment operator

- src/views/Dashboard.vue
Regression from dd8d415473d7a39ecfcfaec7cea0f4b52466c796
Fix #6868
> Remove undefined property or method usage

- Makefile
From release todo https://github.com/nextcloud/spreed/issues/7123
>On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
>    ```sh
>    make appstore
>    ```
> Adjust packaging exclude list for 24

- CHANGELOG.md
- Fix reconnection when media permissions change [#7092](https://github.com/nextcloud/spreed/pull/7092)
- Fix forced reconnection without the High-performance backend [#7095](https://github.com/nextcloud/spreed/pull/7095)
- Compatibility with LDAP user backends and more than 64 characters display names [#7073](https://github.com/nextcloud/spreed/pull/7073)
- Compatibility with Oracle and MySQL ONLY_FULL_GROUP_BY [#7036](https://github.com/nextcloud/spreed/pull/7036)
- Fix broken avatars when search for users to add to a conversation [#7037](https://github.com/nextcloud/spreed/pull/7037)
- Fix sort order of guests and logged-in users [#7053](https://github.com/nextcloud/spreed/pull/7053)
- Allow copying links of open conversations without joining …
> Add changelog for 12.2.5 and 13.0.5

- CHANGELOG.md
- appinfo/info.xml
- Compatibility with LDAP user backends and more than 64 characters display names [#7074](https://github.com/nextcloud/spreed/pull/7074)
- Compatibility with Oracle and MySQL ONLY_FULL_GROUP_BY [#7040](https://github.com/nextcloud/spreed/pull/7040)
> [stable22] Add changelog for 12.2.5

- CHANGELOG.md
- Reactions for chat messages
- Implement `OCP\Talk\IBroker` to allow apps to create conversations
- Sharing a browser tab in Chrome-based browsers can now also share the audio of that tab [#6810](https://github.com/nextcloud/spreed/pull/6810)
- Media tab showing all shared items of the conversation
- Messages of shared objects and files can now be deleted (shares will be removed, files persist) [#7047](https://github.com/nextcloud/spreed/pull/7047)
- Actions like calling and chatting in big rooms should now be much smoother
- Compatibility with Nextcloud 24
> Changelog for 14.0.0 beta.1

- src/components/NewMessageForm/NewMessageForm.vue
Fix #7098 
Before | After
---|---
> Use tertiary-no-background for emoji picker

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
> 3299: updated unread mentions viewport of conversation list

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Fix #7132 
Couldn't find a reason to keep the z-index, only when you hover the next message the hover-background will overlap the menu a little bit (see second screenshot row). But from my POV that's less important than the first case where it prevents you from using certain actions.
x | Before | After
---|---|---
Menu overlap | ![Bildschirmfoto von 2022-04-11 16-43-37](https://user-images.githubusercontent.com/213943/162765430-4fcae298-0d6d-4e52-aed3-3568d8c96a2b.png) | ![Bildschirmfoto von 2022-04-11 16-42-41](https://user-images.githubusercontent.com/213943/162765449-9a400265-5641-48ed-ae5e-db0b664f913d.png)
Hoverbackground overlap | ![Bildschirmfoto von 2022-04-11 16-43-49](https://user-images.githubusercontent.com/213943/162765465-809bb1ea-021e-473e-a9db-b6fa07dc9ddf.png) | …
> Fix menu overlap

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Before clicking a category was "outside" of the message button bar
and therefor closed the reactions popover.
> Fix category selection in reactions emoji picker

- CHANGELOG.md
- appinfo/info.xml
> Add changelog and bump version

- lib/Chat/ChatManager.php
- lib/Chat/ReactionManager.php
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
2. Write a chat message "Message 1"
3. Add reaction ❤️
4. Navigate to main page of talk
5. Assert last message is "You: Message 1" ✅ 
6. Open the conversation
7. Assert last message is "You: Message 1" ❌ see "❤️" instead
2. Write a chat message "Message 1"
3. Add reaction ❤️
4. Remove reaction ❤️
5. Navigate to main page of talk
6. Assert last message is "You: Message 1" ❌ see "You deleted a reaction" instead
7. Open the conversation
8. Assert last message is "You: Message 1" ❌ see "You deleted a reaction" instead
2. Write a chat message "Message 1"
3. Write a chat message "Message 2"
4. Delete "Message 1"
5. Navigate to main page of talk
6. Assert last message is "You: Message 2" ❌ see "You deleted a message" …
> Don't update last message of conversation with invisible message

- src/components/RightSidebar/SharedItems/SharedItems.vue
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
- src/constants.js
- src/store/conversationSharedItemsStore.js
- src/store/messagesStore.js
> Add item shares from chat messages directly to the store

- .drone.jsonnet
- .drone.yml
- .github/workflows/phpunit.yml
- .github/workflows/psalm.yml
> Update stable24 target versions

- appinfo/info.xml
- package.json
- tests/integration/spreedcheats/appinfo/info.xml
> Update version on master

- docs/chat.md
- lib/Controller/ChatController.php
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/store/messagesStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/reaction/react.feature
> [stable24] Move message.reactions.self to message.reactionsSelf to not merge different data structures

- lib/Chat/Notifier.php
> Use actor and time information from the reaction not the message author

- CHANGELOG.md
- Move message.reactions.self to message.reactionsSelf to not merge different data structures [#7182](https://github.com/nextcloud/spreed/pull/7182)
- Use actor and time information from the reaction not the message author [#7190](https://github.com/nextcloud/spreed/pull/7190)
- Fix migration of attachment types for media [#7196](https://github.com/nextcloud/spreed/pull/7196)
- Open chat tab by default in sidebar while in a call [#7201](https://github.com/nextcloud/spreed/pull/7201)
- Fix access to undefined key [#7195](https://github.com/nextcloud/spreed/pull/7195)
- Only set header when the value changed and the status is not 304 [#7200](https://github.com/nextcloud/spreed/pull/7200)
- Media tab showing all shared items of the conversation
> Add changelog for 14.0.0-rc.3

- lib/Migration/Version14000Date20220330141647.php
Error from Sermo:
```
Exception: Database error when running migration 14000Date20220330141647 for app spreed
An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = bigint
LINE 1: ...LEFT JOIN "oc_filecache" "f" ON "s"."item_source" = "f"."fil...
^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
> Fix upgrade with Postgres and Oracle

- lib/Controller/ReactionController.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/store/guestNameStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/reaction/react.feature
> Fix reactions endpoints not accessible by guests

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Saw multiple request for the same summary being triggered when hovering emojis in the company call and all requests made the same response and where triggered basically in the same millisecond
> Only request reactions once

- src/__mocks__/attachmediastream.js
- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/Video.spec.js
- src/components/CallView/shared/Video.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/utils/signaling.js
- src/utils/webrtc/RemoteVideoBlocker.js
- src/utils/webrtc/RemoteVideoBlocker.spec.js
- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
Fixes #5388
Requires https://github.com/strukturag/nextcloud-spreed-signaling/pull/191
If a received video is explicitly disabled by the user, or if the remote participant is not visible, the received video is not needed. Until now the video was simply not rendered, but with this pull request the received video is disconnected/blocked, so it is not even transmitted nor decoded.
Note that, for now, this works only when the HPB is used. When the HPB is not used the renegotiation would need to be implemented by all clients, so something for the future.
If the external signaling server does not support the new `update-sdp` feature the video will not be disconnected when not needed either. If `update-sdp` is not supported then requesting a new offer would close the previous connection and …
> Disconnect received videos when not needed

- CHANGELOG.md
- Add a modal to show more shared items
- Make reactions work for guests and handle guests without name in the summary [7217](https://github.com/nextcloud/spreed/pull/7217)
- Add a link to notification sound settings from talk settings [7224](https://github.com/nextcloud/spreed/pull/7224)
- Fix migration with Postgres and Oracle [7211](https://github.com/nextcloud/spreed/pull/7211)
- Add programmatic output options to talk:active-calls command [7227](https://github.com/nextcloud/spreed/pull/7227)
- Fix media tab and reactions summary in read-only rooms [7236](https://github.com/nextcloud/spreed/pull/7236)
> Add changelog for 14.0.0-rc.4

- src/utils/webrtc/simplewebrtc/peer.js
The `mid` parameter of a transceiver matches its kind only for HPB subscriber peers. For other peers the kind can be got from the receiver track, even if the transceiver is inactive or the remote sender never had a track.
The bug does not seem to appear with the current code flows, but it will, for example, with renegotiations without the HPB.
> Fix setting sender kind from transceiver kind

- lib/AppInfo/Application.php
- lib/Maps/MapsPluginLoader.php
- src/maps.js
- webpack.js
It's done exactly like for Deck in #5110.
This can be tested with the `enh/vue-rewrite` branch of maps (just build with `make`).
The actions are added as buttons to the left click popup and as items in the right click menu.
Changes in Maps: https://github.com/nextcloud/maps/commit/697931d62f2c2d4777e22ceab4ba9934964a0d80
> Register 'share location' action in Maps app

- CHANGELOG.md
- Reactions for chat messages
- Media tab in the sidebar to show all the shared items
- Implement `OCP\Talk\IBroker` to allow apps to create conversations
- Sharing a browser tab in Chrome-based browsers can now also share the audio of that tab
- Messages of shared objects and files can now be deleted (shares will be removed, files persist)
- Actions like calling and chatting in big rooms are now much smoother
- Compatibility with Nextcloud 24
> Add changelog of 14.0.0

- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
Follow up to #6862
Since https://github.com/nextcloud/spreed/commit/48a74da64eac1a593116694f8c6ca299058f6304 offers are requested again and again in an endless loop for the peer of the SIP bridge. If [the block that requests an offer when a negotiation is needed for a subscriber](https://github.com/nextcloud/spreed/blob/48a74da64eac1a593116694f8c6ca299058f6304/src/utils/webrtc/webrtc.js#L935-L968) is moved into [the if condition that checks that the ICE connection state is not `new` nor `checking`](https://github.com/nextcloud/spreed/blob/48a74da64eac1a593116694f8c6ca299058f6304/src/utils/webrtc/webrtc.js#L970-L973) then only the original offer is requested and that is it.
My guess is that this is caused by the lack of data channels in the SIP bridge (but as mentioned it is just a guess, …
> Fix endless offer requests with the SIP bridge

- appinfo/routes/routesRoomController.php
- docs/capabilities.md
- docs/constants.md
- docs/conversation.md
- lib/Capabilities.php
- lib/Controller/RoomController.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Webinary.php
- src/components/ConversationSettings/SipSettings.vue
- src/constants.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-2/sip-dialin.feature
- tests/php/CapabilitiesTest.php
Fix #4957 
When `sipEnabled` on the getRoom request is set to:
* `0` SIP is disabled
* `1` a user pin is required (current)
* `2` no pin is required, just the conversation token
> Allow to enable SIP without individual pin requirement

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
https://user-images.githubusercontent.com/26852655/166658495-d4691110-44ef-4133-89c7-ee29d2721885.mov
> Fix loading icon position in shared items tab

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fix #7319 
1. Open two tabs with 2 users and send chat message `/spam 200 messages` in both
2. Close the tabs
3. Remove the div around the picker (to save you from having to react to all messages)
https://github.com/nextcloud/spreed/blob/e6e005760174417fd820aeb91180b9931635e9c8/src/components/MessagesList/MessagesGroup/Message/Message.vue#L118-L136
and
https://github.com/nextcloud/spreed/blob/e6e005760174417fd820aeb91180b9931635e9c8/src/components/MessagesList/MessagesGroup/Message/Message.vue#L147
5. Open Talk in a new tab
6. Load the chat
7. Wait until it loaded and observe 1.5GB ram being used
8. Scroll up and load the second page
9. Wait long again and see 1.5 GB more being used
10. Close the tab and see 3 GB ram being freed
11. Change to this patch
12. Remove again the change from 3. …
> Only render emoji picker on hover

- src/components/CallView/shared/VideoBottomBar.vue
Follow up to #6862
Fixes #7316
This fixes a regression introduced in 114b83dcdde32005ba25233cfe38b66d1d19823d
`remoteVideoBlocker` is set in the shared datas of all remote participants. However, `videoBottomBar` is used both for remote participants and for local screens, which do not have that attribute.
Other uses of `remoteVideoBlocker` should be safe, as they are implicitly guarded by checking `!isScreen` in the template.
> Fix trying to use "remoteVideoBlocker" with local screens

- CHANGELOG.md
- Fix memory consumption with emoji picker in conversations with a lot of chat messages with reactions  [7328](https://github.com/nextcloud/spreed/pull/7328)
- Fix endless offer loop with SIP participants  [7288](https://github.com/nextcloud/spreed/pull/7288)
- Fix room selector in deck and maps integration  [7290](https://github.com/nextcloud/spreed/pull/7290)  [7294](https://github.com/nextcloud/spreed/pull/7294)
- Fix transceiver kind for participants without the HPB  [7263](https://github.com/nextcloud/spreed/pull/7263)
- Fix error on console when initiating a screenshare  [7330](https://github.com/nextcloud/spreed/pull/7330)
- Add missing translations of 24 branch
> Changelog 14.0.1

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
1. Add a group to a conversation
2. Open the options menu
3. See permissions things which do not have an effect 😕
> Only show permission options for real users

- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Middleware/CanUseTalkMiddleware.php
- lib/Participant.php
- lib/Room.php
- lib/TInitialState.php
- src/components/AdminSettings/AllowedGroups.vue
- src/components/TopBar/CallButton.vue
- tests/php/CapabilitiesTest.php
> Allow to disable calling functionality

- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Controller/ChatController.php
- lib/Events/ChatParticipantEvent.php
- lib/Flow/Operation.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/notifications.feature
- tests/php/CapabilitiesTest.php
- tests/php/Chat/ChatManagerTest.php
- tests/php/Chat/NotifierTest.php
> Add an option for "Silent send" to the API

- lib/Service/RoomService.php
- tests/php/Service/RoomServiceTest.php
Forgotten step from https://github.com/nextcloud/spreed/commit/383ca5fd4c0fa9ddfd0f1c023b9b25ec1f67727e
Noticed while writing integration tests for https://github.com/nextcloud/spreed/pull/7306
> Cache display name of owner as well

- lib/Signaling/Listener.php
Before all sessions of a user where seen as changed, instead of
only the one session that actually was changed.
It is a regression from introducing multi-session support I assume.
It's what lead to the issue @danxuliu created while testing and producing #7367
All his sessions where with the same user so he ended up having 50+50 entries in the request, while it would be 1+99 as a limit otherwise.
So we still need to fix the issue, but at least it's not breaking at 50 participants but 99 now.
> Only declare the actual changed session of a user as changed

- src/components/TopBar/CallButton.vue
Replace old icon classes with the fitting material design icon to have it visible with server/talk master.
Small bit for https://github.com/nextcloud/spreed/issues/7373
Found when looking into typescript stuff with @marcoambrosini
> Use material icons everywhere in CallButton

- src/components/AdminSettings/MatterbridgeIntegration.vue
Change of the name of the Nextcloud store.
Comment: https://github.com/nextcloud/spreed/pull/7387#discussion_r875572208.
> l10n: Changing name of store

- CHANGELOG.md
- Add "Others" section to shared items tab to list unknown items  [#7350](https://github.com/nextcloud/spreed/pull/7350)
- Only declare changed sessions as such instead of all sessions of that participant  [#7382](https://github.com/nextcloud/spreed/pull/7382)
- Ensure display name of conversation owner is stored correctly  [#7376](https://github.com/nextcloud/spreed/pull/7376)
- Don't show promotion options for circles and groups  [#7404](https://github.com/nextcloud/spreed/pull/7404)
- Don't show permissions options for circles and groups  [#7360](https://github.com/nextcloud/spreed/pull/7360)
- Don't show reactions option for command messages  [#7345](https://github.com/nextcloud/spreed/pull/7345)
- Fix forwarding replies  [#7343](https://github.com/nextcloud/spreed/pull/7343)
- Ensure …
> Add changelog for 12.2.6, 13.0.6 and 14.0.2

- lib/Chat/Parser/SystemMessage.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/command/user-remove.feature
This can happen if a user gets deleted from a one-to-one conversation
```
[PHP] Error: Error: Invalid argument supplied for foreach() at /var/www/html/apps/spreed/lib/Chat/Parser/SystemMessage.php#720 at <<closure>>
0. /var/www/html/apps/spreed/lib/Chat/Parser/SystemMessage.php line 720
OC\Log\ErrorHandler::onError()
1. /var/www/html/apps/spreed/lib/Chat/Parser/SystemMessage.php line 169
OCA\Talk\Chat\Parser\SystemMessage->parseMissedCall()
2. /var/www/html/apps/spreed/lib/Chat/Parser/Listener.php line 74
OCA\Talk\Chat\Parser\SystemMessage->parseMessage()
3. /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
OCA\Talk\Chat\Parser\Listener::OCA\Talk\Chat\Parser\{closure}("*** sensitive parameters replaced ***")
4. …
```
> Fix "Invalid argument supplied for foreach() at SystemMessage.php#720"

- src/components/RightSidebar/SharedItems/SharedItems.vue
```
ERROR in src/components/RightSidebar/SharedItems/SharedItems.vue
140:3   ✖  Unexpected empty line before declaration  declaration-empty-line-before
145:4   ✖  Expected indentation of 4 tabs            indentation
145:13  ✖  Expected single quotes                    string-quotes
146:3   ✖  Expected indentation of 3 tabs            indentation
```
> Fix stylelint

- tests/integration/features/chat/notifications.feature
> Add integration tests for reaction notifications

- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/SignalingController.php
- tests/php/CapabilitiesTest.php
- tests/php/Controller/SignalingControllerTest.php
Default enabled with 200 sessions per request:
```
occ config:app:set spreed "session-ping-limit" --value="200"
```
Fix #7335
> Allow the HPB to group session pinging across rooms

- docs/call.md
- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/CallController.php
- lib/Events/SilentModifyParticipantEvent.php
- lib/Notification/Listener.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/notifications.feature
- tests/php/CapabilitiesTest.php
> Support "Silent call" on API

- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
The failure is occurring due to when there is no token, it cannot find the participants.
Created validation for it to dispatch only when there is a token
Fix #7460
> Fixed crash when saving status without conversation selected

- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Notification/Notifier.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
- tests/integration/run.sh
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Federation/FederationTest.php
- tests/php/Notification/NotifierTest.php
> Test remote invite notifications and try to send the accept/decline on invites

- appinfo/info.xml
- appinfo/routes.php
- appinfo/routes/routesPollController.php
- docs/constants.md
- docs/poll.md
- lib/Chat/ChatManager.php
- lib/Chat/Parser/SystemMessage.php
- lib/Controller/PollController.php
- lib/GuestManager.php
- lib/Listener/UserDisplayNameListener.php
- lib/Migration/Version15000Date20220503121308.php
- lib/Model/Poll.php
- lib/Model/PollMapper.php
- lib/Model/Vote.php
- lib/Model/VoteMapper.php
- lib/Service/PollService.php
- mkdocs.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/poll.feature
- tests/integration/spreedcheats/lib/Controller/ApiController.php
- tests/php/Chat/ChatManagerTest.php
> 📊 Simple polls API

- Makefile
- composer.json
- composer.lock
- lib/AppInfo/Application.php
For https://github.com/nextcloud/spreed/issues/7336
> Require firebase JWT lib

- lib/Capabilities.php
- tests/php/CapabilitiesTest.php
To make troubleshooting problems with Talk iOS easier I've submitted a PR which adds some troubleshooting infos to talk-ios, see https://github.com/nextcloud/talk-ios/pull/829
For this it would be really helpful to also show the version of the server version, but currently this version is not exposed. This PR adds the version as part of the capabilities.
> Add app version to capabilities

- docs/Talkbuchet-cli.py
- docs/Talkbuchet-run.sh
- docs/Talkbuchet.js
Talkbuchet is a JavaScript script meant to be loaded and run in a browser. However, until now that required manually copying and pasting the script in a browser console. This pull request adds a Python script that uses Selenium to launch a new browser, load Talkbuchet in it and control it through the Python script.
The CLI requires Selenium and some Python packages to be available in the system, so to simplify using it a helper Bash script is provided to run Talkbuchet CLI in a Docker container with all the needed dependencies.
In the end this pull request ended growing much much more than initially planned. A virtual participant mode was also added to Talkbuchet in addition to the main siege mode; while the siege mode can be used for load tests of the HPB server the virtual participant …
> Add CLI to run Talkbuchet

- docs/conversation.md
- lib/Command/Room/TRoomCommand.php
- lib/Controller/RoomController.php
- lib/Room.php
- lib/Service/RoomService.php
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/LeftSidebar/NewGroupConversation/PasswordProtect/PasswordProtect.vue
- src/services/conversationsService.js
- tests/php/Signaling/BackendNotifierTest.php
> Implement password policy checker

- lib/Command/Turn/Add.php
- lib/Command/Turn/Delete.php
- tests/php/Command/Turn/AddTest.php
- tests/php/Command/Turn/DeleteTest.php
Although it was possible to add TURN servers with OCC commands they had no scheme set, so in practice they always used "turn". If a different scheme had to be set that had to be done afterwards from the UI.
On the other hand, as no scheme could be set when deleting a TURN server all TURN servers matching the server and protocols were deleted regardless of their scheme.
Not sure if it is worth a backport or not, so feel free to call backportbot.
> Add schemes to turn OCC commands

- docs/system-requirements.md
Since https://github.com/nextcloud/talk-ios/pull/736 talk-ios targets iOS 12 as minimum iOS version.
> Update iOS requirements

- src/utils/webrtc/simplewebrtc/peer.js
- src/utils/webrtc/webrtc.js
This pull request adjusts the logs during calls to be more useful, specially when exported to a text file to be analysed later.
- Start a call
- Join the call with another speaking participant
No `Simulcast stream not changed` messages are printed
`Simulcast stream not changed` messages are shown when the other participant starts and stops speaking (and in large calls those messages flood the logs)
- Start a call
- Join the call with other two participants
- Export the browser console of the original participant to a text file
- Try to find out which call event belongs to which peer
The messages can be differentiated from the peer id
:shrug:
> Adjust logs during calls

- CHANGELOG.md
- Add brute force protection for conversation tokens and passwords  [#7535](https://github.com/nextcloud/spreed/pull/7535)
- Allow the HPB to group session pinging across multiple conversations  [#7444](https://github.com/nextcloud/spreed/pull/7444)
- Add a capability for unified search to enable the feature on the clients  [#7448](https://github.com/nextcloud/spreed/pull/7448)
- Fix backend URL in request to HPB from command line  [#7440](https://github.com/nextcloud/spreed/pull/7440)
- Fix error when setting user status while not being in any conversation  [#7466](https://github.com/nextcloud/spreed/pull/7466)
- Add brute force protection for conversation tokens and passwords  [#7536](https://github.com/nextcloud/spreed/pull/7536)
- Add a capability for unified search to enable the …
> Add changelog for 12.2.7, 13.0.7 and 14.0.3

- lib/Search/ConversationSearch.php
- lib/Search/MessageSearch.php
And since it's better for iOS to be bigger,
we also bump the Message result icon size
so it looks sharp on high DPI devices
---
Tested with Android and web and it looks normal.
The 128px avatar returned a 512 already since 24
> Fix avatar size to be a legal value

- src/components/AvatarWrapper/AvatarWrapper.vue
> Error: Attribute menu-container not allowed on element [div](https://html.spec.whatwg.org/multipage/#the-div-element) at this point.
Triggered from https://github.com/nextcloud/spreed/blob/3d8ad1ca8cf417385c1677005ddb87757f971237/src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue#L46
> Correctly forward avatar container

- src/components/ConversationSettings/ConversationPermissionsSettings.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/DeviceChecker/DeviceChecker.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Ref https://github.com/nextcloud/nextcloud-vue/pull/2833
> Fix HTML validation of material design icons

- src/components/TopBar/TopBar.vue
> Error: Attribute menu-align not allowed on element [div](https://html.spec.whatwg.org/multipage/#the-div-element) at this point.
> Remove unknown attribute menu-align

- docs/chat.md
- docs/poll.md
- lib/Chat/Parser/SystemMessage.php
- lib/Service/PollService.php
* Question is limited to 32k chars (not multibyte save, so an emoji is 3-4 chars)
* Json encoded options array is limited to 60k chars (not multibyte save, so an emoji is 3-4 chars)
* Options on creation are now validated to be strings
* Options array on creating needs to be at least 2 strings long
* Options on voting are now validated to be integers
* System messages `poll_voted` do not contain the actor anymore to be okay with the hidden result mode
* Update documentation according to https://github.com/nextcloud/spreed/pull/7512#pullrequestreview-1038633737
> Fix issues mentioned in the polls review

- src/PublicShareAuthRequestPasswordButton.vue
- src/mainPublicShareAuthSidebar.js
Fix #7628 
Before | After
---|---
Also fixes keyboard handling of the Talk button
> Fix video verification layout

- lib/Status/Listener.php
Fix https://github.com/nextcloud/server/issues/33314
> Keep DND and Invisible when automatically setting status to "In a call"

- lib/Share/RoomShareProvider.php
A new `$shallow` argument was introduced to `IShareProvider::getSharesInFolder` in NC25 by https://github.com/nextcloud/server/pull/31728.
This PR adds this new argument and the necessary changes to make it work based on this example https://github.com/nextcloud/server/pull/31728/files#diff-dee1351696d7eae959761edf66c8e5a9052e28be73319733d857a9ab2d9fc967=
Both PRs will have failing CI as long as the other one is not merged. I am unsure which PR to merge first to limit the failing CI on both sides.
> Add `$shallow` arg to `RoomShareProvider::getSharesInFolder`

- src/components/AvatarWrapper/AvatarWrapper.vue
Followup to #7598 
I mixed up container (string) and boundaries-element (object)
https://github.com/nextcloud/nextcloud-vue/blame/master/src/components/Actions/Actions.vue#L338-L341
Currently there is a lot of error spam when participants are shown
> Fix forwarding the menu-container for avatars

- src/App.vue
This is an attempt to fix the problem that multiple links are
suggested by the browser when searching for a room by the name.
The assumption is that while the URL is being changed the page
title is recorded but we currently change the title to the new
name already.
Fix #6211
> Change the page title only after the route changed

- lib/Controller/PageController.php
- lib/Controller/RoomController.php
- lib/Middleware/InjectionMiddleware.php
- psalm.xml
> Use public throttler

- src/App.vue
the next() function is not available in the afterEach router
guard
https://router.vuejs.org/guide/advaiced/navigation-guards.html#global-after-hooks
> Remove next function call

- src/components/CallView/shared/LocalMediaControls.vue
Before | After
---|---
Also note the off-centered screenshare icon | all buttons have the same distance and icons are correctly centered
> Move call buttons to vue buttons

- .github/workflows/phpunit.yml
E.g. https://github.com/nextcloud/spreed/pull/7682 didn't run it (kind of fine, but if the php dependency we use in no-dev is updated they should run)
> Run PHPUnit on composer change

- src/components/ConversationSettings/LinkShareSettings.vue
Split from https://github.com/nextcloud/spreed/pull/7642
> Move conversation settings to vue components

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
If the MessageButtonsBar belongs to the last read message, we need
to raise it to compensate for the shift in position brought by the
last read marker that's added to the message component.
fixes #7219 
> Fix messagebuttonsbar position for last read messages

- src/components/AdminSettings/WebServerSetupChecks.vue
Added success and error colors to the icons
Before | After
---|---
> Move WebServer setup check to Vue button

- src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
Before | After
---|---
While the padding left/right looked better on the old button it didn't really respect the clickable area and not indicate it.
I'm fine if we want to cut it off again but would like the 44px clickable area
> Move "Remove participant" button to Vue

- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
Spot | Before | After
---|---|---
Protocol button right of enable checkbox | ![Bildschirmfoto vom 2022-08-10 11-47-47](https://user-images.githubusercontent.com/213943/183871454-f0420a91-87e1-42c5-a137-fa327af9af33.png) | ![Bildschirmfoto vom 2022-08-10 11-46-25](https://user-images.githubusercontent.com/213943/183871447-ecd3bb0a-6d95-494b-afe3-cedf5de0afc2.png)
Plus icon left of Input | ![Bildschirmfoto vom 2022-08-10 11-47-57](https://user-images.githubusercontent.com/213943/183871459-29bd80b5-a10a-429f-a5c5-ad9e9d54d1c6.png) | ![Bildschirmfoto vom 2022-08-10 11-46-19](https://user-images.githubusercontent.com/213943/183871452-dae003ee-70cf-4565-abb3-05fda99d7b65.png)
> Move matterbridge buttons to Vue

- src/components/LeftSidebar/LeftSidebar.vue
Fix #7103 
Or is this not needed anymore as the AppNavigation already has `Conversation list` as aria label and there is only the search box in between? @jancborchardt any clue?
> Add headline to conversation list for screenreaders

- src/utils/media/pipeline/BlackVideoEnforcer.js
- src/utils/media/pipeline/BlackVideoEnforcer.spec.js
- src/utils/webrtc/simplewebrtc/localmedia.js
- src/utils/webrtc/simplewebrtc/peer.js
The stream sent to other peers is now separate from the one locally shown. This makes possible to adjust them independently to work around specific browser behaviours, for example, to ensure that zero-information-content video tracks will be always received by other participants when needed.
> Reduce sent information with disabled videos

- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/StunServers.vue
- src/components/AdminSettings/TurnServers.vue
- src/views/MainView.vue
The `fade` class for transitions is defined in the `variables` asset, so it needs to be imported wherever the transition is used.
Note that this causes the asset to be imported several times when two or more different components that import it are used in the same parent component, although that should not be a problem (and hopefully the bundler is smart enough to import it just once, but I have not checked).
This should not be related to https://github.com/nextcloud/spreed/pull/7704. I have not checked if it happens in previous versions, though, as it is not a big issue.
> Import missing variables for fade transition

- src/components/NewMessageForm/NewMessageForm.vue
Follow up to #7392
`handleSubmit` was called from an event, so the `options` were the event itself; this did not fail, as the options were defined, but they were useless anyway. Now the options are explicitly set.
> Fix message options when submitting from the advanced input

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
- src/store/messagesStore.js
```
Error while forwarding message TypeError: options is undefined
_callee3$ messagesService.js:144
tryCatch runtime.js:63
invoke runtime.js:294
defineIteratorMethods runtime.js:119
asyncGeneratorStep messagesService.js:1
_next messagesService.js:3
_asyncToGenerator messagesService.js:3
_asyncToGenerator messagesService.js:3
postNewMessage messagesService.js:156
_callee7$ messagesStore.js:1220
tryCatch runtime.js:63
invoke runtime.js:294
```
> Fix message forwarding

- css/publicshare.css
- src/PublicShareSidebarTrigger.vue
- src/mainPublicShareSidebar.js
Follow up to #7576
Fixes #7578
Since the removal of SCSS files the `menu-people` icon can no longer be used directly with a CSS class. However, it is available as a Vue component; although it would be possible to directly render the Vue component for the icon* inside the button element the whole button is moved to Vue instead, as the other approach requires more fighting with the styles.
*For reference in case it is ever needed:
```
const talkSidebarTriggerIconVm = new Vue({
// MenuPeople is a functional component, so it needs to be explicitly
// rendered rather than just spread (...MenuPeople) in the constructor
// of the Vue instance.
render: h => h(MenuPeople, {
props: {
fillColor: 'var(--color-primary-text)',
size: 20,
decorative: true,
},
}),
}) …
```
> Fix missing Talk sidebar trigger in public share pages

- CHANGELOG.md
- Extend search result attributes for better handling in mobile clients  [#7588](https://github.com/nextcloud/spreed/pull/7588)  [#7587](https://github.com/nextcloud/spreed/pull/7587)
- Location shares not visible in chat anymore (only in the sidebar tab)  [#7550](https://github.com/nextcloud/spreed/pull/7550)
- Reduce sent information with disabled videos  [#7709](https://github.com/nextcloud/spreed/pull/7709)
- Multiple accessibility fixes  [#7599](https://github.com/nextcloud/spreed/pull/7599)  [#7654](https://github.com/nextcloud/spreed/pull/7654)  [#7553](https://github.com/nextcloud/spreed/pull/7553)  [#7570](https://github.com/nextcloud/spreed/pull/7570)
- Extend search result attributes for better handling in mobile clients  [#7590](https://github.com/nextcloud/spreed/pull/7590) …
> Add changelog for 13.0.8 and 14.0.4

- lib/Migration/Version15000Date20220503121308.php
- lib/Model/Vote.php
The problem is the entity had 0 as a default it would skip writing
it into the changeset of the query for the insert.
But the DB had a default of 1 so it would store a 1 afterwards in the db.
Having null as default on the Vote model fixes this, as then any number
is a change from the default, the mark-dirty happens and we add it to
the query.
The problem is integration tests always send integers due to the form body usage.
The `0` from the integration tests therefor hits the server as `'0'`, === does not match
and the mark dirty happens:
https://github.com/nextcloud/server/blob/1d30fb7852e61cf9a2fcd03e83fa193c6aa5c827/lib/public/AppFramework/Db/Entity.php#L106-L109
Therefor the option was always specified from integration tests and it set a 0.
> Fix voting for option 0

- src/components/ConversationSettings/LinkShareSettings.vue
```
[Vue warn]: Property or method "submit" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
found in
---> <LinkShareSettings> at src/components/ConversationSettings/LinkShareSettings.vue
<AppSettingsSection>
<Modal>
<AppSettingsDialog>
<ConversationSettingsDialog> at src/components/ConversationSettings/ConversationSettingsDialog.vue
<Content>
<App> at src/App.vue
<Root>
```
> Fix literal value passed as reactive property

- CHANGELOG.md
- Makefile
- appinfo/info.xml
- 🛂 Chat permission
- 📊 Simple polls
- 📴 "Silent call" for group/public calls
- 🔔 Allow to re-notify a participant for a call
- 🔕 "Silent send" for chat messages
- 🔍 Search for messages in mobile apps
- 📵 Allow to disable calling functionality
- 📞 Allow SIP dial-in without individual user PINs
> Prerelease 15.0.0 beta.1

- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
```
[Vue warn]: Invalid prop: type check failed for prop "size". Expected Number with value 16, got String with value "16".
found in
---> <CloseIcon> at node_modules/vue-material-design-icons/Close.vue
<ButtonVue>
<ContactSelectionBubble> at src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
<TransitionGroup>
<SetContacts> at src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
<Modal>
<NewGroupConversation> at src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
<AppNavigation>
<LeftSidebar> at src/components/LeftSidebar/LeftSidebar.vue
<Content>
<App> at src/App.vue
<Root>
```
**I have not tested the Matterbridge icon**, but I guess it has the same problem.
> Fix icon size type

- src/components/LeftSidebar/ConversationsList/Conversation.vue
[The default aria label for actions is _Actions_](https://github.com/nextcloud/nextcloud-vue/blob/9d29c3cf8327e47bf921dfa5081ae578611699a8/src/components/Actions/Actions.vue#L461-L467), but the default value is overriden to an empty string [when used in a list item](https://github.com/nextcloud/nextcloud-vue/blob/e499b4e9b018f8ef6a5d2a05b3d02a6670e5ce4b/src/components/ListItem/ListItem.vue#L362-L368), so it needs to be explicitly set.
Fixes the console warning `You need to fill either the text or the ariaLabel props in the button component.` referred to the actions buttons. I have done it in Talk rather than in Nextcloud vue as having an empty aria label for list items seems to be an explicit decision, probably because the text would need to change depending on the list item context …
> Add missing aria label to buttons to show conversation actions

- css/icons.css
- lib/Dashboard/TalkWidget.php
Before | After
---|---
The old icon is defined in server which toggles the icon based on the a11y theming, but the dashboard additionally has a `filter: var(--background-invert-if-dark)` so the icon was dark again.
> Fix the talk dashboard icon on dark mode

- src/PublicShareSidebar.vue
- In a private window, open the link
- Join the conversation
- Start a call
The local video controls can be used to enable/disable audio and video
The local video controls are not shown, so audio and video can not be enabled/disabled
> Fix missing local media controls in public share sidebar

- src/components/CallView/CallView.vue
Follow up to #3563
When the call view is shown in the sidebar there is no button to share the screen. However, other participants can nevertheless open the call from the main Talk UI and share their screen there, so remote screen shares should be shown even if local ones can not be started.
**Before:**
**After:**
> Fix remote screen shares not shown in sidebar

- src/components/DeviceChecker/DeviceChecker.vue
Although the directive was missing the tooltips were still shown in the normal Talk UI; the tooltips were missing only when Talk was embedded in other apps, like the Files app.
- Share a file
- Open the _Chat_ tab for that file
- Join the conversation
- Start a call
The tooltips are shown on the buttons to enable/disable audio, video and background blur
The tooltips are not shown on the buttons to enable/disable audio, video and background blur; an error is shown in the console about a missing tooltip directive
> Fix missing tooltip directive in DeviceChecker

- composer.lock
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Manager.php
- tests/php/Chat/Parser/SystemMessageTest.php
Reduce query by 1/3 when fetching the list of rooms on the production
instance.
TODO:
> Use DisplayNameCache

- lib/Chat/Parser/SystemMessage.php
- tests/php/Chat/Parser/SystemMessageTest.php
Removes 2 queries for each file that is shared from another user
Meme channel:
Before | After
---|---
142 | 86
> Delay getting the node until we know that we use the data

- docs/chat.md
- lib/Chat/Parser/SystemMessage.php
- lib/Model/Message.php
> Expose message expiration for chat message objects

- lib/Chat/Parser/SystemMessage.php
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/test-setup.js
- tests/php/Chat/Parser/SystemMessageTest.php
> Populate etag and permissions to active the image editor

- lib/Model/Message.php
> Ensure that the reactions array is always a JSON object

- lib/Activity/Provider/Base.php
- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Chat/Notifier.php
- lib/Chat/Parser/UserMention.php
- lib/Controller/CallController.php
- lib/Controller/RoomController.php
- lib/Manager.php
- lib/Notification/Notifier.php
- lib/Service/ParticipantService.php
- tests/php/Activity/Provider/BaseTest.php
- tests/php/Chat/AutoComplete/SearchPluginTest.php
- tests/php/Chat/Parser/UserMentionTest.php
- tests/php/Notification/NotifierTest.php
> Use user displayname cache

- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
- src/store/sharedItemsStore.js
> Hide deprecated projects in shared items tab by default

- lib/Controller/ChatController.php
- lib/Share/RoomShareProvider.php
- tests/php/Controller/ChatControllerTest.php
When diagnosing [slow loading of chat messages](https://github.com/nextcloud/talk-android/issues/2228) in the Talk Android app, I have noticed that information about files (usually images) shared in the chat is read using a separate query for each file.
This is an initial proof-of-concept that reduces it to a single query.
Instead of executing a separate query in **RoomShareProvider::getShareById** for each share, we gather all share ids and execute a single query in a new method **RoomShareProvider::getSharesByIds**.
While performance improvements in the development environment are difficult to notice, on my family "production" environment this gives around 15% improvement of the **ChatController::receiveMessages** execution time (**280 ms** down from **330 ms**).
This code is certainly …
> Reduce number of queries required to read shares

- lib/Chat/Notifier.php
- lib/Notification/Notifier.php
- lib/Service/ParticipantService.php
- tests/integration/features/callapi/notifications.feature
- tests/integration/features/chat/notifications.feature
> Fix notifications when lobby is active

- src/components/ConversationSettings/ExpirationSettings.vue
> l10n: Change style of sentence

- src/utils/signaling.js
- src/utils/webrtc/webrtc.js
When a call is left a request to leave the call is sent to the server and then the UI changes to the _not-in-a-call_ state. Even if the request sent to the server fails (which sometimes happens with flaky connections) [the layout is changed](https://github.com/nextcloud/spreed/blob/a22b31b3cb94b57ea1b65a489d9d900e91852957/src/store/participantsStore.js#L415-L424) ([failures are ignored in the service](https://github.com/nextcloud/spreed/blob/a22b31b3cb94b57ea1b65a489d9d900e91852957/src/services/callsService.js#L61-L67)). However, if the request sent to the server fails the call was not left from the WebRTC side, because the `leaveCall` event was triggered only on success. Due to this the UI implied that the call was left, but the RTCPeerConnections were all still active.
This pull request …
> Fix inconsistent state when leaving a call fails

- lib/Chat/Notifier.php
- lib/Notification/Notifier.php
- lib/Service/ParticipantService.php
- tests/integration/features/callapi/notifications.feature
- tests/integration/features/chat/notifications.feature
Backport of #7788 
Auto backport failed because the callapi/notifications.feature file was only introduced with silent call which is not in 24
> [stable24] Fix notifications when lobby is active

- lib/Controller/RoomController.php
- lib/Events/DuplicatedParticipantEvent.php
- lib/Service/ParticipantService.php
- lib/Signaling/Listener.php
- tests/php/Signaling/BackendNotifierTest.php
Fixes a regression introduced in #6707 (specifically, in 802d1d2f3e4af3e1a590fca7b6dc24c4115f30a4)
When the HPB is not used and the same conversation is joined in another tab [a conflict response is returned by the internal signaling server](https://github.com/nextcloud/spreed/blob/ba7394b51e4161ed803b0ec01f1057941f682410/lib/Controller/SignalingController.php#L367)* in the first tab, which causes [a `duplicate-session-detected` event to be triggered](https://github.com/nextcloud/spreed/blob/9e9197cc56fd8374c4916ba1fd029721cd1a5486/src/utils/signaling.js#L513-L518) and this in turn [causes a redirection to the `duplicate-session` page](https://github.com/nextcloud/spreed/blob/47e98d86d617925253f69f4a5a7ad67d63fd4d79/src/mixins/sessionIssueHandler.js#L58-L60).
*If a long polling request …
> Fix leaving room in one session causing call to be partially left in another session

- lib/Chat/Parser/SystemMessage.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
- src/services/pollService.js
- src/store/conversationsStore.js
- src/store/messagesStore.js
- src/store/pollStore.js
- tests/integration/features/bootstrap/FeatureContext.php
> Polls cleanup

- lib/Chat/Parser/SystemMessage.php
- tests/php/Chat/Parser/SystemMessageTest.php
> Fix email invite SIP Dial-In system message users

- src/utils/webrtc/simplewebrtc/peer.js
Follow up to #6862 
Requires https://github.com/strukturag/nextcloud-spreed-signaling/pull/239 (v0.5.0)
Originally the HPB required a renegotiation to block the received videos. However, besides the standard WebRTC way, Janus also supports directly toggling on and off the video without any renegotiation. This is now exposed by the signaling server through the `selectStream` message, so the video is now blocked using that approach instead.
The previous code to block the video using a renegotiation is still kept, though, as it could be used without HPB once all the clients support renegotiations.
Pending:
In the test below, in Firefox it can be verified that the video is stopped and resumed again opening `about:webrtc` and checking the video stats in the receiver connection; for easier …
> Disconnect received videos by toggling the video directly in Janus

- package-lock.json
- package.json
- src/App.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
- src/components/RightSidebar/RightSidebar.vue
Initial | WIth some fixes
---|---
> ✨ Update to @nextcloud/vue 7

- package-lock.json
Fixes the `ReferenceError: exports is not defined` error introduced in [3.0.1](https://github.com/nextcloud/spreed/pull/7854).
> Bump @nextcloud/event-bus from 3.0.1 to 3.0.2

- css/publicshareauth.css
Fixes #7852
The content now has a fixed position to be always centered in the page. However, in order to add the Talk sidebar the content in the public share authentication page needs to be "pushed" to the left when the sidebar is added, so the content position needs to have a relative position instead (which also keeps the same appearance of the fixed position when the Talk sidebar is not shown yet).
> Adjust public share authentication page to layout changes in NC25

- src/components/TopBar/TopBar.vue
Using the new syntax for slots
fixes #7872
> Fix visibility of sidebar toggle

- css/publicshare.css
> Adjust public share page to layout changes in Nextcloud 25

- css/icons.css
There was a generic filter in the past, but it was removed with https://github.com/nextcloud/server/commit/1d35a53991f356976d78b8053651737821502687
So now we apply the filter at our best knowledge
Fix #7878 
Before | After
---|---
> Fix dashboard icon on dark mode again

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Not totally happy with the longer strings but we need to indicate whether a Poll or Option was voted.
Fix #7829
> Fix unclear translation "You voted"

- lib/Listener/UserDeletedListener.php
- lib/Service/PollService.php
- src/components/AvatarWrapper/AvatarWrapperSmall.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
- tests/integration/features/chat/poll.feature
- tests/integration/features/reaction/react.feature
Fix #7839 
Before | After
---|---
> Fix deleted users in polls

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
Fix #7826 
Fix #7546 
Patch for testing:
```diff
diff --git a/lib/Model/Message.php b/lib/Model/Message.php
index d888d0133..5e8202961 100644
--- a/lib/Model/Message.php
+++ b/lib/Model/Message.php
@@ -192,7 +192,7 @@ class Message {
'isReplyable' => $this->isReplyable(),
'referenceId' => (string) $this->getComment()->getReferenceId(),
'reactions' => $reactions,
-                       'expirationTimestamp' => $expireDate ? $expireDate->getTimestamp() : 0,
+                       'expirationTimestamp' => time() + 5, //$expireDate ? $expireDate->getTimestamp() : 0,
];
if ($this->getMessageType() === ChatManager::VERB_MESSAGE_DELETED) {
diff --git a/src/components/MessagesList/MessagesList.vue b/src/components/MessagesList/MessagesList.vue
index 0bd7b689d..293fa616c 100644
--- …
```
> Remove expired message and when there are too many from the Vue store

- src/components/CallView/CallView.vue
Fix #7879 
1. Start a group call
2. Join with a second user
3. Switch to grid view
4. Click on the other participant
5. Check your frame
6. Unfollow
7. Check the frame again
Before | After
---|---
> Fix missing bottom+right frame when following in a 2 person call

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
> Allow to "Send call notification" for owners

- CHANGELOG.md
- Fix notification sending when the user is blocked by the lobby  [#7794](https://github.com/nextcloud/spreed/pull/7794)
- Fix missing local media controls in public share sidebar  [#7758](https://github.com/nextcloud/spreed/pull/7758)
- Fix missing screenshares in sidebar  [#7760](https://github.com/nextcloud/spreed/pull/7760)
- Fix inconsistent state when leaving a call fails  [#7803](https://github.com/nextcloud/spreed/pull/7803)
- Fix notification sending when the user is blocked by the lobby  [#7796](https://github.com/nextcloud/spreed/pull/7796)
- Fix missing local media controls in public share sidebar  [#7759](https://github.com/nextcloud/spreed/pull/7759)
- Fix missing screenshares in sidebar  [#7763](https://github.com/nextcloud/spreed/pull/7763)
- Fix inconsistent state when …
> Changelog for 13.0.9 and 14.0.5

- CHANGELOG.md
- appinfo/info.xml
- Fix notification sending when the user is blocked by the lobby  [#7794](https://github.com/nextcloud/spreed/pull/7794)
- Fix missing local media controls in public share sidebar  [#7758](https://github.com/nextcloud/spreed/pull/7758)
- Fix missing screenshares in sidebar  [#7760](https://github.com/nextcloud/spreed/pull/7760)
- Fix inconsistent state when leaving a call fails  [#7803](https://github.com/nextcloud/spreed/pull/7803)
> Changelog for 14.0.5

- CHANGELOG.md
- appinfo/info.xml
- Fix notification sending when the user is blocked by the lobby  [#7796](https://github.com/nextcloud/spreed/pull/7796)
- Fix missing local media controls in public share sidebar  [#7759](https://github.com/nextcloud/spreed/pull/7759)
- Fix missing screenshares in sidebar  [#7763](https://github.com/nextcloud/spreed/pull/7763)
- Fix inconsistent state when leaving a call fails  [#7804](https://github.com/nextcloud/spreed/pull/7804)
> Changelog for 13.0.9

- CHANGELOG.md
- appinfo/info.xml
- Add related_resources UI
- Use Node 16 and NPM 8 to compile the interface
- Several dependency updates
- Unload chat messages when moving to another chat to avoid lagging on return
- Several fixes to adapt to the UI changes in Nextcloud 25
- Respect message expiration in the frontend when the user never leaves the conversation
- Fix handling of deleted users in polls
- Allow recalling the owner as a normal moderator
> Changelog for 15.0.0 beta.4

- lib/Flow/Operation.php
- src/views/FlowPostToConversation.vue
> Fix flow and chat permissions

- src/App.vue
- src/components/CallView/shared/LocalMediaControls.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/components/TopBar/TopBar.vue
> Disable keyboard shortcuts when the user opted-out

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fix #7913 
(I tried tertiary but that has no background as the hover is already on the full message, so I think those 2 are the best)
Before | After
---|---
Unclear what you selected, not enough contrast on hover, etc. | Primary = You, Secondary = Others
> Fix reaction buttons due to remove CSS variable

- lib/Controller/AEnvironmentAwareController.php
- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Model/Message.php
Fix #7952 
Check result of both curl commands before and after:
```sh
curl -k -u admin:admin \
'https://nextcloud25.local/ocs/v2.php/apps/spreed/api/v1/chat/7d85h4a9?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=201&includeLastKnown=1' \
-H 'OCS-APIRequest: true' \
-H 'Accept: application/json, text/plain, */*' \
| jq .
curl -k -u admin:admin \
'https://nextcloud25.local/ocs/v2.php/apps/spreed/api/v1/chat/7d85h4a9?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=201&includeLastKnown=1' \
-H 'OCS-APIRequest: true'
```
(Adjust domain and token and make sure the json one still returns an empty object for reactions
> Fix chat endpoints with empty reactions in XML format

- docs/poll.md
- lib/Controller/PollController.php
- src/components/NewMessageForm/NewMessageForm.vue
- tests/integration/features/chat/poll.feature
> Restrict polls from one-to-one chats

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/UploadEditor.vue
Fix #7893 
Before | After
---|---
> Fix size of upload modal

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Fix #7284 
Before | After
---|---
> Show shareWithDisplayNameUnique for users

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
```
console.error
[vuex] duplicate getter key: reactionsLoaded
915 | 			testStoreConfig.modules.messagesStore.getters.reactionsLoaded = reactionsLoadedGetter
916 |
> 917 | 			store = new Store(testStoreConfig)
| 			        ^
918 |
919 | 			const messagePropsWithReactions = Object.assign({}, messageProps)
920 | 			messagePropsWithReactions.reactions = { '❤️': 1 }
at registerGetter (node_modules/vuex/dist/vuex.common.js:878:15)
at node_modules/vuex/dist/vuex.common.js:751:5
at node_modules/vuex/dist/vuex.common.js:125:52
at Array.forEach (<anonymous>)
at forEachValue (node_modules/vuex/dist/vuex.common.js:125:20)
at Module.forEachGetter (node_modules/vuex/dist/vuex.common.js:200:5)
at installModule (node_modules/vuex/dist/vuex.common.js:749:10)
at node_modules/vuex/dist/vuex.common.js:755:5 …
```
> Fix console error '[vuex] duplicate getter key: reactionsLoaded' in jest

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
```
PASS  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
● Console
console.error
[Vue warn]: Missing required prop: "isForwarderOpen"
found in
---> <MessageButtonsBar>
<Root>
86 | 				store = new Store(testStoreConfig)
87 |
> 88 | 				const wrapper = shallowMount(MessageButtonsBar, {
| 				                ^
89 | 					localVue,
90 | 					store,
91 | 					stubs: {
at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4516:21)
at assertProp (node_modules/vue/dist/vue.runtime.common.dev.js:5034:9)
at validateProp (node_modules/vue/dist/vue.runtime.common.dev.js:4994:9)
at initProps$1 (node_modules/vue/dist/vue.runtime.common.dev.js:5285:23)
at initState (node_modules/vue/dist/vue.runtime.common.dev.js:5254:9)
at VueComponent.Vue._init …
```
> Fix console error 'Missing required prop: "isForwarderOpen"' in jest

- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/StunServer.vue
- src/components/AdminSettings/TurnServer.vue
Should make errors more obvious
Ref  #7165
> Color status icons of STUN, TURN and HPB

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
Fix #7919 
Patch for testing:
```diff
diff --git a/lib/Model/Message.php b/lib/Model/Message.php
index d888d0133..5e8202961 100644
--- a/lib/Model/Message.php
+++ b/lib/Model/Message.php
@@ -192,7 +192,7 @@ class Message {
'isReplyable' => $this->isReplyable(),
'referenceId' => (string) $this->getComment()->getReferenceId(),
'reactions' => $reactions,
-                       'expirationTimestamp' => $expireDate ? $expireDate->getTimestamp() : 0,
+                       'expirationTimestamp' => time() + 5, //$expireDate ? $expireDate->getTimestamp() : 0,
];
if ($this->getMessageType() === ChatManager::VERB_MESSAGE_DELETED) {
diff --git a/src/components/MessagesList/MessagesList.vue b/src/components/MessagesList/MessagesList.vue
index 0bd7b689d..293fa616c 100644
--- …
```
> Show empty content when all messages expired

- src/components/NewMessageForm/NewMessageForm.vue
Fix #7904 
Steps:
1. Post a message
2. Apply the following patch
```diff
diff --git a/lib/Controller/ChatController.php b/lib/Controller/ChatController.php
index 3608f5959..39b1f5935 100644
--- a/lib/Controller/ChatController.php
+++ b/lib/Controller/ChatController.php
@@ -221,6 +221,8 @@ class ChatController extends AEnvironmentAwareController {
if (!$parentMessage->isReplyable()) {
return new DataResponse([], Http::STATUS_BAD_REQUEST);
}
+
+                       return new DataResponse([], Http::STATUS_INTERNAL_SERVER_ERROR);
}
$this->participantService->ensureOneToOneRoomIsFilled($this->room);
```
4. Quote the previous message
5. Wait until the message failed
6. Click on the resend option 💥 Quote is missing
> Quote again when retrying to send a failed message

- src/components/LeftSidebar/LeftSidebar.vue
> Fix new-conversation padding

- lib/Chat/Changelog/Manager.php
> Add Talk Changelog chat messages

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Improves the placement a bit, but possibly we should have a tripped down emoji-picker for smaller screeens?
> Improve emojipicker placement

- lib/AppInfo/Application.php
- lib/Chat/ChatManager.php
- lib/Collaboration/Reference/ReferenceInvalidationListener.php
- lib/Collaboration/Reference/TalkReferenceProvider.php
- lib/Room.php
- tests/php/Chat/ChatManagerTest.php
- tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
Fix #7988
* If the user is a participant
* Title is the conversation name
* Description the conversation description
* Open conversation joinable for the user
* Title is the conversation name
* Description the conversation description
* Public link (with and without password)
* Title is the "Private conversation"
* Description is empty
To get a closer preview the user needs to be a participant (open conversation or public link are not enough, in those cases the above information is shown)
* Title is "Message of {user} in {conversation}"
* Description is the plain text chat message
Participant | Stranger
---|---
> 🏷️ /call/ reference provider

- appinfo/info.xml
- lib/Command/Monitor/Calls.php
- lib/Command/Monitor/HasActiveCalls.php
- lib/Command/Monitor/Room.php
- tests/integration/features/bootstrap/CommandLineTrait.php
- tests/integration/features/command/active-calls.feature
- tests/integration/features/command/monitor-calls.feature
- tests/integration/features/command/monitor-room.feature
- tests/psalm-baseline.xml
Fix #7451 
Fix #8014
```sh
occ  talk:active-calls -d --output json_pretty
{
"9537209724": 1
}
```
To get the count of a single conversation:
```sh
occ talk:active-calls -d --output json | jq -r '.["9537209724"]'
1
```
> Allow to count the participants per call

- src/App.vue
- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Fix https://github.com/nextcloud/spreed/issues/1937
Signed-off-by: szaimen <szaimen@e.mail.de>
<details>
<summary>For my own testing</summary>
```
docker run -it ^
-e TRUSTED_DOMAIN=192.168.178.155 ^
-e TALK_BRANCH=enh/1937/mobile ^
--name nextcloud-easy-test ^
-p 8443:443 ^
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" ^
ghcr.io/szaimen/nextcloud-easy-test:latest
```
</details>
> fix and improve mobile UX

- tests/integration/run-docker.sh
This makes possible to launch the database used in the integration tests with a set of custom commands, for example, to replicate [those used in CI](https://github.com/nextcloud/spreed/blob/73033cecfc0ee476664de47e29489bcc3b00fce2/.drone.jsonnet#L84-L87).
Besides that, the default Docker images were also updated to match [those used in CI](https://github.com/nextcloud/spreed/blob/73033cecfc0ee476664de47e29489bcc3b00fce2/.drone.jsonnet#L72-L106).
> Add "--database-custom-command" option to Docker helper script

- src/utils/signaling.js
- src/utils/webrtc/index.js
> Fix silent call

- CHANGELOG.md
- Fix call button missing on Safari for iPadOS
- Fix silent call not working from web
> Add changelog for 15.0.0-rc.4

- lib/Command/Monitor/Calls.php
The function `in` already put the parenthesis, duplicated parenthesis return wrong result with sqlite.
close #8186
> Query in sqlite returning wrong result.

- src/components/CallView/shared/EmptyCallView.vue
When starting a call in a 1on1 conversation, the message is very generic: 
So, improving that to have callee's display name, simply "Waiting for [display name] to join the call …"
> added displayName to pending call message in 1on1 calls

- lib/Dashboard/TalkWidget.php
- lib/Exceptions/NotAllowedToUseTalkException.php
Currently using a dirty way so we can backport
Fix #8232
> Hide the talk dashboard widget when the user is not allowed to use talk

- lib/Files/TemplateLoader.php
- src/PublicShareSidebar.vue
Pending:
I have not checked if there is some way to know the actual user from the `TemplateLoader`, but if not then at least an error should be shown when failing to join the conversation in the public share page (which should be shown nevertheless if there is an error independently of this issue, so maybe it would be the way to go).
- Open Talk settings
- Restrict Talk to be used only by certain group
- Log in as a user not in that group
- Open the sidebar for a file
The `Chat` tab is not shown in the sidebar
The `Chat` tab is shown in the sidebar
- Open Talk settings
- Restrict Talk to be used only by certain group
- Log in as a user not in that group
- Open the link in another tab in the same window
- Join the …
> Do not show Talk sidebar if Talk is disabled for the user

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Fix #8267 
Currently using this string because it's translated already and we want to release today.
Will make a follow up to be backported after the release to remove the "Poll results" bit as its the voting screen not the result screen?
> Show voters count on voting screen for moderators

- lib/Controller/PollController.php
The messages are not rendered either so we shouldn't push for them.
Fix #8266
> No notification for voting

- CHANGELOG.md
- Take the device pixel ratio into account when calculating minimum grid size (should see more videos now on High DPI settings like MacOS and most 4k setup)  [#8246](https://github.com/nextcloud/spreed/pull/8246)
- Show the number of casted votes to the question raiser and moderators on the voting screen  [#8273](https://github.com/nextcloud/spreed/pull/8273)
- Hide talk dashboard when user can not use the Talk app  [#8236](https://github.com/nextcloud/spreed/pull/8236)
- Hide talk sidebar integration when user can not use the Talk app  [#8240](https://github.com/nextcloud/spreed/pull/8240)
- Show other participant's name when waiting in a one-to-one call  [#8228](https://github.com/nextcloud/spreed/pull/8228)
- Take the device pixel ratio into account when calculating minimum grid size …
> Add changelog 12.2.8, 13.0.10, 14.0.6 and 15.0.1

- package-lock.json
- package.json
Reverts nextcloud/spreed#8211
Following #8214 due to the performance regression downgrading to 7.0.0 again for todays release
> Revert "[stable25] Bump @nextcloud/vue to 7.0.1"

- CHANGELOG.md
- appinfo/info.xml
> Add changelog 12.2.8

- src/components/CallView/shared/LocalMediaControls.vue
- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMenu.vue
> Reduce two menus to one

- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/WebServerSetupChecks.vue
> Make apache configuration check less error prone

- lib/Share/RoomShareProvider.php
When working on https://github.com/nextcloud/server/pull/34918, I have noticed that after applying changes proposed in that PR, incorrect permissions are returned for room shares.
This seems to be caused by the fact that the database query issued in **RoomShareProvider::getSharesInFolder** returnes two columns named `permissions` - one from the `oc_shares` table and a second one from `oc_filecache`. Which column is then used by the PHP code probably depends on the database driver used and maybe some random factors. In my case (MariaDB) the wrong column was consistently used.
In this PR I propose to change the SELECT part of the query to match other methods in the class - **getSharesByIds** and **getSharedWith**.
This change also means that the node data will be stored in the cache: …
> Fix permissions returned by getSharesInFolder

- src/components/CallView/Grid/Grid.vue
Fix #8314 
Before with 2.0 device pixel ratio | After with 2.0 device pixel ratio
---|---
> Fix bottom stripe of speaker view with high DPI

- lib/Chat/ChatManager.php
- lib/Model/PollMapper.php
- lib/Model/VoteMapper.php
- lib/Service/PollService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/poll.feature
> Remove poll data when deleting the message

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/CallTime.vue
- src/components/TopBar/TopBar.vue
- src/mixins/isInLobby.js
- src/store/participantsStore.js
> ⏺️ Recording part 1 - Add useful information to the top-bar

- appinfo/routes/routesCallController.php
- appinfo/routes/routesChatController.php
- appinfo/routes/routesCommandController.php
- appinfo/routes/routesFilesIntegrationController.php
- appinfo/routes/routesGuestController.php
- appinfo/routes/routesMatterbridgeController.php
- appinfo/routes/routesPageController.php
- appinfo/routes/routesPollController.php
- appinfo/routes/routesPublicShareAuthController.php
- appinfo/routes/routesReactionController.php
- appinfo/routes/routesRoomController.php
- appinfo/routes/routesSignalingController.php
This allows better parsing for OpenAPI specs later
Fix #8354
> Move all API version requirements to the same format

- src/components/RightSidebar/RightSidebar.vue
Since @nextcloud/vue 7.1.0-beta.0 the tabs in the right sidebar expand to the full height of its contents, which causes the sidebar to be fully scrollable, rather than scrollable only in the tab contents, which breaks the chat when shown in the sidebar.
Until a better fix is found for now the changes in the sidebar CSS from @nextcloud/vue that causes that are reverted specifically for Talk.
> Revert @nextcloud/vue changes to sidebar scrolling

- CHANGELOG.md
- Allow to disable the changelog conversation with an app config  [#8365](https://github.com/nextcloud/spreed/pull/8365)
- Improve message grouping duration to match better with UX expectations  [#8288](https://github.com/nextcloud/spreed/pull/8288)
- Update @nextcloud/vue library to 7.1.0  [#8405](https://github.com/nextcloud/spreed/pull/8405)  [#8419](https://github.com/nextcloud/spreed/pull/8419)
- Fix in_call flag on the "Join room" API response  [#8371](https://github.com/nextcloud/spreed/pull/8371)
- Fix bottom stripe of speaker view with high DPI  [#8319](https://github.com/nextcloud/spreed/pull/8319)
- Make webserver configuration check less error-prone  [#8310](https://github.com/nextcloud/spreed/pull/8310)  [#8332](https://github.com/nextcloud/spreed/pull/8332)
- Fix monitoring …
> Changelog 13.0.11, 14.0.7 and 15.0.2

- CHANGELOG.md
- appinfo/info.xml
- Allow to disable the changelog conversation with an app config  [#8366](https://github.com/nextcloud/spreed/pull/8366)
- Fix bottom stripe of speaker view with high DPI  [#8321](https://github.com/nextcloud/spreed/pull/8321)
> Release 13.0.11

- CHANGELOG.md
- appinfo/info.xml
- Allow to disable the changelog conversation with an app config  [#8365](https://github.com/nextcloud/spreed/pull/8365)
- Fix in_call flag on the "Join room" API response  [#8372](https://github.com/nextcloud/spreed/pull/8372)
- Fix bottom stripe of speaker view with high DPI  [#8320](https://github.com/nextcloud/spreed/pull/8320)
> Release 14.0.7

- CHANGELOG.md
- appinfo/info.xml
- Allow to disable the changelog conversation with an app config  [#8365](https://github.com/nextcloud/spreed/pull/8365)
- Improve message grouping duration to match better with UX expectations  [#8288](https://github.com/nextcloud/spreed/pull/8288)
- Update @nextcloud/vue library to 7.1.0  [#8405](https://github.com/nextcloud/spreed/pull/8405)  [#8419](https://github.com/nextcloud/spreed/pull/8419)
- Fix in_call flag on the "Join room" API response  [#8371](https://github.com/nextcloud/spreed/pull/8371)
- Fix bottom stripe of speaker view with high DPI  [#8319](https://github.com/nextcloud/spreed/pull/8319)
- Make webserver configuration check less error-prone  [#8310](https://github.com/nextcloud/spreed/pull/8310)  [#8332](https://github.com/nextcloud/spreed/pull/8332)
- Fix monitoring …
> Release 15.0.2

- src/components/RightSidebar/RightSidebar.vue
Follow up to #8453 
This reverts commit da87a426aa3a06e247e6638b9c837884f46a0f39 from #8418
which is now not needed anymore as the upstream patch was reverted
> Revert "Revert @nextcloud/vue changes to sidebar scrolling"

- appinfo/routes/routesBreakoutRoomController.php
- appinfo/routes/routesRoomController.php
- docs/breakout-rooms.md
- docs/conversation.md
- lib/Controller/BreakoutRoomController.php
- lib/Controller/RoomController.php
- lib/Model/BreakoutRoom.php
- lib/Service/BreakoutRoomService.php
- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/breakout-rooms.feature
> 🖖 Breakout rooms 🛠️ API - Part 3

- composer.lock
- docs/chat.md
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- tests/integration/features/conversation/avatar.feature
> Send system message when change room avatar

- src/FilesSidebarCallViewApp.vue
When a call is joined all the direct child elements of the header are hidden by adding a special CSS class, `hidden-by-call`, and then the call view is added to the header. When the call is left the `hidden-by-call` class is removed and the call view is moved back to [its original parent](https://github.com/nextcloud/spreed/blob/47e98d86d617925253f69f4a5a7ad67d63fd4d79/src/mainFilesSidebarLoader.js#L57). That parent was `.app-sidebar-header__action`, but in [nextcloud/vue 3.3.0 (Nextcloud 22) it was renamed to `app-sidebar-header__description`](https://github.com/nextcloud/nextcloud-vue/commit/7dec2b584b482699696a124c62e0fb3865984ba6).
As the expected parent did not exist the call view was not moved back and instead stayed as a direct child of the header, so when the call was joined again …
> Fix call view not visible when joining a call again in Files app

- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/WebServerSetupChecks.vue
> Fix(webserver): Remove uncertain warning to not alert on working setups

- appinfo/info.xml
- lib/Command/User/TransferOwnership.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/command/user-transfer-ownership.feature
- tests/psalm-baseline.xml
> Add command to transfer ownership

- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Dashboard/TalkWidget.php
- lib/Notification/Notifier.php
- lib/Search/MessageSearch.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/message-expiration.feature
- tests/integration/spreedcheats/appinfo/routes.php
- tests/integration/spreedcheats/lib/Controller/ApiController.php
- tests/php/Notification/NotifierTest.php
> Hide expired messages when do not run expire job

- docs/settings.md
- lib/Config.php
> Add app config to specify default attachment folder location

- appinfo/routes/routesBreakoutRoomController.php
- docs/breakout-rooms.md
- docs/conversation.md
- docs/participant.md
- lib/Controller/BreakoutRoomController.php
- lib/Controller/RoomController.php
- lib/Manager.php
- lib/Room.php
- lib/Service/BreakoutRoomService.php
- lib/Service/ParticipantService.php
- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/breakout-rooms.feature
- tests/php/Service/BreakoutRoomServiceTest.php
> 🖖 Breakout rooms 🛠️ API - Part 4

- src/components/NewMessageForm/NewMessageForm.vue
Replace deprecated `oc_defaults` with `OC.theme` for `productName` in the "Share from Nextcloud" button on the new message form.
Fixes warning: `oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20`.
It doesn't affect UI or tests.
> Replace deprecated oc_defaults with OC.theme

- src/FilesSidebarTabApp.vue
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- Open Talk
- Open a conversation
- Start a call
- Open the left navigation bar
- Change to another conversation (when asked by the modal, leave the call)
- Change again to the original conversation
The call view is not shown
The call view is automatically shown again, but the call is not actually joined
- Open Files
- Share a file
- Open the _Chat_ tab for that file
- Join the conversation
- Start a call
- Open the details for another file
- Open the details again of the original file
- Join again the conversation
The call view is not shown
The call view is automatically shown again, but the call is not actually joined
> Fix leaving call when switching to another conversation

- .github/workflows/appstore-build-publish.yml
- .github/workflows/lint-eslint-when-unrelated.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/lint-stylelint.yml
- .github/workflows/node-when-unrelated.yml
- .github/workflows/node.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- .github/workflows/psalm.yml
- .github/workflows/update-nextcloud-ocp.yml
- composer.json
> chore(CI): Update master php testing versions and workflow templates

- CHANGELOG.md
- Update @nextcloud/vue library to 7.4.0  [#8458](https://github.com/nextcloud/spreed/pull/8458)  [#8565](https://github.com/nextcloud/spreed/pull/8565)
- Allow autocompleting conversation names from the middle  [#8505](https://github.com/nextcloud/spreed/pull/8505)
- Call view not shown when rejoining a call in the file sidebar  [#8507](https://github.com/nextcloud/spreed/pull/8507)
- Fix leaving the call when switching to another conversation  [#8529](https://github.com/nextcloud/spreed/pull/8529)
- Don't keep the session open longer than necessary when leaving and joining a conversation  [#8394](https://github.com/nextcloud/spreed/pull/8394)
- Enforce a length of the private JWT keys used for signaling in case libressl has 0 as default …
> Add changelog for 14.0.8 and 15.0.3

- docs/recording.md
- lib/Service/RecordingService.php
- lib/Service/RoomService.php
- tests/integration/features/callapi/recording.feature
Allow multiple calls in parallel to stop call recordings
> Don't throw/error when the recording was stopped in parallel

- lib/AppInfo/Application.php
Micro performance optimization as it allows PHP to GC the surrounding class earlier when `$this` isn't bound to the closure.
---|---
:right_anger_bubble:  | :left_speech_bubble:
> perf(PHP): Use static closures for registrations

- lib/Files/TemplateLoader.php
Fix https://github.com/nextcloud/maps/issues/947
Unsure why this happens at all, but for now it might be easier to just disable it.
This however means Talk chats of files are not visible in the files sidebar of Photos you watch on the Maps app, but that is better than Maps not rendering at all.
We could create a follow up to have a look where it breaks, unless @danxuliu already has a clue.
> Don't break the maps app with talks files sidebar

- lib/Maps/MapsPluginLoader.php
---|---
Clicking results in 403 | No click, no error
- Requires usage of stable25 as maps does not work in master yet
- Apply following patch to work around https://github.com/nextcloud/maps/issues/947
```diff
diff --git a/lib/Files/TemplateLoader.php b/lib/Files/TemplateLoader.php
index c129c1854..297a214ae 100644
--- a/lib/Files/TemplateLoader.php
+++ b/lib/Files/TemplateLoader.php
@@ -95,7 +95,9 @@ class TemplateLoader implements IEventListener {
Util::addStyle(Application::APP_ID, 'At');
Util::addStyle(Application::APP_ID, 'icons');
-		Util::addScript(Application::APP_ID, 'talk-files-sidebar');
+		if (strpos(\OC::$server->getRequest()->getPathInfo(), '/apps/maps') !== 0)
+			Util::addScript(Application::APP_ID, 'talk-files-sidebar');
+		}
if ($user instanceof …
```
> Only register Maps plugin when allowed to use Talk

- src/components/LeftSidebar/ConversationsList/Conversation.vue
Fix #8464
---|---
Moderator | - 
User | -
> Change icon for 'Leave conversation'

- lib/Controller/RoomController.php
Fix #8416 
✨ Best reviewed each commit on it's own and with `?w=1` added on the URL to ignore whitespace changes
> 👥 Fix multiple sessions bug

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/BreakoutRoomsEditor/SelectableParticipant.vue
- src/components/ConversationSettings/BreakoutRoomsSettings.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBarMenu.vue
- src/constants.js
- src/services/breakoutRoomsService.js
- src/store/breakoutRoomsStore.js
- src/store/conversationsStore.js
- src/store/storeConfig.js
partially fixes  #8339
---|---
B | A
> Breakout Rooms round 1

- .drone.jsonnet
- .drone.yml
- composer/autoload.php
And don't register any generic PSR-4 nor PSR-0 loader in server.
https://github.com/nextcloud/server/blob/473c546b5c562e19ba8f9d3aef9cd64d2458cda7/lib/private/legacy/OC_App.php#L284-L290
---|---
:sloth:  | :snail:
> perf(autoloader): Force own autoloader

- src/components/LeftSidebar/LeftSidebar.vue
Fix #8599 
Bug appeared because of changing the scroll container with the 25 theming update.
> Fix "Unread mentions" button occurence

- package-lock.json
- package.json
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
Fix #7254 
Due to using the NcListItem component with title locked for modifications, we don't have opportunities to add `v-tooltip` here.
So, HTML-attribute `title` was applied for long names to show tooltip via native browser tools, when name is ellipsed.
*!IMPORTANT*
Current realisation works only if name is ellipsed initially (action button appears on hover and crops name even more)
> Fix tooltip appearance for long names in ConversationList

- src/components/TopBar/TopBar.vue
Fix #8019 
---|---
Light / Dark themes difference | New appearance
to clarify changes:
```
:deep(.action-item--open .action-item__menutoggle),
:deep(.action-item__menutoggle:hover),
:deep(.action-item--single:hover),
```
for NcActions elements (with open menu and on hover) - Screensharing, Conversation Settings, Chat
```
:deep(.buttons-bar button:hover) {
```
for other buttons in LocalMediaControls - Microphone, Camera, etc
hover `background-color: rgba(0, 0, 0, 0.2)` was copied from left sidebar toggle button.
Changes are scoped inside `.top-bar.in-call` selector
> Сorrect hover styles for buttons in TopBar during a call

- lib/Service/BreakoutRoomService.php
- lib/Signaling/BackendNotifier.php
- lib/Signaling/Listener.php
- lib/Signaling/Manager.php
- src/App.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/mixins/isInCall.js
- src/store/callViewStore.js
- src/store/conversationsStore.js
- src/utils/signaling.js
- tests/php/Signaling/BackendNotifierTest.php
When the breakout room status changes a generic `room` message is sent to all the active sessions in either the parent or the breakout rooms (depending on whether they are being started or stopped) with the token of the room that they have to switch to.
> Send signaling messages when starting and stopping breakout rooms

- lib/Collaboration/Collaborators/Listener.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/add-participant.feature
> Only filter mentions for conversation members

- src/components/TopBar/TopBar.vue
Manual backport of #8661 to `stable25` 
Somehow, `:deep(.selector)` isn't working in previous version, so it was changed to `::v-deep .selector`
Please also check it visually on running stable25 version
> [stable25] Сorrect hover styles for buttons in TopBar during a call

- src/components/CallView/CallView.vue
- src/components/CallView/shared/LocalVideo.vue
Fix #8571
Removed top padding from video container
Also untied `margin-top` from fixed value for local video container
(Could be switched to `align-self: flex-end`, but this method has [less support](https://caniuse.com/?search=align-self%3A%20end) )
> Correct position for local video in 1:1 call
