nextcloud/spreed

lib/Command/Room/TRoomCommand.php
lib/Controller/RoomController.php
lib/Manager.php
lib/Room.php
lib/Service/RoomService.php
tests/php/Signaling/BackendNotifierTest.php

Move setReadOnly to room service

---

lib/Chat/AutoComplete/Sorter.php
lib/Controller/ChatController.php
lib/Search/CurrentMessageSearch.php
lib/Search/MessageSearch.php

Fix missing constant usage

---

lib/Signaling/BackendNotifier.php
psalm.xml
tests/php/Signaling/BackendNotifierTest.php

Retry sending signaling messages up to 3 times

---

appinfo/routes/routesCallController.php
docs/call.md
docs/capabilities.md
lib/AppInfo/Application.php
lib/Capabilities.php
lib/Controller/CallController.php
lib/Events/SendCallNotificationEvent.php
lib/Middleware/InjectionMiddleware.php
lib/Notification/Listener.php
lib/Notification/Notifier.php
lib/Service/ParticipantService.php
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/services/participantsService.js
src/store/participantsStore.js
tests/php/CapabilitiesTest.php

Allow to "Send call notifications"

---

docs/call.md
docs/chat.md
docs/conversation.md
docs/integration.md
docs/internal-signaling.md
docs/participant.md
docs/reaction.md
docs/settings.md
docs/webinar.md

Also document Nextcloud versions on API docs

---

lib/Signaling/Listener.php

[stable24] Only declare the actual changed session of a user as changed

---

src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/CallView/shared/EmptyCallView.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/components/TopBar/TopBar.vue
src/deck.js

1. Unification of messages.
2. Improving the spelling of the name "App Store".

l10n: Delete dots and changed spelling of App Store

---

.github/workflows/phpunit.yml
composer.json
composer.lock

Add phpunit as dependency like in other apps

---

.github/workflows/phpunit.yml
composer.json
composer.lock
psalm.xml

[stable23] Add phpunit as dependency like in other apps

---

.github/workflows/phpunit.yml
composer.json
composer.lock
psalm.xml
tests/psalm-baseline.xml

[stable22] Add phpunit as dependency like in other apps

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Don't allow to promote circles

---

lib/Manager.php
lib/Room.php
lib/Service/RoomService.php
lib/Signaling/Manager.php

Move setAssignedSignalingServer to room service

---

lib/Chat/Parser/SystemMessage.php
tests/integration/features/bootstrap/FeatureContext.php

[stable23] Fix "Invalid argument supplied for foreach() at SystemMessage.php#720"

---

lib/Signaling/BackendNotifier.php

Fix backend url from CLI

---

src/components/NewMessageForm/NewMessageForm.vue

l10n: Delete shortcut

---

src/components/LeftSidebar/LeftSidebar.vue

Sneaky lil change, been annoyed by this for too long

Route to the first search result upon pressing enter

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

Backport https://github.com/nextcloud/spreed/pull/7439

[stable23] Add a capability for the unified-search

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

[stable22] Add a capability for the unified-search

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

[stable24] Add a capability for the unified-search

---

lib/Command/Room/TRoomCommand.php
lib/Controller/RoomController.php
lib/Room.php
lib/Service/RoomService.php
tests/php/Signaling/BackendNotifierTest.php

Move setDescription to room service

---

src/PublicShareAuthSidebar.vue
src/components/DeviceChecker/DeviceChecker.vue
src/components/TopBar/CallButton.vue
src/services/callsService.js
src/store/participantsStore.js
src/store/participantsStore.spec.js

Silent calls front end

---

src/components/DeviceChecker/DeviceChecker.vue

Use better name for silent call option

---

src/App.vue

Signed-off-by: szaimen <szaimen@e.mail.de>

do not open the right sidebar on mobile automatically

---

composer.lock

```
composer require --dev christophwurst/nextcloud:dev-master
```

Bump packages

---

docs/chat.md

Document poll system messages

---

docs/poll.md
lib/Model/Poll.php
tests/integration/features/chat/poll.feature

Fix https://github.com/nextcloud/spreed/issues/7480#issuecomment-1168809326

Fix the array structure of "voted" attribute with PHP json_encode

---

lib/Controller/FilesIntegrationController.php
lib/Controller/PageController.php
lib/Controller/RoomController.php
lib/Controller/SignalingController.php
lib/Middleware/InjectionMiddleware.php
psalm.xml
templates/authenticate.php

[stable22] Add brute force protection to conversation passwords

---

src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
src/components/LeftSidebar/SearchBox/SearchBox.vue

Add aria labels to "Remove input" buttons

---

src/components/Quote.vue

Move to single button and add label to "Cancel quote" button

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
src/components/RightSidebar/SharedItems/SharedItems.vue

Fix locations not showing in chat due to missing height

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

Fix syntax

---

docs/capabilities.md
lib/Capabilities.php
lib/Controller/ChatController.php
lib/Controller/PollController.php
lib/Model/Attachment.php
lib/Service/AttachmentService.php
tests/integration/features/chat/poll.feature
tests/php/CapabilitiesTest.php

📊 Poll follow ups

---

appinfo/info.xml
lib/BackgroundJob/ExpireChatMessages.php
lib/Chat/ChatManager.php
lib/Service/RoomService.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/message-expiration.feature
tests/integration/spreedcheats/appinfo/routes.php
tests/integration/spreedcheats/lib/Controller/ApiController.php

Expire messages part 2: a background job for all rooms

---

lib/Search/MessageSearch.php

Add more search attributes

---

lib/Search/MessageSearch.php

Fix guest names in search results

---

lib/TInitialState.php

Ref https://github.com/nextcloud/spreed/issues/7566

Fix HTML validation of meta element

---

tests/integration/features/bootstrap/FeatureContext.php

Accidentally deleted in this PR: https://github.com/nextcloud/spreed/pull/7571
Used here: https://github.com/nextcloud/spreed/blob/master/tests/integration/features/chat/message-expiration.feature#L22

Restore deleted method

---

lib/Chat/SystemMessage/Listener.php
lib/Controller/RoomController.php
lib/Service/RoomService.php

PS: Branch created from #7594. Necessary to review and merge first the parent branch.

Listener to send message expiration message

---

src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Remove invalid attribute icon from button

---

src/components/SettingsDialog/SettingsDialog.vue

Fix keyboard navigation in the settings

---

lib/Controller/PollController.php
lib/Service/PollService.php
tests/integration/features/chat/poll.feature

Fix error getting poll without votes

---

src/components/SettingsDialog/SettingsDialog.vue

Fix invalid setting sections IDs

---

docs/chat.md
docs/conversation.md
docs/poll.md

Signed-off-by: Aaron Segura <aaron@aaronsegura.com>

[Documentation] Set proper header for requesting JSON response

---

src/components/AdminSettings/MatterbridgeIntegration.vue

Move Matterbridge install to vue button

---

src/components/AdminSettings/StunServer.vue
src/components/AdminSettings/StunServers.vue
src/components/AdminSettings/TurnServer.vue
src/components/AdminSettings/TurnServers.vue
src/components/missingMaterialDesignIcons/CategoryMonitoring.vue

Move TURN and STUN to Vue components

---

src/components/AdminSettings/HostedSignalingServer.vue

Move Hosted signaling server to Vue button

---

src/components/AdminSettings/SIPBridge.vue

Move SIP bridge settings to Vue button

---

src/components/AdminSettings/GeneralSettings.vue

Fix checkboxes in general admin settings

---

package-lock.json
package.json
src/components/AdminSettings/AllowedGroups.vue
src/components/AdminSettings/Command.vue
src/components/AdminSettings/GeneralSettings.vue
src/components/AdminSettings/HostedSignalingServer.vue

Ref https://github.com/nextcloud/spreed/issues/7651

Fix HTML validations in admin settings

---

templates/authenticate.php

> ![image](https://user-images.githubusercontent.com/23653902/180420730-9e923a0b-1eba-4653-b786-207ac8b2ef7d.png)

Adapte guest page to NC 25

---

src/components/LeftSidebar/LeftSidebar.vue

> Error: Element div not allowed as child of element ul in this context. (Suppressing further errors from this subtree.)

Fix HTML validation DIV not allowed inside UL

---

lib/Service/PollService.php
tests/integration/features/chat/poll.feature

Return 400 on empty questions and options

---

.github/workflows/update-christophwurst-nextcloud.yml

Update christophwurst/nextcloud package nightly

---

.github/workflows/update-christophwurst-nextcloud.yml

Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>

Update with the final template

---

package-lock.json
package.json

Bump nextcloud-vue to 5.4.0

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

Fix anchors in conversation settings

---

src/components/CallView/shared/EmptyCallView.vue

Move "Copy link" of empty call screen to Vue

---

src/components/ConversationSettings/ConversationPermissionsSettings.vue

Move permission button to Vue

---

src/PublicShareSidebar.vue

Move public share sidebar to vue button

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js

```
console.error
[Vue warn]: Missing required prop: "isLastRead"
found in
---> <MessageButtonsBar>
<Root>
```

Fix missing required prop in tests

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.vue

Move reactions to vue buttons

---

src/components/AdminSettings/WebServerSetupChecks.vue

Fix the icon size being an actual number

---

CHANGELOG.md
appinfo/info.xml

[stable23] Add changelog for 13.0.8

---

lib/Chat/Parser/SystemMessage.php
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/ConversationSettings/ExpirationSettings.vue
src/services/conversationsService.js
src/store/conversationsStore.js

Ref https://github.com/nextcloud/spreed/issues/7359

Add UI option to set the message expiration

---

src/components/SettingsDialog/SettingsDialog.vue

Requires https://github.com/nextcloud/nextcloud-vue/pull/3035.
@nickvergessen Could you check whether this fixes the settings modal scroll issue for you?

Fix app settings dialog style

---

lib/Share/RoomShareProvider.php

This reduce the number of queries considerably. For me on the production
instance I went from 120 queries to 103 queries on the activity page.

Use bigger slice

---

tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/command/user-remove.feature

Ref https://drone.nextcloud.com/nextcloud/spreed/9142/21/4

Make postgres integration tests reliable

---

src/components/DeviceChecker/DeviceChecker.vue

[stable23] Fix missing tooltip directive in DeviceChecker

---

src/components/DeviceChecker/DeviceChecker.vue

[stable24] Fix missing tooltip directive in DeviceChecker

---

tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/command/user-remove.feature

[stable24] Make postgres integration tests reliable

---

src/components/CallView/CallView.vue

[stable23] Fix remote screen shares not shown in sidebar

---

src/components/ConversationSettings/ExpirationSettings.vue

l10n: Improved grammar

---

package-lock.json
package.json

Update to @nextcloud/vue 6.0.0-beta.4

---

.drone.yml
lib/Chat/Notifier.php
lib/Notification/Notifier.php
lib/Service/ParticipantService.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/callapi/notifications.feature
tests/integration/features/chat/notifications.feature
tests/integration/spreedcheats/lib/Controller/ApiController.php

[stable23] Fix notifications when lobby is active

---

docs/poll.md
lib/Controller/PollController.php
tests/integration/features/chat/poll.feature

Don't allow to close polls twice

---

lib/Chat/Parser/SystemMessage.php

Fix close/end wording

---

Makefile

Fix exclude list with vendor src/

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue

Show voters details in polls

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/AvatarWrapper/AvatarWrapperSmall.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
src/store/pollStore.js

* src/components/AvatarWrapper/AvatarWrapper.vue Reverting the changes from #7820 and move it to AvatarWrapperSmall
* Fix guest avatars not showing in the small size
Before | After
---|---

Fix voted guests handling

---

CHANGELOG.md
appinfo/info.xml

- 🗒️ Allow to create new files from within the chat
- 🌏 Show link previews for chat messages with links
- Show more details on the poll result screen
- Upgrade @nextcloud/vue to version 7
- Improve performance by using the UserDisplayNameCache
- Improve performance of chats with a lot of shared files
- Populate ETag and permissions so the image editor works as expected
- Fix depenendency management and make sure all required dependencies are shipped
- Fix type of icon size
- Fix missing aria-labels and tooltips in various places
- Fix missing local media in share sidebar
- Fix missing screenshares in share sidebar
- Ensure that the reactions details is always an object
- Do not allow to close a poll twice
- Make handling of guest moderators more consistent

Changelog for 15.0.0 beta.2

---

composer.json
composer.lock

Fix #7849 
Following the sample of the mail app in the hope that this fixes the broken release automation

Move composer-bin-plugin to normal deps

---

composer.lock
vendor-bin/csfixer/composer.lock
vendor-bin/phpunit/composer.lock
vendor-bin/psalm/composer.lock

Auto-generated update of [christophwurst/nextcloud](https://github.com/ChristophWurst/nextcloud_composer/) dependency

[master] Update christophwurst/nextcloud dependency

---

src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/SettingsDialog/SettingsDialog.vue

Add titles to settings dialogs

---

src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/VideoVue.vue

Adjust videos border radius

---

src/App.vue
src/assets/variables.scss
src/components/CallView/CallView.vue
src/components/TopBar/TopBar.vue

Update callview backdrop

---

CHANGELOG.md
appinfo/info.xml

- Finish polls UI
- Several fixes to adapt to the UI changes in Nextcloud 25

Changelog for 15.0.0 beta.3

---

lib/Controller/PageController.php

* Ref https://github.com/nextcloud/server/pull/33818

Dispatch reference rendering event

---

src/components/DeviceChecker/DeviceChecker.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
src/components/PermissionsEditor/PermissionsEditor.vue

Fixes modal disappearing when toggling fullscreen

Add container to all NcModal components

---

lib/Settings/Admin/AdminSettings.php
templates/settings/admin-settings.php

Remove old import of admin css

---

package-lock.json
package.json

Bump @nextcloud/vue to 7.0.0-beta.3

---

package-lock.json
package.json

You may take over if needed @nextcloud/talk team :)

Bump @nextcloud/vue to 7.0.0-beta.4

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue

l10n: Add "for"

---

package-lock.json
package.json

Ref https://github.com/nextcloud/vue-richtext/pull/778

Update vue-richtext to 2.0.1

---

src/components/RightSidebar/SharedItems/SharedItems.vue
src/components/RightSidebar/SharedItems/SharedItemsTab.vue
src/constants.js
src/mixins/sharedItems.js
src/store/sharedItemsStore.js

Show polls in own section of shared items

---

src/components/RightSidebar/SharedItems/SharedItemsTab.vue

Add related resources panel to shared items sidebar

---

src/components/CallView/shared/LocalVideo.vue

Fix username overlap with localvideo

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue

Fix poll voter details

---

src/components/LeftSidebar/ConversationsList/Conversation.vue

Close menu when favoriting

---

img/reply.svg

Add viewbox to SVG

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

Reduce preview size of non images/videos

---

src/components/AdminSettings/SignalingServers.vue

Fix #7902 
Before | After
---|---

Migrate warning toggle to NcCheckboxRadioSwitch

---

package-lock.json
package.json
src/components/CallView/shared/EmptyCallView.vue
src/components/ConversationSettings/LinkShareSettings.vue
src/components/LeftSidebar/ConversationsList/Conversation.spec.js
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/NewGroupConversation/Confirmation/Confirmation.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/TopBar/TopBar.vue
src/main.js

Remove vue-clipboard2

---

lib/Controller/TempAvatarController.php

Don't use shortcut "admin"

---

package-lock.json
package.json

Bump @nextcloud/vue@7.0.0-beta.5

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesList.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Fix action menus being cut

---

.drone.jsonnet
.drone.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
.github/workflows/update-christophwurst-nextcloud.yml

Adjust testing matrix for Nextcloud 25 on stable25

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesList.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Backport of https://github.com/nextcloud/spreed/pull/7876

[stable25] Fix action menus being cut

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/MessagesGroup.vue

Backport of https://github.com/nextcloud/spreed/pull/7981

[stable25] Fix clipped link previews

---

CHANGELOG.md
appinfo/info.xml

- Implement the new dashboard widget modes
- Allow to opt-out of keyboard shortcuts to improve accessibility
- Show more poll voters in details popover
- Do not allow to forward polls as they become non-functional
- Fix coloring of reaction buttons
- Reduce preview size for non-images
- Disallow polls in one-to-one chats
- Adjust the height of file upload modals
- Show empty content when all messages expire
- Correctly quote the parent again when sending the message failed

Release 15.0.0-rc.1

---

.github/workflows/update-christophwurst-nextcloud.yml
appinfo/info.xml
package.json

Add Nextcloud 26 support on master

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/MessagesGroup.vue

Fix clipped link previews

---

CHANGELOG.md

- Implement the new dashboard widget modes
- Allow to opt-out of keyboard shortcuts to improve accessibility
- Show more poll voters in details popover
- Do not allow to forward polls as they become non-functional
- Fix coloring of reaction buttons
- Reduce preview size for non-images
- Disallow polls in one-to-one chats
- Adjust the height of file upload modals
- Show empty content when all messages expire
- Correctly quote the parent again when sending the message failed

Add changelog for 15.0.0-rc.1

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Fix #7989 
Before | After
---|---

Fix missing reaction summary when hovering

---

composer.json
composer.lock
vendor-bin/phpunit/composer.lock

Auto-generated update of [christophwurst/nextcloud](https://github.com/ChristophWurst/nextcloud_composer/) dependency

[stable25] Update christophwurst/nextcloud dependency

---

.github/workflows/psalm.yml
composer.json
composer.lock

Migrate to nextcloud/OCP package in stable24

---

.github/workflows/psalm.yml
composer.json
composer.lock

Migrate to nextcloud/OCP package in stable23

---

composer.lock

Bump nextcloud/ocp package

---

composer.lock

[stable25] Bump nextcloud/ocp package

---

lib/Room.php
lib/Service/RoomService.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation/lobby.feature

Recursion with lobby timer expiring

---

src/components/TopBar/CallButton.vue

Fix #8030 
Before | After
---|---

Fix missing "Leave call" button for moderators

---

tests/php/phpunit.xml

Solving the follow warning:
```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```

Updated the phpunit.xml to newest schema

---

lib/Controller/ChatController.php
src/components/Quote.vue

Fix quotes of expired messages

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Remove references for deleted messages

---

package-lock.json
package.json

Bump @nextcloud/vue to v7.0.0-beta.7

---

src/components/LeftSidebar/LeftSidebar.vue

Fix left sidebar padding

---

CHANGELOG.md

Add changelog for 15.0.0-rc.2

---

composer.lock
vendor-bin/csfixer/composer.lock
vendor-bin/mozart/composer.lock
vendor-bin/psalm/composer.lock

[stable25] Update nextcloud/ocp dependency

---

composer.lock
vendor-bin/csfixer/composer.lock
vendor-bin/mozart/composer.lock
vendor-bin/psalm/composer.lock

[master] Update nextcloud/ocp dependency

---

src/components/AdminSettings/GeneralSettings.vue
src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/AdminSettings/SignalingServer.vue
src/components/ConversationSettings/LinkShareSettings.vue
src/components/ConversationSettings/LobbySettings.vue
src/components/ConversationSettings/LockingSettings.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/ConversationSettings/SipSettings.vue
src/store/conversationsStore.js

Fix #7997 
Fix #7707
Fix #7901

Fix disappearing conversation settings

---

src/components/MessagesList/MessagesList.vue
src/store/messagesStore.js

See https://github.com/nextcloud/spreed/issues/7320#issuecomment-1264612191 For explanation and reasoning
Fix #7320

Fix chats not updating the read marker

---

src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue

Resort participant actions

---

src/components/ConversationSettings/ConversationPermissionsSettings.vue
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/ConversationSettings/DangerZone.vue
src/components/ConversationSettings/ExpirationSettings.vue
src/components/ConversationSettings/LinkShareSettings.vue
src/components/ConversationSettings/ListableSettings.vue
src/components/ConversationSettings/LobbySettings.vue
src/components/ConversationSettings/LockingSettings.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/ConversationSettings/NotificationsSettings.vue
src/components/ConversationSettings/SipSettings.vue

Fix #5253
Before | After
---|---

Re-group conversation settings

---

lib/AppInfo/Application.php
lib/Controller/PageController.php

Move to new event syntax

---

lib/Controller/RoomController.php

Improve resend invitations performance

---

src/components/RightSidebar/LobbyStatus.vue

Make the lobby opening a positive action

---

src/components/ConversationSettings/LinkShareSettings.vue

Move share password to NcPasswordField

---

src/views/RoomSelector.vue

fixes #8107
https://user-images.githubusercontent.com/26852655/194354280-2d143722-f412-4459-9c14-d59ba964cab4.mov

Use new NcTextField component for Forwarder search

---

lib/Signaling/Listener.php
tests/php/Signaling/BackendNotifierTest.php

Backport of https://github.com/nextcloud/spreed/pull/7974

[stable22] Fix participant sessions not sent to the HPB

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

😄 Frequently used emojis

---

CHANGELOG.md

- Move all checkboxes to NcCheckboxRadioSwitch component so the UI doesn't break
- Reorganize the conversation settings
- Fix chats not getting marked as read with reactions

Changelog for 15.0.0-rc.3

---

package-lock.json
package.json
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue

Fix https://github.com/nextcloud/spreed/issues/8144

Fix emoji picker version

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

Keep emoji picker open

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

Allow expiration in 1-1

---

.github/workflows/phpunit.yml

Test against postgres 14

---

.github/workflows/phpunit.yml

[stable25] Test against postgres 14

---

.github/workflows/phpunit.yml

[stable24] Test against postgres 14

---

.github/workflows/phpunit.yml

[stable23] Test against postgres 14

---

src/components/CallView/shared/VideoBottomBar.vue

Fix broken size of raise hand icon

---

CHANGELOG.md

Add expiration to the changelog

---

package-lock.json
package.json

Should give a huge performance boost when opening action menus

Bump @nextcloud/vue to 7.0.1

---

src/components/CallView/Grid/Grid.vue

Take the devicePixelRatio into consideration for the grid size calculation

---

lib/OCP/Conversation.php
lib/OCP/TalkBackend.php

For https://github.com/nextcloud/server/pull/34894. Use case and description is also found in the other PR.

Add conversation delete support via OCP API

---

CHANGELOG.md
appinfo/info.xml

Add changelog 12.2.8, 13.0.10 and 14.0.6

---

CHANGELOG.md
appinfo/info.xml

Add changelog 12.2.8 and 13.0.10

---

appinfo/info.xml

Welcome on board

---

lib/Controller/CommandController.php
lib/Migration/CreateHelpCommand.php
lib/Migration/Version7000Date20190724121137.php
lib/OCP/Conversation.php
lib/OCP/TalkBackend.php
lib/Service/AttachmentService.php

Fix missing header

---

lib/Middleware/CanUseTalkMiddleware.php

Fix #8315 
Before | After
---|---

Fix signaling server check when admin is blocked from talk

---

package-lock.json
package.json

Bump @nextcloud/vue to 7.1.0-beta.0

---

docs/participant.md

[stable24] Fix parameter name in docs

---

.drone.jsonnet
.drone.yml

Fix postgres integration tests

---

appinfo/info.xml
appinfo/routes.php
appinfo/routes/routesBreakoutRoomController.php
docs/breakout-rooms.md
docs/capabilities.md
docs/constants.md
docs/webinar.md
lib/Capabilities.php
lib/Controller/BreakoutRoomController.php
lib/Manager.php
lib/Migration/Version16000Date20221110151714.php
lib/Model/BreakoutRoom.php
lib/Model/SelectHelper.php
lib/Room.php
lib/Service/BreakoutRoomService.php
lib/Service/ParticipantService.php
lib/Service/RoomService.php
mkdocs.yml
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation/breakout-rooms.feature
tests/php/CapabilitiesTest.php
tests/php/Service/RoomServiceTest.php

🖖 Breakout rooms 🛠️ API - Part 1

---

lib/Config.php

Enfore length of private keys

---

lib/Chat/ChatManager.php
tests/php/Chat/ChatManagerTest.php

Fix channel name autocomplete

---

docs/TURN.md

Fix(docs): Grammar and markdown-layout fixes for TURN docs

---

psalm.xml

Fix psalm schema location

---

appinfo/routes/routesRecordingController.php
lib/Controller/RecordingController.php
lib/Service/RecordingService.php
lib/Service/RoomService.php
tests/php/Service/RecordingServiceTest.php

Move methods of Recording from RoomService to RecordingService

---

lib/Manager.php

Replacement of #8467
Best reviewed as https://github.com/nextcloud/spreed/pull/8531/files?w=1

[stable25] Wrap rooms creation in transaction

---

lib/Manager.php

Create the Room object from available data

---

lib/Controller/RecordingController.php
lib/Service/RecordingService.php

Use PHP8 constructor promotion

---

.github/workflows/appstore-build-publish.yml
.github/workflows/dependabot-approve.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/psalm.yml
.github/workflows/update-nextcloud-ocp.yml
lib/Controller/BreakoutRoomController.php
lib/Service/BreakoutRoomService.php

Use PHP8 constructor promotion in breakout rooms code

---

CHANGELOG.md
appinfo/info.xml

Changelog for 14.0.8

---

CHANGELOG.md
appinfo/info.xml

Changelog for 15.0.3

---

src/components/DeviceChecker/DeviceChecker.vue
src/components/TopBar/CallButton.vue
src/components/TopBar/CallTime.vue
src/components/TopBar/TopBar.vue
src/components/TopBar/TopBarMenu.vue
src/constants.js
src/services/recordingService.js
src/store/conversationsStore.js

Ref #8325 
Menu start | Menu stop | Call time stop
---|---|---

⏺️ Call recording UI part2

---

appinfo/routes/routesRecordingController.php
docs/recording.md
lib/Chat/SystemMessage/Listener.php
lib/Controller/RecordingController.php
lib/Notification/Notifier.php
lib/Service/RecordingService.php
tests/integration/features/callapi/recording.feature
tests/php/Notification/NotifierTest.php
tests/php/Service/RecordingServiceTest.php

Notify recording stored

---

composer.json
lib/Activity/Listener.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/callapi/recording.feature

Stop recording after end call

---

package-lock.json

Changed 1 package, and audited 1817 packages in stable25.
Updated dependency "ua-parser-js" to version 1.0.33

Update dependencies list

---

src/components/BreakoutRoomsEditor/SendMessageDialog.vue
src/components/ChatView.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/store/breakoutRoomsStore.js

https://user-images.githubusercontent.com/26852655/215503893-7e171655-5d99-44bd-b81b-02b4adc2a503.mov

Add ability to post message to breakout rooms

---

.github/dependabot.yml

Set up dependabot for stable branches

---

docs/breakout-rooms.md
lib/Controller/AEnvironmentAwareController.php
lib/Controller/BreakoutRoomController.php
lib/Controller/RoomController.php
lib/Model/Message.php
lib/Service/BreakoutRoomService.php
lib/Service/RoomFormatter.php

- Could help with https://github.com/nextcloud/spreed/issues/8339#issuecomment-1403123701

Return breakout rooms on the API calls

---

Makefile

chore(packaging): Remove upcoming recording scripts from release tarball

---

docs/chat.md

fix(docs): Fix documented system messages list

---

lib/Controller/PollController.php
lib/Middleware/InjectionMiddleware.php

fix(polls): Don't allow to create polls in changelog conversations

---

src/components/BreakoutRoomsEditor/BreakoutRoomsList.vue
src/components/BreakoutRoomsEditor/SendMessageDialog.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/services/breakoutRoomsService.js
src/store/breakoutRoomsStore.js

https://user-images.githubusercontent.com/26852655/216072991-22872319-ed89-468e-8224-4746a5042a1e.mov

Broadcast message to all breakout rooms

---

.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/psalm.yml
tests/php/Chat/ChatManagerTest.php
tests/php/Federation/FederationTest.php
tests/php/Service/BreakoutRoomServiceTest.php
tests/php/Service/RoomServiceTest.php

Add PHP 8.2 support

---

.drone.jsonnet
.drone.yml
.github/dependabot.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/psalm.yml
tests/integration/composer.json
tests/integration/composer.lock
tests/php/Chat/ChatManagerTest.php
tests/php/Federation/FederationTest.php
tests/php/Service/BreakoutRoomServiceTest.php
tests/php/Service/RoomServiceTest.php

Test execution of php8.2 integration tests

---

src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/components/RightSidebar/RightSidebar.vue
src/store/breakoutRoomsStore.js
src/store/conversationsStore.js

Improve breakout rooms reactivity

---

src/App.vue

1. Create 2 users
2. As user 1 create a one-to-one with user 2
3. As user 2 navigate to the "Talk" homepage
4. As user 2 click on "Show chat"
Before | After
---|---
🐌 Page reload | 🐈 No page reload

feat(performance): Open conversations from notifications without page reload

---

lib/Controller/PageController.php
lib/Controller/RoomController.php
lib/Middleware/InjectionMiddleware.php

Always log the token and reset again when joining successfully

---

.github/workflows/dependabot-approve-merge.yml

chore(deps): Add auto approval and merge for dependabot

---

src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/services/breakoutRoomsService.js
src/store/breakoutRoomsStore.js

Get breakout rooms participants

---

src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
src/store/breakoutRoomsStore.js

A few fixes and improvements (see commits messages)

Breakout rooms polishing 

---

src/components/NewMessageForm/NewMessageForm.vue

Do not show audio recorder when broadcasting messages

---

src/components/BreakoutRoomsEditor/BreakoutRoomsList.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/constants.js
src/services/breakoutRoomsService.js

Breakout-rooms: assistance request display and removal for moderators

---

src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/services/breakoutRoomsService.js
src/store/breakoutRoomsStore.js

https://user-images.githubusercontent.com/26852655/218494464-e116b6a4-52a7-45b2-86ec-4dd9d1ee5733.mov

Add participant editor to breakoutroomstab

---

lib/Share/RoomShareProvider.php

When creating a share, we're reading from the database straight afterwards saving it.
```
OCP\Share\Exceptions\ShareNotFound: Share not found
#9 /spreed/lib/Share/RoomShareProvider.php(268): OCA\Talk\Share\RoomShareProvider::getRawShare
#8 /spreed/lib/Share/RoomShareProvider.php(196): OCA\Talk\Share\RoomShareProvider::create
#7 /var/www/nc/nextcloud-25.0.1/lib/private/Share20/Manager.php(818): OC\Share20\Manager::createShare
#6 /files_sharing/lib/Controller/ShareAPIController.php(701): OCA\Files_Sharing\Controller\ShareAPIController::createShare
#5 /var/www/nc/nextcloud-25.0.1/lib/private/AppFramework/Http/Dispatcher.php(225): OC\AppFramework\Http\Dispatcher::executeController
```
Another possibility is just #8741, feel free to close this one.

fix(share): Use transaction to avoid read-after-write issue

---

src/components/CallView/shared/VideoVue.spec.js
src/components/CallView/shared/VideoVue.vue

Fix #8156 
---|---
One-to-One call | 
Group call |

Fix rounded corners on speaker's video

---

docs/capabilities.md
lib/Capabilities.php
lib/Controller/RoomController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/one-to-one.feature
tests/php/CapabilitiesTest.php

Return status of other user on one to one room

---

CHANGELOG.md
appinfo/info.xml

Add changelog for 14.0.9

---

src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesList.vue
src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
src/components/NewMessageForm/NewMessageForm.vue
src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
src/components/SetGuestUsername.vue
src/components/TopBar/CallButton.vue
src/components/TopBar/TopBar.vue
src/components/UploadEditor.vue
src/views/RoomSelector.vue

Fix #8828
Backport of #7133
Before | After
---|---

[stable24] Fix visual glitches introduced by vue lib update

---

docs/capabilities.md
docs/conversation.md
lib/Activity/Provider/Base.php
lib/Capabilities.php
lib/Collaboration/Reference/TalkReferenceProvider.php
lib/Dashboard/TalkWidget.php
lib/Search/ConversationSearch.php
tests/integration/features/conversation/breakout-rooms.feature
tests/integration/features/integration/dashboard.feature
tests/php/Activity/Provider/BaseTest.php
tests/php/CapabilitiesTest.php

Less invasive version of #8774 
* Fix #8760 
* Fix #8747 - Should be reopened when this PR is reverted

Remove avatar capability

---

src/store/conversationsStore.js

fix(recording): Fix detection of previous state when incomplete

---

tests/integration/features/conversation/breakout-rooms.feature

fix(CI): Make the breakout room tests more reliable by ordering locally

---

jest.config.js
package-lock.json
package.json
src/__mocks__/styles.js
src/__mocks__/tabbable.js

Fix #7701 in addition _(Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>)_

Bump @nextcloud/vue to ^7.7.1

---

appinfo/info.xml

Only ordering the rows to make more easy to found the command.

Order commands at info.xml

---

recording/src/nextcloud/talk/recording/BackendNotifier.py

Fix recording server documentation typos

---

docs/call.md

Docs are in https://github.com/nextcloud/spreed/blob/master/docs/recording.md and the duplicate ones aren't even complete

Remove duplicate call recording docs

---

package-lock.json
package.json

chore(deps): Bump @nextcloud/vue to 7.7.2

---

src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue

Improve breakout rooms dialog

---

src/components/NewMessageForm/NewMessageForm.vue

fix: Remove duplicate condition check

---

src/components/ConversationSettings/BreakoutRoomsSettings.vue
src/components/TopBar/TopBarMenu.vue

Fix wording

---

src/components/TopBar/TopBar.vue

Fix #8884 
---|---
See issue above | See video below
https://user-images.githubusercontent.com/93392545/222438214-b46d9393-daad-4988-b66d-df7d21993f96.mp4

Replace `NcActions` with `NcButton` in TopBar.vue

---

lib/Controller/BreakoutRoomController.php
lib/Manager.php
lib/Room.php
lib/Service/BreakoutRoomService.php
lib/Service/RoomFormatter.php

Show breakout room names when listing breakout rooms

---

.github/dependabot.yml

chore(CI): Define backport list for stable26

---

.github/workflows/update-nextcloud-ocp.yml
appinfo/info.xml
package.json
tests/integration/spreedcheats/appinfo/info.xml

chore: Add Nextcloud 27 support on master

---

src/assets/variables.scss
src/components/ChatView.vue

Fix drag-drop modal in Chat.vue flickering

---

.drone.jsonnet
.drone.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml

chore(CI): Adjust testing matrix for Nextcloud 26 on stable26

---

composer.json
composer.lock
vendor-bin/csfixer/composer.lock
vendor-bin/mozart/composer.lock
vendor-bin/phpunit/composer.lock
vendor-bin/psalm/composer.lock

[stable26] Update nextcloud/ocp dependency

---

CHANGELOG.md

- Migrate RichText component usage to NcRichText [#8959](https://github.com/nextcloud/spreed/pull/8959)
- Design review changes for breakout rooms handling [#8962](https://github.com/nextcloud/spreed/pull/8962)
- Add documentation for OCC commands [#8907](https://github.com/nextcloud/spreed/pull/8907)

chore(release): Add changelog for 16.0.0-rc.2

---

CHANGELOG.md
appinfo/info.xml

[stable26] Add changelog for 16.0.0-rc.2

---

lib/Manager.php

ref https://github.com/nextcloud/spreed/pull/8976#issuecomment-1457601411

fix(API): Sort listed conversations on API level so CI results are stable

---

src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
src/components/BreakoutRoomsEditor/SelectableParticipant.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue

Use breakoutroomitem component in participant editor

---

src/components/LeftSidebar/LeftSidebar.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

Fix search-box and new conversation button design

---

src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue

Fix icons alignment

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue

Wrap poll results

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/test-helpers.js

Changed a component, adjust tests to pass
Tooltip was also changed with native title
---|---

Replace `NcActionButton` with `NcButton` in MessageButtonsBar

---

src/components/ConversationSettings/BasicInfo.vue
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/ConversationSettings/EditableTextField.vue
src/components/Description/Description.vue
src/components/RightSidebar/RightSidebar.vue
src/components/TopBar/TopBarMenu.vue

https://user-images.githubusercontent.com/26852655/224713057-63aac718-bd64-4c00-8279-25ed769464f4.mov

Move conversation renaming into conversation dialog

---

.eslintrc.js
package-lock.json
src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
src/main.js
src/mainFilesSidebar.js
src/mainPublicShareAuthSidebar.js
src/mainPublicShareSidebar.js
src/mainRecording.js
src/services/breakoutRoomsService.js
src/store/breakoutRoomsStore.js
src/store/pollStore.js
src/utils/webrtc/index.js

Manual backport of #8409 
Tested on stable version

[stable26] Fix some eslint warnings

---

docs/conversation.md
lib/Controller/AvatarController.php

fix(avatar): Return the conversation data and fix the documentation

---

src/components/ChatView.vue

Fix flickering while dragging files on safari

---

CHANGELOG.md
appinfo/info.xml

feat(release): Changelog and version bump for 16.0.0

---

lib/Manager.php
lib/Share/RoomShareProvider.php

Explicit the default sort order by as 'ASC'

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

chore: Bump issue templates

---

CHANGELOG.md
appinfo/info.xml

chore(release): 14.0.10 

---

src/mixins/browserCheck.js

* Fix https://github.com/nextcloud/spreed/issues/8966
---|---
B | A

allow brave

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/AvatarWrapper/AvatarWrapperSmall.vue
src/components/CallView/shared/LocalMediaControls.vue
src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
src/components/TopBar/TopBar.vue

Disable unsupported featues on desktop

---

package-lock.json
package.json

* From https://github.com/nextcloud/nextcloud-vue/pull/3938

Bump @nextcloud/vue to 7.8.5

---

src/components/CallView/shared/VideoBottomBar.spec.js
src/components/CallView/shared/VideoBottomBar.vue
src/test-helpers.js

Grid view | Speaker view
---|---
| Tests covering #9202  |
| --- |
| ![image](https://user-images.githubusercontent.com/93392545/228057345-5200bbc3-7973-4305-b99f-d25c74fb08e5.png) |

Refactor `VideoBottomBar.vue` component

---

.github/workflows/dependabot-approve-merge.yml

fix(CI): Auto approve and merge when it's NOT our interest

---

package-lock.json
package.json

Revert "chore(deps-dev): Bump @nextcloud/webpack-vue-config from 5.4.0 to 5.5.0"

---

.gitignore
lib/Chat/Changelog/Manager.php

String fixes

---

lib/Notification/Notifier.php

Correct the word "administrators".

l10n: Correct word

---

src/components/ConversationIcon.vue

fix(avatar): Prevent 404 avatar request from dummy conversation object

---

docs/capabilities.md
lib/Activity/Provider/Base.php
lib/Capabilities.php
lib/Collaboration/Reference/TalkReferenceProvider.php
lib/Dashboard/TalkWidget.php
lib/Search/ConversationSearch.php
tests/integration/features/integration/dashboard.feature
tests/php/Activity/Provider/BaseTest.php
tests/php/CapabilitiesTest.php

Revert https://github.com/nextcloud/spreed/pull/8805

feat(avatar): Add back avatar capability and use in other components

---

src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/ConversationsList/ConversationsList.vue
src/utils/signaling.js

Manual backport of #9054 
Tested on stable26 version

[stable26] Show index page instead of hard redirect to 404 on chat delete after signaling error 

---

package-lock.json
package.json

chore(deps): bump @nextcloud/vue from 7.9.0 to 7.10.0

---

package-lock.json
package.json

Backport of #9338 
Tested on the Desktop

[stable26] chore(deps): bump @nextcloud/vue from 7.8.5 to 7.10.0

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

chore(release): Bump version to 16.0.3

---

docs/occ.md
lib/Command/Monitor/Room.php

Fix command description

---

src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
src/components/LeftSidebar/SearchBox/SearchBox.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
src/components/NewMessageForm/SimplePollsEditor/PollOption.vue
src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
src/components/TopBar/TopBar.vue
src/views/RoomSelector.vue

* Fix #7531 (all NcButtons have either aria-label attribute or text)
* Fix #7565 (or should it be visible labels? Follow-up: replace native niputs with Vue components)

Accessibility improvements for text fields and buttons

---

package.json

**Current scripts order and types**
(📦 bundling) `build`
(📦 bundling) `dev`
(📦 bundling) `watch`
(🧪 testing) `test`
(🧪 testing) `test:watch`
(🧪 testing) `test:coverage`
(👮 lint) `lint`
(👮 lint) `lint:fix`
**(📦 bundling) `serve`** __<----- the imposter ------__
(👮 lint) `stylelint`
(👮 lint) `stylelint:fix`
**Grouped by type**
(📦 bundling) `build`
(📦 bundling) `dev`
(📦 bundling) `watch`
(📦 bundling) `serve`
(🧪 testing) `test`
(🧪 testing) `test:watch`
(🧪 testing) `test:coverage`
(👮 lint) `lint`
(👮 lint) `lint:fix`
(👮 lint) `stylelint`
(👮 lint) `stylelint:fix`

Update scripts ordering in package.json

---

appinfo/info.xml
lib/Migration/Version16000Date20230502145340.php
lib/Service/ParticipantService.php
tests/integration/features/conversation-2/promotion-demotion.feature

fix(permissions): Reset custom permissions on promotion

---

lib/Config.php

Updates PHPDoc comments in order to make the parameters match their declared types.

Updates lib/Config.php PHPDoc comments.

---

lib/Controller/PageController.php
lib/Files/TemplateLoader.php
lib/PublicShare/TemplateLoader.php
lib/PublicShareAuth/TemplateLoader.php
lib/TInitialState.php
src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue

feat(chat): Highlight own group mentions with primary

---

lib/Controller/AvatarController.php
lib/Service/AvatarService.php

fix(CI): Fix Psalm and CS

---

package-lock.json
package.json

Ref https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.11.2

fix(deps): Update @nextcloud/vue to 7.11.2

---

src/components/ConversationSettings/ConversationAvatarEditor.vue
src/services/conversationsService.js
src/store/conversationsStore.js

Allow to select an emoji + color as avatar [web client]

---

src/components/ConversationIcon.vue
src/components/ConversationSettings/BasicInfo.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

* E.g. Talk 17 Desktop client connecting to a Talk 16 server
---|---

Add capability check around avatar handling

---

.editorconfig

* Ref https://github.com/nextcloud/spreed/pull/9460#discussion_r1187377262

Add .editorconfig with same rules as Nextcloud server

---

package-lock.json
package.json

* Fix https://github.com/nextcloud/nextcloud-vue/releases

fix(deps): Bump @nextcloud/vue to 7.11.4

---

appinfo/info.xml

chore(release): Bump version in info.xml

---

.drone.jsonnet
.drone.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
composer.json
composer.lock

chore(CI): Adjust testing matrix for Nextcloud 27 on stable27

---

.github/dependabot.yml
.github/workflows/update-nextcloud-ocp.yml
appinfo/info.xml
package.json
tests/integration/spreedcheats/appinfo/info.xml

feat(deps): Add Nextcloud 28 support on master

---

.github/workflows/occ-command-documentation.yml

Test command documentation only against 8.2

---

src/components/MediaSettings/VideoBackgroundEditor.vue

fix(mediasettings): Fix broken aria-label

---

README.md
docs/scalability.md
docs/user-requirements.md
mkdocs.yml

chore(docs): Move scalability to admin documentation and improve readme

---

src/components/NewMessage/NewMessageTypingIndicator.vue

fix(TypingIndicator): Actors are only unique by type+id

---

README.md
docs/index.md
mkdocs.yml

feat(docs): Organize the docs overview

---

CHANGELOG.md

- fix(MediaSettings): Fix guests being prompted with login window when blurring background [#9620](https://github.com/nextcloud/spreed/issues/9620)
- fix(TypingIndicator): Actors are only unique by type and id [#9625](https://github.com/nextcloud/spreed/pull/9625)

chore(release): Add changelog for 17.0.0-rc.3

---

.github/workflows/appstore-build-publish.yml
.github/workflows/command-rebase.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-eslint-when-unrelated.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/phpunit-summary-when-unrelated.yml
.github/workflows/psalm.yml
.github/workflows/update-nextcloud-ocp.yml

Fixes failing CI
Manual backport of:
- https://github.com/nextcloud/spreed/pull/9629
- Fixes failing CI because of wrong PHP extensions in `Set up php`
- https://github.com/nextcloud/spreed/pull/9666
- Fixes failing CI because of out of space (there is an alternative solution - use Ubuntu 22.04)
- https://github.com/nextcloud/spreed/pull/9672
- I'm not sure this is actually required...

Fix CI with backports from master

---

docs/user-requirements.md

See https://github.com/nextcloud/documentation/pull/10613

Adjust iOS requirements to iOS 15

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue

* Currently, when user hasn't voted yet in the poll, server returns voters number as 0 always. See reference: https://github.com/nextcloud/spreed/blob/9b525c2229d73e6989a7182949fa45fdbc84f457/lib/Controller/PollController.php#L245-L256
* PR aims to align frontend behavior with backend - hide poll voters number for people who are not moderators/owners/voted
🏚️ Before (admin) | 🏚️ Before (user) | 🏡 After (admin) | 🏡 After (user)
---|---|---|---

fix(Poll) - hide voters number from open poll if user has not voted

---

.github/workflows/appstore-build-publish.yml
.github/workflows/command-rebase.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-eslint-when-unrelated.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/occ-command-documentation.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/phpunit-summary-when-unrelated.yml
.github/workflows/psalm.yml
.github/workflows/update-nextcloud-ocp.yml

[stable26] fix(CI): Backport updated actions

---

CHANGELOG.md

fix(release): Fix changelog date

---

.github/workflows/phpunit-mysql.yml

Ref https://github.com/nextcloud/.github/pull/182

Update phpunit-mysql.yml to latest

---

.github/workflows/phpunit-mysql.yml

[stable27] Update phpunit-mysql.yml

---

.github/workflows/phpunit-mysql.yml

[stable26] Update phpunit-mysql.yml

---

src/components/RightSidebar/Participants/ParticipantsTab.vue

fix(ParticipantsTab) replace v-model for SearchBox component

---

.github/workflows/occ-command-documentation.yml

* Fix https://github.com/nextcloud/spreed/actions/runs/5537774832/jobs/10106979065

fix(CI): Fix occ-command-documentation.yml when running on GARM

---

.drone.jsonnet
.drone.yml

feat(CI): Sign .drone.yml

---

.drone.jsonnet
.drone.yml

[stable27] feat(CI): Sign .drone.yml

---

lib/Activity/Setting.php
lib/BackgroundJob/CheckReferenceIdColumn.php
lib/Chat/AutoComplete/SearchPlugin.php
lib/Chat/ChatManager.php
lib/Chat/Command/Executor.php
lib/Chat/Command/Listener.php
lib/Chat/Command/ShellExecutor.php
lib/Chat/Parser/UserMention.php

The required adjustments have been made to the following namespaces:
- `/lib/Activity`
- `/lib/AppInfo`
- `/lib/BackgroundJob`
- `/lib/Chat`
The improvements:
- Adding return types
- Adding types to properties
- Replacing `strpos` with `str_starts_with` and `str_contains` to improve code readability

Refactor lib [Part1]

---

composer.lock

Revert "Update nextcloud/ocp"

---

.github/workflows/occ-command-documentation.yml

[stable27] fix(CI): Fix occ-command-documentation.yml when running on GARM

---

.github/workflows/occ-command-documentation.yml

[stable26] fix(CI): Fix occ-command-documentation.yml when running on GARM

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 15.0.7

---

src/components/MessagesList/MessagesList.vue

* Follow-up for https://github.com/nextcloud/spreed/pull/10048#discussion_r1272566223
* No visual changes

follow-up(MessageList) - simplify id comparing for messages groups

---

.github/workflows/update-nextcloud-ocp.yml

Deploying https://github.com/nextcloud/.github/pull/201

feat(CI): Create a GitHub issue on nextcloud/ocp update error

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

feat(Message) - support Markdown in messages

---

appinfo/routes/routesChatController.php
docs/capabilities.md
docs/chat.md
lib/BackgroundJob/ChatMessageReminder.php
lib/Capabilities.php
lib/Chat/ChatManager.php
lib/Chat/Notifier.php
lib/Controller/ChatController.php
lib/Notification/Notifier.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/callapi/recording.feature
tests/integration/features/chat-2/reminder.feature
tests/php/CapabilitiesTest.php
tests/php/Chat/ChatManagerTest.php
tests/php/Notification/NotifierTest.php

[stable27] feat(notification): 🔔 API for "Set reminder"

---

.drone.jsonnet
.drone.yml

fix(CI): Sign drone.yml for stable25

---

.github/dependabot.yml

fix(CI): Remove stable24 from dependabot

---

appinfo/info.xml
lib/BackgroundJob/Reminder.php

fix: Run the background job every minute

---

src/components/ConversationSettings/ExpirationSettings.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/MediaDevicesSelector.vue
src/views/FlowPostToConversation.vue

* Fix #10087 
* Full migration to NcSelect
---|---

Replace NcMultiselect with NcSelect

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

[stable27] Release 17.1.0-rc.1

---

lib/Controller/BotController.php

No need to format again after already acquiring the formatted representation.

Fix duplicate bot formatting

---

lib/Chat/ChatManager.php
lib/Collaboration/Collaborators/RoomPlugin.php
lib/Collaboration/Resources/ConversationProvider.php
lib/Controller/RoomController.php
lib/Controller/SignalingController.php
lib/Federation/Notifications.php
lib/Listener/CircleMembershipListener.php
lib/Listener/GroupMembershipListener.php
lib/Listener/RestrictStartingCalls.php
lib/Model/AttendeeMapper.php
lib/Service/AvatarService.php
lib/Service/HostedSignalingServerService.php
lib/Service/ParticipantService.php
lib/Share/Helper/ShareAPIController.php
psalm.xml

Make psalm more aggressive

---

src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/Quote.vue

* Fix #10179 
🏚️ Before | ![image](https://github.com/nextcloud/spreed/assets/93392545/da05a023-2ddd-4f3f-b3e3-321e9fc41ac4) ![image](https://github.com/nextcloud/spreed/assets/93392545/b889f5af-57a8-45cd-8455-e40d6f792f9d)
---|---
🏡 After  | ![Screenshot from 2023-08-16 09-54-45](https://github.com/nextcloud/spreed/assets/93392545/29e48803-d2b0-4c1c-8f03-813243f1f9d8) ![image](https://github.com/nextcloud/spreed/assets/93392545/560ff7db-bbc6-4584-b035-bea22559d9c0)

feat(Message) - update styles for Quote and blockquote tags

---

package-lock.json
package.json
src/components/ConversationIcon.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/ConversationsListVirtual.vue
src/components/LeftSidebar/LeftSidebar.vue

[stable27] Virtual scrolling for conversations list

---

docs/occ.md
lib/Command/Bot/Install.php

fix(bots): Fix option name

---

package-lock.json
package.json

feat(deps): Update @nextcloud/vue to 7.12.3

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 17.1.0 rc.2

---

package-lock.json
package.json

chore(deps): Update @nextcloud/vue to 7.12.3

---

docs/capabilities.md
lib/Capabilities.php
tests/php/CapabilitiesTest.php

feat(capability): Add a capability for messages being markdown

---

appinfo/info.xml
docs/occ.md
lib/AppInfo/Application.php
lib/Command/Bot/Uninstall.php
lib/Command/Developer/UpdateDocs.php
lib/Events/BotUninstallEvent.php
lib/Listener/BotListener.php
lib/Migration/Version18000Date20230504205823.php
lib/Migration/Version18000Date20230824123939.php
lib/Model/BotServerMapper.php

[stable27] feat(bot)!: Ensure bot uniqueness

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 17.1.0 rc.3

---

src/deck.js

fix(Deck) - show conversation name and highlight link in deck integration

---

.github/workflows/integration-pgsql.yml
tests/integration/features/bootstrap/CommandLineTrait.php

fix(CI): Enable APCu in integration tests

---

src/components/LeftSidebar/LeftSidebar.vue

feat(leftSidebar) - Persist the filter status after reload

---

tests/integration/features/bootstrap/CommandLineTrait.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/spreedcheats/lib/SpeechToText/LoremIpsumSpeechToTextProvider.php

fix(CI): Only reset BFP when we changed it

---

.github/workflows/integration-pgsql.yml
.github/workflows/lint-php.yml
.github/workflows/phpunit-mysql.yml

deps(PHP): Try execution against PHP 8.3 beta

---

composer.json
psalm.xml

* Fix CI and dev enviroment with old OCP https://github.com/nextcloud/spreed/pull/10433

fix(dev): Fix autoloader populating dev dependencies

---

src/components/NewMessage/NewMessage.vue
src/store/messagesStore.js
src/store/messagesStore.spec.js

techdebt(NewMessage) - move "addTemporaryMessage" dispatch to the store

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 17.1.0-rc.4

---

src/components/LeftSidebar/LeftSidebar.vue

Change to border in focus

---

src/components/CallView/CallView.vue
src/components/SettingsDialog/SettingsDialog.vue

(cherry picked from commit d43d1d72e827aa60485661377e14a349ec64cac8)
Backport of #10464

[stable25] perf(CallView) - add an option to disable background blur in call

---

src/FilesSidebarCallViewApp.vue
src/FilesSidebarTabApp.vue
src/components/LoadingComponent.vue
src/views/FilesSidebarChatView.vue
webpack.config.js

[stable27] Lazy load files sidebar of Talk

---

package-lock.json
package.json
src/components/MessagesList/MessagesGroup/Message/Message.vue

[stable27] chore(deps): bump nextcloud/vue from 7.12.4 to 7.12.5

---

docs/bots.md

[Docs] Replace ActivityPub mention by ActivityStreams

---

lib/Listener/BotListener.php
lib/Model/BotServerMapper.php
lib/Notification/Notifier.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat/bots.feature
tests/php/Notification/NotifierTest.php

[stable27] fix(bots): Fix notifications of bot messages and reactions

---

lib/Controller/PageController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation/bruteforce-protection.feature

[stable27] fix(page): Decouple the index controller from the executing method

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 16.0.6

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

Release 17.1.1

---

composer.json
composer.lock
vendor-bin/csfixer/composer.lock
vendor-bin/mozart/composer.lock
vendor-bin/phpunit/composer.lock
vendor-bin/psalm/composer.lock

* Adds the dependency already to avoid conflicts with dependabot updates
* Ref https://github.com/CuyZ/Valinor
* Will be used by https://github.com/nextcloud/spreed/pull/10608

deps: Add Valinor as dependency

---

composer.json
lib/Capabilities.php

fix(docs): Add typing to capabilities

---

.github/workflows/integration-pgsql.yml
.github/workflows/phpunit-mysql.yml

PHP 8.3 is now allowed by server

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue

[stable27] - Mentions in forwarded messages

---

lib/Federation/BackendNotifier.php
lib/Federation/CloudFederationProviderTalk.php
lib/Federation/FederationManager.php

fix(federation): Use constants for magic strings

---

.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/lint-eslint.yml
.github/workflows/node.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
psalm.xml

fix(CI): Fix CI on pushes

---

.readthedocs.yaml
Makefile

Before | After
---|---
Ref 
https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings
https://docs.readthedocs.io/en/stable/config-file/v2.html#mkdocs

fix(docs): Add readthedocs config to try fixing the build

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
src/components/MessagesList/MessagesList.vue

* Fix #10765
| ![image](https://github.com/nextcloud/spreed/assets/93392545/0291c5b3-85e6-447f-bad9-419a280e56fd)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/7f28f4d1-8e63-4a64-866e-fd8d70b0b2a6)       |

fix(Mention): show correct size according to font

---

lib/AppInfo/Application.php
lib/Chat/Changelog/Listener.php
lib/Chat/Listener.php
lib/Events/AParticipantModifiedEvent.php
lib/Listener/BotListener.php
lib/Listener/RestrictStartingCalls.php
lib/Notification/Listener.php
lib/Service/BotService.php
lib/Status/Listener.php
tests/php/Listener/RestrictStartingCallsTest.php

techdebt(events): Migrate to new events

---

src/utils/signaling.js

[stable26] Fix "silent" parameter not sent again when reconnecting

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
src/components/MessagesList/MessagesList.vue

Backport of #10767
Conflict was from missing "remotes" case in mention handling

[stable27] fix(Mention): show correct size according to font

---

openapi.json
vendor-bin/openapi-extractor/composer.lock

Latest version that fixes problems with `array<empty>`.

chore(deps): Update openapi-extractor

---

.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php.yml
.github/workflows/node.yml
.github/workflows/occ-command-documentation.yml
.github/workflows/openapi.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/psalm.yml

ci: Turn off builds for pushes and merges to master/stable*

---

lib/Activity/Listener.php
lib/AppInfo/Application.php
lib/Notification/Listener.php
lib/PublicShareAuth/Listener.php

techdebt(events): Migrate more event handling to `registerEventListener()` and typed events

---

jest.config.js
package-lock.json
package.json
src/App.vue
src/FilesSidebarCallViewApp.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthRequestPasswordButton.vue
src/PublicShareSidebar.vue
src/__mocks__/svg.js
src/components/ConversationSettings/ConversationAvatarEditor.vue
src/components/MediaSettings/VideoBackgroundEditor.vue
src/components/NewMessage/NewMessage.vue
src/components/NewMessage/NewMessageAttachments.vue
src/components/SettingsDialog/SettingsDialog.vue
src/main.js
src/mainAdminSettings.js
src/mainFilesSidebar.js
src/mainPublicShareAuthSidebar.js
src/mainPublicShareSidebar.js
src/mainRecording.js

feat(deps): Bump @nextcloud/dialogs to 5.0.0-beta

---

docs/chat.md
lib/Chat/ChatManager.php
lib/Chat/SystemMessage/Listener.php
tests/php/Chat/SystemMessage/ListenerTest.php

feat(attachments): Allow sending captions as silent messages

---

lib/AppInfo/Application.php
lib/Collaboration/Collaborators/Listener.php

fix(event): Migrate to typed event AutoCompleteFilterEvent

---

src/components/AvatarWrapper/AvatarWrapper.vue

* Fix #10885
| ![image](https://github.com/nextcloud/spreed/assets/93392545/d860c839-9ad5-4133-a7b2-078f41337901)            | ![image](https://github.com/nextcloud/spreed/assets/93392545/d4da0aa0-4a6b-4d81-951c-97bd3fbbea52)      |

fix(AvatarWrapper): fix size for icon-changelog in chat

---

src/components/LeftSidebar/LeftSidebar.vue

[stable27] fix(LeftSidebar): replace three-dot icon with chat-plus icon

---

tests/stubs/oc_comments_manager.php

* Noticed in https://github.com/nextcloud/spreed/actions/runs/6897213560/job/18764917282

fix(CI): Fix psalm missing chache() on the stub

---

src/components/NewMessage/NewMessage.vue

Fix new message input appearance

---

.github/workflows/update-nextcloud-ocp-approve-merge.yml

Try to automatically merge OCP updates

---

.github/workflows/update-nextcloud-ocp-approve-merge.yml

[stable26] feat(CI): Try to automatically merge OCP updates

---

.github/workflows/update-nextcloud-ocp-approve-merge.yml

[stable27] feat(CI): Try to automatically merge OCP updates

---

docs/call.md
lib/Controller/CallController.php
lib/Service/ParticipantService.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/callapi/notifications.feature

[stable27] fix(call): Handle DoesNotExistException when ringing an attendee

---

src/components/LeftSidebar/LeftSidebar.vue

* Fix #10926
| ![image](https://github.com/nextcloud/spreed/assets/84044328/705bc8d1-438a-4a9a-8c36-6ea908bb350b)       | ![image](https://github.com/nextcloud/spreed/assets/84044328/1b7c21ca-1329-4d34-a494-dc8e51729a74)   |

feat(LeftSidebar): Always show "create a new conversation" item

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

* Fix #10083
| ![grafik](https://github.com/nextcloud/spreed/assets/213943/fd31dfd2-17f5-47aa-896b-92d96ff57e3b) | ![grafik](https://github.com/nextcloud/spreed/assets/213943/50bffa73-3f06-47fd-908a-94cc020d6982) |

fix(settings): Remove notification settings for guests

---

src/components/ConversationSettings/ConversationSettingsDialog.vue

[stable27] fix(settings): Remove notification settings for guests

---

src/components/AdminSettings/HostedSignalingServer.vue
src/components/AdminSettings/RecordingServer.vue
src/components/AdminSettings/RecordingServers.vue
src/components/AdminSettings/SIPBridge.vue
src/components/AdminSettings/SignalingServer.vue
src/components/AdminSettings/SignalingServers.vue
src/components/AdminSettings/TurnServer.vue

* Fix #10972
Bug isn't reproducible for me, so did this blindfolded.
Please verify if there are any broken styles left
| ![image](https://github.com/nextcloud/spreed/assets/93392545/fc7cc7c9-9537-4db7-8e37-c1f6b0beeb9b)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/866ca5d9-e9a5-404f-ab90-c61afc93266e)        |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/39a23a89-b7c8-4c1f-abd8-8c719f84c770) | ![image](https://github.com/nextcloud/spreed/assets/93392545/1ad29959-5bef-46e7-a007-02d2eb726796) |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/95501122-3189-4495-88d5-e0b50272d8eb) | ![image](https://github.com/nextcloud/spreed/assets/93392545/ed5ce41b-950f-44c8-abcc-a282c9a91138) |
| …

fix(AdminSettings): fix style specificity

---

.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/occ-command-documentation.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
composer.json
composer.lock

chore(CI): Adjust testing matrix for Nextcloud 28 on stable28

---

.github/workflows/update-nextcloud-ocp.yml
appinfo/info.xml
package-lock.json
package.json
tests/integration/spreedcheats/appinfo/info.xml

feat(deps): Add Nextcloud 29 support on main

---

src/components/TopBar/CallButton.vue

Fix use of blockCalls in vue template

---

src/components/CallView/CallView.vue
src/components/CallView/shared/ViewerOverlayCallView.vue

* Fix #9445
| ![image](https://github.com/nextcloud/spreed/assets/84044328/ac430c6c-074f-4a04-9a1d-e42d8d0a2245)       | ![image](https://github.com/nextcloud/spreed/assets/84044328/7ed8b3ff-3575-4640-9896-c1175cf59a72)    |
TODO

feat(ViewerOverlayCallView): Add screensharing support

---

src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue

I should "git add" before I "git commit"

---

src/components/LeftSidebar/LeftSidebar.vue
src/components/LeftSidebar/SearchBox/SearchBox.vue

Remove label from talk search input

---

src/services/participantsService.js

* Fix #11059 
* Steps to reproduce in the ticket
* Replaces #11061

fix(chat): Only load current absence not future ones

---

src/components/NewMessage/NewMessage.vue
src/components/Quote.vue

* Fix #11108
| ![image](https://github.com/nextcloud/spreed/assets/84044328/178115e4-2b8d-42a9-a3f7-e43bf2f10006)   | ![image](https://github.com/nextcloud/spreed/assets/84044328/b0bb7e70-a0fa-4e70-bc03-691f273332da)      |

Fix file share with caption quote reply

---

src/composables/useActiveSession.js

fix(activeSession): remove toast message

---

lib/Command/Developer/UpdateDocs.php

fix(OCC): Avoid using \OC::$server

---

lib/Config.php
lib/Controller/SignalingController.php
lib/Deck/DeckPluginLoader.php
lib/Flow/Operation.php
lib/Maps/MapsPluginLoader.php
lib/MatterbridgeManager.php
lib/Migration/FixNamespaceInDatabaseTables.php
lib/Recording/BackendNotifier.php
lib/Room.php
lib/Search/ConversationSearch.php
lib/Search/MessageSearch.php
lib/Service/CommandService.php
lib/Settings/Admin/AdminSettings.php
lib/Signaling/BackendNotifier.php

fix(matterbridge): Simplify "string starts with" check

---

lib/Chat/Notifier.php
lib/Federation/FederationManager.php
lib/Service/RoomService.php
tests/php/Chat/NotifierTest.php

fix(API): Remove unused member variables

---

lib/Middleware/CanUseTalkMiddleware.php
lib/Middleware/InjectionMiddleware.php

fix(middleware): Add types as per OCP class we extend

---

docs/chat.md
lib/Chat/ChatManager.php
lib/Chat/ReactionManager.php
lib/Chat/SystemMessage/Listener.php
src/components/NewMessage/NewMessage.vue
src/store/fileUploadStore.js
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/SharingContext.php
tests/integration/features/chat-1/file-share.feature
tests/integration/features/chat-1/notifications.feature
tests/php/Chat/ChatManagerTest.php
tests/php/Chat/SystemMessage/ListenerTest.php

* allows to reply to other messages with file share
* Fix #11239 
|  🏡 Flow |
|------------|
---

fix(shares): reply to message with attachments

---

src/components/LeftSidebar/LeftSidebar.spec.js
src/components/LeftSidebar/LeftSidebar.vue
src/composables/useHashCheck.js

follow-up: adjust talkHash store

---

src/components/TopBar/TopBar.vue

* Missing definition of isModeratorOrUser 😁

Fix(TopBar): Add isModeratorOrUser in the setup 

---

src/components/ConversationSettings/BasicInfo.vue
src/components/ConversationSettings/EditableTextField.vue
src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue

* Fix #11369 
| ![image](https://github.com/nextcloud/spreed/assets/93392545/d7852923-ffa1-4b4b-b432-0074467c682d)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/01d2ff70-44f7-42b8-bbf5-21b160f2dff2)     |

fix(conversation): make description multi-line

---

lib/Share/RoomShareProvider.php

- See https://github.com/nextcloud/server/pull/42638

also filter by storage when getting shares in folder

---

lib/Controller/RoomController.php

fix(theming): Change the talk hash on user theming change

---

lib/Controller/FederationController.php
openapi-federation.json
openapi-full.json

fix(docs): Generate OpenAPI docs for federation so developers can read it

---

src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
src/components/TopBar/TopBarMenu.vue
src/store/breakoutRoomsStore.js
src/store/callViewStore.js
src/store/conversationsStore.js
src/store/participantsStore.js
src/store/participantsStore.spec.js

Manual backport of:
* #11394
* #11443
Tested against stable28

[stable28] enh(participants): extract and reuse patchParticipants action

---

src/components/LeftSidebar/ConversationsList/Conversation.vue

* Apply solution from https://github.com/nextcloud-libraries/nextcloud-vue/pull/3715#issuecomment-1413718146
| Ellpsized names | Short names |

fix(Conversation): always show a native title

---

src/App.vue

* Part of #11279
* Based on #11459

feat(Federation): join conversation after accepting the invitation 

---

.github/workflows/phpunit-pgsql.yml
codecov.yml

feat(CI): Test codecov

---

.github/workflows/phpunit-pgsql.yml
codecov.yml

Reverts nextcloud/spreed#11485

Revert "feat(CI): Test codecov"

---

src/components/NewMessage/NewMessage.vue

fix(Poll): hide poll creation in Note to Self

---

.github/workflows/lint-eslint.yml

fix(CI): Fix queue of eslint jobs

---

.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php.yml
.github/workflows/node.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/update-nextcloud-ocp-approve-merge.yml

[stable28] feat(CI): Utilize the "low" pool

---

lib/Controller/FederationController.php
lib/Controller/RoomController.php
lib/Federation/FederationManager.php
lib/Notification/Notifier.php
openapi-federation.json
openapi-full.json
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/federation/invite.feature

* Ref https://github.com/nextcloud/spreed/issues/11278#issuecomment-1922211257

fix(federation): Fix accepting or declining an invite multiple times

---

src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue

* Ref #11494 
| ![image](https://github.com/nextcloud/spreed/assets/93392545/4f2e6c4c-19b8-4306-9bcb-cecde325dca2)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/eaf78067-0c5a-4341-bdbb-9d6cf66989c9)        |

chore(breakout): migrate to NcInputField to support number type

---

lib/Controller/SignalingController.php

fix(hpb): Log the HPB request when we log

---

.github/workflows/block-unconventional-commits.yml

Ref https://github.com/nextcloud/.github/pull/302

chore: Create block-unconventional-commits.yml

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.spec.js
src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue

* Fix #7139
Ordered historically
| 🏚️ Button | 🏡 Modal |
| ![image](https://github.com/nextcloud/spreed/assets/84044328/6f814725-084c-4371-9742-f63b748ce5a3)       |![image](https://github.com/nextcloud/spreed/assets/84044328/2a46f2c2-3a9d-46c1-bf33-db954f4daec7)  |
TODO:
- Guest icon should not have "G" if it refers to "guest"

feat(Reactions): add All button

---

src/components/LeftSidebar/LeftSidebar.vue

| ![image](https://github.com/nextcloud/spreed/assets/84044328/4af88d1b-c2b7-40db-84d4-3a8682df67ec)       | ![image](https://github.com/nextcloud/spreed/assets/84044328/a8f3a273-7b4a-4bc5-9f52-90e0fda98fc8)        |

chore(LefSidebard): Align press state

---

src/store/participantsStore.js

fix: Log errors when joining a conversation as error

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/ChatView.vue
src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/LeftSidebar/LeftSidebar.vue
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
src/components/MessagesList/MessagesGroup/MessagesGroup.vue
src/components/NewMessage/NewMessage.vue
src/components/NewMessage/NewMessageTypingIndicator.vue
src/components/Quote.vue
src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue
src/services/conversationsService.js
src/store/actorStore.js
src/store/conversationsStore.js
src/store/messagesStore.js
src/store/messagesStore.spec.js
src/store/participantsStore.js

* Fix debug way to add federated user (forgot to change `remotes`)
* Rely on constants, where possible / relevant
* Move common checks of actorType to getters

fix: provide actor source from constants, add actorStore getters to check if user/guest

---

lib/Federation/Proxy/TalkV1/Controller/AvatarController.php
lib/Federation/Proxy/TalkV1/Controller/ChatController.php
lib/Federation/Proxy/TalkV1/ProxyRequest.php

fix(federation): Improve logging

---

lib/Federation/Authenticator.php

* Fix authentication with email addresses

fix(federation): Don't continue reading headers when it's not federation

---

lib/Chat/Parser/SystemMessage.php

fix(federation): Fix "You accepted the invitation" system message

---

.github/workflows/openapi.yml
composer.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

* Fix openapi typescript models are out of sync already

fix(openapi): Make sure typescript models are updated

---

src/components/ConversationSettings/DangerZone.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

* Fix translation introduced in https://github.com/nextcloud/spreed/commit/c21fa0e650228c20acebfea0af1f7c11265dab5f

translate: replace capital letter in 'Delete conversation'

---

lib/Collaboration/Collaborators/Listener.php
lib/Collaboration/Collaborators/RoomPlugin.php
lib/Command/Bot/Setup.php
lib/Controller/BotController.php
lib/Flow/Operation.php
lib/Search/CurrentMessageSearch.php
lib/Search/MessageSearch.php
lib/Share/RoomShareProvider.php

fix(federation): Don't allow things in proxy conversations :)

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/VideoVue.vue
src/components/ConversationIcon.vue
src/components/MediaSettings/MediaSettings.vue
src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
src/components/MessagesList/MessagesGroup/MessagesGroup.vue
src/components/NewMessage/NewMessage.vue
src/components/NewMessage/NewMessageAbsenceInfo.vue
src/components/NewMessage/NewMessageTypingIndicator.vue
src/components/PollViewer/PollViewer.vue
src/components/PollViewer/PollVotersDetails.vue
src/components/Quote.vue
src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
src/services/avatarService.ts
src/services/conversationsService.js
src/store/conversationsStore.js
src/types/index.ts

* Move avatar endpoints to TS
* Provide generic functions to construct conversation / userproxy avatars
* Apply in components
-- | --

fix(federation): proxy user avatars

---

.github/workflows/integration-oci.yml
.github/workflows/phpunit-oci.yml

Run OCI tests again on `ubuntu-latest` after image change.

Run OCI tests on ubuntu-latest again

---

lib/Chat/Parser/SystemMessage.php
lib/Federation/Proxy/TalkV1/ProxyRequest.php

fix(federation): Proxy all requests with the users language

---

lib/Chat/Changelog/Manager.php

feat(changelog): Add "Talk updates" entries for Talk 19

---

lib/Command/User/TransferOwnership.php

The host does not get notified and should not trust a server sending a proxied invite for now.
Fix #11915

fix(federation): Don't try to transfer membership in federated rooms

---

lib/Chat/ChatManager.php
lib/Chat/Parser/SystemMessage.php
lib/Chat/SystemMessage/Listener.php
lib/Service/AttachmentService.php
lib/Service/RecordingService.php

Replaces https://github.com/nextcloud/spreed/pull/11696 because it is not possible to properly type this throughout the whole codebase.

fix(ChatManager): Add missing verbs

---

.github/dependabot.yml
.github/workflows/update-nextcloud-ocp.yml
appinfo/info.xml
package-lock.json
package.json
tests/integration/spreedcheats/appinfo/info.xml

feat(deps): Add Nextcloud 30 support on main

---

.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/occ-command-documentation.yml
composer.json
composer.lock

chore(CI): Adjust testing matrix for Nextcloud 29 on stable29

---

appinfo/routes/routesRoomController.php
openapi-backend-sipbridge.json
openapi-full.json
src/types/openapi/openapi-backend-sipbridge.ts
src/types/openapi/openapi-full.ts

fix(openapi): Make the operation-id unique

---

lib/Controller/PageController.php
tests/integration/features/conversation-1/bruteforce-protection.feature

Reverts nextcloud/spreed#12039

Revert "[stable29] fix(frontpage): Don't bruteforce protect "undefined""

---

lib/Controller/PageController.php
tests/integration/features/conversation-1/bruteforce-protection.feature

Reverts nextcloud/spreed#12029

Revert "fix(frontpage): Don't bruteforce protect "undefined""

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

- fix(conversation): Fix error when adding participants while creating a conversation [#12057](https://github.com/nextcloud/spreed/issues/12057)
- fix(conversation): Fix missing icon in conversation settings for file conversations [#12051](https://github.com/nextcloud/spreed/issues/12051)

Release 18.0.7

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

- fix(conversation): Fix error when adding participants while creating a conversation [#12059](https://github.com/nextcloud/spreed/issues/12059)
- fix(conversation): Fix missing icon in conversation settings for file conversations [#12052](https://github.com/nextcloud/spreed/issues/12052)

Release 17.1.8

---

src/components/CallView/shared/VideoVue.vue

fix(VideoVue): fix bottom bar not clickable

---

src/utils/formattedTime.ts

so translations can be correct

fix: lobby timer translation

---

src/components/ConversationSettings/LobbySettings.vue

fix: correct translation

---

.github/ISSUE_TEMPLATE/1_bug_report.md
.github/ISSUE_TEMPLATE/2_feature_request.md

- Adjusted some versions
- Asking for Nextcloud version on feature requests

chore(github): Adjust feature request and bug report templates

---

lib/Signaling/BackendNotifier.php

- Fixes https://github.com/nextcloud/spreed/actions/runs/8812177450/job/24187380047?pr=12197#step:14:1150

fix(signaling): Make alluserids more reliable for testing

---

.github/workflows/appstore-build-publish.yml
.github/workflows/block-unconventional-commits.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/openapi.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml
.github/workflows/psalm.yml
.github/workflows/reuse.yml
.github/workflows/update-nextcloud-ocp-approve-merge.yml
.github/workflows/update-nextcloud-ocp.yml

~~Automated update of the node.yml workflow from https://github.com/nextcloud/.github~~
Updated with a script: https://github.com/nextcloud/.github#update-workflows-with-a-script

Updating all *.yml workflows from template

---

.github/workflows/appstore-build-publish.yml

Reverts nextcloud/spreed#12070

Revert "chore(release): Fix build action while there is no latest-29 package"

---

lib/Share/Helper/ShareAPIController.php

- Server ref https://github.com/nextcloud/server/pull/44912/commits/1cf2bed55c9f3cf142fd2beacffce31d36d10401 which caused an issue for talk. So also changing it here to avoid future issues

fix(API): Avoid changing variable types

---

tests/integration/features/bootstrap/FeatureContext.php

Now that we want the error, let's see how often we have to run it.

fix: Debugging failing integration tests

---

src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue

* Regression from #12243 
* To check: RoomSelector.spec.js output before/after

fix(conversations): bring back missing prop

---

lib/Chat/Parser/SystemMessage.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-2/poll.feature

fix(polls): Remove actor info from system message

---

package-lock.json
package.json
src/App.vue
src/FilesSidebarCallViewApp.vue
src/PublicShareSidebar.vue

Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>### ☑️ Resolves
* Ref #9448
No changes

fix(prevent-unload): replace PreventUnload with native browser functionality

---

src/App.vue
src/components/LeftSidebar/LeftSidebar.vue
src/components/TopBar/TopBarMenu.vue

fix(vue3): remove v-on.native modifier

---

src/components/TopBar/TopBar.vue

* Fix styles for TopBar
* in Vue2, attributes haven't been passed to the components with falsy value
-- | --

fix(style): don't pass data-theme-dark

---

lib/Controller/PageController.php
lib/Controller/RecordingController.php

fix(recording): Stop broken recording backend

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
src/components/NewMessage/NewMessage.vue
src/components/Quote.vue
src/composables/__tests__/useMessageInfo.spec.js
src/composables/useMessageInfo.js

* Follow-up https://github.com/nextcloud/spreed/pull/12395#discussion_r1618771274

fix(chat): refactor Quote component, fix reactivity

---

.github/workflows/appstore-build-publish.yml
.github/workflows/block-unconventional-commits.yml
.github/workflows/fixup.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-info-xml.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/occ-command-documentation.yml
.github/workflows/openapi.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml
.github/workflows/psalm.yml
.github/workflows/reuse.yml
.github/workflows/update-nextcloud-ocp.yml

Automated update of the lint-eslint.yml workflow from https://github.com/nextcloud/.github

chore(CI): Updating lint-eslint.yml workflow from template

---

lib/Service/BotService.php

* Ref https://github.com/nextcloud/call_summary_bot/pull/68

fix(bots): Allow bots with self-signed certificates

---

src/store/messagesStore.js
src/store/messagesStore.spec.js

* Fix issue with outdated quotes
-- | --

fix(messageStore): update edited parent for all messages

---

src/components/MessagesList/MessagesList.vue
src/store/messagesStore.js
src/store/messagesStore.spec.js

* Forwardport of #12465
* Fix 'loading chat from beggining'

fix(MessagesList): keep token consistent during async methods

---

src/store/messagesStore.js

fix(messagesStore): add missing `markdown` in temporary message object

---

lib/Service/RecordingService.php
tests/integration/features/callapi/recording.feature

feat: transcripts are now avaliable as .md files

---

lib/ResponseDefinitions.php
openapi-backend-sipbridge.json
openapi-federation.json
openapi-full.json
openapi.json
src/types/openapi/openapi-backend-sipbridge.ts
src/types/openapi/openapi-federation.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

Mirror of https://github.com/nextcloud/server/pull/45424.

feat(OpenAPI): Add more rich object fields

---

src/components/TopBar/TopBarMenu.vue

* Fix #12399 
* If hand is raised, and participant started to speak, 3-seconds timer is started;
* If person still speaks, remove the hand after timeout;
* If person stopped speak sooner (e.g. unintended noise registration, or mic check) - stop the timer, decrease the timeout
* Thus, speaking time is accumulated, so 3 intervals with speaking each 1 second long would also remove the raised hand
🏡 After
https://github.com/nextcloud/spreed/assets/88997516/adb5654a-bd38-467e-aad9-d270d797898d

feat(call): auto lower hand on speaking for 3s

---

src/components/MessagesList/MessagesGroup/Message/Message.spec.js
src/components/MessagesList/MessagesGroup/Message/Message.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
src/components/NewMessage/NewMessageUploadEditor.vue
src/components/Quote.vue
src/components/RightSidebar/SharedItems/SharedItems.vue

Fix: replace v-bind with object prop passing

---

lib/Command/Bot/Uninstall.php
tests/integration/features/chat-1/bots.feature
tests/integration/run-docker.sh

Shows an error msg when missing args

---

src/components/TopBar/TopBar.vue

[stable29] style(TopBar): prove contrast text color to unread messages counter

---

package-lock.json
package.json

[stable29] chore(deps): bump @nextcloud/vue from 8.11.3 to ^8.13.0

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue

fix(Reactions): improve styling in popover

---

lib/Migration/Version2001Date20170707115443.php
lib/Migration/Version2001Date20171026134605.php
lib/Migration/Version2001Date20180103144447.php
psalm.xml
tests/psalm-baseline.xml

fix(deps): Use less 3rdparty dependencies by comparing `IDBConnection::PLATFORM_*`

---

src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue

fix(MessagesSystemGroup): separate messages with different actors

---

src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
src/components/MessagesList/MessagesGroup/MessagesSystemGroup.spec.js
src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue

Added tests are designated only for combined system message rendering

Fix(GroupSystemMessages): add tests and adjust conditions for combined messages

---

lib/Chat/ChatManager.php
lib/Collaboration/Reference/TalkReferenceProvider.php
lib/Exceptions/InvalidRoomException.php
lib/Model/ProxyCacheMessageMapper.php
lib/Notification/Notifier.php
tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
tests/php/Service/ProxyCacheMessageServiceTest.php

fix(chat): Fix missing reference information for federated message links

---

src/components/NewMessage/NewMessage.vue
src/components/NewMessage/NewMessageAttachments.vue
src/components/Quote.vue

feat(filepicker): add button to show smart picker

---

appinfo/info.xml
lib/Migration/Version19000Date20240709183938.php

fix(federation): Also fix room::remote_server and pcm::remote_server_url

---

package-lock.json
package.json

* Fix files upload (PUT request has been incorrectly parsed on `1.4.0` - `1.4.1`)

chore(deps): bump @nextcloud/upload library from 1.4.1 to 1.4.2

---

lib/Federation/Proxy/TalkV1/UserConverter.php
lib/Model/SelectHelper.php
lib/Model/SessionMapper.php
lib/Notification/FederationChatNotifier.php

* Follow-up 3 to #12687 
- Mention a federated user (with https) or reply to one
- User has a notification
- No notification

fix(federation): Fix message parameters after adjusting https handling

---

src/components/MessagesList/MessagesList.vue
src/store/messagesStore.js
src/utils/debugTimer.ts

debug: add time measurement for chat requests

---

.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml

fix(CI): Fix mariadb and mysql options in integration test

---

lib/Controller/BanController.php
lib/Listener/DisplayNameListener.php
lib/Migration/Version20000Date20240621150333.php
lib/Migration/Version20000Date20240621150334.php
lib/Migration/Version20000Date20240621150335.php
lib/Model/Ban.php
lib/Model/BanMapper.php
lib/ResponseDefinitions.php
lib/Service/BanService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/conversation-1/ban.feature

fix(ban): Renamed banned to bannedActor

---

src/components/CallView/CallView.vue
src/components/CallView/shared/VideoBottomBar.vue
src/components/CallView/shared/VideoVue.vue

* Fix #12631
🏚️ Before (hovered)| 🏡 After (hovered)
-- | --
---

fix(CallView): freeze promoted video on hover

---

src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
src/components/MessagesList/MessagesGroup/MessagesGroup.vue
src/components/Quote.vue
src/composables/__tests__/useMessageInfo.spec.js
src/composables/useMessageInfo.js

fix: add edited and server hints to author name in quotes

---

src/components/ChatView.vue
src/components/MessagesList/MessagesList.vue

fix: refactor messages list update in watchers

---

appinfo/info.xml
lib/Migration/Version18000Date20231024141627.php
lib/Migration/Version20000Date20240716190335.php

feat: Added (user,state) index for talk_invitations

---

.github/workflows/appstore-build-publish.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/openapi.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml
.github/workflows/psalm.yml
.github/workflows/update-nextcloud-ocp.yml

Backport of #12748
`reuse.yml` was a conflicting file

[stable29] chore: update workflow templates

---

.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-sqlite.yml

- Fixes https://github.com/nextcloud/spreed/issues/10484

fix(ci): Use apcu in all integration tests

---

lib/Controller/BanController.php
lib/Service/BanService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

fix(ban): Validate actor types on banning

---

lib/Controller/RoomController.php
lib/Controller/SignalingController.php
lib/Middleware/InjectionMiddleware.php
lib/Model/BanMapper.php
lib/Service/BanService.php
lib/TalkSession.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation-1/ban.feature
tests/php/Controller/SignalingControllerTest.php

Ban guests by ip

---

lib/Controller/ChatController.php
lib/ResponseDefinitions.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

- The attributes are optional (and some additionally nullable)

fix(chat): Fix OpenAPI optional attributes on mentions

---

.gitignore

`phpserver_fed_real.log` was added in #12785

fix(tests): Ignore all integration server logs

---

lib/Controller/ChatController.php
lib/ResponseDefinitions.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

[stable29] fix(chat): Fix OpenAPI optional attributes 

---

tests/integration/features/bootstrap/FeatureContext.php

Follow up to https://github.com/nextcloud/spreed/pull/12785
Shame :facepalm:

tests: Fix "using server" step definition

---

.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
composer.lock
tests/integration/features/bootstrap/FeatureContext.php

[stable27] Update nextcloud/ocp dependency

---

lib/Command/Developer/UpdateDocs.php
lib/Controller/RecordingController.php
lib/Controller/SignalingController.php
lib/MatterbridgeManager.php
tests/integration/features/bootstrap/CommandLineTrait.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/SharingContext.php
tests/php/Service/CertificateServiceTest.php

* Found by https://github.com/nextcloud/coding-standard/issues/23

fix(cs): Use single quotes for simple strings

---

src/components/ConversationIcon.vue

fix(ConversationIcon): show avatar thumbnail for former 1-1 conversations

---

src/components/MediaSettings/MediaSettings.vue
src/composables/useId.ts

fix(MediaSettings): provide accessible heading

---

src/components/RightSidebar/Participants/Participant.vue

fix(Participant): remove unneeded separator

---

tests/integration/features/federation/chat.feature

tests: Disable flaky test-step

---

src/components/AvatarWrapper/AvatarWrapper.vue
src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/VideoBottomBar.vue
src/components/CallView/shared/VideoVue.spec.js
src/components/CallView/shared/VideoVue.vue

Refactor: clean call view styles and use CSS variables.

---

.github/dependabot.yml
.github/workflows/update-nextcloud-ocp.yml
appinfo/info.xml
package-lock.json
package.json
tests/integration/spreedcheats/appinfo/info.xml

feat(deps): Add Nextcloud 31 support on main

---

src/components/GuestWelcomeWindow.vue
src/components/LobbyScreen.vue
src/components/SetGuestUsername.vue

* Fix #12772
-- | --
Lobby | ![image](https://github.com/user-attachments/assets/1f77729a-380a-4bf2-bdae-90ff06e54499)
Sidebar | ![image](https://github.com/user-attachments/assets/e9850070-5e11-4f85-95d6-d557b8eba3c8)

feat: add login button to guest welcome window

---

.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml

Fixes installing the real fed server in tests:
https://github.com/nextcloud/spreed/actions/runs/10400081376/job/28800014421?pr=12963#step:14:44

ci: Also install sqlite and pdo_sqlite for now

---

src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
src/components/RightSidebar/Participants/ParticipantsTab.vue

* Follow-up to #12819
🏡 After
| --

fix(Participant): design follow-ups

---

.eslintignore
src/services/conversationsService.js

chore(eslint): ignore openapi generated files

---

CHANGELOG.md
appinfo/info.xml
package-lock.json
package.json

- Adjust conversation list density [#13013](https://github.com/nextcloud/spreed/issues/13013)

Release 20.0.0 rc.2

---

lib/Chat/MessageParser.php
lib/Controller/RoomController.php
lib/Service/BotService.php
lib/Service/ParticipantService.php
lib/Service/RoomService.php
tests/psalm-baseline.xml

fix: Fix some minor things found by stan

---

package-lock.json
package.json
src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue

feat(FilePreview): add blurhash support

---

openapi-administration.json
openapi-backend-sipbridge.json
openapi-bots.json
openapi-federation.json
openapi-full.json
openapi.json
src/types/index.ts
src/types/openapi/openapi-administration.ts
src/types/openapi/openapi-backend-sipbridge.ts
src/types/openapi/openapi-bots.ts
src/types/openapi/openapi-federation.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
vendor-bin/openapi-extractor/composer.json
vendor-bin/openapi-extractor/composer.lock

chore(deps): Update openapi-extractor to v1.0.0

---

src/components/GuestWelcomeWindow.vue

* Fix extra padding and margin
* Fix description exceeding box.
-- | --

fix(GuestWelcomeWindow): fix padding and text clipping

---

src/components/CallView/CallView.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/PresenterOverlay.vue
src/components/CallView/shared/VideoVue.vue

Popover on one of the buttons (video or screenshare) couldn't fit because there are popovers or menu below.

feat(Call): show presenter overlay for local screenshare

---

src/components/CallView/shared/LocalVideo.vue

Rebase of #12890 was a bit messed up 🙈

fix: remove rebase bug

---

src/components/TopBar/TasksCounter.vue

* Regression from #13122 
-- | --

fix(TasksCounter): fix translations

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
src/store/fileUploadStore.js

[stable29] fix(fileUpload): don't share files in parallel, harden checks

---

src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
src/components/MessagesList/MessagesGroup/MessagesGroup.vue
src/components/Quote.vue

* Fix concatted author information (if there is too much on a little space)
-- | --

fix(MessagesGroup): concat actor information

---

lib/Command/Bot/Remove.php
lib/Service/BanService.php
tests/integration/features/bootstrap/FeatureContext.php
vendor-bin/csfixer/composer.json
vendor-bin/csfixer/composer.lock
vendor-bin/mozart/composer.lock
vendor-bin/phpunit/composer.json
vendor-bin/phpunit/composer.lock
vendor-bin/psalm/composer.json
vendor-bin/psalm/composer.lock

chore: Update dev dependencies

---

lib/Notification/Notifier.php

* Follow up to #13200 
* Fixes Red CI

fix(notification): Fix missing cast of id to string

---

src/App.vue
src/components/MessagesList/MessagesList.vue
src/components/TopBar/CallTime.vue
src/composables/useActiveSession.js
src/composables/useDocumentVisibility.ts
src/composables/useGetParticipants.js

fix: rename useWindowVisibility to useDocumentVisibility

---

src/views/MainView.vue

* Fix #12649
-- | --
Transition effect | Instant change

fix: remove transition for Chat <-> Call views

---

src/components/ConversationSettings/ConversationAvatarEditor.vue

fix: add advanced fields to the color picker

---

composer.lock
lib/SetupCheck/BackgroundBlurLoading.php
tests/psalm-baseline.xml

[main] Update nextcloud/ocp dependency

---

lib/Notification/Notifier.php

fix(notifications): Fix last type of subject parameters

---

src/components/LeftSidebar/ConversationsList/Conversation.spec.js
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
src/composables/useConversationInfo.js
src/utils/getMessageIcon.ts

* Show icons next to last message
-- | --

feat(Conversation): mark file/object shares with icon in conversations list

---

lib/Chat/CommentsManager.php
lib/Chat/Parser/SystemMessage.php
lib/Command/Developer/UpdateDocs.php
lib/Command/User/TransferOwnership.php
lib/Events/BeforeTurnServersGetEvent.php
lib/Exceptions/DialOutFailedException.php
lib/Manager.php
lib/MatterbridgeManager.php
lib/Middleware/Attribute/RequirePermission.php
lib/Middleware/CanUseTalkMiddleware.php
lib/Middleware/InjectionMiddleware.php
lib/Migration/FixNamespaceInDatabaseTables.php
lib/Migration/Version19000Date20240709183938.php
lib/Notification/Notifier.php
lib/Service/HostedSignalingServerService.php
lib/Share/RoomShareProvider.php
tests/integration/features/bootstrap/FeatureContext.php
tests/php/Collaboration/Collaborators/RoomPluginTest.php

chore(cs): Prepare coding-standard update

---

composer.lock
lib/Chat/AutoComplete/Sorter.php
lib/Collaboration/Collaborators/RoomPlugin.php
lib/Model/AttachmentMapper.php
lib/Service/BotService.php
lib/Signaling/Messages.php
tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
tests/php/Chat/AutoComplete/SearchPluginTest.php
tests/php/Chat/NotifierTest.php
tests/php/Chat/SystemMessage/ListenerTest.php
tests/php/Controller/ChatControllerTest.php
tests/php/Controller/SignalingControllerTest.php
tests/php/Service/RoomServiceTest.php
tests/php/Settings/Admin/AdminSettingsTest.php
tests/php/bootstrap.php

fix(rector): Update with rector

---

src/store/soundsStore.js

fix(sounds): mark audio objects as created

---

package-lock.json
package.json

* Fix  regression from #13366
* Tested

chore(deps): bump @nextcloud/webpack-vue-config from v6.1.0 to v6.1.1

---

.github/dependabot.yml
composer.json
rector.php
templates/index.php
templates/recording.php
vendor-bin/rector/composer.json
vendor-bin/rector/composer.lock

🤖 techdebt: Add PHP rector

---

.github/dependabot.yml

ref https://github.com/nextcloud/spreed/runs/31495799535

ci(dependabot): fix missing schedule

---

.github/dependabot.yml

https://github.com/nextcloud/spreed/pull/13432/checks?check_run_id=31497300106

ci(dependabot): Update configs must have a unique combination

---

README.md

fix(readme): Correct link to developer setup

---

lib/Controller/CallController.php

fix(call): Fix support for PHP < 8.3

---

tests/integration/composer.json
tests/integration/composer.lock

| Dev Packages                       | Operation | Base    | Target  |
|------------------------------------|-----------|---------|---------|
| behat/behat                        | Upgraded  | v3.14.0 | v3.15.0 |
| behat/gherkin                      | Upgraded  | v4.9.0  | v4.10.0 |
| guzzlehttp/promises                | Upgraded  | 2.0.3   | 2.0.4   |
| nikic/php-parser                   | Upgraded  | v5.1.0  | v5.3.1  |
| phpunit/php-code-coverage          | Upgraded  | 10.1.15 | 10.1.16 |
| phpunit/phpunit                    | Upgraded  | 10.5.25 | 10.5.38 |
| sebastian/comparator               | Upgraded  | 5.0.1   | 5.0.3   |
| symfony/config                     | Upgraded  | v6.4.6  | v6.4.13 |
| symfony/console                    | Upgraded  | v6.4.6  | v6.4.13 |
| …

ci(integration): Bump behat/behat to support PHP 8.4

---

src/components/NewMessage/NewMessagePollEditor.vue

fix: rename 'Private poll' to 'Anonymous poll'

---

appinfo/info.xml

chore: update authors

---

lib/MatterbridgeManager.php
src/components/ConversationSettings/Matterbridge/BridgePart.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/ConversationSettings/Matterbridge/matterbridgeTypes.ts

* Fix Matterbridge issues with setup
* Don't save selected result, as it was resetted anyway
* Move hardcoded types to separate file
* Minor code refactor
* Skip TLS for local NC server, optionally skip TLS for target NC server (self-signed certificate)
>[!TIP]
> To test:
> clone app https://github.com/nextcloud/talk_matterbridge to `apps-*` directory on your server
> make binaries (see app README)
> In Administration settings -> Apps -> Enable Talk Matterbridge
> In Administration settings -> Talk -> Enable Matterbridge integration
> In Conversation settings -> Matterbridge -> Select Nextcloud Talk:
> - URL: any host works (tested with https://nextcloud.local to itself and to https://stable29.local)
> - user: userid of user, who will be posting messages on behalf of Matterbridge (should …

fix(matterbridge): fix Matterbridge setup

---

src/components/CallView/CallView.vue

* Fix #13802
* Regression from #13329
-- | --

fix(CallView): update isEmptyCallView correctly

---

lib/Service/ParticipantService.php

fix(calls): Fix call notifications in archived conversations

---

src/components/ConversationSettings/ConversationSettingsDialog.vue
src/components/LeftSidebar/LeftSidebar.spec.js
src/components/LeftSidebar/LeftSidebar.vue
src/utils/conversation.js

fix: adjust archive filtering behaviour - frontend

---

src/components/MessagesList/MessagesGroup/Message/Message.vue

fix(chat): No "Generate summary" in federated conversations

---

.github/workflows/reuse.yml

- Testing https://github.com/nextcloud/.github/pull/457

ci: Run reuse action v5.0.0

---

.github/workflows/command-openapi.yml

Forgotten to git add in #13885

ci(openapi): Update used action

---

lib/Chat/Changelog/Manager.php

feat(release): Promote Desktop, AI Summaries, Meetings and Archiving

---

package-lock.json
src/components/ConversationSettings/LobbySettings.vue

* Fix #13929
* Upstream library changed styles, so appendToBody broke layout now
* Move some props to template
* Also bump external library for icon-close/icon-calendar fix
-- | --

fix(LobbySettings): fix date picker alignment

---

src/components/ImportEmailsDialog.vue
src/components/RightSidebar/LobbyStatus.vue

chore(i18n): Improved grammar

---

src/components/MediaSettings/MediaDevicesSelector.vue
src/components/MediaSettings/MediaDevicesSpeakerTest.vue
src/components/MediaSettings/MediaSettings.vue
src/components/MediaSettings/VideoBackgroundEditor.vue
src/components/TopBar/CallTime.vue
src/components/TopBar/ReactionMenu.vue
src/components/TopBar/TopBar.vue
src/components/TopBar/TopBarMediaControls.vue
src/components/TopBar/TopBarMenu.vue
src/components/UIShared/DialpadPanel.vue
src/components/UIShared/EditableTextField.vue
src/components/UIShared/SearchBox.vue
src/components/UIShared/VolumeIndicator.vue

* Rename some MDI icons to `Icon*` pattern

fix(icons): rename icon components

---

src/components/SettingsDialog/SettingsDialog.vue

fix(media): checking for config existence, not value

---

.github/workflows/integration-federation.yml
tests/integration/features/bootstrap/CommandLineTrait.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/FederationContext.php
tests/integration/run.sh

test(federation): Run cross major federation on CI

---

src/components/AdminSettings/RecordingServer.vue
src/components/AdminSettings/SignalingServer.vue

- Splitted from #13973
- rename icons
- add titles
- replace colors to NC palette

fix(AdminSettings): allow to retry server checks

---

.github/workflows/reuse.yml

- Ref https://github.com/nextcloud/.github/pull/478

ci(reuse): Bump action template

---

src/components/CallView/CallView.vue

* Shows video component for internal (SIP-) clients that publish a video stream.
-- | --

callview: Show internal clients with available video.

---

src/composables/useDocumentTitle.ts

- Archive a conversation and go to a different tab
- Send a normal message in the archived conversation from another user
-> you see an asterik in the doc title, you come back, you see no change in your main conversations list and no blue bubble in archived conversations button
https://github.com/nextcloud/spreed/blob/3a7c64f5f2b7780c2066c83736bd6a1bba10fef1/src/components/LeftSidebar/LeftSidebar.vue#L543-L546

fix(useDocumentTitle): skip asterik for normal messages in archives

---

src/components/NewConversationDialog/NewConversationSetupPage.vue

[stable30] chore(i18n): Improved grammar

---

.eslintignore
jest.config.js
lib/Controller/PageController.php
package-lock.json
package.json
src/utils/e2ee/JitsiDeferred.js
src/utils/e2ee/JitsiE2EEContext.js
src/utils/e2ee/JitsiEncryptionWorker.worker.js
src/utils/e2ee/JitsiEncryptionWorkerContext.js
src/utils/e2ee/crypto-utils.js
src/utils/e2ee/encryption.js
src/utils/e2ee/olm.js
src/utils/signaling.js
src/utils/webrtc/index.js

feat: Enable end-to-end encryption for WebRTC streams.

---

docs/chat.md

fix(docs): Typo in sending a new chat message

---

.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
tests/integration/features/chat-2/bots.feature
tests/integration/run.sh
tests/integration/talk_webhook_demo/appinfo/info.xml
tests/integration/talk_webhook_demo/appinfo/routes.php
tests/integration/talk_webhook_demo/lib/Controller/BotController.php
tests/integration/talk_webhook_demo/lib/Migration/InstallBot.php
tests/integration/talk_webhook_demo/lib/Migration/UninstallBot.php
tests/integration/talk_webhook_demo/lib/Migration/Version1000Date20230719061613.php
tests/integration/talk_webhook_demo/lib/Model/Bot.php
tests/integration/talk_webhook_demo/lib/Model/LogEntry.php
tests/integration/talk_webhook_demo/lib/Model/LogEntryMapper.php
tests/integration/talk_webhook_demo/lib/Service/BotService.php
tests/integration/talk_webhook_demo/lib/Service/SummaryService.php

- Prerequirement for the federation tests in #14160

[stable30] ci: Replace call_summary_bot with a demo app for webhooks

---

src/components/TopBar/TopBar.vue

fix(TopBar): replace richEditor mixin with NcRichText

---

src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/LocalAudioControlButton.vue
src/components/CallView/shared/LocalVideo.vue
src/components/CallView/shared/PresenterOverlay.vue
src/components/CallView/shared/ReactionToaster.vue
src/components/CallView/shared/Screen.vue
src/components/CallView/shared/VideoBackground.vue
src/components/CallView/shared/VideoVue.vue
src/components/CallView/shared/ViewerOverlayCallView.vue
stylelint.config.js

fix: RTL support in call view

---

lib/Chat/AutoComplete/SearchPlugin.php
lib/Chat/Notifier.php
lib/Chat/Parser/UserMention.php
lib/Controller/RoomController.php
lib/Notification/Notifier.php
lib/Service/ParticipantService.php
openapi-full.json
openapi.json
src/constants.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-1/notifications.feature
tests/integration/features/chat-2/mentions.feature
tests/php/Chat/Parser/UserMentionTest.php
tests/php/Notification/NotifierTest.php

feat(mentions): allow teams to be mentioned

---

docs/events.md
lib/AppInfo/Application.php
lib/Chat/ReactionManager.php
lib/Controller/BotController.php
lib/Controller/ReactionController.php
lib/Events/AReactionEvent.php
lib/Events/BeforeReactionAddedEvent.php
lib/Events/BeforeReactionRemovedEvent.php
lib/Events/BotInvokeEvent.php
lib/Events/ReactionAddedEvent.php
lib/Events/ReactionRemovedEvent.php
lib/Listener/BotListener.php
lib/Model/Bot.php
lib/Service/BotService.php
lib/Service/SampleConversationsService.php

feat(bots): Allow bots to get invoked for reactions

---

lib/Controller/ChatController.php
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
src/constants.js

[stable29] fix(chat): Allow to edit messages of bots in one-to-one conversations

---

CHANGELOG.md

chore(changelog): Fix versions

---

tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/federation/call.feature
tests/integration/features/federation/chat.feature
tests/integration/features/federation/invite.feature
tests/integration/features/federation/join-leave.feature
tests/integration/features/federation/lobby.feature
tests/integration/features/federation/permissions.feature
tests/integration/features/federation/poll.feature
tests/integration/features/federation/reminder.feature
tests/integration/features/federation/user-statuses.feature
tests/integration/run.sh

Progress almost completed, only invite.feature is missing after line 107

tests: Make federation tests do real federation

---

src/App.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
src/services/teamsService.ts
src/store/actorStore.js
src/types/index.ts

* Fix frontend for #14283
* Made in vuex store for compatibility with 29-31 (not sure how far we backport it)
-- | --

fix(actorStore): fetch teams with membership

---

src/components/CalendarEventsDialog.vue
src/components/NewConversationDialog/NewConversationContactsPage.vue
src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
src/components/RoomSelector.vue
src/components/UIShared/SearchBox.vue

* fix(NcTextField): replace deprecated slots
* fix(NcDateTimePickerNative): remove overwritten styles, remove resolved comment, fix type check

fix: vue-lib follow-ups

---

src/types/index.ts

* Take types from separate json/ts files:
* Easier navigation
* Less error-prone

fix(openapi): move from full-json to separate files

---

src/types/openapi/core/openapi_dav.ts

Auto-generated update of Nextcloud OpenAPI types

[main] Update Nextcloud OpenAPI types

---

lib/Dashboard/TalkWidget.php
tests/integration/features/integration/dashboard.feature

fix(lobby): Hide lobbied conversations from dashboard

---

docs/quick-install.md

Fix the TURN secret example in quick install guide.

Update quick-install.md (fix TURN secret example)

---

.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
composer.lock

[stable29] Update nextcloud/ocp dependency

---

lib/Notification/Notifier.php
lib/Service/ReminderService.php
tests/php/Notification/NotifierTest.php

fix(reminder): Log when generating the reminder didn't work

---

lib/Controller/CallController.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/callapi/public.feature

fix(calls): Fix displayname when exporting call participants

---

src/components/AdminSettings/MatterbridgeIntegration.vue
src/components/NewMessage/NewMessageAbsenceInfo.vue
src/components/NewMessage/NewMessageChatSummary.vue

* Found with https://github.com/nextcloud/docker-ci/pull/740

fix(l10n): Fix translation source strings

---

lib/AppInfo/Application.php
lib/SetupCheck/NotifyPush.php

* Fix https://github.com/nextcloud/spreed/issues/14410

feat: add notify_push setup check

---

vendor-bin/psalm/composer.json
vendor-bin/psalm/composer.lock

Fixing https://github.com/nextcloud/spreed/network/updates/982171902

ci: Fix psalm requirements

---

src/types/openapi/core/openapi_files.ts

Auto-generated update of Nextcloud OpenAPI types

[stable31] Update Nextcloud OpenAPI types

---

src/components/CallView/CallView.vue
src/components/CallView/useWakeLock.ts

* Fix https://github.com/nextcloud/spreed/issues/9516

fix(call): prevent screen from turning off during call

---

src/types/openapi/core/openapi_provisioning_api.ts

Auto-generated update of Nextcloud OpenAPI types

[stable30] Update Nextcloud OpenAPI types

---

lib/Chat/Parser/SystemMessage.php
tests/integration/features/command/user-remove.feature

fix(calls): Fix system message for unanswered call

---

docs/Talkbuchet.js
package-lock.json
package.json
src/store/fileUploadStore.js
src/store/messagesStore.js
src/utils/readableNumber.ts
src/utils/signaling.js
src/utils/textParse.ts
src/utils/webrtc/VideoConstrainer.js

fix: improve string handling

---

appinfo/info.xml
docs/occ.md
lib/Command/PhoneNumber/AddPhoneNumber.php
lib/Command/PhoneNumber/FindPhoneNumber.php
lib/Command/PhoneNumber/ImportPhoneNumbers.php
lib/Command/PhoneNumber/RemoveAccount.php
lib/Command/PhoneNumber/RemovePhoneNumber.php
lib/Command/PhoneNumber/RemoveUser.php
lib/Migration/Version21001Date20250327161337.php
lib/Model/PhoneNumber.php
lib/Model/PhoneNumberMapper.php
tests/psalm-baseline.xml

feat(sip): Allow adding, removing and importing phone numbers

---

lib/Chat/Parser/SystemMessage.php

fix(shares): Fix lightweight share condition for CardDAV files

---

package-lock.json
package.json
src/components/AvatarWrapper/AvatarWrapper.spec.js
src/components/AvatarWrapper/AvatarWrapper.vue
src/components/ConversationIcon.vue
src/components/GuestWelcomeWindow.vue
src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue

bump library, adjust changed props

chore(deps): bump nextcloud/vue from 8.23.1 to 8.24.0

---

lib/Controller/RoomController.php
tests/integration/features/conversation-5/set-password.feature

fix(RoomController): skip password verification for guests that are reconnecting to the call

---

lib/Chat/MessageParser.php
lib/Chat/Parser/SystemMessage.php
lib/Service/ParticipantService.php
tests/integration/features/chat-1/note-to-self.feature
tests/integration/features/command/user-remove.feature

fix(chat): Don't look for some more hardcoded guests

---

.github/workflows/integration-pgsql.yml
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/SharingContext.php
tests/integration/features/scaling/call.feature
tests/integration/features/scaling/chat.feature
tests/integration/features/scaling/conversations.feature

test: Run scaling tests with query.log

---

src/components/LeftSidebar/LeftSidebar.vue
src/utils/conversation.js

* Pre-requisite to  #14714
* With this approach, we add more filters and they can be used together (like filter group/individual)
-- | --

feat(LeftSidebar): transform filters to chips

---

.github/workflows/appstore-build-publish.yml

Reverts nextcloud/spreed#14842

Revert "ci: Generate authoritative classmap again"

---

src/components/LeftSidebar/ConversationsList/Conversation.spec.js
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
src/components/MediaSettings/MediaDevicesSelector.vue
src/composables/useConversationInfo.ts
src/utils/getMessageIcon.ts

* Follow-up to #14813
🏚️ Before | 🏡 After | Diff
-- | -- | --
---

fix(Conversation): refactor subname rendering, get rid of v-html

---

tests/integration/features/bootstrap/CommandLineTrait.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/bootstrap/FederationContext.php
tests/integration/features/bootstrap/RecordingTrait.php
tests/integration/features/bootstrap/SharingContext.php

chore: Update coding standard in behat

---

appinfo/routes/routesRoomController.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

* Followup to #14738 Should have noticed that the openapi changes are too small :see_no_evil:

fix(conversation): Add route for important conversation

---

lib/GuestManager.php
tests/php/GuestManagerTest.php

* Fix https://github.com/nextcloud/spreed/issues/4966
🏚️ Before | 🏡 After without lobby
-- | --
🏚️ Before | 🏡 After with lobby
-- | --

feat(emails): improved conversation invitation emails

---

appinfo/info.xml
lib/Command/PhoneNumber/AddPhoneNumber.php
lib/Command/PhoneNumber/FindPhoneNumber.php
lib/Command/PhoneNumber/ImportPhoneNumbers.php
lib/Migration/Version21001Date20250417141337.php
lib/Model/PhoneNumber.php
tests/integration/features/bootstrap/CommandLineTrait.php
tests/integration/features/command/phone-number.feature
tests/integration/spreedcheats/lib/Controller/ApiController.php

* Followup to #14729 
* Not sure what went wrong, but it seems I had forgotten to amend the last set of changes and adding the test file and then had wiped them on a rebase it seems.

fix(phonenumber): Fix migration and add missing test

---

package-lock.json
package.json

* Fix avatar requests in webinars and scrolling issue with mentions

chore(deps): bump @nextcloud/vue from 8.25.1 to 8.26.0

---

.github/workflows/update-nextcloud-openapi.yml

ci(openapi): Fix checkout of correct server branch

---

lib/Controller/RoomController.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts

fix(scheduling): Enforce one-to-one participants before scheduling

---

.tx/backport

Reverts nextcloud/spreed#14966

Revert "ci(translations): Backport translations for todays release"

---

lib/GuestManager.php

fix(l10n): fixup localization string for emails

---

lib/Controller/RoomController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation-1/create.feature

fix(conversation): Fix missing return

---

lib/Service/RoomService.php

fix(lobby): Allow setting the lobby on event and extended conversations

---

tests/integration/features/conversation-1/create.feature

- Ref https://github.com/nextcloud/spreed/actions/runs/14732111139/job/41348725053?pr=14731#step:14:5474

test: Fix flaky test conversation order

---

src/components/LeftSidebar/LeftSidebar.vue
src/store/conversationsStore.js
src/store/conversationsStore.spec.js
src/utils/userStatus.ts

Manual backport of #14930
- SearchConversationsResults.vue -> LeftSidebar.vue

[stable30] fix: do not make extra requests to user_status

---

appinfo/routes/routesChatController.php
docs/capabilities.md
lib/Capabilities.php
lib/Chat/ChatManager.php
lib/Controller/ChatController.php
lib/Manager.php
lib/Model/Reminder.php
lib/Model/ReminderMapper.php
lib/ResponseDefinitions.php
lib/Service/ReminderService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-3/reminder.feature
tests/php/Controller/ChatControllerTest.php

feat(reminders): Add API endpoint to get upcoming reminders

---

src/App.vue
src/components/RightSidebar/RightSidebar.vue
src/components/RightSidebar/RightSidebarContent.vue
src/services/coreService.ts
src/stores/groupware.ts
src/types/index.ts
src/types/openapi/core/index.ts

* Ref #14413
* Requires https://github.com/nextcloud-libraries/nextcloud-vue/pull/6666
* Requires nextcloud/server#52366
No info | Minimum | Maximum | Actions
-- | -- | -- | --
Preview | Narrow screen 
-- | --
Full pic | Narrow screen

feat(RightSidebar): improve appearance, show profile details

---

lib/Listener/CalDavEventListener.php
tests/php/Listener/CalDavEventListenerTest.php

- Background jobs and public appointment accept/decline links do not have a user session
- Trimmed stack trace to relevant information 
TypeError: OCA\Talk\Listener\CalDavEventListener::__construct(): Argument #6 ($userId) must be of type string, null given
#35 /spreed/lib/Listener/CalDavEventListener.php(32): OCA\Talk\Listener\CalDavEventListener::__construct
#8 /dav/lib/CalDAV/Schedule/Plugin.php(241): OCA\DAV\CalDAV\Schedule\Plugin::scheduleLocalDelivery
#7 /dav/lib/CalDAV/InvitationResponse/InvitationResponseServer.php(114): OCA\DAV\CalDAV\InvitationResponse\InvitationResponseServer::handleITipMessage
#6 /dav/lib/Controller/InvitationResponseController.php(61): OCA\DAV\Controller\InvitationResponseController::accept
Exception: OCA\Talk\Listener\CalDavEventListener::__construct(): …

fix: no user in background jobs and appointment links

---

src/components/TopBar/TopBarMediaControls.vue
src/utils/webrtc/simplewebrtc/getscreenmedia.js

* Not needed after https://github.com/nextcloud/talk-desktop/pull/1261

chore(desktop): do not skip check for https

---

docs/capabilities.md
lib/Capabilities.php
lib/ResponseDefinitions.php
openapi-administration.json
openapi-backend-recording.json
openapi-backend-signaling.json
openapi-backend-sipbridge.json
openapi-bots.json
openapi-federation.json
openapi-full.json
openapi.json
src/__mocks__/capabilities.ts
src/types/openapi/openapi-administration.ts
src/types/openapi/openapi-backend-recording.ts
src/types/openapi/openapi-backend-signaling.ts
src/types/openapi/openapi-backend-sipbridge.ts
src/types/openapi/openapi-bots.ts
src/types/openapi/openapi-federation.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/php/CapabilitiesTest.php

fix(instant-meetings): Expose retention period for instant meetings

---

lib/Controller/CallController.php
lib/Controller/RoomController.php
lib/Events/ACallStartedEvent.php
lib/Events/AParticipantModifiedEvent.php
lib/Notification/Listener.php
lib/Service/RoomService.php
openapi-full.json
openapi.json
src/App.vue
src/services/callsService.js
src/store/participantsStore.js
src/store/participantsStore.spec.js
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
src/utils/signaling.js
src/utils/webrtc/index.js
tests/integration/features/conversation-1/create.feature

fix(call): Send notification to newly added participants

---

lib/Controller/RoomController.php

fix(instant-meetings): Allow unbinding instant meetings

---

src/__mocks__/capabilities.ts
src/components/Dashboard/EventCard.vue
src/components/Dashboard/TalkDashboard.vue
src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
src/components/LeftSidebar/LeftSidebar.spec.js
src/components/LeftSidebar/LeftSidebar.vue
src/components/MediaSettings/MediaSettings.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
src/components/UIShared/ConversationActionsShortcut.vue
src/components/UIShared/LoadingPlaceholder.vue
src/constants.ts
src/services/EventBus.ts
src/services/dashboardService.ts
src/services/remindersService.js
src/store/conversationsStore.js
src/stores/dashboard.ts
src/stores/talkdashboard.ts
src/types/index.ts
src/utils/handleUrl.ts
src/views/WelcomeView.vue

- ### ☑️ Resolves
* Fix #14408
Initial views | During call
-- | --
-  [ ]  Call event room
-  [ ]  Hover effect on room
-  [ ]  Handle duplicates of events (when they are in multiple calendars)
-  [ ]  Add instant meeting button
-  [ ]  specify max width for the whole of it (like chat)
-  [ ]  upcoming reminders
-  [ ]  Device checker
-  [ ]  Unread mentions
-  [ ]  Periodic fetch  + add button
-  [ ]  Loading placeholder
-  [ ]  Fix calendar badge and In {room}

feat: Talk Dashboard

---

appinfo/info.xml
appinfo/routes/routesRoomController.php
docs/capabilities.md
lib/Capabilities.php
lib/Controller/RoomController.php
lib/Dashboard/TalkWidget.php
lib/Migration/Version21001Date20250509153510.php
lib/Model/Attendee.php
lib/Model/AttendeeMapper.php
lib/Model/SelectHelper.php
lib/Notification/Notifier.php
lib/ResponseDefinitions.php
lib/Service/ParticipantService.php
lib/Service/RoomFormatter.php
openapi-backend-sipbridge.json
openapi-federation.json
openapi-full.json
openapi.json
src/components/LeftSidebar/ConversationsList/Conversation.spec.js
src/components/LeftSidebar/ConversationsList/Conversation.vue
src/types/openapi/openapi-backend-sipbridge.ts
src/types/openapi/openapi-federation.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation-5/sensitive.feature
tests/integration/features/integration/dashboard-server.feature
tests/php/Chat/ChatManagerTest.php

* Fixes https://github.com/nextcloud/spreed/issues/8820 (?)

feat(conversations): Add "sensitive conversations" that hide the last message

---

CHANGELOG.md

chore: Fix typo in changelog

---

lib/Dashboard/Event.php
tests/integration/features/integration/dashboard-talk.feature
tests/integration/spreedcheats/lib/Controller/ApiController.php

fix(calendarintegration): skip unknown attachments

---

lib/AppInfo/Application.php
lib/Listener/AddMissingIndicesListener.php
lib/Migration/Version3003Date20180720162342.php

fix(object-rooms): Add an index on the room object columns

---

lib/Chat/Changelog/Manager.php

* Open point from https://github.com/nextcloud/spreed/issues/15046

chore(release): Add update info for Talk 21.1

---

lib/BackgroundJob/ExpireObjectRooms.php
lib/Manager.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/conversation-5/delete-room.feature
tests/integration/spreedcheats/lib/Controller/ApiController.php

fix(retention): Fix cron job query for retention of object conversations

---

src/assets/variables.scss
src/components/Dashboard/EventCard.vue
src/components/Dashboard/TalkDashboard.vue
src/components/LeftSidebar/LeftSidebar.vue

fix(TalkDashboard):  support mobile view and correct minor styling issues

---

src/components/Dashboard/EventCard.vue
src/components/Dashboard/TalkDashboard.vue
src/components/UIShared/LoadingPlaceholder.vue
src/env.d.ts

* Fix:
*  Correct translation in event room location
* Add icon and show if there are other attachments
* Increase height by 25px so it can provide space for the new addition
-- | --

fix: add attachment icon and link

---

src/App.vue

* Fix broken interface after attempt to navigate to a conversation, which can not be accessed by user
- if it is not yet in the list - should be tried to fetch
- in case of 403/404 - navigate to not-found page
-- | --
App interface is broken | Correct redirect and further work of the app

fix: prevent navigation to inaccessible conversations

---

src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue

* Fix #15362
> Not yet locally tested, but in browser only
-- | --

feat(web): always render code blocks LTR

---

src/components/CalendarEventsDialog.vue
src/components/Dashboard/EventCard.vue
src/components/ExtendOneToOneDialog.vue
src/components/PollViewer/PollEditor.vue
src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
src/components/UIShared/ConfirmDialog.vue
src/composables/useDocumentTitle.ts
src/composables/useSessionIssueHandler.ts
src/composables/useTemporaryMessage.ts
src/services/EventBus.ts
src/types/vendor/vuex.d.ts
tsconfig.json

fix(ts): address typescript issues

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue

* Fix toggling system messages
~~* Fix styles for Desktop client~~

fix(messages): fix toggle for combined message

---

src/components/GuestWelcomeWindow.vue
src/components/SetGuestUsername.vue
src/types/vendor/@nextcloud/event-bus.d.ts

* Fix guest name setting on public pages
* correctly get info from browserstorage, show popups and connect with public user menu
* fix style issues
-- | --

fix(public):  set guest names correctly

---

lib/Chat/ChatManager.php
lib/Service/ThreadService.php
tests/integration/features/chat-4/threads.feature

fix(threads): Mark thread attendees as mentioned

---

src/init.js

https://caniuse.com/?search=requestidlecallback
* Fix regression introduced for Safari
* also refactor old migration steps

fix(safari): provide fallback for 'window.requestIdleCallback'

---

src/components/ConversationSettings/BanSettings/BanSettings.vue
src/components/ConversationSettings/BreakoutRoomsSettings.vue
src/components/ConversationSettings/ConversationAvatarEditor.vue
src/components/ConversationSettings/ConversationPermissionsSettings.vue
src/components/ConversationSettings/LinkShareSettings.vue
src/components/ConversationSettings/LobbySettings.vue
src/components/ConversationSettings/Matterbridge/BridgePart.vue
src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
src/components/ConversationSettings/NotificationsSettings.vue

fix(design): Use outline icons in conversation settings

---

docs/capabilities.md
lib/Capabilities.php
lib/Controller/ThreadController.php
lib/Federation/Proxy/TalkV1/Controller/ThreadController.php
lib/Federation/Proxy/TalkV1/UserConverter.php
openapi-full.json
openapi.json
src/__mocks__/capabilities.ts
src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
src/components/UIShared/ConversationActionsShortcut.vue
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/php/CapabilitiesTest.php

feat(threads): Support federated conversations

---

lib/Controller/PollController.php
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-3/poll.feature

fix(polls): Correctly limit drafts to moderators

---

src/components/MessagesList/MessagesList.vue
src/composables/useGetMessages.ts

* Follow-up to #15530
* Move route change listener to context provider (isolating `getMessageContext()`)
* Refactor initializing logic (preconditions + first/lastKnown for context + find message)
* Replace chatIdentifier with token-only tracking,
* Check preconditions with route change
* This fix loading initial context for URLs like `{token}/#message_123`

fix(useGetMessages): fix getting context around focused message

---

src/components/MessagesList/MessagesList.vue
src/components/NewMessage/NewMessage.vue
src/composables/useConversationInfo.ts
src/store/messagesStore.js
src/store/messagesStore.spec.js
src/stores/__tests__/chat.spec.js
src/stores/chat.ts
src/types/index.ts

* Move messages list getter (actually used in components) to a new Pinia store
* Implement chat blocks feature for the later use

fix(messages): implement chat blocks for message rendering

---

lib/Chat/ChatManager.php
lib/Controller/ChatController.php

feat(threads): Support long polling and getContext with threadId

---

.github/workflows/command-openapi.yml

* Fix https://github.com/nextcloud/spreed/pull/15589#issuecomment-3121575075

ci(openapi): Fix openapi command 

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/TopBar/TopBar.vue
src/services/messagesService.ts
src/stores/chatExtras.ts
src/types/index.ts

* Follow-up to #15579
A | B | C | D
-- | -- | -- | --

fix(thread): replace createThread with setThreadNotificationLevel

---

lib/Chat/SystemMessage/Listener.php
lib/Controller/ChatController.php
lib/Controller/ThreadController.php
lib/Federation/Proxy/TalkV1/Controller/ChatController.php
lib/Federation/Proxy/TalkV1/Controller/ThreadController.php
lib/Model/Thread.php
lib/ResponseDefinitions.php
lib/Service/ThreadService.php
openapi-full.json
openapi.json
src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/TopBar/TopBar.vue
src/services/messagesService.ts
src/stores/chatExtras.ts
src/types/index.ts
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-4/threads.feature
tests/php/Chat/SystemMessage/ListenerTest.php

* Ref https://github.com/nextcloud/spreed/issues/15313#issuecomment-3108492060

feat(threads): Allow threads only while posting with a title

---

lib/Chat/SystemMessage/Listener.php

* Fixup to #15579
* Not sure if it's the right way, but there are a lot of checks like this 🤷🏽

fix(threads): fix creating threads from file shares

---

src/components/UIShared/VolumeIndicator.vue

fix(VolumeIndicator): transform to outline style

---

src/components/ConversationSettings/ConversationAvatarEditor.vue

* Regression from Vue 3 migration.  It is mandatory to expose anything used via ref

fix(ConversationAvatarEditor): fix creating conversation with emoji

---

src/components/UIShared/VolumeIndicator.vue

fix(volumeIndicator): fix misaligned icon

---

src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
src/components/RightSidebar/LobbyStatus.vue
src/components/RightSidebar/Participants/ParticipantsSearchResults.vue
src/components/RightSidebar/RightSidebar.vue
src/components/RightSidebar/RightSidebarContent.vue
src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
src/components/RightSidebar/SharedItems/SharedItemsTab.vue

fix(RightSidebar): change icons to outline

---

src/components/UIShared/VolumeIndicator.vue

fix(VolumeIndicator) migrate from style override to inline prop

---

lib/Chat/ChatManager.php
lib/Chat/SystemMessage/Listener.php
lib/Controller/ChatController.php
lib/Controller/ThreadController.php
lib/Manager.php
lib/Model/Thread.php
lib/Model/ThreadAttendee.php
lib/Service/ThreadService.php
openapi-full.json
openapi.json
src/types/openapi/openapi-full.ts
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/features/chat-4/threads.feature

feat(threads): Add an API to get your list of threads

---

docs/quick-install.md

docs: Adjust docs link for snap installation

---

package-lock.json
package.json
src/App.vue
src/FilesSidebarTabApp.vue
src/PublicShareAuthSidebar.vue
src/PublicShareSidebar.vue
src/Recording.vue
src/components/ExtendOneToOneDialog.vue
src/components/NewMessage/NewMessage.vue
src/components/UIShared/SearchBox.vue

* Bumps vue-library
* Drop some style overrides
New borders:
New status colors:

chore(deps): bump @nextcloud/vue to v9.0.0-rc.7

---

src/Recording.vue
src/components/CallView/CallView.vue

* Fixups after new UX changes
-- | --
same | <img width="1074" height="603" alt="2025-08-28_13h56_55" src="https://github.com/user-attachments/assets/0982d4c5-0b83-454a-a134-211d38e3b5e4" />

fix(Recording): hide controls, increase content height

---

src/components/ConversationSettings/NotificationsSettings.vue
src/components/LeftSidebar/ConversationsList/Conversation.vue

fix(chat):  change notifications icons

---

src/components/Dashboard/DashboardSection.vue
src/components/Dashboard/TalkDashboard.vue

fix(Dashboard): wrap buttons and break words

---

lib/Service/ThreadService.php

fix(threads): Hide unsubscribed threads from "Followed threads"

---

src/components/LeftSidebar/LeftSidebar.vue
src/stores/chatExtras.ts

fix(LeftSidebar): show loading state in sidebar

---

.github/workflows/integration-federation.yml
.github/workflows/integration-mariadb.yml
.github/workflows/integration-mysql.yml
.github/workflows/integration-oci.yml
.github/workflows/integration-pgsql.yml
.github/workflows/integration-sqlite.yml
.github/workflows/occ-command-documentation.yml
composer.json
composer.lock

chore(CI): Adjust testing matrix for Nextcloud 32 on stable32

---

src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
src/components/MessagesList/MessagesList.vue
src/components/RightSidebar/Threads/ThreadItem.vue

fix: support RTL in arrow buttons

---

src/components/RightSidebar/Threads/ThreadItem.vue
src/components/TopBar/TopBar.vue

* Fix #…
-- | --
Fallback for old browsers | --

style(ThreadItem): adjust color scheme

---

src/components/CallView/shared/LocalAudioControlButton.vue
src/components/CallView/shared/LocalVideoControlButton.vue

style(BottomBar): increase selector specificity for control buttons

---

src/components/CallView/BottomBar.vue
src/components/CallView/CallView.vue
src/components/CallView/Grid/Grid.vue
src/components/CallView/shared/VideoVue.vue

* Fix inconsistent paddings
-- | --
---

fix(CallView): align UI elements

---

src/components/LeftSidebar/LeftSidebar.vue
src/components/RightSidebar/Threads/ThreadItem.vue
src/stores/chatExtras.ts
src/utils/prepareTemporaryMessage.ts

* Remove unsubscribed threads from the list (aligned with API)
* Adjust styles for thread items to match conversations
* Correctly work with offset load (100+ threads)
🏡 After
https://github.com/user-attachments/assets/c13aa5d4-b170-44bc-a6f2-3dfd3bac587b
https://github.com/user-attachments/assets/f529ddcd-9652-4da6-8dc6-d4916fbedf75

fix(threads): remove unsubscribed threads from the list

---

src/components/ChatView.vue
src/components/NewMessage/NewMessage.vue
src/components/NewMessage/NewMessageUploadEditor.vue
src/store/fileUploadStore.js

* Fix posting file shares into a thread

fix(threads): upload files in the opened thread

---

tests/integration/run.sh

fix(tests): Reduce the error spam from missing default contact

---

src/components/CallView/shared/LocalAudioControlButton.vue
src/components/CallView/shared/LocalVideoControlButton.vue
src/components/MediaSettings/MediaSettings.vue
src/composables/useDevices.js
src/utils/webrtc/MediaDevicesManager.js

* Fix devices list update on:
* physical unplugging

fix(devices): fix reactive update of the devices list

---

src/components/PollViewer/PollEditor.vue
src/services/messagesService.ts
src/services/pollService.ts
src/stores/polls.ts

fix(threads): Allow posting polls into threads (frontend)

---

src/components/LeftSidebar/LeftSidebar.vue

fix(LeftSidebar): change wording to 'Threads'

---

src/store/messagesStore.js
src/stores/chat.ts

* see explanation in #16007
-- | --

fix(thread): extend thread blocks from message polling and posting new message
