nextcloud/spreed

- package-lock.json
> Audit for stable24 - without breaking changes

- lib/Service/ParticipantService.php
- lib/Signaling/Listener.php
- tests/php/Signaling/BackendNotifierTest.php
Fixes #8626
Self-joined users are just temporary participants and they need to be removed when they leave a conversation. However, this needs to be done once they have no more sessions in that conversation; otherwise the remaining sessions would be kicked out from the conversation as soon as one leaves it.
Moreover, if the external signaling server is used, when a participant is disinvited it is expected that the client leaves the conversation if still in it. Therefore, self-joined users should not be disinvited when
they disconnect from a conversation, as they can still have other sessions in it.
To ensure that self-joined users will be disinvited when their last session leaves the conversation now a USER_REMOVE event is explicitly triggered when that last session leaves and the user is, …
> Fix leaving room as a self joined user with several sessions

- tests/integration/run.sh
> ci: test against server debug branch

- appinfo/routes/routesChatController.php
- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Controller/ChatController.php
- lib/Service/RoomFormatter.php
- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
- src/services/messagesService.js
- src/store/messagesStore.js
- tests/integration/features/conversation/breakout-rooms.feature
- tests/php/CapabilitiesTest.php
> Load history and first set of new messages with 1 API request

- lib/Controller/RoomController.php
- tests/integration/features/conversation/breakout-rooms.feature
> Don't throw when breakout rooms are not started

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Fix #8363 
Native title attribute was added with same text as for aria-label
---|---
See issue | ![Screenshot from 2023-02-13 11-18-19](https://user-images.githubusercontent.com/93392545/218434011-aae5c3a5-6caf-46eb-b0fc-d3b8eba0cfeb.png)
> Apply title to reaction button

- docs/conversation.md
- lib/Controller/RoomController.php
- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/utils/signaling.js
Fix #7299
When `modifiedSince` is provided only conversations with a newer `lastActivity` are returned.
Due to the nature of the data structure we can not return information that a conversation was deleted
or the user removed from a conversation. Therefore it is recommended to do a full refresh:
* Every 5 minutes
* When a signaling message of type `delete` or `disinvite` was received
* Internal signaling mode is used
> "Modified since" support on roomlist

- src/components/CallView/shared/LocalMediaControls.vue
- src/components/VolumeIndicator/VolumeIndicator.vue
> Update LocalMediaControls buttons labels

- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
- src/mixins/getParticipants.js
- src/mixins/isInLobby.js
Fix #8407 
---|---
See mentioned issue | ![image](https://user-images.githubusercontent.com/93392545/219093353-63511eaa-1dcd-44ac-88a9-c598737f8206.png)
> Make participants counter always-on during the call

- appinfo/routes/routesPageController.php
- lib/Controller/PageController.php
- recording/src/nextcloud/talk/recording/Participant.py
- src/Recording.vue
- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/mainRecording.js
- src/router/router.js
- templates/recording.php
- webpack.config.js
Follow up to #8708
The recording UI can be tested without actually recording the call in the following way:
- Start a call in a public conversation
- In a private window, open `{url of the call}/recording`
Note that there will be no sound, as the call is joined without any user interaction and therefore sounds are blocked. This is correctly handled when accessing the endpoint from the recording server.
---|---
> Add specific UI for recording calls

- src/components/TopBar/CallButton.vue
> Make "End call for everyone" always available for moderators

- .github/workflows/appstore-build-publish.yml
- Makefile
- composer.json
Following https://github.com/nextcloud/mail/pull/8020/files
> Only do classmap-authoritative on release

- src/components/MessagesList/MessagesList.vue
Fixes #7690 
Before:
When in a call, but the window itself was not focused, the chat wouldn't scroll.
After:
When in a call, the chat will be scrolled when the window is visible (independent of being focused).
> Always scroll chat when in a call

- src/components/LeftSidebar/LeftSidebar.vue
> Fix event handler error

- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMenu.vue
> Fix hover effects for buttons in TopBar

- lib/Controller/SignalingController.php
- recording/server.conf.in
- recording/src/nextcloud/talk/recording/Config.py
- recording/src/nextcloud/talk/recording/Participant.py
- recording/src/nextcloud/talk/recording/Service.py
- src/Recording.vue
- src/components/CallView/CallView.vue
- src/mainRecording.js
- src/utils/signaling.js
- src/utils/webrtc/index.js
- tests/php/Controller/SignalingControllerTest.php
Follow up to #8708
Requires #8725
Requires strukturag/nextcloud-spreed-signaling#421
[Internal clients are specific to the signaling server](https://github.com/strukturag/nextcloud-spreed-signaling/blob/69dfb0686fdcef5e77f0559aa9e9dd8ac734fcaa/docs/standalone-signaling-api-v1.md#client-type-internal) and do not have a counterpart Nextcloud user/session. Due to its special nature an internal client is able to join any call, so using an internal client makes possible to record calls other than public ones, which was a limitation of using a guest participant.
Besides that, this also fixes stopping a recording when the last participant leaves, as the recording participant was a regular participant and thus prevented the call from ending when the rest left.
Finally, the recording participant …
> Use internal client of signaling server for recording

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesList.vue
Fix #8463
:derelict_house:  Before (covers date and check marker, fall outside of visible area): | -
-- | --
🏡 After
One- and two-line text messages: | In case buttons bar will be rendered outside of scroll area:
-- | --
> Correct MessageButtonsBar position (relative to message itself) on screen

- lib/Notification/Notifier.php
- lib/Service/RecordingService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/recording.feature
> Change notification object type for call recordings to allow better handling in mobile clients

- Makefile
> fix(packaging): Exclude webpack.config.js from packaging

- src/components/NewMessageForm/NewMessageForm.vue
---|---
Style overriding in https://github.com/nextcloud/spreed/pull/4333 worked on local tests but actually depends on building order and other apps. For example, `NcRichContenteditable` may be loaded on the page several times. Another instance may be loaded after the Talk.
~~Adding `!import` makes styles independent of order and duplications.~~
Increase specificity by combinator.
> Fix `NcRichContenteditable` styles overriding in `NewMessageForm`

- CHANGELOG.md
- Make "End call for everyone" available for moderators all the time  [#8767](https://github.com/nextcloud/spreed/pull/8767)
- Update some dependencies
- Show tooltip for conversations with a long title  [#8659](https://github.com/nextcloud/spreed/pull/8659)
- Don't break the maps app with the Talk Files sidebar integration  [#8590](https://github.com/nextcloud/spreed/pull/8590)
- Only register the maps integration when the user is allowed to use Talk  [#8591](https://github.com/nextcloud/spreed/pull/8591)
- Fix missing "Unread mentions" floating button since Nextcloud 25 theming update  [#8603](https://github.com/nextcloud/spreed/pull/8603)
- Fix button style while being in a call  [#8671](https://github.com/nextcloud/spreed/pull/8671)
- Only filter mentions for participants of the …
> Add changelog for 14.0.9 and 15.0.4

- lib/Files/TemplateLoader.php
- lib/PublicShare/TemplateLoader.php
- lib/PublicShareAuth/TemplateLoader.php
- stylelint.config.js
- templates/index.php
Before replacing `AdvancedInput` with `NcRichcontenteditable` in https://github.com/nextcloud/spreed/pull/4333 edited styles from [`vue-at`](https://github.com/fritx/vue-at) were added globally. Not this library is not used, and there is no need for these global styles. But it was still included in templates.
> Remove import of deleted `At.css`

- Makefile
Currently the release manual says:
```
make dev-setup build-js-production
```
But that does not install composer deps with no-dev mode and does not build the class loader. So I'm adding an explicit step that does all the steps the release action is doing
> Add a step "production-setup" to produce a release package

- CHANGELOG.md
- appinfo/info.xml
- Breakout rooms can be used to split a group call into temporary working groups (Requires the High-performance backend)  [#8337](https://github.com/nextcloud/spreed/pull/8337)
- Calls can now be recorded (Requires the High-performance backend)  [#8324](https://github.com/nextcloud/spreed/pull/8324)
- The top bar now shows useful information like participant count, call duration and title while in a call.  [#8341](https://github.com/nextcloud/spreed/pull/8341)
- Chat input now allows to autocomplete emojis  [#4333](https://github.com/nextcloud/spreed/pull/4333)
- Administrators can now define the default conversation permissions via the `default_permissions` app config  [#8457](https://github.com/nextcloud/spreed/pull/8457)
- Administrators can now define the default name of the Talk/ …
> Changelog for 16.0.0 beta.1

- lib/Notification/Notifier.php
- src/store/conversationsStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/recording.feature
>  feat(recording): Add a shorter subject for the call recording notification

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalVideo.vue
---|---
As mentioned in corellated issue #8815 :
>... Even if the camera supports a higher resolution [in calls the resolution is requested to be 720x540](https://github.com/nextcloud/spreed/blob/de32c67ee0b1abf7f0f819ca03e577f951f6f9e7/src/utils/webrtc/VideoConstrainer.js#L187-L194). This is a default value chosen for performance reasons, both for CPU load when encoding the video and for network bandwidth when sending it.
Maximum capable video resolution is fixed at 4:3. This PR adjusts width and height of local video frame in stripe to fit in desired resolution and avoid its cropping
> Set local video in Stripe to 4:3 aspect-ratio

- src/components/CallView/Grid/Grid.vue
This is specially important if the height of the recording is limited, due to the minimum fixed height of the stripe.
---|---
> Hide bottom stripe in recordings

- .github/workflows/jest.yml
In GitHub Actions Jest output doesn't have colors. It can be fixed with [--colors](https://jestjs.io/docs/cli#--colors)
---|---
> Fix colors in GitHub Actions Jest tests output

- docs/conversation.md
- docs/webinar.md
- lib/Controller/RoomController.php
- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/breakout-rooms.feature
> Restrict available APIs for breakout rooms

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoBottomBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
Fix #7703 
Native buttons are replaced with NcButton components, styles are fixed to remain the current appearance and behavior.
> Change native buttons to NcButton components 

- lib/Chat/Parser/SystemMessage.php
- tests/integration/features/chat/file-share.feature
Test fails before the patch:
> ![grafik](https://user-images.githubusercontent.com/213943/221491236-1991d42d-e256-4626-a68c-869f96b6e363.png)
Fix #8858
> Fix message type of files shared from mobile clients

- src/components/NewMessageForm/NewMessageForm.vue
Fix #8848 
Was there on the old advanced input:
https://github.com/nextcloud/spreed/blob/stable25/src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue#L252
---|---
> Focus chat input after quoting

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/test-setup.js
Clear warnings and fix some tests to correlate with MessageButtonsBar behavior (regression from #8716)
🏚️ Before [(jest log)](https://github.com/nextcloud/spreed/actions/runs/4261312050/jobs/7415479683#step:7:1) | 🏡 After [(jest log)](https://github.com/nextcloud/spreed/actions/runs/4264954583/jobs/7423699597#step:7:1) 
--- | --- 
|![image](https://user-images.githubusercontent.com/93392545/221251736-fbaa86a7-ac56-4967-8780-e254894d6903.png) | -
> Configure tests for MessageButtonsBar appearance

- src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
Fix #8842 
Previously we tried to call `focus()` method on NcTextField root DOM element, which is `div`. Fixed now
> Set focus to native input in NcInputField

- src/components/TopBar/TopBarMenu.vue
Fix #8865 
Type | 🏚️ Before | 🏡 After
---|---|---
Public | ![Bildschirmfoto vom 2023-02-27 15-57-28](https://user-images.githubusercontent.com/213943/221597966-1b44f06c-f009-4d62-952f-3f8f179f309f.png)| ![Bildschirmfoto vom 2023-02-27 15-55-55](https://user-images.githubusercontent.com/213943/221597605-e4877b12-931f-44f4-9fb7-0e0a34d436ee.png)
1-1 | ![Bildschirmfoto vom 2023-02-27 15-57-24](https://user-images.githubusercontent.com/213943/221597962-d850c021-3f30-434f-86c4-b537197ed5b2.png) | ![Bildschirmfoto vom 2023-02-27 15-55-59](https://user-images.githubusercontent.com/213943/221597609-3556db68-c02f-468c-8396-20b812cc1afb.png)
Group | ![Bildschirmfoto vom 2023-02-27 15-57-18](https://user-images.githubusercontent.com/213943/221597958-3eda834e-8666-43b4-b80b-34ad6a3574a0.png)| …
> fix(UI): Only show breakout rooms option when it's usable

- CHANGELOG.md
- appinfo/info.xml
- Don't show breakout room options in one-to-one and public conversations  [#8875](https://github.com/nextcloud/spreed/pull/8875)
- Don't show recording options when no recording servers are configured  [#8874](https://github.com/nextcloud/spreed/pull/8874)
- Focus conversation name field when creating conversation  [#8873](https://github.com/nextcloud/spreed/pull/8873)
- Allow to abort emoji-autocomplete with ESC  [#8870](https://github.com/nextcloud/spreed/pull/8870)
- Focus chat input when replying to a message  [#8864](https://github.com/nextcloud/spreed/pull/8864)
- Fix message type of attachments uploaded via mobile apps  [#8861](https://github.com/nextcloud/spreed/pull/8861)
- Hide the bottom video stripe in recordings …
> chore(release): Bump version and add changelog for 16.0.0-beta.2

- lib/Chat/Notifier.php
- tests/integration/features/chat-2/reaction.feature
Fix #8881 
Integration test before
> ![image](https://user-images.githubusercontent.com/213943/221824985-8dbfe7f9-d728-453a-a3fc-9a4efc9ead7c.png)
> fix(reactions): Fix reacting to people that left

- src/components/UploadEditor.vue
> fix(upload): Fix upload editor placement

- src/components/NewMessageForm/NewMessageForm.vue
Follow-up to https://github.com/nextcloud/spreed/pull/8058
Regression of https://github.com/nextcloud/spreed/pull/4333
---|---
B | A
<details>
<summary>For my own testing</summary>
```
docker run -it \
--name nextcloud-easy-test \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.24.128 \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
-e TALK_BRANCH=fix/noid/mobile-focus \
ghcr.io/szaimen/nextcloud-easy-test:latest
```
</details>
> do not focus input on mobile

- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
> Update breakout rooms actions 

- src/assets/variables.scss
- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessageForm/NewMessageForm.vue
> Fix scroll behaviour and "Scroll to bottom" button appearance

- CHANGELOG.md
- appinfo/info.xml
- Design review changes for breakout rooms handling [#8905](https://github.com/nextcloud/spreed/pull/8905) [#8910](https://github.com/nextcloud/spreed/pull/8910) [#8919](https://github.com/nextcloud/spreed/pull/8919) [#8920](https://github.com/nextcloud/spreed/pull/8920) [#8921](https://github.com/nextcloud/spreed/pull/8921) [#8922](https://github.com/nextcloud/spreed/pull/8922)
- Always expose the breakout room names when being a member of the parent [#8925](https://github.com/nextcloud/spreed/pull/8925)
- Hide breakout rooms from the dashboard widget [#8918](https://github.com/nextcloud/spreed/pull/8918)
- Fix chat scrolling to the end and the quick access button for it [#8895](https://github.com/nextcloud/spreed/pull/8895)
- Breakout rooms can not be …
> chore(release): Add changelog and bump version to 16.0.0-rc.1

- tests/integration/features/bootstrap/RecordingTrait.php
What I did:
* Remove request to mock server at `@AfterScenario`
* Prevent to run tests when can't start mock recording server
* Replace Linux command by PHP native way to run mock server
Fixed bug:
```
╳  Client error: `GET http://localhost:33537/fake/requests` resulted in a `404 Not Found` response (GuzzleHttp\Exception\ClientException)
└─ <span class="ansi-red-fg">@AfterScenario</span> <span class="ansi-black-fg"># FeatureContext::recordingServerIsStopped()</span>
```
> Improvements on mock recording server

- src/components/Description/Description.vue
Fix #8933 
Looks like a lot of changes, but it's a clean-up of regression style rules 
(and apply some margins, so input's width wouldn't jump between edit / load states)
---|---
https://user-images.githubusercontent.com/93392545/222758037-8186d5d2-7944-4d7a-90d7-283d8eaaa9f6.mp4
> Refactor `Description.vue`, remove redundant classes and style rules

- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
- src/components/RightSidebar/RightSidebar.vue
---|---
---|---
Aka. late comer, page reloaded, browser crashed, etc.
---|---
---|---
> Breakout room fixes

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
> fix(frontend): Fix empty action separator for group participants

- lib/Dashboard/TalkWidget.php
- tests/integration/features/integration/dashboard.feature
> fix(dashboard): Filter out breakout rooms from the Dashboard API list

- src/components/Description/Description.vue
- src/components/NewMessageForm/NewMessageForm.vue
Fix #7309
Fix #8869 
---|---
Conversation description | ---
Chat messages | ---
> Parse special symbols after NcRichContentEditable, like `<` and `>`

- src/components/TopBar/CallTime.vue
- src/components/TopBar/TopBar.vue
Fix #8899 
🏚️ Before
🏡 After
https://user-images.githubusercontent.com/93392545/223184279-f87bb6a4-c8d7-4a9c-8be2-0d736680ab07.mp4
> Remove empty space from Call Recording button

- src/components/ConversationSettings/ConversationPermissionsSettings.vue
- src/components/PermissionsEditor/PermissionsEditor.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js
Fix #8924 
2. Open settings permissions section: 🗒️ (expected) **Advanced** 👀 (actual) **Advanced**
3. Go to advanced 
4. Grant "Skip lobby"
5. "Update permissions"
6. Settings: 🗒️ (expected) **All permissions** 👀 (actual) **Advanced**
2. Open settings permissions section: 🗒️ (expected) **Advanced** 👀 (actual) **Advanced**
3. Go to advanced 
4. Grant "Skip lobby"
5. "Update permissions"
6. Settings: 🗒️ (expected) **All permissions** 👀 (actual) **All permissions**
> fix(permissions): Fix the permissions editor claiming custom permissions are used, when all boxes are ticked

- src/components/TopBar/TopBar.vue
Before there is a plain text button with only a numeric value on it without any further clue for screenreader users.
---|---
> fix(a11y): Add aria-label to button with only numeric label

- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
> Breakout rooms: improve semantic and a11y

- lib/Chat/ChatManager.php
- tests/integration/features/chat-2/poll.feature
> fix(polls): Remove polls also when deleting the chat history

- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/NewMessageForm/NewMessageForm.vue
> Add container context for `NewMessageForm`

- lib/Chat/Notifier.php
- lib/Notification/Notifier.php
- lib/Service/RecordingService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/recording.feature
- tests/php/Chat/NotifierTest.php
- tests/php/Service/RecordingServiceTest.php
> PS: I couldn't reproduce the reported problem but I did changes to give a best error report and send the notification.
* Notify as `error` when is an upload error
* Fix the error message to make more specific as the occurrence
> Send notification when get upload problem

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Fix #8885 
Sticky behaviour:
https://user-images.githubusercontent.com/93392545/223789949-7dc30ea9-f5f4-43be-b7f5-1cccb818a413.mp4
Message info:
> Improve MessageButtonsBar positionioning and message info visibility

- src/components/LobbyScreen.vue
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/components/Quote.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
> Improve `Unread messages` counter reactivity

- src/components/NewMessageForm/NewMessageForm.vue
Fix #9004 
See responses amount from `fileUploadStore.js`
---|---
> Prevent calling of duplicate paste event

- CHANGELOG.md
- Correctly handle `<` and `>` in chat messages [#8977](https://github.com/nextcloud/spreed/pull/8977)
- Improve the position of the message button bar for single line and very long messages [#9009](https://github.com/nextcloud/spreed/pull/9009)
- Remove space on call-time button [#8979](https://github.com/nextcloud/spreed/pull/8979)
- Fix displaying of restricted and full permissions selection when manually configuring them [#8982](https://github.com/nextcloud/spreed/pull/8982)
- Fix dashboard widget API returning breakout rooms [#8976](https://github.com/nextcloud/spreed/pull/8976)
- Improve breakout room API documentation [#8994](https://github.com/nextcloud/spreed/pull/8994)
- Also remove polls when purging the chat history [#8991](https://github.com/nextcloud/spreed/pull/8991)
- Fix …
> chore(release): Add changelog for 16.0.0-rc.3

- src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
Regression from #8764 
Missed during the development of previous solution, that NcButton styles could override current, and noticed it just now...
---|---
> Fix `PollVotersDetails` style

- src/components/MessagesList/MessagesGroup/Message/Message.vue
Fix #9016
Added a gap under the last message
Also set a right padding for buttons bar (to avoid cropping in sidebar chat and for the better look)
---|---
See issue | ![image](https://user-images.githubusercontent.com/93392545/224552112-d52aca2c-870d-4f9d-be73-0c1127621a6e.png)
> Reserve space for the last message's buttons bar

- lib/Model/Message.php
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
> Fix `Reply` and `Private reply` buttons show conditions

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationsList.vue
- src/utils/signaling.js
1. Open a chat
2. Delete the opened chat
Chat is not open.
After successful deleting, a web-page received a signaling error and redirect to `not-found` with a page reload.
https://user-images.githubusercontent.com/25978914/224779100-903fbd0f-1d17-4305-9c77-e7dbc2d27a73.mp4
https://user-images.githubusercontent.com/25978914/224779367-0b1f534f-8ac5-4877-a4c3-16eef4210c0a.mp4
> Show index page instead of hard redirect to 404 on chat delete after signaling error

- src/components/RightSidebar/RightSidebar.vue
Regression from #9046 
Somehow new syntax broke the behaviour of NcAppSidebarTab. It probably fails to render icons inside the dedicated slots.
(Debugging showed that icons are undefined at the moment of this checking):
https://github.com/nextcloud/nextcloud-vue/blob/e5ff79aeb48bbc250e75d72686a315b75d49eb83/src/components/NcAppSidebar/NcAppSidebarTabs.vue#L249
I assume, it could be safer to revert changes for now, or we could figure out the problem in this PR
> Solve new slot syntax issue

- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Chat/Notifier.php
- lib/Chat/Parser/UserMention.php
- lib/Notification/Notifier.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/components/NewMessageForm/NewMessageForm.vue
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/notifications.feature
- tests/php/Chat/AutoComplete/SearchPluginTest.php
- tests/php/Chat/NotifierTest.php
- tests/php/Chat/Parser/UserMentionTest.php
- tests/php/Notification/NotifierTest.php
> Group mentions

- lib/Signaling/Messages.php
> Fix order of message of signaling server to be returned to client

- .eslintrc.js
- src/App.vue
- src/env.d.ts
- src/main.js
- src/mixins/sessionIssueHandler.js
- src/router/router.js
- src/test-setup.js
- src/utils/signaling.js
- webpack.common.config.js
- webpack.config.js
This is a Draft:
- Waiting for https://github.com/nextcloud/spreed/pull/9048
- There are some more large preparations I want to add in other PR. I may add them to this PR (Should I?):
- Disable screensharing on desktop
- Disable avatars menu on desktop
There are more changes
> Prepare for desktop build

- recording/server.conf.in
- recording/src/nextcloud/talk/recording/Config.py
- recording/src/nextcloud/talk/recording/Service.py
Besides making the encoders and the extension configurable this also increases the default quality for videos and serves as the basis to add a benchmark tool.
In the future it could be better to make it configurable as well by backend, given that each backend can use different resolutions and thus might not require the same quality, but for now this should be enough.
> Add configuration options for FFmpeg

- recording/src/nextcloud/talk/recording/Service.py
Fixes #8750
Fixes/obsoletes #9020
> Fix stopping recording service before it has fully started

- docs/chat.md
- docs/conversation.md
Fixes https://github.com/nextcloud/spreed/pull/9066#discussion_r1143267669
`chat-keep-notifications` is the correct capability needed for the `markNotificationsAsRead` parameter.
Also I updated the wording for `noStatusUpdate` parameter, to be inline with the PHP annotation, which I think makes more sense.
> Fix documentation about capability and update wording

- CHANGELOG.md
- feat(chat): Allow to receive messages without marking notifications as unread [#9103](https://github.com/nextcloud/spreed/pull/9103)
- fix(chat): Fix multiple issues with emoji and mention autocompletion
- fix(chat): Fix pasting HTML and XML content into the chat input  [#9104](https://github.com/nextcloud/spreed/pull/9104)
- fix(calls): Fix RemoteVideoBlocker still active after removing its associated model  [#9131](https://github.com/nextcloud/spreed/pull/9131)
- fix(breakout-rooms): Fix breakout-room option shown for public conversations  [#9135](https://github.com/nextcloud/spreed/pull/9135)
- fix(UI): Fix conditions when a reload of the UI is necessary  [#9123](https://github.com/nextcloud/spreed/pull/9123)
- fix(recordings): Fix default quality of …
> chore(release): Add changelog for 14.0.10, 15.0.5 and 16.0.1

- CHANGELOG.md
- appinfo/info.xml
> chore(release): 15.0.5

- recording/src/nextcloud/talk/recording/BackendNotifier.py
A very small improvement to avoid double slashes on requests URLs from the recording server to the backend server.
> Ensure no double slashes on requests URLs from the recording server to the backend server

- recording/src/nextcloud/talk/recording/BackendNotifier.py
When Cloudflare or similar is used for the main/frontend site, it stops the Recording Server requests from ever reaching the server, due to the `User-Agent` reported by the recording server, `Python-urllib/X.Y` ([urllib.request.Request](https://docs.python.org/3/library/urllib.request.html#urllib.request.Request)).
This PR adds a user-configurable setting for such `User-Agent`.
> User agent for recording backend requests

- recording/src/nextcloud/talk/recording/BackendNotifier.py
- recording/src/nextcloud/talk/recording/__init__.py
A follow up of [#9175](https://github.com/nextcloud/spreed/pull/9175), as there was a missing `User-Agent`.
Also, clean up the double slashes for `uploadRecording`.
> Add missing user agent and double slashes cleanup

- CHANGELOG.md
- feat: Allow Chromium-based browser Brave  [#9166](https://github.com/nextcloud/spreed/pull/9166)
- feat(smart-picker): Add conversation search to the smart-picker integration  [#9105](https://github.com/nextcloud/spreed/pull/9105)
- fix(chat): Fix lost message text when autocomplete triggers after pasting text inside the @nextcloud/vue library  [#9191](https://github.com/nextcloud/spreed/pull/9191)
- fix(chat): Fix visual regression with links inside the @nextcloud/vue library  [#9191](https://github.com/nextcloud/spreed/pull/9191)
- fix(reactions): Don't update last message when someone reacted  [#9186](https://github.com/nextcloud/spreed/pull/9186)
- fix(recordings): Set a dedicated user-agent for the recording backend …
> chore(release): Add changelog for 16.0.2

- lib/Chat/Changelog/Manager.php
> fix(changelog): Add missing "New in Talk 16"

- src/App.vue
- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/RightSidebar/RightSidebar.vue
* Fix #9183 
https://user-images.githubusercontent.com/93392545/228841793-86d419d8-4100-4e5d-ac81-96befe7d3d7e.mp4
Other fixes:
> `RightSidebar` improvements and bug fixes

- tests/integration/run.sh
* Fix integration tests after guests app removed 27 support from master: https://github.com/nextcloud/guests/pull/1009#discussion_r1154097978
> fix(CI): Force enable 3rdparty apps in integration tests

- tests/integration/run.sh
* Fix red CI on integration tests
* Close #9233
> fix(CI): Disable rate limiting protection

- src/mixins/sessionIssueHandler.js
The URL in the session error handling redirect was not correct on the Desktop. 
Previously it redirected by an absolute URL. But it worked only on the dev server on the `http://` protocol. An absolute path is not correct for the `file://` protocol on the production build. It causes a black screen after receiving any signaling session error.
The new solution updates only hash (Hash routing is used on desktop) and reloads the page.
**NO CHANGES FOR WEB**
* Fix (likely): https://github.com/nextcloud/talk-desktop/issues/73
> Fix redirect url in session error handling for desktop

- lib/Settings/Admin/AdminSettings.php
* Fix #9181 
* API upstream proposal in https://github.com/nextcloud/server/pull/37572
---|---
> fix(settings): Fix missing recording settings when upload limit is INF

- lib/Chat/Parser/UserMention.php
- lib/Controller/ChatController.php
- lib/Notification/Notifier.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/rich-object-share.feature
- tests/integration/features/conversation/avatar.feature
- tests/php/Chat/Parser/UserMentionTest.php
- tests/php/Controller/ChatControllerTest.php
- tests/php/Notification/NotifierTest.php
https://github.com/nextcloud/spreed/pull/8333 introduced an optional `icon-url` for the call objects in rich messages.
Fix #8389
> Populate icon-url on call rich objects

- docs/conversation.md
One to one conversations will always be returned when we use `modifiedSince` and also set `includeStatus` to `true` as implemented here:
https://github.com/nextcloud/spreed/blob/f112fb92cc641af27d0d0644940a658a974ba319/lib/Controller/RoomController.php#L202-L207
This should be added to the docs.
> Add note about using modifiedSince with includeStatus set to true

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix #9258 
---|---
Patch that allows better testing as the temporary message is shown for longer:
```diff
diff --git a/lib/Controller/ChatController.php b/lib/Controller/ChatController.php
index 09f0b9dd4..6b07a04f9 100644
--- a/lib/Controller/ChatController.php
+++ b/lib/Controller/ChatController.php
@@ -206,6 +206,7 @@ class ChatController extends AEnvironmentAwareController {
*         found".
*/
public function sendMessage(string $message, string $actorDisplayName = '', string $referenceId = '', int $replyTo = 0, bool $silent = false): DataResponse {
+               sleep(5);
[$actorType, $actorId] = $this->getActorInfo($actorDisplayName);
if (!$actorId) {
return new DataResponse([], Http::STATUS_NOT_FOUND);
```
> fix(chat): Ignore whitespace for "emoji only" check

- src/components/LeftSidebar/LeftSidebar.vue
Regression of: #9068
---|---
After removing a conversation it is still considered current | After removing a conversation no is considered current
> Fix invalid current conversation after conversation remove

- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/ChatView.vue
- src/components/NewMessageForm/NewMessageForm.vue
* Fix container reference, passing to subcomponents in `NewMessageForm` (without changes, document.body by default)
* Prevents tribute to appear in `#content-vue` (which resolves this flickering)
* As a result, tribute doesn't inherit `box-sizing: border-box` from `NcContent` and looks normal
---|---
> Fix squeezed user mentions in NcRichcontenteditable

- lib/Activity/Listener.php
- lib/Chat/SystemMessage/Listener.php
- lib/Service/RecordingService.php
- psalm.xml
- tests/integration/features/callapi/recording.feature
- tests/php/Chat/SystemMessage/ListenerTest.php
> fix(recording): Don't create confusing system message about recording if actor ended the call

- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/simplewebrtc/simplewebrtc.js
Fixes #9267
The signaling messages used for reactions are similar to the ones used for raised hands. It is just a generic signaling message of type _message_ which includes a _reaction_ field. The value of that field is a string with the reaction.
There is no validation of the reactions. It is expected that clients just send the appropriate reactions, most likely a single emoji character. Nevertheless, it would be possible to send any string as reaction, for example, _LOL_. Please, do not do that :-P
The signaling messages work both with the external signaling server and the internal signaling server.
Besides the signaling message this pull request also shows the reactions sent by remote participants. It is just some old code I had lying around, so it does NOT follow in any way the agreed …
> Add signaling messages for reactions in calls

- CHANGELOG.md
- feat: Add missing "New in Talk 16" section [#9205](https://github.com/nextcloud/spreed/pull/9205)
- fix(chat): Fix missing popups and modals in fullscreen mode [#9323](https://github.com/nextcloud/spreed/pull/9323)
- fix(chat): Fix squeezed mention suggestions after library update [#9302](https://github.com/nextcloud/spreed/pull/9302)
- fix(conversation): Change redirect when the conversation is left or deleted [#9242](https://github.com/nextcloud/spreed/pull/9242) [#9058](https://github.com/nextcloud/spreed/pull/9058)
- fix(sidebar): Improve handling of the sidebar [#9212](https://github.com/nextcloud/spreed/pull/9212)
- fix(settings): Fix admin settings page when upload limit is infinite [#9247](https://github.com/nextcloud/spreed/pull/9247)
> chore(release): Add changelog for 16.0.3

- src/components/CallView/CallView.vue
- src/components/CallView/shared/ReactionToaster.vue
- src/components/TopBar/ReactionMenu.vue
- src/components/TopBar/TopBar.vue
* Overview in #9249
* Close #9266
**Reacting** - user's click is throttled to 1 reaction / 2 seconds. Horizontal and vertical offset are randomized to make it look more "natural"
One reaction | Spamming with reactions
-- | --
---
**Overlapping** - reactions source is located around 10-30% of call container width from the left, and each reaction flows up and dissapears at around 30-35% of screen height.
Speaker view | Screensharing
--- | ---
**Screen capture**
[reactions.webm](https://user-images.githubusercontent.com/93392545/233122383-ca5c4f14-8a7c-4166-96d7-95b9f685d62b.webm)
Ongoing tasks:
API tasks:
Visual tasks:
> Reactions in video calls

- composer.lock
- lib/AppInfo/Application.php
- lib/Notification/Notifier.php
- lib/Recording/Listener.php
- lib/Service/RecordingService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/callapi/recording.feature
- tests/integration/spreedcheats/lib/SpeechToText/LoremIpsumProvider.php
- tests/php/Service/RecordingServiceTest.php
- tests/psalm-baseline.xml
* Fix #9274 
* Fix #8504 
<details>
Failed transcript | Successful transcript
---|---
</details>
---
1. Enable the spreedcheat app - **🇴🇷** - 
2. To test without any transcript app available after this code add the following:
https://github.com/nextcloud/spreed/blob/55ce37f46a87507e4393062954c3f8ce3caa5816/lib/Service/RecordingService.php#L150-L152
<details>
```php
\OC::$server->get(IEventDispatcher::class)->dispatchTyped(new \OCP\SpeechToText\Events\TranscriptionFailedEvent(
$fileNode->getId(),
$fileNode,
'Error message',
));
```
```php
\OC::$server->get(IEventDispatcher::class)->dispatchTyped(new \OCP\SpeechToText\Events\TranscriptionSuccessfulEvent(
$fileNode->getId(),
$fileNode,
'Lorem ipsum',
));
```
</details>
---
> feat(recording): Automatically generate transcripts of call recording

- src/components/LeftSidebar/LeftSidebar.vue
* Perhaps a regression from #9068 
* Replace HTML Collection (doesn't have .forEach method) with iterable HTML NodeList (better at [performance](https://dev.to/wlytle/performance-tradeoffs-of-queryselector-and-queryselectorall-1074))
* Fix #9335 
Tested on Chrome, Talk-desktop
> Fix TypeError at `LeftSidebar`

- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/services/conversationsService.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Fix #6808 
---|---
`Mark as read` is shown for all conversation | Different buttons for read and unread conversations
> Allow to mark conversation as unread

- src/components/NewMessageForm/NewMessageForm.vue
> fix(avatar): Use conversation avatar in mention suggestion

- lib/Controller/FilesIntegrationController.php
- lib/Controller/PageController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Middleware/InjectionMiddleware.php
* Ref https://github.com/nextcloud/server/issues/37039#issuecomment-1520019584
> techdebt(controllers): Migrate controllers to Attributes

- lib/Controller/AvatarController.php
- lib/Controller/BreakoutRoomController.php
- lib/Controller/CallController.php
- lib/Controller/ChatController.php
- lib/Controller/GuestController.php
- lib/Controller/MatterbridgeController.php
- lib/Controller/PollController.php
- lib/Controller/ReactionController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Middleware/Attribute/RequireCallEnabled.php
- lib/Middleware/Attribute/RequireLoggedInModeratorParticipant.php
- lib/Middleware/Attribute/RequireLoggedInParticipant.php
- lib/Middleware/Attribute/RequireModeratorOrNoLobby.php
- lib/Middleware/Attribute/RequireModeratorParticipant.php
- lib/Middleware/Attribute/RequireParticipant.php
- lib/Middleware/Attribute/RequirePermission.php
- lib/Middleware/Attribute/RequireReadWriteConversation.php
- lib/Middleware/Attribute/RequireRoom.php
- lib/Middleware/CanUseTalkMiddleware.php
- lib/Middleware/InjectionMiddleware.php
- tests/psalm-baseline.xml
> techdebt(controllers): Move talk annotations to attributes

- composer.lock
- lib/Controller/AvatarController.php
- lib/Controller/BreakoutRoomController.php
- lib/Controller/CallController.php
- lib/Controller/ChatController.php
- lib/Controller/FederationController.php
- lib/Controller/FilesIntegrationController.php
- lib/Controller/GuestController.php
- lib/Controller/HostedSignalingServerController.php
- lib/Controller/MatterbridgeController.php
- lib/Controller/PageController.php
- lib/Controller/PollController.php
- lib/Controller/PublicShareAuthController.php
- lib/Controller/ReactionController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Controller/SettingsController.php
- lib/Controller/SignalingController.php
- lib/Controller/TempAvatarController.php
* Server ref https://github.com/nextcloud/server/pull/37905
> feat(controllers): Migrate server annotations to attributes

- lib/Service/RecordingService.php
- recording/pyproject.toml
- recording/src/nextcloud/talk/recording/BackendNotifier.py
- tests/php/Service/RecordingServiceTest.php
Currently, the recording server (and the backend server) loads the entirety of the recording file into RAM, which is far from optimal.
This PR changes such behavior and uses a streaming POST request instead.
I've noted that `newFile($fileName, $content)` ([source code](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Files/Folder.php#L113)) accepts `string|resource|null`, and `resource` is used in this case.
In my tests it performs a *copy* (and not a simple file rename), which temporarily wastes storage space in my current implementation.
I'm unsure how to force it to perform a file rename instead, or even if the current implementation (copy) is the desired solution so that compatibility with streaming-based file storage is not affected.
> Avoid out-of-memory errors when uploading a recording

- css/icons.css
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
* Fix #9188 
---|---
Groups show in bold | Groups show as mention
At-all shows group icon | At-all shows conversation avatar
Chat input shows no icon | Chat inpt shows avatar or group icon
- Helpful addition: https://github.com/nextcloud/nextcloud-vue/pull/4007
> fix(chat): Conversation avatar for mention chips

- docs/occ.md
- lib/Command/Command/Add.php
- lib/Command/Command/AddSamples.php
- lib/Command/Command/ListCommand.php
- lib/Command/Command/TRenderCommand.php
- lib/Command/Command/Update.php
- tests/integration/features/bootstrap/CommandLineTrait.php
- tests/integration/features/command/command-list.feature
> Fix json output

- src/components/NewMessageForm/NewMessageForm.vue
> Fix mentions of groups and guests as well as users with spaces

- lib/Controller/RoomController.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
* Fix #8787
* Can't really write an integration test for this as we don't want to wait 90 seconds on the test
---|---
All guests without a session are deleted | Guests with display names a kept and hidden<br>Guests with permissions or moderator type are displayed<br>![image](https://user-images.githubusercontent.com/213943/235593277-d67430ef-fd8a-4838-a170-f665d9ab8815.png)
> Keep guest attendees with values

- lib/Service/AvatarService.php
- tests/php/Service/AvatarServiceTest.php
> feat(avatar): Use the first emoji of room names as avatar emoji

- package-lock.json
- package.json
Smoke tested for:
* fix(NcAvatar): Use correct prop to track "open" aka. "shown" state
* feat(NcRichContenteditable): Support iconUrl on mention bubbles 
* NcAppSidebarTabs: fix activating the tab being added 
Note: looks awful :vomiting_face:
> chore(deps): Bump @nextcloud/vue to v7.11.1

- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/RightSidebar.vue
* Don't wait for tabs to be mounted in `$nextTick`
* Requires https://github.com/nextcloud/nextcloud-vue/pull/4004
* Fix #9345
---
* Change icon for moderators with custom permissions
* Fix #9298 (should be also reset to default on API side?)
---
* Check if participant belongs to conversation when updating his status (fix error when trying to get info from server about status while switching between conversations)
> `RightSidebar` improvements and bug fixes (participant tabs)

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
- src/components/NewMessageForm/NewMessageForm.vue
- src/components/SetGuestUsername.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/views/WelcomeView.vue
* Part of #7708 
* Minor visual changes (screenshots attached)
---|---
> Replace native inputs with NcTextfield

- src/components/AdminSettings/TurnServer.vue
* Fix #5563
Without creating a data channel Safari does not even try to create a connection to the turn server. With this PR a connection to the turn server is create successfully and candidates are returned. Tested this with Safari 16.3, Mobile Safari on iOS 16.4.1 and Chrome 112 using:
* `only turn:`
* `UDP & TCP`
---|---
> Create a data-channel when testing the turn setup

- appinfo/routes/routesAvatarController.php
- docs/avatar.md
- lib/Controller/AvatarController.php
- lib/Service/AvatarService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/avatar.feature
> feat(avatar): Allow to select an emoji + color as avatar

- src/utils/webrtc/simplewebrtc/webrtc.js
- src/utils/webrtc/webrtc.js
When a signaling message was sent to all the participants in the call it was first sent to all the peers and, then, to all the participants that had no peer. Due to this the signaling message was sent to screen peers and, when the HPB was used, to the own peer used to send media to the HPB.
Now those messages only take into account the participants, independently of the peers related to them, and a single message is sent for each participant (always with `video` as `roomType`, as `roomType` is always expected in the messages). This prevents, for example, duplicated messages to be received by a participant sending audio/video and sharing the screen.
Note that the `sid` parameter is no longer sent in the messages. Nevertheless, this parameter is specific to identify the session of a …
> Fix signaling messages sent to all participants

- CHANGELOG.md
- Makefile
- appinfo/info.xml
- lib/Chat/Changelog/Manager.php
- package-lock.json
- package.json
- Conversations can now have an avatar or emoji as icon [#927](https://github.com/nextcloud/spreed/issues/927)
- Virtual backgrounds are now available in addition to the blurred background in video calls [#9251](https://github.com/nextcloud/spreed/issues/9251)
- Reactions are now available during calls [#9249](https://github.com/nextcloud/spreed/issues/9249)
- Typing indicators show which users are currently typing a message [#9248](https://github.com/nextcloud/spreed/issues/9248)
- Groups can now be mentioned in chats [#6339](https://github.com/nextcloud/spreed/issues/6339)
- Call recordings are automatically transcript if a transcription provider app is registered [#9274](https://github.com/nextcloud/spreed/issues/9274)
- Chat message can be translated if a translation provider app is …
> Release 17.0.0 beta.1

- docs/capabilities.md
- docs/constants.md
- docs/settings.md
- lib/Capabilities.php
- lib/Config.php
- lib/Controller/AvatarController.php
- lib/Controller/SettingsController.php
- lib/TInitialState.php
- tests/integration/features/chat-2/typing-privacy.feature
- tests/php/CapabilitiesTest.php
API side of #9248 to implement an user setting to toggle typing privacy
> Add user setting for toggle typing privacy

- src/components/AdminSettings/TurnServer.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MediaDevicesSelector.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/NewMessageForm/TemplatePreview.vue
- src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
- src/components/TopBar/CallButton.vue
- src/mixins/devices.js
- src/utils/media/pipeline/TrackToStream.spec.js
- src/utils/webrtc/webrtc.js
Hello :wave:, first-time contributor here.
This PR replaces the use of `.indexOf` with `.includes` for cases where the method is used to check if an array contains a particular element. This results in improved code readability and better adherence to modern JavaScript best practices.
The replaced code snippets include:
1. `.indexOf(...) === -1`
2. `.indexOf(...) !== -1`
3. `.indexOf(...) > -1`
4. `.indexOf(...) >= 0`
> refactor: replace `indexOf` with `includes`

- jest.config.js
- src/components/ConversationIcon.vue
- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
* Adds avatar and description editors on conversation create dialog 
* Change styles and elements position for avatar editor
* Change "profile picture" to "conversation picture"
* Minor refactoring and fixes
---|---
> Add Avatar editor to new conversation dialog

- lib/Collaboration/Reference/TalkReferenceProvider.php
This adds the messageId to the richObject provided by the reference provider in case a link to a message is provided.
Server PR for definition: https://github.com/nextcloud/server/pull/38102
> Add messageId to richObject in ReferenceProvider

- .github/workflows/fixup.yml
Noticed in https://github.com/nextcloud/spreed/pull/9492 that we don't block them yet.
> Block fixup and squash commits

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Typing indicators frontend and settings [#9455](https://github.com/nextcloud/spreed/issues/9455) [#9431](https://github.com/nextcloud/spreed/issues/9431)
- Show empty call view on viewer overlay [#9460](https://github.com/nextcloud/spreed/issues/9460)
- Fix avatar handling when interacting with non-supporting backends [#9492](https://github.com/nextcloud/spreed/issues/9492)
---
> Release 17.0.0 beta.2

- lib/Controller/ChatController.php
- src/components/NewMessageForm/NewMessageForm.vue
- tests/integration/features/chat/group.feature
* Fix #9507
---|---
With only new lines the submit button is active | With only new lines the submit button is inactive
> fix(chat): Prevent empty chat messages

- lib/Service/ParticipantService.php
> Fix clearing of guests

- src/App.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/init.js
- src/utils/webrtc/index.js
- src/utils/webrtc/models/LocalMediaModel.js
* Fix #9501 
* Ref is https://github.com/nextcloud/spreed/commit/27105c9259e862d2b154600d8b51026b368b6367
* But the change was not fully done, so the webrtc code still checked without `videoDisabled_2790450198` but the media setting set `nextcloud_per_dGFsaw==_videoDisabled_2790450198` now both paths are consistent.
* We could also fix it the other way around and basically revert https://github.com/nextcloud/spreed/commit/27105c9259e862d2b154600d8b51026b368b6367 so it also writes without `nextcloud_per_dGFsaw==_` again. The advantage would be that existing settings would be reused, which I would actually prefer.
* Or in case the value is null, we check the old browser storage name to fallback. But that might be very cumbersome.
> fix(call): Fix incorrectly selected media when actually joining a call

- lib/Middleware/CanUseTalkMiddleware.php
> fix(settings): Fix recording server check for blocked admins

- src/components/ChatView.vue
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/NewMessageForm/TemplatePreview.vue
- src/components/Quote.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
- src/views/RoomSelector.vue
Explanation: the color-primary variables are not to be used in components because the introduce problems with high-contrast primary colors. Fix this by using the primary-element variables instead.
> Use the color-primary-element* variables

- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/EmptyCallView.vue
- src/components/ConversationSettings/DangerZone.vue
- src/components/ConversationSettings/ExpirationSettings.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/ConversationSettings/NotificationsSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
- src/components/SetGuestUsername.vue
- src/utils/webrtc/analyzers/AverageStatValue.js
* From https://github.com/nextcloud/spreed/pull/9430#discussion_r1191165370 and https://github.com/nextcloud/spreed/pull/9430#discussion_r1192518267
* Replace 'kinda' radio-buttons at NotificationSettings with `NcCheckboxRadioSwitch`
---|---
> (follow-up) Minor javascript refactoring

- src/mainPublicShareAuthSidebar.js
- src/mainPublicShareSidebar.js
* Fix #9529
* Explanation is in the mentioned issue
* Tested on web master
> Add main container id to the store for sidebars

- CHANGELOG.md
- package-lock.json
- package.json
- Allow translating chat messages [#9512](https://github.com/nextcloud/spreed/issues/9512)
- Media settings or not respected [#9513](https://github.com/nextcloud/spreed/issues/9513)
- Fix clearing guests over and over again on MySQL and Oracle [#9517](https://github.com/nextcloud/spreed/issues/9517)
- Prevent empty chat messages [#9509](https://github.com/nextcloud/spreed/issues/9509)
---
> Release 17.0.0 beta.3

- src/components/NewMessageForm/NewMessageForm.vue
* Partial backport (cherry picked from commit 639a3f77cbdb8ac4cda7e2fe7a14dab617777d2a)
*  Fix #9040
* Tested on stable26
> [stable26] Fix replacement of special symbols by EmojiPicker

- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
- src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.spec.js
If the source values are omitted by default [`drawImage`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) draws the whole source onto the canvas, therefore stretching it if the background and the canvas do not have the same aspect ratio. Now the background image is cropped and centered as needed to cover the whole canvas while maintaining the original aspect ratio of the background.
- Replace some of the background images with cropped versions. For example, with [1_office.jpg](https://github.com/nextcloud/spreed/assets/26858233/0c17ff2f-fa1d-491a-954e-9822c2d7edcf) and [6_theater.jpg](https://github.com/nextcloud/spreed/assets/26858233/d1dc7e7e-16ba-430a-a46d-ecbac87ab199)
- Use Firefox
- Enable fake streams (open `about:config` and enable …
> Fix virtual background image being stretched instead of cropped

- package-lock.json
- package.json
* Ref https://github.com/nextcloud/nextcloud-vue/pull/4125
---|---
> fix(deps): Bump @nextcloud/vue to 7.11.6

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Fix virtual background image being stretched instead of cropped [#9549](https://github.com/nextcloud/spreed/issues/9549)
> Release 17.0.0-rc.1

- src/components/CallView/CallView.vue
* Fix #9550
* Regression of #9336
---|---
Since #9336 entire `#video` block was shown only, when it is not the first `EmptyCallView`. It worked for grid mode with its own `EmptyCallView`, but didn't work with not grid mode. All things from not-grid mode were lost (local view (stripe), local screen-sharing, reactions).
This PR fixes the conditions chain in the CallView.
P.S. diff in GitHub looks a bit strange. I removed `v-else` from `#video` block and wrapped everything after `ViewerOverlayCallView` in `<template v-else>`. No changes in props.
> fix(CallView): fix no local video on empty call in not grid mode

- lib/Chat/ChatManager.php
- lib/Controller/ChatController.php
- tests/integration/features/chat-2/unread-messages.feature
> fix(chat): Update own read marker before triggering events when posting

- src/components/NewMessage/NewMessage.vue
> fix(chat): Don't send startTyping signaling message for each keystroke

- CHANGELOG.md
- fix(reactions): Fix own call reactions when the high-performance backend is used [#9586](https://github.com/nextcloud/spreed/issues/9586)
- fix(mediasettings): Hide virtual background options when not supported [#9611](https://github.com/nextcloud/spreed/issues/9611)
- fix(mediasettings): Fix broken aria-label [#9617](https://github.com/nextcloud/spreed/issues/9617)
- fix(CallView): Fix Fullscreen mode support in ViewerOverlay [#9613](https://github.com/nextcloud/spreed/issues/9613)
- fix(CallView): fix no local video on empty call in not grid mode [#9584](https://github.com/nextcloud/spreed/issues/9584)
- fix(chat): Don't send startTyping signaling message for each keystroke [#9614](https://github.com/nextcloud/spreed/issues/9614)
- Allow to mark conversations unread in the sidebar …
> chore(release): Add changelog for 14.0.11, 15.0.6, 16.0.4 and 17.0.0-rc.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Allow Brave browser without unsupported warning  [#9172](https://github.com/nextcloud/spreed/issues/9172)
- Fix call summary when a user has a full numeric user ID  [#9503](https://github.com/nextcloud/spreed/issues/9503)
> Release 14.0.11

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Allow Brave browser without unsupported warning [#9167](https://github.com/nextcloud/spreed/issues/9167)
- Fix call summary when a user has a full numeric user ID [#9504](https://github.com/nextcloud/spreed/issues/9504)
> Release 15.0.6

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Allow to mark conversations unread in the sidebar [#9366](https://github.com/nextcloud/spreed/issues/9366)
- Make self-joined users persistent members when assigning permissions [#9434](https://github.com/nextcloud/spreed/issues/9434)
- Special characters are HTML encoded when selecting an Emoji from the picker [#9545](https://github.com/nextcloud/spreed/issues/9545)
- Fix missing "New message" form on share and files app integration [#9532](https://github.com/nextcloud/spreed/issues/9532)
- Fix diverging user status between top bar and conversation list [#9419](https://github.com/nextcloud/spreed/issues/9419)
- Fix call summary when a user has a full numeric user ID [#9502](https://github.com/nextcloud/spreed/issues/9502)
- Fix mentions of groups with spaces in …
> Release 16.0.4

- src/composables/useViewer.js
* Fix https://github.com/nextcloud/spreed/pull/9596#issuecomment-1560640396
To work correctly in the Fullscreen mode, the Viewer should be mounted in Talk Vue app (`#content-vue`). Currently, it is moved from the body to `#content-vue` only once on Viewer open. It doesn't help when Fullscreen mode is enabled or disabled after the Viewer was opened.
See also: https://github.com/nextcloud/spreed/pull/6879
This PR moves the Viewer to `watch`.
Currently, there is a 1000ms timeout to wait until Viewer was mounted. But 1 second too much.
This PR uses `nextTick` to wait for one Vue scheduler iteration is enough.
Now opening a file is almost 1000ms faster in Talk 😀
> Fix Viewer with Fullscreen mode toggle

- CHANGELOG.md
- fix(CallView): Fix Fullscreen mode support in ViewerOverlay [#9618](https://github.com/nextcloud/spreed/issues/9618)
- fix(chat): Update own read marker before triggering events when posting [#9612](https://github.com/nextcloud/spreed/issues/9612)
> chore(release): Some changelog additions for 17.0.0-rc.2

- .drone.jsonnet
- .drone.yml
- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(reactions): Fix own call reactions when the high-performance backend is used [#9586](https://github.com/nextcloud/spreed/issues/9586)
- fix(mediasettings): Hide virtual background options when not supported [#9611](https://github.com/nextcloud/spreed/issues/9611)
- fix(mediasettings): Fix broken aria-label [#9617](https://github.com/nextcloud/spreed/issues/9617)
- fix(CallView): Fix Fullscreen mode support in ViewerOverlay [#9613](https://github.com/nextcloud/spreed/issues/9613) [#9618](https://github.com/nextcloud/spreed/issues/9618)
- fix(CallView): fix no local video on empty call in not grid mode [#9584](https://github.com/nextcloud/spreed/issues/9584)
- fix(chat): Update own read marker before triggering events when posting …
> Release 17.0.0 rc.2

- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/store/fileUploadStore.js
> fix(MediaSettings): Fix guests being prompted with login window when blurring background

- docs/call.md
> fix(docs): Document end call for everyone parameter

- docs/HPB-log-simplifier.sh
Creates a neutralized and simplified log from the HPB logs by:
1. Replacing "user sessions" with "userX"
2. Replacing "room sessions" with "sessionX"
E.g. the following line:
```
May 26 13:31:36 server nextcloud-spreed-signaling[726]: clientsession.go:425: Session tooJzGsaUllvfGXdh3-74-yjAt-L9gCQKrs_U-DlLkZ8PTBabmJub3J6bEFGNEV6UnRZdEl2ZHpvUnJKMDNtSkFxZHBxZWR1X3VWUkJuZWllc2VUNko0RTFxLURaRXJyYjJ6ckc4dFBJRVVhT0lOLWR5RGtCM1R2MFpRemd3ZUFSLU9qWDZkR3FEQjR6MGt6c3p0VG92NmhqeEFEQkotN1JHM0lnbHl2ODRlbVRDaUlnQlhFQ3M1U1U2MDl4eWc4SU5MR0xjdTlUa0xaSmJqWGJ8Njk4NzAxNTg2MQ== joined room token123 with room session id P9roBo5O0EnRR8N4r+64MMdSHO2tu2ffNqjtICwSG43AHWL3XKn6XYv9xdYCgUYufxiCzIvg/QQk7cv8Uda1uhyDgh1FLPLCdjUe4uHJWKXb31rHig3gm+FdvOEO3GHEcKlJyPtSZzTupiatpanalRvMi6xR3jIXYoGcuvc//R2gzKFYNZQKwGdXXLMHNNHTlHPS …
```
> feat(docs): Add a script that allows reading the HPB log more easily

- docs/global.md
- docs/index.md
- lib/Middleware/CanUseTalkMiddleware.php
- lib/Middleware/Exceptions/UnsupportedClientVersionException.php
- mkdocs.yml
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/integration/outdated-client.feature
* API throws an exception and returns with a `426 Upgrade Required` status code
> feat(API): Allow to block older clients

- src/components/LeftSidebar/ConversationsList/Conversation.vue
* Fix issue with bold weight for Firefox
---|---
> Correct Font weight for Subtitle

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(MediaSettings): Fix guests being prompted with login window when blurring background [#9620](https://github.com/nextcloud/spreed/issues/9620)
- fix(TypingIndicator): Actors are only unique by type and id [#9625](https://github.com/nextcloud/spreed/pull/9625)
> Release/17.0.0 rc.3

- src/components/ConversationSettings/ConversationAvatarEditor.vue
* Fix #9565 
* Correct styles to wrap child elements in flex container for small screen resolutions
---|---
> Responsive layout for `ConversationAvatarEditor`

- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
* Regression from #9465 
To test:
* have a user group (`admin` is default one)
* type group name in search field
* click on a search result -> create conversation modal should be opened
---|---
> Fix error when creating a conversation from search results

- src/components/MediaSettings/VideoBackgroundEditor.vue
* Follow-up for #9710 
🏡 After (if name isn't presented)
> Add fallback if label for background fileName doesn't exist

- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageTypingIndicator.vue
- src/store/participantsStore.js
- src/store/quoteReplyStore.js
- src/utils/SignalingTypingHandler.js
- src/utils/SignalingTypingHandler.spec.js
* Fix #9589 
* Fix #9604
* Fix #9615
* Fix #9624
---|---
---
After the first key stroke, we send first `true` signal start to watching after input value, if it was changed within intervals:
* 0-10s: if something else was typed, after 10s from the start we send another `true` signal;
* 10-20s: if still typing, after 20s from the start we send another`true` signal;
* ... and repeat for each 10s interval.
In that case, first possible `true` signal will be received in 0s + delay after actor started typing;
consequent signals will come every 10s + delay.
---
`false` signal will be received:
* after actor sent message: in 0s + delay;
`false` signal will be set locally by client:
* after actor left chat: in 0s;
* after actor stopped typing (input value wasn't changed in 10s …
> Adjust typing indicator behaviour

- src/components/ConversationIcon.vue
- src/components/LoadingPlaceholder.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/components/NewMessage/NewMessage.vue
- src/utils/isDarkTheme.js
* Fix #9720
* Fix https://github.com/nextcloud/talk-desktop/issues/45
🏚️ Before LoadingPlaceholder | 🏡 After LoadingPlaceholder
---|---
Default on 🌑 Dark system |
🌑 Dark theme with 🌑 Dark system |
🌕 Light theme with 🌑 Dark system |
Default on 🌕 Light system  |
🌕 Light theme with 🌕 Light system |
🌑 Dark theme with 🌕 Light system |
In Nextcloud we have CSS variables for themes:
1. `:root` - default values based on system `preferred-color-scheme`
2. On `<body>` - set by current theme if not "System default theme" is used in settings. These styles override defaults.
The `LoadingPlaceholder` used variables from `documentElement` (`:root`) instead of `body`. It caused a problem when the system-preferred theme was not equal to the selected in Nextcloud settings.
- Render the component right away …
> Fix dark/light theme in `LoadingPlaceholder` and refactor dark theme detection

- CHANGELOG.md
- fix(chat): Fix dark/light theme in messages loading placeholder
[#9720](https://github.com/nextcloud/spreed/issues/9720)
- fix(TypingIndicator): Signaling messages wrong when conversation is switched
[#9615](https://github.com/nextcloud/spreed/issues/9615)
- fix(TypingIndicator): Typing indicator does not "expire"
[#9604](https://github.com/nextcloud/spreed/issues/9604)
- fix(TypingIndicator): Typing indicator distorted on small sidebar during call when 3 or more people are typing
[#9589](https://github.com/nextcloud/spreed/issues/9589)
- fix(mediasettings): Aria label keywords of virtual backgrounds are not translatable
[#9610](https://github.com/nextcloud/spreed/issues/9610)
- fix(mediasettings): Conversation picture picker does not work well on mobile …
> chore(release): Add changelog for 17.0.0-rc.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(chat): Fix dark/light theme in messages loading placeholder
[#9720](https://github.com/nextcloud/spreed/issues/9720)
- fix(TypingIndicator): Signaling messages wrong when conversation is switched
[#9615](https://github.com/nextcloud/spreed/issues/9615)
- fix(TypingIndicator): Typing indicator does not "expire"
[#9604](https://github.com/nextcloud/spreed/issues/9604)
- fix(TypingIndicator): Typing indicator distorted on small sidebar during call when 3 or more people are typing
[#9589](https://github.com/nextcloud/spreed/issues/9589)
- fix(mediasettings): Aria label keywords of virtual backgrounds are not translatable
[#9610](https://github.com/nextcloud/spreed/issues/9610)
- fix(mediasettings): Conversation picture picker does not work well on mobile …
> Release/17.0.0 rc.4

- src/components/LeftSidebar/LeftSidebar.vue
* Follow up for #9508 
* Previously we're waiting for server response to emit the event, that toggle sidebar. Now we do it after changing the route
* Emitting the event comes from participantsStore async action `joinConversation`, which is called only on switching the conversations
* Action is also called on App.vue `beforeMount()`, but sidebar toggling is also handling by App itself
🏚️ Before
https://github.com/nextcloud/spreed/assets/93392545/1ad58e8c-0c1d-4692-a661-b4ae70d3ac10
🏡 After
https://github.com/nextcloud/spreed/assets/93392545/81d287ec-9629-4e93-8b94-4436c88aff40
> Close sidebar on mobile resolution immediately after changing the route

- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
* Fix #9725  (according to reproduce method cc @SystemKeeper )
* In addition:
* Move and rename `LocalMediaControls` => `TopBar/TopBarMediaControls` (only usage of component)
* Move "Lower Hand" from `TopBarMediaControls` to `TopBarMenu` to reduce amount of duplicated methods
No visual changes, button doesn't dissapear anymore
> Fix displaying 'Screensharing' button after reject and refactor `TopBar` controls for 'Raise hand' and 'Screensharing'

- src/components/CallView/Grid/Grid.vue
* Fix #9505
🏚️ Before: see issue
🏡 After:
Without hover | With hover
---|---
> Make pagination buttons in call (grid, stripe views) visible on call view hover

- CHANGELOG.md
- Conversations can now have an avatar or emoji as icon
[#927](https://github.com/nextcloud/spreed/issues/927)
- Virtual backgrounds are now available in addition to the blurred background in video calls
[#9251](https://github.com/nextcloud/spreed/issues/9251)
- Reactions are now available during calls
[#9249](https://github.com/nextcloud/spreed/issues/9249)
- Typing indicators show which users are currently typing a message
[#9248](https://github.com/nextcloud/spreed/issues/9248)
- Groups can now be mentioned in chats
[#6339](https://github.com/nextcloud/spreed/issues/6339)
- Call recordings are automatically transcribed if a transcription provider app is registered
[#9274](https://github.com/nextcloud/spreed/issues/9274)
- Chat messages can be translated if a translation provider app is …
> chore(release): Add changelog for 17.0.0

- src/components/ConversationSettings/EditableTextField.vue
> Make conversation name and description selectable

- src/components/LoadingPlaceholder.vue
Backport of https://github.com/nextcloud/spreed/pull/9721
Avatars and mentions are working differently on stable26, so only placeholders are fixed with this PR.
Tested on Chrome + Ubuntu for light against dark themes
> [stable26] Fix dark/light theme in `LoadingPlaceholder`

- src/components/CallView/Grid/Grid.vue
* Fix #9767 
* As per discussion (and overall positive opinion on 8px offset), grid navigation buttons in call were adjusted
> Adjust navigation buttons offset for call in Grid view

- src/components/CallView/shared/ReactionToaster.vue
* Fix #9772
* Registered users always have a display name (as far as i know), so if it's empty, it's probably a guest. We could then look if guestName is set in the store, and if it's empty, return `t('spreed', 'Guest')`
---|---
> Show `Guest` to self when guest reacts in call with no name

- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
* Fix #9761 
The navigation bar is used to float over the content. Now it is fixed at the bottom.
---|---
> Prevent the navigation bar from floating

- src/components/LeftSidebar/LeftSidebar.vue
During the discussion of https://github.com/nextcloud/spreed/pull/9706 I missed that in Vue 2 `ref` on `v-for` is always an array and its order is **not guaranteed to match** the order of the `v-for` source. It has initial order in `$refs` and always puts new nodes in the end.
See Evan's comment: https://github.com/vuejs/vue/issues/4952#issuecomment-280661367
It caused a problem with scrolling with newly created conversations (and with reordered ones).
**Step to reproduce:** create 10 new chats, do not reload the page
**Expected:** it scrolls to the newly created chat after the creation or after joining
**Actual:** it scrolls to the first chat because the new chat has index 0 in the data but the last index in the `$refs`.
---|---
Use an unique ref name for each …
> fix(LeftSidebar): fix scroll with new created conversations

- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/services/filesSharingServices.js
* Fix #9779
* Regression from https://github.com/nextcloud/spreed/commit/5ae4c8207f03887ecfd6fec5f6510a1d66689888 - joining of empty template with others into one array
* `this.selectedTemplate?.filename` checks for the path to file, for example, `Templates/Filename.md`. With `/Blank` file, we receive a search error, but file will still be created in `Talk` folder
To reproduce:
1) in Files, click "+" => "Set Templates folder" (could be wrong with button title)
2) Add some templates [from there](https://github.com/nextcloud/example-files/tree/master)
3) in Talk, click :paperclip: => "New text file"
4) Try to create a file with Blank or any of the existing templates
5) Everything should work
5.1) Or use only steps 3-4, template is Blank by default
> fix(NewMessageNewFileDialog) - fix creation of file from Blank template

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
* Follow-up to #9815 
🏡 After (Message view, voting) | 🏡 After (results)
---|---
> follow-up (Poll) - change description for open polls

- lib/Signaling/BackendNotifier.php
- tests/php/Signaling/BackendNotifierTest.php
* Fix #9726 
```json
{
"type": "event",
"event": {
"target": "participants",
"type": "update",
"update": {
"roomid": "...",
"users": [
{
"sessionId": "...",
"participantType": 1,
"participantPermissions": 254,
"userId": "test",
"displayName": "test",
"inCall": 0,
"lastPing": 1686409598
},
{
"participantPermissions": 246,
"displayName": "ABC",
"inCall": 0,
"lastPing": 1686409598,
"sessionId": "...",
"participantType": 4
}
]
}
}
}
```
I don't think we need a capability for this. If the property is there we can use it, otherwise we have the same as we currently have.
CC: @mahibi
> Include display name in participant update message

- src/components/CallView/Grid/Grid.vue
* Fix #9203 
* Stripe wrapper min-width was set to auto, which prevent it from shrinking => as a result, LocalVideo goes out of screen borders
* After fixing that, noticed that columnsMax calculation doesn't consider gaps between video frames => videos also overflowing screen
:warning: To switch call to the devMode, pass boolean prop `dev-mode` to Grid.vue 
---|---
> fix(Grid) - finetune columns calculations

- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Maybe fix #9630
* Decrease re-rendering time for `LeftSidebar` on re-fetching conversations every 30 seconds when:
- External signaling is using
- This is not full re-fetching every 5 minutes
- In comparison, compare `lastActivity` and old `lastActivity`, not `modifiedSince`
- In addition, cache conversations list with KeepAlive to make returning from search fast
- See: https://github.com/nextcloud/spreed/pull/9833
- Instead, decrease number of any state changes by full property comparison
- Works with any signaling
- Also works on 5-minute full re-fresh
- Not domain-specific, a bit more code, but universal solution
- See: https://github.com/nextcloud/spreed/pull/9811
- Instead/In addition use virtual scrolling
- Increase `LeftSidebar` performance in general in any …
> Optimize conversations update on Frontend

- package-lock.json
- package.json
> Chore(deps): Bump emoji-mart-vue-fast from 12.0.5 to 15.0.0

- CHANGELOG.md
- appinfo/info.xml
- Include display name in participant update signaling message [#9822](https://github.com/nextcloud/spreed/issues/9822)
- Improve frontend responsiveness with many conversations [#9841](https://github.com/nextcloud/spreed/issues/9841)
- Don't make the conversation list scroll when the selected conversation is already visible [#9782](https://github.com/nextcloud/spreed/issues/9782) [#9796](https://github.com/nextcloud/spreed/issues/9796)
- Fix creating files from the "Blank" template option [#9818](https://github.com/nextcloud/spreed/issues/9818)
- Make conversation description and name selectable [#9780](https://github.com/nextcloud/spreed/issues/9780)
- Hide poll voting details when not filled [#9821](https://github.com/nextcloud/spreed/issues/9821) …
> chore(release): Add changelog for 17.0.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Include display name in participant update signaling message [#9822](https://github.com/nextcloud/spreed/issues/9822)
- Improve frontend responsiveness with many conversations [#9841](https://github.com/nextcloud/spreed/issues/9841)
- Don't make the conversation list scroll when the selected conversation is already visible [#9782](https://github.com/nextcloud/spreed/issues/9782) [#9796](https://github.com/nextcloud/spreed/issues/9796)
- Fix creating files from the "Blank" template option [#9818](https://github.com/nextcloud/spreed/issues/9818)
- Make conversation description and name selectable [#9780](https://github.com/nextcloud/spreed/issues/9780)
- Hide poll voting details when not filled [#9821](https://github.com/nextcloud/spreed/issues/9821) …
> Releasing 17.0.1

- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageTypingIndicator.vue
* Fix [typing indicator is too close to the message input](https://github.com/nextcloud/spreed/issues/9719)
* Fix typing indicator overlays the message above
---|---
> fix(styles): prevent typing indicator overlay

- docs/TURN.md
- docs/coturn.md
- docs/eturnal.md
- docs/index.md
- mkdocs.yml
* Follow up #9816 
---|---
One document `doc/TURN.md` | Three documents: `doc/TURN.md` as overview, `doc/coturn.md` & `doc/eturnal.md`
Please have a look into the changes of the documentation page. 
Please also see, if mentioning the prometheus exporter is something to be added into the documentation:
https://github.com/processone/eturnal/pull/41
> Documentation: Add eturnal as a second TURN server example

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
- src/mixins/arrowNavigation.js
* Fixes #9677 
* The search box gets expanded when it is focused on to cover the filter button. 
* During the textual search operation, no filter can be applied
---|---
Default View 
Focused on input or during the textual search
> Filter conversation list for unread / mentioned conversations only

- src/components/ChatView.vue
- src/components/MessagesList/MessagesList.vue
* Follow-up from #9826 (cc @dijeth )
* Scroll button was moved to the parent component level
* Its position updated based on NewMessage component's height (which is updated if someone is typing)
---|---
> follow-up(ChatView) - align scroll button position with mobile clients

- lib/Activity/Listener.php
- lib/Activity/Provider/Base.php
- lib/Activity/Setting.php
- lib/BackgroundJob/CheckHostedSignalingServer.php
- lib/BackgroundJob/CheckMatterbridges.php
- lib/BackgroundJob/CheckReferenceIdColumn.php
- lib/BackgroundJob/ExpireChatMessages.php
- lib/BackgroundJob/ExpireSignalingMessage.php
- lib/BackgroundJob/RemoveEmptyRooms.php
- lib/BackgroundJob/ResetAssignedSignalingServer.php
- lib/BackgroundJob/RetryJob.php
- lib/Chat/AutoComplete/SearchPlugin.php
- lib/Chat/Changelog/Listener.php
- lib/Chat/Changelog/Manager.php
- lib/Chat/ChatManager.php
- lib/Chat/Command/Executor.php
- lib/Chat/Command/Listener.php
- lib/Chat/MessageParser.php
- lib/Chat/Notifier.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Chat/ReactionManager.php
- lib/Chat/SystemMessage/Listener.php
* Using PHP8's constructor property promotion in the following namespaces:
- `/lib/Activity`
- `/lib/BackgroundJob`
- `/lib/Chat`
> Use PHP8's constructor property promotion

- recording/server.conf.in
- recording/src/nextcloud/talk/recording/Config.py
- recording/src/nextcloud/talk/recording/Participant.py
- recording/src/nextcloud/talk/recording/Service.py
I've been having issues with Firefox in my network setup, as described in this issue:
- [TURN access : no CONNECT launched if the DNS resolution can't be done locally](https://bugzilla.mozilla.org/show_bug.cgi?id=1239006)
Chromium-based web browsers do not have this issue.
This PR provides support for Chromium.
> Chromium recording

- appinfo/info.xml
- appinfo/routes.php
- appinfo/routes/routesCertificateController.php
- lib/BackgroundJob/CheckCertificates.php
- lib/BackgroundJob/CheckTurnCertificate.php
- lib/Controller/CertificateController.php
- lib/Controller/RecordingController.php
- lib/Controller/SignalingController.php
- lib/Notification/Notifier.php
- lib/Service/CertificateService.php
- src/components/AdminSettings/RecordingServer.vue
- src/components/AdminSettings/SignalingServer.vue
- src/components/AdminSettings/TurnServer.vue
- src/services/certificateService.js
- tests/php/Controller/SignalingControllerTest.php
- tests/php/Service/CertificateServiceTest.php
Fixes #9606 
This PR adds a background job which checks the certificate of the TURN server (if `turns:` is used) and sends a notification to admins when the certificate is about to expire (less than 10 days).
Adding a test for this is a bit above my head - not sure how this can be done.
> Add background job to check TURN certificate

- recording/src/nextcloud/talk/recording/BackendNotifier.py
Follow up to #9253 (specifically, https://github.com/nextcloud/spreed/pull/9253/commits/d166a8b994dc393532fa7ea9bde87aacecd6ca57#diff-9dcf622fec2ddba84dbc38fbb90bad7f1d4b7893d4ce299d6cfcc846275df193L71-R71)
By default `urlopen` from `urllib3` raises an exception if the response is an HTTP error. However, `session.send` from `requests` does not, so [it must be explicitly checked](https://requests.readthedocs.io/en/latest/api/#requests.Response.raise_for_status). Otherwise if the Nextcloud server returns an error the recording server would not abort the current operation as expected, leading to confusion and head-scratching :-)
> Raise exception if the Nextcloud server responded with an HTTP error

- recording/src/nextcloud/talk/recording/__init__.py
Follow up to #9632
The recording server ~~uses~~ used [`Mozilla/5.0 (Recording) Nextcloud-Talk vXXX` as its user agent](https://github.com/nextcloud/spreed/blob/82fdadf29511587611072b0a761bc354144a0bf7/recording/src/nextcloud/talk/recording/__init__.py#L26), which wrongly matched with the regular expression for the desktop client.
Moreover, as the recording server version is lower than the minimum allowed desktop client version the recording server requests were blocked by the Nextcloud server.
~~[The regular expression provided by the Nextcloud server](https://github.com/nextcloud/server/blob/3ecd85f817a0508618e122cf77efe1834a948ebe/lib/public/IRequest.php#L80-L83) would need to be updated as well; it is used in [the inital check](https://github.com/nextcloud/spreed/blob/67c22f97d7d9a10fe …
> Adjust user agent for recording server to not match with desktop client

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/test-setup.js
* Fix / supress Jest logging output:
* Error searching for open conversations
* [Vue warn]: Missing required prop
* Error: Could not parse CSS stylesheet
---|---
~3,000 lines | ~750 lines
> chore(Jest) - clear jest output

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
* Fix #9129 
https://github.com/nextcloud/spreed/assets/93392545/22a53289-c90a-4cea-b3ec-ac0fd1c67368
> fix(MessagesList) - scroll sticky list to bottom, if reaction was added

- psalm.xml
- tests/psalm-baseline.xml
Required to ensure return types are 100% correct.
> Enable less/more specific errors

- package-lock.json
- package.json
* Rebase of #9562 
* Tested on web client (Chrome + Linux)
> chore(deps) - bump @nextcloud/event-bus from 3.0.2 to 3.1.0

- package-lock.json
- package.json
- webpack.common.config.js
* Remove unused dependencies from project:
| Package name | Added since | Unused since |
| --- | --- | --- | 
| `color.js` |  #4985 | #6798 |
| `url-parse` |  #2891 | #9915 |
| `vue-resize` |  #3739 | #4985 |
| `extendable-media-recorder-wav-encoder-worker` |  #5903 | shipped with `extendable-media-recorder-wav-encoder` |
| `workbox-webpack-plugin` |  #5903 | never used |
| `terser-webpack-plugin` |  #5903 | never used |
| `webpack-node-externals` |  #2185 | never used |
> chore(deps) - remove unused dependencies

- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Model/Message.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/reply.feature
> fix(chat)!: Remove threads v1 API changes

- package-lock.json
- package.json
- webpack.common.config.js
Manual backport of #9975 
Tested on web client, main + files sidebar (Chrome, Linux)
> [stable27] chore(deps) - remove unused dependencies

- src/store/conversationsStore.js
* Attempt to contribute to #9630 
* If you think it makes sense, we can also apply it here: https://github.com/nextcloud/spreed/blob/04c973ed6aee1d8113ccf44d91b5431b954d6c70/src/mixins/getParticipants.js#L145-L153
> fix(status): Don't emit event when the user status did not update

- recording/src/nextcloud/talk/recording/Benchmark.py
- recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py
- recording/src/nextcloud/talk/recording/Service.py
Well, this fix is an embarrasing one :-P I do not know what I was thinking on when I wrote the code... And it also took me way longer than I would like to admit to figure out what was going on when I hit the bug :facepalm:
[In PulseAudio sinks are output devices, like headphones, and playback streams are written to them, while sources are input devices, like microphones, and recording streams are read from them.](https://gavv.net/articles/pulseaudio-under-the-hood/#devices-and-streams)
It is not possible to directly read data from a sink. However, for each sink a monitor, which is a virtual source, is automatically created, thus making possible to read the data written to the sink using the monitor.
The recording server creates a null sink for each browser instance to write the output …
> Fix trying to use an audio sink as source

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesList.vue
- src/services/messagesService.js
- src/services/messagesService.spec.js
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
Splitted by commits:
* Fix frequently logging errors and warnings in console:
* Uncaught TypeError "Cannot read properties of undefined" for reactions
* 'focus-trap' error when hover over reaction to message (solves partially #7970)
---
* Limit lookForNewMessages request with default fetch limit (100 messages)
* Fix store regression which leads to unnecessary fetch requests
🖼️ Screenshots: see https://github.com/nextcloud/spreed/pull/9897#discussion_r1265303851
---
* Refactor message grouping with soft update of store
* check previous and new state for changes: now only groups with changes will be re-rendered (probably fix #8880)
---
* Adjust scroll position when loading new / old messages
* now list remains on the same place after re-render and don't jump up-down because of loader insert …
> fix(MessagesList) - performance, search fixes and minor refactoring

- package-lock.json
- package.json
We use global Jest function without typings. IDEs doesn't understand them, show warnings and no auto-complete.
`@types/jest` adds global jest typings.
**Alternative solution**: use `@jest/globals` with explicit import everywhere:
```js
import { describe, it, test, expect, jest } from '@jest/globals'
describe('...', () => {
it('..', () => {})
})
```
**Docs**: https://jestjs.io/docs/getting-started#type-definitions
---|---
JetBrains IDEs | -
Microsoft VSCode | -
JetBrains Fleet | -
> chore(deps): add @types/jest

- CHANGELOG.md
- Automatic transcription of call recordings is now opt-in  [#9971](https://github.com/nextcloud/spreed/issues/9971)
- Fix position of "Scroll to bottom" button in the chat view  [#9871](https://github.com/nextcloud/spreed/issues/9871)  [#9858](https://github.com/nextcloud/spreed/issues/9858)
- Improve accessibility of conversation creation dialog  [#9954](https://github.com/nextcloud/spreed/issues/9954)
- Make chat stay scrolling when the last message receives its first reaction  [#9956](https://github.com/nextcloud/spreed/issues/9956)
- Don't emit event when the user status did not change on refetching  [#10005](https://github.com/nextcloud/spreed/issues/10005)
- Attempt to further improve the performance of conversation list updates with hundreds of conversations …
> chore(release): Add changelog for 15.0.7, 16.0.5 and 17.0.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 16.0.5

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 17.0.2

- recording/src/nextcloud/talk/recording/Config.py
> Don't require a global backened secret when allowall is not set

- jest.config.js
* Regression from #9919 
* After bumping #9915, all the packages are using a new major version of `axios`, which makes it unnecessary to map it with CJS module 
* Affects only Jest work, so as long as tests have passed, rest should be fine
> Revert mapping of cjs module

- src/components/MessagesList/MessagesList.vue
* Fix Vue warn errors in the console, when joining the call:
* In that moment we destroying main `MessageList` component and creating a new one in the sidebar
* Although `this.$nextTick` is an async function, and it will be called after unmounting, then `this.$refs.scroller` isn't existing already
---|---
> fix(MessagesList) - check if list is rendered before scrolling

- src/components/MessagesList/MessagesList.vue
* Regression from #9897 
* When post a new message (not the first in the message group), response from server replaces temporary message, but group length remains the same, and component with temp message won't re-render => infinite loading
---|---
> fix(MessagesList) - check for temporary messages while soft updating

- src/components/ConversationIcon.vue
- src/components/ConversationSettings/BasicInfo.vue
- src/components/ConversationSettings/ConversationAvatarEditor.vue
* Hide unused description and status in conversation settings for 1-1 conversation
---|---
> hide description and status from 1-1 conversation settings

- src/components/RightSidebar/RightSidebar.vue
> fix(SIP): Show SIP info also when enabled without user PIN

- CHANGELOG.md
- Fix duplicate messages and improve performance [#10070](https://github.com/nextcloud/spreed/issues/10070)
- fix(SIP): Show SIP info also when enabled without user PIN [#10064](https://github.com/nextcloud/spreed/issues/10064)
- fix(settings): Hide description and status from 1-1 conversation settings [#10057](https://github.com/nextcloud/spreed/issues/10057)
> chore(release): Add changelog for 17.0.3

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
* Fix #9974
* The new conversation '+' button is now hidden when the search field is expanded
* The abort search button is visible whenever the search box is focused.
* The list gets immediately cleared out from filters once the search field is clicked on. 
* If the search results are empty, a new button shows up to quickly create a conversation with the search text as a name
* The animation is more expedited ( set to 0.15s instead of 0.3s) as it requires to be quick.
https://github.com/nextcloud/spreed/assets/84044328/0f19a2ef-9d79-4573-8f0c-19f4e3ed8310
And if the search results are empty, you can create a new conversation with the search text, it will be set to private by default.
Before
After
> fix(searchBox) - Conversation search UX improvements 

- lib/Service/RecordingService.php
- tests/integration/features/callapi/recording.feature
Before:
```
var_dump(!'no' === 'yes');
bool(false)
var_dump(!'yes' === 'yes');
bool(false)
```
> fix(recording): Fix transcription opt-in

- docs/chat.md
- lib/Model/Message.php
> [stable27] feat(chat): Add a property to indicate whether markdown should be rendered

- jest.config.js
- package-lock.json
- package.json
- src/__mocks__/axios.js
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/services/conversationsService.spec.js
- src/services/filesSharingServices.spec.js
- src/services/messagesService.spec.js
- src/views/RoomSelector.spec.js
Manual backport of #9919 and #10021
Tested in conversations, chats, calls on web client
> [stable27] chore(deps): Bump @nextcloud/axios from 2.3.0 to 2.4.0

- appinfo/routes/routesChatController.php
- docs/capabilities.md
- docs/chat.md
- lib/BackgroundJob/ChatMessageReminder.php
- lib/Capabilities.php
- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Controller/ChatController.php
- lib/Notification/Notifier.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/recording.feature
- tests/integration/features/chat-2/reminder.feature
- tests/php/CapabilitiesTest.php
- tests/php/Chat/ChatManagerTest.php
- tests/php/Notification/NotifierTest.php
> feat(notification): 🔔 API for "Remind me later"

- src/components/TopBar/CallTime.vue
- src/store/messagesStore.js
* Fix #9947 
The Hint text 
[ [design](https://github.com/nextcloud/spreed/issues/6212#issuecomment-1623340533)]
> Note the call is running since 1 hour already. 
* The Hint gets shown at 1:00:00, and the popover stays open for 10s if the user didn't trigger outside focus.
* After that, The Hint remains in the popover and it is accessed by clicking on the call time.
* If the User is a moderator, the hint is added to the recording buttons popover.
This is a recording for a hint faked at 2:20 :
https://github.com/nextcloud/spreed/assets/84044328/8ee08983-3f84-4d30-96b5-9035907d8c0f
The moderator's popover ( e.g in case the recording is starting)
If you don't want to wait for one hour, change this line and you can only wait for 20 sec and it can be repeated with 1 min interval.
``` …
```
> feat(CallTime)- add one hour hint during the call

- docs/TURN.md
- docs/coturn.md
- docs/eturnal.md
- mkdocs.yml
---|---
https://nextcloud-talk.readthedocs.io/en/latest/ | https://nextcloud-talk.readthedocs.io/en/bugfix-noid-fix-docs-navigation/
Root page shows "Turn" as selected | Turn is it's own section and the normal "Overview" is opened
> fix(docs): Fix navigation nesting of the documentation

- composer.lock
- lib/AppInfo/Application.php
- lib/Chat/SystemMessage/Listener.php
- lib/Share/Listener.php
- psalm.xml
- tests/psalm-baseline.xml
- tests/stubs/Symfony_Component_EventDispatcher_GenericEvent.php
* Ref https://github.com/nextcloud/server/pull/38546
* Missing app icon in top bar
* System messages are broken
---|---
> fix: Stop using Symfony event dispatcher directly

- lib/Chat/SystemMessage/Listener.php
- lib/Events/AlreadySharedEvent.php
* Followup to #10078 
* Actually the red CI was not only because of the broken guests app, but also because of this little fail here.
> Fix already shared event

- src/components/ConversationSettings/BotsSettings.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/constants.js
- src/services/botsService.js
- src/stores/bots.js
* Close #9676 
* Rebased on top of #9458 
| 🏡 After |
|--- |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/2bf1f5a7-ab14-47b5-9cd4-cf1094c1b4ce) |
Notes:
- to test install https://github.com/nextcloud/call_summary_bot
- to mock bot for the list, modify the code in store as follows:
```
async updateBotsInformation(token) {
...
response.data.ocs.data.concat([
{ id: 122, name: 'Dummy bot 1 ', description: 'It does nothing', state: 0 },
{ id: 123, name: 'Dummy bot 2 ', description: '  - This program is free software...', state: 2 },
]).forEach((bot) => {
...
```
> feat(ConversationSettings) - add frontend support for enabling bots / webhooks

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/composables/useCombinedSystemMessage.js
* Fix #9678
* New component and util for handling groups of system messages added
* Combine messages for following actions:
* participants being added to the conversations
* participants promoted to / demoted from moderators
* participants joined / left the call
* participant reconnected to the call
* Light sort of messages within one group:
`user added/removed` => `moderator promoted/demoted` => `call started` => `recording started` => `call joined/left` => `call ended`
---|---
> feat(MessageGroup) - group system messages

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/TopBar/CallTime.vue
- src/store/participantsStore.js
- src/utils/formattedTime.js
- src/utils/webrtc/SpeakingStatusHandler.js
- src/utils/webrtc/index.js
- src/utils/webrtc/simplewebrtc/localmedia.js
- src/utils/webrtc/webrtc.js
* Close #9903 
* Known issues:
* Signaling server doesn't notify for leaving participants - they're still could 'speaking' for 5 seconds
* Follow-ups:
* Share speaking time information between models on connection
* Test on force reconections https://github.com/nextcloud/spreed/pull/10068#pullrequestreview-1565565757
---|---
For currently speaking: | ![image](https://github.com/nextcloud/spreed/assets/93392545/82cf2ceb-f38f-4f6b-be47-ac7d6de879da)
> feat(Participant) - count total talking time within call for participants

- src/components/LeftSidebar/LeftSidebar.vue
Seems to be a regression of: https://github.com/nextcloud/spreed/pull/9068
"Unread mentions" button doesn't appear anymore.
---|---
> Fix "Unread mentions" button appearing

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesList.vue
- src/services/remindersService.js
* Fix #10076
* Add an item into MessageButtonsBar (with submenu)
Main menu | Sub menu
--- | ---
https://github.com/nextcloud/spreed/assets/93392545/b5caa45d-d950-41ad-be25-91e61abec5f7
> feat(Message) - 🔔 add frontend support for message reminders

- src/components/ChatView.vue
> fix(ChatView) - adjust 'scrollToBottom' button position in call

- lib/Notification/Notifier.php
Judging from the german translations for the reminder feature, the intention of this feature was not clear. To help translators, we add a comment for these strings.
CC: @rakekniven
> Add notes for translators for reminder feature

- lib/Controller/PageController.php
- lib/Controller/RoomController.php
Since the metadata field was extended to track the password and token separately the metadata comparison on the reset did not match anymore.
* Ref https://github.com/nextcloud/spreed/pull/9367
> fix(bruteforce): Fix resetting the bruteforce protection

- Makefile
* Ref from https://github.com/nextcloud/spreed/issues/10166
> fix(release): Exclude .editorconfig from release package

- CHANGELOG.md
- 🤖 Add support for bots via webhooks  [#10139](https://github.com/nextcloud/spreed/issues/10139)  [#10151](https://github.com/nextcloud/spreed/issues/10151)
- 🔣 Add Markdown support for chat messages  [#10089](https://github.com/nextcloud/spreed/issues/10089)  [#10090](https://github.com/nextcloud/spreed/issues/10090)
- 👤 Allow to filter the conversation list for unread mentions and messages  [#10093](https://github.com/nextcloud/spreed/issues/10093)
- 🗺️ Provide an overview list of open conversations  [#10095](https://github.com/nextcloud/spreed/issues/10095)
- 🔔 Set a reminder to get notified about a chat messages at a later time  [#10104](https://github.com/nextcloud/spreed/issues/10104)  [#10152](https://github.com/nextcloud/spreed/issues/10152) …
> chore(release): Add changelog for 17.1.0-rc.1

- lib/Controller/PageController.php
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
* Fix tabbing to the main content
* Allow tabbing to the Filter from the search input (when empty) - regression from #9997
* Don't focus the search by default which hides the filter and adding option
---|---
[Bildschirmaufzeichnung vom 2023-08-10, 14-07-53.webm](https://github.com/nextcloud/spreed/assets/213943/05ea3205-4a88-4329-86ac-07297563e214) | [Bildschirmaufzeichnung vom 2023-08-10, 14-07-20.webm](https://github.com/nextcloud/spreed/assets/213943/7f4ba1d1-df6b-4781-95b9-0d7ccb091467)
> Search improvement

- src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
The author's avatar in the messages list has an avatar menu on the Desktop. It causes infinity requests to loop on click and leads to rate limit.
---|---
> fix(desktop): fix disabling avatar menu for desktop

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Aligned with discussion at https://github.com/nextcloud/server/issues/39181
Normal day | Normal day after 17:00 PM | Friday
---|---|---
Saturday | Sunday
> fix(MessageButtonsBar) - adjust predefined reminders conditions

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/store/participantsStore.js
Follow up to #10174
The timestamp is only used to calculate the elapsed speaking time when stopping to speak, so it needs to be updated only when starting to speak. Note that before this change the timestamp was updated not only when changing from `true` to `false, but also from `false` to `undefined` (because `speaking` can be undefined in some cases, for example, [when the media stream is removed](https://github.com/nextcloud/spreed/blob/05c22aa430da92746f34a01920bc986cf19a59db/src/utils/webrtc/models/CallParticipantModel.js#L163)).
@Antreesy Feel free to adjust or even drop any of the commits; I think the code and data state is easier to understand with them, but it can be of course a matter of taste :-)
> Simplify tracking of total counted time

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix `margin`, `color`, and `font-weight` for h1-5 tags
---|---
> align styles for h1-h4 tags

- lib/Controller/AvatarController.php
- lib/Middleware/Attribute/RequireParticipantOrLoggedInAndListedConversation.php
- lib/Middleware/InjectionMiddleware.php
- tests/integration/features/conversation/avatar.feature
> fix(conversations): Allow accessing avatars of listable conversations

- docs/bot-management.md
- docs/index.md
* Bot documentation is missing from the overview
* Documentation about the `admin` endpoint is wrong
> Add bot documentation to overview

- src/components/TopBar/CallTime.vue
Regression from #10086 
The recording buttons should be shown to the moderator(s) only but they were shown to all participants.
> Fix recording buttons conditioned appearing 

- src/components/CallView/CallView.vue
- src/utils/signaling.js
- src/utils/webrtc/SpeakingStatusHandler.js
- src/utils/webrtc/index.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
After a forced reconnection both the Nextcloud and the signaling session ID change. Neither the `peerId` in LocalCallParticipantModel nor the session in the actor store were updated, which caused some issues.
It was mostly visible in the speaking time of the local participant after a forced reconnection, as [the speaking time was no longer updated](https://github.com/nextcloud/spreed/pull/10068#pullrequestreview-1565565757) (due to being set to the previous Nextcloud session ID, which is no longer in the call or conversation); something similar happens for the raised hand. There is also a subtler issue with the typing notifications (being sent to both the previous and current session of the self participant, [as they do not match](https://github.com/nextcloud/spreed/blob/f755a2c8edbdd89581 …
> Fix local participant data not updated after forced reconnection

- src/utils/media/pipeline/VirtualBackground.js
- src/utils/media/pipeline/VirtualBackground.spec.js
- src/utils/webrtc/models/LocalMediaModel.js
Before _wasm-check 2.1.0_ (@ShGKme I knew that the try/catch was there [for a reason](https://github.com/nextcloud/spreed/commit/773d24f1ddfaaf65c9aed0c8148f1a0fffb9b2a8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R88) :-P ) if WebAssembly was disabled in Firefox an exception was thrown when loading _wasm-check_. However, [this was not the expected behaviour, but a bug](https://github.com/MaxGraey/wasm-check/commit/86565b3ca4559257410dd57c4bcc395ee44f88f6). The proper way is to check it using `support()`, which returns `false` if not supported.
Besides that, [when support for using images as a virtual background was added](https://github.com/nextcloud/spreed/pull/9296) _someone_ :-P forgot that `_jitsiStreamBackgroundEffect` is not defined when the virtual …
> Fix checking if WebAssembly is supported for virtual background

- src/utils/signaling.js
- src/utils/webrtc/index.js
Follow up to #7472
When the external signaling server returns the error `token_expired` the signaling settings [are fetched again](https://github.com/nextcloud/spreed/blob/650d0dd4d4f423b7a7c4e03e0d3a7cd972ecb81e/src/utils/webrtc/index.js#L134-L135). However, if there are further requests and `token_expired` is returned again [the previous fetch is canceled](https://github.com/nextcloud/spreed/blob/650d0dd4d4f423b7a7c4e03e0d3a7cd972ecb81e/src/utils/webrtc/index.js#L86) and a new one started instead, which caused the settings to be temporary set to `null`. The signaling settings are expected to always be an object, so setting them to `null` could cause an error if they were used during that time (for example, during a reconnection, which caused the signaling object to "hang" and not do any …
> Fix using signaling settings while being refetched

- src/components/LeftSidebar/LeftSidebar.vue
"Create a new conversation button" is shown in the empty search results for a user who cannot create a conversation
> fix(LeftSidebar): create a conversation button is shown when forbidden

- src/utils/signaling.js
This fixes a regression introduced in #10206
After a force reconnection the local participant state is updated in the store. If the participant is not in a call the call flags will be null, but [the store expects an integer as the call flag, and any value different from 0](https://github.com/nextcloud/spreed/blob/1ac74f976047e6394b26a55d2bb51174b34c2881/src/store/participantsStore.js#L281-L282) (disconnected) [is treated as "in the call"](https://github.com/nextcloud/spreed/blob/1ac74f976047e6394b26a55d2bb51174b34c2881/src/store/participantsStore.js#L66).
This should not happen _in the real world_, as forced reconnections are only triggered during calls and in that case the flags are properly set, but better fix it anyway ;-)
- Add a helper to expose the signaling object, for example, in …
> Fix call view shown if force reconnected when not in a call

- lib/Chat/Parser/SystemMessage.php
- tests/php/Chat/Parser/SystemMessageTest.php
```
[error] 2023-08-18T16:18:59.000 no app in contex Call to a member function isGuest() on null in file '…/lib/Chat/Parser/SystemMessage.php' line 281     
```
```
[debug] 2023-08-18T16:23:04.000 call_summary_bot {"type":"Activity","actor":{"type":"Person","id":"users\/admin","name":"Laura Adams"},"object":{"type":"Note","id":"2165","name":"user_added","content":"{\"message\":\"{actor} added {user}\",\"parameters\":{\"actor\":{\"type\":\"user\",\"id\":\"admin\",\"name\":\"Laura Adams\"},\"user\":{\"type\":\"us│
```
> fix(bots): Fix some system messages for bots

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
LeftSidebar refactoring
- Fix "// TODO": instead of mutating the getter result as computed side effect, move sorting conversations into `conversationsList` getter
- Divide storing all conversations in the LeftSidebar into: "All conversations list" + "Filtered conversations list" + "Search result conversations list"
- It allows to easily add `v-show` (`KeepAlive`) or `VirtualScrolling` in future
- Organize rendering in `LeftSIdebar`
- Make conditions less labyrinthine =D
- Remove duplication in conditions (the "no search result" part)
> refactor(conversations): separate search results and conversations

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/LeftSidebar/LeftSidebar.vue
- src/services/talkBroadcastChannel.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/store/participantsStore.js
- src/store/talkHashStore.js
- src/test-setup.js
- src/utils/requestTabLeadership.js
* Allow to store fetched conversations in BrowserStorage, and recover it instantly from cache, while waiting for a server response
* Conversations updated with `patchConversations()` action, which is called approx. every 30 seconds
* If conversation was deleted, it will be removed from the view with the next full fetch, with redirect to `/apps/spreed/not-found`
---|---
> feat(conversationsStore) - cache conversations to BrowserStorage

- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Part of #10283
* If full fetch was forced from signaling (leader or sub-tab), counter will be reset to 10 again (like we do after usual full fetch)
* cashing was moved to `patchConversations` action called by `fetchConversations` action
* a flag was added to `patchConversations` to watch, if there was changes after fetch to cache them
* `updateConversationIfHasChanged` logic was moved from mutation to the action
---
No due tasks
> follow-up(LeftSidebar) - caching optimization

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/utils/webrtc/SpeakingStatusHandler.js
* Fix #10226 
* After reconnection to call (or page reload), participant joins with new sessionId - previously stored data become inaccessible anymore. This could be observable at 'speaking time' jumping from somewhere to 0:00 again
* `attendeeId` is a unique number for participant within conversation, so it could be used to store speaking information and retreive it after reconnection
* P.S. (fixed) - at some point code was moved to support multiple sessionIds for user - there was one place to not check it properly
To test: 
1. Join a group call as two different users
2. Gain some numbers on speaking timer
3. Reload page as one of the users, join call again and speak - second user should still see elapsed time from first connection + new time
4. Optionally: force …
> fix(participantsStore) - use attendeeId as a key to store speaking information

- src/store/conversationsStore.js
Regression of https://github.com/nextcloud/spreed/pull/10284
`await`s in `patchConversations` are redundant as all called actions are synchronous. Each `await` creates a new microtask. For 500 chats it creates 500 microtasks. It blocks the main process.
🐌 Before | 🚄 After | Increase
---|---|---
`11_000 ms` - `17_000 ms` | `115 ms` - `225 ms` | `x48` - `x147`
#
> Fix patch conversation performance

- appinfo/info.xml
- docs/occ.md
- lib/Command/Bot/Install.php
- lib/Command/Bot/ListBots.php
- lib/Command/Bot/State.php
- lib/Controller/BotController.php
- lib/Migration/Version18000Date20230821112014.php
- lib/Model/Bot.php
- lib/Model/BotServer.php
- lib/Service/BotService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/bots.feature
> feat(bots): Add feature flags aka permissions to bots

- package-lock.json
- package.json
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
PR is made on top of https://github.com/nextcloud/spreed/pull/10051
Performance issues:
1. Too many conversations avatars request: 
Opening a page with 500 conversations immediately makes 500 requests for conversation avatars
2. Initial loading is slow for long chat lists
3. Scrolling a long conversations list and interacting with the menu could be slow on a long conversations list
Almost no visual changes, except scrolling behavior.
By default scroll to position in virtual scrolling just "teleport" to a new position instantly:
To the end | To unread
---|---
It doesn't look good and it is different from the current Talk behavior. And it makes it less understandable from what direction (up/down) the user have moved.
But we cannot just use smooth scrolling... Smooth scrolling from the …
> Virtual scrolling for conversations list

- src/store/messagesStore.js
* Fix #10298
Solution might be a bit overkill, so here are some explanations:
* System message `history_cleared` will be the first one in conversation by definition, so only previous messages should be cleared
* Depending on internet connection, or after conversation switching - there could be a new messages after clearing, so we can't purge the whole room, because it also could clear new ones.
* When scroll to the top and fetch - system message will be last processed and first known, so no mutations should occur
[clear-history.webm](https://github.com/nextcloud/spreed/assets/93392545/1e1c1d82-0715-4906-8e0e-30a6807764f2)
> fix(messagesStore) - clean conversation history for participants in call

- docs/occ.md
- lib/Command/User/Remove.php
- lib/Manager.php
- tests/integration/features/command/user-remove.feature
Retaining memberships in public, listable and one-to-one conversations
> Allow to offboard only on private conversations

- src/App.vue
* If another user is logged in, we should check, whether it's `uid` matches with last cached `uid`.
* if it matches, we could safely restore and use data from storage;
* if not, we wipe everything related to the last user and containing possibly sensitive data;
> fix(BrowserStorage) - clear BrowserStorage when different user logged in

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/integration/dashboard.feature
Ref https://github.com/nextcloud/server/pull/39937
* Fix red integration test on master
> fix(dashboard): Adjust dashboard API response after server PR

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/bruteforce-protection.feature
- tests/integration/spreedcheats/appinfo/routes.php
- tests/integration/spreedcheats/lib/Controller/ApiController.php
* Fix #10144 
* To prevent regressions like https://github.com/nextcloud/spreed/pull/10163 in the future
* Better performance with https://github.com/nextcloud/server/pull/39870
> feat(security): Integration tests for bruteforce protection

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
* Fix #10305
* Any changes of input value or `isFocused` state is now handled internally by component (and emitted, like before)
* `:deep` styles were moved from parents to the component
* component now looks and behaves the same in left and right sidebars
* traling button `X` now responds to Enter key
---|---
> fix(SearchBox) - unify component handling

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Fix #10288
* With Markdown introducing, it will be a good option to have, to be able to copy message text fully, with markdown
---|---
In action:
[copy-raw.webm](https://github.com/nextcloud/spreed/assets/93392545/81b01a3e-7aa7-4636-ade1-c0ab2e975a2f)
> feat(Message) - copy formatted message (with markdown and mentions) to clipboard

- CHANGELOG.md
- Avatars of open conversations are now shown without being a participant [#10229](https://github.com/nextcloud/spreed/issues/10229)
- Added an option to only remove a user from private conversations [#10310](https://github.com/nextcloud/spreed/issues/10310)
- Added an option to copy the original message content [#10335](https://github.com/nextcloud/spreed/issues/10335)
- Use virtual scrolling for the conversation list to improve the performance [#10297](https://github.com/nextcloud/spreed/issues/10297)
- Cache the conversation list in the browser storage for better loading experience [#10273](https://github.com/nextcloud/spreed/issues/10273)
- Allow replying to messages of bots [#10219](https://github.com/nextcloud/spreed/issues/10219)
- Fix sending system messages …
> chore(release): Add changelog for 17.1.0-rc.2

- src/components/LeftSidebar/LeftSidebar.vue
* Fix #10207
The active calls are now added to the filtered list of unread messages filter.
> Added active calls to the unread messages filter

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
* Moves date-separators from `<MessagesGroup/>` to parent `<MessagesList/>`
* Less props - less re-renders
* Increase margin-bottom of last message group by 4px, to not crop the buttons bar
🏚️ Before | 🏡 After | Pixel comparison (https://www.img2go.com/)
---|---|---
> fix(MessagesGroup) move date separator to the parent component level

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsListVirtual.vue
Focus outline is a little bit cut and overlaps conversations above and below.
---|---
> fix(LeftSidebar): adjust conversation padding and size

- src/components/Quote.vue
* Fix my primary color is pink, but the quotes were blue
---|---
> fix(chat): Fix primary color selection on quotes

- src/components/RoomSelector.vue
> Fix(RoomSelector) - Align text vertically

- appinfo/info.xml
- docs/occ.md
- lib/AppInfo/Application.php
- lib/Command/Bot/Uninstall.php
- lib/Command/Developer/UpdateDocs.php
- lib/Events/BotUninstallEvent.php
- lib/Listener/BotListener.php
- lib/Migration/Version18000Date20230504205823.php
- lib/Migration/Version18000Date20230824123939.php
- lib/Model/BotServerMapper.php
> feat(bot)!: Ensure bot uniqueness

- src/components/ConversationIcon.vue
On scrolling user status in 1-1 conversations in the `LeftSidebar` is not correct.
- User's avatar and user status is displayed by `NcAvatar` component.
- With virtual scrolling components are reused. During scrolling new visible conversations are just given props of previous.
- It works only for components that react on props update
- `NcAvatar` supports `user` update but doesn't support `preloadedUserStatus` update
It is less performant that adding support of `preloadUserStatus` change to `NcAvatar`.
Ideally it should be fixed on `@nextcloud/vue`. But I cannot say how much is the difference.
> fix(LeftSidebar): wrong user status after scrolling

- CHANGELOG.md
- feat(capability): Add a capability for messages being markdown [#10367](https://github.com/nextcloud/spreed/issues/10367)
- feat(bots)!: Ensure bot uniqueness and allow removing by URL [#10371](https://github.com/nextcloud/spreed/issues/10371)
- fix(LeftSidebar): wrong user status after scrolling [#10369](https://github.com/nextcloud/spreed/issues/10369)
- fix(changelog): Prevent duplicated changelog message by parallel requests [#10366](https://github.com/nextcloud/spreed/issues/10366)
- fix(RoomSelector): Align text vertically for open conversation list [#10363](https://github.com/nextcloud/spreed/issues/10363)
- fix(chat): Fix primary color selection on quotes [#10363](https://github.com/nextcloud/spreed/issues/10363)
- fix(LeftSidebar): adjust conversation …
> chore(release): Changelog for 17.1.0-rc.3

- src/components/LeftSidebar/LeftSidebar.spec.js
- src/services/conversationsService.spec.js
- src/store/conversationsStore.spec.js
- src/store/messagesStore.spec.js
- src/store/participantsStore.spec.js
- src/stores/__tests__/bots.spec.js
- src/stores/__tests__/settings.spec.js
- src/test-helpers.js
- src/test-setup.js
* add test helpers `generateOCSResponse` and `generateOCSErrorResponse` to ease codebase, unify request mocks and enhance typings
* mock `IntersectionObserver` and `@nextcloud/initial-state` to reduce amount of senseless logs in jest output
* update tests for :pineapple: Pinia stores, increase coverage (part of #9202) 
Jest output:
---|---
**3 212 lines** (323 lines - test coverage) | **634 lines** :arrow_down_small: 90%  (323 lines - test coverage)
> techdebt(Jest) - introduce response helper, clear output, raise coverage

- recording/docker-compose/Dockerfile
- recording/docker-compose/docker-compose.yml
- recording/docker-compose/wrap_chromium_binary
A simple Docker compose definition for the recording server.
> Docker compose for recording server

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/composables/useArrowNavigation.js
* Regression from #9980
* Before composable add new eventListener each time (on navigation initialization => after each fetch). Thus some items could receive several event listeners from it. Now it keep listeners in memory to remove them later (on reset method => before fetch).
* Before if search text was changed, and first item was removed from the list, but navigation is not initialized yet, on `Enter` key code tries to click on removed element, which causes page reload - fixed with additional check 
> fix(arrowNavigation) - update way to listen for focus/blur events

- docs/occ.md
- lib/Chat/MessageParser.php
- lib/Command/Bot/Install.php
- lib/Command/Bot/Setup.php
- lib/Controller/BotController.php
- lib/Listener/BotListener.php
- lib/Service/BotService.php
- tests/integration/features/bootstrap/CommandLineTrait.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/bots.feature
> tests(bots): add negative tests for bots

- tests/integration/config/behat.yml
- tests/integration/run.sh
* Fix leaving behind stray PHP built-in server processes
---|---
> fix(CI): Kill stray child proccesses now that the php server is spawning multiple childs

- src/composables/useCombinedSystemMessage.js
* Fix broken system message, when for some reason user joined or left call several times in a row
---|---
> store self as unique user in combined system message

- src/components/ConversationSettings/BasicInfo.vue
- src/components/ConversationSettings/EditableTextField.vue
- src/components/NewMessage/NewMessage.vue
* Fix #10227
* Follow-ups FIXME in the https://github.com/nextcloud-libraries/nextcloud-vue/issues/4492
Input:
```
&amp &lt &gt &sect
&amp; &lt; &gt; &sect;
https://instance.com/?editor=globaladmin&section=Invitation
```
Output:
---|---
``` & < > § & < > § https://instancae.com/?editor=globaladmin§ion=Invitation ``` | ```&amp &lt &gt &sect & < > § https://instancae.com/?editor=globaladmin&section=Invitation ```
> fix(NewMessage, EditabeTextField) - don't parse NcRichContenteditable output before sending

- CHANGELOG.md
- chore(packaging): Ship dependencies lock files [#10426](https://github.com/nextcloud/spreed/issues/10426)
- fix(bots): Fix several problems with bots [#10425](https://github.com/nextcloud/spreed/issues/10425)
- feat(conversations): Persist the filter status after reload [#10407](https://github.com/nextcloud/spreed/issues/10407)
- fix(chat): Don't parse NcRichContenteditable output before sending [#10440](https://github.com/nextcloud/spreed/issues/10440)
- fix(conversations): Fix arrow-key navigation in left and right sidebar [#10418](https://github.com/nextcloud/spreed/issues/10418)
- fix(deck): Show conversation name and highlight link in deck integration [#10394](https://github.com/nextcloud/spreed/issues/10394)
- fix(chat): Store self as unique user in combined …
> chore(release): Add changelog for 17.1.0-rc.4

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/store/messagesStore.js
- src/store/reactionsStore.js
* Fix #10395
* Detailed reactions are now resetted, if new one come from server
* Self reactions don't flicker anymore, if one of reactions was deleted
* Remove redundant store getters:
* `hasReactions()` - we can get this info from prop `reactions` in component
* `userHasReacted()` - we can get this info from prop `reactionsSelf` in component
* Refactor related tests for `Message` component
> fix(Message) - correctly show users reacted to message 

- package-lock.json
- package.json
Adds webpack bundle analyze scripts.
```sh
npm run analyze
npm run analyze:stats
npm run analyze:serve
npm run analyze:report
```
- Stats are stored in `/js/stats.json` (discussable, but the folder must exist).
- Report is stored in `/js/stats/report.html` (discussable).
> Add frontend bundle analyzing scripts

- src/components/CallView/CallView.vue
- src/components/SettingsDialog/SettingsDialog.vue
* Partial solution for #7896
Menu (enabled by default, reset on logout, same as all information in BrowserStorage): 
:computer:  Screen | 🏚️ Before (Enabled) | 🏡 After (Disabled)
---|---|---
3840 x 2160 pixels (4K) | ![image](https://github.com/nextcloud/spreed/assets/93392545/309a7acc-1f41-4f23-8b66-723cd07e9bd9) | ![image](https://github.com/nextcloud/spreed/assets/93392545/615267e1-1669-4735-a061-01d4a7e82468)
1920 x 1080 pixels (Full HD) | ![image](https://github.com/nextcloud/spreed/assets/93392545/945510e0-7bff-412d-907f-d5b14cc0b0be) | ![image](https://github.com/nextcloud/spreed/assets/93392545/ca72c7d6-4775-47ff-a210-5d35b9eedee8)
> perf(CallView) - add an option to disable background blur in call

- src/components/CallView/CallView.vue
- src/components/SettingsDialog/SettingsDialog.vue
(cherry picked from commit d43d1d72e827aa60485661377e14a349ec64cac8)
Backport of #10464
> [stable26] perf(CallView) - add an option to disable background blur in call

- src/FilesSidebarCallViewApp.vue
- src/FilesSidebarTabApp.vue
- src/components/LoadingComponent.vue
- src/views/FilesSidebarChatView.vue
- webpack.config.js
* Fix #8755 
+ Added `loadingComponent `
+ Webpack optimization
+ Async import one component that contains `MediaSettings`, `ChatView `and `CallButton` in `FilesSidebarTabApp`
---|---
Unused JS upon loading
---|---
Total unused JS
---|---
> Lazy load files sidebar of Talk 

- src/components/ChatView.vue
- src/components/GuestWelcomeWindow.vue
- src/components/LobbyScreen.vue
- src/components/SetGuestUsername.vue
- src/stores/__tests__/guestName.spec.js
- src/stores/guestName.js
* Fix #855
- The window is shown only when there is no username set previously. 
🏚️ Chat View | 🏡 Lobby view
---|---
> Add a welcome window to set username for guests

- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/ExpirationSettings.vue
* Fix #10419
---|---
Common | Moderator
-//- | User
> Hide message expiration set-up for non-moderators

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/TopBar/TopBar.vue
- src/mixins/getParticipants.js
* Possibly a regression from #10475 
* Fix cases, then there are guests in the participants list. Mixins aren't configured to work with Pinia stores, so they should be initialised at the component level
> fix(Pinia) - move guestNameStore initialisation from mixin to components

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
- src/components/RightSidebar/Participants/ParticipantsList/ParticipantsListVirtual.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
* Fix #5907 
* Based on #10262 and #10356
* Same performance issues with avatar requests and long list re-rendering (and initial rendering)
* Fix `data-nav-id="undefined_undefined"` for `<Participant />` components without arrow navigation
[virtual scroll.webm](https://github.com/nextcloud/spreed/assets/93392545/767b54a6-a2df-4aff-bf71-5fca0131fd71)
> feat(ParticipantsTab) - virtual scrolling for participants list

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Release notes: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v7.12.5
* Some styles were reverted to align with default lib styles fro markdown
> chore(deps): bump nextcloud/vue from 7.12.4 to 7.12.5

- CHANGELOG.md
- Add support for bots via webhooks [#10139](https://github.com/nextcloud/spreed/issues/10139) [#10151](https://github.com/nextcloud/spreed/issues/10151)
- Add Markdown support for chat messages [#10089](https://github.com/nextcloud/spreed/issues/10089) [#10090](https://github.com/nextcloud/spreed/issues/10090)
- Allow to filter the conversation list for unread mentions and messages [#10093](https://github.com/nextcloud/spreed/issues/10093)
- Provide an overview list of open conversations [#10095](https://github.com/nextcloud/spreed/issues/10095)
- Set a reminder to get notified about a chat messages at a later time [#10104](https://github.com/nextcloud/spreed/issues/10104) [#10152](https://github.com/nextcloud/spreed/issues/10152) …
> chore(release): Add changelog for 17.1.0

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 17.1.0

- src/components/LeftSidebar/LeftSidebar.vue
* Fix #10498
Note ! When activating a filter, the current conversation now stays in list ( even when it doesn't have unread messages/mentions ) 
Conversation remains in the list after being opened and the unread marker has been removed.
> fix(leftSidebar)- Keep the opened conversation in the list

- lib/Listener/BotListener.php
- lib/Model/BotServerMapper.php
- lib/Notification/Notifier.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/bots.feature
- tests/php/Notification/NotifierTest.php
> fix(bots): Fix notifications of bot messages and reactions

- .gitignore
- tests/integration/run.sh
* Removes unneccessary output of "Accepted" and "Closed" messages from the PHP dev server.
* Fixes the trap. Since we can have only one trap per signal, this is now combined.
---|---
> Remove unneccessary output from php process

- lib/Service/RoomFormatter.php
* Fix #10420
| 🏡 After
| ---
| ![image](https://github.com/nextcloud/spreed/assets/93392545/a0f062e4-ccb8-47f6-ad72-daeff0cd589d)
> Allow non-moderators to leave conversation with enabled lobby

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix #10416
| 🏡 After |
|---|
| ![image](https://github.com/nextcloud/spreed/assets/93392545/390b7b16-4cfc-4970-8a65-510d5f64ca44) |
> Add a copy function for code blocks

- lib/Chat/ChatManager.php
- lib/Chat/MessageParser.php
- lib/Chat/Parser/Changelog.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/SystemMessage/Listener.php
- lib/Manager.php
- lib/Model/Attendee.php
- lib/Service/ParticipantService.php
Instead of querying the database yet again
* Fix #10502
> fix(API): Reuse participant objects we already created

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/TopBar.vue
- src/mixins/getParticipants.js
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- Fix #10497
- Previously for users and guest moderators participants were fetched twice, from `RightSidebar` and `TopBar`
- `CancelledRequest` logic was there, but because it was in mixin, it doesn't work for different components as expected
- TopBar duplicates request for participants counter in call only - it's not needed for registered users at all
- TopBar watches if guest was promoted to guest-moderator to fetch participants
---|---
> fix(participantsStore) - handle participants fetch through the store

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/utils/webrtc/simplewebrtc/getscreenmedia.js
* Fix #10525 regression in translatable string
* Add description to getScreenMedia function, fix JSDOC warning
> fix(Message | JSDOC) - trim space, fix lint warnings

- recording/docs/encoders.md
- recording/server.conf.in
- recording/src/nextcloud/talk/recording/Benchmark.py
- recording/src/nextcloud/talk/recording/Config.py
- recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py
Just a code suggestion, feel free to comment. I hope this is up to you coding standards.
* Fix #9418+
> feat(ffmpeg): allow custom common options

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageNewFileDialog.vue
- src/components/RightSidebar/SharedItems/SharedItems.vue
- src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
- src/composables/useViewer.js
- src/store/sharedItemsStore.js
* Closes #3347
* as `list` is required, and `loadMore()` is optional
* Update useViewer() mixin according to docs: https://github.com/nextcloud/viewer#open-a-file
* Pass a list of adjacent media files to the Viewer to be able to list through them
* Could be reused, when support of several files in one message will be added
* Request is paginated by 20 elements and `loadMore()`
---|---
> feat(Viewer) - allow to list shared media

- .drone.jsonnet
- .drone.yml
- lib/Controller/PageController.php
- tests/integration/run.sh
> [stable26] fix(page): Decouple the index controller from the executing method

- .drone.jsonnet
- .drone.yml
- lib/Controller/PageController.php
- tests/integration/run.sh
> [stable25] fix(page): Decouple the index controller from the executing method

- CHANGELOG.md
- feat(chat): Add copy function to code blocks [#10533](https://github.com/nextcloud/spreed/issues/10533)
- fix(attachments): Allow to navigate between attachments in the viewer [#10549](https://github.com/nextcloud/spreed/issues/10549)
- fix(bots): Fix notifications of bot messages and reactions [#10530](https://github.com/nextcloud/spreed/issues/10530)
- fix(conversations): Keep the current conversation in filtered list [#10527](https://github.com/nextcloud/spreed/issues/10527)
- fix(page): Decouple the index controller from the executing method [#10546](https://github.com/nextcloud/spreed/issues/10546)
- fix(API): Reuse participant objects already created to reduce number of database queries [#10536](https://github.com/nextcloud/spreed/issues/10536)
- Update …
> chore(release): Add changelog for 15.0.8, 16.0.6 and 17.1.1

- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
* Fix missing "Shared items tab" for 1-1 conversations
* By default, active tab after mount is `participants` for all types of conversations
* Now it checks for 1-1 conversations on mount as well
* When switching conversations to 1-1, only a change from tab other than 'shared-items' triggers content fetch  
*  Now it checks combination `active && token` as well
---|---
> fix(RightSidebar) update active tab on mount and conversation change

- src/components/ConversationIcon.vue
> fix(ConversationIcon) adjust fallback icon size

- src/components/RightSidebar/RightSidebar.vue
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Minimized fetch requests of shared Items
Regression from #10558
Part of #10559
> fix(RightSidebar) - Optimize update active tab ( sharedItems) 

- appinfo/info.xml
- appinfo/routes/routesRoomController.php
- docs/capabilities.md
- docs/constants.md
- docs/participant.md
- lib/Capabilities.php
- lib/Controller/RoomController.php
- lib/Migration/Version18000Date20230920182747.php
- lib/Model/Session.php
- lib/Service/ParticipantService.php
- lib/Service/SessionService.php
- src/App.vue
- src/composables/useActiveSession.js
- src/constants.js
- src/services/messagesService.js
- src/services/messagesService.spec.js
- src/services/participantsService.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/notifications.feature
- tests/php/CapabilitiesTest.php
* Fix #1575
* Current session (opened room) will be marked as inactive if:
* Tab was hidden or minimized
* Tab was blurred, and there were not any movements on it for 3 minutes
* If inactive, it will receive notifications for this tab as well
> fix(notifications): Allow sessions to mark themselves as inactive

- lib/Config.php
- lib/Controller/RoomController.php
Currently limiting to 1k users because the user_status API would yield an error on Oracle otherwise. Clients should use a virtual scrolling mechanism so the data should not be a problem nowadays
> feat(user_status): Increase participant limit to 1k users

- docs/capabilities.md
- lib/Capabilities.php
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
- tests/php/CapabilitiesTest.php
* Fix #10074 
- https://github.com/nextcloud/talk-ios/issues/1376
- https://github.com/nextcloud/talk-android/issues/3347
> Fix capabilities endpoint with openai translation integration

- recording/src/nextcloud/talk/recording/Participant.py
[`skipverify` can be set in the configuration](https://github.com/nextcloud/spreed/blob/d0ae75785782757632b11797828657a4343c4e01/recording/server.conf.in#L28-L32) to skip certificate validation of the backend endpoints. However, this was honoured only for [requests done by the Python code](https://github.com/nextcloud/spreed/blob/966a851b56700c9a22a3b6496e19c797952e3030/recording/src/nextcloud/talk/recording/BackendNotifier.py#L66); if the Nextcloud server was using an invalid certificate, like a self-signed one, the browser launched by the recording server was not able to load the page that acts as its entry point in the Nextcloud server, and therefore the recording failed. Now [`acceptInsecureCerts` WebDriver capability](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities …
> Accept insecure certificates in the browser if "skipverify" is enabled

- .github/workflows/integration-summary-when-unrelated.yml
- .github/workflows/lint-eslint-when-unrelated.yml
- .github/workflows/node-when-unrelated.yml
- .github/workflows/phpunit-summary-when-unrelated.yml
Before they executed when any file outside the defined scope matched. However that means: When a PR touches PHP and JS, both the real and the fake summaries for node, eslint and phpunit got triggered. Since the fake summary is always green it meant one could merge a PR that in the end had red CI on the non-fake summary.
Now the fake summaries are skipped, if any of the files still matches the pattern, instead of being executed whenever a single file did not match it.
Fix #10600
> fix(CI): Make sure the "when unrelated" fake summaries work correctly

- lib/Controller/RoomController.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/invite-email.feature
Psalm reported
```
ERROR: UndefinedMagicMethod - lib/Controller/RoomController.php:1459:22
Magic method OCA\Talk\Model\Attendee::getattendee does not exist (see https://psalm.dev/219)
```
* Little oopsy found when adding the return type for `getActorsByType` in https://github.com/nextcloud/spreed/pull/10608
* So I extracted it to a new PR and added integration tests for the endpoint.
> fix(email): Fix sending re-invites to all emails

- docs/constants.md
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/CallButton.vue
- src/constants.js
- src/services/conversationsService.js
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* Feature #10405
Forward a message to Note to self
https://github.com/nextcloud/spreed/assets/84044328/6335d4b9-7221-4842-8f86-0770ae325646
Restore
https://github.com/nextcloud/spreed/assets/84044328/1e3f593f-5be0-4604-9a6a-df601f829c1f
> feat(conversation) - add Note to self conversation

- .github/pull_request_template.md
* Made it a bit easier to remove unneeded things when a PR is only frontend or backend
* Adjusted the list of tasks a bit to match more what @Antreesy is posting all the time :P
> ![grafik](https://github.com/nextcloud/spreed/assets/213943/35a72bde-4917-4470-b5de-ba3370dd86da)
> chore(PR): Split PR templates for UI and API work

- tests/integration/composer.json
- tests/integration/composer.lock
- tests/integration/config/behat.yml
* Currently CI always yields:
```
Deprecated: Creation of dynamic property DOMDocument::$preserveWhitespace is deprecated in /home/runner/work/spreed/spreed/apps/spreed/tests/integration/vendor/jarnaiz/behat-junit-formatter/src/Formatter/JUnitFormatter.php on line 314
```
And it will break at some point.
> Remove old and unmaintained junit extension

- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* Fix #10631
| Before 😞  | 🏚️ After: The actual message | 🏡 After : The forwarded message |
|------------|------------|----------|
| ![image](https://github.com/nextcloud/spreed/assets/84044328/11ea9677-b0e3-484b-b9e3-23e561c6a663)| ![image](https://github.com/nextcloud/spreed/assets/84044328/02f45045-70a5-4722-a88a-839e5530fbfb)         | ![image](https://github.com/nextcloud/spreed/assets/84044328/3cc898df-79f1-47b3-b5f4-ce77cfc50c51)       |
> fix(messagesStore) - Mentions in forwarded messages

- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
* Fix #10630
| ![image](https://github.com/nextcloud/spreed/assets/84044328/a7c92c57-9892-4b29-b485-c812ace3bab7) |![image](https://github.com/nextcloud/spreed/assets/84044328/b5116185-a610-49b4-8907-071f06e53789)|
| ![image](https://github.com/nextcloud/spreed/assets/84044328/ba880bea-ef7c-4464-bfef-3963a3040c7b) | ![image](https://github.com/nextcloud/spreed/assets/84044328/303830e6-f40b-4caf-95b4-6ac0b06c2681)|
| ![image](https://github.com/nextcloud/spreed/assets/84044328/5fc27db9-a539-40c3-a357-1cc033e34e87) | ![image](https://github.com/nextcloud/spreed/assets/84044328/020df4c5-5ac6-484d-a94d-2313bc4e35f0)|
|![image](https://github.com/nextcloud/spreed/assets/84044328/5cef67a2-342e-4a9f-8ce3-dbe782b7a7c0) | …
> Fix(MessageForwarder + NewGroupConversation) - The confirmation page enhancement

- lib/Chat/MessageParser.php
- lib/Controller/AEnvironmentAwareController.php
- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Events/BeforeFederatedUserJoinedRoomEvent.php
- lib/Events/FederatedUserJoinedRoomEvent.php
- lib/Federation/FederationManager.php
- lib/Manager.php
- lib/Middleware/InjectionMiddleware.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Service/RoomFormatter.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
- tests/psalm-baseline.xml
Another step towards https://github.com/nextcloud/spreed/issues/5723
> 🌐 Talk federation auth

- css/icons.css
- docs/chat.md
- lib/Chat/Parser/SystemMessage.php
- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- tests/integration/features/federation/invite.feature
Step | Screenshot
---|---
🏚️ Before | ![Bildschirmfoto vom 2023-10-11 10-43-32](https://github.com/nextcloud/spreed/assets/213943/adc5858e-0915-432d-9cae-d1eba9956244)
With only backend changed |  ![Bildschirmfoto vom 2023-10-11 10-43-11](https://github.com/nextcloud/spreed/assets/213943/a28ca4d8-26d1-4e01-b3ed-dbb0a8c8ed60)
🏠 After | ![grafik](https://github.com/nextcloud/spreed/assets/213943/ff896575-87bf-48ca-a804-3733958828a4)
---
---
1. Enable federation on your instance `occ config:app:set spreed federation_enabled --value yes`
2. Use the OCS viewer app https://github.com/provokateurin/ocs_api_viewer and invite your own user to a conversation (adjust the IP to whatever you use to open your own Nextcloud)
> fix(federation): Fix federation invite system messages

- lib/BackgroundJob/RetryJob.php
- lib/Controller/RoomController.php
- lib/Federation/BackendNotifier.php
- lib/Federation/FederationManager.php
- lib/Service/ParticipantService.php
- tests/integration/features/federation/invite.feature
- tests/php/Federation/FederationTest.php
- tests/php/Service/ParticipantServiceTest.php
- tests/php/Signaling/BackendNotifierTest.php
* Fix adding a person from a non-existing server, have a cert error, etc.
* Currently there is no user feedback to be aware.
> fix(federation): Error the POST /participant request when federation failed

- lib/BackgroundJob/RemoveEmptyRooms.php
- lib/Controller/FederationController.php
- lib/Federation/FederationManager.php
- lib/Model/InvitationMapper.php
- lib/Notification/Notifier.php
- lib/ResponseDefinitions.php
- openapi.json
- tests/integration/features/federation/invite.feature
- tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
- tests/php/Notification/NotifierTest.php
* Fixes this comment https://github.com/nextcloud/spreed/issues/5723#issuecomment-1152386582
> fix(federation): Don't remove federation rooms while waiting for accept/reject

- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Notification/Notifier.php
- tests/php/Notification/NotifierTest.php
* Fix #…
| ![grafik](https://github.com/nextcloud/spreed/assets/213943/d64702d0-b3bc-4e2a-b960-8ba9ffb624e9)          | ![Bildschirmfoto vom 2023-10-11 17-07-54](https://github.com/nextcloud/spreed/assets/213943/f0aca481-4b7d-4d2a-bf1d-c6c20ed3e626)        |
> fix(notification): Render the actions and remove notification on click

- src/components/MediaSettings/MediaSettings.vue
- src/components/TopBar/CallButton.vue
* Ease usage of recording function for moderators
From moderator perspective:
| Before call start | During call (hidden) |
|---|---|
| ![Screenshot from 2023-10-05 13-49-41](https://github.com/nextcloud/spreed/assets/93392545/487262e0-1a4c-42dd-9c4e-fba9bf3f573a) | ![Screenshot from 2023-10-05 13-49-51](https://github.com/nextcloud/spreed/assets/93392545/5bb4bad4-786a-4168-96bf-f867b146ddaa) |
> feat(MediaSettings) start recording together with call

- src/utils/signaling.js
When a call was joined the value of the `silent` parameter was not tracked by the signaling object, so if the call was joined again (for example, in a forced reconnection, or if joining the call was deferred because the room was not joined yet by the signaling) `silent` was undefined, which [was treated as `false` by the API](https://github.com/nextcloud/spreed/blob/4d292fe9599f1598b4a44b094595404f1e465dec/lib/Controller/CallController.php#L134).
The current set of scenarios that could trigger the issue is unlikely to happen in the real world, although it is possible nevertheless. Other slightly more common cases, like the participant starting without audio and video and then selecting the devices while already in the call [would not trigger a reconnection, just an update of …
> Fix "silent" parameter not sent again when reconnecting

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/components/Quote.vue
* Fix #10522 and provide for:
* System messages
* Deleted messages
* User messages (including markdown)
* New message input
* :warning:  User mentions and mention bubbles are locked to LTR, to show icon on a left side
* Fix message grouping:
* :warning: `moment().format()` transforms date based on locale, so result of comparison was NaN
* Now, it compares only timestamps in ms
* Make markdown styles language-independent:
* Applicable for ol, ul, blockquote
* blockquote left border doesn't have rounded corners anymore :large_blue_circle: => :blue_square: 
| ![image](https://github.com/nextcloud/spreed/assets/93392545/b7321381-9bd3-4bc5-a758-e5466b876ec6)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/3e653329-710c-41 …
> Add minor RTL support for chat messages

- src/store/messagesStore.js
* Regression from #10296
* If several messages has one as a parent, and parent has been deleted, now we loop through all exisiting messages and clear a parent from each one
[Screencast from 15.10.2023 15:13:11.webm](https://github.com/nextcloud/spreed/assets/93392545/7b87ae59-13d2-44d5-8dde-1b9ade06f94e)
> fix(messagesStore): clear deleted messages from replies

- src/components/AdminSettings/SIPBridge.vue
* Fix regression from #9384
* Input value wasn't stored in component => empty payload (should have been `this.sharedSecret = value`)
Before | After
-- | --
> fix(SIPBridge): fix typo when sending shared secret as payload

- lib/AppInfo/Application.php
- lib/Service/RoomService.php
- lib/Signaling/Listener.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation/breakout-rooms.feature
* Fix comments from https://github.com/nextcloud/spreed/pull/10633#pullrequestreview-1684412801
> Fix consent in breakout rooms and missing updates on the room list

- appinfo/info.xml
- docs/occ.md
- lib/AppInfo/Application.php
- lib/Command/Recording/Consent.php
- lib/Controller/CallController.php
- lib/Events/BeforeRoomDeletedEvent.php
- lib/Events/RoomDeletedEvent.php
- lib/Listener/UserDeletedListener.php
- lib/Migration/Version18000Date20231018065816.php
- lib/Model/Consent.php
- lib/Model/ConsentMapper.php
- lib/Recording/Listener.php
- lib/Service/ConsentService.php
- lib/Service/RoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/recording.feature
- tests/integration/spreedcheats/lib/Controller/ApiController.php
* Fix #10408 
```
+-------+-----------+---------+------------+
| token | actorType | actorId | timestamp  |
+-------+-----------+---------+------------+
| abc   | users     | admin   | 1698227737 |
+-------+-----------+---------+------------+
```
```json
[{"token":"abc","actorType":"users","actorId":"admin","timestamp":1698227737}]
```
```json
[
{
"token": "abc",
"actorType": "users",
"actorId": "admin",
"timestamp": 1698227737
}
]
```
> feat(consent): Save recording consent to DB and allow retrieving with OCC

- lib/Notification/Notifier.php
- src/App.vue
* Fix #7038
* With opening from web client - redirect to the page, media settings dialog is shown
* With opening from NC Desktop client - open new page in browser, media settings dialog is shown
---
> show MediaSettings if coming from notification "Join call"

- src/components/CallView/CallView.vue
- src/components/CallView/shared/VideoVue.vue
* Fix #4478
* You can hide and unhide by clicking on the presenter overlay
* When hidden, a button will be shown.
* If the video is disabled from the stripe, the presenter overlay will be hidden. Pressing on the presenter button will enable the video and show the overlay.
| 🏚️ Default | 🏡 On hover |  🏡 Clicked | 🏡 Stripe Open |
|------------|----------|----------|----------|
| ![Presenter1](https://github.com/nextcloud/spreed/assets/84044328/646e561f-b3ae-4811-95c5-506f7b7c86f4)      | ![image](https://github.com/nextcloud/spreed/assets/84044328/b31891b1-b6ad-48f6-b9d1-8a24090728a4)  |  ![Screenshot 2023-10-09 230256](https://github.com/nextcloud/spreed/assets/84044328/4e77ad55-4dcd-41aa-9bb2-ba392be0a75a) | ![Screenshot 2023-10-09 …
> Add presenter overlay when sharing screen

- src/components/LeftSidebar/LeftSidebar.vue
- src/store/conversationsStore.js
- src/utils/conversation.js
`Hint` component was at the bottom of the `LeftSidebar` because the `ConversationListVirtual` is always present at full height.
* Added utility for conversation
* Refactored filter handling in leftSidebar
* Added captions for unread messages and unread mentions filter
* Add the empty content when there are no results
The filtering logic : 
"Standard Condition" :  if conversation  has call , mentions / unread message and is currently active in the chat view. 
"Special Condition" : if conversation is currently active, the only one in the list and has no flag. 
* At the moment the filter is first applied:
- Apply Standard Condition.
- Check Special Condition:
* If yes, hide the current conversation by returning an empty list. This handles the case of clicking the filter initially and showing …
> Fix(LeftSidebar): Show hint when no filtered results

- src/App.vue
- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/RecordingConsentSettings.vue
- src/components/MediaDevicesSelector.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/TopBarMenu.vue
- src/constants.js
- src/services/callsService.js
- src/services/conversationsService.js
- src/store/conversationsStore.js
- src/store/participantsStore.js
- src/store/participantsStore.spec.js
- src/stores/__tests__/settings.spec.js
- src/stores/settings.js
- src/utils/signaling.js
- src/utils/webrtc/index.js
- src/views/FilesSidebarChatView.vue
* Fix #10409
* Solution is based on MVP + V2 description (https://github.com/nextcloud/spreed/issues/10348#issuecomment-1725333919)
* Option to require consent globally in Admin settings
* When consent is required `1`:
* Enforce the media settings dialog
* Show a checkbox that needs ticking before moderator/user can start or join call
* Moderator setting is visible but disabled
* When consent is optional `2`:
* Moderator setting is enabled with "Off" and "Required"
* Disabled, while call is currently on
* If user accidentally joined without consent, will be blocked by API
* Increase preview size in MediaSettings, align all content elements up to its width
| Off (hidden) | Required (disabled) | Configurable V2 |
|---|------------|----------|
| …
> feat(recording) - add frontend support for recording consent

- src/composables/useActiveSession.js
* Regression from #10544 
* missing clearTimeout was added
* toast message has been kept for cases when tab is visible (otherwise too verbose to see it while switching tabs)
> fix(useActiveSession): adjust behavior of inactive session 

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
> feat(NewMessageUploadEditor) - caption to file share

- src/components/LeftSidebar/LeftSidebar.vue
Filter | 🏚️ Before | 🏡 After
---|---|---
Mentions | ![Bildschirmfoto vom 2023-10-23 14-37-38](https://github.com/nextcloud/spreed/assets/213943/3cc13aec-8bcc-4133-8e0c-5ab2db63c1f4) | ![Bildschirmfoto vom 2023-10-23 14-35-22](https://github.com/nextcloud/spreed/assets/213943/bb5218b8-29a0-4d8a-9afa-67123827b521)
Unread | ![Bildschirmfoto vom 2023-10-23 14-37-33](https://github.com/nextcloud/spreed/assets/213943/ae23261d-4ad7-4c57-9b5c-daa4abe47c61) | ![Bildschirmfoto vom 2023-10-23 14-35-27](https://github.com/nextcloud/spreed/assets/213943/4739ac6f-5676-4c7a-b822-846e9036f289)
Empty | ![Bildschirmfoto vom 2023-10-23 14-37-27](https://github.com/nextcloud/spreed/assets/213943/e3f8729e-0780-46a5-824b-dfe9c86cb4ca) | ![Bildschirmfoto vom 2023-10-23 …
> fix(LeftSidebar): Adjust wording to be less email like

- src/components/MessagesList/MessagesList.vue
- src/store/participantsStore.js
* Fix errors `Can't read properties of 'undefined'`
> fix(ChatView): minor fixes

- .eslintrc.js
- src/components/EmptyView.vue
- src/views/NotFoundView.vue
- src/views/SessionConflictView.vue
- src/views/WelcomeView.vue
- webpack.common.config.js
Use `<NcEmptyContent>` instead our own copy.
> Migrate to NcEmptyContent

- composer.json
- composer.lock
Ref https://github.com/CuyZ/Valinor/pull/437#issuecomment-1768779626
> fix(deps): Update CuyZ/Valinor after upstream fixed the regression from 1.6.1

- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
* Fixes `Can't read properties of 'undefined'`
* v-if destroys the first page where there is a ref for the avatar. Accessing the `this.$refs.conversationAvatar` returns `undefined` . v-show will keep the component ref accessible
> fix(NewGroupConversation): minor fix

- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
* Fix #10734
🏚️ Before  
https://github.com/nextcloud/spreed/assets/84044328/ab3105d8-1aca-492d-adc2-bbe606fe1031   
🏡 After 
https://github.com/nextcloud/spreed/assets/84044328/7273a193-46d8-45c7-a7e7-dbe9fc287b92
> fix(LeftSidebar): Disable blur event in order to click on a conversation

- src/components/MessagesList/MessagesList.vue
Manual partial backport of #10687
To test:
- switch locale to arabic
- open chat
- post some messages
Output:
- messages should be grouped
> [stable26] - fix message grouping for all locales

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/SearchBox/SearchBox.vue
Backport #10737
Changed ref to "container"
> [Stable27] fix(LeftSidebar): Disable blur event in order to click on a conversation

- lib/Controller/RecordingController.php
- src/components/AdminSettings/RecordingServer.vue
* Ref https://github.com/nextcloud/nextcloud-talk-recording/issues/8
| ![grafik](https://github.com/nextcloud/spreed/assets/213943/1a078a30-4804-47a4-b994-034076bf6f19)        | ![Bildschirmfoto vom 2023-10-26 17-20-06](https://github.com/nextcloud/spreed/assets/213943/b0bad3a7-ce94-40e4-b726-2f68bf32508f)  |
> fix(recording): Fail the recording server check when a HPB is configured

- lib/AppInfo/Application.php
- tests/psalm-baseline.xml
> techdebt(context): Use injectFn instead of accessing IServerContainer

- CHANGELOG.md
- fix(chat): Allow joining a conversation via search when a filter is active [#10781](https://github.com/nextcloud/spreed/issues/10781)
- fix(chat): Fix re-rendering of conversation data when scrolling (hover, user status, more) [#10779](https://github.com/nextcloud/spreed/issues/10779)
- fix(chat): Clear deleted messages from replies [#10713](https://github.com/nextcloud/spreed/issues/10713)
- fix(chat): Fix mentions when forwarding messages [#10673](https://github.com/nextcloud/spreed/issues/10673)
- fix(call): Increase the avatar size in calls when the video is disabled [#10628](https://github.com/nextcloud/spreed/issues/10628)
- fix(call): Fix "silent" parameter not sent again when reconnecting [#10776](https://github.com/nextcloud/spreed/issues/10776)
- …
> chore(release): Add changelog for 16.0.7 and 17.1.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(call): Fix "silent" parameter not sent again when reconnecting [#10777](https://github.com/nextcloud/spreed/issues/10777)
- fix(chat): Fix message grouping for all locales [#10696](https://github.com/nextcloud/spreed/issues/10696)
- fix(RightSidebar) update active tab on mount and conversation change [#10564](https://github.com/nextcloud/spreed/issues/10564)
- fix(sip): Fix saving the secret of the SIP bridge in the admin UI [#10719](https://github.com/nextcloud/spreed/issues/10719)
> Release 16.0.7

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(chat): Allow joining a conversation via search when a filter is active [#10781](https://github.com/nextcloud/spreed/issues/10781)
- fix(chat): Fix re-rendering of conversation data when scrolling (hover, user status, more) [#10779](https://github.com/nextcloud/spreed/issues/10779)
- fix(chat): Clear deleted messages from replies [#10713](https://github.com/nextcloud/spreed/issues/10713)
- fix(chat): Fix mentions when forwarding messages [#10673](https://github.com/nextcloud/spreed/issues/10673)
- fix(call): Increase the avatar size in calls when the video is disabled [#10628](https://github.com/nextcloud/spreed/issues/10628)
- fix(call): Fix "silent" parameter not sent again when reconnecting [#10776](https://github.com/nextcloud/spreed/issues/10776)
- …
> Release 17.1.2

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Guest cannot delete a message.
| ![image](https://github.com/nextcloud/spreed/assets/84044328/c3284058-2b4f-4785-8ea4-19e54f63b245)   | ![image](https://github.com/nextcloud/spreed/assets/84044328/7083dcd7-45c2-451b-a174-31bc55954188)       |
> Fix(MessageButtonsBar): hide delete message button for guests

- docs/Talkbuchet-cli.py
Currently Talkbuchet offers the method `addVirtualParticipant()` and `addVirtualParticipants(NUMBER)`. Those methods directly start a virtual participant, therefore joining the call sequentially. This is fine if you want to use Talkbuchet for testing with multiple participants in a call, but is not sufficient if you want to let an arbitrary number of participants join/leave at the same time (e.g. to test performance of layout calculations being done when multiple participants join/leave at once).
This PR extends `Talkbuchet.py` with the following methods:
`prepareVirtualParticipant()`
`prepareVirtualParticipants(NUMBER)`
`startVirtualParticipants()`
`startVirtualParticipantsParallel()`
`stopVirtualParticipants()`
`stopVirtualParticipantsParallel()`
while still keeping the previous …
> Allow to prepare virtual participants without immediately joining the call

- appinfo/routes/routesSignalingController.php
- lib/Controller/SignalingController.php
- openapi.json
The name of the method is not helpful for consumers of the OpenAPI spec. `sendMessages` correctly communicates what the endpoint does without looking at the description.
> refactor(signaling): Rename sendMessages endpoint for clarification

- lib/Controller/SignalingController.php
- lib/Signaling/Messages.php
- openapi.json
Signaling messages from the DB are strings.
> fix(signaling): Fix pullMessages return type

- lib/AppInfo/Application.php
- lib/Chat/Command/Listener.php
- lib/Collaboration/Reference/ReferenceInvalidationListener.php
- lib/Collaboration/Resources/Listener.php
- lib/Files/Listener.php
- lib/Files/TemplateLoader.php
- lib/Share/Listener.php
- lib/Share/RoomShareProvider.php
- psalm.xml
- tests/psalm-baseline.xml
- tests/stubs/oca_files_events.php
> techdebt(events): Migrate more event handling to `registerEventListener()` and typed events

- src/utils/webrtc/simplewebrtc/localmedia.js
When a screen share fails a message is shown in the UI. However, the detailed message was not logged anywhere, which is specially relevant when [an unknown error without an explicit message in the UI occurs](https://github.com/nextcloud/spreed/blob/e4692febc97dc52d40369de67750e9a3d43b114b/src/components/TopBar/TopBarMediaControls.vue#L537).
> Log error when starting a screen share fails

- src/utils/signaling.js
The signaling messages were already logged in debug mode, but only [if the external signaling server was used](https://github.com/nextcloud/spreed/blob/da7064279773936ae72f5ab0beda5ae445f54f24/src/utils/signaling.js#L762-L764). This extends the logging also to internal signaling messages.
> Log internal signaling messages in debug mode

- lib/Controller/FederationController.php
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Migration/Version13000Date20210625232111.php
- lib/Migration/Version18000Date20231024141626.php
- lib/Migration/Version18000Date20231024141627.php
- lib/Model/Invitation.php
- lib/Model/InvitationMapper.php
- lib/Notification/Notifier.php
- lib/ResponseDefinitions.php
- openapi.json
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
- tests/php/Federation/FederationTest.php
> Fix "Validation by remoteAttendeeId + accessToken might be ambiguous"

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- 🗒️ Note to self  [#2196](https://github.com/nextcloud/spreed/issues/2196)
- 🎙️ Show speaker while screensharing  [#4478](https://github.com/nextcloud/spreed/issues/4478)
- 🏷️ Add a caption to your file before sharing it into the chat  [#5354](https://github.com/nextcloud/spreed/issues/5354)
- 👤 Ask Guest to enter a name when connecting  [#855](https://github.com/nextcloud/spreed/issues/855)
- 🤩 Animated call reactions  [#10561](https://github.com/nextcloud/spreed/issues/10561)
- 🖋️ Optionally require consent before joining a recorded call  [#10348](https://github.com/nextcloud/spreed/issues/10348)
- 📲 Allow calling phone numbers from within Talk using SIP dialout  [#10346](https://github.com/nextcloud/spreed/issues/10346)
- Requires Nextcloud 28
> chore(release): Bump version and add meta changelog

- lib/Chat/Parser/UserMention.php
- tests/integration/features/chat/file-share.feature
Set the current message as comment content, so that the message finds mentions which are now part if the message but were not on the original comment, e.g. mentions at the beginning of captions
* Fix #10830 
```behat
Then user "participant1" sees the following messages in room "public room" with 200 # FeatureContext::userSeesTheFollowingMessagesInRoom()
| room        | actorType | actorId      | actorDisplayName         | message         | messageParameters |
| public room | users     | participant1 | participant1-displayname | {mention-user1} | "IGNORE"          |
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
'actorType' => 'users'
'actorId' => 'participant1'
'actorDisplayName' => 'participant1-displayname'
-        'message' => '{mention-user1}'
+ …
```
> fix(chat): Fix mentions at the beginning of captions

- src/components/AdminSettings/SIPBridge.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
Migrate to NcTextArea from native textarea in 
* SIP bridge ( dial-in info)
* Matterbridge settings ( log)
* No visual changes in SIP bridge
* Matterbridge log ( with dummy log)
| ![Screenshot 2023-10-31 121533](https://github.com/nextcloud/spreed/assets/84044328/86a0d0f7-f8d5-438a-b3d8-a717f4bec3fc)       | ![Matterbridge-after](https://github.com/nextcloud/spreed/assets/84044328/2eb7bbf2-cafb-43ea-99d3-383d76dedd20)       |
> Migrate to NcTextArea

- src/components/LeftSidebar/LeftSidebar.vue
* Fix #10443 again :') ( changes of its PR were reverted [here](https://github.com/nextcloud/spreed/commit/948a640bcd7d60078269b19f5fa0d36b6d61f9fb#diff-7a1abf98ca549db81a418814a97629c796bc85dc32b40f9cffb65ce3ad40d555) ). Another workaround is now used which is basically moving the outline inside the element.
* Fix the unexpected outline on favorite conversations ( border radius is changing) . As I checked, there was no explicit style for the border radius coming from the favorite icon node. Setting `overflow: hidden` solved it though 
* Revert some changes after merging https://github.com/nextcloud-libraries/nextcloud-vue/pull/4628
| ![image](https://github.com/nextcloud/spreed/assets/84044328/ce85455c-af0c-48e4-823e-e9514744248a)       | …
> fix(LeftSidebar): revert temp styles and fix conversation styling

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
* Fix #10829
| ![image](https://github.com/nextcloud/spreed/assets/84044328/08265404-89be-4323-8835-ae0ee7a9b4b7)         | ![image](https://github.com/nextcloud/spreed/assets/84044328/e91c057f-c75d-4692-9527-983d30ca5916)     |
> Fix(MessageButtonsBar): Hide copy message button for files

- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/mixins/getParticipants.js
* Fix #10677
The list is always updated unless the participants tab is inactive and there is no call.
> Fix(ParticipantsList): Update list when needed

- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/DangerZone.vue
- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
| ![image](https://github.com/nextcloud/spreed/assets/84044328/1790b2c4-d8ad-43a1-b8e3-49adf8749f03)  |![image](https://github.com/nextcloud/spreed/assets/84044328/72211112-34fd-4379-b10d-ab2e8f3959bd)     |
| ![image](https://github.com/nextcloud/spreed/assets/84044328/1a9cb18c-3dcc-41f0-8721-028705616334) | ![image](https://github.com/nextcloud/spreed/assets/84044328/bc6a8256-8c8a-4249-9bf5-d11a28a7f4c7)|
| ![image](https://github.com/nextcloud/spreed/assets/84044328/3d2c3860-a470-4f6d-b7cd-86738a5b5c03) | ![image](https://github.com/nextcloud/spreed/assets/84044328/d76f753c-34fc-43e3-9e28-c6a2c33b2f8d)
> Replace OC dialog with NcDialog

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Replace various confirmation screens with the NcDialog component [#10812](https://github.com/nextcloud/spreed/issues/10812)
- Fix mentions at the beginning of the text in captions [#10831](https://github.com/nextcloud/spreed/issues/10831)
- Fix not breaking the JSON response when removing the last reaction of a message [#10832](https://github.com/nextcloud/spreed/issues/10832)
- Remove previous style adjustments from left sidebar [#10818](https://github.com/nextcloud/spreed/issues/10818)
-  Migrate the last set of event listeners to be service listeners
> Release/18.0.0 beta.2

- lib/Controller/RoomController.php
- openapi.json
- tests/integration/features/chat/notifications.feature
```
OCA\Talk\Service\SessionService::updateSessionState(): Argument #1 ($session) must be of type OCA\Talk\Model\Session, null given, called in /…/apps/spreed/lib/Controller/RoomController.php on line 1703 in file …/apps/spreed/lib/Service/SessionService.php line 71
```
> fix(session): Don't attempt to set session state without a session

- lib/Chat/Parser/UserMention.php
- lib/Room.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat/mentions.feature
> fix(chat): Handle `at-all` in note to self

- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/services/DavClient.js
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
* Fix #10851 
* Solution initially was copied from https://github.com/nextcloud/viewer/commit/ab86d7f001327c6bc193a00f72005f3cd6ff0d17, but I've missed that request token can be updated and thus new client object is required
> fix(DAVClient): wrap DAV client creation in a function

- src/composables/useActiveSession.js
* Fix 404 in the console, when there is no session for logged in user (at least conversation is not joined => token is empty)
No visual changes. Also no errors in the console
> fix(activeSession): don't set state for cases when token is undefined

- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/services/DavClient.js
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
Manual backport of #10877, as we have webdav lib bumped starting from Talk 17
> [stable27] fix(DAVClient): wrap DAV client creation in a function

- src/components/LeftSidebar/LeftSidebar.vue
* Fix #10878
| ![image](https://github.com/nextcloud/spreed/assets/93392545/4d45460c-742a-4377-b4b2-af70127c42e2)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/96a11deb-2f5f-4299-b1b3-cf726ff82e85)        |
> fix(LeftSidebar): replace three-dot icon with chat-plus icon in

- src/components/LeftSidebar/LeftSidebar.vue
* Fix #10882
* Same logic as for filters reused
[Screencast from 14.11.2023 15:47:45.webm](https://github.com/nextcloud/spreed/assets/93392545/f71f1177-c56b-4e0c-b47e-5ce9827b591e)
> fix(LeftSidebar): reuse logic for unread mentions in pop-up button

- src/components/NewMessage/NewMessageUploadEditor.vue
* Fix #10883 
* Logic is copied from https://github.com/nextcloud/spreed/blob/f4d3343e20eb8390ccc55279fe8e64080562dfc7/src/components/ChatView.vue#L23-L25
Style overview (when dragged over):
In action:
https://github.com/nextcloud/spreed/assets/93392545/6ddd1f15-63de-4a84-bb79-52e835e02b2e
> feat(shares): add drag-n-drop option in the modal

- src/components/LeftSidebar/LeftSidebar.vue
> [stable27] fix(LeftSidebar): reuse logic for unread mentions in pop-up button

- lib/Service/ParticipantService.php
* Fix `Attempt to read property \"message\" on null at …/apps/spreed/lib/Service/ParticipantService.php#1268`
> fix(sip-dialout): Fix the successful dialout case when error is null

- package-lock.json
- package.json
- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/Screen.vue
- src/components/CallView/shared/VideoVue.vue
- src/mixins/devices.js
- src/utils/attachmediastream.js
- src/utils/webrtc/models/CallParticipantModel.js
* Fix #10910
The [original `attachMediaStream`](https://github.com/otalk/attachMediaStream) provides CJS and AMD versions to use in RequireJS and Browserify.
**The CJS version** has an issue with imported inside `webrtc-adapter` with `export default` behavior in ESM-CJS interop. `webrtc-adapter` defines it as `__esModule`: https://npmfs.com/package/webrtc-adapter/8.2.3/dist/adapter_core.js. This is a commonly used by bundlers approach, but it is not a standard (there is no standard, it is a known undefined behavior).
But old CJS version `attachMediaStream` doesn't respect `__esModule` and imports `webrtc-adapter` wrong. We fixed it with a babel plugin in the past.
**The AMD version** seemed to work. But for an unknown reason breaks the audio stream in Safari.
See also: …
> fix: audio/video stream in Safari by coping `attachmediastream` to source in `ESM` format

- src/utils/webrtc/simplewebrtc/peer.js
* Fix #6094 
Currently based on `fix/fork-attachmediastream` branch!
* Start/Join a call with Safari
* Mute yourself 
* Wait a bit (~1 minute)
* Try to unmute yourself
With `fix/fork-attachmediastream`
=> the UI shows as unmuted, but no audio is transmitted (most of the time)
With this PR:
=> Works
> Keep track of senders to allow unmutung with Safari

- src/deck.js
- src/init.js
- src/mainAdminSettings.js
- src/mainRecording.js
- src/maps.js
> fix(deps): Readd fixed style import from nextcloud/dialogs

- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
* Fix #10873
* Reset `input[type="file"]` value when upload files to store
* Fix #10845 
* Talk Desktop client should have an old interface against server <27 (only dismiss-send)
* Fix how `findUniquePath()` function handles filenames with suffixes
| ![image](https://github.com/nextcloud/spreed/assets/93392545/41636092-ef78-4cd9-bb3c-0d164961151e)          | ![Screenshot from 2023-11-13 16-14-35](https://github.com/nextcloud/spreed/assets/93392545/b53ce5eb-342f-4cad-b969-0fcf0c53c236) |
> fix(shares): fix issues with file upload

- lib/Chat/CommentsManager.php
> fix(search): Remove development log

- composer.lock
- lib/Search/MessageSearch.php
> fix(search): Use OCP constants for filters

- lib/Controller/BreakoutRoomController.php
- lib/Controller/CallController.php
- lib/Controller/ChatController.php
- lib/Controller/FederationController.php
- lib/Controller/FilesIntegrationController.php
- lib/Controller/PollController.php
- lib/Controller/PublicShareAuthController.php
- lib/Controller/ReactionController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Controller/SettingsController.php
- lib/Controller/SignalingController.php
- lib/Controller/TempAvatarController.php
- lib/Service/BreakoutRoomService.php
- openapi.json
* Based on https://github.com/nextcloud/spreed/pull/10856
> fix(API): Add more specific int-types

- docs/call.md
- lib/Controller/CallController.php
- lib/Service/ParticipantService.php
- openapi.json
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/callapi/notifications.feature
- As moderator 1 join a call
- As moderator 2 join a call
- Add user 3 to the call
- In "parallel" with moderator 1 winning:
- As moderator 1 remove user 3 from the call
- As moderator 2 ring user 3
- Result:
- Before: Exception breaks the request => 500
- After: 404 returned
> fix(call): Handle DoesNotExistException when ringing an attendee

- src/utils/webrtc/simplewebrtc/peer.js
Reverts nextcloud/spreed#10913
> Revert "Keep track of senders to allow unmutung with Safari"

- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
* Part of #10758
* Reverts message sorting in system messages group, and show them in natural order
| 🏚️ Before (weird sort) | 🏡 After (original order) |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/8f590a80-2672-4d80-b47a-ccc4a5da69c0)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/a8a0d9c8-f727-42e9-a7be-a505649cdfa0)        |
> fix(messages): revert "sort messages within one group"

- src/components/AdminSettings/HostedSignalingServer.vue
* Type in the input fields
Regression from https://github.com/nextcloud/spreed/commit/ae7632078357b76aefabea971a960656f68f7ff8 it seems.
🏚️ Before | 🏡 After 
-----------|----------
> fix(settings): Fix Hosted HPB settings UI

- lib/Command/Room/TRoomCommand.php
- lib/Command/User/TransferOwnership.php
- lib/Controller/RoomController.php
- lib/Controller/SignalingController.php
- lib/Listener/AMembershipListener.php
- lib/Listener/CircleDeletedListener.php
- lib/Listener/GroupDeletedListener.php
- lib/Manager.php
- lib/MatterbridgeManager.php
- lib/Service/BreakoutRoomService.php
- lib/Service/ParticipantService.php
> fix(API): Move away from own deprecated constants

- lib/Service/ParticipantService.php
- tests/integration/features/callapi/one-to-one.feature
* Fix #10595
- Was already blocked indirectly because the room is read only, but now it's more clear and tested.
> fix(calls): Explicitly block calls in former one-to-one

- src/App.vue
* Fix #10907 
🏡 After
https://github.com/nextcloud/spreed/assets/93392545/0caf278d-855d-462d-8e06-945abfb68979
> fix(search): restore app search behaviour (wait for nextTick, use refs)

- lib/Chat/Changelog/Manager.php
> feat(chat): Add changelog conversation entries for Talk 18

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(settings): Remove non-working notification settings for guests [#10976](https://github.com/nextcloud/spreed/issues/10976)
- fix(settings): Fix option to request an HPB trial [#10967](https://github.com/nextcloud/spreed/issues/10967)
- fix(settings): Fail recording server test when an HPB was given as recording backend [#10950](https://github.com/nextcloud/spreed/issues/10950)
- fix(chat): Hide delete option for guests [#10807](https://github.com/nextcloud/spreed/issues/10807)
> Release 16.0.8

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(settings): Remove non-working notification settings for guests [#10974](https://github.com/nextcloud/spreed/issues/10974)
- fix(chat): Fix uploading files after some time of being online [#10891](https://github.com/nextcloud/spreed/issues/10891)
- fix(participants): Update participants list more regularly [#10843](https://github.com/nextcloud/spreed/issues/10843)
- fix(settings): Fix option to request an HPB trial [#10965](https://github.com/nextcloud/spreed/issues/10965)
- fix(settings): Fail recording server test when an HPB was given as recording backend [#10948](https://github.com/nextcloud/spreed/issues/10948)
- fix(chat): Hide delete option for guests [#10806](https://github.com/nextcloud/spreed/issues/10806)
- fix(chat): Fix sorting of system messages …
> Release 17.1.3

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Allow drag'n'drop of files onto the caption dialog [#10898](https://github.com/nextcloud/spreed/issues/10898)
- Add support for "person" and "modified" filter options of the global search [#10909](https://github.com/nextcloud/spreed/issues/10909)
- Improve documentation by adding magic strings and values to parameters [#10857](https://github.com/nextcloud/spreed/issues/10857)
- Require compatible clients when recording consent is enabled [#10969](https://github.com/nextcloud/spreed/issues/10969)
- Revert: Try to fix Safari unmute after being muted for a longer time [#10954](https://github.com/nextcloud/spreed/issues/10954)
- Move away from deprecated constants and functions [#10975](https://github.com/nextcloud/spreed/issues/10975)
- fix(settings): Remove …
> Release 18.0.0 rc.1

- CHANGELOG.md
- Allow drag'n'drop of files onto the caption dialog [#10898](https://github.com/nextcloud/spreed/issues/10898)
- Add support for "person" and "modified" filter options of the global search [#10909](https://github.com/nextcloud/spreed/issues/10909)
- Improve documentation by adding magic strings and values to parameters [#10857](https://github.com/nextcloud/spreed/issues/10857)
- Require compatible clients when recording consent is enabled [#10969](https://github.com/nextcloud/spreed/issues/10969)
- Revert: Try to fix Safari unmute after being muted for a longer time [#10954](https://github.com/nextcloud/spreed/issues/10954)
- Move away from deprecated constants and functions [#10975](https://github.com/nextcloud/spreed/issues/10975)
- fix(settings): Remove …
> chore(release): Add changelog for 16.0.8, 17.1.3 and 18.0.0-rc.1

- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
* Fix #10872 
* Improve connection and syncronize main chat input and upload dialog input:
* When message / upload is sent, clear both
* When in the process, jump freely between views with text keeped
🏡 After
https://github.com/nextcloud/spreed/assets/93392545/d28026fa-2feb-4b74-ba2a-90137c50a4c9
> fix(uploads): allow to send empty uploads as normal messages

- src/components/LeftSidebar/SearchBox/SearchBox.vue
* Fix issue, described in #10908
> when focusing the search box, we're facing a loop for mobiles / desktops with small screen resolution:
> - Tabbing from input moves the focus to the trailing button
> - At the nextTick, trailing button will be deleted, as system assumes search field to be blurred
> - No element to focus => focus-trap falls back to the first available element => input field again
Workaround from Marco: setting a negative tabindex on the trailing button unless there is a non-empty value
🏚️ Before
https://github.com/nextcloud/spreed/assets/93392545/1223aad1-8e81-488b-a1aa-a9975978d933
🏡 After
https://github.com/nextcloud/spreed/assets/93392545/e874df3e-06d7-4f2e-9266-eeb3d7d312de
> fix(search): change conditions for showing trailing button

- src/components/NewMessage/NewMessage.vue
Current placeholder `Write message, @ to mention someone …` is a bit too long and doesn't fit well in the sidebar. At the same time, the instruction is not complete anyway, without a mention of emoji-picker `:` and smart picker `/` 
| ![image](https://github.com/nextcloud/spreed/assets/25978914/43c673b5-8645-4218-978a-b2391b624141) | ![image](https://github.com/nextcloud/spreed/assets/25978914/f03df298-569a-44af-97f5-7cc9a2a45852) |
> fix(chat): use the default new message placeholder

- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
> [stable28] fix(uploads): allow to send empty uploads as normal messages

- lib/Listener/RestrictStartingCalls.php
* Did a performance check with #6983 and noticed that there where O(n) queries more
> fix(calls): Remove a query in a loop when ending call for everyone

- lib/AppInfo/Application.php
- lib/Middleware/ParameterOutOfRangeMiddleware.php
* Requires nextcloud/server#41779
* Fix #11015
> fix(API): Add ParameterOutOfRange middleware

- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
- src/utils/__tests__/fileUpload.spec.js
- src/utils/fileUpload.js
* Fix #10894 
- refactor `utils/fileUpload.js`
- add test coverage for it (maybe missed some examples?)
- before uploading, check if there are any duplicate names in the list (`file.txt` and `file (2).txt` are counted)
- if all names are unique, should be safe to upload in parallel
- if not, extract duplicates and upload one them after uniques one by one (taking longer :snail:, but ensures each upload will have unique path)
- before sharing, check if caption was provided (should not be relevant then group share will be implemented)
- if not, the order is probably not important, so we can share all files in parallel, and they may end up in chat mixed
- if yes, share in parallel all except last one, then share last file with caption (taking longer :snail:, but file with caption will be at …
> fix(shares): handle shares with duplicate names and caption message

- lib/Notification/Notifier.php
- tests/integration/features/callapi/lobby.feature
* Fix `Undefined variable $participant at …/apps/spreed/lib/Notification/Notifier.php#252`
> Fix undefined $participant when calling a lobbied room

- src/utils/webrtc/simplewebrtc/peer.js
* Fix #6094 
After lots of manual trying, it looks like the safari bug was introduced between 12.0.0-alpha2 and 12.0.0-alpha3. After bisecting the commit https://github.com/nextcloud/spreed/commit/abe5633824b06ddfd97869dab6cb12ebbc8407ef seems to be the problem. It belongs to the PR https://github.com/nextcloud/spreed/pull/5660 which replaces disabled tracks with a null track to reduce the amount of data being sent. Reverting the commit above makes the problem #6094 not reproducible anymore in safari.
I don't know if there's a way to use https://github.com/nextcloud/spreed/blob/main/src/mixins/browserCheck.js in `peer.js` as well, currently I just used `ua-parser-js` directly.
Based on the additional safari check, this should only effect safari and no other browsers.
> Fix lost audio track on safari

- src/components/CallView/Grid/Grid.vue
> fix(CallView): pass method reference instead of result to debounce function

- src/store/quoteReplyStore.js
* Fix #11023 
* Duplicate code from NewMessage component: https://github.com/nextcloud/spreed/blob/54655bf99144848c48ef064387a65f6d552bac75/src/components/NewMessage/NewMessage.vue#L524-L528
[Screencast from 30.11.2023 14:10:29.webm](https://github.com/nextcloud/spreed/assets/93392545/7802299d-ca09-4cc3-93e2-c11ee2d06c00)
> fix(chat): patch stored message input

- lib/Search/CurrentMessageSearch.php
- lib/Search/MessageSearch.php
Possible since https://github.com/nextcloud/server/pull/41646
> fix(search): Hide "Messages in current conversation" when not on talk

- src/PublicShareAuthSidebar.vue
- src/stores/guestName.js
* Fix #10959
The condition in MediaSettings for displaying the display name input ( theoretically) should be valid only in `PublicShareAuthSidebar` when the user is a guest because in all other windows, the guest name pop up window is always shown first and cannot be bypassed. 
🏚️ Before (opacity to show both) 
🏡 After
https://github.com/nextcloud/spreed/assets/84044328/60ca1239-f475-4eaa-832d-0b4231edfaf3
TODO
> fix(AuthSidebar): Order popups

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 18.0.0 rc.2

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix #11043
| ![image](https://github.com/nextcloud/spreed/assets/93392545/0754d203-5d48-42e2-a2b0-c0881dc45406)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/91caa1f1-6b6d-433a-a14d-2c3a5561b278)        |
> get text color from theme for unread marker

- src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
* Fix #10755
Close Button has height 44px in `ContactSelectionBubble` whereas selected contacts div goes lower ( 40.8px), causing the extra scroll. 
| ![image](https://github.com/nextcloud/spreed/assets/84044328/17c91f00-9966-4870-bc07-761eb833fa8a)  | ![image](https://github.com/nextcloud/spreed/assets/84044328/7eccf7a7-63fe-4f74-ab2c-769a784f6283)  |
> fix(SetContacts ): Remove unnecessary scroll

- src/mixins/getParticipants.js
* Fix #11048
* Upon creation, we save debounced functions with their context. This alows to cancel currently scheduled executions
* Might help for both start/end call
Patch for testing:
<details>
```
Index: src/mixins/getParticipants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/mixins/getParticipants.js b/src/mixins/getParticipants.js
--- a/src/mixins/getParticipants.js	(revision 7cd9746d80542c1cc1b244c062fb4185aaded33a)
+++ b/src/mixins/getParticipants.js	(date 1701433028038)
@@ -35,6 +35,7 @@
participantsInitialised: false,
fetchingParticipants: false,
pendingChanges: false,
+			i: 0,
debounceFastUpdateParticipants: null,
debounceSlowUpdateParticipants: …
```
> fix(participants): cancel scheduled request when requesting new one

- src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
* Fix #11039
| ![image](https://github.com/nextcloud/spreed/assets/84044328/a1b6a67b-7583-428f-b015-59fb4c839ab9)   | ![image](https://github.com/nextcloud/spreed/assets/84044328/954e92f8-65c6-45a6-a905-8d3f5916ac81) |
> feat(NewGroupConversation): Always show create conversation button

- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
* Fix #11117 
* Button for silent send is brought back to upload dialog
* Following API, silent flag is passed with share metadata
* Fix #11118 
* Same as for drag-n-drop in dialog, if current upload is existing, we reuse it
> fix(shares): handle silent sending and input paste correctly

- src/composables/useActiveSession.js
* Fix #10887
* always reset timer on window focus change
* do not set inactive state when in call
> fix(activeSession): minor fixes

- lib/Chat/Parser/SystemMessage.php
- lib/Controller/ChatController.php
- lib/Share/Helper/FilesMetadataCache.php
- tests/php/Chat/Parser/SystemMessageTest.php
- tests/php/Controller/ChatControllerTest.php
* Fix https://github.com/nextcloud/spreed/issues/10844
I tried to take a look at #10844. Leaving the tests and documentation aside, is this the correct way to solve it or would we need to take another different approach regarding performance?
> Add metadata to file parameters

- src/App.vue
* Drop overwritten styles for AppNavigationToggle  in call
* change theme to dark specifically for the toggle button
Light theme | Dark theme
-- | --
[Screencast from 04.12.2023 11:18:58.webm](https://github.com/nextcloud/spreed/assets/93392545/290a1208-f997-4df5-9e4a-9e8034db1891)
> fix(App): switch toggle button to dark theme in call

- src/PublicShareAuthRequestPasswordButton.vue
- src/PublicShareAuthSidebar.vue
- src/components/MediaSettings/MediaSettings.vue
* Fixes partially #10759
What's changed ? 
- Media Settings doesn't include _"always show preview for this conversation"_ as the password request generates a new room each time.
- "silent call" option is hidden as it is important to ping the share owner about the request call.
- Removed an extra div in the button component of requesting password
|![image](https://github.com/nextcloud/spreed/assets/84044328/1a671721-446d-41b3-a9b9-87e604ddddaa) | ![image](https://github.com/nextcloud/spreed/assets/84044328/3b8f9ca1-861d-4fd9-8af5-63499162a354)   |
> Fix(File share authentication): Remove unnecessary options

- src/composables/useActiveSession.js
* Fix #11126 
* `document` => `document.body` fixes behavior on Firefox with event registration
* `mouseenter` now mark session as active, `mouseleave` restarts a timer
* moving the mouse and scrolling within tab borders should be covered, as mouse entered the tab by that moment
> fix(session): track mouse movement activity

- src/utils/webrtc/simplewebrtc/peer.js
* Manual backport of https://github.com/nextcloud/spreed/pull/11006
It is correct that we use `require` here, since we are still using webpack and haven't moved to esm modules on stable27, right?
> [stable27] Fix lost audio track on safari

- CHANGELOG.md
- feat(call): Add screensharing support to the viewer-overlay [#11033](https://github.com/nextcloud/spreed/issues/11033)
- feat(conversations): Always show create conversation button [#11104](https://github.com/nextcloud/spreed/issues/11104)
- fix(chat): Add metadata to file parameters on API level so clients can calculate aspect ratio of previews [#11131](https://github.com/nextcloud/spreed/issues/11131)
- fix(chat): Fix various cases of handling (in)active sessions while chatting and calling [#11125](https://github.com/nextcloud/spreed/issues/11125) [#11140](https://github.com/nextcloud/spreed/issues/11140)
- fix(chat): Only load current absence not future ones [#11124](https://github.com/nextcloud/spreed/issues/11124)
- fix(chat): Fix …
> chore(release): Add changelog for 18.0.0-rc.3

- lib/Controller/BreakoutRoomController.php
- openapi.json
- vendor-bin/openapi-extractor/composer.lock
| Dev Changes                 | From    | To      | Compare                                                                         |
|-----------------------------|---------|---------|---------------------------------------------------------------------------------|
| nextcloud/openapi-extractor | d99e9c0 | 083417a | [...](https://github.com/nextcloud/openapi-extractor/compare/d99e9c0...083417a) |
> fix(openapi): Bump openapi-extractor for improved API results

- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/ExpirationSettings.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/ConversationSettings/ListableSettings.vue
- src/components/ConversationSettings/RecordingConsentSettings.vue
* Fix #11154
| ![image](https://github.com/nextcloud/spreed/assets/93392545/f9a198e2-2e58-49d1-8a7c-256bcba7d34b)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/289f3cdb-fee7-44a5-a48a-f1196bb2ca65)       |
> fix(settings): apply correct conditions to expiration settings

- src/components/MessagesList/MessagesGroup/Message/Message.vue
* Fix regression from #10687
* Originates from #11159
* User mention is forced LTR in system messages as well
| ![image](https://github.com/nextcloud/spreed/assets/93392545/11176039-f007-4be6-a5b9-d45ad559cafb)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/753e951d-bebf-44f8-93ff-180f2a62c4cc)        |
> fix(messages): apply ltr styles to system messages

- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/ExpirationSettings.vue
* Manual backport of #11156 
| ![Screenshot from 2023-12-08 11-52-39](https://github.com/nextcloud/spreed/assets/93392545/a10b96c6-3221-4edf-993a-4599fc19910b)          | ![Screenshot from 2023-12-08 11-52-59](https://github.com/nextcloud/spreed/assets/93392545/01624de7-da0a-47d3-a9f6-62dd788c9d0c)        |
> [stable27] fix(settings): apply correct conditions to expiration settings

- lib/Share/Helper/FilesMetadataCache.php
> fix(CI): Make psalm more happy about not returning null

- src/utils/signaling.js
For easier debugging I suggest we include the used backend url in the error message:
> Add backend url to connection error

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- 🗒️ Note to self [#2196](https://github.com/nextcloud/spreed/issues/2196)
- 🎙️ Show speaker while screensharing [#4478](https://github.com/nextcloud/spreed/issues/4478)
- 🏷️ Add a caption to your file before sharing it into the chat [#5354](https://github.com/nextcloud/spreed/issues/5354)
- 👤 Ask Guest to enter a name when connecting [#855](https://github.com/nextcloud/spreed/issues/855)
- 🤩 Animated call reactions [#10561](https://github.com/nextcloud/spreed/issues/10561)
- 🖋️ Optionally require consent before joining a recorded call [#10348](https://github.com/nextcloud/spreed/issues/10348)
- 📲 Allow calling phone numbers from within Talk using SIP dialout [#10346](https://github.com/nextcloud/spreed/issues/10346)
- 🔎 Add support for "person" and "modified" filter options of the new …
> Release 18.0.0

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
* Follow-up for web for #11093
* Fix #11041 
:warning: Metadata requires "Photos" app to be enabled
| Uploaded non-media files preview (text, audio) | - |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/fa2836e2-6c7f-44a7-bed4-3dfda899c4a5)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/3c562662-7f45-44fc-b3db-f5a30badd85c)        |
| Jump after preview loaded | - |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/753b509b-5188-4339-877c-f6c270b5fe35) | ![image](https://github.com/nextcloud/spreed/assets/93392545/4e074b75-565a-4432-8ed2-c85b3f616aff) |
| Double hover on message | - |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/8f4928a3-7521-4d7e-ba22-481fb2ef77cb) | …
> fix(shares): reserve space for file preview while it's loading

- package-lock.json
🏚️ Before
```yaml
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix`
node_modules/axios
browserify-sign  2.6.0 - 4.2.1
Severity: high
browserify-sign upper bound check issue in `dsaVerify` leads to a signature forgery attack - https://github.com/advisories/GHSA-x9w5-v3q2-3rhw
fix available via `npm audit fix`
node_modules/browserify-sign
crypto-js  <4.2.0
Severity: critical
crypto-js PBKDF2 1,000 times weaker than …
```
> [stable27] chore(deps): audit dependencies

- docs/chat.md
- lib/Chat/ChatManager.php
- lib/Controller/BotController.php
- lib/Controller/BreakoutRoomController.php
- lib/Controller/ChatController.php
- lib/Flow/Operation.php
- lib/Service/BreakoutRoomService.php
- openapi.json
- tests/php/Chat/ChatManagerTest.php
- vendor-bin/openapi-extractor/composer.lock
> feat(chat): Rate limit guests when mentioning others

- lib/Middleware/CanUseTalkMiddleware.php
- lib/Middleware/InjectionMiddleware.php
> fix(OCP): Move away from deprecated RedirectToDefaultAppResponse

- src/components/MediaSettings/VideoBackgroundEditor.vue
* Fix #11204
* Regression from #10916
* Helper function now returns an object:
https://github.com/nextcloud/spreed/blob/8c37fbe7164615a08b912c1eaa398d028cdb6b11/src/utils/fileUpload.js#L95
> fix(shares): accept returned value from function

- src/components/ChatView.vue
* Fix #10148 
* Regression from #9861 
* Turns out there was a simple way :see_no_evil: 
* z-index set to 2, to be above message actions (user can always scroll to lift actions up)
| ![image](https://github.com/nextcloud/spreed/assets/93392545/758ec92c-8b89-417a-af9c-ee0050593fd2)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/31e009d2-e1ef-4202-8e3a-200c024552ca)        |
> fix(chat): attach button position to invisible wrapper

- src/components/ChatView.vue
Manual backport of https://github.com/nextcloud/spreed/pull/11213
Tested
> [stable27] fix(chat): attach button position to invisible wrapper

- src/components/CallView/shared/ViewerOverlayCallView.vue
> fix(call): add safeguard for remote screen checking

- src/components/MediaSettings/MediaSettings.vue
*  reset 'Start recording immediately with the call' checkbox on modal close
[Screencast from 14.12.2023 11:59:57.webm](https://github.com/nextcloud/spreed/assets/93392545/2fd188bc-f5e9-44cd-90d8-9b0c93727f6f)
> fix(call): reset Media settings checkbox on modal close

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/components/Quote.vue
- Regression from #11120 
-  Trimming is only applicable when it is an image with a caption
| ![image](https://github.com/nextcloud/spreed/assets/93392545/3a638e2c-392f-448f-bf7a-597c9e5a249c)  | ![image](https://github.com/nextcloud/spreed/assets/93392545/abb1111d-a1e2-4a29-a33a-4531eb97d59e)  |
> Fix(Quote): Don't trim the quote when it is not image share with caption

- lib/AppInfo/Application.php
* Fix #11223 
We change the order of the event listeners so that:
- Call state is updated by the activity listener
- "X left the call" appears before the call summary
- Signaling is triggered after the chat was updated
- Push notifications are send after everything is done
> fix(notifications): Fix the order of event listeners 

- src/store/conversationsStore.js
* Fix #11101
| ![image](https://github.com/nextcloud/spreed/assets/84044328/3bcb2cb4-8ae2-4bec-97b7-0b12c8eaf45c)    | ![image](https://github.com/nextcloud/spreed/assets/84044328/d73e0219-3341-4279-a764-1a0ba3df4a0d)     |
> Fix(ParticipantsStore): Purge the store so it deletes the removed conversation

- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Fix the play icon alignment and make the whole link semantically valid (no `div` allowed inside `a`)
| Before | After |
|:---------:|:------:|
|![2023-12-14_10-09](https://github.com/nextcloud/spreed/assets/14975046/c6d9d3f5-6c48-4b16-a555-6bc5da8bfe4d)|![2023-12-14_10-08](https://github.com/nextcloud/spreed/assets/14975046/5c1afc24-c969-4b4c-b58f-042461174296)|
> fix(preview): preview size and semantic inside `a` element

- docs/chat.md
- lib/Chat/ChatManager.php
- lib/Chat/ReactionManager.php
- lib/Chat/SystemMessage/Listener.php
- src/components/NewMessage/NewMessage.vue
- src/store/fileUploadStore.js
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/bootstrap/SharingContext.php
- tests/integration/features/chat-1/file-share.feature
- tests/integration/features/chat-1/notifications.feature
- tests/php/Chat/ChatManagerTest.php
- tests/php/Chat/SystemMessage/ListenerTest.php
Manual backport of #11224
chatExtrasStore wasn't backported, so Pinia actions were replaced with Vuex (1st commit)
Tested
> [stable28] fix(shares): reply to message with attachments

- CHANGELOG.md
- fix(shares): Fix notifications for captions with mentions or as a reply [#11242](https://github.com/nextcloud/spreed/issues/11242)
- fix(shares): Fix replying to message with attachments [#11242](https://github.com/nextcloud/spreed/issues/11242)
- fix(shares): Reserve space for file previews while loading [#11196](https://github.com/nextcloud/spreed/issues/11196)
- fix(chat): Don't trim the quote when it is not an image share with caption [#11237](https://github.com/nextcloud/spreed/issues/11237)
- fix(call): Reset "Start recording" checkbox on "Media settings" close [#11227](https://github.com/nextcloud/spreed/issues/11227)
- fix(call): Fix uploading files as image for the call background [#11214](https://github.com/nextcloud/spreed/issues/11214)
- …
> chore(release): Add changelog for 18.0.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(shares): Fix notifications for captions with mentions or as a reply [#11242](https://github.com/nextcloud/spreed/issues/11242)
- fix(shares): Fix replying to message with attachments [#11242](https://github.com/nextcloud/spreed/issues/11242)
- fix(shares): Reserve space for file previews while loading [#11196](https://github.com/nextcloud/spreed/issues/11196)
- fix(chat): Don't trim the quote when it is not an image share with caption [#11237](https://github.com/nextcloud/spreed/issues/11237)
- fix(call): Reset "Start recording" checkbox on "Media settings" close [#11227](https://github.com/nextcloud/spreed/issues/11227)
- fix(call): Fix uploading files as image for the call background [#11214](https://github.com/nextcloud/spreed/issues/11214)
- …
> Release 18.0.1

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
- src/store/messagesStore.js
* Fix #10768 
* ATM allows to retry with files marked as 'failed-upload' (in case upload failed when putting on webdav step)
[retry-upload.webm](https://github.com/nextcloud/spreed/assets/93392545/cc9fe7a8-e775-49f5-8acb-6d4f7b6312db)
> [!TIP]
> Add `if (Math.random() < 0.5) throw new Error()` to `performUpload` function to fail some uploads
> fix(shares): allow to retry failed uploads

- src/App.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/components/ChatView.vue
- src/components/TopBar/TopBarMenu.vue
- src/store/uiModeStore.js
* Fix #8709
* Fix #9626
* Replaces #9792
Should be safe to use a `body` element while you're not in the fullscreen (as tested with ViewerOverlayCallView).
Also as long as we won't register a fullscreen state in sidebar (for Files page, for example), modal will end up in `body`, so above the Viewer embedded
>[!WARNING]
>Behaviour change: as NcModal component has more reasons against being re-mounted, then pros, hotkey 'F' to toggle Fulscreen mode is now disabled when any modal is open https://github.com/nextcloud/spreed/pull/11222/commits/368e43ab158577f367fc7b2a94543c443e7afa50
| 🖼️  Window frame | 🏞️ Fullscreen |
| Files Sidebar          | -        |
| Talk main app | - |
> fix: use body element if not the fullscreen

- src/App.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/components/ChatView.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/TopBar/TopBarMenu.vue
- src/store/uiModeStore.js
Backport of https://github.com/nextcloud/spreed/pull/11222
> [stable27] fix: use body element if not the fullscreen

- CHANGELOG.md
- fix(UI): Allow joining a call while editing a document [#11260](https://github.com/nextcloud/spreed/issues/11260)
- fix(chat): Fix grouping of chat messages when they include the readmarker [#11068](https://github.com/nextcloud/spreed/issues/11068)
- fix(call): Fix lost audio tracks in Safari after being muted a longer time [#11145](https://github.com/nextcloud/spreed/issues/11145)
- fix(occ): Fix verification of STUN server details [#11194](https://github.com/nextcloud/spreed/issues/11194)
- fix(hosted-hpb): Correctly handle API response codes of hosted High-performance backend when the account expired [#11045](https://github.com/nextcloud/spreed/issues/11045)
- fix(occ): Fix verification of STUN server details [#11195](https://github.com/nextcloud/spreed/issues/11195)
- …
> chore(release): Add changelog for 16.0.9 and 17.1.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(UI): Allow joining a call while editing a document [#11260](https://github.com/nextcloud/spreed/issues/11260)
- fix(chat): Fix grouping of chat messages when they include the readmarker [#11068](https://github.com/nextcloud/spreed/issues/11068)
- fix(call): Fix lost audio tracks in Safari after being muted a longer time [#11145](https://github.com/nextcloud/spreed/issues/11145)
- fix(occ): Fix verification of STUN server details [#11194](https://github.com/nextcloud/spreed/issues/11194)
- fix(hosted-hpb): Correctly handle API response codes of hosted High-performance backend when the account expired [#11045](https://github.com/nextcloud/spreed/issues/11045)
> Release 17.1.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(occ): Fix verification of STUN server details [#11195](https://github.com/nextcloud/spreed/issues/11195)
- fix(hosted-hpb): Correctly handle API response codes of hosted High-performance backend when the account expired [#11045](https://github.com/nextcloud/spreed/issues/11045)
> Release 16.0.9

- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageAttachments.vue
- src/components/SettingsDialog/SettingsDialog.vue
* Fix #11236
* For chat attachments: added multiselect
`picker.setType` is deprecated, but it was responsible for buttons labels => `Choose` everythere
| ![image](https://github.com/nextcloud/spreed/assets/93392545/5b02669b-6859-462a-8fe8-05fe502fcc1e)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/abb5886b-5771-4026-bac4-bf3594d96b93)        |
> fix(shares): use FilePicker component directly

- package-lock.json
- package.json
* Bumps libraries to the latest before EOL:
* `vue`
* `vue-template-compiler`
* Smoke tested
> chore(deps): bump `vue` libraries from 2.7.15 to v2.7.16

- package-lock.json
- package.json
- src/App.vue
- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/ConversationSettings/EditableTextField.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/NewMessage/NewMessage.vue
- src/stores/__tests__/sharedItems.spec.js
- src/stores/sharedItems.js
* Bump `@nextcloud/vue` library from 8.3.0 to 8.4.0
* Fix #11285
* Migrate from `isMobile` mixin to composable
* Define containers for pickers in dialog (backport! :ship: )
* Drop some overwritten styles for NcRichContenteditable
* Fix error with fetching in SharedItemsBrowser (backport! :ship: cc @SystemKeeper)
* All visual and a11y changes as per library changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.4.0
🏚️ Before 
--
🏡 After
--
TODO: check why tests worked fine here: https://github.com/nextcloud/spreed/blob/main/src%2Fstores%2F__tests__%2FsharedItems.spec.js#L139
> chore(deps): Bump nextcloud/vue to 8.4.0

- src/stores/__tests__/reactions.spec.js
- src/stores/reactions.js
* Fix `resetReactions` action, which prevents rendering of following messages
* Add test for `purgeReactionsStore`
| ![image](https://github.com/nextcloud/spreed/assets/93392545/93aee645-4de7-4f37-8e6b-f4cc87f2142b)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/6618dd11-543a-4af1-bde8-22022cdc4265)        |
> fix(reactions): add guardian before resetting reactions

- docs/bots.md
- lib/Controller/BotController.php
- openapi.json
> fix(bots): Don't allow empty messages from bots

- lib/Service/AvatarService.php
> fix(avatar): Fix avatars without PHP intl module

- appinfo/routes/routesChatController.php
- docs/chat.md
- lib/Chat/ChatManager.php
- lib/Chat/Parser/SystemMessage.php
- lib/Controller/ChatController.php
- lib/Manager.php
- lib/Model/Message.php
- lib/ResponseDefinitions.php
- openapi.json
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-1/edit-message.feature
* Fix #11206 
- System message hidden like with delete
- Time limitation like for delete?
- What about bots?
- If a message triggered a bot already it's yolo and will not be retriggered with the new content automatically (bot can do based on the system message?)
> feat(chat): API specs for "Edit message"

- src/components/MediaSettings/MediaSettings.vue
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesList.vue
- src/components/TopBar/CallButton.vue
- src/store/conversationsStore.js
- src/store/messagesStore.js
* Delete unused `scrollerBoundingClientRect` prop
* Move computation of `isLastCallStartedMessage` to store
* Make update of `hasCall` more clear across the app
* Prevent notifications from updating store if already done
> fix(Message): optimize getters and provided props

- lib/Chat/ChatManager.php
- lib/Controller/ChatController.php
- openapi.json
- tests/integration/features/chat-1/edit-message.feature
> fix(chat): Handle basic editing of captions

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.spec.js
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
- src/services/breakoutRoomsService.js
- src/store/breakoutRoomsStore.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
- src/stores/__tests__/reactions.spec.js
- src/stores/__tests__/sharedItems.spec.js
- src/stores/sharedItems.js
* Fix prior to federation:
* federated conversation has `token: a` and `remoteToken: b`. When we're fetching something from remote server, we're using `b`, and messages are coming with `token: b` in the body, which doesn't belong to current instance
* forcing to use local token for all messages actions / mutations
* remove all extra payload from request (don't pass the whole message, if only token/id is needed)
> fix(messagesStore): avoid usage of `message.token` 

- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Service/ParticipantService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-1/edit-message.feature
Ref #11206 
- It is known that the indicator for unread mentions can not be removed/reverted in the left sidebar, due to complexity of the necessary database query we would need to run.
> feat(chat): Edit message mention support

- .github/workflows/integration-pgsql.yml
- composer.lock
> Restore green CI after Lazy Config change in server

- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessageAttachments.vue
- src/components/RightSidebar/SharedItems/SharedItems.vue
* Split SFC file into smaller parts
* Optimize methods and getters, rename props
* Mark deleted message additionaly (fix https://github.com/nextcloud/spreed/issues/11103)
* system messages were moved 4px to the right to be aligned with normal messages
* deleted message:
Before | After
-- | --
> enh(Message): split out MessageBody component

- src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
* Fix #11355
Hint is conditioned because the user will likely pick an amount from 1 to 20, but it will be shown in case they attempt to choose outside that range.
| ![image](https://github.com/nextcloud/spreed/assets/84044328/62e17678-595d-4b89-a462-65381ab1a936)      | ![image](https://github.com/nextcloud/spreed/assets/84044328/4b6abf2a-3f07-4343-89d8-62d7e5ab4017)     |
> Fix(BreakoutRoomsEditor): Add amount validation

- lib/Controller/BotController.php
- lib/Controller/CertificateController.php
- lib/Controller/CommandController.php
- lib/Controller/FederationController.php
- lib/Controller/HostedSignalingServerController.php
- lib/Controller/MatterbridgeSettingsController.php
- lib/Controller/PageController.php
- lib/Controller/PublicShareAuthController.php
- lib/Controller/RecordingController.php
- lib/Controller/RoomController.php
- lib/Controller/SettingsController.php
- lib/Controller/SignalingController.php
- lib/Controller/TempAvatarController.php
- openapi-administration.json
- openapi-backend-recording.json
- openapi-backend-signaling.json
- openapi-backend-sipbridge.json
- openapi-bots.json
- openapi-full.json
- vendor-bin/openapi-extractor/composer.lock
- Using https://github.com/nextcloud/openapi-extractor/pull/24
> Openapi update

- .github/workflows/integration-pgsql.yml
This reverts commit 7b00d1988f4b2d094854fdf7283bb24f390cbe60.
- Reverts #11388  partly
> Revert "fix(CI): Test against Guests app branch"

- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/Federation.vue
- src/views/AdminSettings.vue
* Part of #11279
* Add Admin setting section for Federation (in debug mode only)
---
> feat(federations): provide admin setting to enable Federation in Talk

- docs/capabilities.md
- lib/Capabilities.php
- lib/Controller/ChatController.php
- tests/php/CapabilitiesTest.php
> feat(chat): Add capability for editing messages

- lib/Service/BreakoutRoomService.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/conversation-1/breakout-rooms.feature
- tests/php/Service/BreakoutRoomServiceTest.php
* API part is splitted out from #11394 
* When removing breakout rooms, status at parent is now reset (if create rooms again, they will not be marked as started)
* Updating lastActivity when requesting / dismissing the assistance allows moderators to re-fetch breakout rooms within 30s interval (`?modifiedSince`) and actually see the request (before it was once in 10 requests on a full fetch)
> fix(breakout): stop breakout rooms on removing

- src/components/MessagesList/MessagesList.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/services/participantsService.js
- src/store/participantsStore.js
* Fix #8601
* If lobby is enabled, a new button is appeare in participant action to explicitly change lobby permission for that one participant
* `isInLobby` was removed from `chatIdentifier`:
* chat is mounted/unmounted with param change anyway, so no need to depend on it
* it leaves outdated cancel requests in the store:
>[!IMPORTANT]
> HPB is required to be enabled, to receive signaling messages
In | Out
--|--
https://github.com/nextcloud/spreed/assets/93392545/fc5ae076-b86d-42c2-98fe-ca038a52e09e
> feat(meetings): selectively invite users from lobby

- src/components/CallView/shared/LocalVideo.vue
- src/components/CallView/shared/VideoVue.vue
* Fix #10563
Summary:
- Added speaking class to local video
- Slight improvement in Video component but with no visual changes.
Talking indicator is now shown on local video just like other participants videos
https://github.com/nextcloud/spreed/assets/84044328/f8607689-4e21-440b-9e2c-26eeadbbbf4e
> feat(LocalVideo): Show self talking indicator

- src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
- src/components/TopBar/TopBarMenu.vue
- src/store/breakoutRoomsStore.js
- src/store/callViewStore.js
- src/store/conversationsStore.js
- src/store/participantsStore.js
* `breakoutRoomsStore` used the old way of update: purge each room -> populate again
* With extracting method at `participantsStore`, it could be reused
* On fetching conversations, breakout rooms are also updated
* Moderators can see the request for assistance on the tab
* Non-moderators can also dismiss request for assistance, if no one else is asked for it
* has edge-cases, which should be covered by signaling patch (see mentioned issue)
>[!IMPORTANT]
> HPB is required to be enabled, to receive signaling messages
>[!NOTE]
>Does not required API patch from splitted out PR, but works better with it :rocket: 
Before | After
-|-
> enh(participants): extract and reuse `patchParticipants` action

- src/store/participantsStore.js
- src/store/participantsStore.spec.js
* Fix #11441
* Explanation here: https://v2.vuejs.org/v2/guide/reactivity.html#For-Objects
[Screencast from 25.01.2024 10:48:41.webm](https://github.com/nextcloud/spreed/assets/93392545/fc96bd9c-7053-4562-a5e5-33622a887763)
> fix(participantStore): update the whole participant object

- CHANGELOG.md
-  fix(calls): Device preview not visible when editing, uploading or viewing a file  [#11222](https://github.com/nextcloud/spreed/issues/11222)
-  fix(conversation): Make description input multi line when creating a conversation  [#11376](https://github.com/nextcloud/spreed/issues/11376)
-  fix(bot): Don't allow empty chat messages from bots  [#11353](https://github.com/nextcloud/spreed/issues/11353)
-  fix(breakout): Stop breakout rooms when they are started while deleting them  [#11409](https://github.com/nextcloud/spreed/issues/11409)
-  fix(attachments): Allow to retry failed uploads  [#11256](https://github.com/nextcloud/spreed/issues/11256)
-  fix(attachments): Fix uploading from local device  [#11331](https://github.com/nextcloud/spreed/issues/11331)
-  fix(attachments): Don't …
> chore(release): Changelog for 16.0.10, 17.1.5 and 18.0.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
-  fix(attachments): Don't allow selecting shared folders as attachment folder  [#11430](https://github.com/nextcloud/spreed/issues/11430)
> Release 17.1.5

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
-  fix(calls): Device preview not visible when editing, uploading or viewing a file  [#11222](https://github.com/nextcloud/spreed/issues/11222)
-  fix(conversation): Make description input multi line when creating a conversation  [#11376](https://github.com/nextcloud/spreed/issues/11376)
-  fix(bot): Don't allow empty chat messages from bots  [#11353](https://github.com/nextcloud/spreed/issues/11353)
-  fix(breakout): Stop breakout rooms when they are started while deleting them  [#11409](https://github.com/nextcloud/spreed/issues/11409)
-  fix(attachments): Allow to retry failed uploads  [#11256](https://github.com/nextcloud/spreed/issues/11256)
-  fix(attachments): Fix uploading from local device  [#11331](https://github.com/nextcloud/spreed/issues/11331)
-  fix(attachments): Don't …
> Release 18.0.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
-  fix(attachments): Don't allow selecting shared folders as attachment folder  [#11431](https://github.com/nextcloud/spreed/issues/11431)
> Release 16.0.10

- src/components/BreakoutRoomsEditor/SendMessageDialog.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
* Fix showing an autocomplete tribute behind modal
* NewMessageUploadEditor is never unmounted, so child component persist all the time
* If it's opened again, modal gets a new id, and NewMessage should be rerendered accordingly, so autocomplete tributes will get a new container for mounting
* Already have been done in ChatView :eyes: 
* Now also works in Fullscreen mode :see_no_evil: 
| ![image](https://github.com/nextcloud/spreed/assets/93392545/6dfea0db-c655-456a-9280-0f880b76ce17)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/eaaf7fe1-7a98-495b-a05d-7c09540ed6c7)        |
> fix(NewMessage): re-mount NewMessage component upon id change

- lib/Search/CurrentMessageSearch.php
- lib/Search/MessageSearch.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/search.feature
* API change for https://github.com/nextcloud/server/issues/42914
> feat(search): Allow to search in a dedicated other conversation with a filter

- src/components/MessagesList/MessagesList.vue
* Fix weird message scrolling (hopefully, last time)
> [!IMPORTANT]
> It's better to give it a try with a compiled Talk Desktop + c.nc to see if we'll backport it (and how far)
Explanation:
> If you don't manipulate numbers directly and only add items to the chat list, the scroll position (scrollTop) will be automatically adjusted based on the added height of the new content.
When the scrollTop value is 0 (at the top of the scrollable area), adding new items at the top will not change the scroll position. The browser will automatically adjust the scroll position to maintain the view at the same position relative to the newly added items. In this case, the new scrollTop value will also be 0 since the content was added at the top and the scroll position was already at the top.
However, if …
> fix(MessagesList): correctly handle scrollTop position

- lib/Controller/FederationController.php
- lib/Federation/FederationManager.php
- lib/Service/ParticipantService.php
- openapi-federation.json
- openapi-full.json
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
* Ref https://github.com/nextcloud/spreed/issues/11278
> feat(federation): Add room to response when accepting an invite

- package-lock.json
- package.json
* Bumps nextcloud/vue from 8.5.1 to 8.6.0
* Release [v8.6.0](https://github.com/nextcloud-libraries/nextcloud-vue/tree/v8.6.0) (2024-01-30)
* [Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.5.1...v8.6.0)
* Fix #10895
|![image](https://github.com/nextcloud/spreed/assets/93392545/6023b433-5873-42e9-9997-be0e4fef4635)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/ff1fddfe-7560-4ac9-8e0c-1200fac1e547)        |
- fix falling on body Popover with emoji skin color
> chore(deps): bump nextcloud/vue from 8.5.1 to 8.6.0

- src/assets/markdown.scss
- src/components/ConversationSettings/EditableTextField.vue
- src/components/LobbyScreen.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
* Fix #10066 
* Fix #11405
* Styles are moved to scss file, to be reused by all required components
* Follow-up: interactive checkboxes (align with message editing)
> feat: support flavored markdown in messages

- CHANGELOG.md
- appinfo/info.xml
-  fix(chat): Fix scrolling behaviour when loading older messages  [#11481](https://github.com/nextcloud/spreed/issues/11481)
-  fix(chat): Fix showing mention and emoji suggestions when writing a caption  [#11458](https://github.com/nextcloud/spreed/issues/11458)
-  fix(chat): Show mention chips when inserting a suggested mention  [#11493](https://github.com/nextcloud/spreed/issues/11493)
> chore(release): Add changelog for 18.0.3

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
-  fix(chat): Fix scrolling behaviour when loading older messages  [#11481](https://github.com/nextcloud/spreed/issues/11481)
-  fix(chat): Fix showing mention and emoji suggestions when writing a caption  [#11458](https://github.com/nextcloud/spreed/issues/11458)
-  fix(chat): Show mention chips when inserting a suggested mention  [#11493](https://github.com/nextcloud/spreed/issues/11493)
> Release 18.0.3

- src/components/CallView/CallView.vue
- src/components/CallView/Grid/Grid.vue
- src/components/CallView/shared/Screen.vue
- src/components/CallView/shared/VideoBottomBar.vue
* Move and rearrange some computed props for the CallView
* Remove unused v-for and v-if for promoted views (there is always only one model to handle)
* Unite multiple redundant wrappers
* One-time things moved to child component
* loadState and getCapabilities moved from computed props (to call them once)
* Prioritize selected LocalVideo over Screen
There's still a lot of things processing each time participants change something, but at least some unused computations were eliminated
> fix(CallView): reduce computations amount

- src/components/ConversationSettings/EditableTextField.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/NewMessage/NewMessage.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/stores/__tests__/chatExtras.spec.js
- src/stores/chatExtras.js
- src/utils/textParse.js
* Partially fix #11403
**Remark** 
Mention hint  when editing ( NcNoteCard ) will be shown if the message has `@` initially (before editing it). Otherwise, we will need to compute diff every time the text is edited (not worth it and can be large for long messages) 
| ![image](https://github.com/nextcloud/spreed/assets/84044328/278c6d5d-00f3-4cca-8332-eeb5eb707199)    | ![image](https://github.com/nextcloud/spreed/assets/84044328/6ff524b1-0731-449d-8755-d0ba27505220)      |
Newly added
> Follow-up(Edit message)

- lib/Model/Message.php
* Ref https://github.com/nextcloud/spreed/pull/11505#issuecomment-1920722608
> fix(chat): Ensure silent exists before accessing it

- src/components/LeftSidebar/ConversationsList/Conversation.vue
* Conversation (NcListItem) now indicates, if conversation is public (available for guests by link)
* Place is details above the unread counter
* To discuss:
* Icon for federated conversations:
* Same place?
* Should overwrite public icon?
* Which icon to use? https://pictogrammers.com/library/mdi/icon/shield-link-variant/ as option
| :sun_with_face: Light theme | :new_moon: Dark theme |
| Default with `--color-primary-element-text` for active            | `--color-text-maxcontrast` for others         |
> feat(ConversationIcon): highlight public conversations

- package-lock.json
- package.json
Changelog: https://github.com/nextcloud-libraries/nextcloud-router/releases/tag/v3.0.0
Should be no breaking changes, but I'd leave it for 29 only
> chore(deps): bump '@nextcloud/router' from 2.2.1 to 3.0.0

- lib/Controller/FederationController.php
- lib/Model/Invitation.php
- lib/ResponseDefinitions.php
- openapi-federation.json
- openapi-full.json
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
* Ref https://github.com/nextcloud/spreed/issues/11278#issuecomment-1920068400
> fix(federation)!: Add room name to invite and fix casing of properties

- .php-cs-fixer.dist.php
- lib/Activity/Provider/Call.php
- lib/Activity/Provider/Invitation.php
- lib/Chat/SystemMessage/Listener.php
- lib/Collaboration/Resources/ConversationProvider.php
- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Flow/Operation.php
- lib/Manager.php
- lib/Middleware/InjectionMiddleware.php
- lib/Migration/Version13000Date20210625232111.php
- lib/Migration/Version18000Date20231024141626.php
- lib/Service/BreakoutRoomService.php
- lib/Service/RecordingService.php
- lib/Service/RoomService.php
- lib/Share/RoomShareProvider.php
- tests/php/Recording/BackendNotifierTest.php
- tests/php/bootstrap.php
- Since the new rules don't fail on the old set we can apply them already
> fix(CS): Prepare coding standard update 

- src/components/ConversationSettings/BotsSettings.vue
- src/components/ConversationSettings/BreakoutRoomsSettings.vue
- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/ConversationSettings/ConversationPermissionsSettings.vue
- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/Quote.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/components/TopBar/TopBar.vue
* Fix #10562
|![image](https://github.com/nextcloud/spreed/assets/84044328/9ee04580-71e6-4a43-8076-061feb31d9f7)      | ![image](https://github.com/nextcloud/spreed/assets/84044328/eb874012-753e-4afb-9c18-a96a052fb0c0)    |
> feat(TopBar): show description during call

- src/components/TopBar/ReactionMenu.vue
* Fix #11539
To make the Math right in reactions layout, gap is set to 0. 
|![image](https://github.com/nextcloud/spreed/assets/84044328/5357dce4-565c-4517-8e05-37af9cad2eec)    | ![image](https://github.com/nextcloud/spreed/assets/84044328/d77999fc-201c-4ea7-a448-79c3325ff00c)   |
> Fix(ReactionMenu): Correct gap value

- src/components/NewMessage/NewMessageAbsenceInfo.vue
* From #11494
I just reversed the Chevron because the div gets up and space was reduced.
| ![image](https://github.com/nextcloud/spreed/assets/84044328/0944a209-d606-4b67-8ab9-372f28fed664)    |![image](https://github.com/nextcloud/spreed/assets/84044328/657bd05c-3a89-4a69-9c01-83805b4b41e3)
|
> chore(NcNoteCard): use custom icon slot

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
* Fix #11512
In Participant buttons menu, there are NcActionButtons sequentially and Vue.js might not be able to correctly track each button's state in virtual DOM ( like in a loop). Adding a key will help track buttons correctly. 
no visual changes
> fix(Participant): Add key in order to force re-rendering

- package-lock.json
- package.json
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
- src/store/fileUploadStore.js
- src/store/fileUploadStore.spec.js
- src/test-setup.js
* Fix #11153 
* add `nextcloud/upload` library to perform file uploads to server
* attach uploadManager data to track common upload progress
* Split large `uploadFiles` action into 4 smaller manageable actions
* update NcProgressBar styles (so it won't affects scroller height and chat jumping)
https://github.com/nextcloud/spreed/assets/93392545/21a3ad37-cbe9-463e-bcdb-8e93fc620903
> fix(shares): use `nextcloud/upload` to track upload progress

- src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
- src/components/ConversationSettings/ConversationPermissionsSettings.vue
- src/components/ConversationSettings/DangerZone.vue
- src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
- src/components/PermissionsEditor/PermissionsEditor.vue
* Fix #11543
* Mount Advanced settings inside the Conversation settings to ensure it appears above
* Hard to reproduce initial issue, but this should exclude possibility of falling behind
* Also added a container prop for MessageTranslateDialog and PollVotersDetails
| ![image](https://github.com/nextcloud/spreed/assets/93392545/b30a4a81-c1a4-46ab-bd1e-3f72675b58a2)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/2ab558b6-88df-4ed2-9ec8-e01eed976179)        |
> fix(modal): mount nested modals inside global modals

- docs/bots.md
The text has a different order when describing how to calculate the HMAC then what is actually needed.
> Fix order of how the HMAC is calculated for bots

- src/components/CallView/shared/LocalAudioControlButton.vue
- src/components/CallView/shared/LocalVideoControlButton.vue
- src/components/CallView/shared/ViewerOverlayCallView.vue
- src/components/TopBar/CallButton.vue
- src/components/TopBar/ReactionMenu.vue
- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
* Fix #10566
| ![image](https://github.com/nextcloud/spreed/assets/84044328/7bb378c7-48b4-4ca8-b891-af4fb22da721)      | ![image](https://github.com/nextcloud/spreed/assets/84044328/81ec8e6d-0862-43cd-be75-1e13d3a34b53)     |
| ![image](https://github.com/nextcloud/spreed/assets/84044328/da23ac71-5084-418e-8a6c-ec279cdec5fb)|![image](https://github.com/nextcloud/spreed/assets/84044328/aa3521bc-f894-4944-b118-1f7154a634d6)|
> Feat(screensharing): switch focus to screenshare button instead of end call button

- src/components/LeftSidebar/ConversationsList/Conversation.spec.js
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
- src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
- src/components/LeftSidebar/ConversationsList/ConversationsSearchListVirtual.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/RoomSelector.spec.js
- src/components/RoomSelector.vue
- src/composables/useConversationInfo.js
* Refactor of RoomSelector
* Use ConversationsListVirtual and ConversationSearchResult for conversations list:
* improve accessibility, optimize rendering
* show last message if provided :warning: optionally, disabled atm
* resolve issue with immediate load of all avatars
* Test coverage
Test coverage:
> Improve room selector modal

- src/collections.js
- src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
- src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
- src/components/RoomSelector.spec.js
- src/components/RoomSelector.vue
- src/deck.js
- src/maps.js
* Fix #11604
* Provide a whole conversation object in emitted event (save extra request in plugins, don't rely on incomplete store in sidebar)
* Don't try to use Vue-Router to navigate from Files to Talk
* Reduce bundle size (RoomSelector is loaded dynamically)
| 🏚️ Before (323 kB) | 🏡 After (122 kB) :arrow_down_small: 62% |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/6cdf4e1a-38f8-4f4b-9130-3084a79dbc51)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/817b27d0-dee1-4eed-9166-8dabede5a07b)        |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/15f91f64-6aa1-45f2-8f20-a1de96c88d44) | ![image](https://github.com/nextcloud/spreed/assets/93392545/32fbcd59-0bb8-4a6d-acaf-1b071d9123c3) |
> chore(RoomSelector): reduce bundle size

- lib/AppInfo/Application.php
- lib/Search/UnifiedSearchFilterPlugin.php
- src/search.js
- webpack.config.js
* Fix https://github.com/nextcloud/server/issues/42914
Filter | Selector
--|--
[Screencast from 02-06-2024 11:27:48 AM.webm](https://github.com/nextcloud/server/assets/14317775/4ce91e6d-0d1b-4b94-8a90-b793c98900db)
> Feat: Plug-in talk specific filters for unified search

- lib/Settings/Admin/AdminSettings.php
- src/components/AdminSettings/Federation.vue
* Ref #11503 
* Ref #11279 
| ![image](https://github.com/nextcloud/spreed/assets/93392545/85c50f06-1fcd-47f4-8453-284727766e1d)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/f2678d10-0afc-4645-924d-90bdf1b89525)      |
---
> feat(federation): provide UI toggles in Admin settings for federation options

- src/App.vue
- src/components/LeftSidebar/InvitationHandler.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
- src/constants.js
- src/services/federationService.js
- src/stores/__tests__/federation.spec.js
- src/stores/federation.js
* Ref #11279 
* Add federation store, handle notifications with it
* Introduce dialog to list and manage invitations
Design review:
`Join conversations from remote Nextcloud servers`
> feat(Federation): list pending invitations

- src/PublicShareAuthSidebar.vue
- src/PublicShareSidebar.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
- src/components/PollViewer/PollViewer.vue
- src/components/PollViewer/PollVotersDetails.vue
- src/constants.js
- src/store/messagesStore.js
- src/store/pollStore.js
- src/views/FilesSidebarChatView.vue
- src/views/MainView.vue
* Fix #11372
* Poll component is splitted into two:
* `<Poll />` (card/button), to be shown as message part
* `<PollViewer />` (dialog), detached and moved up on the `<ChatView />` and `<CallView />` level
* With newly processed messages, dialog is triggered to be open when participant is in call
* Necessary evil: components code is optimized 
Toast message:
Unvoted poll highlight:
Talk Main, call view:
Files sidebar (same appearance as with open chat, public share sidebars):
https://github.com/nextcloud/spreed/assets/93392545/d18ebaa5-5a25-4324-aa6b-5cc43dea18df
> feat(Poll): live polls pop-ups during the call

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
* Fix regression from #11589
* Should handle public share sidebars and Talk Desktop correctly, when forwarding messages
> fix(MessageForwarder): better redirect handling

- lib/Search/UnifiedSearchFilterPlugin.php
> fix(search): Only register search filter when allowed to use Talk

- package-lock.json
- package.json
- src/components/LeftSidebar/LeftSidebar.spec.js
- src/components/MessagesList/MessagesGroup/Message/Message.spec.js
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.spec.js
- src/store/conversationsStore.spec.js
- src/stores/__tests__/reactions.spec.js
- src/test-setup.js
- src/utils/media/pipeline/MediaDevicesSource.spec.js
- src/utils/webrtc/RemoteVideoBlocker.spec.js
* Fix regression from 8.6.2
Changelog: https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.7.1
> chore(deps): Bump @nextcloud/vue from 8.7.0 to 8.7.1

- .github/workflows/integration-mysql.yml
- .github/workflows/phpunit-mysql.yml
Looks like the mysql container switches to `unhealthy` too fast (could be dependent on how busy the server is). Since github waits longer then our 25 seconds (5s interval * 5 retries), we should increase the retries.
Relevant github code is at https://github.com/actions/runner/blob/d5c7097d2c4f3f40a029124bbf1bc4c9994929f5/src/Runner.Worker/ContainerOperationProvider.cs#L411-L426
> fix(tests): Increase health-retries for mysql tests

- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
* Fix label at "Remove participant" button to explain behaviour for circles
| ![image](https://github.com/nextcloud/spreed/assets/93392545/be6714c7-28b1-4d11-9a2a-6df728b1e8fa)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/9d0704e1-2d7d-4362-b240-db2a24b06465)        |
> fix(Participant): adjust remove label for circles

- src/components/LeftSidebar/InvitationHandler.vue
* Minor fixes in styles and a11y:
* text as variable (aria-label, title)
* padding between icon - text
* icon as dummy conversation (for MDI, not server source)
| ![image](https://github.com/nextcloud/spreed/assets/93392545/272c98e6-8b79-49e6-b4f8-b0bc612031e5) | ![image](https://github.com/nextcloud/spreed/assets/93392545/3e63380e-a966-4a5b-94fb-92375add0f35) |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/412bd8d0-7bf2-4e05-a5ac-6956c02d4144)     | ![image](https://github.com/nextcloud/spreed/assets/93392545/7b69f414-c25b-4ca3-8050-3ae4dbd03b79)       |
> fix(InvitationHandler): adjust labels and icon appearance

- src/store/messagesStore.js
* Fix excessive store updates:
* When first time loading the chat, we already have the parent message up-to-date from the API
* `message_deleted`, `message_edited`, `reaction...` requested at the same time (not new) contains same parent message without changes, so we don't need to update it again and trigger sideEffect (messagesList re-render)
* deleteMessage, editMessage, addReaction API requests return parent to update it. When it comes again with message long polling, we also don't need to update it
> fix(messagesStore): don't update parent message in the store, if it hasn't been unchanged

- docs/events.md
- lib/Events/BotInstallEvent.php
- lib/Listener/BotListener.php
> feat(BotInstallEvent): Add "features" field

- src/App.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
* Follow-up to #11616 
* When check how to handle redirect link, rely on App context, not the window.location or routes
* Fine to keep as-is for stable releases, but ensure safer check process for future
> fix(MessageForwader): provide value to check where component is being used

- .eslintrc.js
- jest.config.js
- package-lock.json
- package.json
- src/components/AdminSettings/AllowedGroups.vue
- src/components/AdminSettings/Federation.vue
- src/components/AdminSettings/GeneralSettings.vue
- src/components/AdminSettings/MatterbridgeIntegration.vue
- src/components/AdminSettings/RecordingServers.vue
- src/components/AdminSettings/SignalingServers.vue
- src/components/AdminSettings/StunServers.vue
- src/components/AdminSettings/TurnServer.vue
- src/components/AdminSettings/TurnServers.vue
- src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
- src/components/TopBar/CallTime.vue
- src/components/VolumeIndicator/VolumeIndicator.vue
- src/env.d.ts
- src/types/vendor/@nextcloud/vue.d.ts
- src/types/vendor/l10n.d.ts
- src/types/vendor/vue-material-design-icons.d.ts
- src/utils/formattedTime.ts
- tsconfig.json
- webpack.common.config.js
* Reuse existing options from `@nextloud/webpack-vue-config` to compile Typescript files (standalone and Vue SFC scripts)
> build: provide Typescript support 

- lib/Federation/Proxy/TalkV1/UserConverter.php
* Fix undefined index when not all messages are edited
> fix(federation): Allow optional calls like with lastEditActor*

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
* Fix broken `getContext`, when `conversation.lastReadMessage === 0`
| ![image](https://github.com/nextcloud/spreed/assets/93392545/82f3dc32-e23e-45ce-9dce-8fc189c9f3fc)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/785d5cfe-3f1f-4d2e-b39e-1d4ccf85ba96)        |
> fix(messagesStore): allow defined falsy (0) values at state.firstKnown

- src/utils/webrtc/models/CallParticipantModel.js
- src/utils/webrtc/webrtc.js
This is necessary for support of Janus 1.x which will use the (random) id of the publisher that sent the message as label.
* Fix #10003
- Setup HPB with Janux 1.x without this PR
- Notice "talking" indication is not working in the browser
- Apply changes from this PR
- Reload and restart call
- "talking" indication is working again
@ivansss @SystemKeeper @mahibi FYI for the mobile apps.
> Ignore label of data channel when processing received messages.

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Chat/Parser/SystemMessage.php
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
- lib/Federation/Proxy/TalkV1/Notifier/MessageSentListener.php
- lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
- lib/Migration/Version19000Date20240227084313.php
- lib/Model/ProxyCacheMessages.php
- lib/Model/ProxyCacheMessagesMapper.php
- lib/Service/RoomFormatter.php
- tests/integration/run.sh
- tests/php/Federation/FederationTest.php
> feat(federation): Add a proxy cache for messages 

- css/icons.css
* Fix user mentions avatars in messages list
| ![image](https://github.com/nextcloud/spreed/assets/93392545/e4ef561d-c8bf-4bfe-bcc0-2847f13f3523)          | ![image](https://github.com/nextcloud/spreed/assets/93392545/d133197b-d89b-45e4-ae84-390c9976860b)        |
| ![image](https://github.com/nextcloud/spreed/assets/93392545/a1621da2-19be-4451-a636-5a7d201877aa) | ![image](https://github.com/nextcloud/spreed/assets/93392545/f3226ba3-204c-405e-821a-9d969ca3204b) |
> style: align mention icons with conversation icons

- src/components/MessagesList/MessagesList.vue
Old messages were fetched on every scroll event even though messages list weren't updated -> lost requests 
Create a flag to stop fetching when :
* We reach system messages conversation_created and history_cleared
* For chats that don't have such, we wait another request and compare if in both times the list didn't change then we confirm that the very beginning of the chat was reached ( this case applies to chats that have expiration messages, and history cleared after setting it)
No visual changes just spinner doesn't show up when you scroll up at the top.
> fix(MessagesList): Stop fetching when reaching the chat beginning

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
* Fix #4610 
* Refactor messages groups. It is now broken down by Date then by Author+time .
* Light refactoring for MessagesList, it was necessary 😶.
* Soft update messages list, keep the same object and modify only what was changed.
* Added sticky date separator.
> [!NOTE]  
> As the date is sticky and the loading spinner needs to be in absolute position, it will be overlapped. Therefore, the loading spinner should be in another position other than middle, change the loading visualisation, or removed ( like in other messengers where the date separator is sticky) 
**Issues found to fix:**
https://github.com/nextcloud/spreed/assets/84044328/0c848091-eae4-4162-bb2b-f6188fa7fa22
Follow-up
> Feat(MessagesList): Soft update messages list AND add sticky date separator.

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/TopBar/TopBar.vue
* Fix https://github.com/nextcloud/talk-desktop/issues/34
* Requires https://github.com/nextcloud/talk-desktop/pull/540
| ![image](https://github.com/nextcloud/spreed/assets/25978914/816deda8-a038-4861-919d-41b45a02db81) | ![image](https://github.com/nextcloud/spreed/assets/25978914/ece702a2-d070-42de-9215-2ee6370cf207)|
> fix(desktop): allow avatar menu on desktop

- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/services/conversationsService.js
- src/services/conversationsService.spec.js
- src/store/conversationsStore.js
- src/store/conversationsStore.spec.js
* Splitting work on conversations system:
* Template was optimised
* Error handling / displaying moved from services to the store
> fix(Conversation): optimize error handling

- docs/chat.md
- lib/Chat/ChatManager.php
- lib/Chat/Notifier.php
- lib/Controller/ChatController.php
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
- lib/Federation/Proxy/TalkV1/Notifier/MessageSentListener.php
- lib/Model/ProxyCacheMessages.php
- lib/ResponseDefinitions.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Service/RoomFormatter.php
- lib/Service/RoomService.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- tests/php/Controller/ChatControllerTest.php
> feat(federation): Federate unread information to proxies

- CHANGELOG.md
- feat(desktop): Allow using the avatar menu in the desktop client [#11679](https://github.com/nextcloud/spreed/issues/11679)
- fix(webrtc): Ignore label of data channel when processing received messages for Janus 1.x compatibility [#11667](https://github.com/nextcloud/spreed/issues/11667)
- fix(notifications): Fix notification action label length with utf8 languages [#11621](https://github.com/nextcloud/spreed/issues/11621)
- fix(chat): Fix forwarding messages from conversations in the right sidebar [#11606](https://github.com/nextcloud/spreed/issues/11606)
- fix(search): Hide search providers when not allowed to use Talk [#11623](https://github.com/nextcloud/spreed/issues/11623)
- fix(UI): Fix nesting of modals …
> chore(release): Add changelog for 16.0.11, 17.1.6 and 18.0.4

- package-lock.json
- package.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
Changelog
https://github.com/nextcloud-libraries/nextcloud-vue/pull/5328
> chore(deps): Bump @nextcloud/vue from 8.7.1 to 8.8.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- feat(desktop): Allow using the avatar menu in the desktop client [#11679](https://github.com/nextcloud/spreed/issues/11679)
- fix(webrtc): Ignore label of data channel when processing received messages for Janus 1.x compatibility [#11667](https://github.com/nextcloud/spreed/issues/11667)
- fix(notifications): Fix notification action label length with utf8 languages [#11621](https://github.com/nextcloud/spreed/issues/11621)
- fix(chat): Fix forwarding messages from conversations in the right sidebar [#11606](https://github.com/nextcloud/spreed/issues/11606)
- fix(search): Hide search providers when not allowed to use Talk [#11623](https://github.com/nextcloud/spreed/issues/11623)
- fix(UI): Fix nesting of modals …
> Release 18.0.4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(webrtc): Ignore label of data channel when processing received messages for Janus 1.x compatibility [#11668](https://github.com/nextcloud/spreed/issues/11668)
- fix(notifications): Fix notification action label length with utf8 languages [#11620](https://github.com/nextcloud/spreed/issues/11620)
- fix(chat): Fix forwarding messages from conversations in the right sidebar [#11609](https://github.com/nextcloud/spreed/issues/11609)
> Release 17.1.6

- jest.config.js
- src/components/ConversationSettings/EditableTextField.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/NewMessage/NewMessage.vue
- src/stores/chatExtras.js
- src/types/index.ts
- src/utils/__tests__/textParse.spec.js
- src/utils/textParse.ts
* Follow-up for #11664
* Requires https://github.com/nextcloud-libraries/nextcloud-vue/pull/5323 for narrow cases
* Allow to reverse-parse federated users and groups when:
* copy formatted message
* edit message
> fix(mentions): parse groups and federated user mentions

- lib/Service/RoomFormatter.php
> fix(federation): Convert actor info in lastMessage info for CPM messages

- src/components/LeftSidebar/InvitationHandler.vue
- src/stores/federation.js
☑️ Resolves
* Fix showing a loading spinner on all ivitations
Clicking "Accept -> Decline -> Accept"
[Screencast from 01.03.2024 14:36:47.webm](https://github.com/nextcloud/spreed/assets/93392545/ce8610e2-1d71-4249-bafe-046641340d59)
UPD: when rejecting, spinner is shown as well
> fix(federation): scope button disabling to invitation user interacted with

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- src/store/messagesStore.spec.js
* Fix regression from #11592 :smiling_face_with_tear: 
Let's assume we have messagesGroup `{6}` from one author with ids [6..10]
When fetching old messages, new group `{1}` is compiled for the same author, and covers messages [1..10]
As starting id is different, groups won't match and both remain in the list  
Follow-up: move grouping logic to composable and add test coverage?
> fix(MessagesList): soft update groups when fetching old messages

- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
* Ref #9725 
* `clearFocusTrap` from vue-library seems to break component renering on incorrect close
* unrelated to these changes, just a cleanup in `main`
> chore(screenshare): get rid of duplicated properties

- docs/capabilities.md
- docs/chat.md
- lib/Capabilities.php
- lib/Controller/ChatController.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/chat-2/unread-messages.feature
- tests/php/CapabilitiesTest.php
This is required for federated conversations where the clients might not know the hosted message ID but only the proxy ID instead
> feat(chat): Allow marking chat as read without a last message ID

- src/components/MediaSettings/MediaDevicesSelector.vue
- src/components/MediaSettings/MediaDevicesSpeakerTest.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/SettingsDialog/MediaDevicesPreview.vue
- src/components/SettingsDialog/SettingsDialog.vue
- src/store/soundsStore.js
* Fix #1181
| ![image](https://github.com/nextcloud/spreed/assets/84044328/3ed1337c-01a0-4eb7-9508-5d8ee1afad40)  | ![image](https://github.com/nextcloud/spreed/assets/93392545/1e97e7cf-5f02-4cdf-a396-f9d5b3379ed9)     |
Screencast :
[audio-test.webm](https://github.com/nextcloud/spreed/assets/93392545/9cee50aa-9023-4d64-ab7a-ef206683e8d2)
> Feat(MediaSettings): Add audio test

- lib/Chat/ChatManager.php
- lib/Chat/SystemMessage/Listener.php
- lib/Exceptions/MessagingNotAllowedException.php
- lib/Flow/Operation.php
- tests/php/Chat/ChatManagerTest.php
* Fix the Sermo/Tale issue we are facing
> fix(federation): Don't post any messages into proxy conversations

- appinfo/info.xml
- docs/events.md
- lib/Chat/ChatManager.php
- lib/Chat/MessageParser.php
- lib/Chat/Parser/SystemMessage.php
- lib/Chat/Parser/UserMention.php
- lib/Chat/SystemMessage/Listener.php
- lib/Controller/ChatController.php
- lib/Events/AMessageSentEvent.php
- lib/Events/ASystemMessageSentEvent.php
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/Proxy/TalkV1/Notifier/MessageSentListener.php
- lib/Federation/Proxy/TalkV1/UserConverter.php
- lib/Manager.php
- lib/Migration/Version19000Date20240305115243.php
- lib/Model/Message.php
- lib/Model/ProxyCacheMessage.php
- lib/Model/ProxyCacheMessageMapper.php
- lib/Notification/FederationChatNotifier.php
- lib/Notification/Notifier.php
- lib/Service/RoomFormatter.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
- tests/php/Federation/FederationTest.php
- tests/php/Notification/NotifierTest.php
> feat(federation): Implement notifications for mentions, reply and full

- src/store/conversationsStore.js
* There could be a race condition between room and notification fetch
* If room comes first, unread marker is already updated there, no need to do it again
* For federated rooms, lastMessage.id is not presented, so checked by timestamp
[Screencast from 07.03.2024 12:25:29.webm](https://github.com/nextcloud/spreed/assets/93392545/8bd3a0f8-890a-4d3a-bca5-d91992e51fb8)
[Screencast from 07.03.2024 13:13:34.webm](https://github.com/nextcloud/spreed/assets/93392545/64ca819d-d496-43a4-a51a-5ffff9fde14d)
> fix(conversation): skip unread marker increasing from notification

- appinfo/routes/routesAvatarController.php
- docs/avatar.md
- lib/Controller/AvatarController.php
- lib/Federation/Proxy/TalkV1/Controller/AvatarController.php
- lib/Federation/Proxy/TalkV1/ProxyRequest.php
- lib/Service/AvatarService.php
- openapi-federation.json
- openapi-full.json
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
> feat(federation): Add endpoint to get the proxied avatar of other users

- src/components/LeftSidebar/InvitationHandler.vue
- regression from #11700 
- don't mutate store
- check for empty object instead of array
> fix(InvitationHandler): minor fixes

- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- assign `viewId` on Options API initialising: chatIdentifier is no longer updated at `mounted()` - no cancelled requests
-  don't check system messages for parents:
-  weird, but for federated conversations system conversations `getContext` at the moment response is processed, doesn't contain message parent - false check - system message is rendered as-is
-- | --
> fix(messages): minor render enhancements

- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
> fix(federation): Correctly convert message on deleting

- lib/Model/Attendee.php
- lib/Model/Invitation.php
- lib/ResponseDefinitions.php
- lib/Service/RoomFormatter.php
- openapi-federation.json
- openapi-full.json
- src/stores/federation.js
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
> fix(federation): Don't expose the accessToken anymore to the frontend/clients

- composer.lock
- lib/AppInfo/Application.php
- lib/Team/TalkTeamResourceProvider.php
Implement a team resource provider for talk that lists team resources in the related resource panel and in the team dashboard in contacts.
There are two bugs with rendering the image I came across unfortunately but need a fix in contacts and the vue lib:
- https://github.com/nextcloud/contacts/pull/3844
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5364
Screenshot within the team dashboard after the above mentioned fix:
> feat: Implement team resource provider

- lib/Controller/RoomController.php
- lib/Federation/Proxy/TalkV1/Controller/RoomController.php
- Actually No-Op because the host checks and only returns status to "users" and federated users are not authed this way
> fix(federation): Don't request user status from remote instances

- lib/Controller/FederationController.php
- lib/Controller/RoomController.php
- tests/integration/features/federation/invite.feature
> fix(federation): Allow to remove self from a federated conversation

- src/components/MediaSettings/MediaSettings.vue
- src/stores/settings.js
- src/utils/webrtc/index.js
* Fix empty entries like `'virtualBackgroundType_'` in local storage without defined key
* `this.get('token')` sometime returns nothing, as webrtc isn't always initialising it
* Prevent generating empty entries again by providing a token
* Add init function to cleanup them while initialising
* reset virtualBackground at media preview, if none is set for conversation
🏡 After
[reset-virtual-bg.webm](https://github.com/nextcloud/spreed/assets/93392545/00b4d070-e0e4-4339-955c-9396aa53945a)
> fix(BrowserStorage): don't generate empty entries in BrowserStorage

- lib/Share/RoomShareProvider.php
Improves the performance of applying per-user changes to room shares.
I wasn't sure how to handle `getSharesByIds` so I've just disabled the optimization for that code path for now.
See also: https://github.com/nextcloud/server/pull/44004
> perf: improve performance of resolving recipient shares

- package-lock.json
- package.json
Release: 				https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.9.0
https://github.com/nextcloud-libraries/nextcloud-vue/releases/tag/v8.9.1
-- | --
> chore(deps): bump @nextcloud/vue from 8.8.1 to 8.9.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Messages can now be edited by logged-in authors and moderators for 6 hours [#1836](https://github.com/nextcloud/spreed/issues/1836)
- Added a "In conversation" search filter [#11456](https://github.com/nextcloud/spreed/issues/11456)
- Save unsent messages in browser storage so they survive a page reload or browser restart [#3055](https://github.com/nextcloud/spreed/issues/3055)
- Allow to accept individual users when the lobby is enabled [#8601](https://github.com/nextcloud/spreed/issues/8601)
- Flavored Markdown in messages [#10066](https://github.com/nextcloud/spreed/issues/10066)
- Allow to see all reactions [#11508](https://github.com/nextcloud/spreed/issues/11508)
- Preview: Federated chatting [#11231](https://github.com/nextcloud/spreed/issues/11231)
- Update …
> chore(release): Add changelog 19.0.0-beta.1

- src/components/CallView/CallView.vue
- src/components/CallView/shared/VideoBottomBar.vue
* Fix inactive button "Show screen"
[Screencast from 06.03.2024 09:32:05.webm](https://github.com/nextcloud/spreed/assets/93392545/890f8957-8e54-42ac-83f0-976e3659dc69)
> fix(CallView): enforce switching to Speaker view then select screenshares

- CHANGELOG.md
- fix(call): Fix missing screenshare button after stopping a screenshare [#11721](https://github.com/nextcloud/spreed/issues/11721)
- fix(call): Correctly focus the screenshare after selecting in the grid view [#11755](https://github.com/nextcloud/spreed/issues/11755)
- fix(chat): Fix jumping unread counter when entering a conversation after receiving a notification [#11736](https://github.com/nextcloud/spreed/issues/11736)
> chore(release): Add changelog for 18.0.5

- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-mysql.yml
- .github/workflows/phpunit-oci.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/phpunit-sqlite.yml
- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(call): Fix missing screenshare button after stopping a screenshare [#11721](https://github.com/nextcloud/spreed/issues/11721)
- fix(call): Correctly focus the screenshare after selecting in the grid view [#11755](https://github.com/nextcloud/spreed/issues/11755)
- fix(chat): Fix jumping unread counter when entering a conversation after receiving a notification [#11736](https://github.com/nextcloud/spreed/issues/11736)
> chore(release): Bump version to 18.0.5

- lib/Federation/Proxy/TalkV1/UserConverter.php
- lib/Notification/FederationChatNotifier.php
> fix(federation): Fix conversation avatar for `@all`

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
- src/components/NewMessage/NewMessage.vue
- src/components/TopBar/CallButton.vue
* Fix #10085
* Fix #8336
* Fix #11591
* Based on #11718
-- | --
> feat(BrowserStorage): remember silent call / message per conversation

- lib/Controller/ReactionController.php
- lib/Federation/Proxy/TalkV1/Controller/AvatarController.php
- lib/Federation/Proxy/TalkV1/Controller/ReactionController.php
- lib/Federation/Proxy/TalkV1/UserConverter.php
- lib/Room.php
> feat(federation): Implement reactions

- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
* Follow up to https://github.com/nextcloud/spreed/pull/11772
> fix(federation): Add integration tests for reactions

- lib/Notification/FederationChatNotifier.php
```
Undefined array key \"replyToActorType\" at /var/www/html/apps/spreed/lib/Notification/FederationChatNotifier.php#84
```
> fix(federation): Undefined array key "replyToActorType"

- package-lock.json
- package.json
> chore(deps): bump nextcloud/vue from 8.9.1 to 8.10.0

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/NewMessage/NewMessage.vue
- src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
- src/components/RightSidebar/Participants/Participant.spec.js
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantPermissionsEditor.spec.js
- src/components/RightSidebar/Participants/ParticipantPermissionsEditor.vue
- src/components/RightSidebar/Participants/ParticipantsList.vue
- src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
- src/components/RightSidebar/Participants/ParticipantsSearchResults.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
* Feat: mark federated users in MessagesList and ParticipantList:
* web icon at the user_status place, where applicable
* server address in parenthesis next to user name
* Fix regression from #11664 :
* don't replace id with mentionId if not available
* Follow-up to user proxy avatars: 
* use NcAvatarWrapper in ReactionsList 
-- | --
> feat(Participants): mark federated users in MessagesList and ParticipantList

- src/components/MessagesList/MessagesList.vue
- Removal update was missing for date groups level. So clear history didn't remove past groups by date.
> fix(MessagesList): remove deleted groups

- lib/Controller/AEnvironmentAwareController.php
- lib/Controller/AvatarController.php
- lib/Controller/FederationController.php
- lib/Federation/Proxy/TalkV1/Controller/AvatarController.php
- lib/Middleware/Attribute/AllowWithoutParticipantWhenPendingInvitation.php
- lib/Middleware/InjectionMiddleware.php
- lib/Model/Invitation.php
- lib/Model/InvitationMapper.php
- lib/ResponseDefinitions.php
- openapi-federation.json
- openapi-full.json
- src/components/ConversationIcon.vue
- src/components/LeftSidebar/InvitationHandler.vue
- src/stores/__tests__/federation.spec.js
- src/stores/federation.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
> fix(federation): Expose local token with the invite so UI can render proxy avatars

- lib/Service/ParticipantService.php
- Invite a user
- As recipient accept the invite
- As recipient leave the conversation
- :eyes: See a `'Share not found'` 404 message being logged in the nextcloud.log
> fix(federation): Don't notify ourselves when we leave

- lib/Controller/FederationController.php
- lib/Federation/FederationManager.php
- lib/Middleware/InjectionMiddleware.php
- openapi-federation.json
- openapi-full.json
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/invite.feature
- Integration test for https://github.com/nextcloud/spreed/pull/11777
> test(federation): Add test for avatar federation

- lib/AppInfo/Application.php
- lib/Federation/Proxy/TalkV1/Notifier/BeforeRoomDeletedListener.php
* Create a room
* Add a federated user
* As FU accept the invite
* As host delete the room
* Before: The room and invite is still present in the DB
* After: Now the invite and participant are cleaned up immediately (and the room after the next cron run)
> fix(federation): Inform federated servers/users when deleting a conversation

- src/components/NewMessage/NewMessage.vue
- src/components/RightSidebar/RightSidebar.vue
- src/components/TopBar/CallButton.vue
- src/services/conversationsService.js
- src/services/conversationsService.spec.js
* Hide following unavailable features for Federation V1:
* Joining/starting the call;
* Posting attachments:
* Polls
* Files
* Voice messages
* RightSidebar tabs:
* Breakout rooms
* Shared items
> fix(federation): hide unsupported features from web interface

- src/components/CallView/shared/EmptyCallView.vue
- src/components/ConversationSettings/LinkShareSettings.vue
- src/components/LeftSidebar/ConversationsList/Conversation.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/SipSettings.vue
- src/components/TopBar/TopBarMenu.vue
- src/stores/sharedItems.js
- src/types/index.ts
- src/utils/__tests__/formattedTime.spec.js
- src/utils/__tests__/getItemTypeFromMessage.spec.js
- src/utils/__tests__/handleUrl.spec.js
- src/utils/__tests__/readableNumber.spec.js
- src/utils/getItemTypeFromMessage.ts
- src/utils/handleUrl.ts
- src/utils/readableNumber.ts
* Add typings
* Increase test coverage
> chore(typescript): migrate utils to TS

- appinfo/info.xml
- lib/Federation/BackendNotifier.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/FederationManager.php
- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
- lib/Federation/Proxy/TalkV1/Notifier/MessageSentListener.php
- lib/Manager.php
- lib/Migration/Version19000Date20240313134926.php
- lib/Model/Attendee.php
- lib/Model/AttendeeMapper.php
- lib/Model/SelectHelper.php
- lib/Notification/FederationChatNotifier.php
- lib/Room.php
- lib/Service/ParticipantService.php
- lib/Service/RoomFormatter.php
- lib/Service/RoomService.php
- tests/integration/features/federation/chat.feature
- tests/integration/features/federation/invite.feature
- tests/php/Chat/ChatManagerTest.php
- tests/php/Federation/FederationTest.php
- tests/php/Service/RoomServiceTest.php
> fix(federation): Send display name and last read message with federation

- package-lock.json
- package.json
- src/components/CallView/CallView.vue
- src/components/CallView/shared/VideoVue.vue
* Fix #10732
https://github.com/nextcloud/spreed/assets/84044328/808179f4-d4ce-4861-8e27-134126fd265c
---
> feat(PresenterOverlay): make the overlay draggable.

- src/components/RightSidebar/Participants/Participant.vue
- src/store/participantsStore.js
- src/utils/webrtc/SpeakingStatusHandler.js
* Fix #11501
* Data in the store are correct and accessible by token + attendeeId
* Because of virtual scroller in the participant list, interval update in the component can't be used, as it attached to the Vue component object, not the participant data
* Moved interval update to the store, so each second we update a value there
* Component rely only on store update and re-rendered once per second (as before), but with correct value
-- | --
Reproducible | Non-reproducible
> fix(participants): move interval update of talking time counter to the store

- lib/Federation/CloudFederationProviderTalk.php
- lib/Room.php
> fix(federation): Remove duplicate method isFederatedRemoteRoom() vs isFederatedConversation()

- lib/ResponseDefinitions.php
- openapi-backend-sipbridge.json
- openapi-federation.json
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-backend-sipbridge.ts
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> fix(openapi): Provide better message parameter definitions

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Preview: Federated chatting - Implemented reactions [#11772](https://github.com/nextcloud/spreed/issues/11772)
- Preview: Federated chatting - Implemented polls [#11653](https://github.com/nextcloud/spreed/issues/11653)
- Mark federated users as such in the participant list [#11771](https://github.com/nextcloud/spreed/issues/11771)
- Fix retry behaviour when the host or federated instance was not reachable [#11780](https://github.com/nextcloud/spreed/issues/11780)
- Fix UI spaming chat requests when memory cache was cleared [#11788](https://github.com/nextcloud/spreed/issues/11788)
- Fix showing federated users as options when providing a cloudId [#11794](https://github.com/nextcloud/spreed/issues/11794)
- Fix read marker and unread …
> Release 19.0.0 beta.2

- src/components/NewMessage/NewMessage.vue
* Fix #11803 
* compare value from store with parsed value to avoid issues with special symbols
* revert removed line from 9efb614ac0ec6346176dfc75384a3f1b42f6621b
* could fill the input again after posting a message, if was sent before debounced update
* don't check for autocomplete open
* component is capturing Esc event by itself after nextcloud/vue@8.10.0
> fix(NewMessage): fix broken caret

- src/components/RoomSelector.vue
- src/views/AdminSettings.vue
- src/views/FlowPostToConversation.vue
* Show admin options in  production, if capability is there
* Hide federated rooms from:
* MessageForwarder, Deck plugin, Maps plugin (where RoomSelector is used)
* Flow plugin
Talk | Plugins | Flow
-- | -- | --
> fix(federation): show Federation section in AdminSettings, hide federated conversations from plugins

- lib/Federation/CloudFederationProviderTalk.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
Currently all working as expected in tests, but lets see what we monitor
> fix(federation): Log and test last read message

- lib/Notification/FederationChatNotifier.php
- tests/integration/features/federation/chat.feature
* Reply to own message
* Mention yourself
> fix(federation): Don't trigger notifications for own messages

- docs/chat.md
- lib/Controller/ChatController.php
- lib/Manager.php
- lib/Model/ReminderMapper.php
- lib/Notification/Notifier.php
- lib/Service/ProxyCacheMessageService.php
- lib/Service/ReminderService.php
- lib/Service/RoomFormatter.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
- tests/integration/features/federation/chat.feature
- tests/integration/features/federation/reminder.feature
- tests/php/Controller/ChatControllerTest.php
> feat(federation): Implement reminders for federated messages

- lib/BackgroundJob/ExpireChatMessages.php
- lib/Model/ProxyCacheMessageMapper.php
- lib/Service/ProxyCacheMessageService.php
> fix(federation): Expire messages in the PCM cache

- package-lock.json
- package.json
* Fix:
* font-weight in conversations
* user status icon in NcAvatar menu
* flickering widgets in chat
-- | --
> chore(deps): bump nextcloud/vue from 8.10.0 to 8.11.0

- package-lock.json
- package.json
Backport of #11818
Hopefully last bump for stable28, fix:
- focus trap errors
- reference widgets flickering
- capture tribute closing
- require leading space for tribute
- extra spaces when mentioning
- status icons in Safari
- status icons in NcAvatar menu
> chore(deps): bump nextcloud/vue from 8.8.1 to 8.11.0

- lib/Chat/ChatManager.php
- lib/Federation/CloudFederationProviderTalk.php
- lib/Federation/Proxy/TalkV1/Notifier/MessageSentListener.php
- lib/Model/ProxyCacheMessage.php
- lib/Notification/FederationChatNotifier.php
- lib/Service/ProxyCacheMessageService.php
- lib/Service/RoomFormatter.php
- tests/integration/features/federation/chat.feature
- tests/php/Federation/FederationTest.php
> fix(federation): Fix updating PCM after editing or deleting a message

- src/components/MessagesList/MessagesList.vue
* Relative dates are better shown until a week ago (as it used to be).
-- | --
> Fix(MessagesList): Limit relative date up to a week.

- lib/Controller/AvatarController.php
> fix(avatars): Reduce cache time in fallback cases (remote was offline)

- src/components/NewMessage/NewMessage.vue
Main chat input stays empty when upload editor is open.
-- | --
> Fix(NewMessage): Clear main message input when upload editor is open

- src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
> Fix reaction buttons

- lib/Controller/ChatController.php
- lib/Controller/RoomController.php
- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
- lib/Service/ParticipantService.php
- openapi-full.json
- openapi.json
- src/types/openapi/openapi-full.ts
- src/types/openapi/openapi.ts
> fix(federation): Disable read and typing indicators for federated users

- lib/Model/ProxyCacheMessageMapper.php
- tests/php/Service/ProxyCacheMessageServiceTest.php
> fix(federation): Fix expiration of cached messages

- css/icons.css
- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/ConversationIcon.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewMessage/NewMessage.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
* Fix inconsistent avatars in modals
* Use `modal-mask` class from Vue library instead of `talk-modal`
* Update classes for NcRichContenteditable (`mention-bubble` and `autocomplete-result`)
* Fix dark mode for AvatarWrapper
🏚️ Before | ☀️ Light theme | 🌑 Dark Theme
-- | -- | --
> fix(avatars): show Talk-defined avatar thumbnails in modals

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Preview: Federated chatting - Implemented reminders [#11814](https://github.com/nextcloud/spreed/issues/11814)
- Provide better OpenAPI data for message parameters [#11807](https://github.com/nextcloud/spreed/issues/11807)
- Fix editing and deleting not reflected correctly in left sidebar for federated conversations [#11839](https://github.com/nextcloud/spreed/issues/11839)
- Fix missing expiration of cached messages in federated conversations [#11816](https://github.com/nextcloud/spreed/issues/11816)
- Make conversation avatars dark mode again [#11840](https://github.com/nextcloud/spreed/issues/11840)
- Reduce the cache time of avatars when the remote was not reachable [#11842](https://github.com/nextcloud/spreed/issues/11842)
- Don't …
> Release 19.0.0 beta.3

- lib/Controller/ChatController.php
- lib/Federation/Proxy/TalkV1/Controller/ChatController.php
- lib/Notification/Listener.php
- tests/integration/features/federation/chat.feature
- tests/php/Controller/ChatControllerTest.php
Following the pattern of normal chats we are marking read in `getMessageContext() > waitForNewMessages()` and `receiveMessages() > waitForNewMessages()`
Fix #11121
> fix(federation): Mark notifications for federated rooms read similarly

- src/services/conversationsService.js
- src/services/conversationsService.spec.js
- allow to invite federated user when creating a conversation
- conversation creation flow seems to work without errors (with stable network)
Avatar is only shown, if user is joined to the room, which can proxy this exact avatar from remote server
- LeftSidebar search also returns federated user as an option, but doesn't show it (something for later - private federeated conversation?)
> fix(conversation): allow to invite federated user when creating a conversation

- src/components/AvatarWrapper/AvatarWrapper.vue
- src/components/ConversationSettings/BasicInfo.vue
- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewConversationDialog/NewConversationSetupPage.vue
- src/components/RightSidebar/SharedItems/SharedItemsTab.vue
- src/constants.js
- src/services/conversationsService.js
* Fix #11433 
* Fix #11659
* Fix big image fallback when creating new conversation with federated
-- | --
> fix(SharedItems): fetch after page reload + fix(Conversation): set warnings on max length

- src/router/router.js
* Works in a pair with https://github.com/nextcloud/talk-desktop/pull/567
* In path welcome page `/apps/spreed` had alias '/' for desktop. 
* It allowed to initially open welcome page on Talk Desktop
* Instead, it should be fixed on Talk Desktop side
* Having this `/` router is a problem for determining if a link is a Talk links, for example, `https://nextcloud.ltd/apps/spreed` is a Talk link while `https://nextcloud.ltd/` is not. `/` is not a valid Talk path.
> fix(desktop): do not change welcome page path for desktop

- src/components/RightSidebar/Participants/Participant.vue
* Requires `federation-v1` capability
🏚️ Remote | 🏡 Host
-- | --
> fix(Participant): show all federated users in remote conversations as online

- package-lock.json
- package.json
- src/components/LeftSidebar/LeftSidebar.vue
* NcListItem native font-weight is 500
* LeftSidebar animation is smooth
* autocomplete avatars in dark mode are correct
> chore(deps): bump nextcloud/vue from 8.11.0 to 8.11.1

- appinfo/routes/routesAvatarController.php
- lib/Controller/AvatarController.php
- openapi-federation.json
- openapi-full.json
- src/types/openapi/openapi-federation.ts
- src/types/openapi/openapi-full.ts
> feat(avatar): Allow logged-in users to proxy avatars without a token

- src/components/ChatView.vue
- src/components/NewMessage/NewMessage.vue
* Fix #11874 (for federated users, locals still can post files)
> fix(chat): disable drag&drop and Ctrl+V if files upload is not allowed

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Adjust read handling in received federated conversations to match normal conversations [#11861](https://github.com/nextcloud/spreed/issues/11861)
- Allow inviting federated users while creating a conversation [#11862](https://github.com/nextcloud/spreed/issues/11862)
- Fix duplicate messages when sharing recordings or transcripts [#11863](https://github.com/nextcloud/spreed/issues/11863)
- Prevent manipulating receiving federated conversations via OCC [#11855](https://github.com/nextcloud/spreed/issues/11855)
> Release 19.0.0 beta.4

- src/components/ConversationSettings/ConversationSettingsDialog.vue
- src/components/ConversationSettings/NotificationsSettings.vue
> fix(federation): hide call-related settings for federated conversations

- tests/integration/features/bootstrap/FeatureContext.php
> fix(tests): Allow negative expiration time in tests

- README.md
Fix #10686 
When testing federated conversations locally, some additional steps might be needed,
to improve the behaviour and allowing the servers to talk to each others:
1. Allow self-signed certificates
```shell
occ config:system:set sharing.federation.allowSelfSignedCertificates --value true --type bool
occ security:certificates:import /path/to/the/nextcloud.crt
occ security:certificates
```
2. Allow local servers to be remote servers
```shell
occ config:system:set allow_local_remote_servers --value true --type bool
```
Additionally you can enable debug mode that will list local users as federated users options
allowing you to federate with accounts on the same instance. Federation will still work
and use the full federation experience and opposed to the federated files sharing **not** …
> docs(federation): Document how to do local federation

- src/components/ChatView.vue
- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
- src/components/MessagesList/MessagesList.vue
- src/components/NewMessage/NewMessage.vue
- src/store/fileUploadStore.js
* Refactor scrolling to bottom logic that is used when:
- Reaction added to the last messages 
- Polling new messages
- Uploading file
- Scroll to bottom button
🚧 TODO follow-up : 
* Adjust placeholder height to meet `clientHeight` (it scrolls when joining a conversation) !
> chore: refactor scroll to bottom logic

- lib/Chat/ChatManager.php
- lib/Flow/Operation.php
- lib/Notification/Notifier.php
> fix(flow): Fix flow notifications in note-to-self and on own actions

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.vue
- src/composables/useCombinedSystemMessage.js
* Ref #11484 
* message group should be collapsed, as soon as unread marker is moved from it
* only manually open groups will be opened after list re-render, rest will follow the rules
Rest
* group messages ilke `Administrator removed A, B and 3 other participants` (copy-paster from 'user-added')
* cycle through only existing group keys when soft updating
* we could remove group just before in previous cycle
Before | After
--|--
> fix(MessagesSystemGroup): collapse `actor removed` messages, collapse previously open groups with unread marker

- lib/Chat/SystemMessage/Listener.php
- lib/Controller/PageController.php
- lib/Middleware/InjectionMiddleware.php
- tests/php/Chat/SystemMessage/ListenerTest.php
```
│[debug] 2024-03-25T18:54:20.000 spreed-bfp       User "admin" throttled for accessing "fgmhy59r423"  
│[debug] 2024-03-25T18:56:51.000 spreed-bfp       users "admin" added to room "5idt5cep"                                                                                 │
│[debug] 2024-03-25T18:56:58.000 spreed-bfp       groups "group-deed-4572-9589-b8c168fcf4fe" added to room "5idt5cep"                                                    │
│[debug] 2024-03-25T18:56:58.000 spreed-bfp       users "3928cdba-f2d7-4c0a-bac4-9a59a0f49b8b" added to room "5idt5cep"                                                  │
│[debug] 2024-03-25T18:56:58.000 spreed-bfp       User "3928cdba-f2d7-4c0a-bac4-9a59a0f49b8b" added to room "5idt5cep"                                                   │
│[debug] …
```
> fix(bruteforce): Log assumed bruteforce relevant actions

- src/services/participantsService.js
For testing add:
```php
$response->addHeader('X-Nextcloud-Bruteforce-Throttled', '25000ms');
```
Before
https://github.com/nextcloud/server/blob/25309bcb45232bf30fe719bac1776f0136f7cd7a/lib/private/AppFramework/Middleware/Security/BruteForceMiddleware.php#L136
> feat(UX): Show a warning when bruteforce protection is throttling

- lib/Service/BotService.php
> fix(bots): Remove FIXMEs as we just accept the current state

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Fix handling of cloud ID when provided in wrong casing [#11922](https://github.com/nextcloud/spreed/issues/11922)
- Fix flow notifications triggered by own actions and in note-to-self conversations [#11918](https://github.com/nextcloud/spreed/issues/11918)
- Hide call related user settings in federated conversations [#11892](https://github.com/nextcloud/spreed/issues/11892)
> Releasing 19.0.0 beta.5

- src/components/NewMessage/NewMessage.vue
- src/components/Quote.vue
* Fix broken styles for Quote components
-- | --
> fix(Quote): restrict overflow content for quotes / replies

- src/components/CallView/CallView.vue
- src/components/CallView/shared/PresenterOverlay.vue
- src/components/CallView/shared/VideoVue.vue
* Fix #11869
* Moved into a new component
* Added cursor style
🏡 After
https://github.com/nextcloud/spreed/assets/84044328/36696d6e-4a49-4aff-a13e-e46e0b58d01a
> Fix(PresenterOverlay): Add grabbing cursor

- src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
- src/components/LeftSidebar/LeftSidebar.vue
- src/components/NewConversationDialog/NewConversationContactsPage.vue
- src/components/RightSidebar/Participants/Participant.vue
- src/components/RightSidebar/Participants/ParticipantsTab.vue
- src/composables/useArrowNavigation.js
* Fix #11632
* Move "Create new conversation" under current conversations
* Add sublines to indicate that user is starting a new conversation from search results
* Decrease margin between sections
* Show user status for known users in search results
* Add fast option to create group conversation with federated user from search results
* API provides entrypoint, would be a good base for follow-up 1-1 federated rooms
🏚️ Before | 🏡 After | 🏚️ Before | 🏡 After
-- | -- | -- | --
Not available | ![image](https://github.com/nextcloud/spreed/assets/93392545/2ea1e75c-8c10-48cd-ae07-d631a1af33ac) | - | -
> feat(LeftSidebar): rearrange conversation fast creating options

- src/components/ConversationSettings/ConversationAvatarEditor.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/MediaSettings/VideoBackgroundEditor.vue
- src/components/SettingsDialog/SettingsDialog.vue
* Fix cases when FilePicker is shown behind the modal
hard to reproduce
> fix(FilePicker): provide correct container for FilePicker

- lib/Service/RoomFormatter.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
The PCM cache is already converted, so converting again on rendering, would create a conflict if there is a user1 from host and proxy in the room.
> fix(federation): Don't double convert the actor info in the last message

- src/components/NewConversationDialog/NewConversationDialog.vue
- src/components/NewMessage/NewMessagePollEditor.vue
- src/components/NewMessage/NewMessageUploadEditor.vue
* Fix accidental closing by clicking outside of modals, which require a decent investment of time to fill
> fix(NcModal): don't close modals if they were filled

- src/components/MessagesList/MessagesGroup/Message/Message.vue
- src/components/MessagesList/MessagesGroup/MessagesGroup.vue
- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- src/components/MessagesList/MessagesList.spec.js
- src/components/MessagesList/MessagesList.vue
- src/store/messagesStore.js
- Restrict Placeholder to not to create scrolling for the chat when it is there
- Message Highlight is event-driven now instead of ref-oriented, saves some computations
- Adjust fallback visible message to include only actual visible messages (e.g: not reaction system messages)
Follow-up:
- Removed extra steps in scrolling and improved remaining.
> chore(MessagesList): Refactor scrolling

- src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
> fix(MessageButtonsBar): revert to main selector

- src/store/conversationsStore.js
- src/store/messagesStore.js
* don't show system message 'message_edited' in sidebar
* update last message if was edited
🏡 After
[Screencast from 28.03.2024 10:06:04.webm](https://github.com/nextcloud/spreed/assets/93392545/b16f078e-83eb-4a5c-8974-f8089b02e315)
> fix(editing): don't show system message 'message_edited' in sidebar

- src/components/NewMessage/NewMessage.vue
> fix(NewMessage): parse edited message before sending

- CHANGELOG.md
- Add a header to the room list indicating pending invites [#11944](https://github.com/nextcloud/spreed/issues/11944)
- Don't close the modal on outside click when the user started to fill them [#11942](https://github.com/nextcloud/spreed/issues/11942)
- Fix user confusion when federating with a user that has the same user ID [#11941](https://github.com/nextcloud/spreed/issues/11941)
- Don't transfer ownership federated memberships as it doesn't work [#11950](https://github.com/nextcloud/spreed/issues/11950)
- Provide the correct container for the file picker [#11939](https://github.com/nextcloud/spreed/issues/11939)
- Adjust the cursor to be a grabbing hand when dragging the presenter view …
> chore(release): Changelog for 19.0.0-rc.1

- lib/Chat/Parser/SystemMessage.php
According to https://github.com/nextcloud/server/blob/9aa7225ed3e78c2e418c983e65bdc1f1787b9940/lib/public/RichObjectStrings/Definitions.php#L227 only `link` exists and `url` doesn't.
> fix(SystemMessage): Use link parameter for Circle URL in rich object parameters

- lib/Chat/MessageParser.php
- lib/Model/ProxyCacheMessage.php
- tests/integration/features/bootstrap/FeatureContext.php
- tests/integration/features/federation/chat.feature
> fix(federation): Fix empty strings being null in Oracle

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(FilePicker): Provide correct container for FilePicker [#11940](https://github.com/nextcloud/spreed/issues/11940)
- fix(flow): Fix flow notifications in note-to-self and on own actions [#11919](https://github.com/nextcloud/spreed/issues/11919)
- fix(call): Keep the talk time information when changing active tab [#11797](https://github.com/nextcloud/spreed/issues/11797)
> Release 18.0.6

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- fix(conversation): skip unread marker increasing from notification [#11735](https://github.com/nextcloud/spreed/issues/11735)
- fix(modal): mount nested modals inside global modals [#11891](https://github.com/nextcloud/spreed/issues/11891)
> Release 17.1.7

- CHANGELOG.md
- fix(FilePicker): Provide correct container for FilePicker [#11940](https://github.com/nextcloud/spreed/issues/11940)
- fix(flow): Fix flow notifications in note-to-self and on own actions [#11919](https://github.com/nextcloud/spreed/issues/11919)
- fix(call): Keep the talk time information when changing active tab [#11797](https://github.com/nextcloud/spreed/issues/11797)
- fix(conversation): skip unread marker increasing from notification [#11735](https://github.com/nextcloud/spreed/issues/11735)
- fix(modal): mount nested modals inside global modals [#11891](https://github.com/nextcloud/spreed/issues/11891)
> chore(release): Add changelog for 17.1.7 and 18.0.6

- src/components/TopBar/TopBarMediaControls.vue
- src/utils/webrtc/simplewebrtc/getscreenmedia.js
* Used for https://github.com/nextcloud/talk-desktop/pull/595
> desktop: add screen sharing support

- src/components/CallView/CallView.vue
- src/components/MediaSettings/MediaSettings.vue
- src/components/TopBar/TopBar.vue
- src/components/TopBar/TopBarMediaControls.vue
- src/components/TopBar/TopBarMenu.vue
- src/utils/webrtc/SentVideoQualityThrottler.js
- src/utils/webrtc/SpeakingStatusHandler.js
- src/utils/webrtc/analyzers/CallAnalyzer.js
- src/utils/webrtc/models/CallParticipantCollection.js
- src/utils/webrtc/models/LocalCallParticipantModel.js
- src/utils/webrtc/models/LocalMediaModel.js
* Fix #9450
Components affected
---
> chore: define explicit reactivity for webrtc models

- src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
- regression from  #11876
Both screenshots have last read message is the last system message shown
-- | --
TO-DO next:
> fix(MessagesSystemGroup): Follow-up correct collapsed property 
